In [1]:
api_string = """# API

Users can submit and obtain predictions using the AlloPockets API, through the streamlined `gradio_client` Python (or JavaScript) package, or with classic command-line API querying methods.

## gradio_client package

### i. Input

To submit a structure for prediction, users can provide one of `PDB ID` (or `UniProt ID`) or a path to a local protein structure file (using `gradio_client`’s `handle_file`), in addition to a selection of protein chains to run the calculations on.

```python
from gradio_client import Client, handle_file

client = Client(http://127.0.0.1:8998/, download_files="my_path")

jobid, resultsZIP = client.predict(
    pdb={"text":"<PDB or UP ID>", "files":[handle_file("<file>")]},
    chainid="<list of chains>",
    api_name="/predict"
)
```

- `pdb` (dictionary): One of `PDB ID` (or `UniProt ID`) or a path to a local protein structure file, in a dictionary structure.  
  Example `PDB ID`: `pdb={"text":"6t4k", "files":[]}`  
  Example file: `pdb={"text":"", "files":[handle_file("/path/to/file.pdb")]}`  

- `chainid` (string): Comma-separated list of the desired protein chain IDs (`label_asym_id`) of the structure to run predictions on.  
  Example: `chainid="A,B"`

### ii. Output

- `jobid` (string): Unique Job ID of the calculations, which can be used to explore results on the website as well.  
- `resultsZIP` (string): Local path where the `.zip` file containing the prediction results has been downloaded into. Default is `/tmp`, and it can be changed by specifying a download path as `download_files="path"` in the `Client()` object initialization. The contents can be extracted to an output folder with:

```python
import zipfile

with zipfile.ZipFile(resultsZIP, "r") as f:
    f.extractall("<output folder>")
```

---

## cURL

### i. Input

To submit a structure for prediction using `cURL`, users can use the call below providing inside `data` one of `PDB ID` (or `UniProt ID`) or a path to a local protein structure file, in addition to a selection of protein chains to run the calculations on.

The first and second arguments in `data` correspond to the `pdb` and `chainid` arguments, respectively, in the `gradio_client` call.

```bash
curl -s -X POST http://127.0.0.1:8998/gradio_api/call/predict \
  -H "Content-Type: application/json" \
  -d '{
    "data": [
      {"text":"<PDB or UP ID>", "files":[handle_file("<file>")]},
      "<list of chains>"
    ]
  }' \
| awk -F'"' '{print $4}' \
| xargs -I{} curl -N http://127.0.0.1:8998/gradio_api/call/predict/{}
```

### ii. Output

The command waits until the results are returned, which take the following form:

```
data: [
	########################################################
	"8aq6-G-2025-09-15-18-15-48-121954--8051716171144663973",
	########################################################
	{
		"path": "/tmp/gradio/499b2b5c044dd095babc8cef1c64c728978b6d2bfb84feb3c968c88913eadab4/8aq6-G-2025-09-15-18-15-48-121954--8051716171144663973.zip",
		########################################################
		"url": "http://127.0.0.1:8998/gradio_api/file=/tmp/gradio/499b2b5c044dd095babc8cef1c64c728978b6d2bfb84feb3c968c88913eadab4/8aq6-G-2025-09-15-18-15-48-121954--8051716171144663973.zip",
		########################################################
		"size": null,
		"orig_name": "8aq6-G-2025-09-15-18-15-48-121954--8051716171144663973.zip",
		"mime_type": null,
		"is_stream": false,
		"meta": {"_type": "gradio.FileData"}
		}
]
```

Highlighted are the `Job ID`, and the `URL` to download the `.zip` file containing all results, respectively."""

#### Import

In [2]:
import os, re, subprocess, datetime, contextlib, gzip, shutil, tempfile, json, requests, traceback
import pandas as pd
import molviewspec as mvs
import gradio as gr

from predict import \
get_cif, Cif, CifFileWriter, get_clean_pdb, \
Pocket, get_pockets, get_pockets_features, \
get_pdb_features, prepare_data, model, \
get_unfiltered_pathways, get_filtered_pathways, paultol_palette

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/autogluon/common/utils/utils.py:78: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/Bio/Application/__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(

In [3]:
os.makedirs("gradio", exist_ok=True)

#### Databases

In [4]:
from playhouse.apsw_ext import APSWDatabase, Model, TextField, CompositeKey

In [5]:
db = APSWDatabase('gradio/allopockets.db')

In [6]:
class BaseModel(Model):
    class Meta:
        database = db

class Structure(BaseModel):
    pdb_id = TextField()
    chains = TextField()
    workdir = TextField()
    
    class Meta:
        primary_key = CompositeKey('pdb_id', 'chains')

class Job(BaseModel):
    jobid = TextField(primary_key=True)
    pdb_id = TextField()
    chains = TextField()
    workdir = TextField()
    state = TextField(null=True) # NULL=running, "OK"=done, else error message

# Initialize tables
db.connect()
db.create_tables([Structure, Job])

In [7]:
pd.DataFrame(list(Structure.select().dicts()))

,pdb_id,chains,workdir
0,6jpa,C,gradio/6jpa/6jpa-C-2025-07-29-13-45-51-725726-...
1,2ldr,A,gradio/2ldr/2ldr-A-2025-07-29-13-50-02-571655-...
2,6jpa_testciffrompdb_1800427881535255,B,gradio/6jpa_testciffrompdb_1800427881535255/6j...
3,6jpa_testciffrompdb_7903216909225615,B,gradio/6jpa_testciffrompdb_7903216909225615/6j...
4,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...
5,1sl6,A,gradio/1sl6/1sl6-A-2025-08-07-18-11-25-102719-...
6,2it6,A,gradio/2it6/2it6-A-2025-08-12-11-48-15-042722-...
7,7nl6,A,gradio/7nl6/7nl6-A-2025-08-12-11-53-10-201292-...
8,8v81,A,gradio/8v81/8v81-A-2025-08-27-14-16-04-043665-...
9,2ldo,A,gradio/2ldo/2ldo-A-2025-09-01-12-20-51-000190-...
10,2ldm,A,gradio/2ldm/2ldm-A-2025-09-01-12-23-28-902515-...
11,2bz8,A,gradio/2bz8/2bz8-A-2025-09-01-12-26-23-336794-...
12,2lds,A,gradio/2lds/2lds-A-2025-09-01-12-35-27-147221-...
13,2jnh,A,gradio/2jnh/2jnh-A-2025-09-01-12-39-28-455131-...
14,8aq6,B,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...
15,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...
16,8aq6,H,gradio/8aq6/8aq6-H-2025-09-01-13-11-00-659616-...
17,8aq6,E,gradio/8aq6/8aq6-E-2025-09-01-13-24-06-723562-...
18,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...
19,2ldr_4356269585626460629,A,gradio/2ldr_4356269585626460629/2ldr_435626958...
20,6t4k,A,gradio/6t4k/6t4k-A-2025-09-16-12-22-01-638406-...

In [8]:
pd.DataFrame(list(Job.select().dicts()))

,jobid,pdb_id,chains,workdir,state
0,8aq6-H-2025-09-01-13-23-50-686780-65dthcsasvk,8aq6,H,gradio/8aq6/8aq6-H-2025-09-01-13-11-00-659616-...,OK
1,8aq6-E-2025-09-01-13-24-06-723562-65dthcsasvk,8aq6,E,gradio/8aq6/8aq6-E-2025-09-01-13-24-06-723562-...,OK
2,"7snx-A,B-2025-09-01-13-27-15-572345-hp8vybhq7rl",7snx,"A,B","gradio/7snx/7snx-A,B-2025-09-01-13-27-15-57234...","Traceback (most recent call last):\n File ""/t..."
3,8aq6-D-2025-09-01-14-05-28-223609-1lqg6ou96n4,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
4,8aq6-D-2025-09-04-14-07-54-033596--76984688373...,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
5,8aq6-D-2025-09-04-14-30-01-466052--76984688373...,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
6,8aq6-D-2025-09-04-14-34-23-483627--76984688373...,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
7,8aq6-D-2025-09-04-16-37-18-463937--76984688373...,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
8,8aq6-D-2025-09-04-16-38-02-053820--76984688373...,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
9,8aq6-D-2025-09-04-18-37-46-901660--76984688373...,8aq6,D,gradio/8aq6/8aq6-D-2025-09-01-14-05-28-223609-...,OK
10,8aq6-A-2025-09-06-19-16-25-973994-762472376913...,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
11,8aq6-A-2025-09-06-19-35-09-560864-762472376913...,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
12,8aq6-A-2025-09-06-19-36-57-177600-762472376913...,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
13,2ldr_4356269585626460629-A-2025-09-06-19-41-43...,2ldr_4356269585626460629,A,gradio/2ldr_4356269585626460629/2ldr_435626958...,OK
14,8aq6-G-2025-09-06-20-01-55-530998-695107979553...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
15,af-p51449-f1-A-2025-09-06-20-02-43-747123--630...,af-p51449-f1,A,gradio/af-p51449-f1/af-p51449-f1-A-2025-09-06-...,"Traceback (most recent call last):\n File ""/t..."
16,8aq6-G-2025-09-06-20-04-27-329385--44848234353...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
17,8aq6-G-2025-09-06-20-07-21-798057-ytr66i8vqqj,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
18,8aq6-G-2025-09-06-20-12-27-403141--12835948002...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
19,8aq6-G-2025-09-06-20-13-09-804267--12835948002...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
20,8aq6-G-2025-09-06-20-13-34-471315--12835948002...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
21,8aq6-G-2025-09-06-20-13-44-708930--12835948002...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
22,8aq6-A-2025-09-06-20-19-37-512271-yaewbz74gx,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
23,8aq6-B-2025-09-06-20-20-07-573436-qyj6xjni6ke,8aq6,B,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
24,8aq6-G-2025-09-06-20-20-37-634554-hrt3x124v7f,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
25,8aq6-A-2025-09-06-21-21-31-479662-87434te0143,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
26,8aq6-B-2025-09-06-21-21-33-255409-tp38fzz17r,8aq6,B,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
27,8aq6-G-2025-09-06-21-21-34-769753-6ofalg405av,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
28,8aq6-G-2025-09-06-21-24-12-424347-lneergfdnu,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
29,8aq6-G-2025-09-06-21-28-14-585185-nm8cvu5325k,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
30,8aq6-G-2025-09-06-21-32-49-546915--70471748155...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
31,6t4k-A-2025-09-07-23-49-11-831541-ime5th124nk,6t4k,A,gradio/6t4k/6t4k-A-2025-09-07-23-49-11-831541-...,"Traceback (most recent call last):\n File ""/t..."
32,8aq6-A-2025-09-07-23-56-37-893204-ime5th124nk,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
33,8aq6-G-2025-09-07-23-56-50-812452-ime5th124nk,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
34,8aq6-A-2025-09-08-00-06-23-934960-qcasbnnmox,8aq6,A,gradio/8aq6/8aq6-B-2025-09-01-12-43-21-464580-...,OK
35,8aq6-G-2025-09-08-00-06-33-892601-qcasbnnmox,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
36,6jpa-C-2025-09-08-00-07-00-624887-qcasbnnmox,6jpa,C,gradio/6jpa/6jpa-C-2025-07-29-13-45-51-725726-...,OK
37,8aq6-G-2025-09-08-14-07-17-394857--97619964557...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
38,8aq6-G-2025-09-15-18-02-59-284205--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
39,8aq6-G-2025-09-15-18-03-17-819126--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
40,8aq6-G-2025-09-15-18-03-34-243827--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
41,8aq6-G-2025-09-15-18-05-16-704454--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
42,8aq6-G-2025-09-15-18-05-28-177851--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
43,8aq6-G-2025-09-15-18-05-40-422926--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
44,8aq6-G-2025-09-15-18-05-56-482951--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
45,8aq6-G-2025-09-15-18-08-16-436897--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
46,8aq6-G-2025-09-15-18-08-20-124779--57747877789...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
47,8aq6-G-2025-09-15-18-15-48-121954--80517161711...,8aq6,G,gradio/8aq6/8aq6-G-2025-07-31-13-05-37-586371-...,OK
48,6t4k-A-2025-09-16-12-22-01-638406-kc3dmkv4oqc,6t4k,A,gradio/6t4k/6t4k-A-2025-09-16-12-22-01-638406-...,OK
49,6t4k-A-2025-09-22-18-58-34-845459-dyx7f7cuol,6t4k,A,gradio/6t4k/6t4k-A-2025-09-16-12-22-01-638406-...,OK

#### MVS

In [9]:
mvs_pre, mvs_post = mvs.molstar_widgets.VIEWER_TEMPLATE.replace("{{version}}", "latest").replace("{{format}}", "mvsx").split("{{state}}")

def get_mvs(pdb, pdbdir=None):
    if type(pdb) == str:
        with open(f"{pdbdir}/{pdb}_updated.cif.gz", "rb") as f:
            ciftext = gzip.decompress(f.read())
    else:
        ciftext = pdb.cif.text.encode()
    builder = mvs.create_builder()
    structure = (
        builder
        .download(url="cif")
        .parse(format="mmcif")
        .model_structure()
    )
    assets = {'cif': ciftext}
    return builder, structure, assets

def get_mvsData(state, assets):
    mvsx = (
        mvs.MVSX(
            data=state,
            assets=assets
        )
        .molstar_html()
        .removeprefix(mvs_pre).removesuffix(mvs_post)
    )[1:-1] # delete initial and trailiing "
    return mvsx

view = """
(mvs_data) => {
    const mvsData = mvs_data;

    molstar.Viewer
        .create('viewer1', { layoutIsExpanded: false, layoutShowControls: false })
        .then(viewer => viewer.loadMvsData(mvsData, 'mvsx'));
}
"""

#### Process PDB

In [10]:
def process_pdb(pdb, request:gr.Request, **kwargs):
    if ( pdb["text"] != "" and len(pdb["files"]) > 0 ):
        raise gr.Error("Submit only a PDB ID or a file")
    elif ( pdb["text"] == "" and len(pdb["files"]) == 0 ):
        raise gr.Error("Submit either a PDB ID or a file")

    if pdb["text"] != "":
        pdb_id = pdb["text"].lower()
        
        if re.fullmatch(r"[0-9a-z]{4}", pdb_id):
            try:
                pdbdir = f"gradio/{pdb_id}"
                cif = get_cif(pdb_id=pdb_id, path=pdbdir)
            except:
                os.remove(f"{pdbdir}/{pdb_id}_updated.cif.gz")
                raise gr.Error(f"{pdb_id} PDB ID could not be retrieved")
                
        else:
            try:
                pdb_id = f"AF-{pdb_id}-F1".lower()
                pdbdir = f"gradio/{pdb_id}"
                os.makedirs(pdbdir, exist_ok=True)
                
                pdbf = f"{pdb_id.upper()}-model_v4.cif"
                response = requests.get(
                    f"https://alphafold.ebi.ac.uk/files/{pdbf}"
                )
                if response.status_code == 404:
                    raise gr.Error(f"{pdb_id.upper()} AlphaFold model for UniProt ID could not be retrieved")
                
                with open(pdbf, "w") as f:
                    f.write(response.content.decode())
                cif = get_cif(file=pdbf, name=pdb_id, path=pdbdir)
                    
                gr.Info(f"Obtained structural model for UniProt ID from EMBL-EBI AlphaFold PDB")
            except:
                shutil.rmtree(pdbdir)
                raise gr.Error(f"{pdb_id} PDB ID could not be retrieved")
                
            
    elif len(pdb["files"]) > 0:
        pdbf = pdb["files"][0]
        fname, fext = pdbf.rsplit('/', 1)[-1].split('.', 1)
        if request:
            seshash = str(request.session_hash)
        else:
            seshash = str(hash(( (k, tuple(v)) for k, v in pdb.items() )))
        name = '_'.join((
            fname.replace(" ", "_"),
            str(hash((str(datetime.datetime.now()) + seshash)))
        ))[:36] # character limit for fpocket not to fail
        pdbdir = f"gradio/{name}"
        os.makedirs(pdbdir, exist_ok=True)
        shutil.copyfile(pdbf, f"{pdbdir}/{name}.{fext}")
        cif = get_cif(file=f"{pdbdir}/{name}.{fext}", name=name, path=pdbdir)
        pdb_id = name
            
            
    chains = cif.residues.query(f"label_entity_id in {cif._protein_entities}").label_asym_id.unique().tolist()

    builder, structure, assets = get_mvs(cif)
    structure.component(selector="polymer").representation().color(custom=dict(molstar_use_default_coloring=True))
    structure.component(selector="ligand").representation().color(custom=dict(molstar_color_theme_name="element-symbol"))
    structure.component(selector="ion").representation().color(custom=dict(molstar_color_theme_name="element-symbol")) #, molstar_size_theme_name="physical"))
    mvsx = get_mvsData(builder.get_state(), assets)

    if "api" in kwargs and kwargs["api"]:
        return (
            {"text": pdb_id, "files": pdb["files"]}, pdbdir, chains
        )
    else:
        return (
            gr.update(value={"text": pdb_id, "files": pdb["files"]}), gr.update(value=pdbdir), gr.update(value=None, choices=chains, visible=True, interactive=True), gr.update(value=mvsx),
            gr.update(visible=True), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)
        )

#### Predictions

In [11]:
jobid_md = lambda jobid: f"**Job ID:** `{jobid}`<br>Save this ID to retrive the results later."

In [12]:
def get_jobid(pdb, chains, request:gr.Request):
    pdb_id = pdb["text"]
    chain_ids = ",".join(sorted(chains))
    
    if request:
        seshash = str(request.session_hash)
    else:
        seshash = str(hash((pdb_id, tuple(chains), pdbdir)))
    jobid = '-'.join((
        pdb_id, chain_ids, re.sub(r'\D', '-', str(datetime.datetime.now())), seshash
    ))
    if pdb_id.startswith("af") or len(pdb_id) == 4:
        workdir = Structure.get_or_none(Structure.pdb_id == pdb_id, Structure.chains == chain_ids)
        if workdir is not None:
            workdir = workdir.workdir
            Job.create(jobid=jobid, pdb_id = pdb_id, chains = chain_ids, workdir=workdir, state="OK")
    else:
        workdir = None

    return jobid, gr.update(value=jobid_md(jobid), visible=True), workdir


def get_predictions(pdb, chains, jobid, workdir, pdbdir, local_storage, request:gr.Request, prog=gr.Progress()):
    pdb_id = pdb["text"]
    chain_ids = ",".join(sorted(chains))
        
    if workdir is None:
        path = f"{pdbdir}/{jobid}"
        Job.create(jobid=jobid, pdb_id = pdb_id, chains = chain_ids, workdir=path)
        try:
            workdir = path
            os.makedirs(path, exist_ok=True)
            with open(f"{path}/predictions.log", 'w') as f, contextlib.redirect_stdout(f), contextlib.redirect_stderr(f):
                # subprocess.run(f"cp gradio/pphf19lz5bb/6t4k_1.*m {path}/", shell=True)
                # os.makedirs(f"{path}/features/{pdb_id}", exist_ok=True)
                # subprocess.run(f"cp gradio/pphf19lz5bb/features/6t4k/*.pkl {path}/features/6t4k/", shell=True)
                # subprocess.run(f"rm {path}/features/6t4k/PyRosettaF.pkl", shell=True)
                steps = 7
                i = 0; prog((i,steps), "Processing PDB")
                
                Cif.path = pdbdir
                Cif.original_cifs_path = pdbdir
                pdb = Cif(pdb_id, filename=f"{pdbdir}/{pdb_id}_updated.cif.gz")
                os.symlink(f"../{pdb_id}_updated.cif.gz", f"{path}/{pdb_id}_updated.cif.gz")
                clean_pdb = get_clean_pdb(
                    pdb,
                    protein_chains=chains,
                    path=path
                )
            
                # Pockets
                i += 1; prog((i,steps), "Running Fpocket")
                pockets = get_pockets(
                    clean_pdb,
                    path=path,
                    out=f
                )
                pockets["pdb"] = pdb_id
        
                
                # os.makedirs(f"{path}/features/{pdb_id}", exist_ok=True)
                # subprocess.run(f"cp gradio/2ldr/A-2025-07-10-23-55-47-8052518mqp29otf48/features/2ldr/*.pkl {path}/features/{pdb_id}/", shell=True)
                for feat in ['features', 'transferentropy', 'hhblits']:
                    i += 1; prog((i,steps), "Calculating features")
                    subprocess.run(f"python gradio/{feat}.py {pdb_id} {path}", shell=True, check=True, stdout=f, stderr=f)
                
                i += 1; prog((i,steps), "Processing features")
                features = get_pdb_features(
                    clean_pdb,
                    sites = [pd.DataFrame(columns=clean_pdb.residues.columns),],
                    features_path = path
                )
            
                pockets_features = get_pockets_features(
                    clean_pdb,
                    pockets,
                    features,
                    path=path
                )
            
                i += 1; prog((i,steps), "Retrieving predictions")
                preds = model.predict_proba(prepare_data(pockets_features))[[1]].sort_values(1, ascending=False).rename(columns={1: "Allosteric score"})
                preds.index = preds.index.map(lambda x: x.split("_")[-1])
                predictions = preds.reset_index(names="Pocket")
                predictions = predictions.assign(
                    Residues = predictions.Pocket.apply(
                        lambda pocket: " - ".join((
                            "{chain}: {residues}".format(
                                chain=chain,
                                residues=', '.join((
                                    f'{res}:{resnum}' 
                                    for res, resnum in (
                                        chainres[['label_comp_id', 'label_seq_id']]
                                        .sort_values('label_seq_id', key=lambda x: x.astype(int))
                                        .to_numpy())
                                ))
                            )
                            for chain, chainres in Pocket(f"{workdir}/{pdb_id}/{pdb_id}_out/pockets/{pocket}_atm.cif").residues.groupby("label_asym_id")
                        ))
                    )
                )
                
                predictions.to_csv(f"{path}/predictions.csv", index=False)
        except Exception:
            errstr = traceback.format_exc()
            Job.update({Job.state: errstr}).where(Job.jobid == jobid).execute()
            raise gr.Error(errstr)
            
        if pdb_id.startswith("af") or "-" not in pdb_id:
            structure = Structure.create(pdb_id = pdb_id, chains = chain_ids, workdir=path)
        # Job.create(jobid=jobid, pdb_id = pdb_id, chains = chain_ids, workdir=path)
        Job.update({Job.state: "OK"}).where(Job.jobid == jobid).execute()
    else:
        prog((1,1), "Retrieving results from cache")
        predictions = pd.read_csv(f"{workdir}/predictions.csv", index_col=None)
    
    local_storage.append((pdb_id, chain_ids, jobid))
    return (
        predictions,
        jobid,
        workdir,
        local_storage
    )

#### Pocket viz

In [13]:
def get_chain_choices(pdb_id, workdir):
    Cif.path = workdir
    Cif.original_cifs_path = workdir
    cif = Cif(pdb_id, filename=f"{workdir}/{pdb_id}_updated.cif.gz")
    return cif.residues.query(f"label_entity_id in {cif._protein_entities}").label_asym_id.unique().tolist()

In [14]:
def get_pocket_mvs(pdb, chain, pdbdir, workdir, pocketrow):
    pdb_id = pdb["text"]

    all_chains = get_chain_choices(pdb_id, workdir)
    
    builder, structure, assets = get_mvs(pdb_id, pdbdir=pdbdir)
    proteins = (
        structure
        .component(selector=[
            mvs.ComponentExpression(**{"label_asym_id": c})
            for c in chain
        ])
        .focus()
        .representation(type="cartoon")
        .color(color='#BFBFBF')
    )
    (
        structure
        .component(selector=[
            mvs.ComponentExpression(**{"label_asym_id": c})
            for c in all_chains
            if c not in chain
        ])
        .representation(type="cartoon")
        .color(color='white')
        .opacity(opacity=0.5)
    )
    (
        structure
        .component(selector="ligand")
        .representation()
        .color(
            custom={
                "molstar_color_theme_name": "element-symbol",
                "molstar_color_theme_params": {
                    "carbonColor": { "name": "uniform", "params": {"value": int("#808080".replace('#', ''), 16)} }
                }
            }
        )
    )
    (
        structure
        .component(selector="ion")
        .representation()
        .color(custom={"molstar_color_theme_name": "element-symbol"})
    )

    annos = f'annos_pocketres.json'
    assets[annos] = json.dumps(
        [
            {'label_asym_id': r["label_asym_id"], 'label_seq_id': int(r["label_seq_id"]), 'color': 'black'}
            for i, r in Pocket(f"{workdir}/{pdb_id}/{pdb_id}_out/pockets/{pocketrow['Pocket']}_atm.cif").residues.iterrows()
        ]
    ).encode()
    proteins.color_from_uri(uri=annos, format='json', schema='all_atomic')

    
    pockets = (
        builder
        .download(url="pocketscif")
        .parse(format="mmcif")
        .model_structure()
    )
    (
        pockets
        .component(selector=mvs.ComponentExpression(**{
            "label_comp_id": "STP", 
            "label_seq_id": pocketrow["Pocket"].replace("pocket", "")
        }))
        .representation(type="surface")#, custom={"ignoreLight": True})
        .color(color="black")
        .opacity(opacity=0.25)
    )

    with open(f"{workdir}/{pdb_id}/{pdb_id}_out/{pdb_id}_out.cif", "r") as f:
        assets.update({'pocketscif': f.read().encode()})

    return builder, structure, assets


def view_pocket(pdb, chain, pdbdir, workdir, predictions, selected):  
    selected = selected[-1]
        
    pdb_id = pdb["text"]
    pocketrow = predictions.iloc[selected]
    
    builder, structure, assets = get_pocket_mvs(pdb, chain, pdbdir, workdir, pocketrow)
        
    return get_mvsData(
        builder.get_state(
            description = f"""
**{pdb_id}**

**{pocketrow['Pocket']}**: black

{pocketrow['Residues']}
"""), 
            assets
        )

#### Networks

In [15]:
networkd = {"Dynamical Cross-Correlation": "correlationplus", "Perturbation Response Scanning": "prs"}

In [16]:
def calculate_pathways(pdb, path, network, selected, predictions):
    pdb_id = pdb["text"]
    network = networkd[network]
    selected = selected[-1]
    
    source_pocket = predictions.iloc[selected]["Pocket"]
    networkf = f"{path}/{pdb_id}/{network}_{source_pocket}.pkl"
    
    if not os.path.isfile(networkf):
        Cif.path = path
        Cif.original_cifs_path = path
        pdb = Cif(pdb_id)
    
        get_unfiltered_pathways(
            pdb,
            network,
            networkf,
            source_pocket,
            path=path
        )

In [17]:
def view_pathways(pdb, chain, path, network, selected, predictions, pathway_dist_threshold, top_pathways):
    pdb_id = pdb["text"]
    selected = selected[-1]
    pocketrow = predictions.iloc[selected]
    
    builder, structure, assets = get_pocket_mvs(pdb, chain, path, path, pocketrow)
    
    
    network = networkd[network]
    source_pocket = pocketrow["Pocket"]
    networkf = f"{path}/{pdb_id}/{network}_{source_pocket}.pkl"

    Cif.path = path
    Cif.original_cifs_path = path
    pdb = Cif(pdb_id)

    try:
        pathwaysdf = get_filtered_pathways(
            pdb,
            network,
            networkf,
            source_pocket,
            pathway_dist_threshold,
            top_pathways,
            path=path
        )
    except ValueError:
        raise gr.Error(f"No pathways were selected for representation, try lowering the minimum distance threshold between residues")

    
    pathways = (
        builder
        .download(url="pathwayscif")
        .parse(format="mmcif")
        .model_structure()
    )
    with tempfile.NamedTemporaryFile("w+", suffix=".cif") as f:
        writer = CifFileWriter(f.name)
        writer.write({'pathways': {
            "_atom_site": pathwaysdf.to_dict(orient="list"),
        }})
        assets.update({'pathwayscif': f.read().encode()})
    
    for (p, patoms), (colorname, colorcode) in zip(pathwaysdf.groupby("label_asym_id", sort=False), paultol_palette):
        pathwaysdf.loc[lambda x: x["label_asym_id"] == p, "color"] = colorname
        for i, atom in patoms.iloc[:-1].iterrows():
            (
                pathways.primitives(opacity=0.9)
                .ellipsoid(
                    center = {"label_asym_id": p, "label_seq_id": int(atom["label_seq_id"])}, 
                    color = colorcode, radius = 0.5,
                    tooltip = ":".join((atom["auth_asym_id"], atom["auth_comp_id"], atom["auth_seq_id"] + atom['pdbx_PDB_ins_code'].replace('?', ''))),
                )
                .tube(
                    start = {"label_asym_id": p, "label_seq_id": int(atom["label_seq_id"])}, 
                    end = {"label_asym_id": p, "label_seq_id": int(atom["label_seq_id"])+1},
                    color = colorcode, radius = 0.25,
                    tooltip = f"{p}: {patoms['occupancy'].unique().item()}"
                )
            )
        atom = patoms.iloc[-1]
        pathways.primitives(opacity=0.9).ellipsoid(
            center = {"label_asym_id": p, "label_seq_id": int(atom["label_seq_id"])}, 
            color = colorcode, radius = 0.5,
            tooltip = ":".join((atom["auth_asym_id"], atom["auth_comp_id"], atom["auth_seq_id"] + atom['pdbx_PDB_ins_code'].replace('?', ''))),
        )
    
    
    paths = pd.DataFrame((
        {
            "Pathway": p,
            "Color": patoms["color"].unique().item(),
            "Path length": patoms["occupancy"].unique().item(),
            "Residues": " - ".join((
                "{chain}: {residues}".format(
                    chain=chain,
                    residues=', '.join((
                        f"{res}:{resnum}{inscode.replace('?', '')}"
                        for res, resnum, inscode in (
                            chainres[['auth_comp_id', 'auth_seq_id', 'pdbx_PDB_ins_code']]
                            .to_numpy())
                    ))
                )
                for chain, chainres in patoms.groupby("auth_asym_id")
            ))
        }
        for p, patoms in pathwaysdf.groupby("label_asym_id", sort=False)
    ))

        
    return get_mvsData(
        builder.get_state(
            description = f"""
**{pdb_id}**

**{pocketrow['Pocket']}**: black

{pocketrow['Residues']}
"""), 
        assets
    ), paths

#### App

In [23]:
try:
    demo.close()
except NameError:
    pass

with gr.Blocks(
    title="AlloPockets",
    fill_height = True,
    head="""
        <script src="https://cdn.jsdelivr.net/npm/molstar@latest/build/viewer/molstar.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/molstar@latest/build/viewer/molstar.css" />
    """
) as demo:
    navbar = gr.Navbar(
        value=[
            ("Tutorial", "tutorial"),
            ("Manual", "gradio_api/file=gradio/Manual.pdf"),
            ("API", "api"),
            ("GitHub", "https://github.com/frannerin/AlloPockets")
        ], 
        main_page_name="AlloPockets", visible=True
    )
    
    ########################################################### LAYOUT ###########################################################
    with gr.Sidebar(width=500): # with gr.Column(min_width=375):
        gr.Markdown("# AlloPockets")
        pdb = gr.MultimodalTextbox(
            label="PDB or UniProt ID or upload a structure file:", placeholder="e.g, 6t4k or P51449", max_lines=1,
            sources="upload", file_types=[".pdb", ".cif", ".cif.gz"],
        )
        chain_id = gr.CheckboxGroup(label="Select the desired chain ID(s):", info="(label_asym_id)", choices=[], visible=False)
        predict_btn = gr.Button("Predict allosteric pockets", visible=False, variant="primary")
        cur_jobid = gr.Markdown("", visible=False)
        predictions = gr.Dataframe(
            label="Predicted allosteric pockets (click to view)", # info="Click a row to display the pocket",
            visible=False, interactive=False, #datatype="markdown",
            show_copy_button=True, max_height=200, show_row_numbers=True
        )

        with gr.Accordion(label="ALLOSTERIC PATHWAYS", open=False, visible=False) as networks:
            gr.Markdown(
                """View the allosteric pathways originating from the predicted pocket towards spatially distant residues in the structure.

The allosteric network can be chosen between [correlationplus](https://github.com/tekpinar/correlationplus#cite) (Dynamical Cross-Correlation from Elastic Network Models) or ProDy's [Perturbation Response Scanning](http://www.bahargroup.org/prody/tutorials/prs_tutorial/intro.html#how-to-cite). Acknowledge them appropriately. The shortest paths between residues of the source pocket and other spatially distant residues (given a distance threshold) are calculated using [NetworkX](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra.html) with Dijkstra’s algorithm."""
           )
            network = gr.Radio(
                label="Choose an allosteric network to calculate pathways:",
                choices=("Dynamical Cross-Correlation", "Perturbation Response Scanning")
            )
            network_btn = gr.Button("Calculate allosteric pathways", variant="primary", interactive=False)
            pathway_dist_threshold = gr.Slider(label="Minimum distance (Å) between pocket residues and target residues", value=20, minimum=1, step=1, visible=False)
            top_pathways = gr.Slider(label="Number of pathways to visualize", value=5, minimum=1, maximum=21, step=1, visible=False)
            pathways = gr.DataFrame(label="Pathways", show_copy_button=True, show_row_numbers=True, interactive=False, visible=False)

        # selected pocket, 
        # pathway_dist_threshold=20, # Minimum distance between residues to calculate paths from
        # n_top_pathways=10,
        
        download_btn = gr.DownloadButton("Download results files", visible=False, variant="secondary")
        
        with gr.Accordion(label="Job history", open=False, visible=True):
            history = gr.Dataframe([], label="Job history (click to load previous job)", headers=["PDB ID", "Chain ID(s)", "Job ID"], visible=False, interactive=False, show_copy_button=True)
            selected_jobid = gr.Textbox(
                placeholder="Enter Job ID", interactive=True, max_lines=1, 
                show_label=False, autoscroll=False, submit_btn=True, container=True
            )
    
    # with gr.Column(scale=100): #scale=10
    viewer = gr.HTML('<div id="viewer1" style="width: 100%; height: 750px;"></div>')

    

    ########################################################### INITIAL ###########################################################
    # Invisible elements
    local_storage = gr.BrowserState([])
    mvsx = gr.Text(value="", interactive=False, visible=False)
    pdbdir = gr.Text(value="", interactive=False, visible=False)
    selected = gr.State() # Selected predictions row index/pocket

    # Upon first loading
    demo.load(
        fn=None, inputs=mvsx, js=view
    ).success( # thid does not really work because browserstate seems to reinitialize
        fn=lambda local_storage: local_storage if len(local_storage) > 0 else gr.skip(),
        inputs=local_storage,
        outputs=history,
        api_name=False
    )
    
    # Update everything when PDB ID is changed    
    pdb.submit(
        fn=process_pdb,
        inputs=pdb,
        outputs=[
            # Updated
            pdb, pdbdir, chain_id, mvsx,
            # Visibility
            predict_btn, cur_jobid, predictions, download_btn, networks
        ],
        show_progress="full", show_progress_on=viewer,
        api_name=False
    )
    
    mvsx.change(
        fn=None, inputs=mvsx, js=view
    )

    chain_id.input( ################################################################################## was change
        fn = lambda : [gr.update(visible=True), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)],#, gr.update(value=(workdir, None))],
        # inputs=workdir,
        outputs=[predict_btn, cur_jobid, predictions, download_btn, networks],#, selected],
        js=True, api_name=False
    )
    
    

    
    ########################################################### CALCULATION ###########################################################
    # Invisible elements
    jobid = gr.Text(value="", label="Job ID", interactive=False, visible=False)
    workdir = gr.State()

    # Click on predict button
    predict_btn.click(
        fn=lambda : (gr.update(visible=True)),#, gr.update(visible=True)),
        outputs=(predictions),
        api_name=False
    ).success(
        fn=get_jobid, 
        inputs=[pdb, chain_id], 
        outputs=[jobid, cur_jobid, workdir],
        scroll_to_output=True, show_progress_on=[predict_btn],
        api_name=False
    ).success(
        fn=get_predictions, 
        inputs=[pdb, chain_id, jobid, workdir, pdbdir, local_storage], 
        outputs=[predictions, jobid, workdir, local_storage],
        concurrency_limit=1, concurrency_id="queue",
        scroll_to_output=True, show_progress_on=[predictions, viewer],
        api_name=False
    ).success( # Enable pocket viz and download button
        fn=lambda workdir, jobid: ( 
            (workdir, 0), jobid, gr.update(visible=True, interactive=True), gr.update(visible=True)
        ),
        inputs=[workdir, jobid],
        outputs=(selected, selected_jobid, download_btn, networks),
        api_name=False
    )

    download_btn.click(
        fn=lambda jobid, workdir: shutil.make_archive(f"gradio/{jobid}", 'zip', workdir),
        inputs=[jobid, workdir],
        outputs=download_btn,
        api_name=False
    ).success(
        fn=lambda jobid: os.remove(f"gradio/{jobid}.zip"),
        inputs=jobid,
        api_name=False
    )


    
    ########################################################### HISTORY ###########################################################
    local_storage.change(
        fn = lambda local_storage: gr.update(value=local_storage, visible=True),
        inputs=local_storage,
        outputs=history,
        api_name=False
    )
    

    def load_job(selected_jobid, local_storage):
        job = Job.get_or_none(Job.jobid == selected_jobid)
        if job is None:
            raise gr.Error(f"{selected_jobid} Job ID could not be retrieved")

        if job.state is None:
            raise gr.Error("Job is still running, try again later.")
        elif job.state != "OK":
            raise gr.Error(f"Job failed: {job.state}")

        pdb_id = job.pdb_id
        chainlist = job.chains.split(",")
        
        predictions, jobid, workdir, fake_local_storage = get_predictions(
            {"text": pdb_id}, chainlist, job.jobid, job.workdir, job.workdir, local_storage=[], request=None
        )
        local_storage = list(set( [tuple(i) for i in local_storage] + [(pdb_id, job.chains, jobid),] ))

        chain_choices = get_chain_choices(pdb_id, workdir)

        return (
            {"text": pdb_id},
            gr.update(value = chainlist, choices = chain_choices, visible=True),
            job.workdir, 
            job.workdir,
            gr.update(value=predictions, visible=True),
            jobid,
            jobid_md(jobid),
            local_storage
        )

    
    def from_selected_jobid(history, local_storage, evt: gr.SelectData):
        selected_jobid = history.iloc[evt.index[0]]["Job ID"]
        return load_job(selected_jobid, local_storage)

    history.select(
        fn = from_selected_jobid,
        inputs = [history, local_storage], 
        outputs = [
            pdb, chain_id, workdir, pdbdir, predictions, jobid, cur_jobid, local_storage
        ],
        api_name=False
    ).success( # Enable pocket viz and download button
        fn=lambda workdir, jobid: ( 
            (workdir, 0), jobid, gr.update(visible=True), gr.update(visible=True, interactive=True), gr.update(visible=True)
        ),
        inputs=[workdir, jobid],
        outputs=(selected, selected_jobid, predictions, download_btn, networks),
        api_name=False
    )
        
    selected_jobid.submit(
        fn = load_job,
        inputs = [selected_jobid, local_storage], 
        outputs = [
            pdb, chain_id, workdir, pdbdir, predictions, jobid, cur_jobid, local_storage
        ],
        api_name=False # cancels = chain_id_change, 
    ).success( # Enable pocket viz and download button
        fn=lambda workdir: ( (workdir, 0), gr.update(visible=True), gr.update(visible=True, interactive=True), gr.update(visible=True)
        ),
        inputs = workdir,
        outputs=(selected, predictions, download_btn, networks),
        api_name=False
    )

    

    ########################################################### VIZ ###########################################################
    @gr.on(
        triggers=predictions.select, 
        inputs=workdir,
        outputs=selected, 
        api_name=False
    )
    def get_selected(workdir, evt: gr.SelectData):
        return (workdir, evt.index[0])

    selected.change(
        fn=view_pocket,
        inputs=[pdb, chain_id, pdbdir, workdir, predictions, selected],
        outputs=mvsx,
        show_progress="full", show_progress_on=viewer,
        api_name=False
    )

    selected.change(
        fn = lambda selected: (
            gr.update(interactive=True) if selected is not None else gr.update(interactive=False),
            gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)
        ),
        inputs = selected, 
        outputs = (network_btn, pathway_dist_threshold, top_pathways, pathways),
        api_name=False
    )



    ########################################################### NETWORKS ###########################################################
    network.input(
        fn = lambda : (gr.update(visible=False), gr.update(visible=False), gr.update(visible=False)),
        outputs = (pathway_dist_threshold, top_pathways, pathways),
        js=True, api_name=False
    )
    
    network_btn.click(
        fn = calculate_pathways,
        inputs = [pdb, workdir, network, selected, predictions],
        show_progress_on = [pathways, viewer],
        api_name=False
    ).success(
        fn = lambda : (gr.update(visible=True), gr.update(visible=True), gr.update(visible=True)),
        outputs = (pathway_dist_threshold, top_pathways, pathways),
        api_name=False
    ).success(
        fn = view_pathways,
        inputs = [pdb, chain_id, workdir, network, selected, predictions, pathway_dist_threshold, top_pathways],
        outputs = [mvsx, pathways],
        show_progress_on = [pathways, viewer],
        api_name=False
    )

    gr.on(
        triggers = [pathway_dist_threshold.release, top_pathways.release],
        fn = view_pathways,
        inputs = [pdb, chain_id, workdir, network, selected, predictions, pathway_dist_threshold, top_pathways],
        outputs = [mvsx, pathways],
        show_progress_on = [pathways, viewer],
        api_name=False
    )




    ############################################################# API #############################################################
    # pdb_desc = """A dictionary with keys `text` (string) and `files` (list) where only one must be populated: `text` with a PDB or UniProt ID (e.g., "6t4k" or "P51449"), or `files` with a list with a single item pointing to a .pdb, .cif, or .cif.gz protein structure file (e.g., [handle_file("prot.pdb"),])"""
    # pdbid = gr.MultimodalTextbox(
    #     label="PDB or UniProt ID, or a structure file:", placeholder="e.g, 6t4k or P51449", max_lines=1,
    #     sources="upload", file_types=[".pdb", ".cif", ".cif.gz"],
    #     info = pdb_desc, visible=False
    # )
    
    # chain_desc = """A string with comma-separated protein chain(s) ID(s) (label_asym_id) of the structure to run AlloPockets on (e.g., "A" or "A,B")"""
    chainid = gr.Text(visible=False, label="Selected chain ID(s) (label_asym_id)")#, info=chain_desc)

    # job_desc = """Unique Job ID of results"""
    # job_id = gr.Text(visible=False, info=job_desc)
    
    # download_desc = """Path or URL to the results ZIP archive (gradio_client automatically downloads it to /tmp or to the value set in `Client(**download_files=...**)`)"""
    # download = gr.DownloadButton(download_desc, visible=False, variant="secondary")
    
    dummy = gr.State()
    @gr.on(
        triggers = dummy.change,
        inputs = [pdb, chainid], # [pdbid, chainid],
        outputs = [jobid, download_btn], # [job_id, download],
        # api_name = None,
        show_progress = 'hidden',
        concurrency_limit = 1, concurrency_id = "queue",
    )
    def predict(pdb, chainid):
        """Run AlloPockets on the selected structure and chain(s), and return Job ID and a ZIP with predictions results files."""
        # f"""Run AlloPockets on the selected structure and chain(s), and return predictions as a ZIP archive.
        # Args:
        #     pdbid: {pdb_desc}
        #     chainid: {chain_desc}
        # Returns:
        #     job_id: {job_desc}
        #     download: {download_desc}
        # """
        # # Raises:
        # #     AssertionError: If the API token is not valid.
        # # """
        chainid = chainid.split(",")
        pdb, pdbdir, chains = process_pdb(pdb, request=None, api=True)
        if any(c not in chains for c in chainid):
            raise gr.Error("Supplied chain_id not found in structure.")

        jobid, cur_jobid, workdir = get_jobid(pdb, chainid, request=None)
        predictions, jobid,  workdir, fake_local_storage = get_predictions(pdb, chainid, jobid, workdir, pdbdir, local_storage=[], request=None)
        
        return jobid, shutil.make_archive(f"gradio/{jobid}", 'zip', workdir)



with demo.route("API", "/api", show_in_navbar=False):
    gr.Markdown(api_string, padding=True, header_links=True)

with demo.route("Tutorial", "/tutorial", show_in_navbar=False):
    # gr.Markdown(tutorial_string, padding=True, header_links=True)
    gr.Video(
        value = "gradio/tutorial (1).mp4",
        interactive = False, visible = True,
        autoplay = False, loop = False,
        show_share_button = False, show_download_button = False,
        height = "25", width = str(int(1961/1052*25)),
    # height: The height of the component, specified in pixels if a number is passed, or in CSS units if a string is passed. This has no effect on the preprocessed video file, but will affect the displayed video.
    # width: The width of the component, specified in pixels if a number is passed, or in CSS units if a string is passed. This has no effect on the preprocessed video file, but will affect the displayed video.
    # container: if True, will place the component in a container - providing some extra padding around the border.
    # scale: relative size compared to adjacent Components. For example if Components A and B are in a Row, and A has scale=2, and B has scale=1, A will be twice as wide as B. Should be an integer. scale applies in Rows, and to top-level Components in Blocks where fill_height=True.
    # min_width: minimum pixel width, will wrap if not sufficient screen space to satisfy this value. If a certain scale value results in this Component being narrower than min_width, the min_width parameter will be respected first.
    )







demo.launch(server_port=8998, show_api=True, enable_monitoring=True, show_error=True, allowed_paths=["gradio/Manual.pdf",]) # inline=False, inbrowser=True, enable_monitoring=True

Closing server running on port: 8998
********************************************
* Trying to transpile functions from Python -> JS for performance

* (1/2) <lambda>: ✅
* (2/2) <lambda>: ✅
********************************************

* Running on local URL:  http://127.0.0.1:8998
Monitoring URL: http://127.0.0.1:8998/monitoring/1_TXF4es4dN-Mvk-6bbY0A
* To create a public link, set `share=True` in `launch()`.

93

#### end

In [18]:
import time

In [18]:
from gradio_client import Client, handle_file

In [19]:
client = Client("http://127.0.0.1:8998/", download_files="./hi")
result = client.predict(
        pdb={"text":"8aq6","files":[]}, # handle_file("gradio/2ldr/2ldr-A-2025-07-29-13-50-02-571655-nta5oxepwpm/2ldr.cif")
        chainid="G",
        api_name="/predict"
)
print(result)

Loaded as API: http://127.0.0.1:8998/ ✔
('8aq6-G-2025-09-08-14-07-17-394857--976199645576320792', '/home/fnerin/Desktop/AlloPockets/hi/ce7e93ba9e26d788bec5b9cf52c6e7d1d3f047cd7698eead0c3a6547eb5ce6bd/8aq6-G-2025-09-08-14-07-17-394857--976199645576320792.zip')

In [24]:
curl -X POST http://127.0.0.1:8998/gradio_api/call/predict -s -H "Content-Type: application/json" -d '{
	"data": [
							{"text":"8aq6","files":[]},
							"G"
	]}' \
	| awk -F'"' '{ print $4}'  \
	| read EVENT_ID; curl -N http://127.0.0.1:8998/gradio_api/call/predict/$EVENT_ID

SyntaxError: unterminated string literal (detected at line 2) (3813005529.py, line 2)