In [1]:
import os, pickle
import pandas as pd

In [2]:
import sys
sys.path.append("../../training_data")

In [3]:
from utils.utils import Cif

# Data

In [4]:
with open("../../training_data/7.Extra_set/features.pkl", "rb") as f:
    news = pickle.load(f)

len(news), news

(35,
 {'22mj':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       22mj               1             A           10            A
  1       22mj               1             A           11            A
  2       22mj               1             A           12            A
  3       22mj               1             A           13            A
  4       22mj               1             A           14            A
  ..       ...             ...           ...          ...          ...
  281     22mj               1             A          315            A
  282     22mj               1             A          316            A
  283     22mj               1             A          317            A
  284     22mj               1             A          318            A
  285     22mj               1             A          319            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0            10                 ?     0               0               0  ...
  1            11                 ?     0               0               0  ...
  2            12                 ?     0               0               0  ...
  3            13                 ?     0               0               0  ...
  4            14                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  281         315                 ?     0               0               0  ...
  282         316                 ?     0               0               0  ...
  283         317                 ?     0               0               0  ...
  284         318                 ?     0               0               0  ...
  285         319                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.986917  0.007769  0.005073  0.368567  0.631564  0.322864  0.676893
  1    0.988286  0.007229  0.004779  0.147624  0.852635  0.323761  0.676424
  2    0.985549  0.010859  0.003338  0.216434  0.783497  0.561361  0.438607
  3    0.993781  0.003398  0.002895  0.441964  0.557870  0.406408  0.593780
  4    0.993092  0.003557  0.003099  0.153893  0.846159  0.697372  0.302499
  ..        ...       ...       ...       ...       ...       ...       ...
  281  0.991717  0.008229  0.000000  0.392292  0.607518  0.000000  1.000000
  282  0.997231  0.002858  0.000000  0.250000  0.750019  0.000000  1.000000
  283  0.991717  0.008122  0.000000  0.575545  0.424548  0.000000  1.000000
  284  0.995160  0.004866  0.000000  0.199990  0.799960  1.000000  0.000000
  285  0.994470  0.005648  0.000000  1.000000  0.000000  0.000000  0.000000


         Neff Neff_I Neff_D
  0    13.113  1.100  1.116
  1    13.168  1.108  1.169
  2    13.233  1.202  1.183
  3    13.290  1.063  1.156
  4    13.318  1.046  1.135
  ..      ...    ...    ...
  281  13.477  1.097  1.002
  282  13.413  1.001  1.002
  283  13.390  1.054  1.002
  284  13.146  1.001  1.054
  285  12.625  1.000  0.000

  [286 rows x 174 columns],
  '6s3a':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6s3a               1             A            3            A
  1       6s3a               1             A            4            A
  2       6s3a               1             A            5            A
  3       6s3a               1             A            6            A
  4       6s3a               1             A            7            A
  ..       ...             ...           ...          ...          ...
  204     6s3a               1             A          211            A
  205     6s3a               1             A          212            A
  206     6s3a               1             A          213            A
  207     6s3a               1             A          214            A
  208     6s3a               1             A          215            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0           117                 ?     0               0               0  ...
  1           118                 ?     0               0               1  ...
  2           119                 ?     0               0               0  ...
  3           120                 ?     0               0               0  ...
  4           121                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  204         325                 ?     0               0               0  ...
  205         326                 ?     0               1               0  ...
  206         327                 ?     0               0               0  ...
  207         328                 ?     0               0               0  ...
  208         329                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.982821  0.003105  0.014269  0.255076  0.744839  1.000000  0.000000
  1    0.995850  0.002720  0.001706  0.437392  0.562529  0.468786  0.531080
  2    0.993092  0.004876  0.002345  0.918276  0.081843  0.858565  0.141414
  3    0.996540  0.001631  0.001914  1.000000  0.000000  0.775931  0.223756
  4    0.989657  0.004263  0.005950  1.000000  0.000000  0.323312  0.676893
  ..        ...       ...       ...       ...       ...       ...       ...
  204  0.985549  0.004260  0.009848  0.689203  0.311003  1.000000  0.000000
  205  0.986917  0.002448  0.010761  1.000000  0.000000  0.647970  0.351842
  206  1.000000  0.000000  0.000000  0.000000  0.000000  0.569987  0.430176
  207  0.989657  0.010562  0.000000  0.074894  0.925304  1.000000  0.000000
  208  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


         Neff Neff_I Neff_D
  0     9.807  1.017  1.020
  1     9.769  1.022  1.078
  2     9.899  1.088  1.052
  3    10.146  1.005  1.028
  4    10.372  1.063  1.018
  ..      ...    ...    ...
  204   9.192  1.007  1.008
  205   9.058  1.000  1.010
  206   8.769  0.000  1.027
  207   8.396  1.008  1.006
  208   7.666  0.000  0.000

  [209 rows x 174 columns],
  '6vvq':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6vvq               1             C            9            C
  1       6vvq               1             C           10            C
  2       6vvq               1             C           11            C
  3       6vvq               1             C           12            C
  4       6vvq               1             C           13            C
  ..       ...             ...           ...          ...          ...
  229     6vvq               1             C          246            C
  230     6vvq               1             C          247            C
  231     6vvq               1             C          248            C
  232     6vvq               1             C          249            C
  233     6vvq               1             C          250            C

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0           345                 ?     0               0               0  ...
  1           346                 ?     0               0               0  ...
  2           347                 ?     0               0               0  ...
  3           348                 ?     0               0               0  ...
  4           349                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  229         582                 ?     0               0               0  ...
  230         583                 ?     0               0               0  ...
  231         584                 ?     0               0               0  ...
  232         585                 ?     0               0               0  ...
  233         586                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    1.000000  0.000000  0.000000  0.000000  0.000000  0.518710  0.481297
  1    0.995160  0.004982  0.000000  1.000000  0.000000  0.000000  1.000000
  2    0.973329  0.026388  0.000000  0.797192  0.203063  0.142004  0.857971
  3    0.907519  0.058802  0.033447  1.000000  0.000000  0.000000  1.000000
  4    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
  ..        ...       ...       ...       ...       ...       ...       ...
  229  0.988286  0.006511  0.005321  0.755236  0.245025  0.690159  0.309712
  230  0.997923  0.002219  0.000000  1.000000  0.000000  0.457867  0.541863
  231  0.990343  0.004572  0.005332  0.209352  0.790589  0.705638  0.294431
  232  0.998615  0.001285  0.000000  1.000000  0.000000  0.392564  0.607518
  233  0.983502  0.016504  0.000000  0.508740  0.491070  1.000000  0.000000


         Neff Neff_I Neff_D
  0     5.599  0.000  1.136
  1     5.749  1.014  1.058
  2     5.865  1.083  1.058
  3     5.997  1.251  1.048
  4     6.076  0.000  1.219
  ..      ...    ...    ...
  229  11.566  1.072  1.044
  230  11.508  1.017  1.070
  231  11.461  1.088  1.032
  232  11.399  1.000  1.080
  233  11.250  1.154  1.043

  [234 rows x 174 columns],
  '6on4':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6on4               1             A           30            A
  1       6on4               1             A           31            A
  2       6on4               1             A           32            A
  3       6on4               1             A           33            A
  4       6on4               1             A           34            A
  ..       ...             ...           ...          ...          ...
  212     6on4               1             A          242            A
  213     6on4               1             A          243            A
  214     6on4               1             A          244            A
  215     6on4               1             A          245            A
  216     6on4               1             A          246            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0            30                 ?     0               0               0  ...
  1            31                 ?     0               0               0  ...
  2            32                 ?     0               0               0  ...
  3            33                 ?     0               0               0  ...
  4            34                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  212         242                 ?     0               0               0  ...
  213         243                 ?     1               0               0  ...
  214         244                 ?     1               0               0  ...
  215         245                 ?     1               0               0  ...
  216         246                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.993092  0.002912  0.003928  1.000000  0.000000  0.346758  0.653383
  1    0.981459  0.004005  0.014751  0.098892  0.901250  0.304181  0.695923
  2    0.997231  0.001921  0.001003  0.244346  0.755760  0.514413  0.485654
  3    0.991030  0.004665  0.004254  0.230206  0.770037  0.839731  0.160206
  4    0.999307  0.000487  0.000000  0.111105  0.888843  0.714992  0.284993
  ..        ...       ...       ...       ...       ...       ...       ...
  212  0.996540  0.003226  0.000000  0.687771  0.312516  1.000000  0.000000
  213  0.997231  0.000759  0.002089  1.000000  0.000000  0.000000  0.000000
  214  0.999307  0.000000  0.000667  0.000000  0.000000  1.000000  0.000000
  215  0.997923  0.002357  0.000000  0.392020  0.607940  0.000000  1.000000
  216  0.999307  0.000619  0.000000  0.333325  0.666649  0.000000  1.000000


         Neff Neff_I Neff_D
  0    10.344  1.018  1.094
  1    10.353  1.052  1.139
  2    10.369  1.021  1.327
  3    10.443  1.074  1.163
  4    10.441  1.000  1.085
  ..      ...    ...    ...
  212  11.604  1.033  1.000
  213  11.588  1.000  0.000
  214  11.561  0.000  1.013
  215  11.522  1.026  1.000
  216  11.542  1.000  1.000

  [217 rows x 174 columns],
  '6z1m':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6z1m               1             A            9            A
  1       6z1m               1             A           10            A
  2       6z1m               1             A           11            A
  3       6z1m               1             A           12            A
  4       6z1m               1             A           13            A
  ..       ...             ...           ...          ...          ...
  418     6z1m               1             A          446            A
  419     6z1m               1             A          447            A
  420     6z1m               1             A          448            A
  421     6z1m               1             A          449            A
  422     6z1m               1             A          450            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             9                 ?     0               0               0  ...
  1            10                 ?     0               0               0  ...
  2            11                 ?     0               0               0  ...
  3            12                 ?     0               0               0  ...
  4            13                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  418         446                 ?     0               0               0  ...
  419         447                 ?     0               0               0  ...
  420         448                 ?     0               0               0  ...
  421         449                 ?     0               0               0  ...
  422         450                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.956608  0.036550  0.006973  0.734584  0.265172  0.772175  0.227983
  1    0.963262  0.029998  0.006978  0.416677  0.583175  0.705149  0.294839
  2    0.965936  0.018098  0.016198  0.288771  0.711039  0.458820  0.541112
  3    0.977386  0.011825  0.010739  0.417833  0.581963  0.550571  0.449689
  4    0.988971  0.007759  0.003597  0.297508  0.702709  0.525951  0.474013
  ..        ...       ...       ...       ...       ...       ...       ...
  418  0.996540  0.002905  0.000604  0.644834  0.355027  0.000000  1.000000
  419  0.991030  0.008066  0.000870  0.458502  0.541488  0.595428  0.404721
  420  0.995160  0.004812  0.000000  0.788400  0.211833  0.493458  0.506628
  421  0.992404  0.006853  0.000966  0.652025  0.347962  1.000000  0.000000
  422  0.998615  0.001496  0.000000  1.000000  0.000000  1.000000  0.000000


         Neff Neff_I Neff_D
  0     8.612  1.325  1.027
  1     8.718  1.214  1.045
  2     8.957  1.330  1.066
  3     8.985  1.104  1.178
  4     9.040  1.055  1.212
  ..      ...    ...    ...
  418  10.592  1.022  1.002
  419  10.318  1.065  1.010
  420   9.996  1.023  1.006
  421   9.599  1.040  1.000
  422   9.443  1.000  1.000

  [423 rows x 174 columns],
  '6z74':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6z74               1             A            8            A
  1       6z74               1             A            9            A
  2       6z74               1             A           10            A
  3       6z74               1             A           11            A
  4       6z74               1             A           12            A
  ..       ...             ...           ...          ...          ...
  232     6z74               1             A          240            A
  233     6z74               1             A          241            A
  234     6z74               1             A          242            A
  235     6z74               1             A          243            A
  236     6z74               1             A          244            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             8                 ?     0               0               0  ...
  1             9                 ?     0               0               0  ...
  2            10                 ?     0               0               0  ...
  3            11                 ?     0               0               0  ...
  4            12                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  232         240                 ?     0               1               0  ...
  233         241                 ?     0               0               0  ...
  234         242                 ?     0               0               0  ...
  235         243                 ?     0               0               0  ...
  236         244                 ?     0               0               0  ...

        HHBlits                                                            \
           M->M      M->I      M->D      I->M      I->I D->M D->D    Neff
  0    0.995850  0.001753  0.002291  0.500000  0.500000  0.0  0.0  10.328
  1    0.993092  0.005403  0.001831  0.224845  0.775393  0.0  1.0  10.263
  2    0.995850  0.004152  0.000000  0.213159  0.786762  1.0  0.0  10.055
  3    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0   9.996
  4    0.997231  0.002470  0.000000  0.500000  0.500000  0.0  0.0  10.064
  ..        ...       ...       ...       ...       ...  ...  ...     ...
  232  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0   7.818
  233  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0   7.553
  234  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0   7.080
  235  0.932386  0.067499  0.000000  1.000000  0.000000  0.0  0.0   6.773
  236  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0   5.866


      Neff_I Neff_D
  0    1.000  0.000
  1    1.036  1.007
  2    1.028  1.025
  3    0.000  0.000
  4    1.013  0.000
  ..     ...    ...
  232  0.000  0.000
  233  0.000  0.000
  234  0.000  0.000
  235  1.046  0.000
  236  0.000  0.000

  [237 rows x 174 columns],
  '7ac8':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id

In [5]:
with open("../../training_data/7.Extra_set/news_sites.pkl", "rb") as f:
    news_sites = {k: v for k, v in pickle.load(f).items() if k in news}

len(news_sites), news_sites

(35,
 {'22mj': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
    2394         A1MDP             H               4            .

         pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
    2394                 ?         407        A1MDP            A

         pdbx_PDB_model_num pdbx_label_index
    2394                  1              407  ,
    'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            THR             A               1          118                 ?
    1            PRO             A               1          119                 ?
    2            THR             A               1          120                 ?
    3            LYS             A               1          129                 ?
    4            GLY             A               1          130                 ?
    5            GLY             A               1          131                 ?
    6            VAL             A               1          132                 ?
    7            ILE             A               1          146                 ?
    8            CYS             A               1          148                 ?
    9            HIS             A               1          149                 ?
    10           LEU             A               1          150                 ?
    11           ASN             A               1          156                 ?
    12           ARG             A               1          160                 ?
    13           LEU             A               1          161                 ?
    14           HIS             A               1          163                 ?
    15           PHE             A               1          164                 ?
    16           ILE             A               1          167                 ?
    17           GLN             A               1          171                 ?
    18           TRP             A               1          189                 ?
    19           MET             A               1          193                 ?
    20           PHE             A               1          195                 ?
    21           GLN             A               1          222                 ?
    22           LEU             A               1          223                 ?
    23           ALA             A               1          226                 ?
    24           ASP             A               1          230                 ?
    25           LEU             A               1          233                 ?
    26           PHE             A               1          236                 ?
    27           LEU             A               1          272                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index
    0          118          THR            A                  1              118
    1          119          PRO            A                  1              119
    2          120          THR            A                  1              120
    3          129          LYS            A                  1              129
    4          130          GLY            A                  1              130
    5          131          GLY            A                  1              131
    6          132          VAL            A                  1              132
    7          146          ILE            A                  1              146
    8          148          CYS            A                  1              148
    9          149          HIS            A                  1              149
    10         150          LEU            A                  1              150
    11         156          ASN            A                  1              156
    12         160          ARG            A                  1              160
    13         161          LEU            A                  1              161
    14         163          HIS            A                  1              163
    15         164          PHE            A                  1              164
    16         167          ILE            A                  1              167
    17         171          GLN            A                  1              171
    18         189          TRP            A                  1              189
    19         193          MET            A                  1              193
    20         195          PHE            A                  1              195
    21         222          GLN            A                  1              222
    22         223          LEU            A                  1              223
    23         226          ALA            A                  1              226
    24         230          ASP            A                  1              230
    25         233          LEU            A                  1              233
    26         236          PHE            A                  1              236
    27         272          LEU            A                  1              272  }],
  '6s3a': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
    3219           SFX             B               2            .

         pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
    3219                 ?         401          SFX            A

         pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
    3219                  1              401                       ?

         pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
    3219                      ?                      ?                      ?  ,
    'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            LEU             A               1           12                 ?
    1            LEU             A               1           43                 ?
    2            PRO             A               1           44                 ?
    3            PRO             A               1           45                 ?
    4            ILE             A               1           60                 ?
    5            MET             A               1           61                 ?
    6            ASP             A               1           62                 ?
    7            ASP             A               1           63                 ?
    8            LEU             A               1           64                 ?
    9            CYS             A               1           65                 ?
    10           GLN             A               1           66                 ?
    11           ASN             A               1           67                 ?
    12           PRO             A               1           68                 ?
    13           ASP             A               1           69                 ?
    14           LYS             A               1           71                 ?
    15           ASP             A               1           72                 ?
    16           VAL             A               1           73                 ?
    17           LEU             A               1           75                 ?
    18           PHE             A               1           76                 ?
    19           CYS             A               1           77                 ?
    20           ALA             A               1          106                 ?
    21           SER             A               1          107                 ?
    22           THR             A               1          108                 ?
    23           ILE             A               1          113                 ?
    24           ALA             A               1          115                 ?
    25           LEU             A               1          124                 ?
    26           PHE             A               1          128                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0          126          LEU            A                  1               12
    1          157          LEU            A                  1               43
    2          158          PRO            A                  1               44
    3          159          PRO            A                  1               45
    4          174          ILE            A                  1               60
    5          175          MET            A                  1               61
    6          176          ASP            A                  1               62
    7          177          ASP            A                  1               63
    8          178          LEU            A                  1               64
    9          179          CYS            A                  1               65
    10         180          GLN            A                  1               66
    11         181          ASN            A                  1               67
    12         182          PRO            A                  1               68
    13         183          ASP            A                  1               69
    14         185          LYS            A                  1               71
    15         186          ASP            A                  1               72
    16         187          VAL            A                  1               73
    17         189          LEU            A                  1               75
    18         190          PHE            A                  1               76
    19         191          CYS            A                  1               77
    20         220          ALA            A                  1              106
    21         221          SER            A                  1              107
    22         222          THR            A                  1              108
    23         227          ILE            A                  1              113
    24         229          ALA            A                  1              115
    25         238          LEU            A                  1              124
    26         242          PHE            A                  1              128

       pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                      UNP                 P03313                   1226
    1                      UNP                 P03313                   1257
    2                      UNP                 P03313                   1258
    3                      UNP                 P03313                   1259
    4                      UNP                 P03313                   1274
    5                      UNP                 P03313                   1275
    6                      UNP                 P03313                   1276
    7                      UNP                 P03313                   1277
    8                      UNP                 P03313                   1278
    9                      UNP                 P03313                   1279
    10                     UNP                 P03313                   1280
    11                     UNP                 P03313                   1281
    12                     UNP                 P03313                   1282
    13                     UNP                 P03313                   1283
    14                     UNP                 P03313                   1285
    15                     UNP                 P03313                   1286
    16                     UNP                 P03313                   1287
    17                     UNP                 P03313                   1289
    18                     UNP                 P03313                   1290
    19                     UNP                 P03313                   1291
    20                     UNP                 P03313                   1320
    21                     UNP                 P03313                   1321
    22                     UNP                 P03313                   1322
    23                     UNP                 P03313                   1327
    24                     UNP                 P03313                   1329
    25                     UNP                 P03313                   1338
    26                     UNP                 P03313                   1342

       pdbx_sifts_xref_db_res
    0                       L
    1                       L
    2                       P
    3                       P
    4                       I
    5                       M
    6                       D
    7                       D
    8                       L
    9                       C
    10                      Q
    11                      N
    12                      P
    13                      D
    14                      K
    15                      D
    16                      V
    17                      L
    18                      F
    19                      C
    20                      A
    21                      S
    22                      T
    23                      I
    24                      A
    25                      L
    26                      F  }],
  '6vvq': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
    3768           MYR             E               2            .

         pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
    3768                 ?         601          MYR            C

         pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
    3768                  1              601                       ?

         pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
    3768                      ?                      ?                      ?  ,
    'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            PHE             C               1           90                 ?
    1            MET             C               1           92                 ?
    2            LEU             C               1          110                 ?
    3            ARG             C               1          113                 ?
    4            TRP             C               1          116                 ?
    5            ASP             C               1          117                 ?
    6            HIS             C               1          119                 ?
    7            TYR             C               1          120                 ?
    8            VAL             C               1          138                 ?
    9            SER             C               1          140                 ?
    10           PRO             C               1          141                 ?
    11           LEU             C               1          143                 ?
    12           GLN             C               1          150                 ?
    13           PHE             C               1          152                 ?
    14           ILE             C               1          154                 ?
    15           LEU             C               1          172                 ?
    16           SER             C               1          174                 ?
    17           GLU             C               1          190                 ?
    18           THR             C               1          191                 ?
    19           CYS             C               1          193                 ?
    20           SER             C               1          194                 ?
    21           GLY             C               1          195                 ?
    22           PHE             C               1          196                 ?
    23           TYR             C               1          210                 ?
    24           TYR             C               1          211                 ?
    25           ASN             C               1          212                 ?
    26           ALA             C               1          214                 ?
    27           THR             C               1          215                 ?
    28           VAL             C               1          218                 ?
    29           TYR             C               1          221                 ?
    30           VAL             C               1          222                 ?
    31           ASN             C               1          225                 ?
    32           GLU             C               1          232                 ?
    33           PHE             C               1          233                 ?
    34           TYR             C               1          234                 ?
    35           THR             C               1          236                 ?
    36           PHE             C               1          237                 ?
    37           CYS             C               1          240                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0          426          PHE            C                  1               90
    1          428          MET            C                  1               92
    2          446          LEU            C                  1              110
    3          449          ARG            C                  1              113
    4          452          TRP            C                  1              116
    5          453          ASP            C                  1              117
    6          455          HIS            C                  1              119
    7          456          TYR            C                  1              120
    8          474          VAL            C                  1              138
    9          476          SER            C                  1              140
    10         477          PRO            C                  1              141
    11         479          LEU            C                  1              143
    12         486          GLN            C                  1              150
    13         488          PHE            C                  1              152
    14         490          ILE            C                  1              154
    15         508          LEU            C                  1              172
    16         510          SER            C                  1              174
    17         526          GLU            C                  1              190
    18         527          THR            C                  1              191
    19         529          CYS            C                  1              193
    20         530          SER            C                  1              194
    21         531          GLY            C                  1              195
    22         532          PHE            C                  1              196
    23         546          TYR            C                  1              210
    24         547          TYR            C                  1              211
    25         548          ASN            C                  1              212
    26         550          ALA            C                  1              214
    27         551          THR            C                  1              215
    28         554          VAL            C                  1              218
    29         557          TYR            C                  1              221
    30         558          VAL            C                  1              222
    31         561          ASN            C                  1              225
    32         568          GLU            C                  1              232
    33         569          PHE            C                  1              233

# Process structures

In [6]:
os.makedirs("structures", exist_ok=True)

In [7]:
import pymol2

In [8]:
for pdb in news:
    ciff = f"../../training_data/7.Extra_set/cifs/{pdb}.cif"
    if not os.path.isfile(f"structures/{pdb}.cif"):
        os.system(f"cp {ciff} structures/{pdb}.cif")

    if not os.path.isfile(f"structures/{pdb}.pdb"):
        with pymol2.PyMOL() as pymol:
            pymol.cmd.feedback("disable", "executive", "details")
            pymol.cmd.load(ciff, "structure")
            pymol.cmd.save(f"structures/{pdb}.pdb", "structure")

# Our results

In [9]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [10]:
def process_dataframe(df):
    df.index = df["Pockets"][["pdb", "pocket"]].apply(lambda x: "_".join(x), axis=1)
    df = df.drop(columns=["Pockets"], level=0)
    df.columns = map(lambda x: "_".join(x), df.columns.values)
    df.loc[:,'Label_label'] = df['Label_label'].astype("category")
    return df

## Model 5.

In [11]:
predictor = TabularPredictor.load("../pockets_physchem_deploy")

In [12]:
with open("../../training_data/7.Extra_set/pockets_features.pkl", "rb") as f:
    extra = pd.concat((
        pickle.load(f).values()
    ))

extra

    Pockets                                              Label      FPocket  \
        pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
0      22mj  pocket11   13       0.000000       0.000000     0      -0.0344
1      22mj   pocket7   10       0.000000       0.000000     0       0.0487
2      22mj   pocket1   17       0.000000       0.000000     0       0.2733
3      22mj   pocket2   44       0.928571       0.590909     1       0.2570
4      22mj   pocket4   10       0.000000       0.000000     0       0.0698
..      ...       ...  ...            ...            ...   ...          ...
710    9ow9   pocket3   16       0.055556       0.125000     0       0.1895
711    9ow9  pocket12   14       0.000000       0.000000     0       0.0593
712    9ow9  pocket19   13       0.111111       0.307692     0      -0.0406
713    9ow9  pocket21   13       0.000000       0.000000     0      -0.1540
714    9ow9   pocket6   14       0.083333       0.214286     0       0.1175

                                                                 ...  \
    Drug Score Number of alpha spheres Mean alpha-sphere radius  ...
0       0.0005                    40.0                   3.6645  ...
1       0.0007                    40.0                   3.5474  ...
2       0.1102                    49.0                   3.5212  ...
3       0.9974                   312.0                   3.5983  ...
4       0.0009                    59.0                   3.5695  ...
..         ...                     ...                      ...  ...
710     0.0215                    64.0                   3.4302  ...
711     0.1223                    57.0                   3.3835  ...
712     0.1032                    51.0                   3.5753  ...
713     0.0179                    61.0                   3.6792  ...
714     0.0244                    59.0                   3.3881  ...

      HHBlits                                                              \
         M->M      M->I      M->D      I->M      I->I      D->M      D->D
0    0.965538  0.017878  0.016567  0.293938  0.706008  0.220269  0.779680
1    0.976615  0.014044  0.009283  0.198701  0.801308  0.253872  0.746113
2    0.972468  0.022047  0.005504  0.250170  0.573332  0.291624  0.708348
3    0.955549  0.013536  0.030923  0.319427  0.680553  0.187262  0.812706
4    0.935202  0.008965  0.055771  0.259235  0.740732  0.055374  0.944506
..        ...       ...       ...       ...       ...       ...       ...
710  0.979323  0.015552  0.005174  0.221978  0.715481  0.150538  0.849464
711  0.979097  0.012785  0.008063  0.281685  0.718355  0.214290  0.785698
712  0.986117  0.006892  0.006934  0.240089  0.759958  0.193603  0.806453
713  0.983233  0.009535  0.007285  0.346869  0.653202  0.191585  0.808504
714  0.965064  0.026202  0.008636  0.254808  0.745237  0.221290  0.778718


          Neff    Neff_I    Neff_D
0    13.560923  1.422769  2.255692
1    13.655300  1.368300  3.001700
2    13.637059  1.369588  2.838706
3    13.756750  1.343114  4.087545
4    13.609500  1.177300  7.705000
..         ...       ...       ...
710  12.131875  1.193875  1.410125
711  12.596214  1.280786  1.704857
712  12.717846  1.153692  1.917231
713  11.523231  1.086769  1.785231
714  12.702857  1.569286  1.871857

[706 rows x 194 columns]

In [13]:
# Check that all PDBs only have one positive pocket
extra.assign(totalpos=lambda df: df.groupby(("Pockets", "pdb"))[("Label", "label"),].transform("sum")).iloc[:, [0, -1]].drop_duplicates().sort_values("totalpos")

    Pockets totalpos
        pdb
31     6on4        0
82     7agj        0
177    7ry1        0
627    9lhf        0
18     6vvq        1
49     6z1m        1
63     6z74        1
12     6s3a        1
72     7ac8        1
117    7oy0        1
153    7pt0        1
139    7p2v        1
161    7qpn        1
204    7xmd        1
219    7yg5        1
0      22mj        1
285    7zpe        1
296    8crc        1
334    8f4s        1
306    8e24        1
403    8hx9        1
429    8jb3        1
445    8jp0        1
344    8fpi        1
478    8qni        1
495    8uk6        1
570    9b96        1
525    8v81        1
593    9d2r        1
600    9ebs        1
613    9fsj        1
634    9mft        1
664    9ntc        1
676    9oul        1
693    9ow9        1

In [14]:
extra_probs = predictor.predict_proba( process_dataframe(extra) )
extra_probs

                      0         1
22mj_pocket11  0.984074  0.015926
22mj_pocket7   0.999728  0.000272
22mj_pocket1   0.999994  0.000006
22mj_pocket2   0.195944  0.804056
22mj_pocket4   0.999977  0.000023
...                 ...       ...
9ow9_pocket3   0.999598  0.000402
9ow9_pocket12  0.999447  0.000553
9ow9_pocket19  0.999827  0.000173
9ow9_pocket21  0.999992  0.000008
9ow9_pocket6   0.998194  0.001806

[706 rows x 2 columns]

In [15]:
model5_results = {
    pdb: {
        pocket: {
            "prob": prob,
            "pred": 1 if prob >= 0.5 else 0,
            "label": info[("Label", "label")],
            "max_overlap": overlaps.max(),
            **overlaps["Pockets"].to_dict()
        }
        for pocket in pockets["pocket"]
        for prob in (extra_probs.loc[f"{pdb}_{pocket}", 1],)
        for info in (extra.loc[f"{pdb}_{pocket}"],)
        for overlaps in (info[[("Pockets", "pocket_in_site"), ("Pockets", "site_in_pocket")]],)
    }
    for pdb, pockets in (
        pd.DataFrame(
            extra_probs.index.map(lambda x: x.split("_")).values.tolist(),
            columns=["pdb", "pocket"]
        )
        .groupby("pdb")
    )
}

model5_results

{'22mj': {'pocket11': {'prob': 0.015926241874694824,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 0.0002722057106439024,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 5.723202775698155e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket2': {'prob': 0.80405592918396,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.9285714285714286,
   'pocket_in_site': 0.5909090909090909,
   'site_in_pocket': 0.9285714285714286},
  'pocket4': {'prob': 2.3296684958040714e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket9': {'prob': 0.000627053901553154,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.08333333333333333,
   'pocket_in_site': 0.08333333333333333,
   'site_in_pocket': 0.03571428571428571},
  'pocket10': {'prob': 0.0001461432402720675,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.18181818181818182,
   'pocket_in_site': 0.18181818181818182,
   'site_in_pocket': 0.07142857142857142},
  'pocket5': {'prob': 0.00010802153701661155,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.07692307692307693,
   'pocket_in_site': 0.07692307692307693,
   'site_in_pocket': 0.03571428571428571},
  'pocket8': {'prob': 1.4545725207426585e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.0010299441637471318,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.07692307692307693,
   'pocket_in_site': 0.07692307692307693,
   'site_in_pocket': 0.03571428571428571},
  'pocket12': {'prob': 0.0006795694935135543,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 2.654720447026193e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '6on4': {'pocket7': {'prob': 0.0006653632735833526,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.03508249670267105,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket2': {'prob': 0.008349956944584846,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.5454545454545454,
   'pocket_in_site': 0.5454545454545454,
   'site_in_pocket': 0.2222222222222222},
  'pocket4': {'prob': 0.00350033026188612,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket9': {'prob': 1.7894832126330584e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.0015297199133783579,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 2.925443141066353e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.03645719587802887,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 9.636913091526367e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '6s3a': {'pocket1': {'prob': 0.916088342666626,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.7407407407407407,
   'pocket_in_site': 0.5128205128205128,
   'site_in_pocket': 0.7407407407407407},
  'pocket2': {'prob': 0.0006330080796033144,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket4': {'prob': 1.8358763327341876e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.0004271398647688329,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.13333333333333333,
   'pocket_in_site': 0.13333333333333333,
   'site_in_pocket': 0.07407407407407407},
  'pocket3': {'prob': 0.0008974180673249066,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 1.1206387853235356e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '6vvq': {'pocket11': {'prob': 0.0008468019659630954,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 9.395352390129119e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.6666666666666666,
   'pocket_in_site': 0.6666666666666666,
   'site_in_pocket': 0.21052631578947367},
  'pocket13': {'prob': 6.939367267477792e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.9297783374786377,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.7777777777777778,
   'pocket_in_site': 0.7777777777777778,
   'site_in_pocket': 0.7368421052631579},
  'pocket2': {'prob': 0.000794723629951477,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.08333333333333333,
   'pocket_in_site': 0.08333333333333333,
   'site_in_pocket': 0.02631578947368421},
  'pocket4': {'prob': 0.026898527517914772,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0625,
   'pocket_in_site': 0.0625,
   'site_in_pocket': 0.02631578947368421},
  'pocket9': {'prob': 0.0005906405858695507,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.125,
   'pocket_in_site': 0.125,
   'site_in_pocket': 0.05263157894736842},
  'pocket10': {'prob': 0.00016857992159202695,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2727272727272727,
   'pocket_in_site': 0.2727272727272727,
   'site_in_pocket': 0.07894736842105263},
  'pocket5': {'prob': 0.034184589982032776,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.42857142857142855,
   'pocket_in_site': 0.42857142857142855,
   'site_in_pocket': 0.15789473684210525},
  'pocket8': {'prob': 0.0009646386024542153,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.00042768221464939415,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket12': {'prob': 8.93873511813581e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.16666666666666666,
   'pocket_in_site': 0.16666666666666666,
   'site_in_pocket': 0.05263157894736842},
  'pocket6': {'prob': 4.018599611299578e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '6z1m': {'pocket11': {'prob': 0.0015128388768061996,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.047619047619047616,
   'pocket_in_site': 0.047619047619047616,
   'site_in_pocket': 0.027777777777777776},
  'pocket7': {'prob': 3.650477810879238e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket13': {'prob': 1.757488280418329e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket14': {'prob': 0.002025006804615259,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.09523809523809523,
   'pocket_in_site': 0.09523809523809523,
   'site_in_pocket': 0.05555555555555555},
  'pocket1': {'prob': 0.00022238475503399968,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.15384615384615385,
   'pocket_in_site': 0.15384615384615385,
   'site_in_pocket': 0.05555555555555555},
  'pocket2': {'prob': 5.6292923545697704e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket4': {'prob': 4.653539235732751e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2222222222222222,
   'pocket_in_site': 0.2222222222222222,
   'site_in_pocket': 0.05555555555555555},
  'pocket9': {'prob': 0.0002552109945099801,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket10': {'prob': 1.6028646143695369e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.0021523486357182264,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 2.15568197745597e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 5.9831872931681573e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket12': {'prob': 0.00038790932740084827,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.4444444444444444,
   'pocket_in_site': 0.4444444444444444,
   'site_in_pocket': 0.1111111111111111},
  'pocket6': {'prob': 0.8617633581161499,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.8333333333333334,
   'pocket_in_site': 0.7317073170731707,
   'site_in_pocket': 0.8333333333333334}},
 '6z74': {'pocket7': {'prob': 0.0006050413940101862,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.3837234377861023,
   'pred': 0,
   'label': 1,
   'max_overlap': 0.8181818181818182,
   'pocket_in_site': 0.8181818181818182,
   'site_in_pocket': 0.72},
  'pocket2': {'prob': 0.00686656404286623,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.26666666666666666,
   'pocket_in_site': 0.26666666666666666,
   'site_in_pocket': 0.16},
  'pocket4': {'prob': 0.0020264005288481712,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket9': {'prob': 0.0016266737366095185,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2727272727272727,
   'pocket_in_site': 0.2727272727272727,
   'site_in_pocket': 0.12},
  'pocket5': {'prob': 0.003908317070454359,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 0.024111272767186165,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.3333333333333333,
   'pocket_in_site': 0.3333333333333333,
   'site_in_pocket': 0.16},
  'pocket3': {'prob': 0.04653303325176239,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.18181818181818182,
   'pocket_in_site': 0.18181818181818182,
   'site_in_pocket': 0.08},
  'pocket6': {'prob': 0.0004858229367528111,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '7ac8': {'pocket7': {'prob': 4.18781019106973e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.7156406044960022,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.8717948717948718,
   'pocket_in_site': 0.6938775510204082,
   'site_in_pocket': 0.8717948717948718},
  'pocket2': {'prob': 0.14692285656929016,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.17647058823529413,
   'pocket_in_site': 0.17647058823529413,
   'site_in_pocket': 0.07692307692307693},
  'pocket4': {'prob': 0.006182667799293995,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket9': {'prob': 3.595543239498511e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket10': {'prob': 2.8797371669497807e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.0007020255434326828,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 0.00024752982426434755,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.0009099997114390135,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2727272727272727,
   'pocket_in_site': 0.2727272727272727,
   'site_in_pocket': 0.07692307692307693},
  'pocket6': {'prob': 0.0004022723587695509,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2727272727272727,
   'pocket_in_site': 0.2727272727272727,
   'site_in_pocket': 0.07692307692307693}},
 '7agj': {'pocket16': {'prob': 0.001969381235539913,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket28': {'prob': 0.006581176538020372,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.75,
   'pocket_in_site': 0.75,
   'site_in_pocket': 0.2727272727272727},
  'pocket18': {'prob': 3.772671698243357e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.13333333333333333,
   'pocket_in_site': 0.13333333333333333,
   'site_in_pocket': 0.06060606060606061},
  'pocket11': {'prob': 0.8201584219932556,
   'pred': 1,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket34': {'prob': 0.0004608731542248279,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.3333333333333333,
   'pocket_in_site': 0.3333333333333333,
   'site_in_pocket': 0.12121212121212122},
  'pocket25': {'prob': 3.222286613890901e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket15': {'prob': 0.2722623646259308,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 0.0013856315053999424,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket22': {'prob': 0.0003084862546529621,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket13': {'prob': 0.23760010302066803,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket31': {'prob': 0.0001246406463906169,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket23': {'prob': 0.015111612156033516,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket14': {'prob': 0.004035477992147207,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket26': {'prob': 0.002396069699898362,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.3733585476875305,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.4444444444444444,
   'pocket_in_site': 0.4444444444444444,
   'site_in_pocket': 0.36363636363636365},
  'pocket27': {'prob': 6.588882388314232e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket2': {'prob': 0.06302104890346527,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket32': {'prob': 1.702130020930781e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket20': {'prob': 0.0006581561756320298,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket4': {'prob': 0.0024328238796442747,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket29': {'prob': 0.00031837509595789015,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.1111111111111111,
   'pocket_in_site': 0.1111111111111111,
   'site_in_pocket': 0.030303030303030304},
  'pocket30': {'prob': 5.973204224574147e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket17': {'prob': 3.705713606905192e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket9': {'prob': 0.43173307180404663,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.5909090909090909,
   'pocket_in_site': 0.5909090909090909,
   'site_in_pocket': 0.3939393939393939},
  'pocket10': {'prob': 0.00013393881090451032,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket35': {'prob': 2.5944211756723234e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 3.5934053244091047e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 0.06463245302438736,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.03125,
   'pocket_in_site': 0.03125,
   'site_in_pocket': 0.030303030303030304},
  'pocket24': {'prob': 0.00016735262761358172,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.0200122632086277,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket12': {'prob': 2.8406984711182304e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket19': {'prob': 7.997657667146996e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket21': {'prob': 0.0006664830725640059,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket33': {'prob': 0.001114293234422803,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.25,
   'pocket_in_site': 0.25,
   'site_in_pocket': 0.09090909090909091},
  'pocket6': {'prob': 0.0024307742714881897,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '7oy0': {'pocket16': {'prob': 2.363050043641124e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket18': {'prob': 2.2772594547859626e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket11': {'prob': 0.00031729936017654836,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket15': {'prob': 0.00015016336692497134,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 8.447310392512009e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket22': {'prob': 0.04763633757829666,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.08333333333333333,
   'pocket_in_site': 0.08333333333333333,
   'site_in_pocket': 0.05},
  'pocket13': {'prob': 1.4251307902668486e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket14': {'prob': 7.462558278348297e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.9577227234840393,
   'pred': 1,
   'label': 0,
   'max_overlap': 0.15,
   'pocket_in_site': 0.04411764705882353,
   'site_in_pocket': 0.15},
  'pocket2': {'prob': 0.0017142685828730464,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket20': {'prob': 7.961878145579249e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.7272727272727273,
   'pocket_in_site': 0.7272727272727273,
   'site_in_pocket': 0.4},
  'pocket4': {'prob': 0.0009259326616302133,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket17': {'prob': 0.7886338829994202,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.875,
   'pocket_in_site': 0.875,
   'site_in_pocket': 0.7},
  'pocket9': {'prob': 0.0005187379429116845,
   'pred': 0,
   'label': 0,

In [16]:
pd.DataFrame((
    {
        "pdb": pdb,
        "pocket": pocket,
        **pocketd
    }
    for pdb, pockets in model5_results.items()
    for pocket, pocketd in pockets.items()
)).sort_values(["pred", "label", "prob", "site_in_pocket"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
657,9ntc,pocket1,0.982443,1,1,0.717391,0.717391,0.647059
532,8v81,pocket1,0.977954,1,1,0.962963,0.208000,0.962963
673,9oul,pocket1,0.950287,1,1,0.903226,0.259259,0.903226
498,8uk6,pocket1,0.946666,1,1,0.952381,0.540541,0.952381
30,6vvq,pocket1,0.929778,1,1,0.777778,0.777778,0.736842
326,8f4s,pocket1,0.923800,1,1,0.846154,0.733333,0.846154
475,8qni,pocket1,0.917425,1,1,0.966667,0.322222,0.966667
21,6s3a,pocket1,0.916088,1,1,0.740741,0.512821,0.740741
449,8jp0,pocket1,0.906662,1,1,0.781250,0.320513,0.781250
146,7pt0,pocket2,0.900742,1,1,0.863636,0.527778,0.863636
405,8hx9,pocket1,0.900688,1,1,0.884615,0.469388,0.884615
53,6z1m,pocket6,0.861763,1,1,0.833333,0.731707,0.833333
159,7qpn,pocket2,0.829749,1,1,0.913043,0.700000,0.913043
353,8fpi,pocket1,0.813792,1,1,0.775510,0.655172,0.775510
3,22mj,pocket2,0.804056,1,1,0.928571,0.590909,0.928571
592,9ebs,pocket7,0.796260,1,1,0.857143,0.500000,0.857143
120,7oy0,pocket17,0.788634,1,1,0.875000,0.875000,0.700000
692,9ow9,pocket1,0.775315,1,1,0.916667,0.611111,0.916667
64,7ac8,pocket1,0.715641,1,1,0.871795,0.693878,0.871795
285,7zpe,pocket3,0.639918,1,1,0.785714,0.578947,0.785714
585,9d2r,pocket1,0.554641,1,1,0.941176,0.695652,0.941176
608,9fsj,pocket1,0.502134,1,1,0.812500,0.812500,0.764706
637,9mft,pocket1,0.996670,1,0,0.000000,0.000000,0.000000
116,7oy0,pocket1,0.957723,1,0,0.150000,0.044118,0.150000
200,7xmd,pocket1,0.910560,1,0,0.000000,0.000000,0.000000
541,8v81,pocket17,0.841321,1,0,0.000000,0.000000,0.000000
538,8v81,pocket4,0.835974,1,0,0.000000,0.000000,0.000000
426,8jb3,pocket1,0.827686,1,0,0.000000,0.000000,0.000000
76,7agj,pocket11,0.820158,1,0,0.000000,0.000000,0.000000
631,9mft,pocket7,0.783547,1,0,0.000000,0.000000,0.000000
589,9d2r,pocket3,0.776362,1,0,0.000000,0.000000,0.000000
570,9b96,pocket1,0.714871,1,0,0.000000,0.000000,0.000000
337,8fpi,pocket18,0.650229,1,0,0.000000,0.000000,0.000000
273,7yg5,pocket63,0.560827,1,0,0.000000,0.000000,0.000000
278,7zpe,pocket1,0.514394,1,0,0.000000,0.000000,0.000000
571,9b96,pocket2,0.504292,1,0,0.000000,0.000000,0.000000
380,8fpi,pocket45,0.500826,1,0,0.000000,0.000000,0.000000
313,8e24,pocket4,0.412652,0,1,0.888889,0.888889,0.800000
55,6z74,pocket1,0.383723,0,1,0.818182,0.818182,0.720000
433,8jb3,pocket3,0.292251,0,1,0.920000,0.851852,0.920000

# Results

## AllositePro

In [18]:
allositepro_resultsf = "AllositePro/allositepro_results.pkl"

with open(allositepro_resultsf, "rb") as f:
    allositepro_results = {k: v for k,v in pickle.load(f).items() if k in news}

len(allositepro_results), allositepro_results

(15,
 {'22mj': {'pocket0': {'Volume': 992.587,
    'SASA': 508.691,
    'Druggability Score': 0.868,
    'logitProb': 0.822,
    'nmaScore': 0.196,
    'hitScore': 0.697,
    'residues':    auth_asym_id auth_seq_id
    0             A         164
    1             A         163
    2             A         150
    3             A         146
    4             A         195
    5             A         193
    6             A         118
    7             A         133
    8             A         223
    9             A         153
    10            A         151
    11            A         131
    12            A         272
    13            A         160
    14            A         148
    15            A         167
    16            A         236
    17            A         116
    18            A         189
    19            A         119
    20            A         120
    21            A         222
    22            A         233
    23            A         132
    24            A         156
    25            A         171
    26            A         152
    27            A         194
    28            A         122
    29            A         130}},
  '6s3a': {'pocket0': {'Volume': 843.755,
    'SASA': 355.913,
    'Druggability Score': 0.652,
    'logitProb': 0.814,
    'nmaScore': 0.154,
    'hitScore': 0.682,
    'residues':    auth_asym_id auth_seq_id
    0             A         235
    1             A         245
    2             A         295
    3             A         179
    4             A         236
    5             A         226
    6             A         178
    7             A         186
    8             A         220
    9             A         239
    10            A         238
    11            A         187
    12            A         128
    13            A         175
    14            A         227
    15            A         190
    16            A         182
    17            A         126
    18            A         242}},
  '6vvq': {'pocket0': {'Volume': 696.14,
    'SASA': 310.458,
    'Druggability Score': 0.907,
    'logitProb': 0.847,
    'nmaScore': 0.53,
    'hitScore': 0.784,
    'residues':    auth_asym_id auth_seq_id
    0             C         532
    1             C         573
    2             C         557
    3             C         527
    4             C         490
    5             C         476
    6             C         551
    7             C         486
    8             C         488
    9             C         479
    10            C         530
    11            C         508
    12            C         426
    13            C         546
    14            C         474
    15            C         554
    16            C         558
    17            C         569
    18            C         548
    19            C         456
    20            C         455
    21            C         449
    22            C         572
    23            C         453
    24            C         452
    25            C         428}},
  '6z1m': {'pocket0': {'Volume': 2248.598,
    'SASA': 1102.949,
    'Druggability Score': 0.129,
    'logitProb': 0.523,
    'nmaScore': 0.996,
    'hitScore': 0.618,
    'residues':    auth_asym_id auth_seq_id
    0             A         231
    1             A         245
    2             A         184
    3             A         235
    4             A          51
    5             A         237
    6             A          49
    7             A         236
    8             A         358
    9             A         232
    10            A         414
    11            A         183
    12            A         127
    13            A          43
    14            A         304
    15            A         248
    16            A         227
    17            A         174
    18            A         418
    19            A         241
    20            A          25
    21            A         182
    22            A         404
    23            A          50
    24            A         178
    25            A         185
    26            A         412
    27            A         413
    28            A         177
    29            A         190
    30            A         411
    31            A         170
    32            A         305
    33            A          48
    34            A         244
    35            A         240
    36            A         233
    37            A         126
    38            A         171
    39            A         420},
   'pocket1': {'Volume': 511.99,
    'SASA': 335.816,
    'Druggability Score': 0.714,
    'logitProb': 0.677,
    'nmaScore': 0.227,
    'hitScore': 0.587,
    'residues':    auth_asym_id auth_seq_id
    0             A         292
    1             A         203
    2             A         199
    3             A         252
    4             A         206
    5             A         251
    6             A         296
    7             A         202
    8             A         271
    9             A         172
    10            A         264
    11            A         226
    12            A         176
    13            A         255
    14            A         295
    15            A         224
    16            A         173
    17            A         169}},
  '7yg5': {'pocket0': {'Volume': 608.234,
    'SASA': 328.383,
    'Druggability Score': 0.848,
    'logitProb': 0.783,
    'nmaScore': 0.144,
    'hitScore': 0.655,
    'residues':    auth_asym_id auth_seq_id
    0             A        1616
    1             A        1283
    2             A        1617
    3             A        1269
    4             A        1620
    5             A        1713
    6             A        1279
    7             A        1282
    8             A        1286
    9             A        1709
    10            A        1621
    11            A        1613
    12            A        1712
    13            A        1266}},
  '7zpe': {'pocket0': {'Volume': 290.446,
    'SASA': 168.002,
    'Druggability Score': 0.209,
    'logitProb': 0.783,
    'nmaScore': 0.165,
    'hitScore': 0.659,
    'residues':    auth_asym_id auth_seq_id
    0             A         102
    1             A          99
    2             A         170
    3             A          75
    4             A         129
    5             A         167
    6             A         128
    7             A         166
    8             A         171
    9             A         132
    10            A          72
    11            A          71}},
  '8crc': {'pocket0': {'Volume': 679.406,
    'SASA': 418.18,
    'Druggability Score': 0.279,
    'logitProb': 0.376,
    'nmaScore': 1.0,
    'hitScore': 0.501,
    'residues':    auth_asym_id auth_seq_id
    0             A         450
    1             A         409
    2             A         462
    3             A         451
    4             A         510
    5             A         447
    6             A         505
    7             A         460
    8             A         508
    9             A         443
    10            A         507
    11            A         509
    12            A         506
    13            A         526
    14            A         445
    15            A         527
    16            A         452},
   'pocket1': {'Volume': 435.767,
    'SASA': 296.493,
    'Druggability Score': 0.265,
    'logitProb': 0.483,
    'nmaScore': 0.846,
    'hitScore': 0.555,
    'residues':   auth_asym_id auth_seq_id
    0            A         557
    1            A         559
    2            A         410
    3            A         406
    4            A         553
    5            A         540
    6            A         551
    7            A         407
    8            A         542}},
  '8f4s': {'pocket0': {'Volume': 1497.231,
    'SASA': 695.878,
    'Druggability Score': 0.738,
    'logitProb': 0.801,
    'nmaScore': 0.173,
    'hitScore': 0.675,
    'residues':    auth_asym_id auth_seq_id
    0             A        6917
    1             A        6949
    2             A        6931
    3             A        6909
    4             A        6947
    5             A        6951
    6             A        6957
    7             A        6953
    8             A        6927
    9             A        6912
    10            A        6910
    11            A        6894
    12            A        6958
    13            A        6868
    14            A        6896
    15            A        7088
    16            A        6916
    17            A        6954
    18            A        6869
    19            A        6918
    20            A        6950
    21            A        6914
    22            A        6898
    23            A        6922
    24            A        6929
    25            A        6866
    26            A        6897
    27            A        6895
    28            A        6911
    29            A        6913}},
  '8jp0': {'pocket0': {'Volume': 374.703,
    'SASA': 273.097,
    'Druggability Score': 0.472,
    'logitProb': 0.744,
    'nmaScore': 0.119,
    'hitScore': 0.619,
    'residues':   auth_asym_id auth_seq_id
    0            A         206
    1            A         210
    2            A         832
    3            A         839
    4            A         836
    5            A         244
    6            A         835
    7            A         245
    8            A         207
    9            A         248}},
  '8qni': {'pocket0': {'Volume': 1703.293,
    'SASA': 807.696,
    'Druggability Score': 0.749,
    'logitProb': 0.669,
    'nmaScore': 0.474,
    'hitScore': 0.63,
    'residues':    auth_asym_id auth_seq_id
    0             A         261
    1             A         236
    2             A         148
    3             A         293
    4             A         145
    5             A         149
    6             A         142
    7             A         220
    8             A         232
    9             A         295
    10            A         257
    11            A         292
    12            A         262
    13            A         258
    14            A         224
    15            A         222
    16            A         287
    17            A         291
    18            A         141
    19            A         294
    20            A         240
    21            A         254
    22            A         263
    23            A         264
    24            A         335
    25            A         239
    26            A         368
    27            A         288
    28            A         272
    29            A         138
    30            A         144
    31            A         235
    32            A         364
    33            A         268
    34            A         218
    35            A         260
    36            A         363
    37            A         359
    38            A         369
    39            A         255
    40            A         219
    41            A         221
    42            A         152
    43            A         362
    44            A         367
    45            A         366}},
  '8uk6': {'pocket0': {'Volume': 1013.8,
    'SASA': 484.166,
    'Druggability Score': 0.517,
    'logitProb': 0.663,
    'nmaScore': 0.263,
    'hitScore': 0.583,
    'residues':    auth_asym_id auth_seq_id
    0             A         448
    1             A         275
    2             A         458
    3             A         255
    4             A         417
    5             A         405
    6             A         468
    7             A         483
    8             A         289
    9             A         440
    10            A         257
    11            A         403
    12            A         444
    13            A         456
    14            A         291
    15            A         258
    16            A         459
    17            A         462
    18            A         486
    19            A         268
    20            A         469
    21            A         323
    22            A         256
    23            A         443
    24            A         472
    25            A         441
    26            A         457
    27            A         445
    28            A         465
    29            A         447
    30            A         271
    31            A         259},
   'pocket1': {'Volume': 1061.007,
    'SASA': 443.879,
    'Druggability Score': 0.6,
    'logitProb': 0.783,
    'nmaScore': 0.105,
    'hitScore': 0.648,
    'residues':    auth_asym_id auth_seq_id
    0             A         495
    1             A         497
    2             A         493
    3             A         518
    4             A         520
    5             A         700
    6             A         262
    7             A         264
    8             A         699
    9             A         498
    10            A         268
    11            A         496
    12            A         494
    13            A         519
    14            A         302
    15            A         703
    16            A         513
    17            A         701
    18            A         501
    19            A         517
    20            A         259
    21            A         261
    22            A         265
    23            A         263}},
  '8v81': {'pocket0': {'Volume': 351.637,
    'SASA': 192.926,
    'Druggability Score': 0.535,
    'logitProb': 0.716,
    'nmaScore': 0.193,
    'hitScore': 0.611,
    'residues':    auth_asym_id auth_seq_id
    0             A        1143
    1             A        1142
    2             A        1001
    3             A         921
    4             A         923
    5             A        1138
    6             A         920
    7             A        1000
    8             A        1139
    9             A         924
    10            A        1004
    11            A        1135
    12            A         344
    13            A        1008
    14            A        1005}},
  '9fsj': {'pocket0': {'Volume': 831.115,
    'SASA': 425.941,
    'Druggability Score': 0.851,
    'logitProb': 0.859,
    'nmaScore': 0.617,
    'hitScore': 0.811,
    'residues':    auth_asym_id auth_seq_id
    0             A         456
    1             A         635
    2             A         628
    3             A         452
    4             A         519
    5             A         515
    6             A         504
    7             A         518
    8             A         631
    9             A         455
    10            A         505
    11            A         506
    12            A         620
    13            A         389
    14            A         623
    15            A         386
    16            A         385
    17            A         382
    18            A         521
    19            A         508
    20            A         611
    21            A         500
    22            A         499
    23            A         510
    24            A         496
    25            A         503}},
  '9oul': {'pocket0': {'Volume': 884.505,
    'SASA': 513.164,
    'Druggability Score': 0.876,
    'logitProb': 0.814,
    'nmaScore': 0.497,
    'hitScore': 0.75,
    'residues':    auth_asym_id auth_seq_id
    0             C         313
    1             C         288
    2             C         284
    3             C         265
    4             C         360
    5             C         334
    6             C         426
    7             C         287
    8             C         289
    9             C         290
    10            C         321
    11            C         294
    12            C         314
    13            C         315
    14            C         264
    15            C         261
    16            C         344
    17            C         317
    18            C         318
    19            C         319
    20            C         424
    21            C         268
    22            C         345
    23            C         273
    24            C         283
    25            C         339
    26            C         337}},
  '9ow9': {'pocket0': {'Volume': 2678.462,
    'SASA': 1449.088,
    'Druggability Score': 0.676,
    'logitProb': 0.801,
    'nmaScore': 0.639,
    'hitScore': 0.768,
    'residues':    auth_asym_id auth_seq_id
    0             A         723
    1             A         528
    2             A         527
    3             A         854
    4             A         708
    5             A         853
    6             A         825
    7             A         850
    8             A         559
    9             A         917
    10            A         554
    11            A         844
    12            A         847
    13            A         706
    14            A         852
    15            A         913
    16            A         829
    17            A         570
    18            A         705
    19            A         846
    20            A         563
    21            A         530
    22            A         849
    23            A         891
    24            A         558
    25            A         707
    26            A         828
    27            A         529
    28            A         730
    29            A         552
    30            A         732
    31            A         555
    32            A         565
    33            A         843
    34            A         551
    35            A         857
    36            A         726
    37            A         910
    38            A         731
    39            A         737
    40            A         914
    41            A         728
    42            A         727
    43            A         826
    44            A         851
    45            A         918
    46            A         725
    47            A         711
    48            A         822
    49            A         724
    50            A         735}}})

All output pockets are predicted positive.

In [19]:
allositepro_results = {
    pdb: {
        pocket: {
            "pred": 1,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in allositepro_results.items()
}
allositepro_results

{'22mj': {'pocket0': {'pred': 1,
   'Volume': 992.587,
   'SASA': 508.691,
   'Druggability Score': 0.868,
   'logitProb': 0.822,
   'nmaScore': 0.196,
   'hitScore': 0.697,
   'residues':    auth_asym_id auth_seq_id
   0             A         164
   1             A         163
   2             A         150
   3             A         146
   4             A         195
   5             A         193
   6             A         118
   7             A         133
   8             A         223
   9             A         153
   10            A         151
   11            A         131
   12            A         272
   13            A         160
   14            A         148
   15            A         167
   16            A         236
   17            A         116
   18            A         189
   19            A         119
   20            A         120
   21            A         222
   22            A         233
   23            A         132
   24            A         156
   25            A         171
   26            A         152
   27            A         194
   28            A         122
   29            A         130}},
 '6s3a': {'pocket0': {'pred': 1,
   'Volume': 843.755,
   'SASA': 355.913,
   'Druggability Score': 0.652,
   'logitProb': 0.814,
   'nmaScore': 0.154,
   'hitScore': 0.682,
   'residues':    auth_asym_id auth_seq_id
   0             A         235
   1             A         245
   2             A         295
   3             A         179
   4             A         236
   5             A         226
   6             A         178
   7             A         186
   8             A         220
   9             A         239
   10            A         238
   11            A         187
   12            A         128
   13            A         175
   14            A         227
   15            A         190
   16            A         182
   17            A         126
   18            A         242}},
 '6vvq': {'pocket0': {'pred': 1,
   'Volume': 696.14,
   'SASA': 310.458,
   'Druggability Score': 0.907,
   'logitProb': 0.847,
   'nmaScore': 0.53,
   'hitScore': 0.784,
   'residues':    auth_asym_id auth_seq_id
   0             C         532
   1             C         573
   2             C         557
   3             C         527
   4             C         490
   5             C         476
   6             C         551
   7             C         486
   8             C         488
   9             C         479
   10            C         530
   11            C         508
   12            C         426
   13            C         546
   14            C         474
   15            C         554
   16            C         558
   17            C         569
   18            C         548
   19            C         456
   20            C         455
   21            C         449
   22            C         572
   23            C         453
   24            C         452
   25            C         428}},
 '6z1m': {'pocket0': {'pred': 1,
   'Volume': 2248.598,
   'SASA': 1102.949,
   'Druggability Score': 0.129,
   'logitProb': 0.523,
   'nmaScore': 0.996,
   'hitScore': 0.618,
   'residues':    auth_asym_id auth_seq_id
   0             A         231
   1             A         245
   2             A         184
   3             A         235
   4             A          51
   5             A         237
   6             A          49
   7             A         236
   8             A         358
   9             A         232
   10            A         414
   11            A         183
   12            A         127
   13            A          43
   14            A         304
   15            A         248
   16            A         227
   17            A         174
   18            A         418
   19            A         241
   20            A          25
   21            A         182
   22            A         404
   23            A          50
   24            A         178
   25            A         185
   26            A         412
   27            A         413
   28            A         177
   29            A         190
   30            A         411
   31            A         170
   32            A         305
   33            A          48
   34            A         244
   35            A         240
   36            A         233
   37            A         126
   38            A         171
   39            A         420},
  'pocket1': {'pred': 1,
   'Volume': 511.99,
   'SASA': 335.816,
   'Druggability Score': 0.714,
   'logitProb': 0.677,
   'nmaScore': 0.227,
   'hitScore': 0.587,
   'residues':    auth_asym_id auth_seq_id
   0             A         292
   1             A         203
   2             A         199
   3             A         252
   4             A         206
   5             A         251
   6             A         296
   7             A         202
   8             A         271
   9             A         172
   10            A         264
   11            A         226
   12            A         176
   13            A         255
   14            A         295
   15            A         224
   16            A         173
   17            A         169}},
 '7yg5': {'pocket0': {'pred': 1,
   'Volume': 608.234,
   'SASA': 328.383,
   'Druggability Score': 0.848,
   'logitProb': 0.783,
   'nmaScore': 0.144,
   'hitScore': 0.655,
   'residues':    auth_asym_id auth_seq_id
   0             A        1616
   1             A        1283
   2             A        1617
   3             A        1269
   4             A        1620
   5             A        1713
   6             A        1279
   7             A        1282
   8             A        1286
   9             A        1709
   10            A        1621
   11            A        1613
   12            A        1712
   13            A        1266}},
 '7zpe': {'pocket0': {'pred': 1,
   'Volume': 290.446,
   'SASA': 168.002,
   'Druggability Score': 0.209,
   'logitProb': 0.783,
   'nmaScore': 0.165,
   'hitScore': 0.659,
   'residues':    auth_asym_id auth_seq_id
   0             A         102
   1             A          99
   2             A         170
   3             A          75
   4             A         129
   5             A         167
   6             A         128
   7             A         166
   8             A         171
   9             A         132
   10            A          72
   11            A          71}},
 '8crc': {'pocket0': {'pred': 1,
   'Volume': 679.406,
   'SASA': 418.18,
   'Druggability Score': 0.279,
   'logitProb': 0.376,
   'nmaScore': 1.0,
   'hitScore': 0.501,
   'residues':    auth_asym_id auth_seq_id
   0             A         450
   1             A         409
   2             A         462
   3             A         451
   4             A         510
   5             A         447
   6             A         505
   7             A         460
   8             A         508
   9             A         443
   10            A         507
   11            A         509
   12            A         506
   13            A         526
   14            A         445
   15            A         527
   16            A         452},
  'pocket1': {'pred': 1,
   'Volume': 435.767,
   'SASA': 296.493,
   'Druggability Score': 0.265,
   'logitProb': 0.483,
   'nmaScore': 0.846,
   'hitScore': 0.555,
   'residues':   auth_asym_id auth_seq_id
   0            A         557
   1            A         559
   2            A         410
   3            A         406
   4            A         553
   5            A         540
   6            A         551
   7            A         407
   8            A         542}},
 '8f4s': {'pocket0': {'pred': 1,
   'Volume': 1497.231,
   'SASA': 695.878,
   'Druggability Score': 0.738,
   'logitProb': 0.801,
   'nmaScore': 0.173,
   'hitScore': 0.675,
   'residues':    auth_asym_id auth_seq_id
   0             A        6917
   1             A        6949
   2             A        6931
   3             A        6909
   4             A        6947
   5             A        6951
   6             A        6957
   7             A        6953
   8             A        6927
   9             A        6912
   10            A        6910
   11            A        6894
   12            A        6958
   13            A        6868
   14            A        6896
   15            A        7088
   16            A        6916
   17            A        6954
   18            A        6869
   19            A        6918
   20            A        6950
   21            A        6914
   22            A        6898
   23            A        6922
   24            A        6929
   25            A        6866
   26            A        6897
   27            A        6895
   28            A        6911
   29            A        6913}},
 '8jp0': {'pocket0': {'pred': 1,
   'Volume': 374.703,
   'SASA': 273.097,
   'Druggability Score': 0.472,
   'logitProb': 0.744,
   'nmaScore': 0.119,
   'hitScore': 0.619,
   'residues':   auth_asym_id auth_seq_id
   0            A         206
   1            A         210
   2            A         832
   3            A         839
   4            A         836
   5            A         244
   6            A         835
   7            A         245
   8            A         207
   9            A         248}},
 '8qni': {'pocket0': {'pred': 1,
   'Volume': 1703.293,
   'SASA': 807.696,
   'Druggability Score': 0.749,
   'logitProb': 0.669,
   'nmaScore': 0.474,
   'hitScore': 0.63,
   'residues':    auth_asym_id auth_seq_id
   0             A         261
   1             A         236
   2             A         148
   3             A         293
   4             A         145
   5             A         149
   6             A         142
   7             A         220
   8             A         232
   9             A         295
   10            A         257
   11            A         292
   12            A         262
   13            A         258
   14            A         224
   15            A         222
   16            A         287
   17            A         291
   18            A         141
   19            A         294
   20            A         240
   21            A         254
   22            A         263
   23            A         264
   24            A         335
   25            A         239
   26            A         368
   27            A         288
   28            A         272
   29            A         138
   30            A         144
   31            A         235
   32            A         364
   33            A         268
   34            A         218
   35            A         260
   36            A         363
   37            A         359
   38            A         369
   39            A         255
   40            A         219
   41            A         221
   42            A         152
   43            A         362
   44            A         367
   45            A         366}},
 '8uk6': {'pocket0': {'pred': 1,
   'Volume': 1013.8,
   'SASA': 484.166,
   'Druggability Score': 0.517,
   'logitProb': 0.663,
   'nmaScore': 0.263,
   'hitScore': 0.583,
   'residues':    auth_asym_id auth_seq_id
   0             A         448
   1             A         275
   2             A         458
   3             A         255
   4             A         417
   5             A         405
   6             A         468
   7             A         483
   8             A         289
   9             A         440
   10            A         257
   11            A         403
   12            A         444
   13            A         456
   14            A         291
   15            A         258
   16            A         459
   17            A         462
   18            A         486
   19            A         268
   20            A         469
   21            A         323
   22            A         256
   23            A         443
   24            A         472
   25            A         441
   26            A         457
   27            A         445
   28            A         465
   29            A         447
   30            A         271
   31            A         259},
  'pocket1': {'pred': 1,
   'Volume': 1061.007,
   'SASA': 443.879,
   'Druggability Score': 0.6,
   'logitProb': 0.783,
   'nmaScore': 0.105,
   'hitScore': 0.648,
   'residues':    auth_asym_id auth_seq_id
   0             A         495
   1             A         497
   2             A         493
   3             A         518
   4             A         520
   5             A         700
   6             A         262
   7             A         264
   8             A         699
   9             A         498
   10            A         268
   11            A         496
   12            A         494
   13            A         519
   14            A         302
   15            A         703
   16            A         513
   17            A         701
   18            A         501
   19            A         517
   20            A         259
   21            A         261
   22            A         265
   23            A         263}},
 '8v81': {'pocket0': {'pred': 1,
   'Volume': 351.637,
   'SASA': 192.926,
   'Druggability Score': 0.535,
   'logitProb': 0.716,
   'nmaScore': 0.193,
   'hitScore': 0.611,
   'residues':    auth_asym_id auth_seq_id
   0             A        1143
   1             A        1142
   2             A        1001
   3             A         921
   4             A         923
   5             A        1138
   6             A         920
   7             A        1000
   8             A        1139
   9             A         924
   10            A        1004
   11            A        1135
   12            A         344
   13            A        1008
   14            A        1005}},
 '9fsj': {'pocket0': {'pred': 1,
   'Volume': 831.115,
   'SASA': 425.941,
   'Druggability Score': 0.851,
   'logitProb': 0.859,
   'nmaScore': 0.617,
   'hitScore': 0.811,
   'residues':    auth_asym_id auth_seq_id
   0             A         456
   1             A         635
   2             A         628
   3             A         452
   4             A         519
   5             A         515
   6             A         504
   7             A         518
   8             A         631
   9             A         455
   10            A         505
   11            A         506
   12            A         620
   13            A         389
   14            A         623
   15            A         386
   16            A         385
   17            A         382
   18            A         521
   19            A         508
   20            A         611
   21            A         500
   22            A         499
   23            A         510
   24            A         496
   25            A         503}},
 '9oul': {'pocket0': {'pred': 1,
   'Volume': 884.505,
   'SASA': 513.164,
   'Druggability Score': 0.876,
   'logitProb': 0.814,
   'nmaScore': 0.497,
   'hitScore': 0.75,
   'residues':    auth_asym_id auth_seq_id
   0             C         313
   1             C         288
   2             C         284
   3             C         265
   4             C         360
   5             C         334
   6             C         426
   7             C         287
   8             C         289
   9             C         290
   10            C         321
   11            C         294
   12            C         314
   13            C         315
   14            C         264
   15            C         261
   16            C         344
   17            C         317
   18            C         318
   19            C         319
   20            C         424
   21            C         268
   22            C         345
   23            C         273
   24            C         283
   25            C         339
   26            C         337}},
 '9ow9': {'pocket0': {'pred': 1,
   'Volume': 2678.462,
   'SASA': 1449.088,
   'Druggability Score': 0.676,
   'logitProb': 0.801,
   'nmaScore': 0.639,
   'hitScore': 0.768,
   'residues':    auth_asym_id auth_seq_id
   0             A         723
   1             A         528
   2             A         527
   3             A         854
   4             A         708
   5             A         853
   6             A         825
   7             A         850
   8             A         559
   9             A         917
   10            A         554
   11            A         844
   12            A         847
   13            A         706
   14            A         852
   15            A         913
   16            A         829
   17            A         570
   18            A         705
   19            A         846
   20            A         563
   21            A         530
   22            A         849
   23            A         891
   24            A         558
   25            A         707
   26            A         828
   27            A         529
   28            A         730
   29            A         552
   30            A         732
   31            A         555
   32            A         565
   33            A         843
   34            A         551
   35            A         857
   36            A         726
   37            A         910
   38            A         731
   39            A         737
   40            A         914
   41            A         728
   42            A         727
   43            A         826
   44            A         851
   45            A         918
   46            A         725
   47            A         711
   48            A         822
   49            A         724
   50            A         735}}}

## PASSer

In [19]:
passer_resultsf = "PASSer/passer_results.pkl"

with open(passer_resultsf, "rb") as f:
    passer_results = {k1: {k2: v2 for k2, v2 in v1.items() if k2 in news} for k1, v1 in pickle.load(f).items()}

len(passer_results), tuple(len(v) for v in passer_results.values()), passer_results

(3,
 (9, 9, 9),
 {'ensemble': {'7gqu': {'20': {'prob/score': 50.99665205925703,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         916                 ?
     1             A         917                 ?
     4             A         920                 ?
     5             A         727                 ?
     6             A         919                 ?
     8             A         555                 ?
     9             A         552                 ?
     11            A         551                 ?
     12            A         846                 ?
     13            A         845                 ?
     15            A         849                 ?
     17            A         913                 ?
     25            A         706                 ?
     26            A         570                 ?
     27            A         726                 ?
     29            A         725                 ?
     30            A         898                 ?
     31            A         895                 ?
     32            A         730                 ?
     33            A         729                 ?
     34            A         921                 ?
     37            A         923                 ?
     46            A         728                 ?
     55            A         731                 ?
     58            A         575                 ?
     65            A         891                 ?
     68            A         914                 ?
     70            A         704                 ?
     74            A         550                 ?
     90            A         571                 ?
     93            A         918                 ?
     94            A         572                 ?},
    '7': {'prob/score': 49.41235993755981,
     'residues':     auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0              A         601                 ?
     1              A         829                 ?
     3              A         573                 ?
     4              A         577                 ?
     6              A         578                 ?
     ..           ...         ...               ...
     203            A         923                 ?
     204            A         551                 ?
     208            A         547                 ?
     215            A         883                 ?
     228            A         801                 ?

     [78 rows x 3 columns]},
    '26': {'prob/score': 23.19833954970818,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         908                 ?
     1             A         907                 ?
     2             A         942                 ?
     4             A         906                 ?
     7             A         938                 ?
     10            A         931                 ?
     19            A         939                 ?
     23            A         911                 ?
     27            A         930                 ?},
    '25': {'prob/score': 20.856095535418717,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         753                 ?
     1             A         740                 ?
     2             A         865                 ?
     3             A         752                 ?
     4             A         764                 ?
     7             A         835                 ?
     8             A         861                 ?
     18            A         763                 ?
     20            A         834                 ?
     21            A         863                 ?
     27            A         862                 ?
     29            A         767                 ?
     31            A         765                 ?},
    '13': {'prob/score': 20.51994323519466,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         770                 ?
     1             A         822                 ?
     3             A         851                 ?
     4             A         772                 ?
     5             A         842                 ?
     6             A         771                 ?
     7             A         838                 ?
     8             A         843                 ?
     9             A         874                 ?
     15            A         821                 ?
     18            A         841                 ?
     20            A         840                 ?},
    '2': {'prob/score': 17.54845840478083,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         782                 ?
     2             A         786                 ?
     4             A         783                 ?
     5             A         745                 ?
     6             A         747                 ?
     7             A         748                 ?
     10            A         779                 ?
     11            A         746                 ?
     18            A         744                 ?
     26            A         778                 ?},
    '17': {'prob/score': 14.923921372246696,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         916                 ?
     1             A         901                 ?
     3             A         915                 ?
     4             A         897                 ?
     5             A         898                 ?
     6             A         894                 ?
     8             A         912                 ?
     9             A         907                 ?
     13            A         905                 ?
     18            A         911                 ?},
    '24': {'prob/score': 14.705987280467525,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         620                 ?
     1             A         618                 ?
     2             A         623                 ?
     4             A         622                 ?
     6             A         621                 ?
     7             A         599                 ?
     10            A         645                 ?
     16            A         642                 ?
     17            A         644                 ?
     21            A         603                 ?},
    '27': {'prob/score': 12.084111606236547,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         921                 ?
     1             A         529                 ?
     4             A         527                 ?
     10            A         551                 ?
     13            A         923                 ?
     14            A         924                 ?
     19            A         922                 ?},
    '23': {'prob/score': 11.598408490681322,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         885                 ?
     1            A         884                 ?
     6            A         676                 ?
     7            A         675                 ?},
    '8': {'prob/score': 9.782421146519482,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         555                 ?
     3             A         529                 ?
     6             A         551                 ?
     7             A         527                 ?
     8             A         528                 ?
     9             A         554                 ?
     11            A         558                 ?
     15            A         559                 ?
     16            A         724                 ?
     19            A         563                 ?
     25            A         565                 ?},
    '15': {'prob/score': 9.648617967104656,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         551                 ?
     1             A         528                 ?
     2             A         549                 ?
     3             A         527                 ?
     7             A         532                 ?
     10            A         531                 ?
     11            A         548                 ?
     12            A         537                 ?
     16            A         923                 ?},
    '18': {'prob/score': 9.595284333408927,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         887                 ?
     1             A         712                 ?
     2             A         716                 ?
     6             A         885                 ?
     8             A         676                 ?
     9             A         713                 ?
     17            A         709                 ?},
    '14': {'prob/score': 8.403278334299102,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         816                 ?
     3             A         762                 ?
     8             A         766                 ?
     11            A         813                 ?
     15            A         832                 ?
     16            A         815                 ?
     19            A         790                 ?
     24            A         760                 ?
     25            A         814                 ?},
    '9': {'prob/score': 8.249239697579469,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         772                 ?
     2             A         873                 ?
     3             A         776                 ?
     4             A         773                 ?
     6             A         779                 ?
     7             A         775                 ?
     10            A         839                 ?
     11            A         742                 ?
     13            A         840                 ?
     16            A         872                 ?
     19            A         871                 ?},
    '12': {'prob/score': 7.974500021373387,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         708                 ?
     1             A         712                 ?
     3             A         887                 ?
     6             A         709                 ?
     10            A         890                 ?
     13            A         891                 ?
     15            A         894                 ?},
    '19': {'prob/score': 7.825264678103849,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         761                 ?
     1             A         751                 ?
     2             A         754                 ?
     4             A         747                 ?
     11            A         787                 ?},
    '1': {'prob/score': 7.762596171232872,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         901                 ?
     3             A         904                 ?
     4             A         905                 ?
     9             A         897                 ?
     12            A         900                 ?},
    '3': {'prob/score': 7.009097188711166,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         914                 ?
     1             A         915                 ?
     4             A         907                 ?
     5             A         911                 ?
     9             A         922                 ?
     10            A         918                 ?
     11            A         920                 ?
     14            A         930                 ?
     17            A         917                 ?},
    '6': {'prob/score': 6.528391333267791,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         615                 ?
     1            A         613                 ?
     5            A         614                 ?
     6            A         610                 ?},
    '22': {'prob/score': 5.526737066975329,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         564                 ?
     1             A         663                 ?
     3             A         588                 ?
     7             A         590                 ?
     8             A         561                 ?
     10            A         661                 ?
     11            A         657                 ?
     13            A         662                 ?},
    '21': {'prob/score': 5.438909065560438,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         543                 ?
     2            A         637                 ?
     4            A         586                 ?
     5            A         615                 ?
     6            A         613                 ?
     8            A         614                 ?},
    '5': {'prob/score': 5.067528717336245,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         721                 ?
     1             A         566                 ?
     2             A         564                 ?
     3             A         691                 ?
     6             A         565                 ?
     9             A         696                 ?
     13            A         695                 ?
     16            A         563                 ?},
    '4': {'prob/score': 4.62313298630761,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         579                 ?
     1             A         578                 ?
     3             A         544                 ?
     5             A         546                 ?
     6             A         608                 ?
     8             A         582                 ?
     9             A         609                 ?
     10            A         614                 ?
     11            A         612                 ?
     12            A         543                 ?},
    '11': {'prob/score': 4.5262425999681,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         811                 ?
     1             A         808                 ?
     2             A         604                 ?
     3             A         807                 ?
     5             A         829                 ?
     10            A         601                 ?
     11            A         605                 ?
     12            A         608                 ?},
    '16': {'prob/score': 4.503542592283338,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         884                 ?
     1             A         676                 ?
     4             A         678                 ?
     7             A         675                 ?
     9             A         883                 ?
     13            A         882                 ?},
    '10': {'prob/score': 4.307141790923197,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         534                 ?
     1             A         537                 ?
     3             A         532                 ?
     5             A         538                 ?
     6             A         541                 ?
     12            A         533                 ?}},
   '7yg5': {'46': {'prob/score': 58.27678069472313,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         479                 ?
     1             A         575                 ?
     2             A         482                 ?
     6             A         474                 ?
     7             A         530                 ?
     8             A         534                 ?
     10            A         548                 ?
     11            A         519                 ?
     12            A         572                 ?
     15            A         522                 ?
     17            A         523                 ?
     18            A         544                 ?
     19            A         535                 ?
     23            A         526                 ?
     24            A         541                 ?
     26            A         538                 ?
     27            A         478                 ?
     29            A         578                 ?
     32            A         484                 ?
     33            A         480                 ?
     34            A         579                 ?
     35            A         483                 ?
     49            A         473                 ?
     56            A         470                 ?
     59            A         582                 ?
     61            A         476                 ?
     83            A         387                 ?
     85            A         581                 ?
     93            A         540                 ?},
    '36': {'prob/score': 51.058829203248024,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A        1765                 ?
     1             A        1761                 ?
     3             A        1869                 ?
     14            A        1786                 ?
     16            A        1782                 ?
     19            A        1769                 ?
     21            A        1790                 ?
     22            A        1870                 ?
     24            A        1787                 ?
     25            A        1866                 ?
     28            A        1766                 ?
     32            A        1777                 ?
     34            A        1768                 ?
     35            A        1789                 ?
     39            A        1868                 ?
     40            A        1865                 ?
     52            A        1793                 ?
     53            A        1764                 ?
     55            A        1812                 ?
     57            A        1783                 ?
     59            A        1815                 ?
     67            A        1811                 ?},
    '113': {'prob/score': 48.98447059094906,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A        1249                 ?
     3             A        1251                 ?
     4             A        1691                 ?
     5             A        1252                 ?
     6             A        1255                 ?
     10            A        1693                 ?
     13            A        1694                 ?
     14            A        1631                 ?
     15            A        1678                 ?
     16            A        1686                 ?
     17            A        1687                 ?
     22            A        1690                 ?
     31            A        1679                 ?
     32            A        1695                 ?
     40            A        1681                 ?
     41            A        1176                 ?
     43            A        1178                 ?
     47            A        1628                 ?
     49            A        1680                 ?},
    '106': {'prob/score': 44.90342438220978,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A        1299                 ?
     1             A        1413                 ?
     2             A        1414                 ?
     4             A         592                 ?
     5             A        1417                 ?
     10            A        1409                 ?
     13            A        1292                 ?

Top 3 pockets for each PDB are predicted positive.

In [20]:
passer_results = {
    model: {
        pdb: {
            pocket: {
                "pred": 1 if i <=2 else 0,
                **pocketd
            }
            for i, (pocket, pocketd) in enumerate( 
                sorted(
                    pockets.items(), 
                    key=lambda x: x[-1]["prob/score"], 
                    reverse=True
                )
            )
        }
        for pdb, pockets in pdbs.items()
    }
    for model, pdbs in passer_results.items()
}
passer_results

{'ensemble': {'7gqu': {'20': {'pred': 1,
    'prob/score': 50.99665205925703,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         916                 ?
    1             A         917                 ?
    4             A         920                 ?
    5             A         727                 ?
    6             A         919                 ?
    8             A         555                 ?
    9             A         552                 ?
    11            A         551                 ?
    12            A         846                 ?
    13            A         845                 ?
    15            A         849                 ?
    17            A         913                 ?
    25            A         706                 ?
    26            A         570                 ?
    27            A         726                 ?
    29            A         725                 ?
    30            A         898                 ?
    31            A         895                 ?
    32            A         730                 ?
    33            A         729                 ?
    34            A         921                 ?
    37            A         923                 ?
    46            A         728                 ?
    55            A         731                 ?
    58            A         575                 ?
    65            A         891                 ?
    68            A         914                 ?
    70            A         704                 ?
    74            A         550                 ?
    90            A         571                 ?
    93            A         918                 ?
    94            A         572                 ?},
   '7': {'pred': 1,
    'prob/score': 49.41235993755981,
    'residues':     auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0              A         601                 ?
    1              A         829                 ?
    3              A         573                 ?
    4              A         577                 ?
    6              A         578                 ?
    ..           ...         ...               ...
    203            A         923                 ?
    204            A         551                 ?
    208            A         547                 ?
    215            A         883                 ?
    228            A         801                 ?

    [78 rows x 3 columns]},
   '26': {'pred': 1,
    'prob/score': 23.19833954970818,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         908                 ?
    1             A         907                 ?
    2             A         942                 ?
    4             A         906                 ?
    7             A         938                 ?
    10            A         931                 ?
    19            A         939                 ?
    23            A         911                 ?
    27            A         930                 ?},
   '25': {'pred': 0,
    'prob/score': 20.856095535418717,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         753                 ?
    1             A         740                 ?
    2             A         865                 ?
    3             A         752                 ?
    4             A         764                 ?
    7             A         835                 ?
    8             A         861                 ?
    18            A         763                 ?
    20            A         834                 ?
    21            A         863                 ?
    27            A         862                 ?
    29            A         767                 ?
    31            A         765                 ?},
   '13': {'pred': 0,
    'prob/score': 20.51994323519466,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         770                 ?
    1             A         822                 ?
    3             A         851                 ?
    4             A         772                 ?
    5             A         842                 ?
    6             A         771                 ?
    7             A         838                 ?
    8             A         843                 ?
    9             A         874                 ?
    15            A         821                 ?
    18            A         841                 ?
    20            A         840                 ?},
   '2': {'pred': 0,
    'prob/score': 17.54845840478083,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         782                 ?
    2             A         786                 ?
    4             A         783                 ?
    5             A         745                 ?
    6             A         747                 ?
    7             A         748                 ?
    10            A         779                 ?
    11            A         746                 ?
    18            A         744                 ?
    26            A         778                 ?},
   '17': {'pred': 0,
    'prob/score': 14.923921372246696,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         916                 ?
    1             A         901                 ?
    3             A         915                 ?
    4             A         897                 ?
    5             A         898                 ?
    6             A         894                 ?
    8             A         912                 ?
    9             A         907                 ?
    13            A         905                 ?
    18            A         911                 ?},
   '24': {'pred': 0,
    'prob/score': 14.705987280467525,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         620                 ?
    1             A         618                 ?
    2             A         623                 ?
    4             A         622                 ?
    6             A         621                 ?
    7             A         599                 ?
    10            A         645                 ?
    16            A         642                 ?
    17            A         644                 ?
    21            A         603                 ?},
   '27': {'pred': 0,
    'prob/score': 12.084111606236547,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         921                 ?
    1             A         529                 ?
    4             A         527                 ?
    10            A         551                 ?
    13            A         923                 ?
    14            A         924                 ?
    19            A         922                 ?},
   '23': {'pred': 0,
    'prob/score': 11.598408490681322,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         885                 ?
    1            A         884                 ?
    6            A         676                 ?
    7            A         675                 ?},
   '8': {'pred': 0,
    'prob/score': 9.782421146519482,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         555                 ?
    3             A         529                 ?
    6             A         551                 ?
    7             A         527                 ?
    8             A         528                 ?
    9             A         554                 ?
    11            A         558                 ?
    15            A         559                 ?
    16            A         724                 ?
    19            A         563                 ?
    25            A         565                 ?},
   '15': {'pred': 0,
    'prob/score': 9.648617967104656,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         551                 ?
    1             A         528                 ?
    2             A         549                 ?
    3             A         527                 ?
    7             A         532                 ?
    10            A         531                 ?
    11            A         548                 ?
    12            A         537                 ?
    16            A         923                 ?},
   '18': {'pred': 0,
    'prob/score': 9.595284333408927,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         887                 ?
    1             A         712                 ?
    2             A         716                 ?
    6             A         885                 ?
    8             A         676                 ?
    9             A         713                 ?
    17            A         709                 ?},
   '14': {'pred': 0,
    'prob/score': 8.403278334299102,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         816                 ?
    3             A         762                 ?
    8             A         766                 ?
    11            A         813                 ?
    15            A         832                 ?
    16            A         815                 ?
    19            A         790                 ?
    24            A         760                 ?
    25            A         814                 ?},
   '9': {'pred': 0,
    'prob/score': 8.249239697579469,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         772                 ?
    2             A         873                 ?
    3             A         776                 ?
    4             A         773                 ?
    6             A         779                 ?
    7             A         775                 ?
    10            A         839                 ?
    11            A         742                 ?
    13            A         840                 ?
    16            A         872                 ?
    19            A         871                 ?},
   '12': {'pred': 0,
    'prob/score': 7.974500021373387,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         708                 ?
    1             A         712                 ?
    3             A         887                 ?
    6             A         709                 ?
    10            A         890                 ?
    13            A         891                 ?
    15            A         894                 ?},
   '19': {'pred': 0,
    'prob/score': 7.825264678103849,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         761                 ?
    1             A         751                 ?
    2             A         754                 ?
    4             A         747                 ?
    11            A         787                 ?},
   '1': {'pred': 0,
    'prob/score': 7.762596171232872,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         901                 ?
    3             A         904                 ?
    4             A         905                 ?
    9             A         897                 ?
    12            A         900                 ?},
   '3': {'pred': 0,
    'prob/score': 7.009097188711166,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         914                 ?
    1             A         915                 ?
    4             A         907                 ?
    5             A         911                 ?
    9             A         922                 ?
    10            A         918                 ?
    11            A         920                 ?
    14            A         930                 ?
    17            A         917                 ?},
   '6': {'pred': 0,
    'prob/score': 6.528391333267791,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         615                 ?
    1            A         613                 ?
    5            A         614                 ?
    6            A         610                 ?},
   '22': {'pred': 0,
    'prob/score': 5.526737066975329,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         564                 ?
    1             A         663                 ?
    3             A         588                 ?
    7             A         590                 ?
    8             A         561                 ?
    10            A         661                 ?
    11            A         657                 ?
    13            A         662                 ?},
   '21': {'pred': 0,
    'prob/score': 5.438909065560438,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         543                 ?
    2            A         637                 ?
    4            A         586                 ?
    5            A         615                 ?
    6            A         613                 ?
    8            A         614                 ?},
   '5': {'pred': 0,
    'prob/score': 5.067528717336245,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         721                 ?
    1             A         566                 ?
    2             A         564                 ?
    3             A         691                 ?
    6             A         565                 ?
    9             A         696                 ?
    13            A         695                 ?
    16            A         563                 ?},
   '4': {'pred': 0,
    'prob/score': 4.62313298630761,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         579                 ?
    1             A         578                 ?
    3             A         544                 ?
    5             A         546                 ?
    6             A         608                 ?
    8             A         582                 ?
    9             A         609                 ?
    10            A         614                 ?
    11            A         612                 ?
    12            A         543                 ?},
   '11': {'pred': 0,
    'prob/score': 4.5262425999681,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         811                 ?
    1             A         808                 ?
    2             A         604                 ?
    3             A         807                 ?
    5             A         829                 ?
    10            A         601                 ?
    11            A         605                 ?
    12            A         608                 ?},
   '16': {'pred': 0,
    'prob/score': 4.503542592283338,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         884                 ?
    1             A         676                 ?
    4             A         678                 ?
    7             A         675                 ?
    9             A         883                 ?
    13            A         882                 ?},
   '10': {'pred': 0,
    'prob/score': 4.307141790923197,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         534                 ?
    1             A         537                 ?
    3             A         532                 ?
    5             A         538                 ?
    6             A         541                 ?
    12            A         533                 ?}},
  '7yg5': {'46': {'pred': 1,
    'prob/score': 58.27678069472313,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         479                 ?
    1             A         575                 ?
    2             A         482                 ?
    6             A         474                 ?
    7             A         530                 ?
    8             A         534                 ?
    10            A         548                 ?
    11            A         519                 ?
    12            A         572                 ?
    15            A         522                 ?
    17            A         523                 ?
    18            A         544                 ?
    19            A         535                 ?
    23            A         526                 ?
    24            A         541                 ?
    26            A         538                 ?
    27            A         478                 ?
    29            A         578                 ?
    32            A         484                 ?
    33            A         480                 ?
    34            A         579                 ?
    35            A         483                 ?
    49            A         473                 ?
    56            A         470                 ?
    59            A         582                 ?
    61            A         476                 ?
    83            A         387                 ?
    85            A         581                 ?
    93            A         540                 ?},
   '36': {'pred': 1,
    'prob/score': 51.058829203248024,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A        1765                 ?
    1             A        1761                 ?
    3             A        1869                 ?
    14            A        1786                 ?
    16            A        1782                 ?
    19            A        1769                 ?
    21            A        1790                 ?
    22            A        1870                 ?
    24            A        1787                 ?
    25            A        1866                 ?
    28            A        1766                 ?
    32            A        1777                 ?
    34            A        1768                 ?
    35            A        1789                 ?
    39            A        1868                 ?
    40            A        1865                 ?
    52            A        1793                 ?
    53            A        1764                 ?
    55            A        1812                 ?
    57            A        1783                 ?
    59            A        1815                 ?
    67            A        1811                 ?},
   '113': {'pred': 1,
    'prob/score': 48.98447059094906,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A        1249                 ?
    3             A        1251                 ?
    4             A        1691                 ?
    5             A        1252                 ?
    6             A        1255                 ?
    10            A        1693                 ?
    13            A        1694                 ?
    14            A        1631                 ?
    15            A        1678                 ?
    16            A        1686                 ?
    17            A        1687                 ?
    22            A        1690                 ?
    31            A        1679                 ?
    32            A        1695                 ?
    40            A        1681                 ?
    41            A        1176                 ?
    43            A        1178                 ?
    47            A        1628                 ?
    49            A        1680                 ?},
   '106': {'pred': 0,
    'prob/score': 44.90342438220978,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A        1299                 ?
    1             A        1413                 ?
    2             A        1414                 ?
    4             A         592                 ?
    5             A        1417                 ?
    10            A        1409                 ?

## DeepAllo

In [21]:
deepallo_resultsf = "DeepAllo/deepallo_results.pkl"

with open(deepallo_resultsf, "rb") as f:
    deepallo_results = pickle.load(f)

len(deepallo_results), deepallo_results

(9,
 {'7gqu': {'pocket1': {'pred': 1,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         601                 ?
    1             A         829                 ?
    2             A         573                 ?
    3             A         577                 ?
    4             A         578                 ?
    ..          ...         ...               ...
    73            A         923                 ?
    74            A         551                 ?
    75            A         547                 ?
    76            A         883                 ?
    77            A         801                 ?

    [78 rows x 3 columns],
    'prob': 0.2415745109319687},
   'pocket2': {'pred': 1,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         916                 ?
    1             A         917                 ?
    2             A         920                 ?
    3             A         727                 ?
    4             A         919                 ?
    5             A         555                 ?
    6             A         552                 ?
    7             A         551                 ?
    8             A         846                 ?
    9             A         845                 ?
    10            A         849                 ?
    11            A         913                 ?
    12            A         706                 ?
    13            A         570                 ?
    14            A         726                 ?
    15            A         725                 ?
    16            A         898                 ?
    17            A         895                 ?
    18            A         730                 ?
    19            A         729                 ?
    20            A         921                 ?
    21            A         923                 ?
    22            A         728                 ?
    23            A         731                 ?
    24            A         575                 ?
    25            A         891                 ?
    26            A         914                 ?
    27            A         704                 ?
    28            A         550                 ?
    29            A         571                 ?
    30            A         918                 ?
    31            A         572                 ?,
    'prob': 0.1223275363445282},
   'pocket23': {'pred': 1,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         885                 ?
    1            A         884                 ?
    2            A         676                 ?
    3            A         675                 ?,
    'prob': 0.08387450873851776},
   'pocket3': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         901                 ?
    1            A         904                 ?
    2            A         905                 ?
    3            A         897                 ?
    4            A         900                 ?},
   'pocket4': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         579                 ?
    1            A         578                 ?
    2            A         544                 ?
    3            A         546                 ?
    4            A         608                 ?
    5            A         582                 ?
    6            A         609                 ?
    7            A         614                 ?
    8            A         612                 ?
    9            A         543                 ?},
   'pocket5': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         782                 ?
    1            A         786                 ?
    2            A         783                 ?
    3            A         745                 ?
    4            A         747                 ?
    5            A         748                 ?
    6            A         779                 ?
    7            A         746                 ?
    8            A         744                 ?
    9            A         778                 ?},
   'pocket6': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         914                 ?
    1            A         915                 ?
    2            A         907                 ?
    3            A         911                 ?
    4            A         922                 ?
    5            A         918                 ?
    6            A         920                 ?
    7            A         930                 ?
    8            A         917                 ?},
   'pocket7': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         721                 ?
    1            A         566                 ?
    2            A         564                 ?
    3            A         691                 ?
    4            A         565                 ?
    5            A         696                 ?
    6            A         695                 ?
    7            A         563                 ?},
   'pocket8': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         615                 ?
    1            A         613                 ?
    2            A         614                 ?
    3            A         610                 ?},
   'pocket9': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         555                 ?
    1             A         529                 ?
    2             A         551                 ?
    3             A         527                 ?
    4             A         528                 ?
    5             A         554                 ?
    6             A         558                 ?
    7             A         559                 ?
    8             A         724                 ?
    9             A         563                 ?
    10            A         565                 ?},
   'pocket10': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         772                 ?
    1             A         873                 ?
    2             A         776                 ?
    3             A         773                 ?
    4             A         779                 ?
    5             A         775                 ?
    6             A         839                 ?
    7             A         742                 ?
    8             A         840                 ?
    9             A         872                 ?
    10            A         871                 ?},
   'pocket11': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         534                 ?
    1            A         537                 ?
    2            A         532                 ?
    3            A         538                 ?
    4            A         541                 ?
    5            A         533                 ?},
   'pocket12': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         811                 ?
    1            A         808                 ?
    2            A         604                 ?
    3            A         807                 ?
    4            A         829                 ?
    5            A         601                 ?
    6            A         605                 ?
    7            A         608                 ?},
   'pocket13': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         708                 ?
    1            A         712                 ?
    2            A         887                 ?
    3            A         709                 ?
    4            A         890                 ?
    5            A         891                 ?
    6            A         894                 ?},
   'pocket14': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         770                 ?
    1             A         822                 ?
    2             A         851                 ?
    3             A         772                 ?
    4             A         842                 ?
    5             A         771                 ?
    6             A         838                 ?
    7             A         843                 ?
    8             A         874                 ?
    9             A         821                 ?
    10            A         841                 ?
    11            A         840                 ?},
   'pocket15': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         816                 ?
    1            A         762                 ?
    2            A         766                 ?
    3            A         813                 ?
    4            A         832                 ?
    5            A         815                 ?
    6            A         790                 ?
    7            A         760                 ?
    8            A         814                 ?},
   'pocket16': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         551                 ?
    1            A         528                 ?
    2            A         549                 ?
    3            A         527                 ?
    4            A         532                 ?
    5            A         531                 ?
    6            A         548                 ?
    7            A         537                 ?
    8            A         923                 ?},
   'pocket17': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         884                 ?
    1            A         676                 ?
    2            A         678                 ?
    3            A         675                 ?
    4            A         883                 ?
    5            A         882                 ?},
   'pocket18': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         916                 ?
    1            A         901                 ?
    2            A         915                 ?
    3            A         897                 ?
    4            A         898                 ?
    5            A         894                 ?
    6            A         912                 ?
    7            A         907                 ?
    8            A         905                 ?
    9            A         911                 ?},
   'pocket19': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         887                 ?
    1            A         712                 ?
    2            A         716                 ?
    3            A         885                 ?
    4            A         676                 ?
    5            A         713                 ?
    6            A         709                 ?},
   'pocket20': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         761                 ?
    1            A         751                 ?
    2            A         754                 ?
    3            A         747                 ?
    4            A         787                 ?},
   'pocket21': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         543                 ?
    1            A         637                 ?
    2            A         586                 ?
    3            A         615                 ?
    4            A         613                 ?
    5            A         614                 ?},
   'pocket22': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         564                 ?
    1            A         663                 ?
    2            A         588                 ?
    3            A         590                 ?
    4            A         561                 ?
    5            A         661                 ?
    6            A         657                 ?
    7            A         662                 ?},
   'pocket24': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         620                 ?
    1            A         618                 ?
    2            A         623                 ?
    3            A         622                 ?
    4            A         621                 ?
    5            A         599                 ?
    6            A         645                 ?
    7            A         642                 ?
    8            A         644                 ?
    9            A         603                 ?},
   'pocket25': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         753                 ?
    1             A         740                 ?
    2             A         865                 ?
    3             A         752                 ?
    4             A         764                 ?
    5             A         835                 ?
    6             A         861                 ?
    7             A         763                 ?
    8             A         834                 ?
    9             A         863                 ?
    10            A         862                 ?
    11            A         767                 ?
    12            A         765                 ?},
   'pocket26': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         908                 ?
    1            A         907                 ?
    2            A         942                 ?
    3            A         906                 ?
    4            A         938                 ?
    5            A         931                 ?
    6            A         939                 ?
    7            A         911                 ?
    8            A         930                 ?},
   'pocket27': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         921                 ?
    1            A         529                 ?
    2            A         527                 ?
    3            A         551                 ?
    4            A         923                 ?
    5            A         924                 ?
    6            A         922                 ?}},
  '7yg5': {'pocket9': {'pred': 1,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A        1542                 ?
    1            A        1598                 ?
    2            A        1601                 ?
    3            A        1597                 ?
    4            A        1594                 ?
    5            A        1587                 ?,
    'prob': 0.39101290702819824},
   'pocket6': {'pred': 1,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A        1398                 ?
    1             A         561                 ?
    2             A         557                 ?
    3             A        1399                 ?
    4             A        1402                 ?
    5             A        1401                 ?
    6             A         566                 ?
    7             A        1396                 ?
    8             A         564                 ?
    9             A        1310                 ?
    10            A        1306                 ?,
    'prob': 0.37945815920829773},
   'pocket8': {'pred': 1,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         228                 ?
    1            A         229                 ?
    2            A         225                 ?
    3            A         232                 ?
    4            A         303                 ?
    5            A         684                 ?
    6            A         299                 ?
    7            A         688                 ?,
    'prob': 0.36803826689720154},
   'pocket1': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         242                 ?
    1             A         322                 ?
    2             A         326                 ?
    3             A         330                 ?
    4             A         329                 ?
    5             A        1571                 ?
    6             A        1573                 ?
    7             A         270                 ?
    8             A         321                 ?
    9             A         246                 ?
    10            A         323                 ?
    11            A         325                 ?
    12            A        1574                 ?
    13            A        1577                 ?
    14            A         327                 ?
    15            A         269                 ?
    16            A         268                 ?
    17            A         249                 ?
    18            A        1570                 ?
    19            A         245                 ?
    20            A         248                 ?
    21            A         238                 ?
    22            A         235                 ?
    23            A        1569                 ?
    24            A         243                 ?},
   'pocket2': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         708                 ?
    1             A         366                 ?
    2             A         363                 ?
    3             A         598                 ?
    4             A         370                 ?
    5             A         358                 ?
    6             A         367                 ?
    7             A         704                 ?
    8             A         700                 ?
    9             A         354                 ?
    10            A         357                 ?
    11            A         369                 ?
    12            A         606                 ?
    13            A         213                 ?
    14            A         602                 ?
    15            A         217                 ?
    16            A         701                 ?
    17            A         603                 ?
    18            A         599                 ?
    19            A         214                 ?
    20            A         210                 ?
    21            A         373                 ?
    22            A         705                 ?
    23            A         209                 ?},
   'pocket3': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A        1299                 ?
    1             A        1413                 ?
    2             A        1414                 ?
    3             A         592                 ?
    4             A        1417                 ?
    5             A        1409                 ?
    6             A        1292                 ?
    7             A        1295                 ?
    8             A         577                 ?
    9             A         586                 ?
    10            A         540                 ?
    11            A         539                 ?
    12            A         596                 ?
    13            A         589                 ?
    14            A         594                 ?
    15            A         373                 ?
    16            A         598                 ?
    17            A         370                 ?

In [22]:
deepallo_results["8aq6"]

{'pocket3_G': {'pred': 1,
  'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0             G          31                 ?
  1             G          19                 ?
  2             G          18                 ?
  3             G          38                 ?
  4             G          36                 ?
  5             G          29                 ?
  6             G          37                 ?
  7             G          92                 ?
  8             G         162                 ?
  9             G         110                 ?
  10            G          30                 ?
  11            G          22                 ?
  12            G          58                 ?
  13            G          12                 ?,
  'prob': 0.3230498433113098},
 'pocket1_H': {'pred': 1,
  'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0             H         110                 ?
  1             H          92                 ?
  2             H          30                 ?
  3             H         162                 ?
  4             H          19                 ?
  5             H          18                 ?
  6             H          58                 ?
  7             H          29                 ?
  8             H          15                 ?
  9             H          22                 ?
  10            H          38                 ?
  11            H          12                 ?
  12            H          31                 ?
  13            H          37                 ?
  14            H          40                 ?
  15            H          36                 ?
  16            H          77                 ?,
  'prob': 0.17389501631259918},
 'pocket1_G': {'pred': 1,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G          94                 ?
  1            G          43                 ?
  2            G          55                 ?
  3            G          89                 ?
  4            G          53                 ?
  5            G          91                 ?
  6            G          45                 ?
  7            G          81                 ?
  8            G          79                 ?,
  'prob': 0.134913370013237},
 'pocket2_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H         107                 ?
  1            H          54                 ?
  2            H          94                 ?
  3            H          95                 ?
  4            H          93                 ?
  5            H         114                 ?
  6            H         139                 ?
  7            H         141                 ?
  8            H          97                 ?
  9            H         127                 ?,
  'prob': 0.06732850521802902},
 'pocket2_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G         141                 ?
  1            G         107                 ?
  2            G          97                 ?
  3            G          54                 ?
  4            G         139                 ?
  5            G          93                 ?
  6            G         114                 ?
  7            G          94                 ?
  8            G         127                 ?
  9            G          95                 ?,
  'prob': 0.061029814183712006},
 'pocket4_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H         165                 ?
  1            H         146                 ?
  2            H         166                 ?
  3            H         148                 ?
  4            H         147                 ?,
  'prob': 0.06048411875963211},
 'pocket3_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H          68                 ?
  1            H          65                 ?
  2            H          62                 ?
  3            H          88                 ?
  4            H          71                 ?
  5            H          80                 ?
  6            H          74                 ?
  7            H          67                 ?},
 'pocket4_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G          82                 ?
  1            G          62                 ?
  2            G          81                 ?
  3            G          80                 ?
  4            G          74                 ?
  5            G          70                 ?
  6            G          88                 ?},
 'pocket5_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G          65                 ?
  1            G          34                 ?
  2            G          66                 ?
  3            G          36                 ?
  4            G          60                 ?
  5            G          64                 ?
  6            G          69                 ?
  7            G          73                 ?},
 'pocket5_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H          49                 ?
  1            H           4                 ?
  2            H           2                 ?
  3            H          48                 ?
  4            H          46                 ?
  5            H           3                 ?},
 'pocket6_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G         147                 ?
  1            G         166                 ?
  2            G         146                 ?
  3            G         165                 ?
  4            G         148                 ?
  5            G         168                 ?},
 'pocket6_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H         112                 ?
  1            H         132                 ?
  2            H          26                 ?
  3            H          28                 ?
  4            H          27                 ?
  5            H         109                 ?
  6            H         131                 ?
  7            H          76                 ?
  8            H         110                 ?},
 'pocket7_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G          46                 ?
  1            G          49                 ?
  2            G           3                 ?
  3            G           4                 ?
  4            G           2                 ?
  5            G          51                 ?
  6            G          48                 ?},
 'pocket7_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H         108                 ?
  1            H          81                 ?
  2            H          91                 ?
  3            H          89                 ?
  4            H          94                 ?
  5            H          79                 ?
  6            H          77                 ?
  7            H         111                 ?
  8            H          78                 ?},
 'pocket8_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G         142                 ?
  1            G         123                 ?
  2            G         143                 ?
  3            G           1                 ?
  4            G         145                 ?
  5            G          -1                 ?},
 'pocket8_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H           1                 ?
  1            H         145                 ?
  2            H          -1                 ?
  3            H          -2                 ?
  4            H         143                 ?
  5            H         144                 ?
  6            H         147                 ?},
 'pocket9_G': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            G          96                 ?
  1            G         106                 ?
  2            G          94                 ?
  3            G          95                 ?
  4            G          98                 ?
  5            G         105                 ?
  6            G         103                 ?
  7            G         104                 ?},
 'pocket9_H': {'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            H          94                 ?
  1            H         106                 ?
  2            H         108                 ?
  3            H          96                 ?
  4            H         105                 ?
  5            H         104                 ?
  6            H         113                 ?
  7            H          98                 ?
  8            H         103                 ?
  9            H          95                 ?}}

In [23]:
deepallo_results = {
    pdb: {
        pocket: {
            "prob": 0, # will be replaced by the real prob of the top3 pockets if it's in pocketd
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in deepallo_results.items()
}
deepallo_results

{'7gqu': {'pocket1': {'prob': 0.2415745109319687,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         601                 ?
   1             A         829                 ?
   2             A         573                 ?
   3             A         577                 ?
   4             A         578                 ?
   ..          ...         ...               ...
   73            A         923                 ?
   74            A         551                 ?
   75            A         547                 ?
   76            A         883                 ?
   77            A         801                 ?

   [78 rows x 3 columns]},
  'pocket2': {'prob': 0.1223275363445282,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         916                 ?
   1             A         917                 ?
   2             A         920                 ?
   3             A         727                 ?
   4             A         919                 ?
   5             A         555                 ?
   6             A         552                 ?
   7             A         551                 ?
   8             A         846                 ?
   9             A         845                 ?
   10            A         849                 ?
   11            A         913                 ?
   12            A         706                 ?
   13            A         570                 ?
   14            A         726                 ?
   15            A         725                 ?
   16            A         898                 ?
   17            A         895                 ?
   18            A         730                 ?
   19            A         729                 ?
   20            A         921                 ?
   21            A         923                 ?
   22            A         728                 ?
   23            A         731                 ?
   24            A         575                 ?
   25            A         891                 ?
   26            A         914                 ?
   27            A         704                 ?
   28            A         550                 ?
   29            A         571                 ?
   30            A         918                 ?
   31            A         572                 ?},
  'pocket23': {'prob': 0.08387450873851776,
   'pred': 1,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         885                 ?
   1            A         884                 ?
   2            A         676                 ?
   3            A         675                 ?},
  'pocket3': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         901                 ?
   1            A         904                 ?
   2            A         905                 ?
   3            A         897                 ?
   4            A         900                 ?},
  'pocket4': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         579                 ?
   1            A         578                 ?
   2            A         544                 ?
   3            A         546                 ?
   4            A         608                 ?
   5            A         582                 ?
   6            A         609                 ?
   7            A         614                 ?
   8            A         612                 ?
   9            A         543                 ?},
  'pocket5': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         782                 ?
   1            A         786                 ?
   2            A         783                 ?
   3            A         745                 ?
   4            A         747                 ?
   5            A         748                 ?
   6            A         779                 ?
   7            A         746                 ?
   8            A         744                 ?
   9            A         778                 ?},
  'pocket6': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         914                 ?
   1            A         915                 ?
   2            A         907                 ?
   3            A         911                 ?
   4            A         922                 ?
   5            A         918                 ?
   6            A         920                 ?
   7            A         930                 ?
   8            A         917                 ?},
  'pocket7': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         721                 ?
   1            A         566                 ?
   2            A         564                 ?
   3            A         691                 ?
   4            A         565                 ?
   5            A         696                 ?
   6            A         695                 ?
   7            A         563                 ?},
  'pocket8': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         615                 ?
   1            A         613                 ?
   2            A         614                 ?
   3            A         610                 ?},
  'pocket9': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         555                 ?
   1             A         529                 ?
   2             A         551                 ?
   3             A         527                 ?
   4             A         528                 ?
   5             A         554                 ?
   6             A         558                 ?
   7             A         559                 ?
   8             A         724                 ?
   9             A         563                 ?
   10            A         565                 ?},
  'pocket10': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         772                 ?
   1             A         873                 ?
   2             A         776                 ?
   3             A         773                 ?
   4             A         779                 ?
   5             A         775                 ?
   6             A         839                 ?
   7             A         742                 ?
   8             A         840                 ?
   9             A         872                 ?
   10            A         871                 ?},
  'pocket11': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         534                 ?
   1            A         537                 ?
   2            A         532                 ?
   3            A         538                 ?
   4            A         541                 ?
   5            A         533                 ?},
  'pocket12': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         811                 ?
   1            A         808                 ?
   2            A         604                 ?
   3            A         807                 ?
   4            A         829                 ?
   5            A         601                 ?
   6            A         605                 ?
   7            A         608                 ?},
  'pocket13': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         708                 ?
   1            A         712                 ?
   2            A         887                 ?
   3            A         709                 ?
   4            A         890                 ?
   5            A         891                 ?
   6            A         894                 ?},
  'pocket14': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         770                 ?
   1             A         822                 ?
   2             A         851                 ?
   3             A         772                 ?
   4             A         842                 ?
   5             A         771                 ?
   6             A         838                 ?
   7             A         843                 ?
   8             A         874                 ?
   9             A         821                 ?
   10            A         841                 ?
   11            A         840                 ?},
  'pocket15': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         816                 ?
   1            A         762                 ?
   2            A         766                 ?
   3            A         813                 ?
   4            A         832                 ?
   5            A         815                 ?
   6            A         790                 ?
   7            A         760                 ?
   8            A         814                 ?},
  'pocket16': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         551                 ?
   1            A         528                 ?
   2            A         549                 ?
   3            A         527                 ?
   4            A         532                 ?
   5            A         531                 ?
   6            A         548                 ?
   7            A         537                 ?
   8            A         923                 ?},
  'pocket17': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         884                 ?
   1            A         676                 ?
   2            A         678                 ?
   3            A         675                 ?
   4            A         883                 ?
   5            A         882                 ?},
  'pocket18': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         916                 ?
   1            A         901                 ?
   2            A         915                 ?
   3            A         897                 ?
   4            A         898                 ?
   5            A         894                 ?
   6            A         912                 ?
   7            A         907                 ?
   8            A         905                 ?
   9            A         911                 ?},
  'pocket19': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         887                 ?
   1            A         712                 ?
   2            A         716                 ?
   3            A         885                 ?
   4            A         676                 ?
   5            A         713                 ?
   6            A         709                 ?},
  'pocket20': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         761                 ?
   1            A         751                 ?
   2            A         754                 ?
   3            A         747                 ?
   4            A         787                 ?},
  'pocket21': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         543                 ?
   1            A         637                 ?
   2            A         586                 ?
   3            A         615                 ?
   4            A         613                 ?
   5            A         614                 ?},
  'pocket22': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         564                 ?
   1            A         663                 ?
   2            A         588                 ?
   3            A         590                 ?
   4            A         561                 ?
   5            A         661                 ?
   6            A         657                 ?
   7            A         662                 ?},
  'pocket24': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         620                 ?
   1            A         618                 ?
   2            A         623                 ?
   3            A         622                 ?
   4            A         621                 ?
   5            A         599                 ?
   6            A         645                 ?
   7            A         642                 ?
   8            A         644                 ?
   9            A         603                 ?},
  'pocket25': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         753                 ?
   1             A         740                 ?
   2             A         865                 ?
   3             A         752                 ?
   4             A         764                 ?
   5             A         835                 ?
   6             A         861                 ?
   7             A         763                 ?
   8             A         834                 ?
   9             A         863                 ?
   10            A         862                 ?
   11            A         767                 ?
   12            A         765                 ?},
  'pocket26': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         908                 ?
   1            A         907                 ?
   2            A         942                 ?
   3            A         906                 ?
   4            A         938                 ?
   5            A         931                 ?
   6            A         939                 ?
   7            A         911                 ?
   8            A         930                 ?},
  'pocket27': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         921                 ?
   1            A         529                 ?
   2            A         527                 ?
   3            A         551                 ?
   4            A         923                 ?
   5            A         924                 ?
   6            A         922                 ?}},
 '7yg5': {'pocket9': {'prob': 0.39101290702819824,
   'pred': 1,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A        1542                 ?
   1            A        1598                 ?
   2            A        1601                 ?
   3            A        1597                 ?
   4            A        1594                 ?
   5            A        1587                 ?},
  'pocket6': {'prob': 0.37945815920829773,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A        1398                 ?
   1             A         561                 ?
   2             A         557                 ?
   3             A        1399                 ?
   4             A        1402                 ?
   5             A        1401                 ?
   6             A         566                 ?
   7             A        1396                 ?
   8             A         564                 ?
   9             A        1310                 ?
   10            A        1306                 ?},
  'pocket8': {'prob': 0.36803826689720154,
   'pred': 1,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         228                 ?
   1            A         229                 ?
   2            A         225                 ?
   3            A         232                 ?
   4            A         303                 ?
   5            A         684                 ?
   6            A         299                 ?
   7            A         688                 ?},
  'pocket1': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         242                 ?
   1             A         322                 ?
   2             A         326                 ?
   3             A         330                 ?
   4             A         329                 ?
   5             A        1571                 ?
   6             A        1573                 ?
   7             A         270                 ?
   8             A         321                 ?
   9             A         246                 ?
   10            A         323                 ?
   11            A         325                 ?
   12            A        1574                 ?
   13            A        1577                 ?
   14            A         327                 ?
   15            A         269                 ?
   16            A         268                 ?
   17            A         249                 ?
   18            A        1570                 ?
   19            A         245                 ?
   20            A         248                 ?
   21            A         238                 ?
   22            A         235                 ?
   23            A        1569                 ?
   24            A         243                 ?},
  'pocket2': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         708                 ?
   1             A         366                 ?
   2             A         363                 ?
   3             A         598                 ?
   4             A         370                 ?
   5             A         358                 ?
   6             A         367                 ?
   7             A         704                 ?
   8             A         700                 ?
   9             A         354                 ?
   10            A         357                 ?
   11            A         369                 ?
   12            A         606                 ?
   13            A         213                 ?
   14            A         602                 ?
   15            A         217                 ?
   16            A         701                 ?
   17            A         603                 ?
   18            A         599                 ?
   19            A         214                 ?
   20            A         210                 ?
   21            A         373                 ?
   22            A         705                 ?
   23            A         209                 ?},
  'pocket3': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A        1299                 ?
   1             A        1413                 ?
   2             A        1414                 ?
   3             A         592                 ?
   4             A        1417                 ?
   5             A        1409                 ?
   6             A        1292                 ?
   7             A        1295                 ?
   8             A         577                 ?
   9             A         586                 ?
   10            A         540                 ?
   11            A         539                 ?
   12            A         596                 ?
   13            A         589                 ?
   14            A         594                 ?
   15            A         373                 ?
   16            A         598                 ?
   17            A         370                 ?
   18            A         597                 ?

## STINGAllo

In [24]:
stingallo_resultsf = "STINGAllo/stingallo_results.pkl"

with open(stingallo_resultsf, "rb") as f:
    stingallo_results = pickle.load(f)

len(stingallo_results), stingallo_results

(3,
 {'8qni': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         148}},
  '7gqu': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         574
    1            A         576}},
  '8aq6': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            G          91}}})

In [25]:
stingallo_results = {
    pdb: {
        pocket: {
            "pred": 1,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in stingallo_results.items()
}
stingallo_results

{'8qni': {'pocket': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         148}},
 '7gqu': {'pocket': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         574
   1            A         576}},
 '8aq6': {'pocket': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            G          91}}}

## AlloFusion

In [26]:
allofusion_resultsf = "AlloFusion/allofusion_results.pkl"

with open(allofusion_resultsf, "rb") as f:
    allofusion_results = pickle.load(f)

len(allofusion_results), allofusion_results

(9,
 {'7gqu': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         577
    1            A         581
    2            A         713
    3            A         721
    4            A         730
    5            A         731
    6            A         854
    7            A         888
    8            A         891}},
  '7yg5': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         381
    1            A        1354
    2            A        1397}},
  '8f4s': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A        6878
    1            A        6880
    2            A        6968
    3            A        7000}},
  '8jp0': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         486
    1            A         809}},
  '8qni': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         132
    1            A         141
    2            A         143
    3            A         289}},
  '8uk6': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         265
    1            A         268
    2            A         465
    3            A         484
    4            A         566
    5            A         596}},
  '8v81': {'pocket': {'residues':    auth_asym_id auth_seq_id
    0             A         347
    1             A         459
    2             A         464
    3             A         465
    4             A         605
    5             A         622
    6             A         991
    7             A        1098
    8             A        1102
    9             A        1106
    10            A        1144
    11            A        1245
    12            A        1248
    13            A        1250
    14            A        1251
    15            A        1402}},
  '9dnm': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A           9
    1            A          21
    2            A         107
    3            A         160
    4            A         288
    5            A         290
    6            A         333
    7            A         422
    8            A         427
    9            A         453}},
  '8aq6': {'pocket_G': {'residues':   auth_asym_id auth_seq_id
    0            G          10
    1            G          16
    2            G          27
    3            G          57
    4            G          73
    5            G         106
    6            G         114
    7            G         132
    8            G         139
    9            G         141},
   'pocket_H': {'residues':   auth_asym_id auth_seq_id
    0            H          10
    1            H          16
    2            H          27
    3            H          57
    4            H          73
    5            H         106
    6            H         114
    7            H         132
    8            H         139
    9            H         141}}})

In [27]:
allofusion_results = {
    pdb: {
        f"pocket_{res['auth_asym_id']}_{res['auth_seq_id']}": {
            "pred": 1,
            "residues": res.to_frame().T
        }
        for pocket, pocketd in pockets.items()
        for i, res in pocketd["residues"].iterrows()
    }
    for pdb, pockets in allofusion_results.items()
}
allofusion_results

{'7gqu': {'pocket_A_577': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         577},
  'pocket_A_581': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         581},
  'pocket_A_713': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         713},
  'pocket_A_721': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         721},
  'pocket_A_730': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         730},
  'pocket_A_731': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         731},
  'pocket_A_854': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A         854},
  'pocket_A_888': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A         888},
  'pocket_A_891': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            A         891}},
 '7yg5': {'pocket_A_381': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         381},
  'pocket_A_1354': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A        1354},
  'pocket_A_1397': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A        1397}},
 '8f4s': {'pocket_A_6878': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A        6878},
  'pocket_A_6880': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A        6880},
  'pocket_A_6968': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A        6968},
  'pocket_A_7000': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A        7000}},
 '8jp0': {'pocket_A_486': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         486},
  'pocket_A_809': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         809}},
 '8qni': {'pocket_A_132': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         132},
  'pocket_A_141': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         141},
  'pocket_A_143': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         143},
  'pocket_A_289': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         289}},
 '8uk6': {'pocket_A_265': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         265},
  'pocket_A_268': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         268},
  'pocket_A_465': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         465},
  'pocket_A_484': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         484},
  'pocket_A_566': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         566},
  'pocket_A_596': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         596}},
 '8v81': {'pocket_A_347': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         347},
  'pocket_A_459': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         459},
  'pocket_A_464': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         464},
  'pocket_A_465': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         465},
  'pocket_A_605': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         605},
  'pocket_A_622': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         622},
  'pocket_A_991': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A         991},
  'pocket_A_1098': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A        1098},
  'pocket_A_1102': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            A        1102},
  'pocket_A_1106': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            A        1106},
  'pocket_A_1144': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   10            A        1144},
  'pocket_A_1245': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   11            A        1245},
  'pocket_A_1248': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   12            A        1248},
  'pocket_A_1250': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   13            A        1250},
  'pocket_A_1251': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   14            A        1251},
  'pocket_A_1402': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   15            A        1402}},
 '9dnm': {'pocket_A_9': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A           9},
  'pocket_A_21': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A          21},
  'pocket_A_107': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         107},
  'pocket_A_160': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         160},
  'pocket_A_288': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         288},
  'pocket_A_290': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         290},
  'pocket_A_333': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A         333},
  'pocket_A_422': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A         422},
  'pocket_A_427': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            A         427},
  'pocket_A_453': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            A         453}},
 '8aq6': {'pocket_G_10': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            G          10},
  'pocket_G_16': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            G          16},
  'pocket_G_27': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            G          27},
  'pocket_G_57': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            G          57},
  'pocket_G_73': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            G          73},
  'pocket_G_106': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            G         106},
  'pocket_G_114': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            G         114},
  'pocket_G_132': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            G         132},
  'pocket_G_139': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            G         139},
  'pocket_G_141': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            G         141},
  'pocket_H_10': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            H          10},
  'pocket_H_16': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            H          16},
  'pocket_H_27': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            H          27},
  'pocket_H_57': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            H          57},
  'pocket_H_73': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            H          73},
  'pocket_H_106': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            H         106},
  'pocket_H_114': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            H         114},
  'pocket_H_132': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            H         132},
  'pocket_H_139': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            H         139},
  'pocket_H_141': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            H         141}}}

## AllosES

In [28]:
alloses_resultsf = "AllosES/alloses_results.pkl"

with open(alloses_resultsf, "rb") as f:
    alloses_results = pickle.load(f)

len(alloses_results), alloses_results

(9,
 {'7gqu': {'pocket7': {'pro_ave': 0.6077189166132947,
    'residues':    auth_seq_id auth_asym_id
    0          601            A
    1          829            A
    2          573            A
    3          577            A
    4          578            A
    ..         ...          ...
    73         923            A
    74         551            A
    75         547            A
    76         883            A
    77         801            A

    [78 rows x 2 columns]},
   'pocket20': {'pro_ave': 0.4671694797381203,
    'residues':    auth_seq_id auth_asym_id
    0          916            A
    1          917            A
    2          920            A
    3          727            A
    4          919            A
    5          555            A
    6          552            A
    7          551            A
    8          846            A
    9          845            A
    10         849            A
    11         913            A
    12         706            A
    13         570            A
    14         726            A
    15         725            A
    16         898            A
    17         895            A
    18         730            A
    19         729            A
    20         921            A
    21         923            A
    22         728            A
    23         731            A
    24         575            A
    25         891            A
    26         914            A
    27         704            A
    28         550            A
    29         571            A
    30         918            A
    31         572            A},
   'pocket25': {'pro_ave': 0.2263919649682801,
    'residues':    auth_seq_id auth_asym_id
    0          753            A
    1          740            A
    2          865            A
    3          752            A
    4          764            A
    5          835            A
    6          861            A
    7          763            A
    8          834            A
    9          863            A
    10         862            A
    11         767            A
    12         765            A},
   'pocket17': {'pro_ave': 0.2191807043507958,
    'residues':   auth_seq_id auth_asym_id
    0         916            A
    1         901            A
    2         915            A
    3         897            A
    4         898            A
    5         894            A
    6         912            A
    7         907            A
    8         905            A
    9         911            A},
   'pocket13': {'pro_ave': 0.1554380102632959,
    'residues':    auth_seq_id auth_asym_id
    0          770            A
    1          822            A
    2          851            A
    3          772            A
    4          842            A
    5          771            A
    6          838            A
    7          843            A
    8          874            A
    9          821            A
    10         841            A
    11         840            A},
   'pocket1': {'pro_ave': 0.1153199514844701,
    'residues':   auth_seq_id auth_asym_id
    0         901            A
    1         904            A
    2         905            A
    3         897            A
    4         900            A},
   'pocket11': {'pro_ave': 0.1119463691182878,
    'residues':   auth_seq_id auth_asym_id
    0         811            A
    1         808            A
    2         604            A
    3         807            A
    4         829            A
    5         601            A
    6         605            A
    7         608            A},
   'pocket4': {'pro_ave': 0.1026798663575272,
    'residues':   auth_seq_id auth_asym_id
    0         579            A
    1         578            A
    2         544            A
    3         546            A
    4         608            A
    5         582            A
    6         609            A
    7         614            A
    8         612            A
    9         543            A},
   'pocket8': {'pro_ave': 0.1020045765546529,
    'residues':    auth_seq_id auth_asym_id
    0          555            A
    1          529            A
    2          551            A
    3          527            A
    4          528            A
    5          554            A
    6          558            A
    7          559            A
    8          724            A
    9          563            A
    10         565            A},
   'pocket18': {'pro_ave': 0.0920598778468019,
    'residues':   auth_seq_id auth_asym_id
    0         887            A
    1         712            A
    2         716            A
    3         885            A
    4         676            A
    5         713            A
    6         709            A},
   'pocket19': {'pro_ave': 0.0877221307733602,
    'residues':   auth_seq_id auth_asym_id
    0         761            A
    1         751            A
    2         754            A
    3         747            A
    4         787            A},
   'pocket15': {'pro_ave': 0.0870267623141718,
    'residues':   auth_seq_id auth_asym_id
    0         551            A
    1         528            A
    2         549            A
    3         527            A
    4         532            A
    5         531            A
    6         548            A
    7         537            A
    8         923            A},
   'pocket12': {'pro_ave': 0.0858915792236656,
    'residues':   auth_seq_id auth_asym_id
    0         708            A
    1         712            A
    2         887            A
    3         709            A
    4         890            A
    5         891            A
    6         894            A},
   'pocket9': {'pro_ave': 0.0850683764085093,
    'residues':    auth_seq_id auth_asym_id
    0          772            A
    1          873            A
    2          776            A
    3          773            A
    4          779            A
    5          775            A
    6          839            A
    7          742            A
    8          840            A
    9          872            A
    10         871            A},
   'pocket14': {'pro_ave': 0.0843735604152091,
    'residues':   auth_seq_id auth_asym_id
    0         816            A
    1         762            A
    2         766            A
    3         813            A
    4         832            A
    5         815            A
    6         790            A
    7         760            A
    8         814            A},
   'pocket26': {'pro_ave': 0.0809950311695924,
    'residues':   auth_seq_id auth_asym_id
    0         908            A
    1         907            A
    2         942            A
    3         906            A
    4         938            A
    5         931            A
    6         939            A
    7         911            A
    8         930            A},
   'pocket21': {'pro_ave': 0.0765395740475778,
    'residues':   auth_seq_id auth_asym_id
    0         543            A
    1         637            A
    2         586            A
    3         615            A
    4         613            A
    5         614            A},
   'pocket22': {'pro_ave': 0.07513920458807,
    'residues':   auth_seq_id auth_asym_id
    0         564            A
    1         663            A
    2         588            A
    3         590            A
    4         561            A
    5         661            A
    6         657            A
    7         662            A},
   'pocket23': {'pro_ave': 0.0730568054754113,
    'residues':   auth_seq_id auth_asym_id
    0         885            A
    1         884            A
    2         676            A
    3         675            A},
   'pocket3': {'pro_ave': 0.0728235280052202,
    'residues':   auth_seq_id auth_asym_id
    0         914            A
    1         915            A
    2         907            A
    3         911            A
    4         922            A
    5         918            A
    6         920            A
    7         930            A
    8         917            A},
   'pocket24': {'pro_ave': 0.0649855965740845,
    'residues':   auth_seq_id auth_asym_id
    0         620            A
    1         618            A
    2         623            A
    3         622            A
    4         621            A
    5         599            A
    6         645            A
    7         642            A
    8         644            A
    9         603            A},
   'pocket2': {'pro_ave': 0.0590332186854218,
    'residues':   auth_seq_id auth_asym_id
    0         782            A
    1         786            A
    2         783            A
    3         745            A
    4         747            A
    5         748            A
    6         779            A
    7         746            A
    8         744            A
    9         778            A},
   'pocket16': {'pro_ave': 0.0560974170943565,
    'residues':   auth_seq_id auth_asym_id
    0         884            A
    1         676            A
    2         678            A
    3         675            A
    4         883            A
    5         882            A},
   'pocket27': {'pro_ave': 0.0536917680507392,
    'residues':   auth_seq_id auth_asym_id
    0         921            A
    1         529            A
    2         527            A
    3         551            A
    4         923            A
    5         924            A
    6         922            A},
   'pocket10': {'pro_ave': 0.0530534383383505,
    'residues':   auth_seq_id auth_asym_id
    0         534            A
    1         537            A
    2         532            A
    3         538            A
    4         541            A
    5         533            A},
   'pocket6': {'pro_ave': 0.0459679519198046,
    'residues':   auth_seq_id auth_asym_id
    0         615            A
    1         613            A
    2         614            A
    3         610            A},
   'pocket5': {'pro_ave': 0.0444113131234797,
    'residues':   auth_seq_id auth_asym_id
    0         721            A
    1         566            A
    2         564            A
    3         691            A
    4         565            A
    5         696            A
    6         695            A
    7         563            A}},
  '7yg5': {'pocket104': {'pro_ave': 0.4730885983842405,
    'residues':    auth_seq_id auth_asym_id
    0         1299            A
    1         1413            A
    2         1414            A
    3          592            A
    4         1417            A
    5         1409            A
    6         1292            A
    7         1295            A
    8          577            A
    9          586            A
    10         540            A
    11         539            A
    12         596            A
    13         589            A
    14         594            A
    15         373            A
    16         598            A
    17         370            A
    18         597            A
    19         593            A
    20         538            A
    21         578            A
    22         580            A
    23         590            A
    24         374            A
    25         381            A},
   'pocket110': {'pro_ave': 0.4521513393747806,
    'residues':    auth_seq_id auth_asym_id
    0          242            A
    1          322            A
    2          326            A
    3          330            A
    4          329            A
    5         1571            A
    6         1573            A
    7          270            A
    8          321            A
    9          246            A
    10         323            A
    11         325            A
    12        1574            A
    13        1577            A
    14         327            A
    15         269            A
    16         268            A
    17         249            A
    18        1570            A
    19         245            A
    20         248            A
    21         238            A
    22         235            A
    23        1569            A
    24         243            A},
   'pocket109': {'pro_ave': 0.3994402443316814,
    'residues':    auth_seq_id auth_asym_id
    0          328            A
    1         1654            A
    2          332            A
    3          324            A
    4          319            A
    5         1643            A
    6          316            A
    7          315            A
    8          320            A
    9         1650            A
    10        1642            A
    11        1653            A
    12         325            A
    13        1651            A
    14        1648            A
    15         271            A
    16        1619            A
    17        1615            A
    18         323            A
    19        1618            A
    20        1657            A
    21        1649            A},
   'pocket103': {'pro_ave': 0.3772304141657377,
    'residues':    auth_seq_id auth_asym_id
    0         1616            A
    1         1266            A
    2         1269            A
    3         1613            A
    4         1713            A
    5         1617            A
    6         1620            A
    7         1709            A
    8         1621            A
    9         1279            A
    10        1286            A
    11        1282            A
    12        1712            A
    13        1283            A},
   'pocket101': {'pro_ave': 0.3716830983257296,
    'residues':    auth_seq_id auth_asym_id
    0         1293            A
    1         1712            A
    2         1708            A
    3         1711            A
    4         1418            A
    5         1296            A
    6         1415            A
    7         1289            A
    8         1422            A
    9         1366            A
    10        1715            A
    11        1286            A},
   'pocket98': {'pro_ave': 0.3573425306315678,
    'residues':    auth_seq_id auth_asym_id
    0          613            A
    1          693            A
    2          215            A
    3          214            A
    4          211            A
    5          617            A
    6          689            A
    7          654            A
    8          686            A
    9          614            A
    10         218            A
    11         222            A
    12         610            A
    13         690            A
    14         694            A
    15         221            A},
   'pocket46': {'pro_ave': 0.3533808768932701,
    'residues':    auth_seq_id auth_asym_id
    0          479            A
    1          575            A
    2          482            A
    3          474            A
    4          530            A
    5          534            A
    6          548            A
    7          519            A
    8          572            A
    9          522            A
    10         523            A
    11         544            A
    12         535            A
    13         526            A
    14         541            A
    15         538            A
    16         478            A
    17         578            A
    18         484            A
    19         480            A
    20         579            A
    21         483            A
    22         473            A
    23         470            A
    24         582            A
    25         476            A
    26         387            A
    27         581            A
    28         540            A},
   'pocket28': {'pro_ave': 0.3439246986476743,
    'residues':    auth_seq_id auth_asym_id
    0          569            A
    1          551            A
    2          554            A
    3          512            A
    4          565            A
    5          516            A
    6          567            A
    7         1309            A
    8          572            A
    9          555            A
    10         489            A
    11         493            A
    12         509            A
    13         558            A
    14         492            A
    15         508            A
    16         513            A
    17         559            A
    18         511            A
    19         515            A
    20         496            A},
   'pocket66': {'pro_ave': 0.2833904404806703,
    'residues':    auth_seq_id auth_asym_id
    0          607            A
    1         1408            A
    2          651            A
    3          647            A
    4          648            A
    5         1404            A
    6          614            A
    7          610            A
    8          611            A
    9          694            A
    10         698            A
    11        1412            A},
   'pocket18': {'pro_ave': 0.2770624192400578,
    'residues':   auth_seq_id auth_asym_id
    0         225            A
    1         692            A
    2         228            A
    3         221            A
    4         689            A
    5         224            A
    6         688            A
    7         346            A
    8         342            A
    9         218            A},
   'pocket14': {'pro_ave': 0.254823872543587,
    'residues':   auth_seq_id auth_asym_id
    0        1705            A
    1        1704            A
    2        1701            A
    3        1363            A
    4        1362            A
    5        1359            A
    6        1700            A
    7        1360            A
    8        1366            A
    9        1300            A},
   'pocket51': {'pro_ave': 0.2388354179841897,
    'residues':    auth_seq_id auth_asym_id
    0         1660            A
    1         1711            A
    2         1710            A
    3          340            A
    4         1714            A
    5         1657            A
    6         1618            A
    7          336            A
    8         1614            A
    9         1615            A
    10        1611            A},
   'pocket94': {'pro_ave': 0.2371872748868503,
    'residues':    auth_seq_id auth_asym_id
    0          677            A
    1          296            A
    2          300            A
    3          297            A
    4          674            A
    5          681            A
    6          680            A
    7          678            A
    8          684            A
    9          299            A
    10         673            A
    11         294            A},
   'pocket41': {'pro_ave': 0.22484704413507,
    'residues':    auth_seq_id auth_asym_id
    0         1601            A
    1          341            A
    2         1604            A
    3          340            A
    4         1718            A
    5         1717            A
    6         1714            A
    7          336            A
    8          344            A
    9         1611            A
    10         337            A},
   'pocket86': {'pro_ave': 0.2174731714158268,
    'residues':    auth_seq_id auth_asym_id
    0          230            A
    1          227            A
    2          231            A
    3         1597            A
    4         1587            A
    5         1593            A
    6         1584            A
    7          234            A
    8          337            A
    9          341            A
    10        1601            A
    11         235            A},
   'pocket52': {'pro_ave': 0.2120803645843116,
    'residues':    auth_seq_id auth_asym_id
    0          585            A
    1         1288            A
    2         1291            A
    3          588            A
    4         1425            A
    5          710            A
    6          713            A
    7         1287            A
    8         1421            A
    9          706            A
    10         592            A
    11         709            A
    12        1290            A
    13         589            A
    14        1424            A

Positive preds. above 0.5 probability (average).

In [29]:
alloses_results = {
    pdb: {
        pocket: {
            "pred": 1 if pocketd["pro_ave"] >= 0.5 else 0,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in alloses_results.items()
}
alloses_results

{'7gqu': {'pocket7': {'pred': 1,
   'pro_ave': 0.6077189166132947,
   'residues':    auth_seq_id auth_asym_id
   0          601            A
   1          829            A
   2          573            A
   3          577            A
   4          578            A
   ..         ...          ...
   73         923            A
   74         551            A
   75         547            A
   76         883            A
   77         801            A

   [78 rows x 2 columns]},
  'pocket20': {'pred': 0,
   'pro_ave': 0.4671694797381203,
   'residues':    auth_seq_id auth_asym_id
   0          916            A
   1          917            A
   2          920            A
   3          727            A
   4          919            A
   5          555            A
   6          552            A
   7          551            A
   8          846            A
   9          845            A
   10         849            A
   11         913            A
   12         706            A
   13         570            A
   14         726            A
   15         725            A
   16         898            A
   17         895            A
   18         730            A
   19         729            A
   20         921            A
   21         923            A
   22         728            A
   23         731            A
   24         575            A
   25         891            A
   26         914            A
   27         704            A
   28         550            A
   29         571            A
   30         918            A
   31         572            A},
  'pocket25': {'pred': 0,
   'pro_ave': 0.2263919649682801,
   'residues':    auth_seq_id auth_asym_id
   0          753            A
   1          740            A
   2          865            A
   3          752            A
   4          764            A
   5          835            A
   6          861            A
   7          763            A
   8          834            A
   9          863            A
   10         862            A
   11         767            A
   12         765            A},
  'pocket17': {'pred': 0,
   'pro_ave': 0.2191807043507958,
   'residues':   auth_seq_id auth_asym_id
   0         916            A
   1         901            A
   2         915            A
   3         897            A
   4         898            A
   5         894            A
   6         912            A
   7         907            A
   8         905            A
   9         911            A},
  'pocket13': {'pred': 0,
   'pro_ave': 0.1554380102632959,
   'residues':    auth_seq_id auth_asym_id
   0          770            A
   1          822            A
   2          851            A
   3          772            A
   4          842            A
   5          771            A
   6          838            A
   7          843            A
   8          874            A
   9          821            A
   10         841            A
   11         840            A},
  'pocket1': {'pred': 0,
   'pro_ave': 0.1153199514844701,
   'residues':   auth_seq_id auth_asym_id
   0         901            A
   1         904            A
   2         905            A
   3         897            A
   4         900            A},
  'pocket11': {'pred': 0,
   'pro_ave': 0.1119463691182878,
   'residues':   auth_seq_id auth_asym_id
   0         811            A
   1         808            A
   2         604            A
   3         807            A
   4         829            A
   5         601            A
   6         605            A
   7         608            A},
  'pocket4': {'pred': 0,
   'pro_ave': 0.1026798663575272,
   'residues':   auth_seq_id auth_asym_id
   0         579            A
   1         578            A
   2         544            A
   3         546            A
   4         608            A
   5         582            A
   6         609            A
   7         614            A
   8         612            A
   9         543            A},
  'pocket8': {'pred': 0,
   'pro_ave': 0.1020045765546529,
   'residues':    auth_seq_id auth_asym_id
   0          555            A
   1          529            A
   2          551            A
   3          527            A
   4          528            A
   5          554            A
   6          558            A
   7          559            A
   8          724            A
   9          563            A
   10         565            A},
  'pocket18': {'pred': 0,
   'pro_ave': 0.0920598778468019,
   'residues':   auth_seq_id auth_asym_id
   0         887            A
   1         712            A
   2         716            A
   3         885            A
   4         676            A
   5         713            A
   6         709            A},
  'pocket19': {'pred': 0,
   'pro_ave': 0.0877221307733602,
   'residues':   auth_seq_id auth_asym_id
   0         761            A
   1         751            A
   2         754            A
   3         747            A
   4         787            A},
  'pocket15': {'pred': 0,
   'pro_ave': 0.0870267623141718,
   'residues':   auth_seq_id auth_asym_id
   0         551            A
   1         528            A
   2         549            A
   3         527            A
   4         532            A
   5         531            A
   6         548            A
   7         537            A
   8         923            A},
  'pocket12': {'pred': 0,
   'pro_ave': 0.0858915792236656,
   'residues':   auth_seq_id auth_asym_id
   0         708            A
   1         712            A
   2         887            A
   3         709            A
   4         890            A
   5         891            A
   6         894            A},
  'pocket9': {'pred': 0,
   'pro_ave': 0.0850683764085093,
   'residues':    auth_seq_id auth_asym_id
   0          772            A
   1          873            A
   2          776            A
   3          773            A
   4          779            A
   5          775            A
   6          839            A
   7          742            A
   8          840            A
   9          872            A
   10         871            A},
  'pocket14': {'pred': 0,
   'pro_ave': 0.0843735604152091,
   'residues':   auth_seq_id auth_asym_id
   0         816            A
   1         762            A
   2         766            A
   3         813            A
   4         832            A
   5         815            A
   6         790            A
   7         760            A
   8         814            A},
  'pocket26': {'pred': 0,
   'pro_ave': 0.0809950311695924,
   'residues':   auth_seq_id auth_asym_id
   0         908            A
   1         907            A
   2         942            A
   3         906            A
   4         938            A
   5         931            A
   6         939            A
   7         911            A
   8         930            A},
  'pocket21': {'pred': 0,
   'pro_ave': 0.0765395740475778,
   'residues':   auth_seq_id auth_asym_id
   0         543            A
   1         637            A
   2         586            A
   3         615            A
   4         613            A
   5         614            A},
  'pocket22': {'pred': 0,
   'pro_ave': 0.07513920458807,
   'residues':   auth_seq_id auth_asym_id
   0         564            A
   1         663            A
   2         588            A
   3         590            A
   4         561            A
   5         661            A
   6         657            A
   7         662            A},
  'pocket23': {'pred': 0,
   'pro_ave': 0.0730568054754113,
   'residues':   auth_seq_id auth_asym_id
   0         885            A
   1         884            A
   2         676            A
   3         675            A},
  'pocket3': {'pred': 0,
   'pro_ave': 0.0728235280052202,
   'residues':   auth_seq_id auth_asym_id
   0         914            A
   1         915            A
   2         907            A
   3         911            A
   4         922            A
   5         918            A
   6         920            A
   7         930            A
   8         917            A},
  'pocket24': {'pred': 0,
   'pro_ave': 0.0649855965740845,
   'residues':   auth_seq_id auth_asym_id
   0         620            A
   1         618            A
   2         623            A
   3         622            A
   4         621            A
   5         599            A
   6         645            A
   7         642            A
   8         644            A
   9         603            A},
  'pocket2': {'pred': 0,
   'pro_ave': 0.0590332186854218,
   'residues':   auth_seq_id auth_asym_id
   0         782            A
   1         786            A
   2         783            A
   3         745            A
   4         747            A
   5         748            A
   6         779            A
   7         746            A
   8         744            A
   9         778            A},
  'pocket16': {'pred': 0,
   'pro_ave': 0.0560974170943565,
   'residues':   auth_seq_id auth_asym_id
   0         884            A
   1         676            A
   2         678            A
   3         675            A
   4         883            A
   5         882            A},
  'pocket27': {'pred': 0,
   'pro_ave': 0.0536917680507392,
   'residues':   auth_seq_id auth_asym_id
   0         921            A
   1         529            A
   2         527            A
   3         551            A
   4         923            A
   5         924            A
   6         922            A},
  'pocket10': {'pred': 0,
   'pro_ave': 0.0530534383383505,
   'residues':   auth_seq_id auth_asym_id
   0         534            A
   1         537            A
   2         532            A
   3         538            A
   4         541            A
   5         533            A},
  'pocket6': {'pred': 0,
   'pro_ave': 0.0459679519198046,
   'residues':   auth_seq_id auth_asym_id
   0         615            A
   1         613            A
   2         614            A
   3         610            A},
  'pocket5': {'pred': 0,
   'pro_ave': 0.0444113131234797,
   'residues':   auth_seq_id auth_asym_id
   0         721            A
   1         566            A
   2         564            A
   3         691            A
   4         565            A
   5         696            A
   6         695            A
   7         563            A}},
 '7yg5': {'pocket104': {'pred': 0,
   'pro_ave': 0.4730885983842405,
   'residues':    auth_seq_id auth_asym_id
   0         1299            A
   1         1413            A
   2         1414            A
   3          592            A
   4         1417            A
   5         1409            A
   6         1292            A
   7         1295            A
   8          577            A
   9          586            A
   10         540            A
   11         539            A
   12         596            A
   13         589            A
   14         594            A
   15         373            A
   16         598            A
   17         370            A
   18         597            A
   19         593            A
   20         538            A
   21         578            A
   22         580            A
   23         590            A
   24         374            A
   25         381            A},
  'pocket110': {'pred': 0,
   'pro_ave': 0.4521513393747806,
   'residues':    auth_seq_id auth_asym_id
   0          242            A
   1          322            A
   2          326            A
   3          330            A
   4          329            A
   5         1571            A
   6         1573            A
   7          270            A
   8          321            A
   9          246            A
   10         323            A
   11         325            A
   12        1574            A
   13        1577            A
   14         327            A
   15         269            A
   16         268            A
   17         249            A
   18        1570            A
   19         245            A
   20         248            A
   21         238            A
   22         235            A
   23        1569            A
   24         243            A},
  'pocket109': {'pred': 0,
   'pro_ave': 0.3994402443316814,
   'residues':    auth_seq_id auth_asym_id
   0          328            A
   1         1654            A
   2          332            A
   3          324            A
   4          319            A
   5         1643            A
   6          316            A
   7          315            A
   8          320            A
   9         1650            A
   10        1642            A
   11        1653            A
   12         325            A
   13        1651            A
   14        1648            A
   15         271            A
   16        1619            A
   17        1615            A
   18         323            A
   19        1618            A
   20        1657            A
   21        1649            A},
  'pocket103': {'pred': 0,
   'pro_ave': 0.3772304141657377,
   'residues':    auth_seq_id auth_asym_id
   0         1616            A
   1         1266            A
   2         1269            A
   3         1613            A
   4         1713            A
   5         1617            A
   6         1620            A
   7         1709            A
   8         1621            A
   9         1279            A
   10        1286            A
   11        1282            A
   12        1712            A
   13        1283            A},
  'pocket101': {'pred': 0,
   'pro_ave': 0.3716830983257296,
   'residues':    auth_seq_id auth_asym_id
   0         1293            A
   1         1712            A
   2         1708            A
   3         1711            A
   4         1418            A
   5         1296            A
   6         1415            A
   7         1289            A
   8         1422            A
   9         1366            A
   10        1715            A
   11        1286            A},
  'pocket98': {'pred': 0,
   'pro_ave': 0.3573425306315678,
   'residues':    auth_seq_id auth_asym_id
   0          613            A
   1          693            A
   2          215            A
   3          214            A
   4          211            A
   5          617            A
   6          689            A
   7          654            A
   8          686            A
   9          614            A
   10         218            A
   11         222            A
   12         610            A
   13         690            A
   14         694            A
   15         221            A},
  'pocket46': {'pred': 0,
   'pro_ave': 0.3533808768932701,
   'residues':    auth_seq_id auth_asym_id
   0          479            A
   1          575            A
   2          482            A
   3          474            A
   4          530            A
   5          534            A
   6          548            A
   7          519            A
   8          572            A
   9          522            A
   10         523            A
   11         544            A
   12         535            A
   13         526            A
   14         541            A
   15         538            A
   16         478            A
   17         578            A
   18         484            A
   19         480            A
   20         579            A
   21         483            A
   22         473            A
   23         470            A
   24         582            A
   25         476            A
   26         387            A
   27         581            A
   28         540            A},
  'pocket28': {'pred': 0,
   'pro_ave': 0.3439246986476743,
   'residues':    auth_seq_id auth_asym_id
   0          569            A
   1          551            A
   2          554            A
   3          512            A
   4          565            A
   5          516            A
   6          567            A
   7         1309            A
   8          572            A
   9          555            A
   10         489            A
   11         493            A
   12         509            A
   13         558            A
   14         492            A
   15         508            A
   16         513            A
   17         559            A
   18         511            A
   19         515            A
   20         496            A},
  'pocket66': {'pred': 0,
   'pro_ave': 0.2833904404806703,
   'residues':    auth_seq_id auth_asym_id
   0          607            A
   1         1408            A
   2          651            A
   3          647            A
   4          648            A
   5         1404            A
   6          614            A
   7          610            A
   8          611            A
   9          694            A
   10         698            A
   11        1412            A},
  'pocket18': {'pred': 0,
   'pro_ave': 0.2770624192400578,
   'residues':   auth_seq_id auth_asym_id
   0         225            A
   1         692            A
   2         228            A
   3         221            A
   4         689            A
   5         224            A
   6         688            A
   7         346            A
   8         342            A
   9         218            A},
  'pocket14': {'pred': 0,
   'pro_ave': 0.254823872543587,
   'residues':   auth_seq_id auth_asym_id
   0        1705            A
   1        1704            A
   2        1701            A
   3        1363            A
   4        1362            A
   5        1359            A
   6        1700            A
   7        1360            A
   8        1366            A
   9        1300            A},
  'pocket51': {'pred': 0,
   'pro_ave': 0.2388354179841897,
   'residues':    auth_seq_id auth_asym_id
   0         1660            A
   1         1711            A
   2         1710            A
   3          340            A
   4         1714            A
   5         1657            A
   6         1618            A
   7          336            A
   8         1614            A
   9         1615            A
   10        1611            A},
  'pocket94': {'pred': 0,
   'pro_ave': 0.2371872748868503,
   'residues':    auth_seq_id auth_asym_id
   0          677            A
   1          296            A
   2          300            A
   3          297            A
   4          674            A
   5          681            A
   6          680            A
   7          678            A
   8          684            A
   9          299            A
   10         673            A
   11         294            A},
  'pocket41': {'pred': 0,
   'pro_ave': 0.22484704413507,
   'residues':    auth_seq_id auth_asym_id
   0         1601            A
   1          341            A
   2         1604            A
   3          340            A
   4         1718            A
   5         1717            A
   6         1714            A
   7          336            A
   8          344            A
   9         1611            A
   10         337            A},
  'pocket86': {'pred': 0,
   'pro_ave': 0.2174731714158268,
   'residues':    auth_seq_id auth_asym_id
   0          230            A
   1          227            A
   2          231            A
   3         1597            A
   4         1587            A
   5         1593            A
   6         1584            A
   7          234            A
   8          337            A
   9          341            A
   10        1601            A
   11         235            A},
  'pocket52': {'pred': 0,
   'pro_ave': 0.2120803645843116,
   'residues':    auth_seq_id auth_asym_id
   0          585            A
   1         1288            A
   2         1291            A
   3          588            A
   4         1425            A
   5          710            A
   6          713            A
   7         1287            A
   8         1421            A
   9          706            A
   10         592            A
   11         709            A
   12        1290            A
   13         589            A

## MEF-AlloSite

In [30]:
import json

Top 3 pockets for each PDB are predicted positive.

In [31]:
mefallosite_resultsf = "MEF-AlloSite/mef-allosite_results.json"

with open(mefallosite_resultsf, "r") as f:
    mefallosite_results = json.load(f)

len(mefallosite_results), mefallosite_results

(9,
 {'7gqu': {'pocket15': {'prob': 0.07944739485780399,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['760',
      '762',
      '766',
      '790',
      '813',
      '814',
      '815',
      '816',
      '832'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket21': {'prob': 0.09905595394472282,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['561', '564', '588', '590', '657', '661', '662', '663'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket22': {'prob': 0.20237085223197937,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['740',
      '752',
      '753',
      '763',
      '764',
      '765',
      '767',
      '834',
      '835',
      '861',
      '862',
      '863',
      '865'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket10': {'prob': 0.0636305899048845,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['532', '533', '534', '537', '538', '541'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket23': {'prob': 0.5660654231905937,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['546',
      '547',
      '548',
      '549',
      '550',
      '551',
      '553',
      '572',
      '573',
      '574',
      '575',
      '576',
      '577',
      '578',
      '581',
      '596',
      '597',
      '598',
      '599',
      '600',
      '601',
      '602',
      '604',
      '605',
      '608',
      '640',
      '668',
      '669',
      '671',
      '677',
      '678',
      '679',
      '681',
      '704',
      '731',
      '732',
      '733',
      '734',
      '770',
      '774',
      '794',
      '796',
      '800',
      '801',
      '803',
      '804',
      '807',
      '808',
      '822',
      '823',
      '824',
      '825',
      '826',
      '827',
      '828',
      '829',
      '830',
      '831',
      '843',
      '847',
      '850',
      '851',
      '854',
      '856',
      '857',
      '859',
      '923'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket16': {'prob': 0.2781989090144634,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['894',
      '897',
      '898',
      '901',
      '905',
      '907',
      '911',
      '912',
      '915',
      '916'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket3': {'prob': 0.08593026548624039,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['671',
      '677',
      '704',
      '705',
      '710',
      '843',
      '846',
      '847',
      '850',
      '888',
      '892'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket2': {'prob': 0.07222728865842025,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['744',
      '745',
      '746',
      '747',
      '748',
      '778',
      '779',
      '782',
      '783',
      '786'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket6': {'prob': 0.060798547230660915,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A'],
     'auth_seq_id': ['610', '613', '614', '615'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?']}},
   'pocket12': {'prob': 0.058250979675600924,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['601', '604', '605', '608', '807', '808', '811', '829'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket18': {'prob': 0.16577118511001268,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['747', '751', '754', '761', '787'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket20': {'prob': 0.06589377345517278,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['543', '586', '613', '614', '615', '637'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket8': {'prob': 0.09231384998808305,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['742',
      '772',
      '773',
      '775',
      '776',
      '779',
      '839',
      '840',
      '871',
      '872',
      '873'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket17': {'prob': 0.06114864085490505,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['676', '709', '712', '713', '716', '887'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket5': {'prob': 0.06120439758524299,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['543',
      '544',
      '546',
      '578',
      '579',
      '582',
      '608',
      '609',
      '612',
      '614'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket13': {'prob': 0.07344735041260719,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['708', '709', '712', '887', '890', '891', '894'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket1': {'prob': 0.07134894995639722,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['897', '900', '901', '904', '905'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket14': {'prob': 0.672811433672905,
    'pred': 1,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['550',
      '551',
      '552',
      '555',
      '570',
      '571',
      '572',
      '575',
      '704',
      '706',
      '725',
      '726',
      '727',
      '728',
      '729',
      '730',
      '731',
      '845',
      '846',
      '849',
      '891',
      '895',
      '898',
      '913',
      '914',
      '916',
      '917',
      '918',
      '919',
      '920',
      '921',
      '923'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket4': {'prob': 0.08339076333989699,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['907',
      '911',
      '914',
      '915',
      '917',
      '918',
      '920',
      '922',
      '930'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket9': {'prob': 0.06305303222810228,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['906',
      '907',
      '908',
      '911',
      '930',
      '931',
      '938',
      '939',
      '942'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket11': {'prob': 0.17287950093547502,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['770',
      '771',
      '772',
      '821',
      '822',
      '838',
      '840',
      '841',
      '842',
      '843',
      '851',
      '874'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket7': {'prob': 0.10284953936934471,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['527',
      '528',
      '529',
      '551',
      '554',
      '555',
      '558',
      '559',
      '563',
      '565',
      '724'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket19': {'prob': 0.06989484466612339,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A'],
     'auth_seq_id': ['675', '676', '884'],
     'pdbx_PDB_ins_code': ['?', '?', '?']}}},
  '7yg5': {'pocket40': {'prob': 0.1192612958451112,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1591', '1592', '1595', '1728', '1731', '1739', '1742'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket63': {'prob': 0.0603449692328771,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['260', '261', '262', '263', '1337', '1338', '1339'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket15': {'prob': 0.3002418552835782,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['219',
      '220',
      '223',
      '349',
      '353',
      '356',
      '1592',
      '1596',
      '1728',
      '1729',
      '1731'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket33': {'prob': 0.07898059859871864,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1528',
      '1532',
      '1536',
      '1537',
      '1539',
      '1540',
      '1543',
      '1588'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket21': {'prob': 0.6342863440513611,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['241',
      '244',
      '245',
      '246',
      '1494',
      '1497',
      '1498',
      '1499',
      '1500',
      '1501',
      '1502',
      '1506',
      '1507',
      '1510',
      '1511',
      '1514',
      '1515',
      '1556',
      '1557',
      '1560',
      '1576',
      '1579'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket37': {'prob': 0.11766921946158011,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1621', '1624', '1698', '1701', '1702', '1705'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket44': {'prob': 0.6406018435955048,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['607',
      '610',
      '611',
      '614',
      '647',
      '648',
      '651',
      '694',
      '698',
      '1404',
      '1408',
      '1412'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket22': {'prob': 0.061665816543002926,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['287', '631', '633', '634', '636', '665', '668'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket10': {'prob': 0.5358648970723152,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['218',
      '221',
      '224',
      '225',
      '228',
      '342',
      '346',
      '688',
      '689',
      '692'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket62': {'prob': 0.3403007686138153,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['227',
      '230',
      '231',
      '234',
      '235',
      '337',
      '341',
      '1584',
      '1587',
      '1593',
      '1597',
      '1601'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket74': {'prob': 0.06664073808739583,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['187', '623', '624', '628', '670', '678'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket24': {'prob': 0.0564792036699752,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['371', '375', '711', '715', '718', '719'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket83': {'prob': 0.33399433083832264,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1176',
      '1178',
      '1249',
      '1251',
      '1252',
      '1255',
      '1628',
      '1631',
      '1678',
      '1679',
      '1680',
      '1681',
      '1686',
      '1687',
      '1690',
      '1691',
      '1693',
      '1694',
      '1695'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket23': {'prob': 0.6061601489782333,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['336',
      '337',
      '340',
      '341',
      '344',
      '1601',
      '1604',
      '1611',
      '1714',
      '1717',
      '1718'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket27': {'prob': 0.08014264268179734,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['497',
      '498',
      '499',
      '1316',
      '1350',
      '1356',
      '1357',
      '1360'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket71': {'prob': 0.17787393492956957,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['372',
      '375',
      '378',
      '379',
      '382',
      '715',
      '719',
      '720',
      '723',
      '724'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket43': {'prob': 0.615338958799839,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['96',
      '100',
      '103',
      '104',
      '107',
      '197',
      '200',
      '204',
      '608',
      '611',
      '612',
      '615',
      '643'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket53': {'prob': 0.06983550141255061,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1556', '1560', '1571', '1572', '1573', '1576', '1579'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket16': {'prob': 0.1474288155635198,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['211', '214', '606', '609', '610', '613', '693', '697'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket68': {'prob': 0.07416865322738886,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['356', '359', '360', '361', '362', '785', '788', '1732'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket30': {'prob': 0.281755656003952,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['228',
      '303',
      '306',
      '307',
      '308',
      '338',
      '339',
      '340',
      '343',
      '688',
      '691',
      '692',
      '1718'],
     'pdbx_PDB_ins_code': ['?',

In [32]:
mefallosite_results = {
    pdb: {
        pocket: {
            k: v if k != "residues" else pd.DataFrame(v)
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } 
    for pdb, pockets in mefallosite_results.items()
}

mefallosite_results

{'7gqu': {'pocket15': {'prob': 0.07944739485780399,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         760                 ?
   1            A         762                 ?
   2            A         766                 ?
   3            A         790                 ?
   4            A         813                 ?
   5            A         814                 ?
   6            A         815                 ?
   7            A         816                 ?
   8            A         832                 ?},
  'pocket21': {'prob': 0.09905595394472282,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         561                 ?
   1            A         564                 ?
   2            A         588                 ?
   3            A         590                 ?
   4            A         657                 ?
   5            A         661                 ?
   6            A         662                 ?
   7            A         663                 ?},
  'pocket22': {'prob': 0.20237085223197937,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         740                 ?
   1             A         752                 ?
   2             A         753                 ?
   3             A         763                 ?
   4             A         764                 ?
   5             A         765                 ?
   6             A         767                 ?
   7             A         834                 ?
   8             A         835                 ?
   9             A         861                 ?
   10            A         862                 ?
   11            A         863                 ?
   12            A         865                 ?},
  'pocket10': {'prob': 0.0636305899048845,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         532                 ?
   1            A         533                 ?
   2            A         534                 ?
   3            A         537                 ?
   4            A         538                 ?
   5            A         541                 ?},
  'pocket23': {'prob': 0.5660654231905937,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         546                 ?
   1             A         547                 ?
   2             A         548                 ?
   3             A         549                 ?
   4             A         550                 ?
   ..          ...         ...               ...
   62            A         854                 ?
   63            A         856                 ?
   64            A         857                 ?
   65            A         859                 ?
   66            A         923                 ?

   [67 rows x 3 columns]},
  'pocket16': {'prob': 0.2781989090144634,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         894                 ?
   1            A         897                 ?
   2            A         898                 ?
   3            A         901                 ?
   4            A         905                 ?
   5            A         907                 ?
   6            A         911                 ?
   7            A         912                 ?
   8            A         915                 ?
   9            A         916                 ?},
  'pocket3': {'prob': 0.08593026548624039,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         671                 ?
   1             A         677                 ?
   2             A         704                 ?
   3             A         705                 ?
   4             A         710                 ?
   5             A         843                 ?
   6             A         846                 ?
   7             A         847                 ?
   8             A         850                 ?
   9             A         888                 ?
   10            A         892                 ?},
  'pocket2': {'prob': 0.07222728865842025,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         744                 ?
   1            A         745                 ?
   2            A         746                 ?
   3            A         747                 ?
   4            A         748                 ?
   5            A         778                 ?
   6            A         779                 ?
   7            A         782                 ?
   8            A         783                 ?
   9            A         786                 ?},
  'pocket6': {'prob': 0.060798547230660915,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         610                 ?
   1            A         613                 ?
   2            A         614                 ?
   3            A         615                 ?},
  'pocket12': {'prob': 0.058250979675600924,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         601                 ?
   1            A         604                 ?
   2            A         605                 ?
   3            A         608                 ?
   4            A         807                 ?
   5            A         808                 ?
   6            A         811                 ?
   7            A         829                 ?},
  'pocket18': {'prob': 0.16577118511001268,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         747                 ?
   1            A         751                 ?
   2            A         754                 ?
   3            A         761                 ?
   4            A         787                 ?},
  'pocket20': {'prob': 0.06589377345517278,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         543                 ?
   1            A         586                 ?
   2            A         613                 ?
   3            A         614                 ?
   4            A         615                 ?
   5            A         637                 ?},
  'pocket8': {'prob': 0.09231384998808305,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         742                 ?
   1             A         772                 ?
   2             A         773                 ?
   3             A         775                 ?
   4             A         776                 ?
   5             A         779                 ?
   6             A         839                 ?
   7             A         840                 ?
   8             A         871                 ?
   9             A         872                 ?
   10            A         873                 ?},
  'pocket17': {'prob': 0.06114864085490505,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         676                 ?
   1            A         709                 ?
   2            A         712                 ?
   3            A         713                 ?
   4            A         716                 ?
   5            A         887                 ?},
  'pocket5': {'prob': 0.06120439758524299,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         543                 ?
   1            A         544                 ?
   2            A         546                 ?
   3            A         578                 ?
   4            A         579                 ?
   5            A         582                 ?
   6            A         608                 ?
   7            A         609                 ?
   8            A         612                 ?
   9            A         614                 ?},
  'pocket13': {'prob': 0.07344735041260719,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         708                 ?
   1            A         709                 ?
   2            A         712                 ?
   3            A         887                 ?
   4            A         890                 ?
   5            A         891                 ?
   6            A         894                 ?},
  'pocket1': {'prob': 0.07134894995639722,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         897                 ?
   1            A         900                 ?
   2            A         901                 ?
   3            A         904                 ?
   4            A         905                 ?},
  'pocket14': {'prob': 0.672811433672905,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         550                 ?
   1             A         551                 ?
   2             A         552                 ?
   3             A         555                 ?
   4             A         570                 ?
   5             A         571                 ?
   6             A         572                 ?
   7             A         575                 ?
   8             A         704                 ?
   9             A         706                 ?
   10            A         725                 ?
   11            A         726                 ?
   12            A         727                 ?
   13            A         728                 ?
   14            A         729                 ?
   15            A         730                 ?
   16            A         731                 ?
   17            A         845                 ?
   18            A         846                 ?
   19            A         849                 ?
   20            A         891                 ?
   21            A         895                 ?
   22            A         898                 ?
   23            A         913                 ?
   24            A         914                 ?
   25            A         916                 ?
   26            A         917                 ?
   27            A         918                 ?
   28            A         919                 ?
   29            A         920                 ?
   30            A         921                 ?
   31            A         923                 ?},
  'pocket4': {'prob': 0.08339076333989699,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         907                 ?
   1            A         911                 ?
   2            A         914                 ?
   3            A         915                 ?
   4            A         917                 ?
   5            A         918                 ?
   6            A         920                 ?
   7            A         922                 ?
   8            A         930                 ?},
  'pocket9': {'prob': 0.06305303222810228,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         906                 ?
   1            A         907                 ?
   2            A         908                 ?
   3            A         911                 ?
   4            A         930                 ?
   5            A         931                 ?
   6            A         938                 ?
   7            A         939                 ?
   8            A         942                 ?},
  'pocket11': {'prob': 0.17287950093547502,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         770                 ?
   1             A         771                 ?
   2             A         772                 ?
   3             A         821                 ?
   4             A         822                 ?
   5             A         838                 ?
   6             A         840                 ?
   7             A         841                 ?
   8             A         842                 ?
   9             A         843                 ?
   10            A         851                 ?
   11            A         874                 ?},
  'pocket7': {'prob': 0.10284953936934471,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         527                 ?
   1             A         528                 ?
   2             A         529                 ?
   3             A         551                 ?
   4             A         554                 ?
   5             A         555                 ?
   6             A         558                 ?
   7             A         559                 ?
   8             A         563                 ?
   9             A         565                 ?
   10            A         724                 ?},
  'pocket19': {'prob': 0.06989484466612339,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         675                 ?
   1            A         676                 ?
   2            A         884                 ?}},
 '7yg5': {'pocket40': {'prob': 0.1192612958451112,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A        1591                 ?
   1            A        1592                 ?
   2            A        1595                 ?
   3            A        1728                 ?
   4            A        1731                 ?
   5            A        1739                 ?
   6            A        1742                 ?},
  'pocket63': {'prob': 0.0603449692328771,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         260                 ?
   1            A         261                 ?
   2            A         262                 ?
   3            A         263                 ?
   4            A        1337                 ?
   5            A        1338                 ?
   6            A        1339                 ?},
  'pocket15': {'prob': 0.3002418552835782,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         219                 ?
   1             A         220                 ?
   2             A         223                 ?
   3             A         349                 ?
   4             A         353                 ?
   5             A         356                 ?
   6             A        1592                 ?
   7             A        1596                 ?
   8             A        1728                 ?
   9             A        1729                 ?
   10            A        1731                 ?},
  'pocket33': {'prob': 0.07898059859871864,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A        1528                 ?
   1            A        1532                 ?
   2            A        1536                 ?
   3            A        1537                 ?
   4            A        1539                 ?
   5            A        1540                 ?
   6            A        1543                 ?
   7            A        1588                 ?},
  'pocket21': {'prob': 0.6342863440513611,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         241                 ?
   1             A         244                 ?
   2             A         245                 ?
   3             A         246                 ?
   4             A        1494                 ?
   5             A        1497                 ?
   6             A        1498                 ?
   7             A        1499                 ?
   8             A        1500                 ?
   9             A        1501                 ?
   10            A        1502                 ?
   11            A        1506                 ?
   12            A        1507                 ?
   13            A        1510                 ?
   14            A        1511                 ?
   15            A        1514                 ?
   16            A        1515                 ?
   17            A        1556                 ?
   18            A        1557                 ?
   19            A        1560                 ?
   20            A        1576                 ?
   21            A        1579                 ?},
  'pocket37': {'prob': 0.11766921946158011,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A        1621                 ?
   1            A        1624                 ?
   2            A        1698                 ?
   3            A        1701                 ?
   4            A        1702                 ?
   5            A        1705                 ?},
  'pocket44': {'prob': 0.6406018435955048,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         607                 ?
   1             A         610                 ?
   2             A         611                 ?
   3             A         614                 ?
   4             A         647                 ?
   5             A         648                 ?
   6             A         651                 ?
   7             A         694                 ?
   8             A         698                 ?
   9             A        1404                 ?
   10            A        1408                 ?
   11            A        1412                 ?},
  'pocket22': {'prob': 0.061665816543002926,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         287                 ?
   1            A         631                 ?
   2            A         633                 ?
   3            A         634                 ?
   4            A         636                 ?
   5            A         665                 ?
   6            A         668                 ?},
  'pocket10': {'prob': 0.5358648970723152,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         218                 ?
   1            A         221                 ?
   2            A         224                 ?
   3            A         225                 ?
   4            A         228                 ?
   5            A         342                 ?
   6            A         346                 ?
   7            A         688                 ?
   8            A         689                 ?
   9            A         692                 ?},
  'pocket62': {'prob': 0.3403007686138153,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         227                 ?
   1             A         230                 ?
   2             A         231                 ?
   3             A         234                 ?
   4             A         235                 ?
   5             A         337                 ?
   6             A         341                 ?
   7             A        1584                 ?
   8             A        1587                 ?
   9             A        1593                 ?
   10            A        1597                 ?
   11            A        1601                 ?},
  'pocket74': {'prob': 0.06664073808739583,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         187                 ?
   1            A         623                 ?
   2            A         624                 ?
   3            A         628                 ?
   4            A         670                 ?
   5            A         678                 ?},
  'pocket24': {'prob': 0.0564792036699752,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         371                 ?

## ALLO

Top pocket is taken as positive prediction.

In [33]:
allo_resultsf = "ALLO/ALLO_results.json"

with open(allo_resultsf, "r") as f:
    allo_results = json.load(f)

len(allo_results), allo_results

(9,
 {'9dnm': {'P_10': {'pred': 0,
    'prob': 0.04074,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['58',
      '59',
      '60',
      '62',
      '76',
      '78',
      '143',
      '144',
      '145',
      '147',
      '165']}},
   'P_11': {'pred': 0,
    'prob': 0.04071,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['341',
      '342',
      '343',
      '344',
      '345',
      '347',
      '348',
      '413',
      '414']}},
   'P_12': {'pred': 0,
    'prob': 0.04063,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['333',
      '334',
      '335',
      '337',
      '356',
      '425',
      '426',
      '427',
      '445']}},
   'P_13': {'pred': 0,
    'prob': 0.04224,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['9',
      '10',
      '11',
      '20',
      '21',
      '22',
      '24',
      '55',
      '56',
      '115',
      '146',
      '147',
      '148',
      '164',
      '165',
      '166',
      '492']}},
   'P_8': {'pred': 0,
    'prob': 0.0407,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['28',
      '29',
      '30',
      '31',
      '171',
      '172',
      '173',
      '174',
      '175',
      '456']}},
   'P_9': {'pred': 0,
    'prob': 0.04079,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['11',
      '12',
      '13',
      '14',
      '160',
      '163',
      '164',
      '165',
      '166']}},
   'P_6': {'pred': 0,
    'prob': 0.04097,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['275',
      '278',
      '279',
      '284',
      '301',
      '302',
      '303',
      '318',
      '319',
      '320',
      '370']}},
   'P_7': {'pred': 0,
    'prob': 0.04356,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['309',
      '310',
      '311',
      '312',
      '313',
      '315',
      '336',
      '337',
      '338',
      '354',
      '376',
      '377',
      '378',
      '379',
      '400',
      '401',
      '422',
      '423',
      '450',
      '452']}},
   'P_4': {'pred': 0,
    'prob': 0.04106,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['47',
      '51',
      '149',
      '150',
      '151',
      '152',
      '153',
      '154',
      '155',
      '156',
      '157',
      '158',
      '159',
      '162',
      '163']}},
   'P_5': {'pred': 0,
    'prob': 0.04136,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['289',
      '291',
      '298',
      '323',
      '325',
      '327',
      '328',
      '329',
      '428',
      '429',
      '430',
      '432',
      '433',
      '442',
      '443',
      '444']}},
   'P_2': {'pred': 0,
    'prob': 0.042910000000000004,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['36',
      '80',
      '82',
      '84',
      '85',
      '86',
      '88',
      '89',
      '90',
      '91',
      '92',
      '93',
      '94',
      '95',
      '96',
      '97',
      '98',
      '101',
      '114',
      '115',
      '116',
      '117',
      '118']}},
   'P_3': {'pred': 0,
    'prob': 0.04591,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['183',
      '186',
      '187',
      '190',
      '209',
      '224',
      '232',
      '233',
      '236',
      '237',
      '240',
      '241',
      '244',
      '270',
      '271',
      '273',
      '274',
      '276',
      '277',
      '280',
      '281']}},
   'P_0': {'pred': 1,
    'prob': 0.30634,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['25',
      '26',
      '27',
      '28',
      '29',
      '31',
      '34',
      '35',
      '36',
      '37',
      '57',
      '59',
      '61',
      '62',
      '75',
      '76',
      '77',
      '78',
      '79',
      '80',
      '117',
      '118',
      '119',
      '120',
      '121',
      '122',
      '123',
      '124',
      '125',
      '126',
      '127',
      '128',
      '129',
      '130',
      '131',
      '132',
      '133',
      '134',
      '135',
      '136',
      '137',
      '138',
      '139',
      '140',
      '141',
      '142',
      '143',
      '144',
      '167',
      '168',
      '169',
      '170',
      '171',
      '172',
      '173',
      '339',
      '340',
      '341',
      '342',
      '343',
      '344',
      '345',
      '346',
      '348',
      '349',
      '350',
      '379',
      '382',
      '383',
      '384',
      '385',
      '386',
      '387',
      '388',
      '390',
      '391',
      '392',
      '399',
      '402',
      '403',
      '404',
      '405',
      '406',
      '407',
      '408',
      '409',
      '410',
      '411',
      '412',
      '413',
      '414',
      '415',
      '416',
      '417',
      '418',
      '419',
      '420',
      '421',
      '422',
      '423',
      '449',
      '450',
      '451',
      '453',
      '454',
      '492']}},
   'P_1': {'pred': 0,
    'prob': 0.047580000000000004,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['175',
      '176',
      '177',
      '178',
      '179',
      '180',
      '181',
      '183',
      '184',
      '187',
      '219',
      '220',
      '221',
      '222',
      '223',
      '225',
      '274',
      '277',
      '281',
      '282',
      '283',
      '305',
      '306',
      '307',
      '308',
      '309',
      '310',
      '313',
      '314',
      '315',
      '316']}}},
  '8qni': {'P_8': {'pred': 0,
    'prob': 0.04072,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['38',
      '39',
      '40',
      '41',
      '45',
      '108',
      '111',
      '112',
      '115']}},
   'P_9': {'pred': 0,
    'prob': 0.04074,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['397',
      '400',
      '401',
      '404',
      '405',
      '406',
      '407',
      '408',
      '415']}},
   'P_6': {'pred': 0,
    'prob': 0.04097,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['50', '53', '54', '57', '78', '79', '82']}},
   'P_7': {'pred': 0,
    'prob': 0.04102,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['71',
      '72',
      '73',
      '76',
      '77',
      '151',
      '154',
      '289',
      '290']}},
   'P_4': {'pred': 0,
    'prob': 0.042089999999999995,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['253',
      '257',
      '283',
      '285',
      '317',
      '320',
      '321',
      '324',
      '329',
      '338',
      '339',
      '340',
      '341',
      '342']}},
   'P_5': {'pred': 0,
    'prob': 0.04124,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['297',
      '299',
      '309',
      '311',
      '314',
      '319',
      '322',
      '323',
      '326',
      '328',
      '329']}},
   'P_2': {'pred': 0,
    'prob': 0.04133,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['205',
      '206',
      '208',
      '209',
      '212',
      '244',
      '245',
      '246',
      '247',
      '248',
      '251',
      '252',
      '354',
      '355',
      '357',
      '360']}},
   'P_3': {'pred': 0,
    'prob': 0.042230000000000004,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['174',
      '175',
      '238',
      '239',
      '240',
      '241',
      '249',
      '253',
      '293',
      '294',
      '295',
      '310',
      '311',
      '312',
      '313',
      '314',
      '315',
      '316',
      '317']}},
   'P_0': {'pred': 1,
    'prob': 0.31525,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['38',
      '60',
      '67',
      '68',
      '70',
      '71',
      '72',
      '73',
      '74',
      '108',
      '109',
      '112',
      '113',
      '116',
      '117',
      '120',
      '124',
      '135',
      '138',
      '140',
      '141',
      '142',
      '143',
      '144',
      '145',
      '146',
      '147',
      '148',
      '149',
      '152',
      '153',
      '155',
      '156',
      '193',
      '194',
      '195',
      '214',
      '215',
      '217',
      '218',
      '219',
      '220',
      '221',
      '222',
      '223',
      '224',
      '225',
      '226',
      '227',
      '229',
      '231',
      '232',
      '233',
      '235',
      '236',
      '239',
      '240',
      '254',
      '255',
      '256',
      '257',
      '258',
      '260',
      '261',
      '262',
      '263',
      '264',
      '265',
      '266',
      '268',
      '286',
      '287',
      '288',
      '289',
      '290',
      '291',
      '292',
      '293',
      '294',
      '295',
      '296',
      '310',
      '359',
      '362',
      '363',
      '364',
      '366',
      '367',
      '368',
      '369',
      '370',
      '371',
      '372',
      '378',
      '379',
      '380']}},
   'P_1': {'pred': 0,
    'prob': 0.041960000000000004,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['104',
      '105',
      '106',
      '166',
      '168',
      '169',
      '170',

In [34]:
allo_results = {
    pdb: {
        pocket: {
            k: v if k != "residues" else pd.DataFrame(v)
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } 
    for pdb, pockets in allo_results.items()
}

allo_results

{'9dnm': {'P_10': {'pred': 0,
   'prob': 0.04074,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A          58
   1                  ?            A          59
   2                  ?            A          60
   3                  ?            A          62
   4                  ?            A          76
   5                  ?            A          78
   6                  ?            A         143
   7                  ?            A         144
   8                  ?            A         145
   9                  ?            A         147
   10                 ?            A         165},
  'P_11': {'pred': 0,
   'prob': 0.04071,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         341
   1                 ?            A         342
   2                 ?            A         343
   3                 ?            A         344
   4                 ?            A         345
   5                 ?            A         347
   6                 ?            A         348
   7                 ?            A         413
   8                 ?            A         414},
  'P_12': {'pred': 0,
   'prob': 0.04063,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         333
   1                 ?            A         334
   2                 ?            A         335
   3                 ?            A         337
   4                 ?            A         356
   5                 ?            A         425
   6                 ?            A         426
   7                 ?            A         427
   8                 ?            A         445},
  'P_13': {'pred': 0,
   'prob': 0.04224,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A           9
   1                  ?            A          10
   2                  ?            A          11
   3                  ?            A          20
   4                  ?            A          21
   5                  ?            A          22
   6                  ?            A          24
   7                  ?            A          55
   8                  ?            A          56
   9                  ?            A         115
   10                 ?            A         146
   11                 ?            A         147
   12                 ?            A         148
   13                 ?            A         164
   14                 ?            A         165
   15                 ?            A         166
   16                 ?            A         492},
  'P_8': {'pred': 0,
   'prob': 0.0407,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A          28
   1                 ?            A          29
   2                 ?            A          30
   3                 ?            A          31
   4                 ?            A         171
   5                 ?            A         172
   6                 ?            A         173
   7                 ?            A         174
   8                 ?            A         175
   9                 ?            A         456},
  'P_9': {'pred': 0,
   'prob': 0.04079,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A          11
   1                 ?            A          12
   2                 ?            A          13
   3                 ?            A          14
   4                 ?            A         160
   5                 ?            A         163
   6                 ?            A         164
   7                 ?            A         165
   8                 ?            A         166},
  'P_6': {'pred': 0,
   'prob': 0.04097,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         275
   1                  ?            A         278
   2                  ?            A         279
   3                  ?            A         284
   4                  ?            A         301
   5                  ?            A         302
   6                  ?            A         303
   7                  ?            A         318
   8                  ?            A         319
   9                  ?            A         320
   10                 ?            A         370},
  'P_7': {'pred': 0,
   'prob': 0.04356,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         309
   1                  ?            A         310
   2                  ?            A         311
   3                  ?            A         312
   4                  ?            A         313
   5                  ?            A         315
   6                  ?            A         336
   7                  ?            A         337
   8                  ?            A         338
   9                  ?            A         354
   10                 ?            A         376
   11                 ?            A         377
   12                 ?            A         378
   13                 ?            A         379
   14                 ?            A         400
   15                 ?            A         401
   16                 ?            A         422
   17                 ?            A         423
   18                 ?            A         450
   19                 ?            A         452},
  'P_4': {'pred': 0,
   'prob': 0.04106,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A          47
   1                  ?            A          51
   2                  ?            A         149
   3                  ?            A         150
   4                  ?            A         151
   5                  ?            A         152
   6                  ?            A         153
   7                  ?            A         154
   8                  ?            A         155
   9                  ?            A         156
   10                 ?            A         157
   11                 ?            A         158
   12                 ?            A         159
   13                 ?            A         162
   14                 ?            A         163},
  'P_5': {'pred': 0,
   'prob': 0.04136,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         289
   1                  ?            A         291
   2                  ?            A         298
   3                  ?            A         323
   4                  ?            A         325
   5                  ?            A         327
   6                  ?            A         328
   7                  ?            A         329
   8                  ?            A         428
   9                  ?            A         429
   10                 ?            A         430
   11                 ?            A         432
   12                 ?            A         433
   13                 ?            A         442
   14                 ?            A         443
   15                 ?            A         444},
  'P_2': {'pred': 0,
   'prob': 0.042910000000000004,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A          36
   1                  ?            A          80
   2                  ?            A          82
   3                  ?            A          84
   4                  ?            A          85
   5                  ?            A          86
   6                  ?            A          88
   7                  ?            A          89
   8                  ?            A          90
   9                  ?            A          91
   10                 ?            A          92
   11                 ?            A          93
   12                 ?            A          94
   13                 ?            A          95
   14                 ?            A          96
   15                 ?            A          97
   16                 ?            A          98
   17                 ?            A         101
   18                 ?            A         114
   19                 ?            A         115
   20                 ?            A         116
   21                 ?            A         117
   22                 ?            A         118},
  'P_3': {'pred': 0,
   'prob': 0.04591,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         183
   1                  ?            A         186
   2                  ?            A         187
   3                  ?            A         190
   4                  ?            A         209
   5                  ?            A         224
   6                  ?            A         232
   7                  ?            A         233
   8                  ?            A         236
   9                  ?            A         237
   10                 ?            A         240
   11                 ?            A         241
   12                 ?            A         244
   13                 ?            A         270
   14                 ?            A         271
   15                 ?            A         273
   16                 ?            A         274
   17                 ?            A         276
   18                 ?            A         277
   19                 ?            A         280
   20                 ?            A         281},
  'P_0': {'pred': 1,
   'prob': 0.30634,
   'residues':     pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                   ?            A          25
   1                   ?            A          26
   2                   ?            A          27
   3                   ?            A          28
   4                   ?            A          29
   ..                ...          ...         ...
   101                 ?            A         450
   102                 ?            A         451
   103                 ?            A         453
   104                 ?            A         454
   105                 ?            A         492

   [106 rows x 3 columns]},
  'P_1': {'pred': 0,
   'prob': 0.047580000000000004,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         175
   1                  ?            A         176
   2                  ?            A         177
   3                  ?            A         178
   4                  ?            A         179
   5                  ?            A         180
   6                  ?            A         181
   7                  ?            A         183
   8                  ?            A         184
   9                  ?            A         187
   10                 ?            A         219
   11                 ?            A         220
   12                 ?            A         221
   13                 ?            A         222
   14                 ?            A         223
   15                 ?            A         225
   16                 ?            A         274
   17                 ?            A         277
   18                 ?            A         281
   19                 ?            A         282
   20                 ?            A         283
   21                 ?            A         305
   22                 ?            A         306
   23                 ?            A         307
   24                 ?            A         308
   25                 ?            A         309
   26                 ?            A         310
   27                 ?            A         313
   28                 ?            A         314
   29                 ?            A         315
   30                 ?            A         316}},
 '8qni': {'P_8': {'pred': 0,
   'prob': 0.04072,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A          38
   1                 ?            A          39
   2                 ?            A          40
   3                 ?            A          41
   4                 ?            A          45
   5                 ?            A         108
   6                 ?            A         111
   7                 ?            A         112
   8                 ?            A         115},
  'P_9': {'pred': 0,
   'prob': 0.04074,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         397
   1                 ?            A         400
   2                 ?            A         401
   3                 ?            A         404
   4                 ?            A         405
   5                 ?            A         406
   6                 ?            A         407
   7                 ?            A         408
   8                 ?            A         415},
  'P_6': {'pred': 0,
   'prob': 0.04097,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A          50
   1                 ?            A          53
   2                 ?            A          54
   3                 ?            A          57
   4                 ?            A          78
   5                 ?            A          79
   6                 ?            A          82},
  'P_7': {'pred': 0,
   'prob': 0.04102,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A          71
   1                 ?            A          72
   2                 ?            A          73
   3                 ?            A          76
   4                 ?            A          77
   5                 ?            A         151
   6                 ?            A         154
   7                 ?            A         289
   8                 ?            A         290},
  'P_4': {'pred': 0,
   'prob': 0.042089999999999995,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         253
   1                  ?            A         257
   2                  ?            A         283
   3                  ?            A         285
   4                  ?            A         317
   5                  ?            A         320
   6                  ?            A         321
   7                  ?            A         324
   8                  ?            A         329
   9                  ?            A         338
   10                 ?            A         339
   11                 ?            A         340
   12                 ?            A         341
   13                 ?            A         342},
  'P_5': {'pred': 0,
   'prob': 0.04124,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         297
   1                  ?            A         299
   2                  ?            A         309
   3                  ?            A         311
   4                  ?            A         314
   5                  ?            A         319
   6                  ?            A         322
   7                  ?            A         323
   8                  ?            A         326
   9                  ?            A         328
   10                 ?            A         329},
  'P_2': {'pred': 0,
   'prob': 0.04133,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         205
   1                  ?            A         206
   2                  ?            A         208
   3                  ?            A         209
   4                  ?            A         212
   5                  ?            A         244
   6                  ?            A         245
   7                  ?            A         246
   8                  ?            A         247
   9                  ?            A         248
   10                 ?            A         251
   11                 ?            A         252
   12                 ?            A         354
   13                 ?            A         355
   14                 ?            A         357
   15                 ?            A         360},
  'P_3': {'pred': 0,
   'prob': 0.042230000000000004,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         174
   1                  ?            A         175
   2                  ?            A         238
   3                  ?            A         239
   4                  ?            A         240
   5                  ?            A         241
   6                  ?            A         249
   7                  ?            A         253
   8                  ?            A         293
   9                  ?            A         294
   10                 ?            A         295
   11                 ?            A         310
   12                 ?            A         311
   13                 ?            A         312
   14                 ?            A         313
   15                 ?            A         314
   16                 ?            A         315
   17                 ?            A         316
   18                 ?            A         317},
  'P_0': {'pred': 1,
   'prob': 0.31525,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A          38
   1                  ?            A          60
   2                  ?            A          67
   3                  ?            A          68
   4                  ?            A          70
   ..               ...          ...         ...
   91                 ?            A         371
   92                 ?            A         372
   93                 ?            A         378
   94                 ?            A         379
   95                 ?            A         380

   [96 rows x 3 columns]},
  'P_1': {'pred': 0,
   'prob': 0.041960000000000004,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         104
   1                  ?            A         105
   2                  ?            A         106
   3                  ?            A         166
   4                  ?            A         168
   5                  ?            A         169
   6                  ?            A         170
   7                  ?            A         171
   8                  ?            A         172
   9                  ?            A         173
   10                 ?            A         179
   11                 ?            A         182
   12                 ?            A         183
   13                 ?            A         187
   14                 ?            A         188
   15                 ?            A         189
   16                 ?            A         190
   17                 ?            A         191
   18                 ?            A         230}},
 '8uk6': {'P_10': {'pred': 0,
   'prob': 0.04162,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         240
   1                  ?            A         243
   2                  ?            A         244
   3                  ?            A         333
   4                  ?            A         446
   5                  ?            A         449
   6                  ?            A         450
   7                  ?            A         452
   8                  ?            A         477
   9                  ?            A         478
   10                 ?            A         479},
  'P_11': {'pred': 0,
   'prob': 0.040839999999999994,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         576
   1                  ?            A         577
   2                  ?            A         578

## All models

In [27]:
defaults = { "all_pockets_in_output": True, "prob_key": "prob" }

models = {
    "model5": { "results": model5_results, **defaults, "labelling": None },
    
    "allositepro": { "results": allositepro_results, "all_pockets_in_output": False, "prob_key": "hitScore" },
    # "stingallo": { "results": stingallo_results, "all_pockets_in_output": False, "prob_key": None },
    # "allofusion": { "results": allofusion_results, "all_pockets_in_output": False, "prob_key": None },
    
    # "passer_ensemble": { "results": passer_results["ensemble"], **defaults, "prob_key": "prob/score" },
    # "passer_automl": { "results": passer_results["automl"], **defaults, "prob_key": "prob/score" },
    # "passer_rank": { "results": passer_results["rank"], **defaults, "prob_key": "prob/score" },
    # "deepallo": { "results": deepallo_results, **defaults },
    # "alloses": { "results": alloses_results, **defaults, "prob_key": "pro_ave" },
    # "mefallosite": { "results": mefallosite_results, **defaults },
    # "allo": { "results": allo_results, **defaults },
}
models

{'model5': {'results': {'22mj': {'pocket11': {'prob': 0.015926241874694824,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 0.0002722057106439024,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 5.723202775698155e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket2': {'prob': 0.80405592918396,
     'pred': 1,
     'label': 1,
     'max_overlap': 0.9285714285714286,
     'pocket_in_site': 0.5909090909090909,
     'site_in_pocket': 0.9285714285714286},
    'pocket4': {'prob': 2.3296684958040714e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket9': {'prob': 0.000627053901553154,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.08333333333333333,
     'pocket_in_site': 0.08333333333333333,
     'site_in_pocket': 0.03571428571428571},
    'pocket10': {'prob': 0.0001461432402720675,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.18181818181818182,
     'pocket_in_site': 0.18181818181818182,
     'site_in_pocket': 0.07142857142857142},
    'pocket5': {'prob': 0.00010802153701661155,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.07692307692307693,
     'pocket_in_site': 0.07692307692307693,
     'site_in_pocket': 0.03571428571428571},
    'pocket8': {'prob': 1.4545725207426585e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 0.0010299441637471318,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.07692307692307693,
     'pocket_in_site': 0.07692307692307693,
     'site_in_pocket': 0.03571428571428571},
    'pocket12': {'prob': 0.0006795694935135543,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 2.654720447026193e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '6s3a': {'pocket1': {'prob': 0.916088342666626,
     'pred': 1,
     'label': 1,
     'max_overlap': 0.7407407407407407,
     'pocket_in_site': 0.5128205128205128,
     'site_in_pocket': 0.7407407407407407},
    'pocket2': {'prob': 0.0006330080796033144,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket4': {'prob': 1.8358763327341876e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.0004271398647688329,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.13333333333333333,
     'pocket_in_site': 0.13333333333333333,
     'site_in_pocket': 0.07407407407407407},
    'pocket3': {'prob': 0.0008974180673249066,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 1.1206387853235356e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '6vvq': {'pocket11': {'prob': 0.0008468019659630954,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 9.395352390129119e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.6666666666666666,
     'pocket_in_site': 0.6666666666666666,
     'site_in_pocket': 0.21052631578947367},
    'pocket13': {'prob': 6.939367267477792e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.9297783374786377,
     'pred': 1,
     'label': 1,
     'max_overlap': 0.7777777777777778,
     'pocket_in_site': 0.7777777777777778,
     'site_in_pocket': 0.7368421052631579},
    'pocket2': {'prob': 0.000794723629951477,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.08333333333333333,
     'pocket_in_site': 0.08333333333333333,
     'site_in_pocket': 0.02631578947368421},
    'pocket4': {'prob': 0.026898527517914772,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0625,
     'pocket_in_site': 0.0625,
     'site_in_pocket': 0.02631578947368421},
    'pocket9': {'prob': 0.0005906405858695507,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.125,
     'pocket_in_site': 0.125,
     'site_in_pocket': 0.05263157894736842},
    'pocket10': {'prob': 0.00016857992159202695,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.2727272727272727,
     'pocket_in_site': 0.2727272727272727,
     'site_in_pocket': 0.07894736842105263},
    'pocket5': {'prob': 0.034184589982032776,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.42857142857142855,
     'pocket_in_site': 0.42857142857142855,
     'site_in_pocket': 0.15789473684210525},
    'pocket8': {'prob': 0.0009646386024542153,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 0.00042768221464939415,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket12': {'prob': 8.93873511813581e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.16666666666666666,
     'pocket_in_site': 0.16666666666666666,
     'site_in_pocket': 0.05263157894736842},
    'pocket6': {'prob': 4.018599611299578e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '6z1m': {'pocket11': {'prob': 0.0015128388768061996,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.047619047619047616,
     'pocket_in_site': 0.047619047619047616,
     'site_in_pocket': 0.027777777777777776},
    'pocket7': {'prob': 3.650477810879238e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket13': {'prob': 1.757488280418329e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket14': {'prob': 0.002025006804615259,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.09523809523809523,
     'pocket_in_site': 0.09523809523809523,
     'site_in_pocket': 0.05555555555555555},
    'pocket1': {'prob': 0.00022238475503399968,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.15384615384615385,
     'pocket_in_site': 0.15384615384615385,
     'site_in_pocket': 0.05555555555555555},
    'pocket2': {'prob': 5.6292923545697704e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket4': {'prob': 4.653539235732751e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.2222222222222222,
     'pocket_in_site': 0.2222222222222222,
     'site_in_pocket': 0.05555555555555555},
    'pocket9': {'prob': 0.0002552109945099801,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket10': {'prob': 1.6028646143695369e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.0021523486357182264,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket8': {'prob': 2.15568197745597e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 5.9831872931681573e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket12': {'prob': 0.00038790932740084827,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.4444444444444444,
     'pocket_in_site': 0.4444444444444444,
     'site_in_pocket': 0.1111111111111111},
    'pocket6': {'prob': 0.8617633581161499,
     'pred': 1,
     'label': 1,
     'max_overlap': 0.8333333333333334,
     'pocket_in_site': 0.7317073170731707,
     'site_in_pocket': 0.8333333333333334}},
   '7p2v': {'pocket11': {'prob': 9.90892999652715e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 0.22542302310466766,
     'pred': 0,
     'label': 1,
     'max_overlap': 0.7857142857142857,
     'pocket_in_site': 0.7857142857142857,
     'site_in_pocket': 0.6470588235294118},
    'pocket13': {'prob': 0.00024260056670755148,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket14': {'prob': 0.00043349715997464955,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.0016324439784511924,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket2': {'prob': 0.04158148169517517,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.23529411764705882,
     'pocket_in_site': 0.16666666666666666,
     'site_in_pocket': 0.23529411764705882},
    'pocket4': {'prob': 0.00046392466174438596,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket9': {'prob': 0.00012165052612544969,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket10': {'prob': 1.0455707979417639e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.01673027127981186,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket8': {'prob': 0.0002992592053487897,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 0.0006657162448391318,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket12': {'prob': 0.00045260938350111246,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 0.021827585995197296,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '7xmd': {'pocket11': {'prob': 0.0003222687228117138,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket15': {'prob': 0.00012147700908826664,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 0.37806421518325806,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket13': {'prob': 0.04310575872659683,
     'pred': 0,
     'label': 1,
     'max_overlap': 0.7368421052631579,
     'pocket_in_site': 0.7368421052631579,
     'site_in_pocket': 0.7368421052631579},
    'pocket14': {'prob': 0.00030769145814701915,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.9105599522590637,
     'pred': 1,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket2': {'prob': 2.2651147446595132e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.08333333333333333,
     'pocket_in_site': 0.08333333333333333,
     'site_in_pocket': 0.05263157894736842},
    'pocket4': {'prob': 1.721340510130176e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket9': {'prob': 8.688537491252646e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket10': {'prob': 0.00014345876115839928,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.001021128031425178,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket8': {'prob': 0.00027641234919428825,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 0.0006295689381659031,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket12': {'prob': 0.000123516540043056,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 1.2127803529438097e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.06666666666666667,
     'pocket_in_site': 0.06666666666666667,
     'site_in_pocket': 0.05263157894736842}},
   '7yg5': {'pocket16': {'prob': 0.000672654714435339,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket28': {'prob': 0.000601460924372077,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket18': {'prob': 1.5210117453534622e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket11': {'prob': 0.010929443873465061,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket34': {'prob': 4.1801024508458795e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.25,
     'pocket_in_site': 0.25,
     'site_in_pocket': 0.10344827586206896},
    'pocket49': {'prob': 8.028100273804739e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket64': {'prob': 0.0002669623354449868,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket25': {'prob': 0.3384205400943756,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket60': {'prob': 0.00017371945432387292,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket15': {'prob': 0.008113360963761806,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket40': {'prob': 1.5094919945113361e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 2.149906867998652e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket65': {'prob': 0.0004010335251223296,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket22': {'prob': 4.923057986161439e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.21428571428571427,
     'pocket_in_site': 0.21428571428571427,
     'site_in_pocket': 0.10344827586206896},
    'pocket13': {'prob': 0.0008437373908236623,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket31': {'prob': 0.0004652818024624139,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket39': {'prob': 3.7505354377742606e-09,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket23': {'prob': 0.0013137826463207603,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket14': {'prob': 2.4785981622699182e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.09090909090909091,
     'pocket_in_site': 0.09090909090909091,
     'site_in_pocket': 0.034482758620689655},
    'pocket59': {'prob': 0.002538274507969618,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket26': {'prob': 0.0002272545243613422,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.042063742876052856,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket46': {'prob': 0.006618991028517485,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket58': {'prob': 0.11724098026752472,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.04,
     'pocket_in_site': 0.04,
     'site_in_pocket': 0.034482758620689655},
    'pocket27': {'prob': 0.03397761657834053,
     'pred': 0,
     'label': 1,
     'max_overlap': 0.7307692307692307,
     'pocket_in_site': 0.7307692307692307,
     'site_in_pocket': 0.6551724137931034},
    'pocket44': {'prob': 0.003498188452795148,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket2': {'prob': 0.3741379380226135,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket32': {'prob': 3.1523821235168725e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket20': {'prob': 0.00013746338663622737,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket4': {'prob': 3.5446122637949884e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket29': {'prob': 0.42382657527923584,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket30': {'prob': 0.00301389885134995,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket61': {'prob': 0.00022272086062002927,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket17': {'prob': 0.017126621678471565,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket9': {'prob': 0.0011379583738744259,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket10': {'prob': 0.00046359593397937715,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket35': {'prob': 0.00020348752150312066,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.056185584515333176,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.13793103448275862,
     'pocket_in_site': 0.10526315789473684,
     'site_in_pocket': 0.13793103448275862},
    'pocket66': {'prob': 0.0007842619088478386,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket47': {'prob': 2.9024260584264994e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},

# Labelling

In [17]:
# Percentage of residues of "one" in "other"
get_overlap = lambda one, other: (
    len( one.merge(other) ) / len(one)
)

def get_label(overlaps, site_in_pocket=None, pocket_in_site=None):
    assert not (site_in_pocket==None and pocket_in_site==None)
    
    if site_in_pocket is None:
        return int( round(overlaps["pocket_in_site"], 2) >= pocket_in_site )
    if pocket_in_site is None:
        return int( round(overlaps["site_in_pocket"], 2) >= site_in_pocket )
    return int( round(overlaps["site_in_pocket"], 2) >= site_in_pocket or round(overlaps["pocket_in_site"], 2) >= pocket_in_site )

In [18]:
get_overlaps = lambda pdb, pocketd: {
    name: get_overlap(*one_in_other) 
        for site in news_sites[pdb] 
            for name, one_in_other in (
                ("pocket_in_site", (pocketd["residues"], site["site"])),
                ("site_in_pocket", (site["site"], pocketd["residues"])),
            )
}

get_overlaps_special = lambda pdb, pocketd: {
    name: get_overlap(*one_in_other) 
        for pocketres in (pocketd["residues"],)
            for sited in news_sites[pdb]
                for site in (sited["site"].query(f"auth_asym_id == '{pocketres.auth_asym_id.unique().item()}'"),)
                    for name, one_in_other in (
                        ("pocket_in_site", (pocketres, site)),
                        ("site_in_pocket", (site, pocketres)),
                    )
}

In [19]:
def label_results(resultsd, site_in_pocket=0.65, pocket_in_site=None, prob_key=None, topx=False, special_8aq6_sc=False):
    df = pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            **{"prob": pocketd[prob_key] for prob_key in (prob_key,) if prob_key is not None},
            "pred": pocketd["pred"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in ((
            get_overlaps_special(pdb, pocketd)
            if special_8aq6_sc and pdb == "8aq6"
            else get_overlaps(pdb, pocketd)
        ),)
    ))
    if prob_key is not None and topx:
        df["pred"] = (
            # Start from a Series where each value/row (sample/pocket) is the total number of pos. labels on its PDB
            df.groupby("pdb")["label"].transform("sum")
            # Then subtract this "total num. of pos. in a PDB" by the rank of each pocket in a PDB, sorted by the probability
            .sub(df.groupby("pdb")["prob"].rank(method="first", ascending=False))
            # If the subtraction is positive or 0 it means that the pocket is in the topX and will be assigned 1
            >= 0
        ).astype(int)
        # If a PDB has no + labelled pocket, assign the highest prob. as positive
        for pdb, group in df.groupby("pdb"):
            if group["pred"].sum() == 0:
                df.loc[ group["prob"].idxmax(), "pred" ] = 1
            
    
    return df.sort_values("max_overlap", ascending=False)

## Model 5.

In [20]:
def label_results_ours(resultsd, site_in_pocket=0.65, pocket_in_site=None, prob_key=None, topx=False, special_8aq6_sc=False):
    df = pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            **{"prob": pocketd[prob_key] for prob_key in (prob_key,) if prob_key is not None},
            "pred": pocketd["pred"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in ({
            "pocket_in_site": pocketd["pocket_in_site"],
            "site_in_pocket": pocketd["site_in_pocket"],
        },)
    ))
    if prob_key is not None and topx:
        df["pred"] = (
            # Start from a Series where each value/row (sample/pocket) is the total number of pos. labels on its PDB
            df.groupby("pdb")["label"].transform("sum")
            # Then subtract this "total num. of pos. in a PDB" by the rank of each pocket in a PDB, sorted by the probability
            .sub(df.groupby("pdb")["prob"].rank(method="first", ascending=False))
            # If the subtraction is positive or 0 it means that the pocket is in the topX and will be assigned 1
            >= 0
        ).astype(int)
        # If a PDB has no + labelled pocket, assign the highest prob. as positive
        for pdb, group in df.groupby("pdb"):
            if group["pred"].sum() == 0:
                df.loc[ group["prob"].idxmax(), "pred" ] = 1
            
    
    return df.sort_values("max_overlap", ascending=False)

In [21]:
our_results = label_results_ours(model5_results, site_in_pocket=0.65, pocket_in_site=None, prob_key="prob", topx=True, special_8aq6_sc=False)

our_results.sort_values(["pred", "label", "prob", "site_in_pocket"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
657,9ntc,pocket1,0.982443,1,1,0.717391,0.717391,0.647059
532,8v81,pocket1,0.977954,1,1,0.962963,0.208000,0.962963
673,9oul,pocket1,0.950287,1,1,0.903226,0.259259,0.903226
498,8uk6,pocket1,0.946666,1,1,0.952381,0.540541,0.952381
30,6vvq,pocket1,0.929778,1,1,0.777778,0.777778,0.736842
326,8f4s,pocket1,0.923800,1,1,0.846154,0.733333,0.846154
475,8qni,pocket1,0.917425,1,1,0.966667,0.322222,0.966667
21,6s3a,pocket1,0.916088,1,1,0.740741,0.512821,0.740741
449,8jp0,pocket1,0.906662,1,1,0.781250,0.320513,0.781250
146,7pt0,pocket2,0.900742,1,1,0.863636,0.527778,0.863636
405,8hx9,pocket1,0.900688,1,1,0.884615,0.469388,0.884615
53,6z1m,pocket6,0.861763,1,1,0.833333,0.731707,0.833333
159,7qpn,pocket2,0.829749,1,1,0.913043,0.700000,0.913043
353,8fpi,pocket1,0.813792,1,1,0.775510,0.655172,0.775510
3,22mj,pocket2,0.804056,1,1,0.928571,0.590909,0.928571
592,9ebs,pocket7,0.796260,1,1,0.857143,0.500000,0.857143
692,9ow9,pocket1,0.775315,1,1,0.916667,0.611111,0.916667
64,7ac8,pocket1,0.715641,1,1,0.871795,0.693878,0.871795
285,7zpe,pocket3,0.639918,1,1,0.785714,0.578947,0.785714
608,9fsj,pocket1,0.502134,1,1,0.812500,0.812500,0.764706
55,6z74,pocket1,0.383723,1,1,0.818182,0.818182,0.720000
131,7p2v,pocket7,0.225423,1,1,0.785714,0.785714,0.647059
291,8crc,pocket9,0.041327,1,1,0.692308,0.600000,0.692308
637,9mft,pocket1,0.996670,1,0,0.000000,0.000000,0.000000
116,7oy0,pocket1,0.957723,1,0,0.150000,0.044118,0.150000
200,7xmd,pocket1,0.910560,1,0,0.000000,0.000000,0.000000
426,8jb3,pocket1,0.827686,1,0,0.000000,0.000000,0.000000
76,7agj,pocket11,0.820158,1,0,0.000000,0.000000,0.000000
589,9d2r,pocket3,0.776362,1,0,0.000000,0.000000,0.000000
570,9b96,pocket1,0.714871,1,0,0.000000,0.000000,0.000000
273,7yg5,pocket63,0.560827,1,0,0.000000,0.000000,0.000000
309,8e24,pocket1,0.494149,1,0,0.166667,0.147059,0.166667
179,7ry1,pocket1,0.314387,1,0,0.000000,0.000000,0.000000
619,9lhf,pocket1,0.040825,1,0,0.782609,0.782609,0.620690
19,6on4,pocket3,0.036457,1,0,0.000000,0.000000,0.000000
120,7oy0,pocket17,0.788634,0,1,0.875000,0.875000,0.700000
585,9d2r,pocket1,0.554641,0,1,0.941176,0.695652,0.941176
313,8e24,pocket4,0.412652,0,1,0.888889,0.888889,0.800000
433,8jb3,pocket3,0.292251,0,1,0.920000,0.851852,0.920000
198,7xmd,pocket13,0.043106,0,1,0.736842,0.736842,0.736842

In [22]:
our_results.sort_values(["pred", "label", "pdb"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
692,9ow9,pocket1,0.775315,1,1,0.916667,0.611111,0.916667
673,9oul,pocket1,0.950287,1,1,0.903226,0.259259,0.903226
657,9ntc,pocket1,0.982443,1,1,0.717391,0.717391,0.647059
608,9fsj,pocket1,0.502134,1,1,0.812500,0.812500,0.764706
592,9ebs,pocket7,0.796260,1,1,0.857143,0.500000,0.857143
532,8v81,pocket1,0.977954,1,1,0.962963,0.208000,0.962963
498,8uk6,pocket1,0.946666,1,1,0.952381,0.540541,0.952381
475,8qni,pocket1,0.917425,1,1,0.966667,0.322222,0.966667
449,8jp0,pocket1,0.906662,1,1,0.781250,0.320513,0.781250
405,8hx9,pocket1,0.900688,1,1,0.884615,0.469388,0.884615
353,8fpi,pocket1,0.813792,1,1,0.775510,0.655172,0.775510
326,8f4s,pocket1,0.923800,1,1,0.846154,0.733333,0.846154
291,8crc,pocket9,0.041327,1,1,0.692308,0.600000,0.692308
285,7zpe,pocket3,0.639918,1,1,0.785714,0.578947,0.785714
159,7qpn,pocket2,0.829749,1,1,0.913043,0.700000,0.913043
146,7pt0,pocket2,0.900742,1,1,0.863636,0.527778,0.863636
131,7p2v,pocket7,0.225423,1,1,0.785714,0.785714,0.647059
64,7ac8,pocket1,0.715641,1,1,0.871795,0.693878,0.871795
55,6z74,pocket1,0.383723,1,1,0.818182,0.818182,0.720000
53,6z1m,pocket6,0.861763,1,1,0.833333,0.731707,0.833333
30,6vvq,pocket1,0.929778,1,1,0.777778,0.777778,0.736842
21,6s3a,pocket1,0.916088,1,1,0.740741,0.512821,0.740741
3,22mj,pocket2,0.804056,1,1,0.928571,0.590909,0.928571
637,9mft,pocket1,0.996670,1,0,0.000000,0.000000,0.000000
619,9lhf,pocket1,0.040825,1,0,0.782609,0.782609,0.620690
589,9d2r,pocket3,0.776362,1,0,0.000000,0.000000,0.000000
570,9b96,pocket1,0.714871,1,0,0.000000,0.000000,0.000000
426,8jb3,pocket1,0.827686,1,0,0.000000,0.000000,0.000000
309,8e24,pocket1,0.494149,1,0,0.166667,0.147059,0.166667
273,7yg5,pocket63,0.560827,1,0,0.000000,0.000000,0.000000
200,7xmd,pocket1,0.910560,1,0,0.000000,0.000000,0.000000
179,7ry1,pocket1,0.314387,1,0,0.000000,0.000000,0.000000
116,7oy0,pocket1,0.957723,1,0,0.150000,0.044118,0.150000
76,7agj,pocket11,0.820158,1,0,0.000000,0.000000,0.000000
19,6on4,pocket3,0.036457,1,0,0.000000,0.000000,0.000000
627,9mft,pocket18,0.041517,0,1,0.791667,0.791667,0.730769
585,9d2r,pocket1,0.554641,0,1,0.941176,0.695652,0.941176
582,9b96,pocket21,0.005604,0,1,0.833333,0.833333,0.666667
433,8jb3,pocket3,0.292251,0,1,0.920000,0.851852,0.920000
313,8e24,pocket4,0.412652,0,1,0.888889,0.888889,0.800000

In [23]:
our_results.query("pdb == '9mft'").sort_values(["prob"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
637,9mft,pocket1,9.966699e-01,1,0,0.000000,0.000000,0.000000
631,9mft,pocket7,7.835469e-01,0,0,0.000000,0.000000,0.000000
639,9mft,pocket2,4.122567e-01,0,0,0.000000,0.000000,0.000000
650,9mft,pocket3,1.622391e-01,0,0,0.000000,0.000000,0.000000
640,9mft,pocket20,5.491935e-02,0,0,0.000000,0.000000,0.000000
627,9mft,pocket18,4.151691e-02,0,1,0.791667,0.791667,0.730769
654,9mft,pocket6,1.697234e-02,0,0,0.076923,0.068966,0.076923
633,9mft,pocket13,7.605394e-03,0,0,0.000000,0.000000,0.000000
643,9mft,pocket30,5.665230e-03,0,0,0.000000,0.000000,0.000000
653,9mft,pocket21,2.508157e-03,0,0,0.000000,0.000000,0.000000
641,9mft,pocket4,1.770464e-03,0,0,0.000000,0.000000,0.000000
646,9mft,pocket10,9.920625e-04,0,0,0.000000,0.000000,0.000000
634,9mft,pocket23,7.264540e-04,0,0,0.285714,0.285714,0.230769
647,9mft,pocket5,7.258308e-04,0,0,0.000000,0.000000,0.000000
635,9mft,pocket14,4.720247e-04,0,0,0.000000,0.000000,0.000000
649,9mft,pocket24,4.170946e-04,0,0,0.000000,0.000000,0.000000
626,9mft,pocket28,3.728726e-04,0,0,0.000000,0.000000,0.000000
642,9mft,pocket29,3.087970e-04,0,0,0.052632,0.052632,0.038462
651,9mft,pocket12,2.762891e-04,0,0,0.000000,0.000000,0.000000
644,9mft,pocket17,2.342756e-04,0,0,0.000000,0.000000,0.000000
638,9mft,pocket27,2.094792e-04,0,0,0.000000,0.000000,0.000000
629,9mft,pocket25,6.229904e-05,0,0,0.000000,0.000000,0.000000
648,9mft,pocket8,4.161336e-05,0,0,0.000000,0.000000,0.000000
630,9mft,pocket15,3.400899e-05,0,0,0.000000,0.000000,0.000000
632,9mft,pocket22,1.248429e-05,0,0,0.000000,0.000000,0.000000
628,9mft,pocket11,3.304008e-06,0,0,0.181818,0.181818,0.076923
636,9mft,pocket26,3.016344e-06,0,0,0.333333,0.333333,0.115385
652,9mft,pocket19,4.551735e-07,0,0,0.000000,0.000000,0.000000
645,9mft,pocket9,4.443115e-07,0,0,0.000000,0.000000,0.000000
625,9mft,pocket16,1.507519e-08,0,0,0.000000,0.000000,0.000000

In [26]:
our_results.query("pdb == '8e24'").sort_values(["prob"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
309,8e24,pocket1,0.494149,1,0,0.166667,0.147059,0.166667
313,8e24,pocket4,0.412652,0,1,0.888889,0.888889,0.800000
303,8e24,pocket7,0.069771,0,0,0.000000,0.000000,0.000000
305,8e24,pocket13,0.045207,0,0,0.000000,0.000000,0.000000
315,8e24,pocket9,0.023964,0,0,0.000000,0.000000,0.000000
322,8e24,pocket19,0.015794,0,0,0.000000,0.000000,0.000000
321,8e24,pocket12,0.002156,0,0,0.000000,0.000000,0.000000
324,8e24,pocket6,0.001389,0,0,0.062500,0.062500,0.033333
320,8e24,pocket3,0.000987,0,0,0.000000,0.000000,0.000000
302,8e24,pocket15,0.000968,0,0,0.000000,0.000000,0.000000
300,8e24,pocket11,0.000794,0,0,0.000000,0.000000,0.000000
318,8e24,pocket8,0.000482,0,0,0.000000,0.000000,0.000000
299,8e24,pocket18,0.000312,0,0,0.000000,0.000000,0.000000
310,8e24,pocket27,0.000171,0,0,0.000000,0.000000,0.000000
297,8e24,pocket16,0.000150,0,0,0.000000,0.000000,0.000000
298,8e24,pocket28,0.000140,0,0,0.000000,0.000000,0.000000
314,8e24,pocket17,0.000138,0,0,0.000000,0.000000,0.000000
316,8e24,pocket10,0.000088,0,0,0.000000,0.000000,0.000000
319,8e24,pocket24,0.000053,0,0,0.000000,0.000000,0.000000
311,8e24,pocket2,0.000049,0,0,0.000000,0.000000,0.000000
312,8e24,pocket20,0.000037,0,0,0.000000,0.000000,0.000000
307,8e24,pocket14,0.000015,0,0,0.000000,0.000000,0.000000
317,8e24,pocket5,0.000012,0,0,0.454545,0.454545,0.166667
301,8e24,pocket25,0.000012,0,0,0.000000,0.000000,0.000000
308,8e24,pocket26,0.000005,0,0,0.000000,0.000000,0.000000
304,8e24,pocket22,0.000004,0,0,0.000000,0.000000,0.000000
306,8e24,pocket23,0.000004,0,0,0.000000,0.000000,0.000000
323,8e24,pocket21,0.000002,0,0,0.000000,0.000000,0.000000

In [9]:
our_results.query("pdb == '7oy0'").sort_values(["prob"], ascending=False).iloc[:40]

NameError: name 'our_results' is not defined

In [27]:
our_results.query("pdb == '8jb3'").sort_values(["prob"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
426,8jb3,pocket1,8.276858e-01,1,0,0.000000,0.000000,0.00
433,8jb3,pocket3,2.922507e-01,0,1,0.920000,0.851852,0.92
427,8jb3,pocket2,2.179353e-01,0,0,0.000000,0.000000,0.00
430,8jb3,pocket10,7.053933e-02,0,0,0.000000,0.000000,0.00
423,8jb3,pocket7,3.764052e-02,0,0,0.000000,0.000000,0.00
421,8jb3,pocket11,1.984207e-03,0,0,0.000000,0.000000,0.00
428,8jb3,pocket4,1.827343e-03,0,0,0.058824,0.058824,0.04
435,8jb3,pocket6,7.793623e-04,0,0,0.411765,0.411765,0.28
420,8jb3,pocket16,6.153825e-04,0,0,0.000000,0.000000,0.00
432,8jb3,pocket8,2.331167e-04,0,0,0.000000,0.000000,0.00
424,8jb3,pocket13,8.960642e-05,0,0,0.000000,0.000000,0.00
429,8jb3,pocket9,1.502002e-05,0,0,0.000000,0.000000,0.00
431,8jb3,pocket5,9.851783e-06,0,0,0.111111,0.111111,0.04
422,8jb3,pocket15,8.351878e-07,0,0,0.000000,0.000000,0.00
425,8jb3,pocket14,8.279610e-08,0,0,0.000000,0.000000,0.00
434,8jb3,pocket12,2.026012e-09,0,0,0.000000,0.000000,0.00

In [28]:
our_results.query("pdb == '9b96'").sort_values(["prob"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
570,9b96,pocket1,7.148713e-01,1,0,0.000000,0.000000,0.000000
571,9b96,pocket2,5.042924e-01,0,0,0.000000,0.000000,0.000000
583,9b96,pocket6,1.270476e-01,0,0,0.133333,0.105263,0.133333
568,9b96,pocket23,1.180363e-02,0,0,0.000000,0.000000,0.000000
582,9b96,pocket21,5.604086e-03,0,1,0.833333,0.833333,0.666667
579,9b96,pocket3,5.163046e-03,0,0,0.000000,0.000000,0.000000
564,9b96,pocket15,3.829577e-03,0,0,0.000000,0.000000,0.000000
575,9b96,pocket9,1.604969e-03,0,0,0.000000,0.000000,0.000000
577,9b96,pocket5,1.177435e-03,0,0,0.000000,0.000000,0.000000
565,9b96,pocket7,7.283384e-04,0,0,0.000000,0.000000,0.000000
580,9b96,pocket12,6.371338e-04,0,0,0.000000,0.000000,0.000000
574,9b96,pocket17,6.297022e-04,0,0,0.000000,0.000000,0.000000
573,9b96,pocket4,5.071322e-04,0,0,0.000000,0.000000,0.000000
566,9b96,pocket22,2.072340e-04,0,0,0.000000,0.000000,0.000000
567,9b96,pocket13,1.258868e-04,0,0,0.000000,0.000000,0.000000
561,9b96,pocket16,4.815960e-05,0,0,0.000000,0.000000,0.000000
578,9b96,pocket8,4.196753e-05,0,0,0.000000,0.000000,0.000000
563,9b96,pocket11,2.866534e-05,0,0,0.000000,0.000000,0.000000
576,9b96,pocket10,2.865086e-05,0,0,0.000000,0.000000,0.000000
562,9b96,pocket18,2.021542e-05,0,0,0.000000,0.000000,0.000000
569,9b96,pocket14,1.978127e-05,0,0,0.000000,0.000000,0.000000
581,9b96,pocket19,1.501985e-05,0,0,0.000000,0.000000,0.000000
572,9b96,pocket20,2.304080e-07,0,0,0.000000,0.000000,0.000000

In [29]:
our_results.query("pdb == '9d2r'").sort_values(["prob"], ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
589,9d2r,pocket3,0.776362,1,0,0.000000,0.000000,0.000000
585,9d2r,pocket1,0.554641,0,1,0.941176,0.695652,0.941176
587,9d2r,pocket4,0.324540,0,0,0.000000,0.000000,0.000000
586,9d2r,pocket2,0.067344,0,0,0.117647,0.111111,0.117647
588,9d2r,pocket5,0.038538,0,0,0.000000,0.000000,0.000000
584,9d2r,pocket7,0.006982,0,0,0.181818,0.181818,0.117647
590,9d2r,pocket6,0.000254,0,0,0.000000,0.000000,0.000000

## AllositePro

In [25]:
label_results(allositepro_results, site_in_pocket=0.65, pocket_in_site=0.6)

     pdb   pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
8   8crc  pocket1     1      1     1.000000        1.000000        0.692308
2   6vvq  pocket0     1      1     1.000000        1.000000        0.684211
10  8jp0  pocket0     1      1     1.000000        1.000000        0.312500
13  8uk6  pocket1     1      1     0.952381        0.833333        0.952381
4   6z1m  pocket1     1      1     0.944444        0.944444        0.472222
11  8qni  pocket0     1      1     0.933333        0.608696        0.933333
15  9fsj  pocket0     1      1     0.923077        0.923077        0.705882
9   8f4s  pocket0     1      1     0.846154        0.733333        0.846154
0   22mj  pocket0     1      1     0.821429        0.766667        0.821429
16  9oul  pocket0     1      1     0.814815        0.814815        0.709677
14  8v81  pocket0     1      1     0.800000        0.800000        0.444444
17  9ow9  pocket0     1      1     0.750000        0.529412        0.750000
1   6s3a  pocket0     1      1     0.631579        0.631579        0.444444
3   6z1m  pocket0     1      0     0.083333        0.075000        0.083333
7   8crc  pocket0     1      0     0.076923        0.058824        0.076923
12  8uk6  pocket0     1      0     0.047619        0.031250        0.047619
6   7zpe  pocket0     1      0     0.000000        0.000000        0.000000
5   7yg5  pocket0     1      0     0.000000        0.000000        0.000000

In [28]:
models["allositepro"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.6}

## PASSer

In [41]:
label_results(passer_results["ensemble"], site_in_pocket=0.65, pocket_in_site=0.7).iloc[:40]

      pdb pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
262  8uk6      1     1      1     0.904762        0.904762        0.904762
306  8v81     49     1      1     0.888889        0.666667        0.888889
241  8qni     13     1      1     0.833333        0.510204        0.833333
0    7gqu     20     1      1     0.758621        0.687500        0.758621
141  8aq6      8     1      1     0.740741        0.740741        0.689655
158  8f4s      9     1      1     0.730769        0.730769        0.730769
182  8jp0     57     1      1     0.718750        0.534884        0.718750
31   7yg5     29     0      1     0.708333        0.708333        0.586207
166  8f4s     15     0      0     0.625000        0.625000        0.192308
250  8qni      1     0      0     0.428571        0.428571        0.200000
157  8aq6      9     0      0     0.428571        0.428571        0.103448
391  9dnm      3     0      0     0.400000        0.400000        0.400000
292  8uk6     34     0      0     0.400000        0.400000        0.095238
144  8aq6      2     0      0     0.400000        0.400000        0.206897
276  8uk6      7     0      0     0.384615        0.384615        0.238095
200  8jp0     14     0      0     0.375000        0.375000        0.093750
86   7yg5     23     0      0     0.375000        0.375000        0.103448
90   7yg5     34     0      0     0.333333        0.333333        0.068966
18   7gqu      3     0      0     0.333333        0.333333        0.103448
153  8aq6      3     0      0     0.333333        0.333333        0.068966
242  8qni     19     1      0     0.307692        0.307692        0.266667
326  8v81      8     0      0     0.307692        0.307692        0.148148
299  8uk6     36     0      0     0.300000        0.300000        0.142857
217  8jp0      5     0      0     0.300000        0.300000        0.093750
183  8jp0     59     1      0     0.285714        0.285714        0.125000
399  9dnm     30     0      0     0.285714        0.285714        0.200000
169  8f4s      7     0      0     0.250000        0.250000        0.076923
1    7gqu      7     1      0     0.241379        0.089744        0.241379
186  8jp0     47     0      0     0.238095        0.238095        0.156250
142  8aq6     11     1      0     0.230769        0.230769        0.103448
266  8uk6      8     0      0     0.230769        0.230769        0.142857
178  8f4s     21     0      0     0.222222        0.222222        0.076923
279  8uk6      5     0      0     0.200000        0.200000        0.095238
6    7gqu     17     0      0     0.200000        0.200000        0.068966
370  8v81     29     0      0     0.181818        0.181818        0.074074
312  8v81      2     0      0     0.153846        0.153846        0.074074
15   7gqu     12     0      0     0.142857        0.142857        0.034483
227  8jp0     31     0      0     0.142857        0.142857        0.031250
140  8aq6     18     1      0     0.137931        0.102564        0.137931
291  8uk6     30     0      0     0.125000        0.125000        0.047619

In [42]:
models["passer_ensemble"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.7}

In [43]:
label_results(passer_results["automl"], site_in_pocket=0.65, pocket_in_site=0.7).iloc[:40]

      pdb pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
262  8uk6      1     1      1     0.904762        0.904762        0.904762
307  8v81     49     0      1     0.888889        0.666667        0.888889
241  8qni     13     1      1     0.833333        0.510204        0.833333
1    7gqu     20     1      1     0.758621        0.687500        0.758621
141  8aq6      8     1      1     0.740741        0.740741        0.689655
158  8f4s      9     1      1     0.730769        0.730769        0.730769
182  8jp0     57     1      1     0.718750        0.534884        0.718750
31   7yg5     29     0      1     0.708333        0.708333        0.586207
164  8f4s     15     0      0     0.625000        0.625000        0.192308
149  8aq6      9     0      0     0.428571        0.428571        0.103448
248  8qni      1     0      0     0.428571        0.428571        0.200000
289  8uk6     34     0      0     0.400000        0.400000        0.095238
393  9dnm      3     0      0     0.400000        0.400000        0.400000
142  8aq6      2     1      0     0.400000        0.400000        0.206897
279  8uk6      7     0      0     0.384615        0.384615        0.238095
207  8jp0     14     0      0     0.375000        0.375000        0.093750
128  7yg5     23     0      0     0.375000        0.375000        0.103448
148  8aq6      3     0      0     0.333333        0.333333        0.068966
78   7yg5     34     0      0     0.333333        0.333333        0.068966
9    7gqu      3     0      0     0.333333        0.333333        0.103448
242  8qni     19     1      0     0.307692        0.307692        0.266667
330  8v81      8     0      0     0.307692        0.307692        0.148148
208  8jp0      5     0      0     0.300000        0.300000        0.093750
285  8uk6     36     0      0     0.300000        0.300000        0.142857
183  8jp0     59     1      0     0.285714        0.285714        0.125000
400  9dnm     30     0      0     0.285714        0.285714        0.200000
180  8f4s      7     0      0     0.250000        0.250000        0.076923
0    7gqu      7     1      0     0.241379        0.089744        0.241379
184  8jp0     47     1      0     0.238095        0.238095        0.156250
275  8uk6      8     0      0     0.230769        0.230769        0.142857
144  8aq6     11     0      0     0.230769        0.230769        0.103448
160  8f4s     21     1      0     0.222222        0.222222        0.076923
2    7gqu     17     1      0     0.200000        0.200000        0.068966
278  8uk6      5     0      0     0.200000        0.200000        0.095238
324  8v81     29     0      0     0.181818        0.181818        0.074074
314  8v81      2     0      0     0.153846        0.153846        0.074074
219  8jp0     31     0      0     0.142857        0.142857        0.031250
19   7gqu     12     0      0     0.142857        0.142857        0.034483
140  8aq6     18     1      0     0.137931        0.102564        0.137931
274  8uk6     30     0      0     0.125000        0.125000        0.047619

In [44]:
models["passer_automl"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.7}

In [45]:
label_results(passer_results["rank"], site_in_pocket=0.65, pocket_in_site=0.7).iloc[:40]

      pdb pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
262  8uk6      1     1      1     0.904762        0.904762        0.904762
325  8v81     49     0      1     0.888889        0.666667        0.888889
249  8qni     13     0      1     0.833333        0.510204        0.833333
3    7gqu     20     0      1     0.758621        0.687500        0.758621
144  8aq6      8     0      1     0.740741        0.740741        0.689655
160  8f4s      9     1      1     0.730769        0.730769        0.730769
198  8jp0     57     0      1     0.718750        0.534884        0.718750
80   7yg5     29     0      1     0.708333        0.708333        0.586207
177  8f4s     15     0      0     0.625000        0.625000        0.192308
147  8aq6      9     0      0     0.428571        0.428571        0.103448
241  8qni      1     1      0     0.428571        0.428571        0.200000
387  9dnm      3     0      0     0.400000        0.400000        0.400000
290  8uk6     34     0      0     0.400000        0.400000        0.095238
141  8aq6      2     1      0     0.400000        0.400000        0.206897
273  8uk6      7     0      0     0.384615        0.384615        0.238095
51   7yg5     23     0      0     0.375000        0.375000        0.103448
207  8jp0     14     0      0     0.375000        0.375000        0.093750
85   7yg5     34     0      0     0.333333        0.333333        0.068966
143  8aq6      3     0      0     0.333333        0.333333        0.068966
19   7gqu      3     0      0     0.333333        0.333333        0.103448
247  8qni     19     0      0     0.307692        0.307692        0.266667
359  8v81      8     0      0     0.307692        0.307692        0.148148
280  8uk6     36     0      0     0.300000        0.300000        0.142857
205  8jp0      5     0      0     0.300000        0.300000        0.093750
402  9dnm     30     0      0     0.285714        0.285714        0.200000
192  8jp0     59     0      0     0.285714        0.285714        0.125000
178  8f4s      7     0      0     0.250000        0.250000        0.076923
1    7gqu      7     1      0     0.241379        0.089744        0.241379
201  8jp0     47     0      0     0.238095        0.238095        0.156250
269  8uk6      8     0      0     0.230769        0.230769        0.142857
146  8aq6     11     0      0     0.230769        0.230769        0.103448
170  8f4s     21     0      0     0.222222        0.222222        0.076923
264  8uk6      5     1      0     0.200000        0.200000        0.095238
9    7gqu     17     0      0     0.200000        0.200000        0.068966
324  8v81     29     0      0     0.181818        0.181818        0.074074
305  8v81      2     1      0     0.153846        0.153846        0.074074
13   7gqu     12     0      0     0.142857        0.142857        0.034483
190  8jp0     31     0      0     0.142857        0.142857        0.031250
145  8aq6     18     0      0     0.137931        0.102564        0.137931
410  9dnm     16     0      0     0.125000        0.125000        0.100000

In [46]:
models["passer_rank"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.7}

## DeepAllo

In [47]:
label_results(deepallo_results, site_in_pocket=0.65, pocket_in_site=0.65, special_8aq6_sc=True).iloc[:40]

      pdb     pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
245  8uk6    pocket1     1      1     0.904762        0.904762        0.904762
288  8v81    pocket2     1      1     0.888889        0.666667        0.888889
224  8qni    pocket1     1      1     0.833333        0.543478        0.833333
1    7gqu    pocket2     1      1     0.758621        0.687500        0.758621
140  8f4s    pocket1     1      1     0.730769        0.730769        0.730769
167  8jp0    pocket1     0      1     0.718750        0.534884        0.718750
31   7yg5    pocket2     0      1     0.708333        0.708333        0.586207
396  8aq6  pocket1_G     1      1     0.666667        0.666667        0.375000
153  8f4s   pocket13     0      0     0.625000        0.625000        0.192308
223  8qni    pocket2     1      0     0.428571        0.428571        0.200000
401  8aq6  pocket4_G     0      0     0.428571        0.428571        0.187500
366  9dnm    pocket3     0      0     0.400000        0.400000        0.400000
278  8uk6   pocket34     0      0     0.400000        0.400000        0.095238
247  8uk6    pocket7     1      0     0.384615        0.384615        0.238095
63   7yg5   pocket37     0      0     0.375000        0.375000        0.103448
178  8jp0   pocket15     0      0     0.375000        0.375000        0.093750
403  8aq6  pocket5_H     0      0     0.333333        0.333333        0.153846
74   7yg5   pocket48     0      0     0.333333        0.333333        0.068966
6    7gqu    pocket6     0      0     0.333333        0.333333        0.103448
299  8v81   pocket12     0      0     0.307692        0.307692        0.148148
242  8qni   pocket20     0      0     0.307692        0.307692        0.266667
170  8jp0    pocket6     0      0     0.300000        0.300000        0.093750
280  8uk6   pocket36     0      0     0.300000        0.300000        0.142857
391  9dnm   pocket31     0      0     0.285714        0.285714        0.200000
222  8jp0   pocket59     0      0     0.285714        0.285714        0.125000
149  8f4s    pocket9     0      0     0.250000        0.250000        0.076923
0    7gqu    pocket1     1      0     0.241379        0.089744        0.241379
211  8jp0   pocket48     0      0     0.238095        0.238095        0.156250
253  8uk6    pocket8     0      0     0.230769        0.230769        0.142857
161  8f4s   pocket21     0      0     0.222222        0.222222        0.076923
399  8aq6  pocket4_H     0      0     0.200000        0.200000        0.076923
251  8uk6    pocket5     0      0     0.200000        0.200000        0.095238
18   7gqu   pocket18     0      0     0.200000        0.200000        0.068966
305  8v81   pocket18     0      0     0.181818        0.181818        0.074074
291  8v81    pocket4     0      0     0.153846        0.153846        0.074074
13   7gqu   pocket13     0      0     0.142857        0.142857        0.034483
195  8jp0   pocket32     0      0     0.142857        0.142857        0.031250
376  9dnm   pocket15     0      0     0.125000        0.125000        0.100000
126  7yg5  pocket100     0      0     0.125000        0.125000        0.034483
240  8qni   pocket18     0      0     0.125000        0.125000        0.033333

In [48]:
models["deepallo"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.65, "special_8aq6_sc": True}

## STINGAllo

In [49]:
label_results(stingallo_results, site_in_pocket=None, pocket_in_site=1)

    pdb  pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
0  8qni  pocket     1      1          1.0             1.0        0.033333
2  8aq6  pocket     1      1          1.0             1.0        0.034483
1  7gqu  pocket     1      0          0.0             0.0        0.000000

In [50]:
models["stingallo"]["labelling"] = {"site_in_pocket": None, "pocket_in_site": 1}

## AlloFusion

In [51]:
result = label_results(allofusion_results, site_in_pocket=None, pocket_in_site=1)
result

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
54,8aq6,pocket_G_10,1,1,1.0,1.0,0.034483
19,8qni,pocket_A_141,1,1,1.0,1.0,0.033333
22,8uk6,pocket_A_265,1,1,1.0,1.0,0.047619
23,8uk6,pocket_A_268,1,1,1.0,1.0,0.047619
57,8aq6,pocket_G_57,1,1,1.0,1.0,0.034483
...,...,...,...,...,...,...,...
24,8uk6,pocket_A_465,1,0,0.0,0.0,0.000000
21,8qni,pocket_A_289,1,0,0.0,0.0,0.000000
20,8qni,pocket_A_143,1,0,0.0,0.0,0.000000
18,8qni,pocket_A_132,1,0,0.0,0.0,0.000000
30,8v81,pocket_A_464,1,0,0.0,0.0,0.000000

In [52]:
mask = ((result.pred == 1) & (result.label == 1))
mask

54     True
19     True
22     True
23     True
57     True
      ...
24    False
21    False
20    False
18    False
30    False
Length: 74, dtype: bool

In [53]:
pd.concat((
    result.loc[result[mask].drop_duplicates("pdb").index],
    result[~mask]
))

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
54,8aq6,pocket_G_10,1,1,1.0,1.0,0.034483
19,8qni,pocket_A_141,1,1,1.0,1.0,0.033333
22,8uk6,pocket_A_265,1,1,1.0,1.0,0.047619
8,7gqu,pocket_A_891,1,1,1.0,1.0,0.034483
28,8v81,pocket_A_347,1,1,1.0,1.0,0.037037
...,...,...,...,...,...,...,...
24,8uk6,pocket_A_465,1,0,0.0,0.0,0.000000
21,8qni,pocket_A_289,1,0,0.0,0.0,0.000000
20,8qni,pocket_A_143,1,0,0.0,0.0,0.000000
18,8qni,pocket_A_132,1,0,0.0,0.0,0.000000
30,8v81,pocket_A_464,1,0,0.0,0.0,0.000000

In [54]:
models["allofusion"]["labelling"] = {"site_in_pocket": None, "pocket_in_site": 1}

## AllosES

In [55]:
label_results(alloses_results, site_in_pocket=0.65, pocket_in_site=0.7, special_8aq6_sc=True).iloc[:40]

      pdb     pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
244  8uk6    pocket1     0      1     0.904762        0.904762        0.904762
287  8v81   pocket49     0      1     0.888889        0.666667        0.888889
222  8qni   pocket13     0      1     0.833333        0.510204        0.833333
1    7gqu   pocket20     0      1     0.758621        0.687500        0.758621
138  8f4s    pocket9     1      1     0.730769        0.730769        0.730769
162  8jp0   pocket57     1      1     0.718750        0.534884        0.718750
45   7yg5   pocket29     0      1     0.708333        0.708333        0.586207
397  8aq6  pocket1_G     0      0     0.666667        0.666667        0.375000
152  8f4s   pocket15     0      0     0.625000        0.625000        0.192308
223  8qni    pocket1     0      0     0.428571        0.428571        0.200000
409  8aq6  pocket4_G     0      0     0.428571        0.428571        0.187500
385  9dnm    pocket3     0      0     0.400000        0.400000        0.400000
262  8uk6   pocket34     0      0     0.400000        0.400000        0.095238
271  8uk6    pocket7     0      0     0.384615        0.384615        0.238095
50   7yg5   pocket23     0      0     0.375000        0.375000        0.103448
166  8jp0   pocket14     0      0     0.375000        0.375000        0.093750
73   7yg5   pocket34     0      0     0.333333        0.333333        0.068966
406  8aq6  pocket4_H     0      0     0.333333        0.333333        0.153846
19   7gqu    pocket3     0      0     0.333333        0.333333        0.103448
301  8v81    pocket8     0      0     0.307692        0.307692        0.148148
224  8qni   pocket19     0      0     0.307692        0.307692        0.266667
265  8uk6   pocket36     0      0     0.300000        0.300000        0.142857
167  8jp0    pocket5     0      0     0.300000        0.300000        0.093750
187  8jp0   pocket60     0      0     0.285714        0.285714        0.125000
371  9dnm   pocket30     0      0     0.285714        0.285714        0.200000
154  8f4s    pocket7     0      0     0.250000        0.250000        0.076923
0    7gqu    pocket7     1      0     0.241379        0.089744        0.241379
163  8jp0   pocket47     0      0     0.238095        0.238095        0.156250
247  8uk6    pocket8     0      0     0.230769        0.230769        0.142857
161  8f4s   pocket21     0      0     0.222222        0.222222        0.076923
245  8uk6    pocket5     0      0     0.200000        0.200000        0.095238
3    7gqu   pocket17     0      0     0.200000        0.200000        0.068966
404  8aq6  pocket8_H     0      0     0.200000        0.200000        0.076923
310  8v81   pocket29     0      0     0.181818        0.181818        0.074074
297  8v81    pocket2     0      0     0.153846        0.153846        0.074074
168  8jp0   pocket32     0      0     0.142857        0.142857        0.031250
12   7gqu   pocket12     0      0     0.142857        0.142857        0.034483
389  9dnm   pocket16     0      0     0.125000        0.125000        0.100000
400  8aq6  pocket9_G     0      0     0.125000        0.125000        0.062500
278  8uk6   pocket30     0      0     0.125000        0.125000        0.047619

In [56]:
models["alloses"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.65, "special_8aq6_sc": True}

## MEF-AlloSite

In [57]:
label_results(mefallosite_results, site_in_pocket=0.65, pocket_in_site=0.7).iloc[:40]

      pdb    pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
243  8uk6   pocket1     0      1     0.904762        0.904762        0.904762
287  8v81  pocket36     0      1     0.888889        0.666667        0.888889
209  8qni  pocket13     0      1     0.833333        0.510204        0.833333
17   7gqu  pocket14     1      1     0.758621        0.687500        0.758621
114  8aq6   pocket5     1      1     0.740741        0.740741        0.689655
133  8f4s   pocket8     1      1     0.720000        0.720000        0.692308
184  8jp0  pocket49     0      1     0.718750        0.534884        0.718750
55   7yg5  pocket12     0      1     0.708333        0.708333        0.586207
126  8f4s  pocket16     0      0     0.625000        0.625000        0.192308
6    7gqu   pocket3     0      0     0.454545        0.454545        0.172414
210  8qni   pocket1     0      0     0.428571        0.428571        0.200000
107  8aq6  pocket10     0      0     0.428571        0.428571        0.103448
110  8aq6   pocket2     0      0     0.400000        0.400000        0.206897
321  9dnm   pocket3     0      0     0.400000        0.400000        0.400000
224  8uk6  pocket27     0      0     0.400000        0.400000        0.095238
250  8uk6   pocket7     0      0     0.384615        0.384615        0.238095
182  8jp0  pocket13     0      0     0.375000        0.375000        0.093750
41   7yg5  pocket16     0      0     0.375000        0.375000        0.103448
274  8v81   pocket6     0      0     0.333333        0.333333        0.148148
18   7gqu   pocket4     0      0     0.333333        0.333333        0.103448
109  8aq6   pocket3     0      0     0.333333        0.333333        0.068966
61   7yg5  pocket20     0      0     0.333333        0.333333        0.068966
216  8qni  pocket19     1      0     0.307692        0.307692        0.266667
180  8jp0   pocket5     0      0     0.300000        0.300000        0.093750
230  8uk6  pocket29     0      0     0.300000        0.300000        0.142857
330  9dnm  pocket28     0      0     0.285714        0.285714        0.200000
166  8jp0  pocket52     0      0     0.285714        0.285714        0.125000
125  8f4s  pocket10     0      0     0.285714        0.285714        0.076923
138  8f4s  pocket14     0      0     0.285714        0.285714        0.076923
113  8aq6   pocket8     0      0     0.250000        0.250000        0.103448
187  8jp0  pocket41     0      0     0.238095        0.238095        0.156250
238  8uk6   pocket8     0      0     0.230769        0.230769        0.142857
240  8uk6   pocket5     0      0     0.200000        0.200000        0.095238
5    7gqu  pocket16     0      0     0.200000        0.200000        0.068966
304  8v81   pocket4     0      0     0.200000        0.200000        0.074074
255  8v81  pocket21     0      0     0.181818        0.181818        0.074074
162  8jp0  pocket29     0      0     0.142857        0.142857        0.031250
15   7gqu  pocket13     0      0     0.142857        0.142857        0.034483
4    7gqu  pocket23     0      0     0.137931        0.059701        0.137931
108  8aq6  pocket16     0      0     0.137931        0.102564        0.137931

In [58]:
models["mefallosite"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": 0.7}

## ALLO

In [59]:
label_results(allo_results, site_in_pocket=0.65, pocket_in_site=None).iloc[:40]

      pdb pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
42   8uk6    P_0     0      1     1.000000        0.375000        1.000000
22   8qni    P_0     1      1     1.000000        0.312500        1.000000
197  8jp0    P_0     1      1     0.968750        0.248000        0.968750
176  7gqu    P_1     0      1     0.950000        0.950000        0.655172
163  8v81    P_0     1      1     0.925926        0.500000        0.925926
105  8aq6    P_0     0      1     0.862069        0.510204        0.862069
120  8f4s    P_0     0      1     0.846154        0.758621        0.846154
12   9dnm    P_0     1      1     0.700000        0.066038        0.700000
93   7yg5    P_1     0      1     0.655172        0.513514        0.655172
65   7yg5   P_39     0      0     0.500000        0.500000        0.137931
173  7gqu    P_2     0      0     0.333333        0.333333        0.206897
142  8v81   P_13     0      0     0.318182        0.318182        0.259259
175  7gqu    P_0     1      0     0.310345        0.152542        0.310345
114  8f4s    P_6     0      0     0.294118        0.294118        0.192308
106  8aq6    P_1     0      0     0.208333        0.208333        0.172414
87   7yg5    P_7     0      0     0.166667        0.166667        0.137931
125  8v81   P_20     0      0     0.142857        0.142857        0.074074
43   8uk6    P_1     1      0     0.142857        0.066667        0.142857
185  8jp0   P_16     0      0     0.117647        0.117647        0.062500
97   8aq6    P_8     0      0     0.111111        0.111111        0.068966
127  8v81   P_22     0      0     0.100000        0.100000        0.037037
102  8aq6    P_5     1      0     0.095238        0.095238        0.068966
167  7gqu    P_8     0      0     0.090909        0.090909        0.034483
118  8f4s    P_2     0      0     0.090909        0.090909        0.076923
100  8aq6    P_7     0      0     0.083333        0.083333        0.034483
101  8aq6    P_4     0      0     0.083333        0.083333        0.034483
147  8v81   P_18     0      0     0.076923        0.076923        0.037037
121  8f4s    P_1     0      0     0.076923        0.074074        0.076923
69   7yg5   P_11     0      0     0.058824        0.058824        0.034483
21   8qni    P_3     0      0     0.052632        0.052632        0.033333
39   8uk6    P_5     0      0     0.047619        0.045455        0.047619
174  7gqu    P_3     0      0     0.045455        0.045455        0.034483
91   7yg5    P_3     0      0     0.035714        0.035714        0.034483
132  8v81   P_42     0      0     0.000000        0.000000        0.000000
131  8v81   P_26     0      0     0.000000        0.000000        0.000000
133  8v81   P_41     0      0     0.000000        0.000000        0.000000
140  8v81   P_11     0      0     0.000000        0.000000        0.000000
134  8v81   P_40     0      0     0.000000        0.000000        0.000000
135  8v81   P_38     0      0     0.000000        0.000000        0.000000
136  8v81   P_39     0      0     0.000000        0.000000        0.000000

In [60]:
models["allo"]["labelling"] = {"site_in_pocket": 0.65, "pocket_in_site": None}

<br>

In [61]:
pd.to_pickle(models, "models.pkl")

# Scoring

## Original

In [70]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news:
        if pdb == "9dnm": continue #######################################################################################
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            # Top1 pred for our model
            if model == "model5":
                # pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
                pass
            elif model == "allofusion":
                pdbpreds = pdbpreds.drop(
                    pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
                    .index[1:]
                )
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'7gqu': {'total': 15, 'tp': 1, 'fn': 0, 'fp': 0},
  '7yg5': {'total': 66, 'tp': 0, 'fn': 1, 'fp': 1},
  '8aq6': {'total': 13, 'tp': 1, 'fn': 0, 'fp': 0},
  '8f4s': {'total': 10, 'tp': 1, 'fn': 0, 'fp': 0},
  '8jp0': {'total': 34, 'tp': 1, 'fn': 0, 'fp': 0},
  '8qni': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '8uk6': {'total': 30, 'tp': 1, 'fn': 0, 'fp': 0},
  '8v81': {'total': 45, 'tp': 1, 'fn': 0, 'fp': 2}},
 'allositepro': {'7gqu': {'tp': 1, 'fn': 0, 'fp': 0},
  '7yg5': {'tp': 0, 'fn': 1, 'fp': 1},
  '8aq6': {'tp': 1, 'fn': 0, 'fp': 1},
  '8f4s': {'tp': 1, 'fn': 0, 'fp': 0},
  '8jp0': {'tp': 1, 'fn': 0, 'fp': 0},
  '8qni': {'tp': 1, 'fn': 0, 'fp': 0},
  '8uk6': {'tp': 1, 'fn': 0, 'fp': 1},
  '8v81': {'tp': 1, 'fn': 0, 'fp': 0}},
 'stingallo': {'7gqu': {'tp': 0, 'fn': 1, 'fp': 1},
  '7yg5': {'tp': 0, 'fn': 1, 'fp': 0},
  '8aq6': {'tp': 1, 'fn': 0, 'fp': 0},
  '8f4s': {'tp': 0, 'fn': 1, 'fp': 0},
  '8jp0': {'tp': 0, 'fn': 1, 'fp': 0},
  '8qni': {'tp': 1, 'fn': 0, 'fp': 0},
  '8uk6': {'tp': 0, 'fn': 1, 'fp': 0},
  '8v81': {'tp': 0, 'fn': 1, 'fp': 0}},
 'allofusion': {'7gqu': {'tp': 1, 'fn': 0, 'fp': 8},
  '7yg5': {'tp': 0, 'fn': 1, 'fp': 3},
  '8aq6': {'tp': 1, 'fn': 0, 'fp': 17},
  '8f4s': {'tp': 0, 'fn': 1, 'fp': 4},
  '8jp0': {'tp': 0, 'fn': 1, 'fp': 2},
  '8qni': {'tp': 1, 'fn': 0, 'fp': 3},
  '8uk6': {'tp': 1, 'fn': 0, 'fp': 4},
  '8v81': {'tp': 1, 'fn': 0, 'fp': 15}},
 'passer_ensemble': {'7gqu': {'total': 27, 'tp': 1, 'fn': 0, 'fp': 2},
  '7yg5': {'total': 113, 'tp': 0, 'fn': 1, 'fp': 3},
  '8aq6': {'total': 18, 'tp': 1, 'fn': 0, 'fp': 2},
  '8f4s': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 2},
  '8jp0': {'total': 59, 'tp': 1, 'fn': 0, 'fp': 2},
  '8qni': {'total': 21, 'tp': 1, 'fn': 0, 'fp': 2},
  '8uk6': {'total': 42, 'tp': 1, 'fn': 0, 'fp': 2},
  '8v81': {'total': 74, 'tp': 1, 'fn': 0, 'fp': 2}},
 'passer_automl': {'7gqu': {'total': 27, 'tp': 1, 'fn': 0, 'fp': 2},
  '7yg5': {'total': 113, 'tp': 0, 'fn': 1, 'fp': 3},
  '8aq6': {'total': 18, 'tp': 1, 'fn': 0, 'fp': 2},
  '8f4s': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 2},
  '8jp0': {'total': 59, 'tp': 1, 'fn': 0, 'fp': 2},
  '8qni': {'total': 21, 'tp': 1, 'fn': 0, 'fp': 2},
  '8uk6': {'total': 42, 'tp': 1, 'fn': 0, 'fp': 2},
  '8v81': {'total': 74, 'tp': 0, 'fn': 1, 'fp': 3}},
 'passer_rank': {'7gqu': {'total': 27, 'tp': 0, 'fn': 1, 'fp': 3},
  '7yg5': {'total': 113, 'tp': 0, 'fn': 1, 'fp': 3},
  '8aq6': {'total': 18, 'tp': 0, 'fn': 1, 'fp': 3},
  '8f4s': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 2},
  '8jp0': {'total': 59, 'tp': 0, 'fn': 1, 'fp': 3},
  '8qni': {'total': 21, 'tp': 0, 'fn': 1, 'fp': 3},
  '8uk6': {'total': 42, 'tp': 1, 'fn': 0, 'fp': 2},
  '8v81': {'total': 74, 'tp': 0, 'fn': 1, 'fp': 3}},
 'deepallo': {'7gqu': {'total': 27, 'tp': 1, 'fn': 0, 'fp': 2},
  '7yg5': {'total': 113, 'tp': 0, 'fn': 1, 'fp': 3},
  '8aq6': {'total': 18, 'tp': 1, 'fn': 0, 'fp': 2},
  '8f4s': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 2},
  '8jp0': {'total': 59, 'tp': 0, 'fn': 1, 'fp': 3},
  '8qni': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 2},
  '8uk6': {'total': 42, 'tp': 1, 'fn': 0, 'fp': 2},
  '8v81': {'total': 74, 'tp': 1, 'fn': 0, 'fp': 2}},
 'alloses': {'7gqu': {'total': 27, 'tp': 0, 'fn': 1, 'fp': 1},
  '7yg5': {'total': 111, 'tp': 0, 'fn': 1, 'fp': 0},
  '8aq6': {'total': 18, 'tp': 0, 'fn': 1, 'fp': 0},
  '8f4s': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 0},
  '8jp0': {'total': 60, 'tp': 1, 'fn': 0, 'fp': 0},
  '8qni': {'total': 21, 'tp': 0, 'fn': 1, 'fp': 0},
  '8uk6': {'total': 42, 'tp': 0, 'fn': 1, 'fp': 1},
  '8v81': {'total': 74, 'tp': 0, 'fn': 1, 'fp': 1}},
 'mefallosite': {'7gqu': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '7yg5': {'total': 83, 'tp': 0, 'fn': 1, 'fp': 1},
  '8aq6': {'total': 16, 'tp': 1, 'fn': 0, 'fp': 0},
  '8f4s': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 0},
  '8jp0': {'total': 52, 'tp': 0, 'fn': 1, 'fp': 1},
  '8qni': {'total': 21, 'tp': 0, 'fn': 1, 'fp': 1},
  '8uk6': {'total': 35, 'tp': 0, 'fn': 1, 'fp': 1},
  '8v81': {'total': 60, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allo': {'7gqu': {'total': 12, 'tp': 0, 'fn': 1, 'fp': 1},
  '7yg5': {'total': 50, 'tp': 0, 'fn': 1, 'fp': 1},
  '8aq6': {'total': 13, 'tp': 0, 'fn': 1, 'fp': 1},
  '8f4s': {'total': 15, 'tp': 0, 'fn': 1, 'fp': 1},
  '8jp0': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 0},
  '8qni': {'total': 10, 'tp': 1, 'fn': 0, 'fp': 0},
  '8uk6': {'total': 20, 'tp': 0, 'fn': 1, 'fp': 1},
  '8v81': {'total': 43, 'tp': 1, 'fn': 0, 'fp': 0}}}

In [29]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [72]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
model5,model5,7,1,3,0.774031,0.884364,0 1 0 219 3 1 1 7
passer_ensemble,passer_ensemble,7,1,17,0.489352,0.706319,0 1 0 353 17 1 1 7
allositepro,allositepro,7,1,3,NaN,NaN,NaN
deepallo,deepallo,6,2,18,0.414027,0.673726,0 1 0 353 18 1 2 6
passer_automl,passer_automl,6,2,18,0.413975,0.673688,0 1 0 352 18 1 2 6
allofusion,allofusion,5,3,56,NaN,NaN,NaN
mefallosite,mefallosite,3,5,5,0.358553,0.679276,0 1 0 299 5 1 5 3
allo,allo,3,5,5,0.346751,0.673376,0 1 0 172 5 1 5 3
alloses,alloses,2,6,3,0.304708,0.647773,0 1 0 366 3 1 6 2
passer_rank,passer_rank,2,6,22,0.112467,0.543163,0 1 0 348 22 1 6 2
stingallo,stingallo,2,6,1,NaN,NaN,NaN

In [65]:
models_metrics.infer_objects().to_csv("models_metrics.csv", index=False, sep="\t", decimal=",")

## TopX

In [30]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"], topx=True)
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news:
        if pdb == "9dnm": continue #######################################################################################
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            # Top1 pred for our model
            if model == "model5":
                pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
            # elif model == "allofusion":
            #     pdbpreds = pdbpreds.drop(
            #         pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
            #         .index[1:]
            #     )
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'22mj': {'total': 12, 'tp': 1, 'fn': 0, 'fp': 0},
  '6s3a': {'total': 6, 'tp': 1, 'fn': 0, 'fp': 0},
  '6vvq': {'total': 13, 'tp': 1, 'fn': 0, 'fp': 0},
  '6z1m': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '7p2v': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xmd': {'total': 15, 'tp': 0, 'fn': 1, 'fp': 1},
  '7yg5': {'total': 66, 'tp': 0, 'fn': 1, 'fp': 1},
  '7zpe': {'total': 11, 'tp': 1, 'fn': 0, 'fp': 0},
  '8crc': {'total': 10, 'tp': 1, 'fn': 0, 'fp': 0},
  '8f4s': {'total': 10, 'tp': 1, 'fn': 0, 'fp': 0},
  '8fpi': {'total': 59, 'tp': 1, 'fn': 0, 'fp': 0},
  '8jp0': {'total': 33, 'tp': 1, 'fn': 0, 'fp': 0},
  '8qni': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '8uk6': {'total': 30, 'tp': 1, 'fn': 0, 'fp': 0},
  '8v81': {'total': 45, 'tp': 1, 'fn': 0, 'fp': 0},
  '9ebs': {'total': 13, 'tp': 1, 'fn': 0, 'fp': 0},
  '9fsj': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '9ntc': {'total': 12, 'tp': 1, 'fn': 0, 'fp': 0},
  '9oul': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '9ow9': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 0}},
 'allositepro': {'22mj': {'tp': 1, 'fn': 0, 'fp': 0},
  '6s3a': {'tp': 1, 'fn': 0, 'fp': 0},
  '6vvq': {'tp': 1, 'fn': 0, 'fp': 0},
  '6z1m': {'tp': 0, 'fn': 1, 'fp': 1},
  '7p2v': {'tp': 0, 'fn': 1, 'fp': 0},
  '7xmd': {'tp': 0, 'fn': 1, 'fp': 0},
  '7yg5': {'tp': 0, 'fn': 1, 'fp': 1},
  '7zpe': {'tp': 0, 'fn': 1, 'fp': 1},
  '8crc': {'tp': 1, 'fn': 0, 'fp': 0},
  '8f4s': {'tp': 1, 'fn': 0, 'fp': 0},
  '8fpi': {'tp': 0, 'fn': 1, 'fp': 0},
  '8jp0': {'tp': 1, 'fn': 0, 'fp': 0},
  '8qni': {'tp': 1, 'fn': 0, 'fp': 0},
  '8uk6': {'tp': 1, 'fn': 0, 'fp': 0},
  '8v81': {'tp': 1, 'fn': 0, 'fp': 0},
  '9ebs': {'tp': 0, 'fn': 1, 'fp': 0},
  '9fsj': {'tp': 1, 'fn': 0, 'fp': 0},
  '9ntc': {'tp': 0, 'fn': 1, 'fp': 0},
  '9oul': {'tp': 1, 'fn': 0, 'fp': 0},
  '9ow9': {'tp': 1, 'fn': 0, 'fp': 0}}}

allositepro vs allopockets
allositepro fails 6z1m, 7p2v, 7zpe, 8fpi, 9ebs, 9ntc
we both fail 7xmd, 7yg5

In [31]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [32]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
model5,model5,18,2,2,0.895157,0.947579,0 1 0 411 2 1 2 18
allositepro,allositepro,12,8,3,NaN,NaN,NaN

In [69]:
models_metrics.infer_objects().to_csv("models_metrics_topx.csv", index=False, sep="\t", decimal=",")

# Old

In [79]:
model = "passer_ensemble"
modeld = models["passer_ensemble"]

results = modeld["results"]
results

{'7gqu': {'20': {'pred': 1,
   'prob/score': 50.99665205925703,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         916                 ?
   1             A         917                 ?
   4             A         920                 ?
   5             A         727                 ?
   6             A         919                 ?
   8             A         555                 ?
   9             A         552                 ?
   11            A         551                 ?
   12            A         846                 ?
   13            A         845                 ?
   15            A         849                 ?
   17            A         913                 ?
   25            A         706                 ?
   26            A         570                 ?
   27            A         726                 ?
   29            A         725                 ?
   30            A         898                 ?
   31            A         895                 ?
   32            A         730                 ?
   33            A         729                 ?
   34            A         921                 ?
   37            A         923                 ?
   46            A         728                 ?
   55            A         731                 ?
   58            A         575                 ?
   65            A         891                 ?
   68            A         914                 ?
   70            A         704                 ?
   74            A         550                 ?
   90            A         571                 ?
   93            A         918                 ?
   94            A         572                 ?},
  '7': {'pred': 1,
   'prob/score': 49.41235993755981,
   'residues':     auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0              A         601                 ?
   1              A         829                 ?
   3              A         573                 ?
   4              A         577                 ?
   6              A         578                 ?
   ..           ...         ...               ...
   203            A         923                 ?
   204            A         551                 ?
   208            A         547                 ?
   215            A         883                 ?
   228            A         801                 ?

   [78 rows x 3 columns]},
  '26': {'pred': 1,
   'prob/score': 23.19833954970818,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         908                 ?
   1             A         907                 ?
   2             A         942                 ?
   4             A         906                 ?
   7             A         938                 ?
   10            A         931                 ?
   19            A         939                 ?
   23            A         911                 ?
   27            A         930                 ?},
  '25': {'pred': 0,
   'prob/score': 20.856095535418717,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         753                 ?
   1             A         740                 ?
   2             A         865                 ?
   3             A         752                 ?
   4             A         764                 ?
   7             A         835                 ?
   8             A         861                 ?
   18            A         763                 ?
   20            A         834                 ?
   21            A         863                 ?
   27            A         862                 ?
   29            A         767                 ?
   31            A         765                 ?},
  '13': {'pred': 0,
   'prob/score': 20.51994323519466,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         770                 ?
   1             A         822                 ?
   3             A         851                 ?
   4             A         772                 ?
   5             A         842                 ?
   6             A         771                 ?
   7             A         838                 ?
   8             A         843                 ?
   9             A         874                 ?
   15            A         821                 ?
   18            A         841                 ?
   20            A         840                 ?},
  '2': {'pred': 0,
   'prob/score': 17.54845840478083,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         782                 ?
   2             A         786                 ?
   4             A         783                 ?
   5             A         745                 ?
   6             A         747                 ?
   7             A         748                 ?
   10            A         779                 ?
   11            A         746                 ?
   18            A         744                 ?
   26            A         778                 ?},
  '17': {'pred': 0,
   'prob/score': 14.923921372246696,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         916                 ?
   1             A         901                 ?
   3             A         915                 ?
   4             A         897                 ?
   5             A         898                 ?
   6             A         894                 ?
   8             A         912                 ?
   9             A         907                 ?
   13            A         905                 ?
   18            A         911                 ?},
  '24': {'pred': 0,
   'prob/score': 14.705987280467525,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         620                 ?
   1             A         618                 ?
   2             A         623                 ?
   4             A         622                 ?
   6             A         621                 ?
   7             A         599                 ?
   10            A         645                 ?
   16            A         642                 ?
   17            A         644                 ?
   21            A         603                 ?},
  '27': {'pred': 0,
   'prob/score': 12.084111606236547,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         921                 ?
   1             A         529                 ?
   4             A         527                 ?
   10            A         551                 ?
   13            A         923                 ?
   14            A         924                 ?
   19            A         922                 ?},
  '23': {'pred': 0,
   'prob/score': 11.598408490681322,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         885                 ?
   1            A         884                 ?
   6            A         676                 ?
   7            A         675                 ?},
  '8': {'pred': 0,
   'prob/score': 9.782421146519482,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         555                 ?
   3             A         529                 ?
   6             A         551                 ?
   7             A         527                 ?
   8             A         528                 ?
   9             A         554                 ?
   11            A         558                 ?
   15            A         559                 ?
   16            A         724                 ?
   19            A         563                 ?
   25            A         565                 ?},
  '15': {'pred': 0,
   'prob/score': 9.648617967104656,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         551                 ?
   1             A         528                 ?
   2             A         549                 ?
   3             A         527                 ?
   7             A         532                 ?
   10            A         531                 ?
   11            A         548                 ?
   12            A         537                 ?
   16            A         923                 ?},
  '18': {'pred': 0,
   'prob/score': 9.595284333408927,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         887                 ?
   1             A         712                 ?
   2             A         716                 ?
   6             A         885                 ?
   8             A         676                 ?
   9             A         713                 ?
   17            A         709                 ?},
  '14': {'pred': 0,
   'prob/score': 8.403278334299102,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         816                 ?
   3             A         762                 ?
   8             A         766                 ?
   11            A         813                 ?
   15            A         832                 ?
   16            A         815                 ?
   19            A         790                 ?
   24            A         760                 ?
   25            A         814                 ?},
  '9': {'pred': 0,
   'prob/score': 8.249239697579469,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         772                 ?
   2             A         873                 ?
   3             A         776                 ?
   4             A         773                 ?
   6             A         779                 ?
   7             A         775                 ?
   10            A         839                 ?
   11            A         742                 ?
   13            A         840                 ?
   16            A         872                 ?
   19            A         871                 ?},
  '12': {'pred': 0,
   'prob/score': 7.974500021373387,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         708                 ?
   1             A         712                 ?
   3             A         887                 ?
   6             A         709                 ?
   10            A         890                 ?
   13            A         891                 ?
   15            A         894                 ?},
  '19': {'pred': 0,
   'prob/score': 7.825264678103849,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         761                 ?
   1             A         751                 ?
   2             A         754                 ?
   4             A         747                 ?
   11            A         787                 ?},
  '1': {'pred': 0,
   'prob/score': 7.762596171232872,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         901                 ?
   3             A         904                 ?
   4             A         905                 ?
   9             A         897                 ?
   12            A         900                 ?},
  '3': {'pred': 0,
   'prob/score': 7.009097188711166,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         914                 ?
   1             A         915                 ?
   4             A         907                 ?
   5             A         911                 ?
   9             A         922                 ?
   10            A         918                 ?
   11            A         920                 ?
   14            A         930                 ?
   17            A         917                 ?},
  '6': {'pred': 0,
   'prob/score': 6.528391333267791,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         615                 ?
   1            A         613                 ?
   5            A         614                 ?
   6            A         610                 ?},
  '22': {'pred': 0,
   'prob/score': 5.526737066975329,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         564                 ?
   1             A         663                 ?
   3             A         588                 ?
   7             A         590                 ?
   8             A         561                 ?
   10            A         661                 ?
   11            A         657                 ?
   13            A         662                 ?},
  '21': {'pred': 0,
   'prob/score': 5.438909065560438,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         543                 ?
   2            A         637                 ?
   4            A         586                 ?
   5            A         615                 ?
   6            A         613                 ?
   8            A         614                 ?},
  '5': {'pred': 0,
   'prob/score': 5.067528717336245,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         721                 ?
   1             A         566                 ?
   2             A         564                 ?
   3             A         691                 ?
   6             A         565                 ?
   9             A         696                 ?
   13            A         695                 ?
   16            A         563                 ?},
  '4': {'pred': 0,
   'prob/score': 4.62313298630761,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         579                 ?
   1             A         578                 ?
   3             A         544                 ?
   5             A         546                 ?
   6             A         608                 ?
   8             A         582                 ?
   9             A         609                 ?
   10            A         614                 ?
   11            A         612                 ?
   12            A         543                 ?},
  '11': {'pred': 0,
   'prob/score': 4.5262425999681,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         811                 ?
   1             A         808                 ?
   2             A         604                 ?
   3             A         807                 ?
   5             A         829                 ?
   10            A         601                 ?
   11            A         605                 ?
   12            A         608                 ?},
  '16': {'pred': 0,
   'prob/score': 4.503542592283338,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         884                 ?
   1             A         676                 ?
   4             A         678                 ?
   7             A         675                 ?
   9             A         883                 ?
   13            A         882                 ?},
  '10': {'pred': 0,
   'prob/score': 4.307141790923197,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         534                 ?
   1             A         537                 ?
   3             A         532                 ?
   5             A         538                 ?
   6             A         541                 ?
   12            A         533                 ?}},
 '7yg5': {'46': {'pred': 1,
   'prob/score': 58.27678069472313,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         479                 ?
   1             A         575                 ?
   2             A         482                 ?
   6             A         474                 ?
   7             A         530                 ?
   8             A         534                 ?
   10            A         548                 ?
   11            A         519                 ?
   12            A         572                 ?
   15            A         522                 ?
   17            A         523                 ?
   18            A         544                 ?
   19            A         535                 ?
   23            A         526                 ?
   24            A         541                 ?
   26            A         538                 ?
   27            A         478                 ?
   29            A         578                 ?
   32            A         484                 ?
   33            A         480                 ?
   34            A         579                 ?
   35            A         483                 ?
   49            A         473                 ?
   56            A         470                 ?
   59            A         582                 ?
   61            A         476                 ?
   83            A         387                 ?
   85            A         581                 ?
   93            A         540                 ?},
  '36': {'pred': 1,
   'prob/score': 51.058829203248024,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A        1765                 ?
   1             A        1761                 ?
   3             A        1869                 ?
   14            A        1786                 ?
   16            A        1782                 ?
   19            A        1769                 ?
   21            A        1790                 ?
   22            A        1870                 ?
   24            A        1787                 ?
   25            A        1866                 ?
   28            A        1766                 ?
   32            A        1777                 ?
   34            A        1768                 ?
   35            A        1789                 ?
   39            A        1868                 ?
   40            A        1865                 ?
   52            A        1793                 ?
   53            A        1764                 ?
   55            A        1812                 ?
   57            A        1783                 ?
   59            A        1815                 ?
   67            A        1811                 ?},
  '113': {'pred': 1,
   'prob/score': 48.98447059094906,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A        1249                 ?
   3             A        1251                 ?
   4             A        1691                 ?
   5             A        1252                 ?
   6             A        1255                 ?
   10            A        1693                 ?
   13            A        1694                 ?
   14            A        1631                 ?
   15            A        1678                 ?
   16            A        1686                 ?
   17            A        1687                 ?
   22            A        1690                 ?
   31            A        1679                 ?
   32            A        1695                 ?
   40            A        1681                 ?
   41            A        1176                 ?
   43            A        1178                 ?
   47            A        1628                 ?
   49            A        1680                 ?},
  '106': {'pred': 0,
   'prob/score': 44.90342438220978,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A        1299                 ?
   1             A        1413                 ?
   2             A        1414                 ?
   4             A         592                 ?
   5             A        1417                 ?
   10            A        1409                 ?
   13            A        1292                 ?
   15            A        1295                 ?
   17            A         577                 ?
   18            A         586                 ?
   19            A         540                 ?
   21            A         539                 ?
   23            A         596                 ?
   24            A         589                 ?
   28            A         594                 ?

In [84]:
modeld["prob_key"]

'prob/score'

In [80]:
if modeld["labelling"] is not None:
    labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
# else:
#     labelled_results = pd.DataFrame((
#         {
#             "pdb": pdb,
#             "pocket": pocket,
#             **pocketd
#         }
#         for pdb, pockets in results.items()
#         for pocket, pocketd in pockets.items()
#     ))
labelled_results

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
262,8uk6,1,71.084872,1,1,0.904762,0.904762,0.904762
306,8v81,49,42.582709,0,1,0.888889,0.666667,0.888889
241,8qni,13,48.563351,1,1,0.833333,0.510204,0.833333
0,7gqu,20,50.996652,1,1,0.758621,0.687500,0.758621
141,8aq6,8,46.686667,0,1,0.740741,0.740741,0.689655
...,...,...,...,...,...,...,...,...
133,7yg5,69,3.204734,0,0,0.000000,0.000000,0.000000
131,7yg5,58,3.321074,0,0,0.000000,0.000000,0.000000
130,7yg5,86,3.379763,0,0,0.000000,0.000000,0.000000
129,7yg5,44,3.398566,0,0,0.000000,0.000000,0.000000
145,8aq6,10,15.124823,0,0,0.000000,0.000000,0.000000

In [81]:
labelled_results.sort_values("pred", ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
378,9dnm,20,57.407993,1,0,0.000000,0.000000,0.000000
140,8aq6,18,49.659825,1,0,0.137931,0.102564,0.137931
304,8v81,73,61.714813,1,0,0.000000,0.000000,0.000000
182,8jp0,57,51.007666,1,1,0.718750,0.534884,0.718750
158,8f4s,9,50.438614,1,1,0.730769,0.730769,0.730769
0,7gqu,20,50.996652,1,1,0.758621,0.687500,0.758621
241,8qni,13,48.563351,1,1,0.833333,0.510204,0.833333
27,7yg5,46,58.276781,1,0,0.000000,0.000000,0.000000
262,8uk6,1,71.084872,1,1,0.904762,0.904762,0.904762
354,8v81,17,4.550745,0,0,0.000000,0.000000,0.000000
58,7yg5,11,15.623070,0,0,0.000000,0.000000,0.000000
373,8v81,27,2.716598,0,0,0.000000,0.000000,0.000000
34,7yg5,14,39.475310,0,0,0.000000,0.000000,0.000000
410,9dnm,21,4.304450,0,0,0.000000,0.000000,0.000000
2,7gqu,26,23.198340,0,0,0.000000,0.000000,0.000000
26,7gqu,10,4.307142,0,0,0.000000,0.000000,0.000000
4,7gqu,13,20.519943,0,0,0.000000,0.000000,0.000000
5,7gqu,2,17.548458,0,0,0.000000,0.000000,0.000000
7,7gqu,24,14.705987,0,0,0.000000,0.000000,0.000000
8,7gqu,27,12.084112,0,0,0.000000,0.000000,0.000000
9,7gqu,23,11.598408,0,0,0.000000,0.000000,0.000000
10,7gqu,8,9.782421,0,0,0.000000,0.000000,0.000000
91,7yg5,74,7.495750,0,0,0.000000,0.000000,0.000000
78,7yg5,110,9.003326,0,0,0.000000,0.000000,0.000000
79,7yg5,78,8.848810,0,0,0.000000,0.000000,0.000000
80,7yg5,63,8.770246,0,0,0.000000,0.000000,0.000000
81,7yg5,56,8.728628,0,0,0.000000,0.000000,0.000000
82,7yg5,15,8.244746,0,0,0.000000,0.000000,0.000000
83,7yg5,19,8.195416,0,0,0.000000,0.000000,0.000000
84,7yg5,49,7.946248,0,0,0.000000,0.000000,0.000000
85,7yg5,25,7.806240,0,0,0.000000,0.000000,0.000000
3,7gqu,25,20.856096,0,0,0.000000,0.000000,0.000000
357,8v81,30,4.263869,0,0,0.000000,0.000000,0.000000
358,8v81,7,4.230528,0,0,0.000000,0.000000,0.000000
359,8v81,14,4.171339,0,0,0.000000,0.000000,0.000000
347,8v81,35,6.706599,0,0,0.000000,0.000000,0.000000
361,8v81,46,3.823596,0,0,0.000000,0.000000,0.000000
362,8v81,21,3.605678,0,0,0.000000,0.000000,0.000000
363,8v81,53,3.589557,0,0,0.000000,0.000000,0.000000
364,8v81,16,3.391715,0,0,0.000000,0.000000,0.000000

In [ ]:
preds = {}
for pdb in news:
    if pdb == "9dnm": continue #######################################################################################
    pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
    total = len(pdbpreds)
    if total > 0:
        # Top1 pred for our model
        if model == "model5":
            pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
        elif model == "allofusion":
            pdbpreds = pdbpreds.drop(
                pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
                .index[1:]
            )
        tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
        fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
        fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
        if tp + fn == 0:
            fn = 1 # There's at least 1 allo. pocket per PDB
    else:
        tp, fp = 0, 0
        fn = 1 # There's at least 1 allo. pocket per PDB

    if total == 0 or not modeld["all_pockets_in_output"]:
        preds[pdb] = {
            "tp": tp,
            "fn": fn,
            "fp": fp
        }
    else:
        preds[pdb] = {
            "total": total,
            "tp": tp,
            "fn": fn,
            "fp": fp
        }

models_preds[model] = preds

In [71]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [72]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
model5,model5,7,1,1,0.870495,0.935248,0 1 0 221 1 1 1 7
allositepro,allositepro,7,1,1,NaN,NaN,NaN
passer_ensemble,passer_ensemble,5,3,3,0.616892,0.808446,0 1 0 367 3 1 3 5
allofusion,allofusion,5,3,56,NaN,NaN,NaN
passer_automl,passer_automl,4,4,4,0.489189,0.744595,0 1 0 366 4 1 4 4
alloses,alloses,3,5,5,0.36145,0.680725,0 1 0 364 5 1 5 3
mefallosite,mefallosite,3,5,5,0.358553,0.679276,0 1 0 299 5 1 5 3
allo,allo,3,5,5,0.346751,0.673376,0 1 0 172 5 1 5 3
deepallo,deepallo,2,6,6,0.233827,0.616914,0 1 0 365 6 1 6 2
stingallo,stingallo,2,6,1,NaN,NaN,NaN
passer_rank,passer_rank,1,7,7,0.106081,0.553041,0 1 0 363 7 1 7 1

In [65]:
models_metrics.infer_objects().to_csv("models_metrics.csv", index=False, sep="\t", decimal=",")

## Top1

models_preds_top1 = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        try:
            labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
        except:
            print(model)
            raise
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news:
        pdbpreds = pd.DataFrame(labelled_results.query(f"pdb == '{pdb}'"))
        total = len(pdbpreds)
        if total > 0:
            if modeld["prob_key"] is not None:
                pdbpreds["pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int))
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds_top1[model] = preds

models_preds_top1

models_metrics_top1 = {}

for model, preds in models_preds_top1.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics_top1[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics_top1[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics_top1 = pd.DataFrame(models_metrics_top1).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics_top1

models_metrics_top1.loc[models_metrics.index]