In [1]:
import os, pickle
import pandas as pd

In [2]:
import sys
sys.path.append("../../training_data")

In [3]:
from utils.utils import Cif

# Data

In [4]:
with open("../../training_data/8.Apos/Extra_set/features.pkl", "rb") as f:
    news = pickle.load(f)

len(news), news

(9,
 {'8sgj':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       8sgj               1             A           52            A
  1       8sgj               1             A           53            A
  2       8sgj               1             A           54            A
  3       8sgj               1             A           55            A
  4       8sgj               1             A           56            A
  ..       ...             ...           ...          ...          ...
  746     8sgj               1             A          941            A
  747     8sgj               1             A          942            A
  748     8sgj               1             A          943            A
  749     8sgj               1             A          944            A
  750     8sgj               1             A          945            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0            17                 ?     0               0               0  ...
  1            18                 ?     0               0               0  ...
  2            19                 ?     0               0               0  ...
  3            20                 ?     0               0               1  ...
  4            21                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  746         931                 ?     0               1               0  ...
  747         932                 ?     0               0               0  ...
  748         933                 ?     0               0               1  ...
  749         934                 ?     0               0               0  ...
  750         935                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.951318  0.009978  0.038929  0.439825  0.560195  0.190518  0.809442
  1    0.898132  0.085141  0.016805  0.182757  0.817335  0.157454  0.842647
  2    0.980099  0.015135  0.004629  0.563700  0.436484  0.223137  0.777007
  3    0.990343  0.004066  0.005739  0.307786  0.692075  0.204334  0.795536
  4    0.951978  0.036071  0.011670  0.133693  0.866337  0.108292  0.891929
  ..        ...       ...       ...       ...       ...       ...       ...
  746  0.997231  0.000944  0.001883  1.000000  0.000000  0.082698  0.917640
  747  0.991030  0.003431  0.005437  0.367292  0.632878  0.299993  0.699793
  748  0.948027  0.025453  0.026608  0.371388  0.628507  0.191843  0.808321
  749  0.966606  0.028976  0.004163  0.582771  0.417255  0.678772  0.321302
  750  0.995160  0.002228  0.002438  1.000000  0.000000  0.756284  0.243501


        Neff Neff_I Neff_D
  0    6.284  1.030  1.223
  1    6.291  1.302  1.298
  2    6.295  1.089  1.292
  3    6.430  1.009  1.243
  4    6.446  1.154  1.215
  ..     ...    ...    ...
  746  8.860  1.005  1.018
  747  8.675  1.010  1.036
  748  8.609  1.034  1.068
  749  8.477  1.038  1.194
  750  8.265  1.000  1.079

  [751 rows x 174 columns],
  'AF-A0A1D8PQM9-F1':              Residues                                                          \
                    pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0    AF-A0A1D8PQM9-F1               1             A            1            A
  1    AF-A0A1D8PQM9-F1               1             A            2            A
  2    AF-A0A1D8PQM9-F1               1             A            3            A
  3    AF-A0A1D8PQM9-F1               1             A            4            A
  4    AF-A0A1D8PQM9-F1               1             A            5            A
  ..                ...             ...           ...          ...          ...
  794  AF-A0A1D8PQM9-F1               1             A          795            A
  795  AF-A0A1D8PQM9-F1               1             A          796            A
  796  AF-A0A1D8PQM9-F1               1             A          797            A
  797  AF-A0A1D8PQM9-F1               1             A          798            A
  798  AF-A0A1D8PQM9-F1               1             A          799            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             1                 ?     0               0               0  ...
  1             2                 ?     0               0               0  ...
  2             3                 ?     0               0               0  ...
  3             4                 ?     0               0               0  ...
  4             5                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  794         795                 ?     0               0               0  ...
  795         796                 ?     0               1               0  ...
  796         797                 ?     0               1               0  ...
  797         798                 ?     0               0               0  ...
  798         799                 ?     0               0               0  ...

        HHBlits                                                                  \
           M->M      M->I      M->D      I->M      I->I D->M D->D   Neff Neff_I
  0    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  4.335  0.000
  1    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  4.332  0.000
  2    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  6.375  0.000
  3    0.948684  0.044286  0.007274  0.519070  0.480964  0.0  0.0  6.532  1.015
  4    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  1.0  6.603  0.000
  ..        ...       ...       ...       ...       ...  ...  ...    ...    ...
  794  0.993092  0.005296  0.001690  0.191976  0.808321  0.0  1.0  5.617  1.012
  795  0.997923  0.002401  0.000000  0.446583  0.553632  1.0  0.0  5.576  1.002
  796  0.991717  0.008269  0.000000  0.490390  0.509446  0.0  0.0  5.523  1.010
  797  0.992404  0.007764  0.000000  1.000000  0.000000  0.0  0.0  5.428  1.007
  798  1.000000  0.000000  0.000000  1.000000  0.000000  0.0  0.0  3.703  0.000


      Neff_D
  0    0.000
  1    0.000
  2    0.000
  3    0.000
  4    1.000
  ..     ...
  794  1.016
  795  1.020
  796  0.000
  797  0.000
  798  0.000

  [799 rows x 174 columns],
  '7l6r':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       7l6r               1             A            1            A
  1       7l6r               1             A            2            A
  2       7l6r               1             A            3            A
  3       7l6r               1             A            4            A
  4       7l6r               1             A            5            A
  ..       ...             ...           ...          ...          ...
  295     7l6r               1             A          296            A
  296     7l6r               1             A          297            A
  297     7l6r               1             A          298            A
  298     7l6r               1             A          299            A
  299     7l6r               1             A          300            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0          6797                 ?     0               0               0  ...
  1          6798                 ?     0               0               0  ...
  2          6799                 ?     0               0               0  ...
  3          6800                 ?     0               0               0  ...
  4          6801                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  295        7092                 ?     0               0               0  ...
  296        7093                 ?     0               0               0  ...
  297        7094                 ?     0               0               0  ...
  298        7095                 ?     0               0               0  ...
  299        7096                 ?     0               0               0  ...

        HHBlits
           M->M      M->I      M->D I->M I->I D->M D->D   Neff Neff_I Neff_D
  0    1.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  5.853  0.000  0.000
  1    1.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  6.786  0.000  0.000
  2    0.967947  0.000000  0.032062  0.0  0.0  0.0  0.0  7.141  0.000  0.000
  3    1.000000  0.000000  0.000000  0.0  0.0  1.0  0.0  7.655  0.000  1.075
  4    0.961261  0.015625  0.023004  1.0  0.0  0.0  0.0  7.880  1.079  0.000
  ..        ...       ...       ...  ...  ...  ...  ...    ...    ...    ...
  295  1.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  2.308  0.000  0.000
  296  1.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  2.308  0.000  0.000
  297  1.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  2.308  0.000  0.000
  298  1.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  2.126  0.000  0.000
  299  1.000000  0.000000  0.000000  1.0  0.0  0.0  0.0  2.026  0.000  0.000

  [300 rows x 174 columns],
  '8vw5':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       8vw5               1             A            5            A
  1       8vw5               1             A            6            A
  2       8vw5               1             A            7            A
  3       8vw5               1             A            8            A
  4       8vw5               1             A            9            A
  ..       ...             ...           ...          ...          ...
  299     8vw5               1             A          304            A
  300     8vw5               1             A          305            A
  301     8vw5               1             A          306            A
  302     8vw5               1             A          307            A
  303     8vw5               1             A          308            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0            38                 ?     0               0               0  ...
  1            39                 ?     0               1               0  ...
  2            40                 ?     0               1               0  ...
  3            41                 ?     0               1               0  ...
  4            42                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  299         337                 ?     0               0               0  ...
  300         338                 ?     0               0               0  ...
  301         339                 ?     0               0               0  ...
  302         340                 ?     0               0               0  ...
  303         341                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.952638  0.012319  0.034770  0.242155  0.757858  0.000000  0.000000
  1    1.000000  0.000000  0.000000  0.000000  0.000000  0.679243  0.320634
  2    0.864537  0.053032  0.082355  0.259175  0.740720  0.000000  1.000000
  3    0.969962  0.030019  0.000000  0.494485  0.505576  0.883928  0.116065
  4    1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
  ..        ...       ...       ...       ...       ...       ...       ...
  299  1.000000  0.000000  0.000000  0.000000  0.000000  0.170755  0.829320
  300  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
  301  0.799960  0.199990  0.000000  0.956608  0.043045  0.000000  0.000000
  302  0.995160  0.004819  0.000000  1.000000  0.000000  0.000000  0.000000
  303  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


        Neff Neff_I Neff_D
  0    3.861  1.017  0.000
  1    4.142  0.000  1.027
  2    4.216  1.068  1.005
  3    4.495  1.050  1.125
  4    4.590  0.000  1.010
  ..     ...    ...    ...
  299  6.963  0.000  1.046
  300  6.659  0.000  1.037
  301  6.476  1.251  0.000
  302  6.310  1.002  0.000
  303  6.082  0.000  0.000

  [304 rows x 174 columns],
  '6yhr':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       6yhr               1             A           13            A
  1       6yhr               1             A           14            A
  2       6yhr               1             A           15            A
  3       6yhr               1             A           16            A
  4       6yhr               1             A           17            A
  ..       ...             ...           ...          ...          ...
  536     6yhr               1             A          553            A
  537     6yhr               1             A          554            A
  538     6yhr               1             A          555            A
  539     6yhr               1             A          556            A
  540     6yhr               1             A          557            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0           528                 ?     0               0               0  ...
  1           529                 ?     0               0               0  ...
  2           530                 ?     0               0               0  ...
  3           531                 ?     0               1               0  ...
  4           532                 ?     0               0               0  ...
  ..          ...               ...   ...             ...             ...  ...
  536        1068                 ?     0               0               0  ...
  537        1069                 ?     0               0               0  ...
  538        1070                 ?     0               0               1  ...
  539        1071                 ?     0               0               0  ...
  540        1072                 ?     0               0               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0    0.980779  0.005900  0.013471  1.000000  0.000000  0.000000  1.000000
  1    0.986917  0.011606  0.001366  0.503129  0.496891  0.150830  0.849096
  2    0.988971  0.003434  0.007823  0.500000  0.500000  0.446583  0.553632
  3    0.993092  0.006570  0.000000  0.433168  0.566835  0.275476  0.724471
  4    0.983502  0.002152  0.014259  0.500000  0.500000  0.216734  0.782954
  ..        ...       ...       ...       ...       ...       ...       ...
  536  1.000000  0.000000  0.000000  0.000000  0.000000  0.550953  0.449066
  537  0.893166  0.099373  0.007386  0.848508  0.151669  0.000000  1.000000
  538  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
  539  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
  540  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


         Neff Neff_I Neff_D
  0    10.662  1.000  1.023
  1    10.632  1.016  1.037
  2    10.847  1.000  1.048
  3    10.989  1.014  1.041
  4    11.149  1.000  1.027
  ..      ...    ...    ...
  536   2.305  0.000  1.015
  537   2.278  1.117  1.003
  538   2.270  0.000  1.011
  539   2.270  0.000  1.011
  540   2.270  0.000  0.000

  [541 rows x 174 columns],
  '7xlq':      Residues                                                          \
            pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0        7xlq               1             A           76            A
  1        7xlq               1             A           77            A
  2        7xlq               1             A           78            A
  3        7xlq               1             A           79            A
  4        7xlq               1             A           80            A
  ...       ...             ...           ...          ...          ...
  1314     7xlq               1             A         1867            A
  1315     7xlq               1             A         1868            A
  1316     7xlq               1             A         1869            A
  1317     7xlq               1             A         1870            A
  1318     7xlq               1             A         1871            A

                                     Label     Amino acids                  ...  \
       auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
  0             76                 ?     0               0               0  ...
  1             77                 ?     0               0               0  ...
  2             78                 ?     0               0               0  ...
  3             79                 ?     0               0               0  ...
  4             80                 ?     0               0               0  ...
  ...          ...               ...   ...             ...             ...  ...
  1314        1867                 ?     0               0               0  ...
  1315        1868                 ?     0               0               0  ...
  1316        1869                 ?     0               0               0  ...
  1317        1870                 ?     0               1               0  ...
  1318        1871                 ?     0               1               0  ...

         HHBlits                                                              \
            M->M      M->I      M->D      I->M      I->I      D->M      D->D
  0     0.997923  0.001115  0.000782  1.000000  0.000000  0.071051  0.929161
  1     0.988971  0.007325  0.003434  0.274904  0.724973  0.310357  0.689680
  2     0.985549  0.008520  0.005723  0.248445  0.751581  0.323536  0.676424
  3     0.992404  0.001790  0.006012  0.064614  0.935623  0.087595  0.912565
  4     0.991030  0.006263  0.002367  0.261159  0.738669  0.184156  0.815637
  ...        ...       ...       ...       ...       ...       ...       ...
  1314  0.982140  0.017787  0.000000  1.000000  0.000000  0.117522  0.882703
  1315  0.996540  0.002181  0.001338  0.190782  0.809442  0.361985  0.638164
  1316  0.953960  0.046007  0.000000  0.933033  0.067265  0.057472  0.942785
  1317  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
  1318  0.997231  0.002726  0.000000  0.247757  0.752102  0.075992  0.924023


         Neff Neff_I Neff_D
  0     8.362  1.001  1.129
  1     8.411  1.018  1.123
  2     8.575  1.019  1.097
  3     8.609  1.006  1.076
  4     8.642  1.024  1.090
  ...     ...    ...    ...
  1314  6.021  1.025  1.115
  1315  6.050  1.002  1.102
  1316  6.077  1.052  1.066
  1317  6.077  0.000  1.062
  1318  6.078  1.003  1.062

  [1319 rows x 174 columns],
  '7sns':     Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
  0       7sns               1             A            4            A
  1       7sns               1             A            5            A
  2       7sns               1             A            6            A

In [5]:
with open("../../training_data/8.Apos/Extra_set/apos_sites.pkl", "rb") as f:
    news_sites = {k: [{"id": sid, "site": site["site"]} for sid, site in v.items()] for k, v in pickle.load(f).items() if k in news}

len(news_sites), news_sites

(9,
 {'8sgj': [{'id': (0, 'P32418', 'A'),
    'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            GLU             A               1          132                 ?
    1            THR             A               1          133                 ?
    2            VAL             A               1          134                 ?
    3            SER             A               1          135                 ?
    4            LEU             A               1          137                 ?
    5            THR             A               1          138                 ?
    6            ALA             A               1          141                 ?
    7            HIS             A               1          200                 ?
    8            VAL             A               1          203                 ?
    9            VAL             A               1          206                 ?
    10           THR             A               1          207                 ?
    11           ALA             A               1          208                 ?
    12           TRP             A               1          210                 ?
    13           SER             A               1          211                 ?
    14           PHE             A               1          241                 ?
    15           ILE             A               1          244                 ?
    16           CYS             A               1          245                 ?
    17           PHE             A               1          248                 ?
    18           ALA             A               1          249                 ?
    19           LEU             A               1          256                 ?
    20           GLU             A               1          279                 ?
    21           THR             A               1          803                 ?
    22           ILE             A               1          804                 ?
    23           GLY             A               1          805                 ?
    24           LEU             A               1          806                 ?
    25           LYS             A               1          807                 ?
    26           ASP             A               1          808                 ?
    27           VAL             A               1          810                 ?
    28           THR             A               1          811                 ?
    29           ALA             A               1          812                 ?
    30           VAL             A               1          814                 ?
    31           PHE             A               1          815                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0           97          GLU            A                  1              132
    1           98          THR            A                  1              133
    2           99          VAL            A                  1              134
    3          100          SER            A                  1              135
    4          102          LEU            A                  1              137
    5          103          THR            A                  1              138
    6          106          ALA            A                  1              141
    7          165          HIS            A                  1              200
    8          168          VAL            A                  1              203
    9          171          VAL            A                  1              206
    10         172          THR            A                  1              207
    11         173          ALA            A                  1              208
    12         175          TRP            A                  1              210
    13         176          SER            A                  1              211
    14         206          PHE            A                  1              241
    15         209          ILE            A                  1              244
    16         210          CYS            A                  1              245
    17         213          PHE            A                  1              248
    18         214          ALA            A                  1              249
    19         221          LEU            A                  1              256
    20         244          GLU            A                  1              279
    21         793          THR            A                  1              803
    22         794          ILE            A                  1              804
    23         795          GLY            A                  1              805
    24         796          LEU            A                  1              806
    25         797          LYS            A                  1              807
    26         798          ASP            A                  1              808
    27         800          VAL            A                  1              810
    28         801          THR            A                  1              811
    29         802          ALA            A                  1              812
    30         804          VAL            A                  1              814
    31         805          PHE            A                  1              815

       pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                      UNP                 P32418                    132
    1                      UNP                 P32418                    133
    2                      UNP                 P32418                    134
    3                      UNP                 P32418                    135
    4                      UNP                 P32418                    137
    5                      UNP                 P32418                    138
    6                      UNP                 P32418                    141
    7                      UNP                 P32418                    200
    8                      UNP                 P32418                    203
    9                      UNP                 P32418                    206
    10                     UNP                 P32418                    207
    11                     UNP                 P32418                    208
    12                     UNP                 P32418                    210
    13                     UNP                 P32418                    211
    14                     UNP                 P32418                    241
    15                     UNP                 P32418                    244
    16                     UNP                 P32418                    245
    17                     UNP                 P32418                    248
    18                     UNP                 P32418                    249
    19                     UNP                 P32418                    256
    20                     UNP                 P32418                    279
    21                     UNP                 P32418                    828
    22                     UNP                 P32418                    829
    23                     UNP                 P32418                    830
    24                     UNP                 P32418                    831
    25                     UNP                 P32418                    832
    26                     UNP                 P32418                    833
    27                     UNP                 P32418                    835
    28                     UNP                 P32418                    836
    29                     UNP                 P32418                    837
    30                     UNP                 P32418                    839
    31                     UNP                 P32418                    840

       pdbx_sifts_xref_db_res
    0                       E
    1                       T
    2                       V
    3                       S
    4                       L
    5                       T
    6                       A
    7                       H
    8                       V
    9                       V
    10                      T
    11                      A
    12                      W
    13                      S
    14                      F
    15                      I
    16                      C
    17                      F
    18                      A
    19                      L
    20                      E
    21                      T
    22                      I
    23                      G
    24                      L
    25                      K
    26                      D
    27                      V
    28                      T
    29                      A
    30                      V
    31                      F  }],
  'AF-A0A1D8PQM9-F1': [{'id': (0, 'A0A1D8PQM9', 'A'),
    'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            GLY             A               1          262                 ?
    1            PHE             A               1          263                 ?
    2            LEU             A               1          264                 ?
    3            HIS             A               1          265                 ?
    4            HIS             A               1          268                 ?
    5            GLY             A               1          493                 ?
    6            THR             A               1          494                 ?
    7            ILE             A               1          495                 ?
    8            MET             A               1          496                 ?
    9            SER             A               1          497                 ?
    10           LYS             A               1          498                 ?
    11           ILE             A               1          501                 ?
    12           TRP             A               1          513                 ?
    13           ARG             A               1          517                 ?
    14           LEU             A               1          518                 ?
    15           TYR             A               1          519                 ?
    16           THR             A               1          520                 ?
    17           GLN             A               1          699                 ?
    18           LEU             A               1          700                 ?
    19           PHE             A               1          701                 ?
    20           PRO             A               1          706                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num  \
    0          262          GLY            A                  1
    1          263          PHE            A                  1
    2          264          LEU            A                  1
    3          265          HIS            A                  1
    4          268          HIS            A                  1
    5          493          GLY            A                  1
    6          494          THR            A                  1
    7          495          ILE            A                  1
    8          496          MET            A                  1
    9          497          SER            A                  1
    10         498          LYS            A                  1
    11         501          ILE            A                  1
    12         513          TRP            A                  1
    13         517          ARG            A                  1
    14         518          LEU            A                  1
    15         519          TYR            A                  1
    16         520          THR            A                  1
    17         699          GLN            A                  1
    18         700          LEU            A                  1
    19         701          PHE            A                  1
    20         706          PRO            A                  1

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_name pdbx_sifts_xref_db_num  \
    0              A0A1D8PQM9                     UNP                    262
    1              A0A1D8PQM9                     UNP                    263
    2              A0A1D8PQM9                     UNP                    264
    3              A0A1D8PQM9                     UNP                    265
    4              A0A1D8PQM9                     UNP                    268
    5              A0A1D8PQM9                     UNP                    493
    6              A0A1D8PQM9                     UNP                    494
    7              A0A1D8PQM9                     UNP                    495
    8              A0A1D8PQM9                     UNP                    496
    9              A0A1D8PQM9                     UNP                    497
    10             A0A1D8PQM9                     UNP                    498
    11             A0A1D8PQM9                     UNP                    501
    12             A0A1D8PQM9                     UNP                    513
    13             A0A1D8PQM9                     UNP                    517
    14             A0A1D8PQM9                     UNP                    518
    15             A0A1D8PQM9                     UNP                    519
    16             A0A1D8PQM9                     UNP                    520
    17             A0A1D8PQM9                     UNP                    699
    18             A0A1D8PQM9                     UNP                    700
    19             A0A1D8PQM9                     UNP                    701
    20             A0A1D8PQM9                     UNP                    706

       pdbx_sifts_xref_db_res
    0                       G
    1                       F
    2                       L
    3                       H
    4                       H
    5                       G
    6                       T
    7                       I
    8                       M
    9                       S
    10                      K
    11                      I
    12                      W
    13                      R
    14                      L
    15                      Y
    16                      T
    17                      Q
    18                      L
    19                      F
    20                      P  }],
  '7l6r': [{'id': (0, 'P0DTD1', 'A'),
    'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            ILE             A               1           70                 ?
    1            PHE             A               1           72                 ?
    2            GLY             A               1           73                 ?
    3            VAL             A               1           98                 ?
    4            SER             A               1          100                 ?
    5            LEU             A               1          113                 ?
    6            GLY             A               1          115                 ?
    7            ASP             A               1          116                 ?
    8            CYS             A               1          117                 ?
    9            ALA             A               1          118                 ?
    10           VAL             A               1          120                 ?
    11           HIS             A               1          121                 ?
    12           THR             A               1          122                 ?
    13           ASN             A               1          124                 ?
    14           TRP             A               1          126                 ?
    15           SER             A               1          131                 ?
    16           MET             A               1          133                 ?
    17           PHE             A               1          151                 ?
    18           PHE             A               1          152                 ?
    19           TYR             A               1          154                 ?
    20           ILE             A               1          155                 ?
    21           PHE             A               1          158                 ?
    22           LYS             A               1          162                 ?
    23           VAL             A               1          291                 ?
    24           ILE             A               1          292                 ?
    25           SER             A               1          293                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         6866          ILE            A                  1               70
    1         6868          PHE            A                  1               72
    2         6869          GLY            A                  1               73
    3         6894          VAL            A                  1               98
    4         6896          SER            A                  1              100
    5         6909          LEU            A                  1              113
    6         6911          GLY            A                  1              115
    7         6912          ASP            A                  1              116
    8         6913          CYS            A                  1              117
    9         6914          ALA            A                  1              118
    10        6916          VAL            A                  1              120
    11        6917          HIS            A                  1              121
    12        6918          THR            A                  1              122
    13        6920          ASN            A                  1              124
    14        6922          TRP            A                  1              126
    15        6927          SER            A                  1              131
    16        6929          MET            A                  1              133
    17        6947          PHE            A                  1              151
    18        6948          PHE            A                  1              152
    19        6950          TYR            A                  1              154
    20        6951          ILE            A                  1              155
    21        6954          PHE            A                  1              158
    22        6958          LYS            A                  1              162
    23        7087          VAL            A                  1              291
    24        7088          ILE            A                  1              292
    25        7089          SER            A                  1              293

       pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                      UNP                 P0DTD1                   6866
    1                      UNP                 P0DTD1                   6868
    2                      UNP                 P0DTD1                   6869
    3                      UNP                 P0DTD1                   6894
    4                      UNP                 P0DTD1                   6896
    5                      UNP                 P0DTD1                   6909
    6                      UNP                 P0DTD1                   6911
    7                      UNP                 P0DTD1                   6912
    8                      UNP                 P0DTD1                   6913
    9                      UNP                 P0DTD1                   6914

news_sites = {
    pdb: {
        tuple(sorted(
            site["site"].auth_asym_id.unique().tolist()
        )): [site["site"],]
        for site in sites
    }
    for pdb, sites in news_sites.items()
}

news_sites

In [6]:
news_sites = {
    pdb: [
        site["site"]
        for site in sites
    ]
    for pdb, sites in news_sites.items()
}

news_sites

{'8sgj': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            GLU             A               1          132                 ?
  1            THR             A               1          133                 ?
  2            VAL             A               1          134                 ?
  3            SER             A               1          135                 ?
  4            LEU             A               1          137                 ?
  5            THR             A               1          138                 ?
  6            ALA             A               1          141                 ?
  7            HIS             A               1          200                 ?
  8            VAL             A               1          203                 ?
  9            VAL             A               1          206                 ?
  10           THR             A               1          207                 ?
  11           ALA             A               1          208                 ?
  12           TRP             A               1          210                 ?
  13           SER             A               1          211                 ?
  14           PHE             A               1          241                 ?
  15           ILE             A               1          244                 ?
  16           CYS             A               1          245                 ?
  17           PHE             A               1          248                 ?
  18           ALA             A               1          249                 ?
  19           LEU             A               1          256                 ?
  20           GLU             A               1          279                 ?
  21           THR             A               1          803                 ?
  22           ILE             A               1          804                 ?
  23           GLY             A               1          805                 ?
  24           LEU             A               1          806                 ?
  25           LYS             A               1          807                 ?
  26           ASP             A               1          808                 ?
  27           VAL             A               1          810                 ?
  28           THR             A               1          811                 ?
  29           ALA             A               1          812                 ?
  30           VAL             A               1          814                 ?
  31           PHE             A               1          815                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
  0           97          GLU            A                  1              132
  1           98          THR            A                  1              133
  2           99          VAL            A                  1              134
  3          100          SER            A                  1              135
  4          102          LEU            A                  1              137
  5          103          THR            A                  1              138
  6          106          ALA            A                  1              141
  7          165          HIS            A                  1              200
  8          168          VAL            A                  1              203
  9          171          VAL            A                  1              206
  10         172          THR            A                  1              207
  11         173          ALA            A                  1              208
  12         175          TRP            A                  1              210
  13         176          SER            A                  1              211
  14         206          PHE            A                  1              241
  15         209          ILE            A                  1              244
  16         210          CYS            A                  1              245
  17         213          PHE            A                  1              248
  18         214          ALA            A                  1              249
  19         221          LEU            A                  1              256
  20         244          GLU            A                  1              279
  21         793          THR            A                  1              803
  22         794          ILE            A                  1              804
  23         795          GLY            A                  1              805
  24         796          LEU            A                  1              806
  25         797          LYS            A                  1              807
  26         798          ASP            A                  1              808
  27         800          VAL            A                  1              810
  28         801          THR            A                  1              811
  29         802          ALA            A                  1              812
  30         804          VAL            A                  1              814
  31         805          PHE            A                  1              815

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
  0                      UNP                 P32418                    132
  1                      UNP                 P32418                    133
  2                      UNP                 P32418                    134
  3                      UNP                 P32418                    135
  4                      UNP                 P32418                    137
  5                      UNP                 P32418                    138
  6                      UNP                 P32418                    141
  7                      UNP                 P32418                    200
  8                      UNP                 P32418                    203
  9                      UNP                 P32418                    206
  10                     UNP                 P32418                    207
  11                     UNP                 P32418                    208
  12                     UNP                 P32418                    210
  13                     UNP                 P32418                    211
  14                     UNP                 P32418                    241
  15                     UNP                 P32418                    244
  16                     UNP                 P32418                    245
  17                     UNP                 P32418                    248
  18                     UNP                 P32418                    249
  19                     UNP                 P32418                    256
  20                     UNP                 P32418                    279
  21                     UNP                 P32418                    828
  22                     UNP                 P32418                    829
  23                     UNP                 P32418                    830
  24                     UNP                 P32418                    831
  25                     UNP                 P32418                    832
  26                     UNP                 P32418                    833
  27                     UNP                 P32418                    835
  28                     UNP                 P32418                    836
  29                     UNP                 P32418                    837
  30                     UNP                 P32418                    839
  31                     UNP                 P32418                    840

     pdbx_sifts_xref_db_res
  0                       E
  1                       T
  2                       V
  3                       S
  4                       L
  5                       T
  6                       A
  7                       H
  8                       V
  9                       V
  10                      T
  11                      A
  12                      W
  13                      S
  14                      F
  15                      I
  16                      C
  17                      F
  18                      A
  19                      L
  20                      E
  21                      T
  22                      I
  23                      G
  24                      L
  25                      K
  26                      D
  27                      V
  28                      T
  29                      A
  30                      V
  31                      F  ],
 'AF-A0A1D8PQM9-F1': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            GLY             A               1          262                 ?
  1            PHE             A               1          263                 ?
  2            LEU             A               1          264                 ?
  3            HIS             A               1          265                 ?
  4            HIS             A               1          268                 ?
  5            GLY             A               1          493                 ?
  6            THR             A               1          494                 ?
  7            ILE             A               1          495                 ?
  8            MET             A               1          496                 ?
  9            SER             A               1          497                 ?
  10           LYS             A               1          498                 ?
  11           ILE             A               1          501                 ?
  12           TRP             A               1          513                 ?
  13           ARG             A               1          517                 ?
  14           LEU             A               1          518                 ?
  15           TYR             A               1          519                 ?
  16           THR             A               1          520                 ?
  17           GLN             A               1          699                 ?
  18           LEU             A               1          700                 ?
  19           PHE             A               1          701                 ?
  20           PRO             A               1          706                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num  \
  0          262          GLY            A                  1
  1          263          PHE            A                  1
  2          264          LEU            A                  1
  3          265          HIS            A                  1
  4          268          HIS            A                  1
  5          493          GLY            A                  1
  6          494          THR            A                  1
  7          495          ILE            A                  1
  8          496          MET            A                  1
  9          497          SER            A                  1
  10         498          LYS            A                  1
  11         501          ILE            A                  1
  12         513          TRP            A                  1
  13         517          ARG            A                  1
  14         518          LEU            A                  1
  15         519          TYR            A                  1
  16         520          THR            A                  1
  17         699          GLN            A                  1
  18         700          LEU            A                  1
  19         701          PHE            A                  1
  20         706          PRO            A                  1

     pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_name pdbx_sifts_xref_db_num  \
  0              A0A1D8PQM9                     UNP                    262
  1              A0A1D8PQM9                     UNP                    263
  2              A0A1D8PQM9                     UNP                    264
  3              A0A1D8PQM9                     UNP                    265
  4              A0A1D8PQM9                     UNP                    268
  5              A0A1D8PQM9                     UNP                    493
  6              A0A1D8PQM9                     UNP                    494
  7              A0A1D8PQM9                     UNP                    495
  8              A0A1D8PQM9                     UNP                    496
  9              A0A1D8PQM9                     UNP                    497
  10             A0A1D8PQM9                     UNP                    498
  11             A0A1D8PQM9                     UNP                    501
  12             A0A1D8PQM9                     UNP                    513
  13             A0A1D8PQM9                     UNP                    517
  14             A0A1D8PQM9                     UNP                    518
  15             A0A1D8PQM9                     UNP                    519
  16             A0A1D8PQM9                     UNP                    520
  17             A0A1D8PQM9                     UNP                    699
  18             A0A1D8PQM9                     UNP                    700
  19             A0A1D8PQM9                     UNP                    701
  20             A0A1D8PQM9                     UNP                    706

     pdbx_sifts_xref_db_res
  0                       G
  1                       F
  2                       L
  3                       H
  4                       H
  5                       G
  6                       T
  7                       I
  8                       M
  9                       S
  10                      K
  11                      I
  12                      W
  13                      R
  14                      L
  15                      Y
  16                      T
  17                      Q
  18                      L
  19                      F
  20                      P  ],
 '7l6r': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            ILE             A               1           70                 ?
  1            PHE             A               1           72                 ?
  2            GLY             A               1           73                 ?
  3            VAL             A               1           98                 ?
  4            SER             A               1          100                 ?
  5            LEU             A               1          113                 ?
  6            GLY             A               1          115                 ?
  7            ASP             A               1          116                 ?
  8            CYS             A               1          117                 ?
  9            ALA             A               1          118                 ?
  10           VAL             A               1          120                 ?
  11           HIS             A               1          121                 ?
  12           THR             A               1          122                 ?
  13           ASN             A               1          124                 ?
  14           TRP             A               1          126                 ?
  15           SER             A               1          131                 ?
  16           MET             A               1          133                 ?
  17           PHE             A               1          151                 ?
  18           PHE             A               1          152                 ?
  19           TYR             A               1          154                 ?
  20           ILE             A               1          155                 ?
  21           PHE             A               1          158                 ?
  22           LYS             A               1          162                 ?
  23           VAL             A               1          291                 ?
  24           ILE             A               1          292                 ?
  25           SER             A               1          293                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
  0         6866          ILE            A                  1               70
  1         6868          PHE            A                  1               72
  2         6869          GLY            A                  1               73
  3         6894          VAL            A                  1               98
  4         6896          SER            A                  1              100
  5         6909          LEU            A                  1              113
  6         6911          GLY            A                  1              115
  7         6912          ASP            A                  1              116
  8         6913          CYS            A                  1              117
  9         6914          ALA            A                  1              118
  10        6916          VAL            A                  1              120
  11        6917          HIS            A                  1              121
  12        6918          THR            A                  1              122
  13        6920          ASN            A                  1              124
  14        6922          TRP            A                  1              126
  15        6927          SER            A                  1              131
  16        6929          MET            A                  1              133
  17        6947          PHE            A                  1              151
  18        6948          PHE            A                  1              152
  19        6950          TYR            A                  1              154
  20        6951          ILE            A                  1              155
  21        6954          PHE            A                  1              158
  22        6958          LYS            A                  1              162
  23        7087          VAL            A                  1              291
  24        7088          ILE            A                  1              292
  25        7089          SER            A                  1              293

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
  0                      UNP                 P0DTD1                   6866
  1                      UNP                 P0DTD1                   6868
  2                      UNP                 P0DTD1                   6869
  3                      UNP                 P0DTD1                   6894
  4                      UNP                 P0DTD1                   6896
  5                      UNP                 P0DTD1                   6909
  6                      UNP                 P0DTD1                   6911
  7                      UNP                 P0DTD1                   6912
  8                      UNP                 P0DTD1                   6913
  9                      UNP                 P0DTD1                   6914
  10                     UNP                 P0DTD1                   6916
  11                     UNP                 P0DTD1                   6917
  12                     UNP                 P0DTD1                   6918
  13                     UNP                 P0DTD1                   6920
  14                     UNP                 P0DTD1                   6922
  15                     UNP                 P0DTD1                   6927
  16                     UNP                 P0DTD1                   6929
  17                     UNP                 P0DTD1                   6947
  18                     UNP                 P0DTD1                   6948
  19                     UNP                 P0DTD1                   6950

In [7]:
news_sites["7sns"]

[   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
 0            GLU             A               1            9                 ?
 1            ASP             A               1           10                 ?
 2            PHE             A               1           11                 ?
 3            VAL             A               1           12                 ?
 4            GLY             A               1           13                 ?
 5            ASP             A               1           14                 ?
 6            TRP             A               1           15                 ?
 7            ILE             A               1           49                 ?
 8            LEU             A               1           51                 ?
 9            ARG             A               1          171                 ?
 10           ILE             A               1          172                 ?
 11           LEU             A               1          173                 ?
 12           ALA             A               1          174                 ?

    auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
 0            4          GLU            A                  1                9
 1            5          ASP            A                  1               10
 2            6          PHE            A                  1               11
 3            7          VAL            A                  1               12
 4            8          GLY            A                  1               13
 5            9          ASP            A                  1               14
 6           10          TRP            A                  1               15
 7           44          ILE            A                  1               49
 8           46          LEU            A                  1               51
 9          166          ARG            A                  1              171
 10         167          ILE            A                  1              172
 11         168          LEU            A                  1              173
 12         169          ALA            A                  1              174

    pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
 0                      UNP                 Q9GV45                     31
 1                      UNP                 Q9GV45                     32
 2                      UNP                 Q9GV45                     33
 3                      UNP                 Q9GV45                     34
 4                      UNP                 Q9GV45                     35
 5                      UNP                 Q9GV45                     36
 6                      UNP                 Q9GV45                     37
 7                      UNP                 Q9GV45                     71
 8                      UNP                 Q9GV45                     73
 9                      UNP                 Q9GV45                    193
 10                     UNP                 Q9GV45                    194
 11                     UNP                 Q9GV45                    195
 12                     UNP                 Q9GV45                    196

    pdbx_sifts_xref_db_res
 0                       A
 1                       D
 2                       F
 3                       V
 4                       G
 5                       D
 6                       W
 7                       V
 8                       L
 9                       N
 10                      I
 11                      L
 12                      A  ,
    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
 13           ASP             B               1           14                 ?
 14           TRP             B               1           15                 ?
 15           ARG             B               1           16                 ?
 16           ILE             B               1           46                 ?
 17           ARG             B               1           48                 ?
 18           ASP             B               1           60                 ?
 19           HIS             B               1           62                 ?
 20           ILE             B               1           64                 ?
 21           TYR             B               1           86                 ?
 22           PRO             B               1           87                 ?
 23           VAL             B               1           88                 ?
 24           PHE             B               1           93                 ?
 25           LYS             B               1           94                 ?
 26           ILE             B               1           96                 ?
 27           TYR             B               1           99                 ?
 28           ILE             B               1          172                 ?

    auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
 13           9          ASP            B                  1               14
 14          10          TRP            B                  1               15
 15          11          ARG            B                  1               16
 16          41          ILE            B                  1               46
 17          43          ARG            B                  1               48
 18          55          ASP            B                  1               60
 19          57          HIS            B                  1               62
 20          59          ILE            B                  1               64
 21          81          TYR            B                  1               86
 22          82          PRO            B                  1               87
 23          83          VAL            B                  1               88
 24          88          PHE            B                  1               93
 25          89          LYS            B                  1               94
 26          91          ILE            B                  1               96
 27          94          TYR            B                  1               99
 28         167          ILE            B                  1              172

    pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
 13                     UNP                 Q9GV45                     36
 14                     UNP                 Q9GV45                     37
 15                     UNP                 Q9GV45                     38
 16                     UNP                 Q9GV45                     68
 17                     UNP                 Q9GV45                     70
 18                     UNP                 Q9GV45                     82
 19                     UNP                 Q9GV45                     84
 20                     UNP                 Q9GV45                     86
 21                     UNP                 Q9GV45                    108
 22                     UNP                 Q9GV45                    109
 23                     UNP                 Q9GV45                    110
 24                     UNP                 Q9GV45                    115
 25                     UNP                 Q9GV45                    116
 26                     UNP                 Q9GV45                    118
 27                     UNP                 Q9GV45                    121
 28                     UNP                 Q9GV45                    194

    pdbx_sifts_xref_db_res
 13                      D
 14                      W
 15                      Q
 16                      I
 17                      K
 18                      D
 19                      H
 20                      I
 21                      Y
 22                      P
 23                      V
 24                      F
 25                      K
 26                      I
 27                      Y
 28                      I  ]

In [8]:
comb_site = pd.concat(news_sites["7sns"])
comb_site

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,GLU,A,1,9,?,4,GLU,A,1,9,UNP,Q9GV45,31,A
1,ASP,A,1,10,?,5,ASP,A,1,10,UNP,Q9GV45,32,D
2,PHE,A,1,11,?,6,PHE,A,1,11,UNP,Q9GV45,33,F
3,VAL,A,1,12,?,7,VAL,A,1,12,UNP,Q9GV45,34,V
4,GLY,A,1,13,?,8,GLY,A,1,13,UNP,Q9GV45,35,G
5,ASP,A,1,14,?,9,ASP,A,1,14,UNP,Q9GV45,36,D
6,TRP,A,1,15,?,10,TRP,A,1,15,UNP,Q9GV45,37,W
7,ILE,A,1,49,?,44,ILE,A,1,49,UNP,Q9GV45,71,V
8,LEU,A,1,51,?,46,LEU,A,1,51,UNP,Q9GV45,73,L
9,ARG,A,1,171,?,166,ARG,A,1,171,UNP,Q9GV45,193,N
10,ILE,A,1,172,?,167,ILE,A,1,172,UNP,Q9GV45,194,I
11,LEU,A,1,173,?,168,LEU,A,1,173,UNP,Q9GV45,195,L
12,ALA,A,1,174,?,169,ALA,A,1,174,UNP,Q9GV45,196,A
13,ASP,B,1,14,?,9,ASP,B,1,14,UNP,Q9GV45,36,D
14,TRP,B,1,15,?,10,TRP,B,1,15,UNP,Q9GV45,37,W
15,ARG,B,1,16,?,11,ARG,B,1,16,UNP,Q9GV45,38,Q
16,ILE,B,1,46,?,41,ILE,B,1,46,UNP,Q9GV45,68,I
17,ARG,B,1,48,?,43,ARG,B,1,48,UNP,Q9GV45,70,K
18,ASP,B,1,60,?,55,ASP,B,1,60,UNP,Q9GV45,82,D
19,HIS,B,1,62,?,57,HIS,B,1,62,UNP,Q9GV45,84,H
20,ILE,B,1,64,?,59,ILE,B,1,64,UNP,Q9GV45,86,I
21,TYR,B,1,86,?,81,TYR,B,1,86,UNP,Q9GV45,108,Y
22,PRO,B,1,87,?,82,PRO,B,1,87,UNP,Q9GV45,109,P
23,VAL,B,1,88,?,83,VAL,B,1,88,UNP,Q9GV45,110,V
24,PHE,B,1,93,?,88,PHE,B,1,93,UNP,Q9GV45,115,F
25,LYS,B,1,94,?,89,LYS,B,1,94,UNP,Q9GV45,116,K
26,ILE,B,1,96,?,91,ILE,B,1,96,UNP,Q9GV45,118,I
27,TYR,B,1,99,?,94,TYR,B,1,99,UNP,Q9GV45,121,Y
28,ILE,B,1,172,?,167,ILE,B,1,172,UNP,Q9GV45,194,I

In [9]:
news_sites["7sns"] = [
    comb_site,
    comb_site.replace({"label_asym_id": {"A": "B", "B": "A"}, "auth_asym_id": {"A": "B", "B": "A"}})
]

In [10]:
len(news_sites), news_sites

(9,
 {'8sgj': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            GLU             A               1          132                 ?
   1            THR             A               1          133                 ?
   2            VAL             A               1          134                 ?
   3            SER             A               1          135                 ?
   4            LEU             A               1          137                 ?
   5            THR             A               1          138                 ?
   6            ALA             A               1          141                 ?
   7            HIS             A               1          200                 ?
   8            VAL             A               1          203                 ?
   9            VAL             A               1          206                 ?
   10           THR             A               1          207                 ?
   11           ALA             A               1          208                 ?
   12           TRP             A               1          210                 ?
   13           SER             A               1          211                 ?
   14           PHE             A               1          241                 ?
   15           ILE             A               1          244                 ?
   16           CYS             A               1          245                 ?
   17           PHE             A               1          248                 ?
   18           ALA             A               1          249                 ?
   19           LEU             A               1          256                 ?
   20           GLU             A               1          279                 ?
   21           THR             A               1          803                 ?
   22           ILE             A               1          804                 ?
   23           GLY             A               1          805                 ?
   24           LEU             A               1          806                 ?
   25           LYS             A               1          807                 ?
   26           ASP             A               1          808                 ?
   27           VAL             A               1          810                 ?
   28           THR             A               1          811                 ?
   29           ALA             A               1          812                 ?
   30           VAL             A               1          814                 ?
   31           PHE             A               1          815                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0           97          GLU            A                  1              132
   1           98          THR            A                  1              133
   2           99          VAL            A                  1              134
   3          100          SER            A                  1              135
   4          102          LEU            A                  1              137
   5          103          THR            A                  1              138
   6          106          ALA            A                  1              141
   7          165          HIS            A                  1              200
   8          168          VAL            A                  1              203
   9          171          VAL            A                  1              206
   10         172          THR            A                  1              207
   11         173          ALA            A                  1              208
   12         175          TRP            A                  1              210
   13         176          SER            A                  1              211
   14         206          PHE            A                  1              241
   15         209          ILE            A                  1              244
   16         210          CYS            A                  1              245
   17         213          PHE            A                  1              248
   18         214          ALA            A                  1              249
   19         221          LEU            A                  1              256
   20         244          GLU            A                  1              279
   21         793          THR            A                  1              803
   22         794          ILE            A                  1              804
   23         795          GLY            A                  1              805
   24         796          LEU            A                  1              806
   25         797          LYS            A                  1              807
   26         798          ASP            A                  1              808
   27         800          VAL            A                  1              810
   28         801          THR            A                  1              811
   29         802          ALA            A                  1              812
   30         804          VAL            A                  1              814
   31         805          PHE            A                  1              815

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 P32418                    132
   1                      UNP                 P32418                    133
   2                      UNP                 P32418                    134
   3                      UNP                 P32418                    135
   4                      UNP                 P32418                    137
   5                      UNP                 P32418                    138
   6                      UNP                 P32418                    141
   7                      UNP                 P32418                    200
   8                      UNP                 P32418                    203
   9                      UNP                 P32418                    206
   10                     UNP                 P32418                    207
   11                     UNP                 P32418                    208
   12                     UNP                 P32418                    210
   13                     UNP                 P32418                    211
   14                     UNP                 P32418                    241
   15                     UNP                 P32418                    244
   16                     UNP                 P32418                    245
   17                     UNP                 P32418                    248
   18                     UNP                 P32418                    249
   19                     UNP                 P32418                    256
   20                     UNP                 P32418                    279
   21                     UNP                 P32418                    828
   22                     UNP                 P32418                    829
   23                     UNP                 P32418                    830
   24                     UNP                 P32418                    831
   25                     UNP                 P32418                    832
   26                     UNP                 P32418                    833
   27                     UNP                 P32418                    835
   28                     UNP                 P32418                    836
   29                     UNP                 P32418                    837
   30                     UNP                 P32418                    839
   31                     UNP                 P32418                    840

      pdbx_sifts_xref_db_res
   0                       E
   1                       T
   2                       V
   3                       S
   4                       L
   5                       T
   6                       A
   7                       H
   8                       V
   9                       V
   10                      T
   11                      A
   12                      W
   13                      S
   14                      F
   15                      I
   16                      C
   17                      F
   18                      A
   19                      L
   20                      E
   21                      T
   22                      I
   23                      G
   24                      L
   25                      K
   26                      D
   27                      V
   28                      T
   29                      A
   30                      V
   31                      F  ],
  'AF-A0A1D8PQM9-F1': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            GLY             A               1          262                 ?
   1            PHE             A               1          263                 ?
   2            LEU             A               1          264                 ?
   3            HIS             A               1          265                 ?
   4            HIS             A               1          268                 ?
   5            GLY             A               1          493                 ?
   6            THR             A               1          494                 ?
   7            ILE             A               1          495                 ?
   8            MET             A               1          496                 ?
   9            SER             A               1          497                 ?
   10           LYS             A               1          498                 ?
   11           ILE             A               1          501                 ?
   12           TRP             A               1          513                 ?
   13           ARG             A               1          517                 ?
   14           LEU             A               1          518                 ?
   15           TYR             A               1          519                 ?
   16           THR             A               1          520                 ?
   17           GLN             A               1          699                 ?
   18           LEU             A               1          700                 ?
   19           PHE             A               1          701                 ?
   20           PRO             A               1          706                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num  \
   0          262          GLY            A                  1
   1          263          PHE            A                  1
   2          264          LEU            A                  1
   3          265          HIS            A                  1
   4          268          HIS            A                  1
   5          493          GLY            A                  1
   6          494          THR            A                  1
   7          495          ILE            A                  1
   8          496          MET            A                  1
   9          497          SER            A                  1
   10         498          LYS            A                  1
   11         501          ILE            A                  1
   12         513          TRP            A                  1
   13         517          ARG            A                  1
   14         518          LEU            A                  1
   15         519          TYR            A                  1
   16         520          THR            A                  1
   17         699          GLN            A                  1
   18         700          LEU            A                  1
   19         701          PHE            A                  1
   20         706          PRO            A                  1

      pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_name pdbx_sifts_xref_db_num  \
   0              A0A1D8PQM9                     UNP                    262
   1              A0A1D8PQM9                     UNP                    263
   2              A0A1D8PQM9                     UNP                    264
   3              A0A1D8PQM9                     UNP                    265
   4              A0A1D8PQM9                     UNP                    268
   5              A0A1D8PQM9                     UNP                    493
   6              A0A1D8PQM9                     UNP                    494
   7              A0A1D8PQM9                     UNP                    495
   8              A0A1D8PQM9                     UNP                    496
   9              A0A1D8PQM9                     UNP                    497
   10             A0A1D8PQM9                     UNP                    498
   11             A0A1D8PQM9                     UNP                    501
   12             A0A1D8PQM9                     UNP                    513
   13             A0A1D8PQM9                     UNP                    517
   14             A0A1D8PQM9                     UNP                    518
   15             A0A1D8PQM9                     UNP                    519
   16             A0A1D8PQM9                     UNP                    520
   17             A0A1D8PQM9                     UNP                    699
   18             A0A1D8PQM9                     UNP                    700
   19             A0A1D8PQM9                     UNP                    701
   20             A0A1D8PQM9                     UNP                    706

      pdbx_sifts_xref_db_res
   0                       G
   1                       F
   2                       L
   3                       H
   4                       H
   5                       G
   6                       T
   7                       I
   8                       M
   9                       S
   10                      K
   11                      I
   12                      W
   13                      R
   14                      L
   15                      Y
   16                      T
   17                      Q
   18                      L
   19                      F
   20                      P  ],
  '7l6r': [   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ILE             A               1           70                 ?
   1            PHE             A               1           72                 ?
   2            GLY             A               1           73                 ?
   3            VAL             A               1           98                 ?
   4            SER             A               1          100                 ?
   5            LEU             A               1          113                 ?
   6            GLY             A               1          115                 ?
   7            ASP             A               1          116                 ?
   8            CYS             A               1          117                 ?
   9            ALA             A               1          118                 ?
   10           VAL             A               1          120                 ?
   11           HIS             A               1          121                 ?
   12           THR             A               1          122                 ?
   13           ASN             A               1          124                 ?
   14           TRP             A               1          126                 ?
   15           SER             A               1          131                 ?
   16           MET             A               1          133                 ?
   17           PHE             A               1          151                 ?
   18           PHE             A               1          152                 ?
   19           TYR             A               1          154                 ?
   20           ILE             A               1          155                 ?
   21           PHE             A               1          158                 ?
   22           LYS             A               1          162                 ?
   23           VAL             A               1          291                 ?
   24           ILE             A               1          292                 ?
   25           SER             A               1          293                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0         6866          ILE            A                  1               70
   1         6868          PHE            A                  1               72
   2         6869          GLY            A                  1               73
   3         6894          VAL            A                  1               98
   4         6896          SER            A                  1              100
   5         6909          LEU            A                  1              113
   6         6911          GLY            A                  1              115
   7         6912          ASP            A                  1              116
   8         6913          CYS            A                  1              117
   9         6914          ALA            A                  1              118
   10        6916          VAL            A                  1              120
   11        6917          HIS            A                  1              121
   12        6918          THR            A                  1              122
   13        6920          ASN            A                  1              124
   14        6922          TRP            A                  1              126
   15        6927          SER            A                  1              131
   16        6929          MET            A                  1              133
   17        6947          PHE            A                  1              151
   18        6948          PHE            A                  1              152
   19        6950          TYR            A                  1              154
   20        6951          ILE            A                  1              155
   21        6954          PHE            A                  1              158
   22        6958          LYS            A                  1              162
   23        7087          VAL            A                  1              291
   24        7088          ILE            A                  1              292
   25        7089          SER            A                  1              293

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 P0DTD1                   6866
   1                      UNP                 P0DTD1                   6868
   2                      UNP                 P0DTD1                   6869
   3                      UNP                 P0DTD1                   6894
   4                      UNP                 P0DTD1                   6896
   5                      UNP                 P0DTD1                   6909
   6                      UNP                 P0DTD1                   6911
   7                      UNP                 P0DTD1                   6912
   8                      UNP                 P0DTD1                   6913
   9                      UNP                 P0DTD1                   6914
   10                     UNP                 P0DTD1                   6916
   11                     UNP                 P0DTD1                   6917
   12                     UNP                 P0DTD1                   6918
   13                     UNP                 P0DTD1                   6920
   14                     UNP                 P0DTD1                   6922
   15                     UNP                 P0DTD1                   6927

In [11]:
news_sites["7sns"]

[   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
 0            GLU             A               1            9                 ?
 1            ASP             A               1           10                 ?
 2            PHE             A               1           11                 ?
 3            VAL             A               1           12                 ?
 4            GLY             A               1           13                 ?
 5            ASP             A               1           14                 ?
 6            TRP             A               1           15                 ?
 7            ILE             A               1           49                 ?
 8            LEU             A               1           51                 ?
 9            ARG             A               1          171                 ?
 10           ILE             A               1          172                 ?
 11           LEU             A               1          173                 ?
 12           ALA             A               1          174                 ?
 13           ASP             B               1           14                 ?
 14           TRP             B               1           15                 ?
 15           ARG             B               1           16                 ?
 16           ILE             B               1           46                 ?
 17           ARG             B               1           48                 ?
 18           ASP             B               1           60                 ?
 19           HIS             B               1           62                 ?
 20           ILE             B               1           64                 ?
 21           TYR             B               1           86                 ?
 22           PRO             B               1           87                 ?
 23           VAL             B               1           88                 ?
 24           PHE             B               1           93                 ?
 25           LYS             B               1           94                 ?
 26           ILE             B               1           96                 ?
 27           TYR             B               1           99                 ?
 28           ILE             B               1          172                 ?

    auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
 0            4          GLU            A                  1                9
 1            5          ASP            A                  1               10
 2            6          PHE            A                  1               11
 3            7          VAL            A                  1               12
 4            8          GLY            A                  1               13
 5            9          ASP            A                  1               14
 6           10          TRP            A                  1               15
 7           44          ILE            A                  1               49
 8           46          LEU            A                  1               51
 9          166          ARG            A                  1              171
 10         167          ILE            A                  1              172
 11         168          LEU            A                  1              173
 12         169          ALA            A                  1              174
 13           9          ASP            B                  1               14
 14          10          TRP            B                  1               15
 15          11          ARG            B                  1               16
 16          41          ILE            B                  1               46
 17          43          ARG            B                  1               48
 18          55          ASP            B                  1               60
 19          57          HIS            B                  1               62
 20          59          ILE            B                  1               64
 21          81          TYR            B                  1               86
 22          82          PRO            B                  1               87
 23          83          VAL            B                  1               88
 24          88          PHE            B                  1               93
 25          89          LYS            B                  1               94
 26          91          ILE            B                  1               96
 27          94          TYR            B                  1               99
 28         167          ILE            B                  1              172

    pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
 0                      UNP                 Q9GV45                     31
 1                      UNP                 Q9GV45                     32
 2                      UNP                 Q9GV45                     33
 3                      UNP                 Q9GV45                     34
 4                      UNP                 Q9GV45                     35
 5                      UNP                 Q9GV45                     36
 6                      UNP                 Q9GV45                     37
 7                      UNP                 Q9GV45                     71
 8                      UNP                 Q9GV45                     73
 9                      UNP                 Q9GV45                    193
 10                     UNP                 Q9GV45                    194
 11                     UNP                 Q9GV45                    195
 12                     UNP                 Q9GV45                    196
 13                     UNP                 Q9GV45                     36
 14                     UNP                 Q9GV45                     37
 15                     UNP                 Q9GV45                     38
 16                     UNP                 Q9GV45                     68
 17                     UNP                 Q9GV45                     70
 18                     UNP                 Q9GV45                     82
 19                     UNP                 Q9GV45                     84
 20                     UNP                 Q9GV45                     86
 21                     UNP                 Q9GV45                    108
 22                     UNP                 Q9GV45                    109
 23                     UNP                 Q9GV45                    110
 24                     UNP                 Q9GV45                    115
 25                     UNP                 Q9GV45                    116
 26                     UNP                 Q9GV45                    118
 27                     UNP                 Q9GV45                    121
 28                     UNP                 Q9GV45                    194

    pdbx_sifts_xref_db_res
 0                       A
 1                       D
 2                       F
 3                       V
 4                       G
 5                       D
 6                       W
 7                       V
 8                       L
 9                       N
 10                      I
 11                      L
 12                      A
 13                      D
 14                      W
 15                      Q
 16                      I
 17                      K
 18                      D
 19                      H
 20                      I
 21                      Y
 22                      P
 23                      V
 24                      F
 25                      K
 26                      I
 27                      Y
 28                      I  ,
    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
 0            GLU             B               1            9                 ?
 1            ASP             B               1           10                 ?
 2            PHE             B               1           11                 ?
 3            VAL             B               1           12                 ?
 4            GLY             B               1           13                 ?
 5            ASP             B               1           14                 ?
 6            TRP             B               1           15                 ?
 7            ILE             B               1           49                 ?
 8            LEU             B               1           51                 ?
 9            ARG             B               1          171                 ?
 10           ILE             B               1          172                 ?
 11           LEU             B               1          173                 ?
 12           ALA             B               1          174                 ?
 13           ASP             A               1           14                 ?
 14           TRP             A               1           15                 ?
 15           ARG             A               1           16                 ?
 16           ILE             A               1           46                 ?
 17           ARG             A               1           48                 ?
 18           ASP             A               1           60                 ?
 19           HIS             A               1           62                 ?
 20           ILE             A               1           64                 ?
 21           TYR             A               1           86                 ?
 22           PRO             A               1           87                 ?
 23           VAL             A               1           88                 ?
 24           PHE             A               1           93                 ?
 25           LYS             A               1           94                 ?
 26           ILE             A               1           96                 ?
 27           TYR             A               1           99                 ?
 28           ILE             A               1          172                 ?

    auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
 0            4          GLU            B                  1                9
 1            5          ASP            B                  1               10
 2            6          PHE            B                  1               11
 3            7          VAL            B                  1               12
 4            8          GLY            B                  1               13
 5            9          ASP            B                  1               14
 6           10          TRP            B                  1               15
 7           44          ILE            B                  1               49
 8           46          LEU            B                  1               51
 9          166          ARG            B                  1              171
 10         167          ILE            B                  1              172
 11         168          LEU            B                  1              173
 12         169          ALA            B                  1              174
 13           9          ASP            A                  1               14
 14          10          TRP            A                  1               15
 15          11          ARG            A                  1               16
 16          41          ILE            A                  1               46
 17          43          ARG            A                  1               48
 18          55          ASP            A                  1               60
 19          57          HIS            A                  1               62
 20          59          ILE            A                  1               64
 21          81          TYR            A                  1               86
 22          82          PRO            A                  1               87
 23          83          VAL            A                  1               88
 24          88          PHE            A                  1               93
 25          89          LYS            A                  1               94
 26          91          ILE            A                  1               96
 27          94          TYR            A                  1               99
 28         167          ILE            A                  1              172

    pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
 0                      UNP                 Q9GV45                     31
 1                      UNP                 Q9GV45                     32
 2                      UNP                 Q9GV45                     33
 3                      UNP                 Q9GV45                     34
 4                      UNP                 Q9GV45                     35
 5                      UNP                 Q9GV45                     36
 6                      UNP                 Q9GV45                     37
 7                      UNP                 Q9GV45                     71
 8                      UNP                 Q9GV45                     73
 9                      UNP                 Q9GV45                    193
 10                     UNP                 Q9GV45                    194
 11                     UNP                 Q9GV45                    195
 12                     UNP                 Q9GV45                    196
 13                     UNP                 Q9GV45                     36
 14                     UNP                 Q9GV45                     37
 15                     UNP                 Q9GV45                     38
 16                     UNP                 Q9GV45                     68
 17                     UNP                 Q9GV45                     70
 18                     UNP                 Q9GV45                     82
 19                     UNP                 Q9GV45                     84
 20                     UNP                 Q9GV45                     86
 21                     UNP                 Q9GV45                    108
 22                     UNP                 Q9GV45                    109
 23                     UNP                 Q9GV45                    110
 24                     UNP                 Q9GV45                    115
 25                     UNP                 Q9GV45                    116
 26                     UNP                 Q9GV45                    118
 27                     UNP                 Q9GV45                    121
 28                     UNP                 Q9GV45                    194

    pdbx_sifts_xref_db_res
 0                       A
 1                       D
 2                       F
 3                       V
 4                       G
 5                       D
 6                       W
 7                       V
 8                       L
 9                       N
 10                      I
 11                      L
 12                      A
 13                      D
 14                      W
 15                      Q
 16                      I
 17                      K
 18                      D
 19                      H
 20                      I
 21                      Y
 22                      P
 23                      V
 24                      F
 25                      K
 26                      I
 27                      Y
 28                      I  ]

In [12]:
# assert all(len(sites) == 1 for sites in news_sites.values()), "Not all apos have a single annotated site"

# Process structures

In [13]:
os.makedirs("structures", exist_ok=True)

In [14]:
import pymol2

In [15]:
for pdb in news:
    ciff = f"../../training_data/8.Apos/Extra_set/cifs/{pdb}.cif"
    if not os.path.isfile(f"structures/{pdb}.cif"):
        os.system(f"cp {ciff} structures/{pdb}.cif")

    if not os.path.isfile(f"structures/{pdb}.pdb"):
        with pymol2.PyMOL() as pymol:
            pymol.cmd.feedback("disable", "executive", "details")
            pymol.cmd.load(ciff, "structure")
            pymol.cmd.save(f"structures/{pdb}.pdb", "structure")

In [16]:
# !zip structures_apos.zip structures/*

# Our results

In [17]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [18]:
def process_dataframe(df):
    df.index = df["Pockets"][["pdb", "pocket"]].apply(lambda x: "_".join(x), axis=1)
    df = df.drop(columns=["Pockets"], level=0)
    df.columns = map(lambda x: "_".join(x), df.columns.values)
    df.loc[:,'Label_label'] = df['Label_label'].astype("category")
    return df

## Model 5.

In [19]:
with open("../../training_data/8.Apos/Extra_set/pockets_features.pkl", "rb") as f:
    extra = pd.concat((
        pickle.load(f).values()
    ))

extra

    Pockets                                              Label      FPocket  \
        pdb    pocket nres site_in_pocket pocket_in_site label Pocket Score
0      8sgj  pocket16   12        0.00000       0.000000     0      -0.0342
1      8sgj  pocket28   14        0.00000       0.000000     0      -0.1447
2      8sgj  pocket18   13        0.03125       0.076923     0      -0.0508
3      8sgj  pocket11   19        0.00000       0.000000     0       0.0417
4      8sgj  pocket25   13        0.00000       0.000000     0      -0.1152
..      ...       ...  ...            ...            ...   ...          ...
277    4jqi   pocket8   14        0.20000       0.142857     0       0.0042
278    4jqi   pocket3   16        0.00000       0.000000     0       0.2233
279    4jqi  pocket12   12        0.00000       0.000000     0      -0.0437
280    4jqi  pocket19   16        0.00000       0.000000     0      -0.1457
281    4jqi   pocket6   18        0.00000       0.000000     0       0.0327

                                                                 ...  \
    Drug Score Number of alpha spheres Mean alpha-sphere radius  ...
0       0.3070                    53.0                   3.4745  ...
1       0.0047                    71.0                   3.4962  ...
2       0.0055                    45.0                   3.7490  ...
3       0.1571                    82.0                   3.2878  ...
4       0.0046                    58.0                   3.5925  ...
..         ...                     ...                      ...  ...
277     0.0047                    42.0                   3.5379  ...
278     0.0927                    55.0                   3.4106  ...
279     0.0029                    54.0                   3.6728  ...
280     0.0054                    80.0                   3.7185  ...
281     0.0099                    72.0                   3.7133  ...

      HHBlits                                                              \
         M->M      M->I      M->D      I->M      I->I      D->M      D->D
0    0.960393  0.013573  0.026106  0.258887  0.491092  0.049368  0.950513
1    0.881871  0.030298  0.087796  0.383562  0.616425  0.018516  0.981423
2    0.899622  0.030244  0.070014  0.401700  0.598274  0.106505  0.893517
3    0.876903  0.036800  0.086349  0.289485  0.710526  0.047774  0.952233
4    0.936656  0.023770  0.039556  0.351106  0.572006  0.165316  0.834701
..        ...       ...       ...       ...       ...       ...       ...
277  0.903910  0.020998  0.075087  0.359765  0.640269  0.103486  0.896543
278  0.964962  0.009062  0.025914  0.298281  0.639198  0.224343  0.775659
279  0.957657  0.028217  0.014108  0.418731  0.497841  0.307800  0.692181
280  0.944717  0.018328  0.037005  0.286179  0.588822  0.091041  0.908843
281  0.818487  0.053249  0.128251  0.364035  0.635970  0.302670  0.697328


          Neff    Neff_I    Neff_D
0     7.402167  0.777083  4.546750
1     8.198214  1.068071  4.327357
2     8.226231  1.096231  3.046538
3    10.482684  1.128737  3.646263
4     8.005692  1.033462  2.943231
..         ...       ...       ...
277  11.652929  1.203571  6.393357
278  11.691562  1.083687  2.318750
279  11.358750  1.477750  1.626333
280  11.506875  1.060500  3.739063
281  11.367500  1.758778  4.348611

[282 rows x 194 columns]

In [20]:
extra[("Pockets", "pdb")].unique()

array(['8sgj', 'AF-A0A1D8PQM9-F1', '7l6r', '8vw5', '6yhr', '7xlq', '7sns',
       '5uak', '4jqi'], dtype=object)

In [21]:
predictor = TabularPredictor.load("../pockets_physchem_deploy")

In [22]:
extra_probs = predictor.predict_proba( process_dataframe(extra) )
extra_probs

                      0             1
8sgj_pocket16  0.998758  1.241810e-03
8sgj_pocket28  0.999933  6.712489e-05
8sgj_pocket18  0.999967  3.303184e-05
8sgj_pocket11  0.998627  1.372718e-03
8sgj_pocket25  0.998793  1.207400e-03
...                 ...           ...
4jqi_pocket8   0.999994  5.881765e-06
4jqi_pocket3   0.999406  5.942771e-04
4jqi_pocket12  1.000000  3.218317e-07
4jqi_pocket19  0.999932  6.801011e-05
4jqi_pocket6   0.997571  2.429151e-03

[282 rows x 2 columns]

In [23]:
model5_results = {
    pdb: {
        pocket: {
            "prob": prob,
            "pred": 1 if prob >= 0.5 else 0,
            "label": info[("Label", "label")],
            "max_overlap": overlaps.max(),
            **overlaps["Pockets"].to_dict()
        }
        for pocket in pockets["pocket"]
        for prob in (extra_probs.loc[f"{pdb}_{pocket}", 1],)
        for info in (extra.loc[f"{pdb}_{pocket}"],)
        for overlaps in (info[[("Pockets", "pocket_in_site"), ("Pockets", "site_in_pocket")]],)
    }
    for pdb, pockets in (
        pd.DataFrame(
            extra_probs.index.map(lambda x: x.split("_")).values.tolist(),
            columns=["pdb", "pocket"]
        )
        .groupby("pdb")
    )
}

model5_results

{'4jqi': {'pocket16': {'prob': 0.0001226096646860242,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket18': {'prob': 0.003527346532791853,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket11': {'prob': 4.818243542104028e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket15': {'prob': 1.1008408629109567e-09,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 0.0006957116420380771,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket13': {'prob': 0.09678139537572861,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket14': {'prob': 1.2360335688299529e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.48696210980415344,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.1,
   'pocket_in_site': 0.01694915254237288,
   'site_in_pocket': 0.1},
  'pocket2': {'prob': 0.04993942379951477,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket4': {'prob': 0.0003950250393245369,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket17': {'prob': 0.013226842507719994,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.3,
   'pocket_in_site': 0.125,
   'site_in_pocket': 0.3},
  'pocket9': {'prob': 1.895525747386273e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket10': {'prob': 0.00015777153021190315,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.0011327075771987438,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.1,
   'pocket_in_site': 0.1,
   'site_in_pocket': 0.1},
  'pocket8': {'prob': 5.881764991499949e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2,
   'pocket_in_site': 0.14285714285714285,
   'site_in_pocket': 0.2},
  'pocket3': {'prob': 0.0005942771094851196,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket12': {'prob': 3.218316635411611e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket19': {'prob': 6.801011477364227e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 0.002429150976240635,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '5uak': {'pocket16': {'prob': 3.0019442419870757e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.1,
   'pocket_in_site': 0.1,
   'site_in_pocket': 0.037037037037037035},
  'pocket28': {'prob': 0.00038587115705013275,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket74': {'prob': 0.083624929189682,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.037037037037037035,
   'pocket_in_site': 0.025,
   'site_in_pocket': 0.037037037037037035},
  'pocket18': {'prob': 1.94397107406985e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket11': {'prob': 4.243553485139273e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket34': {'prob': 3.98365642695353e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket49': {'prob': 0.000820803688839078,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket75': {'prob': 0.1360320746898651,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket72': {'prob': 2.265783116683906e-08,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket64': {'prob': 6.354485230986029e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket25': {'prob': 0.002951409900560975,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket60': {'prob': 4.296440238249488e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket15': {'prob': 0.08613934367895126,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket40': {'prob': 9.83518566499697e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 0.17062930762767792,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket65': {'prob': 6.698257948301034e-08,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket22': {'prob': 0.0006872391095384955,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket13': {'prob': 0.00047426376841031015,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket31': {'prob': 0.00034840204170905054,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket39': {'prob': 0.00022040517069399357,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket23': {'prob': 0.0005286466330289841,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket14': {'prob': 0.0009157537715509534,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket59': {'prob': 0.006774789188057184,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket70': {'prob': 4.0977141907205805e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket26': {'prob': 0.012044261209666729,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.9867374300956726,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.9629629629629629,
   'pocket_in_site': 0.13978494623655913,
   'site_in_pocket': 0.9629629629629629},
  'pocket46': {'prob': 0.0014091776683926582,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket69': {'prob': 3.480364102870226e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket58': {'prob': 0.00036729127168655396,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket27': {'prob': 0.0027211715932935476,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket44': {'prob': 0.0001502553204772994,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket2': {'prob': 0.9017921090126038,
   'pred': 1,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket32': {'prob': 0.0009325698483735323,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket20': {'prob': 0.00014424252731259912,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket4': {'prob': 0.047339797019958496,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket29': {'prob': 0.28048035502433777,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket67': {'prob': 0.0001530459412606433,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket30': {'prob': 8.970695489551872e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket61': {'prob': 2.23932001972571e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket17': {'prob': 2.677696102182381e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket9': {'prob': 4.362659183243522e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket10': {'prob': 8.874721402207797e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.07142857142857142,
   'pocket_in_site': 0.07142857142857142,
   'site_in_pocket': 0.037037037037037035},
  'pocket35': {'prob': 2.144993959518615e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.30562925338745117,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket66': {'prob': 0.0008130857022479177,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket47': {'prob': 1.7490343452664092e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket73': {'prob': 0.0006872479571029544,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 0.0010288351913914084,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket43': {'prob': 0.00046817478141747415,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket37': {'prob': 0.0004792721301782876,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket57': {'prob': 0.004534082021564245,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket54': {'prob': 0.0006482342723757029,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket51': {'prob': 9.815461817197502e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket53': {'prob': 0.00018505097250454128,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket24': {'prob': 0.0015840076375752687,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket56': {'prob': 1.9594939559830493e-10,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.0075988504104316235,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket45': {'prob': 0.00030932205845601857,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket12': {'prob': 0.13124743103981018,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket50': {'prob': 1.5748948953842046e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket71': {'prob': 0.0027146341744810343,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket68': {'prob': 3.193134398316033e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket48': {'prob': 3.3817927942436654e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket38': {'prob': 0.0012789833126589656,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket52': {'prob': 9.871517977444455e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket62': {'prob': 9.985836868509068e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket42': {'prob': 2.7387670343159698e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket19': {'prob': 0.0002437986695440486,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket21': {'prob': 0.0006895983824506402,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket55': {'prob': 0.0010643895948305726,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket33': {'prob': 9.092727850656956e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket36': {'prob': 0.003312306012958288,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.08333333333333333,
   'pocket_in_site': 0.08333333333333333,
   'site_in_pocket': 0.07407407407407407},
  'pocket63': {'prob': 0.00010547602141741663,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket41': {'prob': 0.0003279552038293332,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 0.7475950121879578,
   'pred': 1,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '6yhr': {'pocket16': {'prob': 0.000840068852994591,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.05,
   'pocket_in_site': 0.05,
   'site_in_pocket': 0.034482758620689655},
  'pocket18': {'prob': 2.988547009863396e-08,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket11': {'prob': 8.406837878283113e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket15': {'prob': 1.2131650350966083e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 5.069195481155475e-07,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket13': {'prob': 0.00022405335039366037,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket14': {'prob': 0.0012382169952616096,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.5116669535636902,
   'pred': 1,
   'label': 1,
   'max_overlap': 0.3793103448275862,
   'pocket_in_site': 0.14864864864864866,
   'site_in_pocket': 0.3793103448275862},
  'pocket2': {'prob': 6.2724589042773005e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket20': {'prob': 0.00042591363308019936,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.14285714285714285,
   'pocket_in_site': 0.14285714285714285,
   'site_in_pocket': 0.06896551724137931},
  'pocket4': {'prob': 0.0004984461120329797,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket17': {'prob': 2.2640482711722143e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.21428571428571427,
   'pocket_in_site': 0.21428571428571427,
   'site_in_pocket': 0.10344827586206896},
  'pocket9': {'prob': 0.0010378675069659948,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.3888888888888889,
   'pocket_in_site': 0.3888888888888889,
   'site_in_pocket': 0.2413793103448276},
  'pocket10': {'prob': 0.0003061984316445887,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.6923076923076923,
   'pocket_in_site': 0.6923076923076923,
   'site_in_pocket': 0.3103448275862069},
  'pocket5': {'prob': 0.031633567065000534,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.16666666666666666,
   'pocket_in_site': 0.16666666666666666,
   'site_in_pocket': 0.06896551724137931},
  'pocket8': {'prob': 0.008575640618801117,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.003484924091026187,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.4117647058823529,
   'pocket_in_site': 0.4117647058823529,
   'site_in_pocket': 0.2413793103448276},
  'pocket12': {'prob': 0.0003283672849647701,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.75,
   'pocket_in_site': 0.75,
   'site_in_pocket': 0.3103448275862069},
  'pocket19': {'prob': 1.5314815755118616e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 0.0006159227923490107,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0}},
 '7l6r': {'pocket11': {'prob': 5.500509359990247e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket7': {'prob': 4.781044026458403e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket13': {'prob': 0.00038983477861620486,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.2222222222222222,
   'pocket_in_site': 0.2222222222222222,
   'site_in_pocket': 0.07692307692307693},
  'pocket14': {'prob': 5.5861914916022215e-06,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket1': {'prob': 0.0016447186935693026,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.3,
   'pocket_in_site': 0.3,
   'site_in_pocket': 0.11538461538461539},
  'pocket2': {'prob': 0.003150504780933261,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket4': {'prob': 0.0006775618530809879,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.07142857142857142,
   'pocket_in_site': 0.07142857142857142,
   'site_in_pocket': 0.038461538461538464},
  'pocket9': {'prob': 0.4967275559902191,
   'pred': 0,
   'label': 1,
   'max_overlap': 0.5263157894736842,
   'pocket_in_site': 0.5263157894736842,
   'site_in_pocket': 0.38461538461538464},
  'pocket10': {'prob': 0.00018154927238356322,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket5': {'prob': 0.0008170751389116049,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket8': {'prob': 0.00011428071593400091,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket3': {'prob': 0.04113571345806122,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket12': {'prob': 0.001183598767966032,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,
   'pocket_in_site': 0.0,
   'site_in_pocket': 0.0},
  'pocket6': {'prob': 6.895566912135109e-05,
   'pred': 0,
   'label': 0,
   'max_overlap': 0.0,

In [24]:
pd.DataFrame((
    {
        "pdb": pdb,
        "pocket": pocket,
        **pocketd
    }
    for pdb, pockets in model5_results.items()
    for pocket, pocketd in pockets.items()
)).sort_values("max_overlap", ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
44,5uak,pocket1,9.867374e-01,1,1,0.962963,0.139785,0.962963
207,7xlq,pocket36,7.707643e-03,0,1,0.950000,0.950000,0.655172
264,AF-A0A1D8PQM9-F1,pocket1,7.636943e-01,1,1,0.904762,0.475000,0.904762
111,6yhr,pocket12,3.283673e-04,0,0,0.750000,0.750000,0.310345
242,8vw5,pocket1,8.185676e-02,0,1,0.695652,0.551724,0.695652
107,6yhr,pocket10,3.061984e-04,0,0,0.692308,0.692308,0.310345
133,7sns,pocket2,8.367134e-01,1,1,0.692308,0.321429,0.692308
209,7xlq,pocket41,2.944160e-03,0,0,0.533333,0.533333,0.275862
223,8sgj,pocket1,9.810975e-01,1,1,0.531250,0.188889,0.531250
121,7l6r,pocket9,4.967276e-01,0,1,0.526316,0.526316,0.384615
110,6yhr,pocket3,3.484924e-03,0,0,0.411765,0.411765,0.241379
106,6yhr,pocket9,1.037868e-03,0,0,0.388889,0.388889,0.241379
101,6yhr,pocket1,5.116670e-01,1,1,0.379310,0.148649,0.379310
132,7sns,pocket1,3.342263e-01,0,1,0.375000,0.300000,0.375000
140,7sns,pocket12,5.605952e-03,0,0,0.307692,0.181818,0.307692
118,7l6r,pocket1,1.644719e-03,0,0,0.300000,0.300000,0.115385
194,7xlq,pocket45,3.081347e-04,0,0,0.300000,0.300000,0.103448
10,4jqi,pocket17,1.322684e-02,0,0,0.300000,0.125000,0.300000
251,8vw5,pocket6,1.372154e-03,0,0,0.260870,0.250000,0.260870
279,AF-A0A1D8PQM9-F1,pocket19,4.550540e-01,0,0,0.250000,0.250000,0.142857
201,7xlq,pocket62,1.469304e-05,0,0,0.250000,0.250000,0.103448
277,AF-A0A1D8PQM9-F1,pocket3,7.510448e-02,0,0,0.238095,0.185185,0.238095
221,8sgj,pocket14,5.787342e-06,0,0,0.222222,0.222222,0.062500
116,7l6r,pocket13,3.898348e-04,0,0,0.222222,0.222222,0.076923
105,6yhr,pocket17,2.264048e-05,0,0,0.214286,0.214286,0.103448
14,4jqi,pocket8,5.881765e-06,0,0,0.200000,0.142857,0.200000
238,8sgj,pocket6,2.534678e-03,0,0,0.187500,0.176471,0.187500
108,6yhr,pocket5,3.163357e-02,0,0,0.166667,0.166667,0.068966
103,6yhr,pocket20,4.259136e-04,0,0,0.142857,0.142857,0.068966
245,8vw5,pocket9,1.554466e-04,0,0,0.142857,0.142857,0.086957
137,7sns,pocket5,1.214310e-03,0,0,0.125000,0.125000,0.125000
217,8sgj,pocket7,1.997486e-06,0,0,0.125000,0.125000,0.031250
152,7xlq,pocket40,1.387074e-06,0,0,0.125000,0.125000,0.034483
216,8sgj,pocket15,3.372802e-05,0,0,0.111111,0.111111,0.031250
234,8sgj,pocket3,5.811149e-04,0,0,0.105263,0.105263,0.062500
243,8vw5,pocket2,1.656396e-02,0,0,0.105263,0.105263,0.086957
7,4jqi,pocket1,4.869621e-01,0,0,0.100000,0.016949,0.100000
19,5uak,pocket16,3.001944e-05,0,0,0.100000,0.100000,0.037037
13,4jqi,pocket5,1.132708e-03,0,0,0.100000,0.100000,0.100000
173,7xlq,pocket29,1.473504e-08,0,0,0.090909,0.090909,0.034483

In [25]:
pd.DataFrame((
    {
        "pdb": pdb,
        "pocket": pocket,
        **pocketd
    }
    for pdb, pockets in model5_results.items()
    for pocket, pocketd in pockets.items()
)).sort_values("label", ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
121,7l6r,pocket9,0.496728,0,1,0.526316,0.526316,0.384615
242,8vw5,pocket1,0.081857,0,1,0.695652,0.551724,0.695652
264,AF-A0A1D8PQM9-F1,pocket1,0.763694,1,1,0.904762,0.475000,0.904762
44,5uak,pocket1,0.986737,1,1,0.962963,0.139785,0.962963
133,7sns,pocket2,0.836713,1,1,0.692308,0.321429,0.692308
223,8sgj,pocket1,0.981097,1,1,0.531250,0.188889,0.531250
101,6yhr,pocket1,0.511667,1,1,0.379310,0.148649,0.379310
207,7xlq,pocket36,0.007708,0,1,0.950000,0.950000,0.655172
132,7sns,pocket1,0.334226,0,1,0.375000,0.300000,0.375000
183,7xlq,pocket47,0.000059,0,0,0.000000,0.000000,0.000000
182,7xlq,pocket66,0.001410,0,0,0.000000,0.000000,0.000000
184,7xlq,pocket8,0.000621,0,0,0.000000,0.000000,0.000000
190,7xlq,pocket53,0.063784,0,0,0.000000,0.000000,0.000000
185,7xlq,pocket43,0.000006,0,0,0.000000,0.000000,0.000000
181,7xlq,pocket5,0.000172,0,0,0.000000,0.000000,0.000000
186,7xlq,pocket37,0.000016,0,0,0.000000,0.000000,0.000000
180,7xlq,pocket35,0.000156,0,0,0.000000,0.000000,0.000000
187,7xlq,pocket57,0.000034,0,0,0.000000,0.000000,0.000000
188,7xlq,pocket54,0.144714,0,0,0.000000,0.000000,0.000000
189,7xlq,pocket51,0.000003,0,0,0.000000,0.000000,0.000000
179,7xlq,pocket10,0.201105,0,0,0.000000,0.000000,0.000000
208,7xlq,pocket63,0.010177,0,0,0.000000,0.000000,0.000000
206,7xlq,pocket33,0.000080,0,0,0.000000,0.000000,0.000000
205,7xlq,pocket55,0.023657,0,0,0.041667,0.041667,0.034483
204,7xlq,pocket21,0.000034,0,0,0.000000,0.000000,0.000000
203,7xlq,pocket19,0.000405,0,0,0.000000,0.000000,0.000000
202,7xlq,pocket42,0.002101,0,0,0.000000,0.000000,0.000000
201,7xlq,pocket62,0.000015,0,0,0.250000,0.250000,0.103448
200,7xlq,pocket52,0.000009,0,0,0.000000,0.000000,0.000000
192,7xlq,pocket56,0.000104,0,0,0.000000,0.000000,0.000000
198,7xlq,pocket48,0.515813,1,0,0.000000,0.000000,0.000000
197,7xlq,pocket68,0.421780,0,0,0.000000,0.000000,0.000000
196,7xlq,pocket50,0.000163,0,0,0.000000,0.000000,0.000000
195,7xlq,pocket12,0.001076,0,0,0.000000,0.000000,0.000000
194,7xlq,pocket45,0.000308,0,0,0.300000,0.300000,0.103448
193,7xlq,pocket3,0.001409,0,0,0.000000,0.000000,0.000000
178,7xlq,pocket9,0.000286,0,0,0.000000,0.000000,0.000000
191,7xlq,pocket24,0.001024,0,0,0.083333,0.083333,0.034483
199,7xlq,pocket38,0.003379,0,0,0.068966,0.062500,0.068966
159,7xlq,pocket23,0.000002,0,0,0.000000,0.000000,0.000000

In [26]:
pd.DataFrame((
    {
        "pdb": pdb,
        "pocket": pocket,
        **pocketd
    }
    for pdb, pockets in model5_results.items()
    for pocket, pocketd in pockets.items()
)).sort_values("prob", ascending=False).iloc[:40]

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
44,5uak,pocket1,0.986737,1,1,0.962963,0.139785,0.962963
223,8sgj,pocket1,0.981097,1,1,0.531250,0.188889,0.531250
50,5uak,pocket2,0.901792,1,0,0.000000,0.000000,0.000000
133,7sns,pocket2,0.836713,1,1,0.692308,0.321429,0.692308
264,AF-A0A1D8PQM9-F1,pocket1,0.763694,1,1,0.904762,0.475000,0.904762
93,5uak,pocket6,0.747595,1,0,0.000000,0.000000,0.000000
198,7xlq,pocket48,0.515813,1,0,0.000000,0.000000,0.000000
101,6yhr,pocket1,0.511667,1,1,0.379310,0.148649,0.379310
163,7xlq,pocket1,0.510600,1,0,0.000000,0.000000,0.000000
121,7l6r,pocket9,0.496728,0,1,0.526316,0.526316,0.384615
7,4jqi,pocket1,0.486962,0,0,0.100000,0.016949,0.100000
279,AF-A0A1D8PQM9-F1,pocket19,0.455054,0,0,0.250000,0.250000,0.142857
197,7xlq,pocket68,0.421780,0,0,0.000000,0.000000,0.000000
132,7sns,pocket1,0.334226,0,1,0.375000,0.300000,0.375000
220,8sgj,pocket23,0.315970,0,0,0.000000,0.000000,0.000000
62,5uak,pocket5,0.305629,0,0,0.000000,0.000000,0.000000
138,7sns,pocket8,0.291187,0,0,0.000000,0.000000,0.000000
54,5uak,pocket29,0.280480,0,0,0.000000,0.000000,0.000000
179,7xlq,pocket10,0.201105,0,0,0.000000,0.000000,0.000000
33,5uak,pocket7,0.170629,0,0,0.000000,0.000000,0.000000
280,AF-A0A1D8PQM9-F1,pocket21,0.160090,0,0,0.000000,0.000000,0.000000
188,7xlq,pocket54,0.144714,0,0,0.000000,0.000000,0.000000
26,5uak,pocket75,0.136032,0,0,0.000000,0.000000,0.000000
77,5uak,pocket12,0.131247,0,0,0.000000,0.000000,0.000000
153,7xlq,pocket7,0.115733,0,0,0.000000,0.000000,0.000000
5,4jqi,pocket13,0.096781,0,0,0.000000,0.000000,0.000000
31,5uak,pocket15,0.086139,0,0,0.000000,0.000000,0.000000
21,5uak,pocket74,0.083625,0,0,0.037037,0.025000,0.037037
160,7xlq,pocket14,0.082497,0,0,0.000000,0.000000,0.000000
242,8vw5,pocket1,0.081857,0,1,0.695652,0.551724,0.695652
277,AF-A0A1D8PQM9-F1,pocket3,0.075104,0,0,0.238095,0.185185,0.238095
190,7xlq,pocket53,0.063784,0,0,0.000000,0.000000,0.000000
225,8sgj,pocket2,0.059493,0,0,0.031250,0.024390,0.031250
136,7sns,pocket10,0.059411,0,0,0.000000,0.000000,0.000000
252,AF-A0A1D8PQM9-F1,pocket16,0.059199,0,0,0.000000,0.000000,0.000000
8,4jqi,pocket2,0.049939,0,0,0.000000,0.000000,0.000000
255,AF-A0A1D8PQM9-F1,pocket11,0.049106,0,0,0.000000,0.000000,0.000000
53,5uak,pocket4,0.047340,0,0,0.000000,0.000000,0.000000
125,7l6r,pocket3,0.041136,0,0,0.000000,0.000000,0.000000
108,6yhr,pocket5,0.031634,0,0,0.166667,0.166667,0.068966

In [27]:
labelled_results = pd.DataFrame((
    {
        "pdb": pdb,
        "pocket": pocket,
        **pocketd
    }
    for pdb, pockets in model5_results.items()
    for pocket, pocketd in pockets.items()
))

preds = []
for pdb in news:
    if pdb == "4jqi": continue #######################################################################################
    pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
    pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
    preds.append(pdbpreds)

our_results = pd.concat(preds).sort_values("max_overlap", ascending=False).iloc[:40]
our_results

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
44,5uak,pocket1,9.867374e-01,1,1,0.962963,0.139785,0.962963
207,7xlq,pocket36,7.707643e-03,0,1,0.950000,0.950000,0.655172
264,AF-A0A1D8PQM9-F1,pocket1,7.636943e-01,1,1,0.904762,0.475000,0.904762
111,6yhr,pocket12,3.283673e-04,0,0,0.750000,0.750000,0.310345
242,8vw5,pocket1,8.185676e-02,1,1,0.695652,0.551724,0.695652
107,6yhr,pocket10,3.061984e-04,0,0,0.692308,0.692308,0.310345
133,7sns,pocket2,8.367134e-01,1,1,0.692308,0.321429,0.692308
209,7xlq,pocket41,2.944160e-03,0,0,0.533333,0.533333,0.275862
223,8sgj,pocket1,9.810975e-01,1,1,0.531250,0.188889,0.531250
121,7l6r,pocket9,4.967276e-01,1,1,0.526316,0.526316,0.384615
110,6yhr,pocket3,3.484924e-03,0,0,0.411765,0.411765,0.241379
106,6yhr,pocket9,1.037868e-03,0,0,0.388889,0.388889,0.241379
101,6yhr,pocket1,5.116670e-01,1,1,0.379310,0.148649,0.379310
132,7sns,pocket1,3.342263e-01,0,1,0.375000,0.300000,0.375000
140,7sns,pocket12,5.605952e-03,0,0,0.307692,0.181818,0.307692
118,7l6r,pocket1,1.644719e-03,0,0,0.300000,0.300000,0.115385
194,7xlq,pocket45,3.081347e-04,0,0,0.300000,0.300000,0.103448
251,8vw5,pocket6,1.372154e-03,0,0,0.260870,0.250000,0.260870
279,AF-A0A1D8PQM9-F1,pocket19,4.550540e-01,0,0,0.250000,0.250000,0.142857
201,7xlq,pocket62,1.469304e-05,0,0,0.250000,0.250000,0.103448
277,AF-A0A1D8PQM9-F1,pocket3,7.510448e-02,0,0,0.238095,0.185185,0.238095
221,8sgj,pocket14,5.787342e-06,0,0,0.222222,0.222222,0.062500
116,7l6r,pocket13,3.898348e-04,0,0,0.222222,0.222222,0.076923
105,6yhr,pocket17,2.264048e-05,0,0,0.214286,0.214286,0.103448
238,8sgj,pocket6,2.534678e-03,0,0,0.187500,0.176471,0.187500
108,6yhr,pocket5,3.163357e-02,0,0,0.166667,0.166667,0.068966
245,8vw5,pocket9,1.554466e-04,0,0,0.142857,0.142857,0.086957
103,6yhr,pocket20,4.259136e-04,0,0,0.142857,0.142857,0.068966
152,7xlq,pocket40,1.387074e-06,0,0,0.125000,0.125000,0.034483
217,8sgj,pocket7,1.997486e-06,0,0,0.125000,0.125000,0.031250
137,7sns,pocket5,1.214310e-03,0,0,0.125000,0.125000,0.125000
216,8sgj,pocket15,3.372802e-05,0,0,0.111111,0.111111,0.031250
243,8vw5,pocket2,1.656396e-02,0,0,0.105263,0.105263,0.086957
234,8sgj,pocket3,5.811149e-04,0,0,0.105263,0.105263,0.062500
19,5uak,pocket16,3.001944e-05,0,0,0.100000,0.100000,0.037037
173,7xlq,pocket29,1.473504e-08,0,0,0.090909,0.090909,0.034483
141,7sns,pocket6,6.384794e-04,0,0,0.083333,0.083333,0.062500
90,5uak,pocket36,3.312306e-03,0,0,0.083333,0.083333,0.074074
227,8sgj,pocket4,3.239725e-04,0,0,0.083333,0.083333,0.031250
191,7xlq,pocket24,1.023644e-03,0,0,0.083333,0.083333,0.034483

In [28]:
model5_results["7sns"]["pocket1"].update({"label": 0})

# Results

## AllositePro

In [29]:
allositepro_resultsf = "AllositePro/allositepro_results.pkl"

with open(allositepro_resultsf, "rb") as f:
    allositepro_results = {k: v for k,v in pickle.load(f).items() if k in news}

len(allositepro_results), allositepro_results

(2,
 {'7l6r': {'pocket0': {'Volume': 2222.145,
    'SASA': 1065.897,
    'Druggability Score': 0.576,
    'logitProb': 0.844,
    'nmaScore': 0.971,
    'hitScore': 0.869,
    'residues':    auth_asym_id auth_seq_id
    0             A        6972
    1             A        6935
    2             A        6996
    3             A        6947
    4             A        6932
    5             A        6931
    6             A        6999
    7             A        6913
    8             A        6897
    9             A        6824
    10            A        6946
    11            A        6871
    12            A        6896
    13            A        6872
    14            A        6911
    15            A        6844
    16            A        6823
    17            A        6929
    18            A        6971
    19            A        6822
    20            A        6828
    21            A        6841
    22            A        6912
    23            A        6928
    24            A        6937
    25            A        6930
    26            A        7000
    27            A        6825
    28            A        6898
    29            A        7001
    30            A        6968
    31            A        6873
    32            A        6869
    33            A        6970
    34            A        6934
    35            A        6868}},
  '7sns': {'pocket0': {'Volume': 1121.762,
    'SASA': 579.602,
    'Druggability Score': 0.604,
    'logitProb': 0.755,
    'nmaScore': 0.123,
    'hitScore': 0.628,
    'residues':    auth_asym_id auth_seq_id
    0             A           9
    1             A         148
    2             A           8
    3             A           4
    4             A           7
    5             A           5
    6             A         168
    7             A         147
    8             A         146
    9             A         169
    10            A         165
    11            A         166
    12            A         167
    13            B          57
    14            B          43
    15            B          37
    16            B          41
    17            B          84
    18            B          61
    19            B           9
    20            B          39
    21            B          87
    22            B          58
    23            B          89
    24            B          59
    25            B          38
    26            B          83
    27            B          82},
   'pocket1': {'Volume': 569.092,
    'SASA': 337.096,
    'Druggability Score': 0.172,
    'logitProb': 0.513,
    'nmaScore': 0.951,
    'hitScore': 0.601,
    'residues':    auth_asym_id auth_seq_id
    0             A          79
    1             A          91
    2             A          77
    3             A          81
    4             A          54
    5             A          43
    6             A         111
    7             A          55
    8             A          92
    9             A          53
    10            A          45
    11            A         110
    12            A         108
    13            A          78
    14            A          94
    15            A          89
    16            A          93
    17            B           4
    18            B           7
    19            B          45
    20            B          46},
   'pocket2': {'Volume': 558.483,
    'SASA': 320.352,
    'Druggability Score': 0.251,
    'logitProb': 0.516,
    'nmaScore': 0.904,
    'hitScore': 0.594,
    'residues':    auth_asym_id auth_seq_id
    0             A          45
    1             A           7
    2             A          46
    3             A           4
    4             B         111
    5             B          91
    6             B          78
    7             B          45
    8             B          77
    9             B          89
    10            B          54
    11            B         108
    12            B          43
    13            B          53
    14            B          94
    15            B          55
    16            B          81
    17            B          79}}})

All output pockets are predicted positive.

In [30]:
allositepro_results = {
    pdb: {
        pocket: {
            "pred": 1,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in allositepro_results.items()
}
allositepro_results

{'7l6r': {'pocket0': {'pred': 1,
   'Volume': 2222.145,
   'SASA': 1065.897,
   'Druggability Score': 0.576,
   'logitProb': 0.844,
   'nmaScore': 0.971,
   'hitScore': 0.869,
   'residues':    auth_asym_id auth_seq_id
   0             A        6972
   1             A        6935
   2             A        6996
   3             A        6947
   4             A        6932
   5             A        6931
   6             A        6999
   7             A        6913
   8             A        6897
   9             A        6824
   10            A        6946
   11            A        6871
   12            A        6896
   13            A        6872
   14            A        6911
   15            A        6844
   16            A        6823
   17            A        6929
   18            A        6971
   19            A        6822
   20            A        6828
   21            A        6841
   22            A        6912
   23            A        6928
   24            A        6937
   25            A        6930
   26            A        7000
   27            A        6825
   28            A        6898
   29            A        7001
   30            A        6968
   31            A        6873
   32            A        6869
   33            A        6970
   34            A        6934
   35            A        6868}},
 '7sns': {'pocket0': {'pred': 1,
   'Volume': 1121.762,
   'SASA': 579.602,
   'Druggability Score': 0.604,
   'logitProb': 0.755,
   'nmaScore': 0.123,
   'hitScore': 0.628,
   'residues':    auth_asym_id auth_seq_id
   0             A           9
   1             A         148
   2             A           8
   3             A           4
   4             A           7
   5             A           5
   6             A         168
   7             A         147
   8             A         146
   9             A         169
   10            A         165
   11            A         166
   12            A         167
   13            B          57
   14            B          43
   15            B          37
   16            B          41
   17            B          84
   18            B          61
   19            B           9
   20            B          39
   21            B          87
   22            B          58
   23            B          89
   24            B          59
   25            B          38
   26            B          83
   27            B          82},
  'pocket1': {'pred': 1,
   'Volume': 569.092,
   'SASA': 337.096,
   'Druggability Score': 0.172,
   'logitProb': 0.513,
   'nmaScore': 0.951,
   'hitScore': 0.601,
   'residues':    auth_asym_id auth_seq_id
   0             A          79
   1             A          91
   2             A          77
   3             A          81
   4             A          54
   5             A          43
   6             A         111
   7             A          55
   8             A          92
   9             A          53
   10            A          45
   11            A         110
   12            A         108
   13            A          78
   14            A          94
   15            A          89
   16            A          93
   17            B           4
   18            B           7
   19            B          45
   20            B          46},
  'pocket2': {'pred': 1,
   'Volume': 558.483,
   'SASA': 320.352,
   'Druggability Score': 0.251,
   'logitProb': 0.516,
   'nmaScore': 0.904,
   'hitScore': 0.594,
   'residues':    auth_asym_id auth_seq_id
   0             A          45
   1             A           7
   2             A          46
   3             A           4
   4             B         111
   5             B          91
   6             B          78
   7             B          45
   8             B          77
   9             B          89
   10            B          54
   11            B         108
   12            B          43
   13            B          53
   14            B          94
   15            B          55
   16            B          81
   17            B          79}}}

## PASSer

In [31]:
passer_resultsf = "PASSer/passer_results.pkl"

with open(passer_resultsf, "rb") as f:
    passer_results = {k1: {k2: v2 for k2, v2 in v1.items() if k2 in news} for k1, v1 in pickle.load(f).items()}

len(passer_results), tuple(len(v) for v in passer_results.values()), passer_results

(3,
 (9, 9, 9),
 {'ensemble': {'8sgj': {'54': {'prob/score': 46.400259248912334,
     'residues':     auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0              A         712                 ?
     1              A         715                 ?
     3              A         711                 ?
     5              A         237                 ?
     7              A         708                 ?
     8              A         707                 ?
     16             A         761                 ?
     17             A         760                 ?
     20             A         759                 ?
     25             A         236                 ?
     27             A          66                 ?
     30             A         235                 ?
     33             A          63                 ?
     39             A          62                 ?
     44             A         241                 ?
     45             A          69                 ?
     46             A         232                 ?
     49             A         751                 ?
     50             A         716                 ?
     58             A         817                 ?
     59             A         816                 ?
     62             A         105                 ?
     63             A          65                 ?
     65             A          95                 ?
     69             A         820                 ?
     72             A         233                 ?
     73             A         824                 ?
     78             A         821                 ?
     85             A         102                 ?
     86             A         830                 ?
     87             A         834                 ?
     88             A          97                 ?
     103            A         823                 ?
     106            A         819                 ?},
    '53': {'prob/score': 41.81335587054491,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         600                 ?
     1             A         623                 ?
     2             A         448                 ?
     4             A         656                 ?
     6             A         660                 ?
     7             A         417                 ?
     8             A         415                 ?
     10            A         621                 ?
     11            A         620                 ?
     17            A         602                 ?
     18            A         453                 ?
     19            A         452                 ?
     24            A         601                 ?
     27            A         605                 ?
     34            A         447                 ?
     36            A         449                 ?
     37            A         454                 ?
     41            A         663                 ?
     44            A         659                 ?
     48            A         451                 ?
     52            A         445                 ?
     53            A         419                 ?
     59            A         446                 ?
     60            A         420                 ?
     62            A         421                 ?
     73            A         450                 ?},
    '1': {'prob/score': 41.08986845239997,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         837                 ?
     1             A         172                 ?
     2             A         833                 ?
     4             A         830                 ?
     5             A         829                 ?
     8             A         836                 ?
     10            A         840                 ?
     11            A         210                 ?
     12            A          99                 ?
     13            A         103                 ?
     14            A         214                 ?
     17            A         244                 ?
     18            A          97                 ?
     21            A         825                 ?
     25            A         827                 ?
     27            A         826                 ?
     34            A         168                 ?
     35            A         175                 ?
     36            A         171                 ?
     41            A         102                 ?
     44            A         165                 ?
     47            A         209                 ?
     50            A         213                 ?
     57            A          98                 ?
     60            A         222                 ?
     61            A         224                 ?},
    '17': {'prob/score': 21.413986792322248,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         247                 ?
     4             A         520                 ?
     7             A         223                 ?
     8             A         226                 ?
     10            A         574                 ?
     15            A         245                 ?
     16            A         228                 ?
     22            A         164                 ?
     23            A         246                 ?
     25            A         227                 ?
     28            A         222                 ?
     32            A         244                 ?},
    '4': {'prob/score': 21.344163009052863,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         868                 ?
     1             A         866                 ?
     2             A         128                 ?
     6             A         192                 ?
     8             A         193                 ?
     12            A         130                 ?
     13            A         867                 ?
     16            A         129                 ?
     19            A         133                 ?
     20            A         872                 ?
     21            A         134                 ?
     22            A         851                 ?
     26            A         869                 ?
     29            A         871                 ?},
    '37': {'prob/score': 21.303347899447544,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         129                 ?
     1             A         128                 ?
     2             A         127                 ?
     3             A          21                 ?
     4             A         788                 ?
     6             A         131                 ?
     7             A         798                 ?
     9             A         120                 ?
     10            A         124                 ?
     14            A         123                 ?
     15            A          22                 ?
     16            A          23                 ?
     18            A         125                 ?
     21            A         784                 ?},
    '15': {'prob/score': 21.229054376817658,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         508                 ?
     1             A         522                 ?
     2             A         523                 ?
     3             A         512                 ?
     4             A         524                 ?
     9             A         509                 ?
     19            A         677                 ?
     22            A         507                 ?
     24            A         521                 ?},
    '27': {'prob/score': 19.821725305519067,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         225                 ?
     1             A         576                 ?
     2             A         577                 ?
     9             A         242                 ?
     10            A         579                 ?
     11            A         224                 ?
     12            A          96                 ?
     16            A          76                 ?
     17            A         578                 ?
     19            A          74                 ?
     20            A         229                 ?
     28            A          75                 ?
     30            A          94                 ?},
    '44': {'prob/score': 16.723024029306544,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         540                 ?
     2            A         538                 ?
     3            A         539                 ?
     4            A         592                 ?
     8            A         590                 ?
     9            A         591                 ?},
    '35': {'prob/score': 15.976311254053144,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         761                 ?
     1             A         237                 ?
     4             A         238                 ?
     5             A         239                 ?
     6             A         236                 ?
     10            A          93                 ?
     11            A          91                 ?
     13            A          92                 ?
     14            A         708                 ?
     20            A         760                 ?
     23            A          75                 ?
     25            A          70                 ?},
    '14': {'prob/score': 15.385569629870588,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A          54                 ?
     1             A         812                 ?
     2             A          55                 ?
     3             A          58                 ?
     8             A         808                 ?
     9             A         805                 ?
     11            A         804                 ?
     13            A          51                 ?
     16            A          47                 ?
     17            A          50                 ?
     22            A         809                 ?},
    '2': {'prob/score': 13.622491923160851,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A          42                 ?
     1             A          33                 ?
     2             A          32                 ?
     4             A          18                 ?
     5             A         793                 ?
     11            A          34                 ?
     12            A          20                 ?
     13            A          29                 ?
     14            A          39                 ?
     16            A          28                 ?
     18            A         789                 ?
     20            A          46                 ?},
    '50': {'prob/score': 12.530130944833218,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         225                 ?
     1             A         219                 ?
     2             A         226                 ?
     7             A         218                 ?
     8             A          96                 ?
     9             A         224                 ?
     10            A          98                 ?
     11            A         223                 ?
     14            A         101                 ?
     15            A          72                 ?
     19            A          74                 ?
     28            A         100                 ?},
    '40': {'prob/score': 10.87077725896961,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         104                 ?
     2             A          68                 ?
     5             A         766                 ?
     6             A          71                 ?
     7             A          72                 ?
     8             A         107                 ?
     11            A         769                 ?
     16            A         108                 ?
     17            A          64                 ?},
    '42': {'prob/score': 10.732115267819609,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A          21                 ?
     2             A          19                 ?
     5             A          17                 ?
     8             A         798                 ?
     9             A         796                 ?
     11            A         797                 ?
     14            A         130                 ?
     16            A         792                 ?
     20            A         788                 ?},
    '22': {'prob/score': 9.885811398271471,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         408                 ?
     1             A         462                 ?
     2             A         461                 ?
     4             A         427                 ?
     5             A         426                 ?
     6             A         428                 ?
     12            A         410                 ?},
    '7': {'prob/score': 9.837496062391438,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         465                 ?
     1             A         466                 ?
     2             A         406                 ?
     5             A         464                 ?
     14            A         462                 ?
     15            A         408                 ?
     16            A         428                 ?
     19            A         407                 ?},
    '29': {'prob/score': 9.572862379718572,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         628                 ?
     1             A         597                 ?
     3             A         627                 ?
     4             A         632                 ?
     5             A         536                 ?
     7             A         595                 ?
     9             A         630                 ?
     13            A         633                 ?
     14            A         629                 ?},
    '10': {'prob/score': 9.178626476204954,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A          59                 ?
     1             A         816                 ?
     2             A          58                 ?
     5             A          62                 ?
     9             A          65                 ?
     11            A         813                 ?
     16            A         812                 ?},
    '18': {'prob/score': 8.579278986144345,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         209                 ?
     1            A         212                 ?
     2            A         208                 ?
     7            A         213                 ?
     9            A         216                 ?},
    '34': {'prob/score': 8.551799581164232,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         695                 ?
     1             A         698                 ?
     4             A          88                 ?
     5             A          90                 ?
     8             A         694                 ?
     12            A          92                 ?
     13            A         238                 ?
     14            A          91                 ?
     18            A         237                 ?},
    '51': {'prob/score': 8.016805304214358,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         609                 ?
     2             A         607                 ?
     3             A         608                 ?
     4             A         596                 ?
     6             A         668                 ?
     11            A         610                 ?
     13            A         595                 ?
     16            A         628                 ?},
    '11': {'prob/score': 7.90204924705904,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         156                 ?
     1             A         157                 ?
     2             A         155                 ?
     3             A         154                 ?
     4             A         906                 ?
     5             A         909                 ?
     11            A         153                 ?},
    '6': {'prob/score': 7.890383366975584,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         744                 ?
     1             A         751                 ?
     4             A         740                 ?
     5             A         718                 ?
     7             A         741                 ?
     8             A         743                 ?
     14            A         737                 ?
     17            A         747                 ?},
    '24': {'prob/score': 7.640129522769712,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         745                 ?
     1             A         741                 ?
     6             A         746                 ?
     11            A         742                 ?
     14            A         738                 ?},
    '16': {'prob/score': 6.464324484113604,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         894                 ?
     1            A         163                 ?
     2            A         164                 ?
     3            A         162                 ?
     4            A         827                 ?},
    '33': {'prob/score': 6.459094623278361,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         884                 ?
     2             A         181                 ?
     4             A         880                 ?
     6             A         184                 ?
     8             A         877                 ?
     13            A         876                 ?
     16            A         180                 ?},
    '28': {'prob/score': 6.378506543114781,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         912                 ?
     2             A         911                 ?
     4             A         898                 ?
     5             A         893                 ?
     6             A         892                 ?
     8             A         908                 ?
     12            A         915                 ?
     15            A         889                 ?},
    '13': {'prob/score': 6.258499827526975,
     'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0            A         913                 ?
     2            A         914                 ?
     3            A         917                 ?
     4            A         918                 ?
     7            A         921                 ?},
    '5': {'prob/score': 5.9488183876965195,
     'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
     0             A         377                 ?
     1             A         393                 ?
     2             A         381                 ?
     3             A         378                 ?
     4             A         382                 ?
     5             A         391                 ?
     6             A         390                 ?
     7             A         389                 ?
     12            A         383                 ?
     13            A         387                 ?},

Top 3 pockets for each PDB are predicted positive.

In [32]:
passer_results = {
    model: {
        pdb: {
            pocket: {
                "pred": 1 if i <=2 else 0,
                **pocketd
            }
            for i, (pocket, pocketd) in enumerate( 
                sorted(
                    pockets.items(), 
                    key=lambda x: x[-1]["prob/score"], 
                    reverse=True
                )
            )
        }
        for pdb, pockets in pdbs.items()
    }
    for model, pdbs in passer_results.items()
}
passer_results

{'ensemble': {'8sgj': {'54': {'pred': 1,
    'prob/score': 46.400259248912334,
    'residues':     auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0              A         712                 ?
    1              A         715                 ?
    3              A         711                 ?
    5              A         237                 ?
    7              A         708                 ?
    8              A         707                 ?
    16             A         761                 ?
    17             A         760                 ?
    20             A         759                 ?
    25             A         236                 ?
    27             A          66                 ?
    30             A         235                 ?
    33             A          63                 ?
    39             A          62                 ?
    44             A         241                 ?
    45             A          69                 ?
    46             A         232                 ?
    49             A         751                 ?
    50             A         716                 ?
    58             A         817                 ?
    59             A         816                 ?
    62             A         105                 ?
    63             A          65                 ?
    65             A          95                 ?
    69             A         820                 ?
    72             A         233                 ?
    73             A         824                 ?
    78             A         821                 ?
    85             A         102                 ?
    86             A         830                 ?
    87             A         834                 ?
    88             A          97                 ?
    103            A         823                 ?
    106            A         819                 ?},
   '53': {'pred': 1,
    'prob/score': 41.81335587054491,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         600                 ?
    1             A         623                 ?
    2             A         448                 ?
    4             A         656                 ?
    6             A         660                 ?
    7             A         417                 ?
    8             A         415                 ?
    10            A         621                 ?
    11            A         620                 ?
    17            A         602                 ?
    18            A         453                 ?
    19            A         452                 ?
    24            A         601                 ?
    27            A         605                 ?
    34            A         447                 ?
    36            A         449                 ?
    37            A         454                 ?
    41            A         663                 ?
    44            A         659                 ?
    48            A         451                 ?
    52            A         445                 ?
    53            A         419                 ?
    59            A         446                 ?
    60            A         420                 ?
    62            A         421                 ?
    73            A         450                 ?},
   '1': {'pred': 1,
    'prob/score': 41.08986845239997,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         837                 ?
    1             A         172                 ?
    2             A         833                 ?
    4             A         830                 ?
    5             A         829                 ?
    8             A         836                 ?
    10            A         840                 ?
    11            A         210                 ?
    12            A          99                 ?
    13            A         103                 ?
    14            A         214                 ?
    17            A         244                 ?
    18            A          97                 ?
    21            A         825                 ?
    25            A         827                 ?
    27            A         826                 ?
    34            A         168                 ?
    35            A         175                 ?
    36            A         171                 ?
    41            A         102                 ?
    44            A         165                 ?
    47            A         209                 ?
    50            A         213                 ?
    57            A          98                 ?
    60            A         222                 ?
    61            A         224                 ?},
   '17': {'pred': 0,
    'prob/score': 21.413986792322248,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         247                 ?
    4             A         520                 ?
    7             A         223                 ?
    8             A         226                 ?
    10            A         574                 ?
    15            A         245                 ?
    16            A         228                 ?
    22            A         164                 ?
    23            A         246                 ?
    25            A         227                 ?
    28            A         222                 ?
    32            A         244                 ?},
   '4': {'pred': 0,
    'prob/score': 21.344163009052863,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         868                 ?
    1             A         866                 ?
    2             A         128                 ?
    6             A         192                 ?
    8             A         193                 ?
    12            A         130                 ?
    13            A         867                 ?
    16            A         129                 ?
    19            A         133                 ?
    20            A         872                 ?
    21            A         134                 ?
    22            A         851                 ?
    26            A         869                 ?
    29            A         871                 ?},
   '37': {'pred': 0,
    'prob/score': 21.303347899447544,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         129                 ?
    1             A         128                 ?
    2             A         127                 ?
    3             A          21                 ?
    4             A         788                 ?
    6             A         131                 ?
    7             A         798                 ?
    9             A         120                 ?
    10            A         124                 ?
    14            A         123                 ?
    15            A          22                 ?
    16            A          23                 ?
    18            A         125                 ?
    21            A         784                 ?},
   '15': {'pred': 0,
    'prob/score': 21.229054376817658,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         508                 ?
    1             A         522                 ?
    2             A         523                 ?
    3             A         512                 ?
    4             A         524                 ?
    9             A         509                 ?
    19            A         677                 ?
    22            A         507                 ?
    24            A         521                 ?},
   '27': {'pred': 0,
    'prob/score': 19.821725305519067,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         225                 ?
    1             A         576                 ?
    2             A         577                 ?
    9             A         242                 ?
    10            A         579                 ?
    11            A         224                 ?
    12            A          96                 ?
    16            A          76                 ?
    17            A         578                 ?
    19            A          74                 ?
    20            A         229                 ?
    28            A          75                 ?
    30            A          94                 ?},
   '44': {'pred': 0,
    'prob/score': 16.723024029306544,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         540                 ?
    2            A         538                 ?
    3            A         539                 ?
    4            A         592                 ?
    8            A         590                 ?
    9            A         591                 ?},
   '35': {'pred': 0,
    'prob/score': 15.976311254053144,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         761                 ?
    1             A         237                 ?
    4             A         238                 ?
    5             A         239                 ?
    6             A         236                 ?
    10            A          93                 ?
    11            A          91                 ?
    13            A          92                 ?
    14            A         708                 ?
    20            A         760                 ?
    23            A          75                 ?
    25            A          70                 ?},
   '14': {'pred': 0,
    'prob/score': 15.385569629870588,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A          54                 ?
    1             A         812                 ?
    2             A          55                 ?
    3             A          58                 ?
    8             A         808                 ?
    9             A         805                 ?
    11            A         804                 ?
    13            A          51                 ?
    16            A          47                 ?
    17            A          50                 ?
    22            A         809                 ?},
   '2': {'pred': 0,
    'prob/score': 13.622491923160851,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A          42                 ?
    1             A          33                 ?
    2             A          32                 ?
    4             A          18                 ?
    5             A         793                 ?
    11            A          34                 ?
    12            A          20                 ?
    13            A          29                 ?
    14            A          39                 ?
    16            A          28                 ?
    18            A         789                 ?
    20            A          46                 ?},
   '50': {'pred': 0,
    'prob/score': 12.530130944833218,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         225                 ?
    1             A         219                 ?
    2             A         226                 ?
    7             A         218                 ?
    8             A          96                 ?
    9             A         224                 ?
    10            A          98                 ?
    11            A         223                 ?
    14            A         101                 ?
    15            A          72                 ?
    19            A          74                 ?
    28            A         100                 ?},
   '40': {'pred': 0,
    'prob/score': 10.87077725896961,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         104                 ?
    2             A          68                 ?
    5             A         766                 ?
    6             A          71                 ?
    7             A          72                 ?
    8             A         107                 ?
    11            A         769                 ?
    16            A         108                 ?
    17            A          64                 ?},
   '42': {'pred': 0,
    'prob/score': 10.732115267819609,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A          21                 ?
    2             A          19                 ?
    5             A          17                 ?
    8             A         798                 ?
    9             A         796                 ?
    11            A         797                 ?
    14            A         130                 ?
    16            A         792                 ?
    20            A         788                 ?},
   '22': {'pred': 0,
    'prob/score': 9.885811398271471,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         408                 ?
    1             A         462                 ?
    2             A         461                 ?
    4             A         427                 ?
    5             A         426                 ?
    6             A         428                 ?
    12            A         410                 ?},
   '7': {'pred': 0,
    'prob/score': 9.837496062391438,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         465                 ?
    1             A         466                 ?
    2             A         406                 ?
    5             A         464                 ?
    14            A         462                 ?
    15            A         408                 ?
    16            A         428                 ?
    19            A         407                 ?},
   '29': {'pred': 0,
    'prob/score': 9.572862379718572,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         628                 ?
    1             A         597                 ?
    3             A         627                 ?
    4             A         632                 ?
    5             A         536                 ?
    7             A         595                 ?
    9             A         630                 ?
    13            A         633                 ?
    14            A         629                 ?},
   '10': {'pred': 0,
    'prob/score': 9.178626476204954,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A          59                 ?
    1             A         816                 ?
    2             A          58                 ?
    5             A          62                 ?
    9             A          65                 ?
    11            A         813                 ?
    16            A         812                 ?},
   '18': {'pred': 0,
    'prob/score': 8.579278986144345,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         209                 ?
    1            A         212                 ?
    2            A         208                 ?
    7            A         213                 ?
    9            A         216                 ?},
   '34': {'pred': 0,
    'prob/score': 8.551799581164232,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         695                 ?
    1             A         698                 ?
    4             A          88                 ?
    5             A          90                 ?
    8             A         694                 ?
    12            A          92                 ?
    13            A         238                 ?
    14            A          91                 ?
    18            A         237                 ?},
   '51': {'pred': 0,
    'prob/score': 8.016805304214358,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         609                 ?
    2             A         607                 ?
    3             A         608                 ?
    4             A         596                 ?
    6             A         668                 ?
    11            A         610                 ?
    13            A         595                 ?
    16            A         628                 ?},
   '11': {'pred': 0,
    'prob/score': 7.90204924705904,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         156                 ?
    1             A         157                 ?
    2             A         155                 ?
    3             A         154                 ?
    4             A         906                 ?
    5             A         909                 ?
    11            A         153                 ?},
   '6': {'pred': 0,
    'prob/score': 7.890383366975584,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         744                 ?
    1             A         751                 ?
    4             A         740                 ?
    5             A         718                 ?
    7             A         741                 ?
    8             A         743                 ?
    14            A         737                 ?
    17            A         747                 ?},
   '24': {'pred': 0,
    'prob/score': 7.640129522769712,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         745                 ?
    1             A         741                 ?
    6             A         746                 ?
    11            A         742                 ?
    14            A         738                 ?},
   '16': {'pred': 0,
    'prob/score': 6.464324484113604,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         894                 ?
    1            A         163                 ?
    2            A         164                 ?
    3            A         162                 ?
    4            A         827                 ?},
   '33': {'pred': 0,
    'prob/score': 6.459094623278361,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         884                 ?
    2             A         181                 ?
    4             A         880                 ?
    6             A         184                 ?
    8             A         877                 ?
    13            A         876                 ?
    16            A         180                 ?},
   '28': {'pred': 0,
    'prob/score': 6.378506543114781,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         912                 ?
    2             A         911                 ?
    4             A         898                 ?
    5             A         893                 ?
    6             A         892                 ?
    8             A         908                 ?
    12            A         915                 ?
    15            A         889                 ?},
   '13': {'pred': 0,
    'prob/score': 6.258499827526975,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         913                 ?
    2            A         914                 ?
    3            A         917                 ?
    4            A         918                 ?
    7            A         921                 ?},
   '5': {'pred': 0,
    'prob/score': 5.9488183876965195,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         377                 ?
    1             A         393                 ?
    2             A         381                 ?
    3             A         378                 ?
    4             A         382                 ?
    5             A         391                 ?
    6             A         390                 ?
    7             A         389                 ?
    12            A         383                 ?

## DeepAllo

In [33]:
deepallo_resultsf = "DeepAllo/deepallo_results.pkl"

with open(deepallo_resultsf, "rb") as f:
    deepallo_results = pickle.load(f)

len(deepallo_results), deepallo_results

(9,
 {'8sgj': {'pocket1': {'pred': 1,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         175                 ?
    1             A         171                 ?
    2             A         172                 ?
    3             A         210                 ?
    4             A         209                 ?
    5             A         840                 ?
    6             A         833                 ?
    7             A          99                 ?
    8             A         168                 ?
    9             A         213                 ?
    10            A         103                 ?
    11            A         214                 ?
    12            A         244                 ?
    13            A         825                 ?
    14            A         827                 ?
    15            A         837                 ?
    16            A         836                 ?
    17            A         826                 ?
    18            A         222                 ?
    19            A         224                 ?
    20            A          97                 ?
    21            A         829                 ?
    22            A         830                 ?
    23            A         165                 ?
    24            A         102                 ?
    25            A          98                 ?,
    'prob': 0.06474058330059052},
   'pocket4': {'pred': 1,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         128                 ?
    1             A         868                 ?
    2             A         867                 ?
    3             A         866                 ?
    4             A         193                 ?
    5             A         192                 ?
    6             A         851                 ?
    7             A         129                 ?
    8             A         133                 ?
    9             A         872                 ?
    10            A         130                 ?
    11            A         871                 ?
    12            A         134                 ?
    13            A         869                 ?,
    'prob': 0.0645398423075676},
   'pocket46': {'pred': 1,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         864                 ?
    1            A         194                 ?
    2            A         195                 ?
    3            A         196                 ?
    4            A         197                 ?
    5            A         859                 ?
    6            A         863                 ?
    7            A         855                 ?
    8            A         865                 ?
    9            A         198                 ?,
    'prob': 0.05889119952917099},
   'pocket2': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         793                 ?
    1             A          39                 ?
    2             A          34                 ?
    3             A          33                 ?
    4             A          18                 ?
    5             A          42                 ?
    6             A          32                 ?
    7             A          29                 ?
    8             A          20                 ?
    9             A          46                 ?
    10            A          28                 ?
    11            A         789                 ?},
   'pocket3': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         134                 ?
    1            A         875                 ?
    2            A         871                 ?
    3            A         927                 ?
    4            A         930                 ?
    5            A         931                 ?
    6            A         803                 ?
    7            A         799                 ?
    8            A         137                 ?
    9            A         872                 ?},
   'pocket5': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         382                 ?
    1            A         381                 ?
    2            A         378                 ?
    3            A         391                 ?
    4            A         393                 ?
    5            A         377                 ?
    6            A         390                 ?
    7            A         389                 ?
    8            A         383                 ?
    9            A         387                 ?},
   'pocket6': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         740                 ?
    1            A         737                 ?
    2            A         718                 ?
    3            A         741                 ?
    4            A         744                 ?
    5            A         743                 ?
    6            A         747                 ?
    7            A         751                 ?},
   'pocket7': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         406                 ?
    1            A         464                 ?
    2            A         428                 ?
    3            A         408                 ?
    4            A         407                 ?
    5            A         462                 ?
    6            A         465                 ?
    7            A         466                 ?},
   'pocket8': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         780                 ?
    1            A         784                 ?
    2            A         119                 ?
    3            A         781                 ?
    4            A         116                 ?
    5            A          24                 ?
    6            A         120                 ?
    7            A         124                 ?
    8            A         785                 ?},
   'pocket9': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         225                 ?
    1             A         576                 ?
    2             A         577                 ?
    3             A         579                 ?
    4             A         242                 ?
    5             A         229                 ?
    6             A         224                 ?
    7             A          76                 ?
    8             A         578                 ?
    9             A          74                 ?
    10            A          94                 ?
    11            A          75                 ?
    12            A          96                 ?},
   'pocket10': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         584                 ?
    1            A         582                 ?
    2            A         583                 ?
    3            A         580                 ?
    4            A         585                 ?
    5            A         578                 ?},
   'pocket11': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         816                 ?
    1            A          62                 ?
    2            A          58                 ?
    3            A         812                 ?
    4            A          59                 ?
    5            A         813                 ?
    6            A          65                 ?},
   'pocket12': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         906                 ?
    1            A         153                 ?
    2            A         156                 ?
    3            A         157                 ?
    4            A         155                 ?
    5            A         154                 ?
    6            A         909                 ?},
   'pocket13': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         762                 ?
    1            A         761                 ?
    2            A         708                 ?
    3            A         707                 ?},
   'pocket14': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         917                 ?
    1            A         914                 ?
    2            A         913                 ?
    3            A         918                 ?
    4            A         921                 ?},
   'pocket15': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A          55                 ?
    1             A          54                 ?
    2             A          51                 ?
    3             A         808                 ?
    4             A         805                 ?
    5             A          47                 ?
    6             A          50                 ?
    7             A         812                 ?
    8             A          58                 ?
    9             A         804                 ?
    10            A         809                 ?},
   'pocket16': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         508                 ?
    1            A         522                 ?
    2            A         523                 ?
    3            A         512                 ?
    4            A         524                 ?
    5            A         509                 ?
    6            A         521                 ?
    7            A         677                 ?
    8            A         507                 ?},
   'pocket17': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         164                 ?
    1            A         162                 ?
    2            A         827                 ?
    3            A         163                 ?
    4            A         894                 ?},
   'pocket18': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         246                 ?
    1             A         247                 ?
    2             A         520                 ?
    3             A         223                 ?
    4             A         226                 ?
    5             A         574                 ?
    6             A         228                 ?
    7             A         227                 ?
    8             A         164                 ?
    9             A         222                 ?
    10            A         244                 ?
    11            A         245                 ?},
   'pocket19': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         213                 ?
    1            A         212                 ?
    2            A         209                 ?
    3            A         216                 ?
    4            A         208                 ?},
   'pocket20': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         530                 ?
    1            A         499                 ?
    2            A         498                 ?
    3            A         501                 ?
    4            A         529                 ?
    5            A         450                 ?},
   'pocket21': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A          91                 ?
    1            A          89                 ?
    2            A          77                 ?
    3            A          75                 ?
    4            A          76                 ?},
   'pocket22': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         221                 ?
    1            A         167                 ?
    2            A         168                 ?
    3            A         165                 ?},
   'pocket23': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         461                 ?
    1            A         410                 ?
    2            A         408                 ?
    3            A         426                 ?
    4            A         427                 ?
    5            A         462                 ?
    6            A         428                 ?},
   'pocket24': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         718                 ?
    1            A         744                 ?
    2            A         745                 ?
    3            A         741                 ?
    4            A         717                 ?
    5            A         748                 ?},
   'pocket25': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         745                 ?
    1            A         746                 ?
    2            A         742                 ?
    3            A         741                 ?
    4            A         738                 ?},
   'pocket26': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         564                 ?
    1            A         618                 ?
    2            A         620                 ?
    3            A         598                 ?
    4            A         625                 ?
    5            A         619                 ?
    6            A         534                 ?
    7            A         563                 ?},
   'pocket27': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A          51                 ?
    1            A          48                 ?
    2            A          47                 ?
    3            A          52                 ?
    4            A         746                 ?
    5            A          55                 ?},
   'pocket28': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         912                 ?
    1            A         893                 ?
    2            A         892                 ?
    3            A         898                 ?
    4            A         908                 ?
    5            A         911                 ?
    6            A         889                 ?
    7            A         915                 ?},
   'pocket29': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         595                 ?
    1            A         597                 ?
    2            A         630                 ?
    3            A         536                 ?
    4            A         632                 ?
    5            A         627                 ?
    6            A         628                 ?
    7            A         629                 ?
    8            A         633                 ?},
   'pocket30': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A          29                 ?
    1            A          27                 ?
    2            A          28                 ?
    3            A          46                 ?
    4            A          26                 ?},
   'pocket31': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         555                 ?
    1            A         574                 ?
    2            A         556                 ?
    3            A         572                 ?
    4            A         554                 ?},
   'pocket32': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         688                 ?
    1            A          81                 ?
    2            A         581                 ?
    3            A          83                 ?
    4            A          82                 ?
    5            A         582                 ?
    6            A         683                 ?},
   'pocket33': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         880                 ?
    1            A         181                 ?
    2            A         877                 ?
    3            A         884                 ?
    4            A         184                 ?
    5            A         876                 ?
    6            A         180                 ?},
   'pocket34': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         695                 ?
    1            A         698                 ?
    2            A          88                 ?
    3            A          90                 ?
    4            A         694                 ?
    5            A         238                 ?
    6            A          92                 ?
    7            A          91                 ?
    8            A         237                 ?},
   'pocket35': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         236                 ?
    1             A         237                 ?
    2             A         238                 ?
    3             A         708                 ?
    4             A         761                 ?
    5             A          75                 ?
    6             A          93                 ?
    7             A         239                 ?
    8             A         760                 ?
    9             A          92                 ?
    10            A          91                 ?
    11            A          70                 ?},
   'pocket36': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         782                 ?
    1            A          53                 ?
    2            A         778                 ?
    3            A         750                 ?
    4            A         753                 ?
    5            A         779                 ?
    6            A         749                 ?
    7            A          52                 ?},
   'pocket37': {'pred': 0,
    'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0             A         129                 ?
    1             A         128                 ?
    2             A         127                 ?
    3             A          21                 ?
    4             A         124                 ?
    5             A         131                 ?
    6             A         120                 ?
    7             A         788                 ?
    8             A         123                 ?
    9             A          23                 ?
    10            A          22                 ?
    11            A         125                 ?
    12            A         784                 ?
    13            A         798                 ?},
   'pocket38': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A         107                 ?
    1            A         114                 ?
    2            A         845                 ?
    3            A         115                 ?
    4            A         773                 ?
    5            A         111                 ?
    6            A          64                 ?},
   'pocket39': {'pred': 0,
    'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
    0            A          48                 ?

In [34]:
deepallo_results = {
    pdb: {
        pocket: {
            "prob": 0, # will be replaced by the real prob of the top3 pockets if it's in pocketd
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in deepallo_results.items()
}
deepallo_results

{'8sgj': {'pocket1': {'prob': 0.06474058330059052,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         175                 ?
   1             A         171                 ?
   2             A         172                 ?
   3             A         210                 ?
   4             A         209                 ?
   5             A         840                 ?
   6             A         833                 ?
   7             A          99                 ?
   8             A         168                 ?
   9             A         213                 ?
   10            A         103                 ?
   11            A         214                 ?
   12            A         244                 ?
   13            A         825                 ?
   14            A         827                 ?
   15            A         837                 ?
   16            A         836                 ?
   17            A         826                 ?
   18            A         222                 ?
   19            A         224                 ?
   20            A          97                 ?
   21            A         829                 ?
   22            A         830                 ?
   23            A         165                 ?
   24            A         102                 ?
   25            A          98                 ?},
  'pocket4': {'prob': 0.0645398423075676,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         128                 ?
   1             A         868                 ?
   2             A         867                 ?
   3             A         866                 ?
   4             A         193                 ?
   5             A         192                 ?
   6             A         851                 ?
   7             A         129                 ?
   8             A         133                 ?
   9             A         872                 ?
   10            A         130                 ?
   11            A         871                 ?
   12            A         134                 ?
   13            A         869                 ?},
  'pocket46': {'prob': 0.05889119952917099,
   'pred': 1,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         864                 ?
   1            A         194                 ?
   2            A         195                 ?
   3            A         196                 ?
   4            A         197                 ?
   5            A         859                 ?
   6            A         863                 ?
   7            A         855                 ?
   8            A         865                 ?
   9            A         198                 ?},
  'pocket2': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         793                 ?
   1             A          39                 ?
   2             A          34                 ?
   3             A          33                 ?
   4             A          18                 ?
   5             A          42                 ?
   6             A          32                 ?
   7             A          29                 ?
   8             A          20                 ?
   9             A          46                 ?
   10            A          28                 ?
   11            A         789                 ?},
  'pocket3': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         134                 ?
   1            A         875                 ?
   2            A         871                 ?
   3            A         927                 ?
   4            A         930                 ?
   5            A         931                 ?
   6            A         803                 ?
   7            A         799                 ?
   8            A         137                 ?
   9            A         872                 ?},
  'pocket5': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         382                 ?
   1            A         381                 ?
   2            A         378                 ?
   3            A         391                 ?
   4            A         393                 ?
   5            A         377                 ?
   6            A         390                 ?
   7            A         389                 ?
   8            A         383                 ?
   9            A         387                 ?},
  'pocket6': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         740                 ?
   1            A         737                 ?
   2            A         718                 ?
   3            A         741                 ?
   4            A         744                 ?
   5            A         743                 ?
   6            A         747                 ?
   7            A         751                 ?},
  'pocket7': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         406                 ?
   1            A         464                 ?
   2            A         428                 ?
   3            A         408                 ?
   4            A         407                 ?
   5            A         462                 ?
   6            A         465                 ?
   7            A         466                 ?},
  'pocket8': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         780                 ?
   1            A         784                 ?
   2            A         119                 ?
   3            A         781                 ?
   4            A         116                 ?
   5            A          24                 ?
   6            A         120                 ?
   7            A         124                 ?
   8            A         785                 ?},
  'pocket9': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         225                 ?
   1             A         576                 ?
   2             A         577                 ?
   3             A         579                 ?
   4             A         242                 ?
   5             A         229                 ?
   6             A         224                 ?
   7             A          76                 ?
   8             A         578                 ?
   9             A          74                 ?
   10            A          94                 ?
   11            A          75                 ?
   12            A          96                 ?},
  'pocket10': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         584                 ?
   1            A         582                 ?
   2            A         583                 ?
   3            A         580                 ?
   4            A         585                 ?
   5            A         578                 ?},
  'pocket11': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         816                 ?
   1            A          62                 ?
   2            A          58                 ?
   3            A         812                 ?
   4            A          59                 ?
   5            A         813                 ?
   6            A          65                 ?},
  'pocket12': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         906                 ?
   1            A         153                 ?
   2            A         156                 ?
   3            A         157                 ?
   4            A         155                 ?
   5            A         154                 ?
   6            A         909                 ?},
  'pocket13': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         762                 ?
   1            A         761                 ?
   2            A         708                 ?
   3            A         707                 ?},
  'pocket14': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         917                 ?
   1            A         914                 ?
   2            A         913                 ?
   3            A         918                 ?
   4            A         921                 ?},
  'pocket15': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          55                 ?
   1             A          54                 ?
   2             A          51                 ?
   3             A         808                 ?
   4             A         805                 ?
   5             A          47                 ?
   6             A          50                 ?
   7             A         812                 ?
   8             A          58                 ?
   9             A         804                 ?
   10            A         809                 ?},
  'pocket16': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         508                 ?
   1            A         522                 ?
   2            A         523                 ?
   3            A         512                 ?
   4            A         524                 ?
   5            A         509                 ?
   6            A         521                 ?
   7            A         677                 ?
   8            A         507                 ?},
  'pocket17': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         164                 ?
   1            A         162                 ?
   2            A         827                 ?
   3            A         163                 ?
   4            A         894                 ?},
  'pocket18': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         246                 ?
   1             A         247                 ?
   2             A         520                 ?
   3             A         223                 ?
   4             A         226                 ?
   5             A         574                 ?
   6             A         228                 ?
   7             A         227                 ?
   8             A         164                 ?
   9             A         222                 ?
   10            A         244                 ?
   11            A         245                 ?},
  'pocket19': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         213                 ?
   1            A         212                 ?
   2            A         209                 ?
   3            A         216                 ?
   4            A         208                 ?},
  'pocket20': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         530                 ?
   1            A         499                 ?
   2            A         498                 ?
   3            A         501                 ?
   4            A         529                 ?
   5            A         450                 ?},
  'pocket21': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          91                 ?
   1            A          89                 ?
   2            A          77                 ?
   3            A          75                 ?
   4            A          76                 ?},
  'pocket22': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         221                 ?
   1            A         167                 ?
   2            A         168                 ?
   3            A         165                 ?},
  'pocket23': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         461                 ?
   1            A         410                 ?
   2            A         408                 ?
   3            A         426                 ?
   4            A         427                 ?
   5            A         462                 ?
   6            A         428                 ?},
  'pocket24': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         718                 ?
   1            A         744                 ?
   2            A         745                 ?
   3            A         741                 ?
   4            A         717                 ?
   5            A         748                 ?},
  'pocket25': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         745                 ?
   1            A         746                 ?
   2            A         742                 ?
   3            A         741                 ?
   4            A         738                 ?},
  'pocket26': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         564                 ?
   1            A         618                 ?
   2            A         620                 ?
   3            A         598                 ?
   4            A         625                 ?
   5            A         619                 ?
   6            A         534                 ?
   7            A         563                 ?},
  'pocket27': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          51                 ?
   1            A          48                 ?
   2            A          47                 ?
   3            A          52                 ?
   4            A         746                 ?
   5            A          55                 ?},
  'pocket28': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         912                 ?
   1            A         893                 ?
   2            A         892                 ?
   3            A         898                 ?
   4            A         908                 ?
   5            A         911                 ?
   6            A         889                 ?
   7            A         915                 ?},
  'pocket29': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         595                 ?
   1            A         597                 ?
   2            A         630                 ?
   3            A         536                 ?
   4            A         632                 ?
   5            A         627                 ?
   6            A         628                 ?
   7            A         629                 ?
   8            A         633                 ?},
  'pocket30': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          29                 ?
   1            A          27                 ?
   2            A          28                 ?
   3            A          46                 ?
   4            A          26                 ?},
  'pocket31': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         555                 ?
   1            A         574                 ?
   2            A         556                 ?
   3            A         572                 ?
   4            A         554                 ?},
  'pocket32': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         688                 ?
   1            A          81                 ?
   2            A         581                 ?
   3            A          83                 ?
   4            A          82                 ?
   5            A         582                 ?
   6            A         683                 ?},
  'pocket33': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         880                 ?
   1            A         181                 ?
   2            A         877                 ?
   3            A         884                 ?
   4            A         184                 ?
   5            A         876                 ?
   6            A         180                 ?},
  'pocket34': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         695                 ?
   1            A         698                 ?
   2            A          88                 ?
   3            A          90                 ?
   4            A         694                 ?
   5            A         238                 ?
   6            A          92                 ?
   7            A          91                 ?
   8            A         237                 ?},
  'pocket35': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         236                 ?
   1             A         237                 ?
   2             A         238                 ?
   3             A         708                 ?
   4             A         761                 ?
   5             A          75                 ?
   6             A          93                 ?
   7             A         239                 ?
   8             A         760                 ?
   9             A          92                 ?
   10            A          91                 ?
   11            A          70                 ?},
  'pocket36': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         782                 ?
   1            A          53                 ?
   2            A         778                 ?
   3            A         750                 ?
   4            A         753                 ?
   5            A         779                 ?
   6            A         749                 ?
   7            A          52                 ?},
  'pocket37': {'prob': 0,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         129                 ?
   1             A         128                 ?
   2             A         127                 ?
   3             A          21                 ?
   4             A         124                 ?
   5             A         131                 ?
   6             A         120                 ?
   7             A         788                 ?
   8             A         123                 ?
   9             A          23                 ?
   10            A          22                 ?
   11            A         125                 ?
   12            A         784                 ?
   13            A         798                 ?},
  'pocket38': {'prob': 0,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         107                 ?
   1            A         114                 ?
   2            A         845                 ?
   3            A         115                 ?
   4            A         773                 ?
   5            A         111                 ?
   6            A          64                 ?},
  'pocket39': {'prob': 0,
   'pred': 0,

In [35]:
deepallo_results["7sns"]

{'pocket1_A': {'prob': 0.7203512787818909,
  'pred': 1,
  'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0             A          30                 ?
  1             A          38                 ?
  2             A         162                 ?
  3             A          77                 ?
  4             A          22                 ?
  5             A          28                 ?
  6             A          36                 ?
  7             A          31                 ?
  8             A          40                 ?
  9             A         110                 ?
  10            A          18                 ?
  11            A          12                 ?
  12            A          37                 ?
  13            A          76                 ?
  14            A          92                 ?
  15            A          58                 ?
  16            A          19                 ?},
 'pocket2_A': {'prob': 0.5346346497535706,
  'pred': 1,
  'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0             A         153                 ?
  1             A          21                 ?
  2             A          93                 ?
  3             A         162                 ?
  4             A         110                 ?
  5             A         151                 ?
  6             A         161                 ?
  7             A          18                 ?
  8             A         109                 ?
  9             A          22                 ?
  10            A         160                 ?},
 'pocket3_B': {'prob': 0.4574265778064728,
  'pred': 1,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B         107                 ?
  1            B         141                 ?
  2            B          97                 ?
  3            B          95                 ?
  4            B         139                 ?
  5            B         127                 ?
  6            B          93                 ?
  7            B          54                 ?
  8            B          94                 ?},
 'pocket2_B': {'prob': 0.42734429240226746,
  'pred': 0,
  'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0             B          30                 ?
  1             B          31                 ?
  2             B          36                 ?
  3             B          38                 ?
  4             B          40                 ?
  5             B          12                 ?
  6             B          37                 ?
  7             B          92                 ?
  8             B          58                 ?
  9             B          29                 ?
  10            B          18                 ?
  11            B          77                 ?
  12            B         110                 ?
  13            B          22                 ?
  14            B         162                 ?
  15            B          19                 ?
  16            B          28                 ?
  17            B          76                 ?
  18            B          27                 ?},
 'pocket3_A': {'prob': 0.16181659698486328,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A          54                 ?
  1            A          94                 ?
  2            A          95                 ?
  3            A         141                 ?
  4            A          97                 ?
  5            A         127                 ?
  6            A         107                 ?
  7            A         139                 ?
  8            A          93                 ?
  9            A         114                 ?},
 'pocket1_B': {'prob': 0.04334361106157303,
  'pred': 0,
  'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0             B         108                 ?
  1             B          81                 ?
  2             B          79                 ?
  3             B          91                 ?
  4             B          94                 ?
  5             B          89                 ?
  6             B          53                 ?
  7             B          43                 ?
  8             B         111                 ?
  9             B          78                 ?
  10            B          77                 ?
  11            B          55                 ?
  12            B          45                 ?},
 'pocket4_A': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A          32                 ?
  1            A          20                 ?
  2            A          23                 ?
  3            A          29                 ?
  4            A          33                 ?
  5            A          19                 ?
  6            A          28                 ?
  7            A          26                 ?
  8            A          27                 ?},
 'pocket4_B': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B          26                 ?
  1            B          75                 ?
  2            B          76                 ?
  3            B         110                 ?
  4            B         132                 ?
  5            B         112                 ?
  6            B         109                 ?
  7            B          27                 ?
  8            B          25                 ?
  9            B          28                 ?},
 'pocket5_A': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A         104                 ?
  1            A         115                 ?
  2            A         117                 ?
  3            A         130                 ?
  4            A         129                 ?
  5            A         128                 ?
  6            A         106                 ?
  7            A         114                 ?},
 'pocket5_B': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B         108                 ?
  1            B         106                 ?
  2            B         113                 ?
  3            B          94                 ?
  4            B          95                 ?
  5            B          96                 ?
  6            B          98                 ?
  7            B         105                 ?
  8            B         104                 ?},
 'pocket6_A': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A          72                 ?
  1            A          71                 ?
  2            A          75                 ?
  3            A          34                 ?
  4            A          33                 ?
  5            A          76                 ?
  6            A          68                 ?},
 'pocket6_B': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B          62                 ?
  1            B          64                 ?
  2            B          65                 ?
  3            B          63                 ?
  4            B          86                 ?
  5            B          87                 ?
  6            B          61                 ?},
 'pocket7_A': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A          36                 ?
  1            A          37                 ?
  2            A          64                 ?
  3            A          38                 ?
  4            A          65                 ?
  5            A          69                 ?
  6            A          60                 ?
  7            A          61                 ?},
 'pocket7_B': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B          23                 ?
  1            B          28                 ?
  2            B          33                 ?
  3            B          19                 ?
  4            B          27                 ?
  5            B          29                 ?
  6            B          20                 ?},
 'pocket8_A': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A         147                 ?
  1            A         165                 ?
  2            A         146                 ?
  3            A         148                 ?
  4            A         166                 ?},
 'pocket8_B': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B           3                 ?
  1            B          49                 ?
  2            B          46                 ?
  3            B           4                 ?
  4            B           2                 ?
  5            B          48                 ?
  6            B          51                 ?},
 'pocket9_A': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            A          89                 ?
  1            A          94                 ?
  2            A          55                 ?
  3            A          81                 ?
  4            A          91                 ?
  5            A         108                 ?},
 'pocket9_B': {'prob': 0,
  'pred': 0,
  'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
  0            B         146                 ?
  1            B         148                 ?
  2            B         165                 ?
  3            B         147                 ?
  4            B         166                 ?
  5            B         168                 ?}}

## STINGAllo

In [36]:
stingallo_resultsf = "STINGAllo/stingallo_results.pkl"

with open(stingallo_resultsf, "rb") as f:
    stingallo_results = pickle.load(f)

len(stingallo_results), stingallo_results

(2,
 {'6yhr': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         960}},
  '7sns': {'pocket1': {'residues':   auth_asym_id auth_seq_id
    0            A          96},
   'pocket2': {'residues':   auth_asym_id auth_seq_id
    0            A         107},
   'pocket3': {'residues':   auth_asym_id auth_seq_id
    0            A         111}}})

In [37]:
stingallo_results = {
    pdb: {
        pocket: {
            "pred": 1,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in stingallo_results.items()
}
stingallo_results

{'6yhr': {'pocket': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         960}},
 '7sns': {'pocket1': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A          96},
  'pocket2': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         107},
  'pocket3': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         111}}}

## AlloFusion

In [38]:
allofusion_resultsf = "AlloFusion/allofusion_results.pkl"

with open(allofusion_resultsf, "rb") as f:
    allofusion_results = {k.upper() if k.startswith("af") else k: v for k, v in pickle.load(f).items()}

len(allofusion_results), allofusion_results

(9,
 {'8sgj': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         451
    1            A         810}},
  'AF-A0A1D8PQM9-F1': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         484}},
  '7l6r': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A        6878
    1            A        6880
    2            A        6968
    3            A        7000}},
  '8vw5': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A         125
    1            A         132
    2            A         143
    3            A         151
    4            A         171
    5            A         289
    6            A         297
    7            A         308}},
  '6yhr': {'pocket': {'residues':    auth_asym_id auth_seq_id
    0             A         577
    1             A         581
    2             A         704
    3             A         713
    4             A         720
    5             A         721
    6             A         730
    7             A         731
    8             A         854
    9             A         888
    10            A         981}},
  '7xlq': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A        1354
    1            A        1397}},
  '5uak': {'pocket': {'residues':    auth_asym_id auth_seq_id
    0             A         347
    1             A         459
    2             A         464
    3             A         605
    4             A         622
    5             A         631
    6             A         911
    7             A         991
    8             A        1098
    9             A        1102
    10            A        1106
    11            A        1144
    12            A        1245
    13            A        1248
    14            A        1250
    15            A        1251
    16            A        1402}},
  '4jqi': {'pocket': {'residues':   auth_asym_id auth_seq_id
    0            A           9
    1            A          21
    2            A         172
    3            A         189
    4            A         321}},
  '7sns': {'pocket_A': {'residues':    auth_asym_id auth_seq_id
    0             A          10
    1             A          16
    2             A          27
    3             A          57
    4             A          59
    5             A          72
    6             A          73
    7             A          75
    8             A         112
    9             A         114
    10            A         132
    11            A         139
    12            A         141},
   'pocket_B': {'residues':    auth_asym_id auth_seq_id
    0             B          10
    1             B          16
    2             B          27
    3             B          57
    4             B          59
    5             B          72
    6             B          73
    7             B          75
    8             B         112
    9             B         114
    10            B         132
    11            B         139
    12            B         141}}})

In [39]:
allofusion_results = {
    pdb: {
        f"pocket_{res['auth_asym_id']}_{res['auth_seq_id']}": {
            "pred": 1,
            "residues": res.to_frame().T
        }
        for pocket, pocketd in pockets.items()
        for i, res in pocketd["residues"].iterrows()
    }
    for pdb, pockets in allofusion_results.items()
}
allofusion_results

{'8sgj': {'pocket_A_451': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         451},
  'pocket_A_810': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         810}},
 'AF-A0A1D8PQM9-F1': {'pocket_A_484': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         484}},
 '7l6r': {'pocket_A_6878': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A        6878},
  'pocket_A_6880': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A        6880},
  'pocket_A_6968': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A        6968},
  'pocket_A_7000': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A        7000}},
 '8vw5': {'pocket_A_125': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         125},
  'pocket_A_132': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         132},
  'pocket_A_143': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         143},
  'pocket_A_151': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         151},
  'pocket_A_171': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         171},
  'pocket_A_289': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         289},
  'pocket_A_297': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A         297},
  'pocket_A_308': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A         308}},
 '6yhr': {'pocket_A_577': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         577},
  'pocket_A_581': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         581},
  'pocket_A_704': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         704},
  'pocket_A_713': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         713},
  'pocket_A_720': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         720},
  'pocket_A_721': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         721},
  'pocket_A_730': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A         730},
  'pocket_A_731': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A         731},
  'pocket_A_854': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            A         854},
  'pocket_A_888': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            A         888},
  'pocket_A_981': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   10            A         981}},
 '7xlq': {'pocket_A_1354': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A        1354},
  'pocket_A_1397': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A        1397}},
 '5uak': {'pocket_A_347': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A         347},
  'pocket_A_459': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A         459},
  'pocket_A_464': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         464},
  'pocket_A_605': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         605},
  'pocket_A_622': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         622},
  'pocket_A_631': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A         631},
  'pocket_A_911': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A         911},
  'pocket_A_991': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A         991},
  'pocket_A_1098': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            A        1098},
  'pocket_A_1102': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            A        1102},
  'pocket_A_1106': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   10            A        1106},
  'pocket_A_1144': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   11            A        1144},
  'pocket_A_1245': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   12            A        1245},
  'pocket_A_1248': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   13            A        1248},
  'pocket_A_1250': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   14            A        1250},
  'pocket_A_1251': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   15            A        1251},
  'pocket_A_1402': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   16            A        1402}},
 '4jqi': {'pocket_A_9': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A           9},
  'pocket_A_21': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A          21},
  'pocket_A_172': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A         172},
  'pocket_A_189': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A         189},
  'pocket_A_321': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A         321}},
 '7sns': {'pocket_A_10': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            A          10},
  'pocket_A_16': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            A          16},
  'pocket_A_27': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            A          27},
  'pocket_A_57': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            A          57},
  'pocket_A_59': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            A          59},
  'pocket_A_72': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            A          72},
  'pocket_A_73': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            A          73},
  'pocket_A_75': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            A          75},
  'pocket_A_112': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            A         112},
  'pocket_A_114': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            A         114},
  'pocket_A_132': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   10            A         132},
  'pocket_A_139': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   11            A         139},
  'pocket_A_141': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   12            A         141},
  'pocket_B_10': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   0            B          10},
  'pocket_B_16': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   1            B          16},
  'pocket_B_27': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   2            B          27},
  'pocket_B_57': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   3            B          57},
  'pocket_B_59': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   4            B          59},
  'pocket_B_72': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   5            B          72},
  'pocket_B_73': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   6            B          73},
  'pocket_B_75': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   7            B          75},
  'pocket_B_112': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   8            B         112},
  'pocket_B_114': {'pred': 1,
   'residues':   auth_asym_id auth_seq_id
   9            B         114},
  'pocket_B_132': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   10            B         132},
  'pocket_B_139': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   11            B         139},
  'pocket_B_141': {'pred': 1,
   'residues':    auth_asym_id auth_seq_id
   12            B         141}}}

## AllosES

In [40]:
alloses_resultsf = "AllosES/alloses_results.pkl"

with open(alloses_resultsf, "rb") as f:
    alloses_results = pickle.load(f)

len(alloses_results), alloses_results

(9,
 {'8sgj': {'pocket1': {'pro_ave': 0.4566435782802614,
    'residues':    auth_seq_id auth_asym_id
    0          837            A
    1          172            A
    2          833            A
    3          830            A
    4          829            A
    5          836            A
    6          840            A
    7          210            A
    8           99            A
    9          103            A
    10         214            A
    11         244            A
    12          97            A
    13         825            A
    14         827            A
    15         826            A
    16         168            A
    17         175            A
    18         171            A
    19         102            A
    20         165            A
    21         209            A
    22         213            A
    23          98            A
    24         222            A
    25         224            A},
   'pocket54': {'pro_ave': 0.2878497901019058,
    'residues':    auth_seq_id auth_asym_id
    0          712            A
    1          715            A
    2          711            A
    3          237            A
    4          708            A
    5          707            A
    6          761            A
    7          760            A
    8          759            A
    9          236            A
    10          66            A
    11         235            A
    12          63            A
    13          62            A
    14         241            A
    15          69            A
    16         232            A
    17         751            A
    18         716            A
    19         817            A
    20         816            A
    21         105            A
    22          65            A
    23          95            A
    24         820            A
    25         233            A
    26         824            A
    27         821            A
    28         102            A
    29         830            A
    30         834            A
    31          97            A
    32         823            A
    33         819            A},
   'pocket40': {'pro_ave': 0.1734607927798349,
    'residues':   auth_seq_id auth_asym_id
    0         104            A
    1          68            A
    2         766            A
    3          71            A
    4          72            A
    5         107            A
    6         769            A
    7         108            A
    8          64            A},
   'pocket15': {'pro_ave': 0.1625996096117233,
    'residues':   auth_seq_id auth_asym_id
    0         508            A
    1         522            A
    2         523            A
    3         512            A
    4         524            A
    5         509            A
    6         677            A
    7         507            A
    8         521            A},
   'pocket14': {'pro_ave': 0.1571703420466916,
    'residues':    auth_seq_id auth_asym_id
    0           54            A
    1          812            A
    2           55            A
    3           58            A
    4          808            A
    5          805            A
    6          804            A
    7           51            A
    8           47            A
    9           50            A
    10         809            A},
   'pocket37': {'pro_ave': 0.1363207099892069,
    'residues':    auth_seq_id auth_asym_id
    0          129            A
    1          128            A
    2          127            A
    3           21            A
    4          788            A
    5          131            A
    6          798            A
    7          120            A
    8          124            A
    9          123            A
    10          22            A
    11          23            A
    12         125            A
    13         784            A},
   'pocket53': {'pro_ave': 0.1345995059567041,
    'residues':    auth_seq_id auth_asym_id
    0          600            A
    1          623            A
    2          448            A
    3          656            A
    4          660            A
    5          417            A
    6          415            A
    7          621            A
    8          620            A
    9          602            A
    10         453            A
    11         452            A
    12         601            A
    13         605            A
    14         447            A
    15         449            A
    16         454            A
    17         663            A
    18         659            A
    19         451            A
    20         445            A
    21         419            A
    22         446            A
    23         420            A
    24         421            A
    25         450            A},
   'pocket44': {'pro_ave': 0.1311344936441817,
    'residues':   auth_seq_id auth_asym_id
    0         540            A
    1         538            A
    2         539            A
    3         592            A
    4         590            A
    5         591            A},
   'pocket39': {'pro_ave': 0.1289870354747966,
    'residues':   auth_seq_id auth_asym_id
    0          48            A
    1          45            A
    2          49            A
    3          52            A
    4          44            A},
   'pocket50': {'pro_ave': 0.1221113407578764,
    'residues':    auth_seq_id auth_asym_id
    0          225            A
    1          219            A
    2          226            A
    3          218            A
    4           96            A
    5          224            A
    6           98            A
    7          223            A
    8          101            A
    9           72            A
    10          74            A
    11         100            A},
   'pocket13': {'pro_ave': 0.1216957792706279,
    'residues':   auth_seq_id auth_asym_id
    0         913            A
    1         914            A
    2         917            A
    3         918            A
    4         921            A},
   'pocket33': {'pro_ave': 0.1215533971045553,
    'residues':   auth_seq_id auth_asym_id
    0         884            A
    1         181            A
    2         880            A
    3         184            A
    4         877            A
    5         876            A
    6         180            A},
   'pocket21': {'pro_ave': 0.1192454617342589,
    'residues':   auth_seq_id auth_asym_id
    0         167            A
    1         221            A
    2         168            A
    3         165            A},
   'pocket8': {'pro_ave': 0.1180615896513026,
    'residues':   auth_seq_id auth_asym_id
    0         119            A
    1         120            A
    2         784            A
    3         116            A
    4         124            A
    5          24            A
    6         785            A
    7         780            A
    8         781            A},
   'pocket26': {'pro_ave': 0.1174433799890073,
    'residues':   auth_seq_id auth_asym_id
    0          52            A
    1          48            A
    2          47            A
    3          51            A
    4          55            A
    5         746            A},
   'pocket3': {'pro_ave': 0.1174388737921299,
    'residues':   auth_seq_id auth_asym_id
    0         134            A
    1         875            A
    2         803            A
    3         799            A
    4         927            A
    5         871            A
    6         931            A
    7         930            A
    8         137            A
    9         872            A},
   'pocket34': {'pro_ave': 0.1165089017695761,
    'residues':   auth_seq_id auth_asym_id
    0         695            A
    1         698            A
    2          88            A
    3          90            A
    4         694            A
    5          92            A
    6         238            A
    7          91            A
    8         237            A},
   'pocket46': {'pro_ave': 0.1162021167956458,
    'residues':   auth_seq_id auth_asym_id
    0         864            A
    1         194            A
    2         195            A
    3         196            A
    4         197            A
    5         859            A
    6         863            A
    7         855            A
    8         865            A
    9         198            A},
   'pocket38': {'pro_ave': 0.1126744823339926,
    'residues':   auth_seq_id auth_asym_id
    0         773            A
    1         115            A
    2         114            A
    3         111            A
    4         107            A
    5          64            A
    6         845            A},
   'pocket18': {'pro_ave': 0.1125044537547318,
    'residues':   auth_seq_id auth_asym_id
    0         209            A
    1         212            A
    2         208            A
    3         213            A
    4         216            A},
   'pocket36': {'pro_ave': 0.1117788449676401,
    'residues':   auth_seq_id auth_asym_id
    0         749            A
    1         750            A
    2         753            A
    3          53            A
    4         778            A
    5         779            A
    6         782            A
    7          52            A},
   'pocket27': {'pro_ave': 0.1105504786148025,
    'residues':    auth_seq_id auth_asym_id
    0          225            A
    1          576            A
    2          577            A
    3          242            A
    4          579            A
    5          224            A
    6           96            A
    7           76            A
    8          578            A
    9           74            A
    10         229            A
    11          75            A
    12          94            A},
   'pocket35': {'pro_ave': 0.10945018329252,
    'residues':    auth_seq_id auth_asym_id
    0          761            A
    1          237            A
    2          238            A
    3          239            A
    4          236            A
    5           93            A
    6           91            A
    7           92            A
    8          708            A
    9          760            A
    10          75            A
    11          70            A},
   'pocket47': {'pro_ave': 0.1041881740461209,
    'residues':   auth_seq_id auth_asym_id
    0         762            A
    1         763            A
    2         709            A
    3         758            A
    4         771            A
    5         767            A
    6         770            A},
   'pocket52': {'pro_ave': 0.1020520247953693,
    'residues':   auth_seq_id auth_asym_id
    0         933            A
    1         935            A
    2         870            A
    3         871            A
    4         930            A
    5         931            A
    6         868            A},
   'pocket25': {'pro_ave': 0.1016081210170074,
    'residues':   auth_seq_id auth_asym_id
    0         598            A
    1         625            A
    2         618            A
    3         620            A
    4         619            A
    5         564            A
    6         534            A
    7         563            A},
   'pocket10': {'pro_ave': 0.1015626069356534,
    'residues':   auth_seq_id auth_asym_id
    0          59            A
    1         816            A
    2          58            A
    3          62            A
    4          65            A
    5         813            A
    6         812            A},
   'pocket49': {'pro_ave': 0.096369349808425,
    'residues':   auth_seq_id auth_asym_id
    0         856            A
    1         852            A
    2         853            A
    3         849            A
    4         204            A
    5         201            A},
   'pocket41': {'pro_ave': 0.0916936928177328,
    'residues':   auth_seq_id auth_asym_id
    0         689            A
    1         686            A
    2         690            A
    3         693            A
    4         243            A
    5         230            A
    6         231            A
    7         232            A
    8         824            A
    9         233            A},
   'pocket4': {'pro_ave': 0.0909573523344817,
    'residues':    auth_seq_id auth_asym_id
    0          868            A
    1          866            A
    2          128            A
    3          192            A
    4          193            A
    5          130            A
    6          867            A
    7          129            A
    8          133            A
    9          872            A
    10         134            A
    11         851            A
    12         869            A
    13         871            A},
   'pocket28': {'pro_ave': 0.0833132183805546,
    'residues':   auth_seq_id auth_asym_id
    0         912            A
    1         911            A
    2         898            A
    3         893            A
    4         892            A
    5         908            A
    6         915            A
    7         889            A},
   'pocket31': {'pro_ave': 0.0775529513648791,
    'residues':   auth_seq_id auth_asym_id
    0         574            A
    1         554            A
    2         555            A
    3         556            A
    4         572            A},
   'pocket29': {'pro_ave': 0.0739604608385042,
    'residues':   auth_seq_id auth_asym_id
    0         628            A
    1         597            A
    2         627            A
    3         632            A
    4         536            A
    5         595            A
    6         630            A
    7         633            A
    8         629            A},
   'pocket17': {'pro_ave': 0.067914218127466,
    'residues':    auth_seq_id auth_asym_id
    0          247            A
    1          520            A
    2          223            A
    3          226            A
    4          574            A
    5          245            A
    6          228            A
    7          164            A
    8          246            A
    9          227            A
    10         222            A
    11         244            A},
   'pocket48': {'pro_ave': 0.0675220752703562,
    'residues':   auth_seq_id auth_asym_id
    0         515            A
    1         685            A
    2         683            A
    3         228            A
    4         684            A
    5         229            A
    6         517            A
    7         686            A},
   'pocket12': {'pro_ave': 0.0670042777241036,
    'residues':   auth_seq_id auth_asym_id
    0         761            A
    1         762            A
    2         708            A
    3         707            A},
   'pocket45': {'pro_ave': 0.061447744307997,
    'residues':   auth_seq_id auth_asym_id
    0         247            A
    1         518            A
    2         248            A
    3         514            A
    4         522            A
    5         521            A
    6         520            A
    7         512            A},
   'pocket23': {'pro_ave': 0.0573544885410174,
    'residues':   auth_seq_id auth_asym_id
    0         745            A
    1         717            A
    2         741            A
    3         718            A
    4         744            A
    5         748            A},
   'pocket51': {'pro_ave': 0.0571718078546414,
    'residues':   auth_seq_id auth_asym_id
    0         609            A
    1         607            A
    2         608            A
    3         596            A
    4         668            A
    5         610            A
    6         595            A
    7         628            A},
   'pocket20': {'pro_ave': 0.0554110227241032,
    'residues':   auth_seq_id auth_asym_id
    0          77            A
    1          75            A
    2          91            A
    3          89            A
    4          76            A},
   'pocket5': {'pro_ave': 0.0547091587296161,
    'residues':   auth_seq_id auth_asym_id
    0         377            A
    1         393            A
    2         381            A
    3         378            A
    4         382            A
    5         391            A
    6         390            A
    7         389            A
    8         383            A
    9         387            A},
   'pocket6': {'pro_ave': 0.0513235392609814,
    'residues':   auth_seq_id auth_asym_id
    0         744            A
    1         751            A
    2         740            A
    3         718            A
    4         741            A
    5         743            A
    6         737            A
    7         747            A},
   'pocket19': {'pro_ave': 0.0508887361152054,
    'residues':   auth_seq_id auth_asym_id
    0         529            A
    1         501            A
    2         498            A
    3         499            A
    4         530            A
    5         450            A},
   'pocket42': {'pro_ave': 0.0508449496848455,
    'residues':   auth_seq_id auth_asym_id
    0          21            A
    1          19            A
    2          17            A
    3         798            A
    4         796            A
    5         797            A
    6         130            A
    7         792            A
    8         788            A},
   'pocket30': {'pro_ave': 0.0487426734018541,
    'residues':   auth_seq_id auth_asym_id
    0          29            A
    1          28            A
    2          27            A
    3          46            A
    4          26            A},
   'pocket2': {'pro_ave': 0.0475608008712661,
    'residues':    auth_seq_id auth_asym_id
    0           42            A
    1           33            A
    2           32            A
    3           18            A
    4          793            A
    5           34            A
    6           20            A
    7           29            A
    8           39            A
    9           28            A
    10         789            A
    11          46            A},
   'pocket22': {'pro_ave': 0.0451166134051986,
    'residues':   auth_seq_id auth_asym_id
    0         408            A
    1         462            A
    2         461            A
    3         427            A
    4         426            A
    5         428            A
    6         410            A},
   'pocket24': {'pro_ave': 0.0446849323817689,
    'residues':   auth_seq_id auth_asym_id
    0         745            A
    1         741            A
    2         746            A
    3         742            A
    4         738            A},
   'pocket9': {'pro_ave': 0.0407928953470048,
    'residues':   auth_seq_id auth_asym_id
    0         584            A
    1         582            A
    2         583            A
    3         585            A
    4         580            A
    5         578            A},
   'pocket16': {'pro_ave': 0.0402360525131337,
    'residues':   auth_seq_id auth_asym_id
    0         894            A
    1         163            A
    2         164            A
    3         162            A
    4         827            A},
   'pocket11': {'pro_ave': 0.0345441281496303,
    'residues':   auth_seq_id auth_asym_id
    0         156            A
    1         157            A
    2         155            A
    3         154            A
    4         906            A
    5         909            A
    6         153            A},
   'pocket7': {'pro_ave': 0.0343978936638829,
    'residues':   auth_seq_id auth_asym_id
    0         465            A
    1         466            A
    2         406            A
    3         464            A
    4         462            A
    5         408            A
    6         428            A
    7         407            A},
   'pocket32': {'pro_ave': 0.0312345964340321,
    'residues':   auth_seq_id auth_asym_id
    0         688            A
    1         582            A
    2         581            A
    3         683            A

Positive preds. above 0.5 probability (average) and upper pdb name for AlphaFold model.

In [41]:
alloses_results = {
    pdb if "af" not in pdb.lower() else pdb.upper(): {
        pocket: {
            "pred": 1 if pocketd["pro_ave"] >= 0.5 else 0,
            **pocketd
        }
        for pocket, pocketd in pockets.items()
    }
    for pdb, pockets in alloses_results.items()
}
alloses_results

{'8sgj': {'pocket1': {'pred': 0,
   'pro_ave': 0.4566435782802614,
   'residues':    auth_seq_id auth_asym_id
   0          837            A
   1          172            A
   2          833            A
   3          830            A
   4          829            A
   5          836            A
   6          840            A
   7          210            A
   8           99            A
   9          103            A
   10         214            A
   11         244            A
   12          97            A
   13         825            A
   14         827            A
   15         826            A
   16         168            A
   17         175            A
   18         171            A
   19         102            A
   20         165            A
   21         209            A
   22         213            A
   23          98            A
   24         222            A
   25         224            A},
  'pocket54': {'pred': 0,
   'pro_ave': 0.2878497901019058,
   'residues':    auth_seq_id auth_asym_id
   0          712            A
   1          715            A
   2          711            A
   3          237            A
   4          708            A
   5          707            A
   6          761            A
   7          760            A
   8          759            A
   9          236            A
   10          66            A
   11         235            A
   12          63            A
   13          62            A
   14         241            A
   15          69            A
   16         232            A
   17         751            A
   18         716            A
   19         817            A
   20         816            A
   21         105            A
   22          65            A
   23          95            A
   24         820            A
   25         233            A
   26         824            A
   27         821            A
   28         102            A
   29         830            A
   30         834            A
   31          97            A
   32         823            A
   33         819            A},
  'pocket40': {'pred': 0,
   'pro_ave': 0.1734607927798349,
   'residues':   auth_seq_id auth_asym_id
   0         104            A
   1          68            A
   2         766            A
   3          71            A
   4          72            A
   5         107            A
   6         769            A
   7         108            A
   8          64            A},
  'pocket15': {'pred': 0,
   'pro_ave': 0.1625996096117233,
   'residues':   auth_seq_id auth_asym_id
   0         508            A
   1         522            A
   2         523            A
   3         512            A
   4         524            A
   5         509            A
   6         677            A
   7         507            A
   8         521            A},
  'pocket14': {'pred': 0,
   'pro_ave': 0.1571703420466916,
   'residues':    auth_seq_id auth_asym_id
   0           54            A
   1          812            A
   2           55            A
   3           58            A
   4          808            A
   5          805            A
   6          804            A
   7           51            A
   8           47            A
   9           50            A
   10         809            A},
  'pocket37': {'pred': 0,
   'pro_ave': 0.1363207099892069,
   'residues':    auth_seq_id auth_asym_id
   0          129            A
   1          128            A
   2          127            A
   3           21            A
   4          788            A
   5          131            A
   6          798            A
   7          120            A
   8          124            A
   9          123            A
   10          22            A
   11          23            A
   12         125            A
   13         784            A},
  'pocket53': {'pred': 0,
   'pro_ave': 0.1345995059567041,
   'residues':    auth_seq_id auth_asym_id
   0          600            A
   1          623            A
   2          448            A
   3          656            A
   4          660            A
   5          417            A
   6          415            A
   7          621            A
   8          620            A
   9          602            A
   10         453            A
   11         452            A
   12         601            A
   13         605            A
   14         447            A
   15         449            A
   16         454            A
   17         663            A
   18         659            A
   19         451            A
   20         445            A
   21         419            A
   22         446            A
   23         420            A
   24         421            A
   25         450            A},
  'pocket44': {'pred': 0,
   'pro_ave': 0.1311344936441817,
   'residues':   auth_seq_id auth_asym_id
   0         540            A
   1         538            A
   2         539            A
   3         592            A
   4         590            A
   5         591            A},
  'pocket39': {'pred': 0,
   'pro_ave': 0.1289870354747966,
   'residues':   auth_seq_id auth_asym_id
   0          48            A
   1          45            A
   2          49            A
   3          52            A
   4          44            A},
  'pocket50': {'pred': 0,
   'pro_ave': 0.1221113407578764,
   'residues':    auth_seq_id auth_asym_id
   0          225            A
   1          219            A
   2          226            A
   3          218            A
   4           96            A
   5          224            A
   6           98            A
   7          223            A
   8          101            A
   9           72            A
   10          74            A
   11         100            A},
  'pocket13': {'pred': 0,
   'pro_ave': 0.1216957792706279,
   'residues':   auth_seq_id auth_asym_id
   0         913            A
   1         914            A
   2         917            A
   3         918            A
   4         921            A},
  'pocket33': {'pred': 0,
   'pro_ave': 0.1215533971045553,
   'residues':   auth_seq_id auth_asym_id
   0         884            A
   1         181            A
   2         880            A
   3         184            A
   4         877            A
   5         876            A
   6         180            A},
  'pocket21': {'pred': 0,
   'pro_ave': 0.1192454617342589,
   'residues':   auth_seq_id auth_asym_id
   0         167            A
   1         221            A
   2         168            A
   3         165            A},
  'pocket8': {'pred': 0,
   'pro_ave': 0.1180615896513026,
   'residues':   auth_seq_id auth_asym_id
   0         119            A
   1         120            A
   2         784            A
   3         116            A
   4         124            A
   5          24            A
   6         785            A
   7         780            A
   8         781            A},
  'pocket26': {'pred': 0,
   'pro_ave': 0.1174433799890073,
   'residues':   auth_seq_id auth_asym_id
   0          52            A
   1          48            A
   2          47            A
   3          51            A
   4          55            A
   5         746            A},
  'pocket3': {'pred': 0,
   'pro_ave': 0.1174388737921299,
   'residues':   auth_seq_id auth_asym_id
   0         134            A
   1         875            A
   2         803            A
   3         799            A
   4         927            A
   5         871            A
   6         931            A
   7         930            A
   8         137            A
   9         872            A},
  'pocket34': {'pred': 0,
   'pro_ave': 0.1165089017695761,
   'residues':   auth_seq_id auth_asym_id
   0         695            A
   1         698            A
   2          88            A
   3          90            A
   4         694            A
   5          92            A
   6         238            A
   7          91            A
   8         237            A},
  'pocket46': {'pred': 0,
   'pro_ave': 0.1162021167956458,
   'residues':   auth_seq_id auth_asym_id
   0         864            A
   1         194            A
   2         195            A
   3         196            A
   4         197            A
   5         859            A
   6         863            A
   7         855            A
   8         865            A
   9         198            A},
  'pocket38': {'pred': 0,
   'pro_ave': 0.1126744823339926,
   'residues':   auth_seq_id auth_asym_id
   0         773            A
   1         115            A
   2         114            A
   3         111            A
   4         107            A
   5          64            A
   6         845            A},
  'pocket18': {'pred': 0,
   'pro_ave': 0.1125044537547318,
   'residues':   auth_seq_id auth_asym_id
   0         209            A
   1         212            A
   2         208            A
   3         213            A
   4         216            A},
  'pocket36': {'pred': 0,
   'pro_ave': 0.1117788449676401,
   'residues':   auth_seq_id auth_asym_id
   0         749            A
   1         750            A
   2         753            A
   3          53            A
   4         778            A
   5         779            A
   6         782            A
   7          52            A},
  'pocket27': {'pred': 0,
   'pro_ave': 0.1105504786148025,
   'residues':    auth_seq_id auth_asym_id
   0          225            A
   1          576            A
   2          577            A
   3          242            A
   4          579            A
   5          224            A
   6           96            A
   7           76            A
   8          578            A
   9           74            A
   10         229            A
   11          75            A
   12          94            A},
  'pocket35': {'pred': 0,
   'pro_ave': 0.10945018329252,
   'residues':    auth_seq_id auth_asym_id
   0          761            A
   1          237            A
   2          238            A
   3          239            A
   4          236            A
   5           93            A
   6           91            A
   7           92            A
   8          708            A
   9          760            A
   10          75            A
   11          70            A},
  'pocket47': {'pred': 0,
   'pro_ave': 0.1041881740461209,
   'residues':   auth_seq_id auth_asym_id
   0         762            A
   1         763            A
   2         709            A
   3         758            A
   4         771            A
   5         767            A
   6         770            A},
  'pocket52': {'pred': 0,
   'pro_ave': 0.1020520247953693,
   'residues':   auth_seq_id auth_asym_id
   0         933            A
   1         935            A
   2         870            A
   3         871            A
   4         930            A
   5         931            A
   6         868            A},
  'pocket25': {'pred': 0,
   'pro_ave': 0.1016081210170074,
   'residues':   auth_seq_id auth_asym_id
   0         598            A
   1         625            A
   2         618            A
   3         620            A
   4         619            A
   5         564            A
   6         534            A
   7         563            A},
  'pocket10': {'pred': 0,
   'pro_ave': 0.1015626069356534,
   'residues':   auth_seq_id auth_asym_id
   0          59            A
   1         816            A
   2          58            A
   3          62            A
   4          65            A
   5         813            A
   6         812            A},
  'pocket49': {'pred': 0,
   'pro_ave': 0.096369349808425,
   'residues':   auth_seq_id auth_asym_id
   0         856            A
   1         852            A
   2         853            A
   3         849            A
   4         204            A
   5         201            A},
  'pocket41': {'pred': 0,
   'pro_ave': 0.0916936928177328,
   'residues':   auth_seq_id auth_asym_id
   0         689            A
   1         686            A
   2         690            A
   3         693            A
   4         243            A
   5         230            A
   6         231            A
   7         232            A
   8         824            A
   9         233            A},
  'pocket4': {'pred': 0,
   'pro_ave': 0.0909573523344817,
   'residues':    auth_seq_id auth_asym_id
   0          868            A
   1          866            A
   2          128            A
   3          192            A
   4          193            A
   5          130            A
   6          867            A
   7          129            A
   8          133            A
   9          872            A
   10         134            A
   11         851            A
   12         869            A
   13         871            A},
  'pocket28': {'pred': 0,
   'pro_ave': 0.0833132183805546,
   'residues':   auth_seq_id auth_asym_id
   0         912            A
   1         911            A
   2         898            A
   3         893            A
   4         892            A
   5         908            A
   6         915            A
   7         889            A},
  'pocket31': {'pred': 0,
   'pro_ave': 0.0775529513648791,
   'residues':   auth_seq_id auth_asym_id
   0         574            A
   1         554            A
   2         555            A
   3         556            A
   4         572            A},
  'pocket29': {'pred': 0,
   'pro_ave': 0.0739604608385042,
   'residues':   auth_seq_id auth_asym_id
   0         628            A
   1         597            A
   2         627            A
   3         632            A
   4         536            A
   5         595            A
   6         630            A
   7         633            A
   8         629            A},
  'pocket17': {'pred': 0,
   'pro_ave': 0.067914218127466,
   'residues':    auth_seq_id auth_asym_id
   0          247            A
   1          520            A
   2          223            A
   3          226            A
   4          574            A
   5          245            A
   6          228            A
   7          164            A
   8          246            A
   9          227            A
   10         222            A
   11         244            A},
  'pocket48': {'pred': 0,
   'pro_ave': 0.0675220752703562,
   'residues':   auth_seq_id auth_asym_id
   0         515            A
   1         685            A
   2         683            A
   3         228            A
   4         684            A
   5         229            A
   6         517            A
   7         686            A},
  'pocket12': {'pred': 0,
   'pro_ave': 0.0670042777241036,
   'residues':   auth_seq_id auth_asym_id
   0         761            A
   1         762            A
   2         708            A
   3         707            A},
  'pocket45': {'pred': 0,
   'pro_ave': 0.061447744307997,
   'residues':   auth_seq_id auth_asym_id
   0         247            A
   1         518            A
   2         248            A
   3         514            A
   4         522            A
   5         521            A
   6         520            A
   7         512            A},
  'pocket23': {'pred': 0,
   'pro_ave': 0.0573544885410174,
   'residues':   auth_seq_id auth_asym_id
   0         745            A
   1         717            A
   2         741            A
   3         718            A
   4         744            A
   5         748            A},
  'pocket51': {'pred': 0,
   'pro_ave': 0.0571718078546414,
   'residues':   auth_seq_id auth_asym_id
   0         609            A
   1         607            A
   2         608            A
   3         596            A
   4         668            A
   5         610            A
   6         595            A
   7         628            A},
  'pocket20': {'pred': 0,
   'pro_ave': 0.0554110227241032,
   'residues':   auth_seq_id auth_asym_id
   0          77            A
   1          75            A
   2          91            A
   3          89            A
   4          76            A},
  'pocket5': {'pred': 0,
   'pro_ave': 0.0547091587296161,
   'residues':   auth_seq_id auth_asym_id
   0         377            A
   1         393            A
   2         381            A
   3         378            A
   4         382            A
   5         391            A
   6         390            A
   7         389            A
   8         383            A
   9         387            A},
  'pocket6': {'pred': 0,
   'pro_ave': 0.0513235392609814,
   'residues':   auth_seq_id auth_asym_id
   0         744            A
   1         751            A
   2         740            A
   3         718            A
   4         741            A
   5         743            A
   6         737            A
   7         747            A},
  'pocket19': {'pred': 0,
   'pro_ave': 0.0508887361152054,
   'residues':   auth_seq_id auth_asym_id
   0         529            A
   1         501            A
   2         498            A
   3         499            A
   4         530            A
   5         450            A},
  'pocket42': {'pred': 0,
   'pro_ave': 0.0508449496848455,
   'residues':   auth_seq_id auth_asym_id
   0          21            A
   1          19            A
   2          17            A
   3         798            A
   4         796            A
   5         797            A
   6         130            A
   7         792            A
   8         788            A},
  'pocket30': {'pred': 0,
   'pro_ave': 0.0487426734018541,
   'residues':   auth_seq_id auth_asym_id
   0          29            A
   1          28            A
   2          27            A
   3          46            A
   4          26            A},
  'pocket2': {'pred': 0,
   'pro_ave': 0.0475608008712661,
   'residues':    auth_seq_id auth_asym_id
   0           42            A
   1           33            A
   2           32            A
   3           18            A
   4          793            A
   5           34            A
   6           20            A
   7           29            A
   8           39            A
   9           28            A
   10         789            A
   11          46            A},
  'pocket22': {'pred': 0,
   'pro_ave': 0.0451166134051986,
   'residues':   auth_seq_id auth_asym_id
   0         408            A
   1         462            A
   2         461            A
   3         427            A
   4         426            A
   5         428            A
   6         410            A},
  'pocket24': {'pred': 0,
   'pro_ave': 0.0446849323817689,
   'residues':   auth_seq_id auth_asym_id
   0         745            A
   1         741            A
   2         746            A
   3         742            A
   4         738            A},
  'pocket9': {'pred': 0,
   'pro_ave': 0.0407928953470048,
   'residues':   auth_seq_id auth_asym_id
   0         584            A
   1         582            A
   2         583            A
   3         585            A
   4         580            A
   5         578            A},
  'pocket16': {'pred': 0,
   'pro_ave': 0.0402360525131337,
   'residues':   auth_seq_id auth_asym_id
   0         894            A
   1         163            A
   2         164            A
   3         162            A
   4         827            A},
  'pocket11': {'pred': 0,
   'pro_ave': 0.0345441281496303,
   'residues':   auth_seq_id auth_asym_id
   0         156            A
   1         157            A
   2         155            A
   3         154            A
   4         906            A
   5         909            A
   6         153            A},
  'pocket7': {'pred': 0,
   'pro_ave': 0.0343978936638829,
   'residues':   auth_seq_id auth_asym_id
   0         465            A
   1         466            A
   2         406            A
   3         464            A
   4         462            A
   5         408            A
   6         428            A
   7         407            A},
  'pocket32': {'pred': 0,
   'pro_ave': 0.0312345964340321,

In [42]:
alloses_results["7sns"]

{'pocket2_B': {'pred': 0,
  'pro_ave': 0.2164314981091613,
  'residues':    auth_seq_id auth_asym_id
  0           31            B
  1           19            B
  2           76            B
  3           28            B
  4          110            B
  5           27            B
  6           37            B
  7           38            B
  8           36            B
  9           40            B
  10          58            B
  11          92            B
  12          30            B
  13          77            B
  14          15            B
  15          12            B
  16         162            B
  17          17            B
  18          18            B
  19          29            B
  20          22            B},
 'pocket2_A': {'pred': 0,
  'pro_ave': 0.1231541995767996,
  'residues':    auth_seq_id auth_asym_id
  0           18            A
  1          162            A
  2           38            A
  3           12            A
  4           40            A
  5           30            A
  6           92            A
  7           31            A
  8           37            A
  9           58            A
  10          19            A
  11          36            A
  12          22            A
  13         110            A
  14          77            A
  15          76            A
  16          28            A},
 'pocket1_A': {'pred': 0,
  'pro_ave': 0.1192431249480838,
  'residues':    auth_seq_id auth_asym_id
  0           93            A
  1          110            A
  2          162            A
  3          153            A
  4          151            A
  5           22            A
  6           18            A
  7          161            A
  8           21            A
  9          109            A
  10         160            A},
 'pocket3_B': {'pred': 0,
  'pro_ave': 0.1171127570087619,
  'residues':   auth_seq_id auth_asym_id
  0          97            B
  1         141            B
  2         107            B
  3         139            B
  4          93            B
  5          95            B
  6         127            B
  7          54            B
  8          94            B},
 'pocket1_B': {'pred': 0,
  'pro_ave': 0.0998356152156971,
  'residues':    auth_seq_id auth_asym_id
  0           55            B
  1           94            B
  2           89            B
  3           91            B
  4           81            B
  5           77            B
  6          108            B
  7           79            B
  8           53            B
  9           43            B
  10         111            B
  11          45            B
  12          78            B},
 'pocket5_A': {'pred': 0,
  'pro_ave': 0.0884852074661268,
  'residues':   auth_seq_id auth_asym_id
  0         111            A
  1          79            A
  2          81            A
  3          77            A
  4          91            A
  5          94            A
  6          89            A
  7         108            A
  8          78            A
  9          55            A},
 'pocket10_B': {'pred': 0,
  'pro_ave': 0.0869920782392682,
  'residues':   auth_seq_id auth_asym_id
  0          -1            B
  1         143            B
  2           1            B
  3         145            B
  4         144            B
  5         142            B
  6         123            B
  7         124            B
  8         121            B},
 'pocket4_B': {'pred': 0,
  'pro_ave': 0.0847652046128382,
  'residues':   auth_seq_id auth_asym_id
  0         106            B
  1          94            B
  2          95            B
  3          96            B
  4         108            B
  5         113            B
  6         105            B
  7          98            B
  8         104            B},
 'pocket4_A': {'pred': 0,
  'pro_ave': 0.0805447432119303,
  'residues':   auth_seq_id auth_asym_id
  0         141            A
  1         139            A
  2         107            A
  3          93            A
  4          54            A
  5         127            A
  6          97            A
  7          95            A
  8          94            A
  9         114            A},
 'pocket9_B': {'pred': 0,
  'pro_ave': 0.0774223746859138,
  'residues':   auth_seq_id auth_asym_id
  0          46            B
  1          48            B
  2          49            B
  3           3            B
  4          51            B
  5           4            B
  6           2            B},
 'pocket3_A': {'pred': 0,
  'pro_ave': 0.0619438475429147,
  'residues':   auth_seq_id auth_asym_id
  0          23            A
  1          27            A
  2          26            A
  3          28            A
  4          33            A
  5          32            A
  6          20            A
  7          19            A
  8          29            A},
 'pocket5_B': {'pred': 0,
  'pro_ave': 0.0609312203882293,
  'residues':   auth_seq_id auth_asym_id
  0          76            B
  1          26            B
  2          78            B
  3          75            B
  4          27            B
  5          28            B
  6         132            B
  7         112            B
  8         110            B},
 'pocket11_B': {'pred': 0,
  'pro_ave': 0.052750701420064,
  'residues':   auth_seq_id auth_asym_id
  0         147            B
  1         168            B
  2         146            B
  3         166            B
  4         165            B
  5         148            B},
 'pocket7_B': {'pred': 0,
  'pro_ave': 0.0510847463922723,
  'residues':   auth_seq_id auth_asym_id
  0          20            B
  1          19            B
  2          23            B
  3          27            B
  4          28            B
  5          33            B
  6          29            B},
 'pocket8_A': {'pred': 0,
  'pro_ave': 0.0448789677884142,
  'residues':   auth_seq_id auth_asym_id
  0          64            A
  1          37            A
  2          61            A
  3          65            A
  4          69            A
  5          36            A
  6          38            A
  7          60            A},
 'pocket7_A': {'pred': 0,
  'pro_ave': 0.0414977242425593,
  'residues':   auth_seq_id auth_asym_id
  0         130            A
  1         115            A
  2         106            A
  3         114            A
  4         117            A
  5         129            A
  6         128            A
  7         104            A},
 'pocket8_B': {'pred': 0,
  'pro_ave': 0.0391761565636098,
  'residues':   auth_seq_id auth_asym_id
  0          74            B
  1          71            B
  2          70            B
  3          67            B
  4          80            B},
 'pocket6_A': {'pred': 0,
  'pro_ave': 0.034020350276844,
  'residues':   auth_seq_id auth_asym_id
  0          33            A
  1          76            A
  2          34            A
  3          72            A
  4          71            A
  5          68            A
  6          75            A},
 'pocket9_A': {'pred': 0,
  'pro_ave': 0.0290669791358011,
  'residues':   auth_seq_id auth_asym_id
  0         166            A
  1         165            A
  2         146            A
  3         147            A
  4         148            A},
 'pocket6_B': {'pred': 0,
  'pro_ave': 0.0281689055594201,
  'residues':   auth_seq_id auth_asym_id
  0          62            B
  1          63            B
  2          64            B
  3          65            B
  4          86            B
  5          61            B
  6          87            B}}

## MEF-AlloSite

In [43]:
import json

Top 3 pockets for each PDB are predicted positive.

In [44]:
mefallosite_resultsf = "MEF-AlloSite/mef-allosite_results.json"

with open(mefallosite_resultsf, "r") as f:
    mefallosite_results = json.load(f)

len(mefallosite_results), mefallosite_results

(9,
 {'8vw5': {'pocket15': {'prob': 0.166392813436687,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['50', '53', '54', '57', '78', '79', '82'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket10': {'prob': 0.0657426134372751,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['67',
      '68',
      '70',
      '71',
      '72',
      '74',
      '140',
      '143',
      '144',
      '147',
      '268'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket16': {'prob': 0.1929948745916287,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['69',
      '71',
      '72',
      '73',
      '76',
      '77',
      '80',
      '151',
      '289',
      '290'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket3': {'prob': 0.07908273752157886,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['104',
      '105',
      '106',
      '166',
      '169',
      '188',
      '189',
      '190',
      '191'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket2': {'prob': 0.6654382248719534,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['69',
      '70',
      '71',
      '72',
      '144',
      '148',
      '263',
      '264',
      '265',
      '266',
      '267',
      '268',
      '286',
      '288',
      '289',
      '290',
      '291',
      '294',
      '295',
      '296',
      '310',
      '312'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket6': {'prob': 0.06664851338913043,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['252',
      '257',
      '283',
      '320',
      '321',
      '324',
      '338',
      '339',
      '340',
      '341'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket12': {'prob': 0.10105580370873213,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['92', '100', '101', '104', '161', '166'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket8': {'prob': 0.2025973399480184,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['55', '59', '122', '125', '126', '129', '133'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket17': {'prob': 0.1708226107681791,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['105', '185', '186', '189', '191', '192', '193', '196'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket5': {'prob': 0.06446196014682452,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['43', '86', '89', '90', '92', '93', '98'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket13': {'prob': 0.06001520793264111,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['214', '217', '218', '221', '224'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket1': {'prob': 0.7004015247027079,
    'pred': 1,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['145',
      '148',
      '149',
      '152',
      '215',
      '218',
      '219',
      '220',
      '222',
      '224',
      '232',
      '235',
      '236',
      '239',
      '240',
      '250',
      '254',
      '255',
      '260',
      '262',
      '263',
      '287',
      '293'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket14': {'prob': 0.14767316915094852,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['209', '211', '212', '215', '250', '251', '255'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket4': {'prob': 0.08852154823640983,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['238',
      '239',
      '241',
      '293',
      '294',
      '295',
      '311',
      '312',
      '313',
      '314',
      '315',
      '316'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket9': {'prob': 0.43525440618395805,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['38',
      '112',
      '113',
      '116',
      '117',
      '193',
      '194',
      '195',
      '224',
      '225',
      '226',
      '227'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket11': {'prob': 0.23482606559991837,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['194', '195', '198', '199', '202', '203', '207'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket7': {'prob': 0.054422961082309484,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['80', '83', '84', '87', '158'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}}},
  '8sgj': {'pocket40': {'prob': 0.21772011121114096,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['709', '758', '762', '763', '767', '770', '771'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket15': {'prob': 0.2351133649547895,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['208', '209', '212', '213', '216'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket33': {'prob': 0.15540115473171076,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['44', '45', '48', '49', '52'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket21': {'prob': 0.17212234499553838,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['74',
      '75',
      '76',
      '94',
      '96',
      '224',
      '225',
      '229',
      '242',
      '576',
      '577',
      '578',
      '579'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket37': {'prob': 0.2033240950355927,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['538', '539', '540', '590', '591', '592'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket44': {'prob': 0.058638261165469885,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['595', '596', '607', '608', '609', '610', '628', '668'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket22': {'prob': 0.11587695218622684,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['889', '892', '893', '898', '908', '911', '912', '915'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket10': {'prob': 0.11892446782439947,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['913', '914', '917', '918', '921'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket24': {'prob': 0.09263415665676196,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['26', '27', '28', '29', '46'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket23': {'prob': 0.07075683834652106,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['536',
      '595',
      '597',
      '627',
      '628',
      '629',
      '630',
      '632',
      '633'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket27': {'prob': 0.13077236153185368,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['88',
      '90',
      '91',
      '92',
      '237',
      '238',
      '694',
      '695',
      '698'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket43': {'prob': 0.45789027710755664,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['72',
      '74',
      '96',
      '98',
      '100',
      '101',
      '218',
      '219',
      '223',
      '224',
      '225',
      '226'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket16': {'prob': 0.07637030072510242,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['450', '498', '499', '501', '529', '530'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket30': {'prob': 0.34949595108628273,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['21',
      '22',
      '23',
      '120',
      '123',
      '124',
      '125',
      '127',
      '128',
      '129',
      '131',
      '784',
      '788',
      '798'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket42': {'prob': 0.10297252517193556,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['201', '204', '849', '852', '853', '856'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket3': {'prob': 0.1437834563354651,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['18',
      '20',
      '28',
      '29',
      '32',
      '33',
      '34',
      '39',
      '42',
      '46',
      '789',
      '793'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket25': {'prob': 0.06592865474522114,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['554', '555', '556', '572', '574'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket2': {'prob': 0.06291313391799729,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['134',
      '137',
      '799',
      '803',
      '871',
      '872',
      '875',
      '927',
      '930',
      '931'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket29': {'prob': 0.20906834366420904,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['52', '53', '749', '750', '753', '778', '779', '782'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket6': {'prob': 0.05661559415360292,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['578', '580', '582', '583', '584', '585'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket12': {'prob': 0.19072261018057665,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['507',
      '508',
      '509',
      '512',
      '521',
      '522',
      '523',
      '524',
      '677'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket18': {'prob': 0.05953302669028441,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A'],
     'auth_seq_id': ['165', '167', '168', '221'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?']}},
   'pocket20': {'prob': 0.13048161442081133,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['47', '48', '51', '52', '55', '746'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?']}},
   'pocket45': {'prob': 0.09059256998201211,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['868', '870', '871', '930', '931', '933', '935'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket46': {'prob': 0.4881017928322156,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['415',
      '417',
      '419',
      '420',
      '421',
      '445',
      '446',
      '447',
      '448',
      '449',
      '450',
      '451',
      '452',
      '453',
      '454',
      '600',
      '601',
      '602',
      '605',
      '620',
      '621',
      '623',
      '656',
      '659',
      '660',
      '663'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket39': {'prob': 0.11614428460597992,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['194',
      '195',
      '196',
      '197',
      '198',
      '855',
      '859',
      '863',
      '864',
      '865'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket31': {'prob': 0.06508060079067945,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['81', '581', '582', '683', '688'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket36': {'prob': 0.06388768646866083,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['17',
      '19',
      '21',
      '130',
      '788',
      '792',
      '796',
      '797',
      '798'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket28': {'prob': 0.1996820867061615,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['70',
      '75',
      '91',
      '92',
      '93',
      '236',
      '237',
      '238',
      '239',
      '708',
      '760',
      '761'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket47': {'prob': 0.5807215124368668,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['62',
      '63',
      '65',
      '66',
      '69',
      '95',
      '97',
      '102',
      '105',
      '232',
      '233',
      '235',
      '236',
      '237',
      '241',
      '707',
      '708',
      '711',
      '712',
      '715',
      '716',
      '751',
      '759',
      '760',
      '761',
      '816',
      '817',
      '819',
      '820',
      '821',
      '823',
      '824',
      '830',
      '834'],
     'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?']}},
   'pocket26': {'prob': 0.1787627701026698,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['180', '181', '184', '876', '877', '880', '884'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket8': {'prob': 0.07660451189925273,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['153', '154', '155', '156', '157', '906', '909'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?']}},
   'pocket17': {'prob': 0.0626663660320143,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['75', '76', '77', '89', '91'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?']}},
   'pocket5': {'prob': 0.06268439690272014,
    'pred': 0,
    'residues': {'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['24',
      '116',
      '119',
      '120',
      '124',
      '780',
      '781',
      '784',
      '785'],
     'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?', '?']}},
   'pocket35': {'prob': 0.07405505018929641,
    'pred': 0,
    'residues': {'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['230',
      '231',
      '232',
      '233',
      '243',
      '686',
      '689',
      '690',
      '693',
      '824'],

In [45]:
mefallosite_results = {
    pdb if "af" not in pdb.lower() else pdb.upper(): {
        pocket: {
            k: v if k != "residues" else pd.DataFrame(v)
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } 
    for pdb, pockets in mefallosite_results.items()
}

mefallosite_results

{'8vw5': {'pocket15': {'prob': 0.166392813436687,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          50                 ?
   1            A          53                 ?
   2            A          54                 ?
   3            A          57                 ?
   4            A          78                 ?
   5            A          79                 ?
   6            A          82                 ?},
  'pocket10': {'prob': 0.0657426134372751,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          67                 ?
   1             A          68                 ?
   2             A          70                 ?
   3             A          71                 ?
   4             A          72                 ?
   5             A          74                 ?
   6             A         140                 ?
   7             A         143                 ?
   8             A         144                 ?
   9             A         147                 ?
   10            A         268                 ?},
  'pocket16': {'prob': 0.1929948745916287,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          69                 ?
   1            A          71                 ?
   2            A          72                 ?
   3            A          73                 ?
   4            A          76                 ?
   5            A          77                 ?
   6            A          80                 ?
   7            A         151                 ?
   8            A         289                 ?
   9            A         290                 ?},
  'pocket3': {'prob': 0.07908273752157886,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         104                 ?
   1            A         105                 ?
   2            A         106                 ?
   3            A         166                 ?
   4            A         169                 ?
   5            A         188                 ?
   6            A         189                 ?
   7            A         190                 ?
   8            A         191                 ?},
  'pocket2': {'prob': 0.6654382248719534,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          69                 ?
   1             A          70                 ?
   2             A          71                 ?
   3             A          72                 ?
   4             A         144                 ?
   5             A         148                 ?
   6             A         263                 ?
   7             A         264                 ?
   8             A         265                 ?
   9             A         266                 ?
   10            A         267                 ?
   11            A         268                 ?
   12            A         286                 ?
   13            A         288                 ?
   14            A         289                 ?
   15            A         290                 ?
   16            A         291                 ?
   17            A         294                 ?
   18            A         295                 ?
   19            A         296                 ?
   20            A         310                 ?
   21            A         312                 ?},
  'pocket6': {'prob': 0.06664851338913043,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         252                 ?
   1            A         257                 ?
   2            A         283                 ?
   3            A         320                 ?
   4            A         321                 ?
   5            A         324                 ?
   6            A         338                 ?
   7            A         339                 ?
   8            A         340                 ?
   9            A         341                 ?},
  'pocket12': {'prob': 0.10105580370873213,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          92                 ?
   1            A         100                 ?
   2            A         101                 ?
   3            A         104                 ?
   4            A         161                 ?
   5            A         166                 ?},
  'pocket8': {'prob': 0.2025973399480184,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          55                 ?
   1            A          59                 ?
   2            A         122                 ?
   3            A         125                 ?
   4            A         126                 ?
   5            A         129                 ?
   6            A         133                 ?},
  'pocket17': {'prob': 0.1708226107681791,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         105                 ?
   1            A         185                 ?
   2            A         186                 ?
   3            A         189                 ?
   4            A         191                 ?
   5            A         192                 ?
   6            A         193                 ?
   7            A         196                 ?},
  'pocket5': {'prob': 0.06446196014682452,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          43                 ?
   1            A          86                 ?
   2            A          89                 ?
   3            A          90                 ?
   4            A          92                 ?
   5            A          93                 ?
   6            A          98                 ?},
  'pocket13': {'prob': 0.06001520793264111,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         214                 ?
   1            A         217                 ?
   2            A         218                 ?
   3            A         221                 ?
   4            A         224                 ?},
  'pocket1': {'prob': 0.7004015247027079,
   'pred': 1,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         145                 ?
   1             A         148                 ?
   2             A         149                 ?
   3             A         152                 ?
   4             A         215                 ?
   5             A         218                 ?
   6             A         219                 ?
   7             A         220                 ?
   8             A         222                 ?
   9             A         224                 ?
   10            A         232                 ?
   11            A         235                 ?
   12            A         236                 ?
   13            A         239                 ?
   14            A         240                 ?
   15            A         250                 ?
   16            A         254                 ?
   17            A         255                 ?
   18            A         260                 ?
   19            A         262                 ?
   20            A         263                 ?
   21            A         287                 ?
   22            A         293                 ?},
  'pocket14': {'prob': 0.14767316915094852,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         209                 ?
   1            A         211                 ?
   2            A         212                 ?
   3            A         215                 ?
   4            A         250                 ?
   5            A         251                 ?
   6            A         255                 ?},
  'pocket4': {'prob': 0.08852154823640983,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A         238                 ?
   1             A         239                 ?
   2             A         241                 ?
   3             A         293                 ?
   4             A         294                 ?
   5             A         295                 ?
   6             A         311                 ?
   7             A         312                 ?
   8             A         313                 ?
   9             A         314                 ?
   10            A         315                 ?
   11            A         316                 ?},
  'pocket9': {'prob': 0.43525440618395805,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          38                 ?
   1             A         112                 ?
   2             A         113                 ?
   3             A         116                 ?
   4             A         117                 ?
   5             A         193                 ?
   6             A         194                 ?
   7             A         195                 ?
   8             A         224                 ?
   9             A         225                 ?
   10            A         226                 ?
   11            A         227                 ?},
  'pocket11': {'prob': 0.23482606559991837,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         194                 ?
   1            A         195                 ?
   2            A         198                 ?
   3            A         199                 ?
   4            A         202                 ?
   5            A         203                 ?
   6            A         207                 ?},
  'pocket7': {'prob': 0.054422961082309484,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          80                 ?
   1            A          83                 ?
   2            A          84                 ?
   3            A          87                 ?
   4            A         158                 ?}},
 '8sgj': {'pocket40': {'prob': 0.21772011121114096,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         709                 ?
   1            A         758                 ?
   2            A         762                 ?
   3            A         763                 ?
   4            A         767                 ?
   5            A         770                 ?
   6            A         771                 ?},
  'pocket15': {'prob': 0.2351133649547895,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         208                 ?
   1            A         209                 ?
   2            A         212                 ?
   3            A         213                 ?
   4            A         216                 ?},
  'pocket33': {'prob': 0.15540115473171076,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          44                 ?
   1            A          45                 ?
   2            A          48                 ?
   3            A          49                 ?
   4            A          52                 ?},
  'pocket21': {'prob': 0.17212234499553838,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          74                 ?
   1             A          75                 ?
   2             A          76                 ?
   3             A          94                 ?
   4             A          96                 ?
   5             A         224                 ?
   6             A         225                 ?
   7             A         229                 ?
   8             A         242                 ?
   9             A         576                 ?
   10            A         577                 ?
   11            A         578                 ?
   12            A         579                 ?},
  'pocket37': {'prob': 0.2033240950355927,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         538                 ?
   1            A         539                 ?
   2            A         540                 ?
   3            A         590                 ?
   4            A         591                 ?
   5            A         592                 ?},
  'pocket44': {'prob': 0.058638261165469885,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         595                 ?
   1            A         596                 ?
   2            A         607                 ?
   3            A         608                 ?
   4            A         609                 ?
   5            A         610                 ?
   6            A         628                 ?
   7            A         668                 ?},
  'pocket22': {'prob': 0.11587695218622684,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         889                 ?
   1            A         892                 ?
   2            A         893                 ?
   3            A         898                 ?
   4            A         908                 ?
   5            A         911                 ?
   6            A         912                 ?
   7            A         915                 ?},
  'pocket10': {'prob': 0.11892446782439947,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         913                 ?
   1            A         914                 ?
   2            A         917                 ?
   3            A         918                 ?
   4            A         921                 ?},
  'pocket24': {'prob': 0.09263415665676196,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          26                 ?
   1            A          27                 ?
   2            A          28                 ?
   3            A          29                 ?
   4            A          46                 ?},
  'pocket23': {'prob': 0.07075683834652106,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         536                 ?
   1            A         595                 ?
   2            A         597                 ?
   3            A         627                 ?
   4            A         628                 ?
   5            A         629                 ?
   6            A         630                 ?
   7            A         632                 ?
   8            A         633                 ?},
  'pocket27': {'prob': 0.13077236153185368,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          88                 ?
   1            A          90                 ?
   2            A          91                 ?
   3            A          92                 ?
   4            A         237                 ?
   5            A         238                 ?
   6            A         694                 ?
   7            A         695                 ?
   8            A         698                 ?},
  'pocket43': {'prob': 0.45789027710755664,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          72                 ?
   1             A          74                 ?
   2             A          96                 ?
   3             A          98                 ?
   4             A         100                 ?
   5             A         101                 ?
   6             A         218                 ?
   7             A         219                 ?
   8             A         223                 ?
   9             A         224                 ?
   10            A         225                 ?
   11            A         226                 ?},
  'pocket16': {'prob': 0.07637030072510242,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         450                 ?
   1            A         498                 ?
   2            A         499                 ?
   3            A         501                 ?
   4            A         529                 ?
   5            A         530                 ?},
  'pocket30': {'prob': 0.34949595108628273,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          21                 ?
   1             A          22                 ?
   2             A          23                 ?
   3             A         120                 ?
   4             A         123                 ?
   5             A         124                 ?
   6             A         125                 ?
   7             A         127                 ?
   8             A         128                 ?
   9             A         129                 ?
   10            A         131                 ?
   11            A         784                 ?
   12            A         788                 ?
   13            A         798                 ?},
  'pocket42': {'prob': 0.10297252517193556,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         201                 ?
   1            A         204                 ?
   2            A         849                 ?
   3            A         852                 ?
   4            A         853                 ?
   5            A         856                 ?},
  'pocket3': {'prob': 0.1437834563354651,
   'pred': 0,
   'residues':    auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0             A          18                 ?
   1             A          20                 ?
   2             A          28                 ?
   3             A          29                 ?
   4             A          32                 ?
   5             A          33                 ?
   6             A          34                 ?
   7             A          39                 ?
   8             A          42                 ?
   9             A          46                 ?
   10            A         789                 ?
   11            A         793                 ?},
  'pocket25': {'prob': 0.06592865474522114,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         554                 ?
   1            A         555                 ?
   2            A         556                 ?
   3            A         572                 ?
   4            A         574                 ?},
  'pocket2': {'prob': 0.06291313391799729,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A         134                 ?
   1            A         137                 ?
   2            A         799                 ?
   3            A         803                 ?
   4            A         871                 ?
   5            A         872                 ?
   6            A         875                 ?
   7            A         927                 ?
   8            A         930                 ?
   9            A         931                 ?},
  'pocket29': {'prob': 0.20906834366420904,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code
   0            A          52                 ?
   1            A          53                 ?
   2            A         749                 ?
   3            A         750                 ?
   4            A         753                 ?
   5            A         778                 ?
   6            A         779                 ?
   7            A         782                 ?},
  'pocket6': {'prob': 0.05661559415360292,
   'pred': 0,
   'residues':   auth_asym_id auth_seq_id pdbx_PDB_ins_code

## ALLO

Top pocket is taken as positive prediction.

In [46]:
allo_resultsf = "ALLO/ALLO_results.json"

with open(allo_resultsf, "r") as f:
    allo_results = json.load(f)

len(allo_results), allo_results

(9,
 {'7xlq': {'P_29': {'pred': 0,
    'prob': 0.025810000000000003,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['128',
      '132',
      '166',
      '167',
      '170',
      '171',
      '174',
      '175',
      '189',
      '190',
      '192',
      '193',
      '196']}},
   'P_28': {'pred': 0,
    'prob': 0.025830000000000002,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1160',
      '1163',
      '1164',
      '1167',
      '1168',
      '1264',
      '1265',
      '1268',
      '1612',
      '1615',
      '1616',
      '1619']}},
   'P_21': {'pred': 0,
    'prob': 0.025910000000000002,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['781',
      '1442',
      '1443',
      '1446',
      '1727',
      '1730',
      '1731',
      '1732',
      '1733',
      '1735',
      '1736',
      '1737',
      '1738',
      '1739',
      '1740']}},
   'P_20': {'pred': 0,
    'prob': 0.025960000000000004,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['358',
      '359',
      '364',
      '371',
      '707',
      '710',
      '711',
      '714',
      '715',
      '775',
      '778',
      '779',
      '782',
      '783',
      '786']}},
   'P_23': {'pred': 0,
    'prob': 0.02586,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['106',
      '109',
      '110',
      '111',
      '112',
      '116',
      '117',
      '118',
      '121',
      '193',
      '194',
      '619',
      '622',
      '623']}},
   'P_22': {'pred': 0,
    'prob': 0.02585,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['308',
      '309',
      '310',
      '657',
      '658',
      '660',
      '1370',
      '1372',
      '1373',
      '1376',
      '1661',
      '1662',
      '1663',
      '1664',
      '1666',
      '1667']}},
   'P_25': {'pred': 0,
    'prob': 0.02576,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['218',
      '221',
      '222',
      '224',
      '225',
      '228',
      '342',
      '346',
      '688',
      '689',
      '692']}},
   'P_24': {'pred': 0,
    'prob': 0.02661,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1744',
      '1747',
      '1748',
      '1751',
      '1752',
      '1756',
      '1757',
      '1759',
      '1763',
      '1764',
      '1767',
      '1768',
      '1771',
      '1790',
      '1793',
      '1795',
      '1803',
      '1808',
      '1812',
      '1865']}},
   'P_27': {'pred': 0,
    'prob': 0.02584,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['100',
      '103',
      '106',
      '107',
      '197',
      '200',
      '608',
      '611',
      '612',
      '615',
      '619',
      '643']}},
   'P_26': {'pred': 0,
    'prob': 0.02593,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1281',
      '1284',
      '1285',
      '1288',
      '1421',
      '1422',
      '1425',
      '1426',
      '1427',
      '1428',
      '1429',
      '1716']}},
   'P_49': {'pred': 0,
    'prob': 0.02578,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1310', '1398', '1399', '1401', '1402']}},
   'P_48': {'pred': 0,
    'prob': 0.025639999999999996,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1459', '1532', '1536', '1537', '1539', '1540', '1543']}},
   'P_47': {'pred': 0,
    'prob': 0.025730000000000003,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1784', '1787', '1788', '1791', '1866', '1869', '1870']}},
   'P_46': {'pred': 0,
    'prob': 0.02559,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1274',
      '1277',
      '1278',
      '1429',
      '1606',
      '1607',
      '1608',
      '1609',
      '1610']}},
   'P_45': {'pred': 0,
    'prob': 0.0256,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1632',
      '1633',
      '1634',
      '1635',
      '1638',
      '1640',
      '1671',
      '1676',
      '1677']}},
   'P_44': {'pred': 0,
    'prob': 0.025519999999999998,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1511',
      '1514',
      '1515',
      '1553',
      '1556',
      '1557',
      '1560',
      '1579']}},
   'P_43': {'pred': 0,
    'prob': 0.025789999999999997,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['617',
      '620',
      '624',
      '678',
      '679',
      '680',
      '681',
      '682',
      '685']}},
   'P_42': {'pred': 0,
    'prob': 0.025910000000000002,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1768',
      '1773',
      '1774',
      '1775',
      '1776',
      '1777',
      '1786',
      '1787',
      '1789',
      '1790',
      '1793']}},
   'P_41': {'pred': 0,
    'prob': 0.02576,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['596',
      '600',
      '603',
      '607',
      '698',
      '701',
      '1408',
      '1413']}},
   'P_40': {'pred': 0,
    'prob': 0.02585,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1278',
      '1281',
      '1282',
      '1426',
      '1429',
      '1610',
      '1613',
      '1614',
      '1713',
      '1716',
      '1717',
      '1720']}},
   'P_38': {'pred': 0,
    'prob': 0.02556,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['356',
      '359',
      '360',
      '785',
      '788',
      '1732',
      '1734',
      '1735']}},
   'P_39': {'pred': 0,
    'prob': 0.02567,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1454',
      '1455',
      '1456',
      '1458',
      '1748',
      '1752',
      '1754',
      '1755',
      '1757',
      '1805']}},
   'P_36': {'pred': 0,
    'prob': 0.02586,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['227',
      '230',
      '231',
      '337',
      '1584',
      '1587',
      '1593',
      '1597']}},
   'P_37': {'pred': 0,
    'prob': 0.02597,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['777',
      '1426',
      '1427',
      '1428',
      '1429',
      '1607',
      '1720',
      '1723',
      '1724']}},
   'P_10': {'pred': 0,
    'prob': 0.02885,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1481',
      '1484',
      '1485',
      '1488',
      '1518',
      '1521',
      '1522',
      '1524',
      '1525',
      '1528',
      '1537',
      '1542',
      '1543',
      '1546',
      '1547',
      '1549',
      '1550',
      '1553',
      '1582',
      '1585',
      '1588',
      '1589']}},
   'P_11': {'pred': 0,
    'prob': 0.02657,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['241',
      '1487',
      '1488',
      '1491',
      '1492',
      '1494',
      '1495',
      '1497',
      '1498',
      '1499',
      '1502',
      '1506',
      '1507',
      '1510',
      '1514',
      '1517',
      '1521',
      '1579',
      '1582',
      '1583',
      '1585',
      '1586']}},
   'P_12': {'pred': 0,
    'prob': 0.0269,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['92',
      '95',
      '96',
      '99',
      '135',
      '138',
      '139',
      '142',
      '155',
      '161',
      '164',
      '165',
      '167',
      '168',
      '199',
      '202',
      '203']}},
   'P_13': {'pred': 0,
    'prob': 0.0262,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1170',
      '1173',
      '1174',
      '1175',
      '1178',
      '1183',
      '1187',
      '1254',
      '1255',
      '1258',
      '1259',
      '1261',
      '1626',
      '1627',
      '1630',
      '1631']}},
   'P_14': {'pred': 0,
    'prob': 0.02599,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['229',
      '232',
      '296',
      '297',
      '299',
      '300',
      '303',
      '677',
      '678',
      '680',
      '681',
      '684',
      '688']}},
   'P_15': {'pred': 0,
    'prob': 0.02584,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['262',
      '264',
      '265',
      '266',
      '267',
      '282',
      '285',
      '286',
      '312',
      '313',
      '316',
      '317',
      '320',
      '1636',
      '1641',
      '1642',
      '1643']}},
   'P_16': {'pred': 0,
    'prob': 0.02635,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1187',
      '1190',
      '1191',
      '1193',
      '1194',
      '1197',
      '1228',
      '1229',
      '1230',
      '1232',
      '1233',
      '1236',
      '1237',
      '1240',
      '1241',
      '1254',
      '1257',
      '1258',
      '1260',
      '1261',
      '1264',
      '1267']}},
   'P_17': {'pred': 0,
    'prob': 0.02582,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1175',
      '1176',
      '1178',
      '1255',
      '1631',
      '1677',
      '1678',
      '1679',
      '1680',
      '1681',
      '1684',
      '1686',
      '1687',
      '1688',
      '1690',
      '1691',
      '1692',
      '1694']}},
   'P_18': {'pred': 0,
    'prob': 0.026019999999999998,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1266',
      '1269',
      '1279',
      '1282',
      '1283',
      '1286',
      '1613',
      '1616',
      '1617',
      '1620',
      '1708',
      '1709',
      '1712',
      '1713']}},
   'P_19': {'pred': 0,
    'prob': 0.02661,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['585',
      '588',
      '589',
      '592',
      '706',
      '709',
      '710',
      '713',
      '1288',
      '1291',
      '1292',
      '1421',
      '1424',
      '1425']}},
   'P_34': {'pred': 0,
    'prob': 0.0256,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['76',
      '77',
      '79',
      '81',
      '84',
      '143',
      '144',
      '145',
      '146',
      '147',
      '148',
      '150',
      '151',
      '153']}},
   'P_35': {'pred': 0,
    'prob': 0.02582,
    'residues': {'pdbx_PDB_ins_code': ['?', '?', '?', '?', '?', '?', '?', '?'],
     'auth_asym_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
     'auth_seq_id': ['1621',
      '1624',
      '1628',
      '1629',
      '1698',
      '1701',
      '1702',
      '1705']}},
   'P_32': {'pred': 0,
    'prob': 0.02585,
    'residues': {'pdbx_PDB_ins_code': ['?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?',
      '?'],
     'auth_asym_id': ['A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A',
      'A'],
     'auth_seq_id': ['1315',
      '1351',
      '1352',
      '1353',
      '1355',
      '1367',
      '1372',
      '1373',
      '1376',
      '1377',
      '1380',
      '1666',

In [47]:
allo_results = {
    pdb: {
        pocket: {
            k: v if k != "residues" else pd.DataFrame(v)
            for k, v in pocketd.items()
        }
        for pocket, pocketd in pockets.items()
    } 
    for pdb, pockets in allo_results.items()
}

allo_results

{'7xlq': {'P_29': {'pred': 0,
   'prob': 0.025810000000000003,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         128
   1                  ?            A         132
   2                  ?            A         166
   3                  ?            A         167
   4                  ?            A         170
   5                  ?            A         171
   6                  ?            A         174
   7                  ?            A         175
   8                  ?            A         189
   9                  ?            A         190
   10                 ?            A         192
   11                 ?            A         193
   12                 ?            A         196},
  'P_28': {'pred': 0,
   'prob': 0.025830000000000002,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1160
   1                  ?            A        1163
   2                  ?            A        1164
   3                  ?            A        1167
   4                  ?            A        1168
   5                  ?            A        1264
   6                  ?            A        1265
   7                  ?            A        1268
   8                  ?            A        1612
   9                  ?            A        1615
   10                 ?            A        1616
   11                 ?            A        1619},
  'P_21': {'pred': 0,
   'prob': 0.025910000000000002,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         781
   1                  ?            A        1442
   2                  ?            A        1443
   3                  ?            A        1446
   4                  ?            A        1727
   5                  ?            A        1730
   6                  ?            A        1731
   7                  ?            A        1732
   8                  ?            A        1733
   9                  ?            A        1735
   10                 ?            A        1736
   11                 ?            A        1737
   12                 ?            A        1738
   13                 ?            A        1739
   14                 ?            A        1740},
  'P_20': {'pred': 0,
   'prob': 0.025960000000000004,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         358
   1                  ?            A         359
   2                  ?            A         364
   3                  ?            A         371
   4                  ?            A         707
   5                  ?            A         710
   6                  ?            A         711
   7                  ?            A         714
   8                  ?            A         715
   9                  ?            A         775
   10                 ?            A         778
   11                 ?            A         779
   12                 ?            A         782
   13                 ?            A         783
   14                 ?            A         786},
  'P_23': {'pred': 0,
   'prob': 0.02586,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         106
   1                  ?            A         109
   2                  ?            A         110
   3                  ?            A         111
   4                  ?            A         112
   5                  ?            A         116
   6                  ?            A         117
   7                  ?            A         118
   8                  ?            A         121
   9                  ?            A         193
   10                 ?            A         194
   11                 ?            A         619
   12                 ?            A         622
   13                 ?            A         623},
  'P_22': {'pred': 0,
   'prob': 0.02585,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         308
   1                  ?            A         309
   2                  ?            A         310
   3                  ?            A         657
   4                  ?            A         658
   5                  ?            A         660
   6                  ?            A        1370
   7                  ?            A        1372
   8                  ?            A        1373
   9                  ?            A        1376
   10                 ?            A        1661
   11                 ?            A        1662
   12                 ?            A        1663
   13                 ?            A        1664
   14                 ?            A        1666
   15                 ?            A        1667},
  'P_25': {'pred': 0,
   'prob': 0.02576,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         218
   1                  ?            A         221
   2                  ?            A         222
   3                  ?            A         224
   4                  ?            A         225
   5                  ?            A         228
   6                  ?            A         342
   7                  ?            A         346
   8                  ?            A         688
   9                  ?            A         689
   10                 ?            A         692},
  'P_24': {'pred': 0,
   'prob': 0.02661,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1744
   1                  ?            A        1747
   2                  ?            A        1748
   3                  ?            A        1751
   4                  ?            A        1752
   5                  ?            A        1756
   6                  ?            A        1757
   7                  ?            A        1759
   8                  ?            A        1763
   9                  ?            A        1764
   10                 ?            A        1767
   11                 ?            A        1768
   12                 ?            A        1771
   13                 ?            A        1790
   14                 ?            A        1793
   15                 ?            A        1795
   16                 ?            A        1803
   17                 ?            A        1808
   18                 ?            A        1812
   19                 ?            A        1865},
  'P_27': {'pred': 0,
   'prob': 0.02584,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         100
   1                  ?            A         103
   2                  ?            A         106
   3                  ?            A         107
   4                  ?            A         197
   5                  ?            A         200
   6                  ?            A         608
   7                  ?            A         611
   8                  ?            A         612
   9                  ?            A         615
   10                 ?            A         619
   11                 ?            A         643},
  'P_26': {'pred': 0,
   'prob': 0.02593,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1281
   1                  ?            A        1284
   2                  ?            A        1285
   3                  ?            A        1288
   4                  ?            A        1421
   5                  ?            A        1422
   6                  ?            A        1425
   7                  ?            A        1426
   8                  ?            A        1427
   9                  ?            A        1428
   10                 ?            A        1429
   11                 ?            A        1716},
  'P_49': {'pred': 0,
   'prob': 0.02578,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1310
   1                 ?            A        1398
   2                 ?            A        1399
   3                 ?            A        1401
   4                 ?            A        1402},
  'P_48': {'pred': 0,
   'prob': 0.025639999999999996,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1459
   1                 ?            A        1532
   2                 ?            A        1536
   3                 ?            A        1537
   4                 ?            A        1539
   5                 ?            A        1540
   6                 ?            A        1543},
  'P_47': {'pred': 0,
   'prob': 0.025730000000000003,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1784
   1                 ?            A        1787
   2                 ?            A        1788
   3                 ?            A        1791
   4                 ?            A        1866
   5                 ?            A        1869
   6                 ?            A        1870},
  'P_46': {'pred': 0,
   'prob': 0.02559,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1274
   1                 ?            A        1277
   2                 ?            A        1278
   3                 ?            A        1429
   4                 ?            A        1606
   5                 ?            A        1607
   6                 ?            A        1608
   7                 ?            A        1609
   8                 ?            A        1610},
  'P_45': {'pred': 0,
   'prob': 0.0256,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1632
   1                 ?            A        1633
   2                 ?            A        1634
   3                 ?            A        1635
   4                 ?            A        1638
   5                 ?            A        1640
   6                 ?            A        1671
   7                 ?            A        1676
   8                 ?            A        1677},
  'P_44': {'pred': 0,
   'prob': 0.025519999999999998,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1511
   1                 ?            A        1514
   2                 ?            A        1515
   3                 ?            A        1553
   4                 ?            A        1556
   5                 ?            A        1557
   6                 ?            A        1560
   7                 ?            A        1579},
  'P_43': {'pred': 0,
   'prob': 0.025789999999999997,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         617
   1                 ?            A         620
   2                 ?            A         624
   3                 ?            A         678
   4                 ?            A         679
   5                 ?            A         680
   6                 ?            A         681
   7                 ?            A         682
   8                 ?            A         685},
  'P_42': {'pred': 0,
   'prob': 0.025910000000000002,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1768
   1                  ?            A        1773
   2                  ?            A        1774
   3                  ?            A        1775
   4                  ?            A        1776
   5                  ?            A        1777
   6                  ?            A        1786
   7                  ?            A        1787
   8                  ?            A        1789
   9                  ?            A        1790
   10                 ?            A        1793},
  'P_41': {'pred': 0,
   'prob': 0.02576,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         596
   1                 ?            A         600
   2                 ?            A         603
   3                 ?            A         607
   4                 ?            A         698
   5                 ?            A         701
   6                 ?            A        1408
   7                 ?            A        1413},
  'P_40': {'pred': 0,
   'prob': 0.02585,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1278
   1                  ?            A        1281
   2                  ?            A        1282
   3                  ?            A        1426
   4                  ?            A        1429
   5                  ?            A        1610
   6                  ?            A        1613
   7                  ?            A        1614
   8                  ?            A        1713
   9                  ?            A        1716
   10                 ?            A        1717
   11                 ?            A        1720},
  'P_38': {'pred': 0,
   'prob': 0.02556,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         356
   1                 ?            A         359
   2                 ?            A         360
   3                 ?            A         785
   4                 ?            A         788
   5                 ?            A        1732
   6                 ?            A        1734
   7                 ?            A        1735},
  'P_39': {'pred': 0,
   'prob': 0.02567,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A        1454
   1                 ?            A        1455
   2                 ?            A        1456
   3                 ?            A        1458
   4                 ?            A        1748
   5                 ?            A        1752
   6                 ?            A        1754
   7                 ?            A        1755
   8                 ?            A        1757
   9                 ?            A        1805},
  'P_36': {'pred': 0,
   'prob': 0.02586,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         227
   1                 ?            A         230
   2                 ?            A         231
   3                 ?            A         337
   4                 ?            A        1584
   5                 ?            A        1587
   6                 ?            A        1593
   7                 ?            A        1597},
  'P_37': {'pred': 0,
   'prob': 0.02597,
   'residues':   pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                 ?            A         777
   1                 ?            A        1426
   2                 ?            A        1427
   3                 ?            A        1428
   4                 ?            A        1429
   5                 ?            A        1607
   6                 ?            A        1720
   7                 ?            A        1723
   8                 ?            A        1724},
  'P_10': {'pred': 0,
   'prob': 0.02885,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1481
   1                  ?            A        1484
   2                  ?            A        1485
   3                  ?            A        1488
   4                  ?            A        1518
   5                  ?            A        1521
   6                  ?            A        1522
   7                  ?            A        1524
   8                  ?            A        1525
   9                  ?            A        1528
   10                 ?            A        1537
   11                 ?            A        1542
   12                 ?            A        1543
   13                 ?            A        1546
   14                 ?            A        1547
   15                 ?            A        1549
   16                 ?            A        1550
   17                 ?            A        1553
   18                 ?            A        1582
   19                 ?            A        1585
   20                 ?            A        1588
   21                 ?            A        1589},
  'P_11': {'pred': 0,
   'prob': 0.02657,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         241
   1                  ?            A        1487
   2                  ?            A        1488
   3                  ?            A        1491
   4                  ?            A        1492
   5                  ?            A        1494
   6                  ?            A        1495
   7                  ?            A        1497
   8                  ?            A        1498
   9                  ?            A        1499
   10                 ?            A        1502
   11                 ?            A        1506
   12                 ?            A        1507
   13                 ?            A        1510
   14                 ?            A        1514
   15                 ?            A        1517
   16                 ?            A        1521
   17                 ?            A        1579
   18                 ?            A        1582
   19                 ?            A        1583
   20                 ?            A        1585
   21                 ?            A        1586},
  'P_12': {'pred': 0,
   'prob': 0.0269,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A          92
   1                  ?            A          95
   2                  ?            A          96
   3                  ?            A          99
   4                  ?            A         135
   5                  ?            A         138
   6                  ?            A         139
   7                  ?            A         142
   8                  ?            A         155
   9                  ?            A         161
   10                 ?            A         164
   11                 ?            A         165
   12                 ?            A         167
   13                 ?            A         168
   14                 ?            A         199
   15                 ?            A         202
   16                 ?            A         203},
  'P_13': {'pred': 0,
   'prob': 0.0262,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A        1170
   1                  ?            A        1173
   2                  ?            A        1174
   3                  ?            A        1175
   4                  ?            A        1178
   5                  ?            A        1183
   6                  ?            A        1187
   7                  ?            A        1254
   8                  ?            A        1255
   9                  ?            A        1258
   10                 ?            A        1259
   11                 ?            A        1261
   12                 ?            A        1626
   13                 ?            A        1627
   14                 ?            A        1630
   15                 ?            A        1631},
  'P_14': {'pred': 0,
   'prob': 0.02599,
   'residues':    pdbx_PDB_ins_code auth_asym_id auth_seq_id
   0                  ?            A         229
   1                  ?            A         232
   2                  ?            A         296
   3                  ?            A         297
   4                  ?            A         299
   5                  ?            A         300
   6                  ?            A         303
   7                  ?            A         677

## All models

In [48]:
defaults = { "all_pockets_in_output": True, "prob_key": "prob" }

models = {
    "model5": { "results": model5_results, **defaults, "labelling": None },
    
    "allositepro": { "results": allositepro_results, "all_pockets_in_output": False, "prob_key": "hitScore" },
    "stingallo": { "results": stingallo_results, "all_pockets_in_output": False, "prob_key": None },
    "allofusion": { "results": allofusion_results, "all_pockets_in_output": False, "prob_key": None },
    
    "passer_ensemble": { "results": passer_results["ensemble"], **defaults, "prob_key": "prob/score" },
    "passer_automl": { "results": passer_results["automl"], **defaults, "prob_key": "prob/score" },
    "passer_rank": { "results": passer_results["rank"], **defaults, "prob_key": "prob/score" },
    "deepallo": { "results": deepallo_results, **defaults },
    "alloses": { "results": alloses_results, **defaults, "prob_key": "pro_ave" },
    "mefallosite": { "results": mefallosite_results, **defaults },
    "allo": { "results": allo_results, **defaults },
}
models

{'model5': {'results': {'4jqi': {'pocket16': {'prob': 0.0001226096646860242,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket18': {'prob': 0.003527346532791853,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket11': {'prob': 4.818243542104028e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket15': {'prob': 1.1008408629109567e-09,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 0.0006957116420380771,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket13': {'prob': 0.09678139537572861,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket14': {'prob': 1.2360335688299529e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.48696210980415344,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.1,
     'pocket_in_site': 0.01694915254237288,
     'site_in_pocket': 0.1},
    'pocket2': {'prob': 0.04993942379951477,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket4': {'prob': 0.0003950250393245369,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket17': {'prob': 0.013226842507719994,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.3,
     'pocket_in_site': 0.125,
     'site_in_pocket': 0.3},
    'pocket9': {'prob': 1.895525747386273e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket10': {'prob': 0.00015777153021190315,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.0011327075771987438,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.1,
     'pocket_in_site': 0.1,
     'site_in_pocket': 0.1},
    'pocket8': {'prob': 5.881764991499949e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.2,
     'pocket_in_site': 0.14285714285714285,
     'site_in_pocket': 0.2},
    'pocket3': {'prob': 0.0005942771094851196,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket12': {'prob': 3.218316635411611e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket19': {'prob': 6.801011477364227e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 0.002429150976240635,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '5uak': {'pocket16': {'prob': 3.0019442419870757e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.1,
     'pocket_in_site': 0.1,
     'site_in_pocket': 0.037037037037037035},
    'pocket28': {'prob': 0.00038587115705013275,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket74': {'prob': 0.083624929189682,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.037037037037037035,
     'pocket_in_site': 0.025,
     'site_in_pocket': 0.037037037037037035},
    'pocket18': {'prob': 1.94397107406985e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket11': {'prob': 4.243553485139273e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket34': {'prob': 3.98365642695353e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket49': {'prob': 0.000820803688839078,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket75': {'prob': 0.1360320746898651,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket72': {'prob': 2.265783116683906e-08,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket64': {'prob': 6.354485230986029e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket25': {'prob': 0.002951409900560975,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket60': {'prob': 4.296440238249488e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket15': {'prob': 0.08613934367895126,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket40': {'prob': 9.83518566499697e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 0.17062930762767792,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket65': {'prob': 6.698257948301034e-08,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket22': {'prob': 0.0006872391095384955,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket13': {'prob': 0.00047426376841031015,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket31': {'prob': 0.00034840204170905054,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket39': {'prob': 0.00022040517069399357,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket23': {'prob': 0.0005286466330289841,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket14': {'prob': 0.0009157537715509534,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket59': {'prob': 0.006774789188057184,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket70': {'prob': 4.0977141907205805e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket26': {'prob': 0.012044261209666729,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.9867374300956726,
     'pred': 1,
     'label': 1,
     'max_overlap': 0.9629629629629629,
     'pocket_in_site': 0.13978494623655913,
     'site_in_pocket': 0.9629629629629629},
    'pocket46': {'prob': 0.0014091776683926582,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket69': {'prob': 3.480364102870226e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket58': {'prob': 0.00036729127168655396,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket27': {'prob': 0.0027211715932935476,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket44': {'prob': 0.0001502553204772994,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket2': {'prob': 0.9017921090126038,
     'pred': 1,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket32': {'prob': 0.0009325698483735323,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket20': {'prob': 0.00014424252731259912,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket4': {'prob': 0.047339797019958496,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket29': {'prob': 0.28048035502433777,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket67': {'prob': 0.0001530459412606433,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket30': {'prob': 8.970695489551872e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket61': {'prob': 2.23932001972571e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket17': {'prob': 2.677696102182381e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket9': {'prob': 4.362659183243522e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket10': {'prob': 8.874721402207797e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.07142857142857142,
     'pocket_in_site': 0.07142857142857142,
     'site_in_pocket': 0.037037037037037035},
    'pocket35': {'prob': 2.144993959518615e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket5': {'prob': 0.30562925338745117,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket66': {'prob': 0.0008130857022479177,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket47': {'prob': 1.7490343452664092e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket73': {'prob': 0.0006872479571029544,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket8': {'prob': 0.0010288351913914084,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket43': {'prob': 0.00046817478141747415,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket37': {'prob': 0.0004792721301782876,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket57': {'prob': 0.004534082021564245,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket54': {'prob': 0.0006482342723757029,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket51': {'prob': 9.815461817197502e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket53': {'prob': 0.00018505097250454128,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket24': {'prob': 0.0015840076375752687,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket56': {'prob': 1.9594939559830493e-10,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 0.0075988504104316235,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket45': {'prob': 0.00030932205845601857,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket12': {'prob': 0.13124743103981018,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket50': {'prob': 1.5748948953842046e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket71': {'prob': 0.0027146341744810343,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket68': {'prob': 3.193134398316033e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket48': {'prob': 3.3817927942436654e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket38': {'prob': 0.0012789833126589656,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket52': {'prob': 9.871517977444455e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket62': {'prob': 9.985836868509068e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket42': {'prob': 2.7387670343159698e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket19': {'prob': 0.0002437986695440486,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket21': {'prob': 0.0006895983824506402,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket55': {'prob': 0.0010643895948305726,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket33': {'prob': 9.092727850656956e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket36': {'prob': 0.003312306012958288,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.08333333333333333,
     'pocket_in_site': 0.08333333333333333,
     'site_in_pocket': 0.07407407407407407},
    'pocket63': {'prob': 0.00010547602141741663,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket41': {'prob': 0.0003279552038293332,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 0.7475950121879578,
     'pred': 1,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '6yhr': {'pocket16': {'prob': 0.000840068852994591,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.05,
     'pocket_in_site': 0.05,
     'site_in_pocket': 0.034482758620689655},
    'pocket18': {'prob': 2.988547009863396e-08,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket11': {'prob': 8.406837878283113e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket15': {'prob': 1.2131650350966083e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 5.069195481155475e-07,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket13': {'prob': 0.00022405335039366037,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket14': {'prob': 0.0012382169952616096,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.5116669535636902,
     'pred': 1,
     'label': 1,
     'max_overlap': 0.3793103448275862,
     'pocket_in_site': 0.14864864864864866,
     'site_in_pocket': 0.3793103448275862},
    'pocket2': {'prob': 6.2724589042773005e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket20': {'prob': 0.00042591363308019936,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.14285714285714285,
     'pocket_in_site': 0.14285714285714285,
     'site_in_pocket': 0.06896551724137931},
    'pocket4': {'prob': 0.0004984461120329797,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket17': {'prob': 2.2640482711722143e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.21428571428571427,
     'pocket_in_site': 0.21428571428571427,
     'site_in_pocket': 0.10344827586206896},
    'pocket9': {'prob': 0.0010378675069659948,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.3888888888888889,
     'pocket_in_site': 0.3888888888888889,
     'site_in_pocket': 0.2413793103448276},
    'pocket10': {'prob': 0.0003061984316445887,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.6923076923076923,
     'pocket_in_site': 0.6923076923076923,
     'site_in_pocket': 0.3103448275862069},
    'pocket5': {'prob': 0.031633567065000534,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.16666666666666666,
     'pocket_in_site': 0.16666666666666666,
     'site_in_pocket': 0.06896551724137931},
    'pocket8': {'prob': 0.008575640618801117,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket3': {'prob': 0.003484924091026187,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.4117647058823529,
     'pocket_in_site': 0.4117647058823529,
     'site_in_pocket': 0.2413793103448276},
    'pocket12': {'prob': 0.0003283672849647701,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.75,
     'pocket_in_site': 0.75,
     'site_in_pocket': 0.3103448275862069},
    'pocket19': {'prob': 1.5314815755118616e-05,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket6': {'prob': 0.0006159227923490107,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0}},
   '7l6r': {'pocket11': {'prob': 5.500509359990247e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket7': {'prob': 4.781044026458403e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket13': {'prob': 0.00038983477861620486,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.2222222222222222,
     'pocket_in_site': 0.2222222222222222,
     'site_in_pocket': 0.07692307692307693},
    'pocket14': {'prob': 5.5861914916022215e-06,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.0,
     'pocket_in_site': 0.0,
     'site_in_pocket': 0.0},
    'pocket1': {'prob': 0.0016447186935693026,
     'pred': 0,
     'label': 0,
     'max_overlap': 0.3,

# Labelling

In [49]:
# Percentage of residues of "one" in "other"
get_overlap = lambda one, other: (
    len( one.merge(other) ) / len(one)
)

def get_label(overlaps, site_in_pocket=None, pocket_in_site=None):
    assert not (site_in_pocket==None and pocket_in_site==None)
    
    if site_in_pocket is None:
        return int( overlaps["pocket_in_site"] >= pocket_in_site )
    if pocket_in_site is None:
        return int( overlaps["site_in_pocket"] >= site_in_pocket )
    return int( overlaps["site_in_pocket"] >= site_in_pocket or overlaps["pocket_in_site"] >= pocket_in_site )

In [50]:
# get_overlaps = lambda pdb, pocketd: {
#     name: get_overlap(*one_in_other) 
#         for site in news_sites[pdb]
#             for name, one_in_other in (
#                 ("pocket_in_site", (pocketd["residues"], site["site"])),
#                 ("site_in_pocket", (site["site"], pocketd["residues"])),
#             )
# }

get_overlaps = lambda pdb, pocketd: max(
    (
        {
            name: get_overlap(*one_in_other)
            for name, one_in_other in (
                ("pocket_in_site", (pocketd["residues"], site)),
                ("site_in_pocket", (site, pocketd["residues"])),
            )
        }
        for site in news_sites[pdb]
    ),
    key=lambda x: x["site_in_pocket"]
)



# get_overlaps_special = lambda pdb, pocketd: {
#     name: get_overlap(*one_in_other) 
#         for pocketres in (pocketd["residues"],)
#             for sited in news_sites[pdb]
#                 for site in (sited["site"].query(f"auth_asym_id == '{pocketres.auth_asym_id.unique().item()}'"),)
#                     for name, one_in_other in (
#                         ("pocket_in_site", (pocketres, site)),
#                         ("site_in_pocket", (site, pocketres)),
#                     )
# }

get_overlaps_special = lambda pdb, pocketd: max(
    (
        {
            name: get_overlap(*one_in_other)
            for name, one_in_other in (
                ("pocket_in_site", (pocketres, site)),
                ("site_in_pocket", (site, pocketres)),
            )
        }
        for pocketres in (pocketd["residues"],)
            for sitei in news_sites[pdb]
                for site in (sitei.query(f"auth_asym_id == '{pocketres.auth_asym_id.unique().item()}'"),)
    ),
    key=lambda x: x["site_in_pocket"]
)

In [51]:
def label_results(resultsd, site_in_pocket=0.65, pocket_in_site=None, prob_key=None, topx=False, special_7sns_sc=False):
    df = pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            **{"prob": pocketd[prob_key] for prob_key in (prob_key,) if prob_key is not None},
            "pred": pocketd["pred"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in ((
            get_overlaps_special(pdb, pocketd)
            if special_7sns_sc and pdb == "7sns"
            else get_overlaps(pdb, pocketd)
        ),)
    ))
    
    if prob_key is not None and topx:
        df["pred"] = (
            # Start from a Series where each value/row (sample/pocket) is the total number of pos. labels on its PDB
            df.groupby("pdb")["label"].transform("sum")
            # Then subtract this "total num. of pos. in a PDB" by the rank of each pocket in a PDB, sorted by the probability
            .sub(df.groupby("pdb")["prob"].rank(method="first", ascending=False))
            # If the subtraction is positive or 0 it means that the pocket is in the topX and will be assigned 1
            >= 0
        ).astype(int)
        # If a PDB has no + labelled pocket, assign the highest prob. as positive
        for pdb, group in df.groupby("pdb"):
            if group["pred"].sum() == 0:
                df.loc[ group["prob"].idxmax(), "pred" ] = 1
    
    return df.sort_values("max_overlap", ascending=False)

def label_results(resultsd, site_in_pocket=0.65, pocket_in_site=None, prob_key=None, topx=False, special_7sns_sc=False):
    return pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            **{"prob": pocketd[prob_key] for prob_key in (prob_key,) if prob_key is not None},
            "pred": pocketd["pred"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in ((
            get_overlaps_special(pdb, pocketd)
            if special_7sns_sc and pdb == "7sns"
            else get_overlaps(pdb, pocketd)
        ),)
    )).sort_values("max_overlap", ascending=False)

def label_results_topx(resultsd, site_in_pocket=0.65, pocket_in_site=None, prob_key=None):
    df = pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            **{"prob": pocketd[prob_key] for prob_key in (prob_key,) if prob_key is not None},
            "pred": pocketd["pred"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in (get_overlaps(pdb, pocketd),)
    ))
    if prob_key is not None:
        df["pred"] = (
            # Start from a Series where each value/row (sample/pocket) is the total number of pos. labels on its PDB
            df.groupby("pdb")["label"].transform("sum")
            # Then subtract this "total num. of pos. in a PDB" by the rank of each pocket in a PDB, sorted by the probability
            .sub(df.groupby("pdb")["prob"].rank(method="first", ascending=False))
            # If the subtraction is positive or 0 it means that the pocket is in the topX and will be assigned 1
            >= 0
        ).astype(int)
        # If a PDB has no + labelled pocket, assign the highest prob. as positive
        for pdb, group in df.groupby("pdb"):
            if group["pred"].sum() == 0:
                df.loc[ group["prob"].idxmax(), "pred" ] = 1
            
    
    return df.sort_values("site_in_pocket", ascending=False)

## Our results

def label_our_results(resultsd, site_in_pocket=0.65, pocket_in_site=None):
    return pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            "prob": pocketd["prob"],
            "pred": pocketd["pred"],
            "pred_top1": int( pocketd["prob"] == pdb_maxprob ),
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pdb_maxprob in (max(pktd["prob"] for pktd in pockets.values()),)
        for pocket, pocketd in pockets.items()
        for overlaps in ({k: pocketd[k] for k in ["pocket_in_site", "site_in_pocket"]},)
    )).sort_values("max_overlap", ascending=False)


def label_our_results_topx(resultsd, site_in_pocket=0.65, pocket_in_site=None):
    df = pd.DataFrame((
        {
            "pdb": pdb,
            "pocket": pocket,
            "prob": pocketd["prob"],
            "label": get_label(overlaps, site_in_pocket, pocket_in_site),
            "max_overlap": max(overlaps.values()),
            **overlaps,
        }
        for pdb, pockets in resultsd.items()
        for pocket, pocketd in pockets.items()
        for overlaps in ({k: pocketd[k] for k in ["pocket_in_site", "site_in_pocket"]},)
    ))
    df["pred"] = (
        # Start from a Series where each value/row (sample/pocket) is the total number of pos. labels on its PDB
        df.groupby("pdb")["label"].transform("sum")
        # Then subtract this "total num. of pos. in a PDB" by the rank of each pocket in a PDB, sorted by the probability
        .sub(df.groupby("pdb")["prob"].rank(method="first", ascending=False))
        # If the subtraction is positive or 0 it means that the pocket is in the topX and will be assigned 1
        >= 0
    ).astype(int)
    # If a PDB has no + labelled pocket, assign the highest prob. as positive
    for pdb, group in df.groupby("pdb"):
        if group["pred"].sum() == 0:
            df.loc[ group["prob"].idxmax(), "pred" ] = 1

    
    # ########## TEMP top1 labelling
    # df["pred"] = 0
    # for pdb, group in df.groupby("pdb"):
    #     df.loc[ group["prob"].idxmax(), "pred" ] = 1


    return df.sort_values("site_in_pocket", ascending=False)

label_our_results_topx(model5_results, site_in_pocket=0.35, pocket_in_site=None,).iloc[:40].sort_values("site_in_pocket", ascending=False)

label_our_results_topx(model5_results, site_in_pocket=0.35, pocket_in_site=None).query("pdb == '7xlq'").sort_values("pred")

We don't label any pocket for 5b0u and 4jqi

<br>

label_our_results_topx(model5_results, site_in_pocket=0.5, pocket_in_site=0.5).query("pdb in ['5b0u', '4jqi']")

models["model5"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

## Model 5.

from utils.pocket_utils import Pocket

for pdb, pdbd in tuple(model5_results.items()):
    for pocket, pocketd in tuple(pdbd.items()):
        model5_results[pdb][pocket].update({
            "residues": Pocket(f"../../training_data/8.Apos/Extra_set/pockets/{pdb}/{pdb}_out/pockets/{pocket}_atm.cif").residues
        })

label_results(model5_results, site_in_pocket=0.35, pocket_in_site=None, topx=True, prob_key="prob").iloc[:40] # , prob_key=models["allo"]["prob_key"]

label_results(model5_results, site_in_pocket=0.35, pocket_in_site=None, topx=True, prob_key="prob").sort_values("label", ascending=False).iloc[:40] # , prob_key=models["allo"]["prob_key"]

models["model5"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

## AllositePro

In [79]:
label_results(allositepro_results, site_in_pocket=0.3, pocket_in_site=None, prob_key=models["allositepro"]["prob_key"])

,pdb,pocket,prob,pred,label,max_overlap,pocket_in_site,site_in_pocket
1,7sns,pocket0,0.628,1,1,0.607143,0.607143,0.586207
3,7sns,pocket2,0.594,1,1,0.500000,0.500000,0.310345
2,7sns,pocket1,0.601,1,1,0.428571,0.428571,0.310345
0,7l6r,pocket0,0.869,1,1,0.307692,0.222222,0.307692

In [53]:
models["allositepro"]["labelling"] = {"site_in_pocket": 0.3, "pocket_in_site": None}

## PASSer

In [54]:
label_results(passer_results["ensemble"], site_in_pocket=0.35, pocket_in_site=None).iloc[:40] # prob_key=models["passer_ensemble"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
335,7sns,12,0,1,1.000000,1.000000,0.413793
214,7xlq,49,0,1,0.947368,0.947368,0.620690
489,4jqi,10,0,1,0.875000,0.875000,0.700000
403,5uak,36,0,1,0.866667,0.866667,0.481481
128,7l6r,20,0,0,0.857143,0.857143,0.230769
52,8sgj,21,0,0,0.750000,0.750000,0.093750
182,6yhr,32,0,0,0.727273,0.727273,0.275862
125,7l6r,19,0,0,0.666667,0.666667,0.230769
132,8vw5,1,1,1,0.652174,0.652174,0.652174
313,7sns,2,1,1,0.625000,0.625000,0.517241
257,7xlq,55,0,0,0.600000,0.600000,0.103448
152,8vw5,16,0,0,0.600000,0.600000,0.130435
317,7sns,1,0,0,0.600000,0.600000,0.310345
2,8sgj,1,1,1,0.576923,0.576923,0.468750
165,6yhr,12,0,0,0.571429,0.571429,0.137931
314,7sns,4,1,0,0.529412,0.529412,0.310345
108,7l6r,4,1,1,0.526316,0.526316,0.384615
98,AF-A0A1D8PQM9-F1,16,0,0,0.500000,0.500000,0.190476
248,7xlq,98,0,0,0.500000,0.500000,0.172414
371,5uak,8,0,0,0.500000,0.500000,0.333333
334,7sns,16,0,0,0.500000,0.500000,0.103448
303,7xlq,30,0,0,0.444444,0.444444,0.137931
19,8sgj,18,0,0,0.400000,0.400000,0.062500
153,6yhr,44,1,1,0.379310,0.244444,0.379310
503,4jqi,23,0,0,0.375000,0.375000,0.300000
119,7l6r,23,0,0,0.333333,0.333333,0.076923
178,6yhr,39,0,0,0.333333,0.333333,0.068966
14,8sgj,42,0,0,0.333333,0.333333,0.093750
316,7sns,9,0,0,0.307692,0.307692,0.137931
475,4jqi,33,1,0,0.300000,0.107143,0.300000
184,6yhr,35,0,0,0.285714,0.285714,0.068966
331,7sns,20,0,0,0.285714,0.285714,0.068966
329,7sns,23,0,0,0.285714,0.285714,0.068966
54,AF-A0A1D8PQM9-F1,2,1,0,0.285714,0.250000,0.285714
164,6yhr,5,0,0,0.285714,0.285714,0.137931
104,AF-A0A1D8PQM9-F1,28,0,0,0.250000,0.250000,0.095238
129,7l6r,18,0,0,0.250000,0.250000,0.076923
473,5uak,106,0,0,0.250000,0.250000,0.074074
56,AF-A0A1D8PQM9-F1,4,1,0,0.238095,0.208333,0.238095
158,6yhr,34,0,0,0.230769,0.230769,0.103448

In [55]:
models["passer_ensemble"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

In [56]:
label_results(passer_results["automl"], site_in_pocket=0.35, pocket_in_site=None).iloc[:40] # , prob_key=models["passer_automl"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
325,7sns,12,0,1,1.000000,1.000000,0.413793
224,7xlq,49,0,1,0.947368,0.947368,0.620690
500,4jqi,10,0,1,0.875000,0.875000,0.700000
411,5uak,36,0,1,0.866667,0.866667,0.481481
120,7l6r,20,0,0,0.857143,0.857143,0.230769
53,8sgj,21,0,0,0.750000,0.750000,0.093750
167,6yhr,32,0,0,0.727273,0.727273,0.275862
123,7l6r,19,0,0,0.666667,0.666667,0.230769
132,8vw5,1,1,1,0.652174,0.652174,0.652174
312,7sns,2,1,1,0.625000,0.625000,0.517241
300,7xlq,55,0,0,0.600000,0.600000,0.103448
150,8vw5,16,0,0,0.600000,0.600000,0.130435
313,7sns,1,1,0,0.600000,0.600000,0.310345
0,8sgj,1,1,1,0.576923,0.576923,0.468750
187,6yhr,12,0,0,0.571429,0.571429,0.137931
315,7sns,4,0,0,0.529412,0.529412,0.310345
108,7l6r,4,1,1,0.526316,0.526316,0.384615
234,7xlq,98,0,0,0.500000,0.500000,0.172414
326,7sns,16,0,0,0.500000,0.500000,0.103448
99,AF-A0A1D8PQM9-F1,16,0,0,0.500000,0.500000,0.190476
373,5uak,8,0,0,0.500000,0.500000,0.333333
247,7xlq,30,0,0,0.444444,0.444444,0.137931
17,8sgj,18,0,0,0.400000,0.400000,0.062500
153,6yhr,44,1,1,0.379310,0.244444,0.379310
489,4jqi,23,0,0,0.375000,0.375000,0.300000
129,7l6r,23,0,0,0.333333,0.333333,0.076923
188,6yhr,39,0,0,0.333333,0.333333,0.068966
16,8sgj,42,0,0,0.333333,0.333333,0.093750
319,7sns,9,0,0,0.307692,0.307692,0.137931
476,4jqi,33,1,0,0.300000,0.107143,0.300000
54,AF-A0A1D8PQM9-F1,2,1,0,0.285714,0.250000,0.285714
172,6yhr,5,0,0,0.285714,0.285714,0.137931
321,7sns,23,0,0,0.285714,0.285714,0.068966
196,6yhr,35,0,0,0.285714,0.285714,0.068966
335,7sns,20,0,0,0.285714,0.285714,0.068966
82,AF-A0A1D8PQM9-F1,28,0,0,0.250000,0.250000,0.095238
450,5uak,106,0,0,0.250000,0.250000,0.074074
130,7l6r,18,0,0,0.250000,0.250000,0.076923
55,AF-A0A1D8PQM9-F1,4,1,0,0.238095,0.208333,0.238095
169,6yhr,34,0,0,0.230769,0.230769,0.103448

In [57]:
models["passer_automl"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

In [58]:
models["passer_rank"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

## DeepAllo

In [59]:
label_results(deepallo_results, site_in_pocket=0.35, pocket_in_site=None, special_7sns_sc=True).iloc[:40] # , prob_key=models["deepallo"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
249,7xlq,pocket56,0,1,0.947368,0.947368,0.620690
456,4jqi,pocket8,0,1,0.875000,0.875000,0.700000
345,5uak,pocket36,0,1,0.866667,0.866667,0.481481
123,7l6r,pocket16,0,0,0.857143,0.857143,0.230769
491,7sns,pocket9_A,0,0,0.833333,0.833333,0.312500
184,6yhr,pocket31,0,0,0.800000,0.800000,0.275862
22,8sgj,pocket22,0,0,0.750000,0.750000,0.093750
120,7l6r,pocket13,0,0,0.666667,0.666667,0.230769
132,8vw5,pocket1,1,1,0.652174,0.652174,0.652174
129,7l6r,pocket22,0,0,0.625000,0.625000,0.192308
253,7xlq,pocket60,0,0,0.600000,0.600000,0.103448
147,8vw5,pocket16,0,0,0.600000,0.600000,0.130435
0,8sgj,pocket1,1,1,0.576923,0.576923,0.468750
165,6yhr,pocket11,0,0,0.571429,0.571429,0.137931
55,AF-A0A1D8PQM9-F1,pocket16,1,0,0.500000,0.500000,0.190476
317,5uak,pocket8,0,0,0.500000,0.500000,0.333333
294,7xlq,pocket101,0,0,0.500000,0.500000,0.172414
480,7sns,pocket1_B,0,1,0.461538,0.461538,0.375000
207,7xlq,pocket14,0,0,0.444444,0.444444,0.137931
19,8sgj,pocket19,0,0,0.400000,0.400000,0.062500
157,6yhr,pocket1,0,1,0.379310,0.244444,0.379310
469,4jqi,pocket21,0,0,0.375000,0.375000,0.300000
189,6yhr,pocket36,0,0,0.333333,0.333333,0.068966
42,8sgj,pocket42,0,0,0.333333,0.333333,0.093750
492,7sns,pocket9_B,0,0,0.333333,0.333333,0.153846
131,7l6r,pocket24,0,0,0.333333,0.333333,0.076923
459,4jqi,pocket11,0,0,0.300000,0.111111,0.300000
156,6yhr,pocket5,1,0,0.285714,0.285714,0.137931
185,6yhr,pocket32,0,0,0.285714,0.285714,0.068966
54,AF-A0A1D8PQM9-F1,pocket2,1,0,0.285714,0.250000,0.285714
490,7sns,pocket8_B,0,0,0.285714,0.285714,0.153846
118,7l6r,pocket11,0,0,0.250000,0.250000,0.076923
414,5uak,pocket106,0,0,0.250000,0.250000,0.074074
82,AF-A0A1D8PQM9-F1,pocket28,0,0,0.250000,0.250000,0.095238
59,AF-A0A1D8PQM9-F1,pocket4,0,0,0.238095,0.208333,0.238095
187,6yhr,pocket34,0,0,0.230769,0.230769,0.103448
133,8vw5,pocket2,1,0,0.227273,0.227273,0.217391
489,7sns,pocket8_A,0,0,0.200000,0.200000,0.076923
381,5uak,pocket73,0,0,0.200000,0.200000,0.074074
81,AF-A0A1D8PQM9-F1,pocket27,0,0,0.200000,0.200000,0.047619

In [60]:
models["deepallo"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None, "special_7sns_sc": True}

## STINGAllo

In [61]:
label_results(stingallo_results, site_in_pocket=None, pocket_in_site=1) # _topx

    pdb   pocket  pred  label  max_overlap  pocket_in_site  site_in_pocket
0  6yhr   pocket     1      0          0.0             0.0             0.0
1  7sns  pocket1     1      0          0.0             0.0             0.0
2  7sns  pocket2     1      0          0.0             0.0             0.0
3  7sns  pocket3     1      0          0.0             0.0             0.0

In [62]:
models["stingallo"]["labelling"] = {"site_in_pocket": None, "pocket_in_site": 1}

## AlloFusion

In [63]:
result = label_results(allofusion_results, site_in_pocket=None, pocket_in_site=1)
result

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
54,7sns,pocket_A_59,1,1,1.0,1.0,0.034483
53,7sns,pocket_A_57,1,1,1.0,1.0,0.034483
67,7sns,pocket_B_59,1,1,1.0,1.0,0.034483
17,6yhr,pocket_A_704,1,1,1.0,1.0,0.034483
50,7sns,pocket_A_10,1,1,1.0,1.0,0.034483
...,...,...,...,...,...,...,...
23,6yhr,pocket_A_854,1,0,0.0,0.0,0.000000
22,6yhr,pocket_A_731,1,0,0.0,0.0,0.000000
21,6yhr,pocket_A_730,1,0,0.0,0.0,0.000000
20,6yhr,pocket_A_721,1,0,0.0,0.0,0.000000
30,5uak,pocket_A_464,1,0,0.0,0.0,0.000000

In [64]:
mask = ((result.pred == 1) & (result.label == 1))
mask

54     True
53     True
67     True
17     True
50     True
      ...
23    False
22    False
21    False
20    False
30    False
Length: 76, dtype: bool

In [65]:
pd.concat((
    result.loc[result[mask].drop_duplicates("pdb").index],
    result[~mask]
))

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
54,7sns,pocket_A_59,1,1,1.0,1.0,0.034483
17,6yhr,pocket_A_704,1,1,1.0,1.0,0.034483
28,5uak,pocket_A_347,1,1,1.0,1.0,0.037037
52,7sns,pocket_A_27,1,0,0.0,0.0,0.000000
51,7sns,pocket_A_16,1,0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...
23,6yhr,pocket_A_854,1,0,0.0,0.0,0.000000
22,6yhr,pocket_A_731,1,0,0.0,0.0,0.000000
21,6yhr,pocket_A_730,1,0,0.0,0.0,0.000000
20,6yhr,pocket_A_721,1,0,0.0,0.0,0.000000
30,5uak,pocket_A_464,1,0,0.0,0.0,0.000000

In [66]:
models["allofusion"]["labelling"] = {"site_in_pocket": None, "pocket_in_site": 1}

## AllosES

In [67]:
label_results(alloses_results, site_in_pocket=0.35, pocket_in_site=None, special_7sns_sc=True).iloc[:40] # , prob_key=models["alloses"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
206,7xlq,pocket49,0,1,0.947368,0.947368,0.620690
458,4jqi,pocket10,0,1,0.875000,0.875000,0.700000
324,5uak,pocket36,0,1,0.866667,0.866667,0.481481
125,7l6r,pocket20,0,0,0.857143,0.857143,0.230769
12,8sgj,pocket21,0,0,0.750000,0.750000,0.093750
171,6yhr,pocket32,0,0,0.727273,0.727273,0.275862
118,7l6r,pocket19,0,0,0.666667,0.666667,0.230769
132,8vw5,pocket1,0,1,0.652174,0.652174,0.652174
151,8vw5,pocket16,0,0,0.600000,0.600000,0.130435
268,7xlq,pocket55,0,0,0.600000,0.600000,0.103448
0,8sgj,pocket1,0,1,0.576923,0.576923,0.468750
185,6yhr,pocket12,0,0,0.571429,0.571429,0.137931
108,7l6r,pocket4,0,1,0.526316,0.526316,0.384615
239,7xlq,pocket98,0,0,0.500000,0.500000,0.172414
489,7sns,pocket5_A,0,0,0.500000,0.500000,0.312500
71,AF-A0A1D8PQM9-F1,pocket16,0,0,0.500000,0.500000,0.190476
352,5uak,pocket8,0,0,0.500000,0.500000,0.333333
488,7sns,pocket1_B,0,1,0.461538,0.461538,0.375000
222,7xlq,pocket30,0,0,0.444444,0.444444,0.137931
19,8sgj,pocket18,0,0,0.400000,0.400000,0.062500
153,6yhr,pocket44,0,1,0.379310,0.244444,0.379310
463,4jqi,pocket23,0,0,0.375000,0.375000,0.300000
129,7l6r,pocket23,0,0,0.333333,0.333333,0.076923
43,8sgj,pocket42,0,0,0.333333,0.333333,0.093750
186,6yhr,pocket39,0,0,0.333333,0.333333,0.068966
496,7sns,pocket11_B,0,0,0.333333,0.333333,0.153846
455,4jqi,pocket33,0,0,0.300000,0.107143,0.300000
190,6yhr,pocket35,0,0,0.285714,0.285714,0.068966
493,7sns,pocket9_B,0,0,0.285714,0.285714,0.153846
166,6yhr,pocket5,0,0,0.285714,0.285714,0.137931
55,AF-A0A1D8PQM9-F1,pocket2,0,0,0.285714,0.250000,0.285714
390,5uak,pocket106,0,0,0.250000,0.250000,0.074074
72,AF-A0A1D8PQM9-F1,pocket28,0,0,0.250000,0.250000,0.095238
119,7l6r,pocket18,0,0,0.250000,0.250000,0.076923
54,AF-A0A1D8PQM9-F1,pocket4,0,0,0.238095,0.208333,0.238095
158,6yhr,pocket34,0,0,0.230769,0.230769,0.103448
131,8vw5,pocket2,0,0,0.227273,0.227273,0.217391
380,5uak,pocket73,0,0,0.200000,0.200000,0.074074
502,7sns,pocket9_A,0,0,0.200000,0.200000,0.076923
82,AF-A0A1D8PQM9-F1,pocket27,0,0,0.200000,0.200000,0.047619

In [68]:
label_results(alloses_results, site_in_pocket=0.35, pocket_in_site=None, special_7sns_sc=True).sort_values("label", ascending=False).iloc[:40] # , prob_key=models["alloses"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
324,5uak,pocket36,0,1,0.866667,0.866667,0.481481
458,4jqi,pocket10,0,1,0.875000,0.875000,0.700000
488,7sns,pocket1_B,0,1,0.461538,0.461538,0.375000
206,7xlq,pocket49,0,1,0.947368,0.947368,0.620690
132,8vw5,pocket1,0,1,0.652174,0.652174,0.652174
153,6yhr,pocket44,0,1,0.379310,0.244444,0.379310
108,7l6r,pocket4,0,1,0.526316,0.526316,0.384615
0,8sgj,pocket1,0,1,0.576923,0.576923,0.468750
446,5uak,pocket60,0,0,0.000000,0.000000,0.000000
445,5uak,pocket18,0,0,0.000000,0.000000,0.000000
444,5uak,pocket16,0,0,0.000000,0.000000,0.000000
443,5uak,pocket53,0,0,0.000000,0.000000,0.000000
442,5uak,pocket76,0,0,0.000000,0.000000,0.000000
448,5uak,pocket115,0,0,0.000000,0.000000,0.000000
440,5uak,pocket79,0,0,0.000000,0.000000,0.000000
7,8sgj,pocket44,0,0,0.000000,0.000000,0.000000
6,8sgj,pocket53,0,0,0.000000,0.000000,0.000000
3,8sgj,pocket15,0,0,0.000000,0.000000,0.000000
2,8sgj,pocket40,0,0,0.000000,0.000000,0.000000
31,8sgj,pocket31,0,0,0.000000,0.000000,0.000000
441,5uak,pocket69,0,0,0.000000,0.000000,0.000000
116,7l6r,pocket10,0,0,0.000000,0.000000,0.000000
115,7l6r,pocket15,0,0,0.000000,0.000000,0.000000
114,7l6r,pocket3,0,0,0.000000,0.000000,0.000000
113,7l6r,pocket16,0,0,0.000000,0.000000,0.000000
112,7l6r,pocket1,0,0,0.000000,0.000000,0.000000
111,7l6r,pocket2,0,0,0.000000,0.000000,0.000000
110,7l6r,pocket13,0,0,0.000000,0.000000,0.000000
70,AF-A0A1D8PQM9-F1,pocket47,0,0,0.000000,0.000000,0.000000
107,AF-A0A1D8PQM9-F1,pocket26,0,0,0.000000,0.000000,0.000000
106,AF-A0A1D8PQM9-F1,pocket11,0,0,0.000000,0.000000,0.000000
105,AF-A0A1D8PQM9-F1,pocket35,0,0,0.000000,0.000000,0.000000
104,AF-A0A1D8PQM9-F1,pocket29,0,0,0.000000,0.000000,0.000000
103,AF-A0A1D8PQM9-F1,pocket13,0,0,0.000000,0.000000,0.000000
102,AF-A0A1D8PQM9-F1,pocket9,0,0,0.000000,0.000000,0.000000
117,7l6r,pocket17,0,0,0.000000,0.000000,0.000000
449,5uak,pocket85,0,0,0.000000,0.000000,0.000000
109,7l6r,pocket9,0,0,0.000000,0.000000,0.000000
467,4jqi,pocket22,0,0,0.000000,0.000000,0.000000
468,4jqi,pocket17,0,0,0.000000,0.000000,0.000000

In [69]:
models["alloses"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None, "special_7sns_sc": True}

## MEF-AlloSite

In [70]:
label_results(mefallosite_results, site_in_pocket=0.35, pocket_in_site=None).iloc[:40] # , prob_key=models["mefallosite"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
435,7sns,pocket9,0,1,1.000000,1.000000,0.413793
173,7xlq,pocket33,0,1,0.947368,0.947368,0.620690
409,4jqi,pocket8,0,1,0.875000,0.875000,0.700000
354,5uak,pocket35,0,1,0.866667,0.866667,0.481481
127,7l6r,pocket17,0,0,0.833333,0.833333,0.192308
38,8sgj,pocket18,0,0,0.750000,0.750000,0.093750
144,6yhr,pocket27,0,0,0.727273,0.727273,0.275862
125,7l6r,pocket18,0,0,0.666667,0.666667,0.230769
11,8vw5,pocket1,1,1,0.652174,0.652174,0.652174
432,7sns,pocket1,0,1,0.625000,0.625000,0.517241
10,8vw5,pocket13,0,0,0.600000,0.600000,0.130435
250,7xlq,pocket38,0,0,0.600000,0.600000,0.103448
53,8sgj,pocket1,1,1,0.576923,0.576923,0.468750
166,6yhr,pocket11,0,0,0.571429,0.571429,0.137931
423,7sns,pocket3,1,0,0.529412,0.529412,0.310345
132,7l6r,pocket4,1,1,0.526316,0.526316,0.384615
185,7xlq,pocket71,0,0,0.500000,0.500000,0.172414
77,AF-A0A1D8PQM9-F1,pocket16,0,0,0.500000,0.500000,0.190476
344,5uak,pocket8,0,0,0.500000,0.500000,0.333333
209,7xlq,pocket20,0,0,0.444444,0.444444,0.137931
18,8sgj,pocket15,0,0,0.400000,0.400000,0.062500
138,6yhr,pocket33,1,1,0.379310,0.255814,0.379310
395,4jqi,pocket22,0,0,0.375000,0.375000,0.300000
436,7sns,pocket11,0,0,0.333333,0.333333,0.137931
44,8sgj,pocket36,0,0,0.333333,0.333333,0.093750
422,7sns,pocket16,0,0,0.285714,0.285714,0.068966
438,7sns,pocket19,0,0,0.285714,0.285714,0.068966
427,7sns,pocket18,0,0,0.285714,0.285714,0.137931
82,AF-A0A1D8PQM9-F1,pocket2,0,0,0.285714,0.250000,0.285714
164,6yhr,pocket4,0,0,0.285714,0.285714,0.137931
309,5uak,pocket106,0,0,0.250000,0.250000,0.074074
120,7l6r,pocket16,0,0,0.250000,0.250000,0.076923
95,AF-A0A1D8PQM9-F1,pocket28,0,0,0.250000,0.250000,0.095238
157,6yhr,pocket26,0,0,0.250000,0.250000,0.103448
110,AF-A0A1D8PQM9-F1,pocket4,0,0,0.238095,0.208333,0.238095
4,8vw5,pocket2,0,0,0.227273,0.227273,0.217391
312,5uak,pocket73,0,0,0.200000,0.200000,0.074074
418,4jqi,pocket7,0,0,0.200000,0.086957,0.200000
74,AF-A0A1D8PQM9-F1,pocket27,0,0,0.200000,0.200000,0.047619
321,5uak,pocket46,0,0,0.190476,0.190476,0.148148

In [71]:
models["mefallosite"]["labelling"] = {"site_in_pocket": 0.35, "pocket_in_site": None}

## ALLO

In [72]:
label_results(allo_results, site_in_pocket=0.3, pocket_in_site=None).iloc[:40] # , prob_key=models["allo"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
184,7sns,P_0,0,1,0.931034,0.313953,0.931034
210,8vw5,P_0,1,1,0.913043,0.355932,0.913043
91,AF-A0A1D8PQM9-F1,P_1,0,1,0.904762,0.395833,0.904762
178,5uak,P_0,1,1,0.814815,0.366667,0.814815
117,7l6r,P_8,0,0,0.777778,0.777778,0.269231
54,7xlq,P_2,0,1,0.689655,0.689655,0.689655
225,6yhr,P_0,1,1,0.689655,0.229885,0.689655
112,8sgj,P_1,1,1,0.562500,0.315789,0.562500
18,7xlq,P_41,0,0,0.500000,0.500000,0.137931
71,AF-A0A1D8PQM9-F1,P_13,0,0,0.461538,0.461538,0.285714
164,5uak,P_33,0,0,0.411765,0.411765,0.259259
126,7l6r,P_1,0,1,0.384615,0.344828,0.384615
90,AF-A0A1D8PQM9-F1,P_0,1,1,0.333333,0.140000,0.333333
129,5uak,P_21,0,0,0.312500,0.312500,0.185185
181,7sns,P_5,0,0,0.307692,0.307692,0.137931
200,4jqi,P_2,0,1,0.300000,0.115385,0.300000
183,7sns,P_3,0,0,0.294118,0.294118,0.172414
226,6yhr,P_1,0,0,0.241379,0.241379,0.241379
190,4jqi,P_14,0,0,0.200000,0.181818,0.200000
221,6yhr,P_4,0,0,0.190476,0.190476,0.137931
208,8vw5,P_2,0,0,0.190476,0.190476,0.173913
219,6yhr,P_6,0,0,0.166667,0.166667,0.068966
108,8sgj,P_5,0,0,0.142857,0.142857,0.125000
20,7xlq,P_38,0,0,0.125000,0.125000,0.034483
100,8sgj,P_18,0,0,0.117647,0.117647,0.062500
150,5uak,P_37,0,0,0.111111,0.111111,0.037037
185,7sns,P_1,1,0,0.103448,0.062500,0.103448
109,8sgj,P_2,0,0,0.100000,0.100000,0.093750
189,4jqi,P_13,0,0,0.100000,0.090909,0.100000
106,8sgj,P_7,0,0,0.090909,0.090909,0.062500
132,5uak,P_22,0,0,0.090909,0.090909,0.074074
50,7xlq,P_6,0,0,0.083333,0.083333,0.068966
125,7l6r,P_0,0,0,0.076923,0.068966,0.076923
177,5uak,P_3,0,0,0.074074,0.066667,0.074074
37,7xlq,P_33,0,0,0.071429,0.071429,0.034483
154,5uak,P_13,0,0,0.071429,0.071429,0.037037
182,7sns,P_2,0,0,0.068966,0.045455,0.068966
3,7xlq,P_20,0,0,0.066667,0.066667,0.034483
105,8sgj,P_6,0,0,0.062500,0.057143,0.062500
104,8sgj,P_9,0,0,0.062500,0.062500,0.031250

In [73]:
label_results(allo_results, site_in_pocket=0.5, pocket_in_site=None).sort_values(["label", "pred"], ascending=False).iloc[:40] # , prob_key=models["allo"]["prob_key"]

,pdb,pocket,pred,label,max_overlap,pocket_in_site,site_in_pocket
210,8vw5,P_0,1,1,0.913043,0.355932,0.913043
178,5uak,P_0,1,1,0.814815,0.366667,0.814815
225,6yhr,P_0,1,1,0.689655,0.229885,0.689655
112,8sgj,P_1,1,1,0.562500,0.315789,0.562500
184,7sns,P_0,0,1,0.931034,0.313953,0.931034
91,AF-A0A1D8PQM9-F1,P_1,0,1,0.904762,0.395833,0.904762
54,7xlq,P_2,0,1,0.689655,0.689655,0.689655
90,AF-A0A1D8PQM9-F1,P_0,1,0,0.333333,0.140000,0.333333
185,7sns,P_1,1,0,0.103448,0.062500,0.103448
202,4jqi,P_0,1,0,0.000000,0.000000,0.000000
56,7xlq,P_0,1,0,0.000000,0.000000,0.000000
118,7l6r,P_9,1,0,0.000000,0.000000,0.000000
117,7l6r,P_8,0,0,0.777778,0.777778,0.269231
18,7xlq,P_41,0,0,0.500000,0.500000,0.137931
71,AF-A0A1D8PQM9-F1,P_13,0,0,0.461538,0.461538,0.285714
164,5uak,P_33,0,0,0.411765,0.411765,0.259259
126,7l6r,P_1,0,0,0.384615,0.344828,0.384615
129,5uak,P_21,0,0,0.312500,0.312500,0.185185
181,7sns,P_5,0,0,0.307692,0.307692,0.137931
200,4jqi,P_2,0,0,0.300000,0.115385,0.300000
183,7sns,P_3,0,0,0.294118,0.294118,0.172414
226,6yhr,P_1,0,0,0.241379,0.241379,0.241379
190,4jqi,P_14,0,0,0.200000,0.181818,0.200000
221,6yhr,P_4,0,0,0.190476,0.190476,0.137931
208,8vw5,P_2,0,0,0.190476,0.190476,0.173913
219,6yhr,P_6,0,0,0.166667,0.166667,0.068966
108,8sgj,P_5,0,0,0.142857,0.142857,0.125000
20,7xlq,P_38,0,0,0.125000,0.125000,0.034483
100,8sgj,P_18,0,0,0.117647,0.117647,0.062500
150,5uak,P_37,0,0,0.111111,0.111111,0.037037
109,8sgj,P_2,0,0,0.100000,0.100000,0.093750
189,4jqi,P_13,0,0,0.100000,0.090909,0.100000
106,8sgj,P_7,0,0,0.090909,0.090909,0.062500
132,5uak,P_22,0,0,0.090909,0.090909,0.074074
50,7xlq,P_6,0,0,0.083333,0.083333,0.068966
125,7l6r,P_0,0,0,0.076923,0.068966,0.076923
177,5uak,P_3,0,0,0.074074,0.066667,0.074074
37,7xlq,P_33,0,0,0.071429,0.071429,0.034483
154,5uak,P_13,0,0,0.071429,0.071429,0.037037
182,7sns,P_2,0,0,0.068966,0.045455,0.068966

In [74]:
models["allo"]["labelling"] = {"site_in_pocket": 0.5, "pocket_in_site": None}

In [75]:
pd.to_pickle(models, "models_lenient_labelling.pkl")

# Scoring

## Original

In [81]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news:
        if pdb in ["4jqi", 'AF-A0A1D8PQM9-F1']: continue #################################################################################
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            # Top1 pred for our model
            if model == "model5":
                # pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
                pass
            # elif model == "allofusion":
            #     pdbpreds = pdbpreds.drop(
            #         pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
            #         .index[1:]
            #     )

            # if pdb is 7sns, if there's more than 1 label 1, keep only the pred one if exists, or just 1 in general
            if pdb == "7sns" and model not in ["allofusion", "stingallo"]:
                if model == "allositepro":
                    idxs = (
                        pdbpreds.loc[pdbpreds.label == 1]
                        .sort_values("prob", ascending=False)
                        .index[1:]
                    )
                    pdbpreds.loc[idxs, "label"] = 0
                else:
                    pdbpreds = pdbpreds.drop(
                        pdbpreds.loc[pdbpreds.label == 1]
                        .sort_values("pred", ascending=False)
                        .index[1:]
                    )

            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'8sgj': {'total': 28, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 14, 'tp': 0, 'fn': 1, 'fp': 0},
  '8vw5': {'total': 13, 'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'total': 20, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 69, 'tp': 0, 'fn': 1, 'fp': 2},
  '7sns': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '5uak': {'total': 75, 'tp': 1, 'fn': 0, 'fp': 2}},
 'allositepro': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 0},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '7sns': {'tp': 1, 'fn': 0, 'fp': 2},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0}},
 'stingallo': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '7sns': {'tp': 0, 'fn': 1, 'fp': 3},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0}},
 'allofusion': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 2},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 4},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 8},
  '6yhr': {'tp': 1, 'fn': 0, 'fp': 10},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 2},
  '7sns': {'tp': 6, 'fn': 0, 'fp': 20},
  '5uak': {'tp': 1, 'fn': 0, 'fp': 16}},
 'passer_ensemble': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 2},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 2},
  '8vw5': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 2},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 2},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 3},
  '7sns': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 2},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 3}},
 'passer_automl': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 2},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 2},
  '8vw5': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 2},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 2},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 3},
  '7sns': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 2},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 3}},
 'passer_rank': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 2},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 2},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 3},
  '6yhr': {'total': 44, 'tp': 0, 'fn': 1, 'fp': 3},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 3},
  '7sns': {'total': 24, 'tp': 0, 'fn': 1, 'fp': 3},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 3}},
 'deepallo': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 2},
  '7l6r': {'total': 24, 'tp': 0, 'fn': 1, 'fp': 3},
  '8vw5': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 2},
  '6yhr': {'total': 40, 'tp': 0, 'fn': 1, 'fp': 3},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 3},
  '7sns': {'total': 18, 'tp': 0, 'fn': 1, 'fp': 3},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 3}},
 'alloses': {'8sgj': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'total': 23, 'tp': 0, 'fn': 1, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'total': 44, 'tp': 0, 'fn': 1, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 20, 'tp': 0, 'fn': 1, 'fp': 0},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'mefallosite': {'8sgj': {'total': 47, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 19, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 33, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 84, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 19, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allo': {'8sgj': {'total': 21, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 14, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 8, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 15, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 58, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 6, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 53, 'tp': 1, 'fn': 0, 'fp': 0}}}

In [82]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [83]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
allofusion,allofusion,8,4,62,NaN,NaN,NaN
passer_ensemble,passer_ensemble,5,2,16,0.396848,0.667515,0 1 0 398 16 1 2 5
passer_automl,passer_automl,5,2,16,0.396848,0.667515,0 1 0 398 16 1 2 5
mefallosite,mefallosite,4,3,3,0.562882,0.781441,0 1 0 348 3 1 3 4
allo,allo,4,3,3,0.553571,0.776786,0 1 0 165 3 1 3 4
model5,model5,4,3,4,0.519116,0.758906,0 1 0 222 4 1 3 4
passer_rank,passer_rank,2,5,19,0.140863,0.556687,0 1 0 395 19 1 5 2
deepallo,deepallo,2,5,19,0.140318,0.556353,0 1 0 386 19 1 5 2
allositepro,allositepro,2,5,2,NaN,NaN,NaN
alloses,alloses,0,7,2,-0.009071,0.494545,0 1 0 408 2 1 7 0
stingallo,stingallo,0,7,4,NaN,NaN,NaN

In [84]:
models_metrics.infer_objects().to_csv("models_metrics.csv", index=False, sep="\t", decimal=",")

## TopX

In [86]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if modeld["labelling"] is not None:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"], topx=True)
    else:
        labelled_results = pd.DataFrame((
            {
                "pdb": pdb,
                "pocket": pocket,
                **pocketd
            }
            for pdb, pockets in results.items()
            for pocket, pocketd in pockets.items()
        ))

    preds = {}
    for pdb in news:
        if pdb in ["4jqi", 'AF-A0A1D8PQM9-F1']: continue ##################################################################################
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            # Top1 pred for our model
            if model == "model5":
                pdbpreds.loc[:, "pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int)).values
            elif model == "allofusion":
                pdbpreds = pdbpreds.drop(
                    pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
                    .index[1:]
                )

            # if pdb is 7sns, if there's more than 1 label 1, keep only the pred one if exists, or just 1 in general
            if pdb == "7sns":
                if model == "allositepro":
                    idxs = (
                        pdbpreds.loc[pdbpreds.label == 1]
                        .sort_values("prob", ascending=False)
                        .index[1:]
                    )
                    pdbpreds.loc[idxs, "label"] = 0
                else:
                    pdbpreds = pdbpreds.drop(
                        pdbpreds.loc[pdbpreds.label == 1]
                        .sort_values("pred", ascending=False)
                        .index[1:]
                    )
                
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'8sgj': {'total': 28, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 13, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 20, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 69, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '5uak': {'total': 75, 'tp': 1, 'fn': 0, 'fp': 0}},
 'allositepro': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 0},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '7sns': {'tp': 1, 'fn': 0, 'fp': 2},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0}},
 'stingallo': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '7sns': {'tp': 0, 'fn': 1, 'fp': 3},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0}},
 'allofusion': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 2},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 4},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 8},
  '6yhr': {'tp': 1, 'fn': 0, 'fp': 10},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 2},
  '7sns': {'tp': 1, 'fn': 0, 'fp': 20},
  '5uak': {'tp': 1, 'fn': 0, 'fp': 16}},
 'passer_ensemble': {'8sgj': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'passer_automl': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 24, 'tp': 1, 'fn': 0, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'passer_rank': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 24, 'tp': 0, 'fn': 1, 'fp': 2},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'deepallo': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 24, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 40, 'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 18, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'alloses': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 20, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'mefallosite': {'8sgj': {'total': 47, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 19, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 33, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 84, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 19, 'tp': 0, 'fn': 1, 'fp': 2},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allo': {'8sgj': {'total': 21, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 14, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 8, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 15, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 58, 'tp': 0, 'fn': 1, 'fp': 1},
  '7sns': {'total': 6, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 53, 'tp': 1, 'fn': 0, 'fp': 0}}}

In [87]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [88]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
model5,model5,6,1,1,0.852718,0.926359,0 1 0 225 1 1 1 6
allo,allo,4,3,3,0.553571,0.776786,0 1 0 165 3 1 3 4
passer_automl,passer_automl,4,3,4,0.52612,0.762435,0 1 0 410 4 1 3 4
mefallosite,mefallosite,4,3,4,0.52461,0.761674,0 1 0 347 4 1 3 4
alloses,alloses,3,4,4,0.418815,0.709408,0 1 0 406 4 1 4 3
passer_ensemble,passer_ensemble,3,4,5,0.390066,0.694559,0 1 0 409 5 1 4 3
allofusion,allofusion,3,4,62,NaN,NaN,NaN
deepallo,deepallo,2,5,5,0.273369,0.636684,0 1 0 400 5 1 5 2
passer_rank,passer_rank,2,5,6,0.254011,0.626683,0 1 0 408 6 1 5 2
allositepro,allositepro,2,5,2,NaN,NaN,NaN
stingallo,stingallo,0,7,4,NaN,NaN,NaN

In [89]:
models_metrics.infer_objects().to_csv("models_metrics_topx.csv", index=False, sep="\t", decimal=",")

# Old

In [63]:
models_preds = {}

for model, modeld in models.items():
    results = modeld["results"]
    if "model5" not in model:
        labelled_results = label_results_topx(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = label_our_results_topx(results, **modeld["labelling"])

    preds = {}
    for pdb in news:
        pdbpreds = labelled_results.query(f"pdb == '{pdb}'")
        total = len(pdbpreds)
        if total > 0:
            if model == "allofusion":
                pdbpreds = pdbpreds.drop(
                    pdbpreds.loc[lambda x: (x.pred == 1) & (x.label == 1)]
                    .index[1:]
                )
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds[model] = preds

models_preds

{'model5': {'8sgj': {'total': 28, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 30, 'tp': 1, 'fn': 0, 'fp': 0},
  '7l6r': {'total': 14, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 13, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 20, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 69, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 2, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 75, 'tp': 1, 'fn': 0, 'fp': 0},
  '4jqi': {'total': 19, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allositepro': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 0},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '5b0u': {'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0},
  '4jqi': {'tp': 0, 'fn': 1, 'fp': 0}},
 'stingallo': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'tp': 0, 'fn': 1, 'fp': 0},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 0},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 0},
  '6yhr': {'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 0},
  '5b0u': {'tp': 0, 'fn': 1, 'fp': 0},
  '5uak': {'tp': 0, 'fn': 1, 'fp': 0},
  '4jqi': {'tp': 0, 'fn': 1, 'fp': 0}},
 'allofusion': {'8sgj': {'tp': 0, 'fn': 1, 'fp': 2},
  'AF-A0A1D8PQM9-F1': {'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'tp': 0, 'fn': 1, 'fp': 4},
  '8vw5': {'tp': 0, 'fn': 1, 'fp': 8},
  '6yhr': {'tp': 1, 'fn': 0, 'fp': 10},
  '7xlq': {'tp': 0, 'fn': 1, 'fp': 2},
  '5b0u': {'tp': 1, 'fn': 0, 'fp': 7},
  '5uak': {'tp': 1, 'fn': 0, 'fp': 16},
  '4jqi': {'tp': 0, 'fn': 1, 'fp': 5}},
 'passer_ensemble': {'8sgj': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'passer_automl': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'passer_rank': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'deepallo': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 24, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 22, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 40, 'tp': 0, 'fn': 1, 'fp': 1},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 27, 'tp': 0, 'fn': 1, 'fp': 1}},
 'alloses': {'8sgj': {'total': 54, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 23, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 22, 'tp': 0, 'fn': 1, 'fp': 1},
  '6yhr': {'total': 44, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 115, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 7, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 33, 'tp': 0, 'fn': 1, 'fp': 1}},
 'mefallosite': {'8sgj': {'total': 47, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 54, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 19, 'tp': 1, 'fn': 0, 'fp': 0},
  '8vw5': {'total': 17, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 33, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 84, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 4, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 139, 'tp': 0, 'fn': 1, 'fp': 1},
  '4jqi': {'total': 27, 'tp': 0, 'fn': 1, 'fp': 1}},
 'allo': {'8sgj': {'total': 21, 'tp': 1, 'fn': 0, 'fp': 0},
  'AF-A0A1D8PQM9-F1': {'total': 34, 'tp': 0, 'fn': 1, 'fp': 1},
  '7l6r': {'total': 14, 'tp': 0, 'fn': 1, 'fp': 1},
  '8vw5': {'total': 8, 'tp': 1, 'fn': 0, 'fp': 0},
  '6yhr': {'total': 15, 'tp': 1, 'fn': 0, 'fp': 0},
  '7xlq': {'total': 58, 'tp': 0, 'fn': 1, 'fp': 1},
  '5b0u': {'total': 2, 'tp': 0, 'fn': 1, 'fp': 1},
  '5uak': {'total': 53, 'tp': 1, 'fn': 0, 'fp': 0},
  '4jqi': {'total': 18, 'tp': 0, 'fn': 1, 'fp': 1}}}

In [64]:
from sklearn.metrics import matthews_corrcoef, f1_score, confusion_matrix

In [65]:
models_metrics = {}

for model, preds in models_preds.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics = pd.DataFrame(models_metrics).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics

,model,tp,fn,fp,mcc,macro-f1,confmat
model5,model5,6,3,3,0.655172,0.827586,0 1 0 258 3 1 3 6
mefallosite,mefallosite,4,5,5,0.432396,0.716198,0 1 0 410 5 1 5 4
allo,allo,4,5,5,0.42108,0.71054,0 1 0 209 5 1 5 4
passer_automl,passer_automl,3,6,6,0.320885,0.660443,0 1 0 476 6 1 6 3
alloses,alloses,3,6,6,0.320885,0.660443,0 1 0 476 6 1 6 3
allofusion,allofusion,3,6,55,NaN,NaN,NaN
passer_ensemble,passer_ensemble,2,7,7,0.207699,0.60385,0 1 0 475 7 1 7 2
passer_rank,passer_rank,2,7,7,0.207699,0.60385,0 1 0 475 7 1 7 2
deepallo,deepallo,2,7,7,0.207423,0.603712,0 1 0 466 7 1 7 2
allositepro,allositepro,1,8,1,NaN,NaN,NaN
stingallo,stingallo,0,9,1,NaN,NaN,NaN

In [66]:
models_metrics.infer_objects().to_csv("models_metrics_top1_apos_lenient_labelling.csv", index=False, sep=";", decimal=",")

## Top1

models_preds_top1 = {}

for model, modeld in models.items():
    results = modeld["results"]
    if "model5" not in model:
        labelled_results = label_results(results, **modeld["labelling"], prob_key=modeld["prob_key"])
    else:
        labelled_results = label_our_results(results, **modeld["labelling"])

    preds = {}
    for pdb in news:
        pdbpreds = pd.DataFrame(labelled_results.query(f"pdb == '{pdb}'"))
        total = len(pdbpreds)
        if total > 0:
            if modeld["prob_key"] is not None:
                pdbpreds["pred"] = pdbpreds[["prob"]].apply(lambda x: (x == x.max()).astype(int))
            tp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 1)] )
            fp = len( pdbpreds.loc[lambda x: (x["pred"] == 1) & (x["label"] == 0)] )
            fn = len( pdbpreds.loc[lambda x: (x["pred"] == 0) & (x["label"] == 1)] )
            if tp + fn == 0:
                fn = 1 # There's at least 1 allo. pocket per PDB
        else:
            tp, fp = 0, 0
            fn = 1 # There's at least 1 allo. pocket per PDB

        if total == 0 or not modeld["all_pockets_in_output"]:
            preds[pdb] = {
                "tp": tp,
                "fn": fn,
                "fp": fp
            }
        else:
            preds[pdb] = {
                "total": total,
                "tp": tp,
                "fn": fn,
                "fp": fp
            }

    models_preds_top1[model] = preds

models_preds_top1

{'8jp0': {'8sgj': ['A']},
 '8uk6': {'AF-A0A1D8PQM9-F1': ['A']},
 '8f4s': {'7l6r': ['A']},
 '7gqu': {'6yhr': ['A']},
 '7yg5': {'7xlq': ['A']},
 '8aq6': {'5b0u': ['A']},
 '8qni': {'2ldr': ['A']},
 '8v81': {'5uak': ['A']},
 '9dnm': {'4jqi': ['A']}}

models_metrics_top1 = {}

for model, preds in models_preds_top1.items():
    df = pd.DataFrame(preds).T
    
    if models[model]["all_pockets_in_output"]:
        y_true = [1] * df["tp"].sum() + [1] * df["fn"].sum() + [0] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())
        y_pred = [1] * df["tp"].sum() + [0] * df["fn"].sum() + [1] * df["fp"].sum() + [0] * (df["total"].sum() - df[["tp", "fn", "fp"]].sum().sum())

        models_metrics_top1[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
            "mcc": matthews_corrcoef(y_true, y_pred),
            "macro-f1": f1_score(y_true, y_pred, average="macro"),
            "confmat": pd.DataFrame(confusion_matrix(y_true, y_pred))
        }
        
    else:
        models_metrics_top1[model] = {
            "model": model,
            "tp": df["tp"].sum(),
            "fn": df["fn"].sum(),
            "fp": df["fp"].sum(),
        }

models_metrics_top1 = pd.DataFrame(models_metrics_top1).T.sort_values(["tp", "mcc"], ascending=False)
models_metrics_top1

models_metrics_top1.to_csv("models_metrics_top1_apos_lenient_labelling.csv", index=False)