In [1]:
basein = "bioemu_test_150_batch75"

In [1]:
import os, sys, subprocess
import pandas as pd
from tqdm.notebook import tqdm

In [3]:
sys.path.append("..")

In [10]:
from predict import \
get_cif, Cif, Site, get_pockets, Pocket, \
get_pdb_features, get_pockets_features, \
prepare_data, model, view_pockets
# get_features

# Ensembles

In [5]:
site_residues = [{"label_asym_id": "A", "label_seq_id": seqnum} for seqnum in ('73', '77', '78', '80', '81', '84', '85', '88', '109', '110', '111', '112', '113', '114', '232', '235', '236', '238', '239', '240', '241', '243', '248', '250', '251', '252', '253', '254', '255', '257', '258', '261', '262')]

## Only sc

### Tests

In [5]:
indir = f"{basein}/relax_nomd"

In [6]:
pdbf = f"{indir}/frame_0.pdb"

In [13]:
path = f"predict_0"

In [7]:
cif = get_cif(file=pdbf, path=path)
cif

In [20]:
clean_pdb = cif

In [21]:
os.system(f"cp {path}/frame_0_updated.cif {path}/frame_0.cif")
clean_pdb.filename = f"{path}/frame_0.cif"

In [23]:
# # Clean PDB
# protein_chains = protein_chains or pdb.residues.query(f"label_entity_id in {pdb._protein_entities}").label_asym_id.unique().tolist()

# clean_pdb = get_clean_pdb(
#     pdb,
#     protein_chains=protein_chains,
#     path=path
# )

# Pockets
pockets = get_pockets(
    clean_pdb,
    out=sys.stdout,
    path=path
)
pockets["pdb"] = clean_pdb.entry_id

In [27]:
os.makedirs(f"{path}/features/{clean_pdb.entry_id}", exist_ok=True)

In [28]:
# # ColabFold MSA if necessary:
# get_colabfold_msa(
#     clean_pdb,
#     email=email,
#     path=path
# )

os.system(f"cp ../predict/features/6t4k/HHBlitsF.pkl {path}/features/{clean_pdb.entry_id}/")

0

In [30]:
import subprocess

In [42]:
for feat in ['features', 'transferentropy', 'hhblits']:
    subprocess.run(f"python ../gradio/{feat}.py {clean_pdb.entry_id} {path}", shell=True, check=True)

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database
rmdb /tmp/tmp7q5ko6v6/tmp/18369195607934354183/pref_tmp_1

Time for processing: 0h 0m 0s 0ms
mergedbs /tmp/tmp7q5ko6v6/tmp/18369195607934354183/profile_0 /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_1 /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_0 /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_tmp_1

Merging the results to /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_1
[=================================================================] 1 0s 0ms
Time for merging to aln_1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 1ms
rmdb /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_0

Time for processing: 0h 0m 0s 0ms
rmdb /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_tmp_1

Time for processing: 0h 0m 0s 0ms
rmdb /tmp/tmp7q5ko6v6/tmp/18369195607934354183/pref_tmp_2

Time for processing: 0h 0m 0s 0ms
mergedbs /tmp/tmp7q5ko6v6/tmp/18369195607934354183/profile_1 /tmp/tmp7q5ko6v6/result /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_1 /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_tmp_2

Merging the results to /tmp/tmp7q5ko6v6/result
[=================================================================] 1 0s 0ms
Time for merging to result: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 0ms
rmdb /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_1

Time for processing: 0h 0m 0s 0ms
rmdb /tmp/tmp7q5ko6v6/tmp/18369195607934354183/aln_tmp_2

Time for processing: 0h 0m 0s 0ms
mvdb /tmp/tmp7q5ko6v6/tmp/latest/profile_1 /tmp/tmp7q5ko6v6/prof_res

MMseqs Version:	17.b804f
Verbosity	3

Time for processing: 0h 0m 0s 0ms
lndb /tmp/tmp7q5ko6v6/qdb_h /tmp/tmp7q5ko6v6/prof_res_h

MMseqs Version:	17.b804f
Verbosity	3

Time for processing: 0h 0m 0s 0ms

In [35]:
# # Features
# features = get_features(
#     clean_pdb,
#     path=path,
#     # uniref_path=uniref_path
# )

In [40]:
import pandas as pd

In [43]:
features = get_pdb_features(
    clean_pdb,
    sites = [pd.DataFrame(columns=clean_pdb.residues.columns),],
    features_path = path
)
features

           Residues                                                      \
    label_entity_id label_asym_id label_seq_id auth_asym_id auth_seq_id
0                 1             A            1            A           0
1                 1             A            2            A           1
2                 1             A            3            A           2
3                 1             A            4            A           3
4                 1             A            5            A           4
..              ...           ...          ...          ...         ...
258               1             A          259            A         258
259               1             A          260            A         259
260               1             A          261            A         260
261               1             A          262            A         261
262               1             A          263            A         262

                      Label     Amino acids                                  \
    pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C label_comp_id_D
0                   ?     0               0               0               0
1                   ?     0               0               0               0
2                   ?     0               0               0               0
3                   ?     0               0               0               0
4                   ?     0               0               0               0
..                ...   ...             ...             ...             ...
258                 ?     0               0               0               0
259                 ?     0               0               0               0
260                 ?     0               0               0               0
261                 ?     0               0               0               0
262                 ?     0               0               0               0

     ... HHBlits
     ...    M->M M->I M->D I->M I->I D->M D->D   Neff Neff_I Neff_D
0    ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.812    0.0    0.0
1    ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.812    0.0    0.0
2    ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  2.208    0.0    0.0
3    ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  3.134    0.0    0.0
4    ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  3.134    0.0    0.0
..   ...     ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
258  ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  5.503    0.0    0.0
259  ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  5.503    0.0    0.0
260  ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  5.503    0.0    0.0
261  ...     1.0  0.0  0.0  0.0  0.0  0.0  0.0  5.404    0.0    0.0
262  ...     1.0  0.0  0.0  1.0  0.0  0.0  0.0  4.968    0.0    0.0

[263 rows x 173 columns]

In [44]:
pockets_features = get_pockets_features(
    clean_pdb,
    pockets,
    features,
    path=path
)

In [45]:
data = prepare_data(pockets_features)

preds = model.predict_proba(data)[[1]].sort_values(1, ascending=False).rename(columns={1: "Allosteric score"})
preds.index = preds.index.map(lambda x: x.split("_")[-1])

preds

          Allosteric score
pocket2       3.383116e-01
pocket4       4.515884e-02
pocket1       2.359568e-02
pocket3       2.515104e-03
pocket5       1.055452e-03
pocket7       1.496603e-04
pocket8       1.192619e-05
pocket6       3.546163e-06
pocket9       1.404345e-07
pocket10      5.684562e-09

In [52]:
print(['73',
 '77',
 '78',
 '80',
 '81',
 '84',
 '85',
 '88',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '232',
 '235',
 '236',
 '238',
 '239',
 '240',
 '241',
 '243',
 '248',
 '250',
 '251',
 '252',
 '253',
 '254',
 '255',
 '257',
 '258',
 '261',
 '262'])

['73', '77', '78', '80', '81', '84', '85', '88', '109', '110', '111', '112', '113', '114', '232', '235', '236', '238', '239', '240', '241', '243', '248', '250', '251', '252', '253', '254', '255', '257', '258', '261', '262']

In [54]:
res_site = Site(
    pdb=clean_pdb,
    residues=[{"label_asym_id": "A", "label_seq_id": seqnum} for seqnum in ('73', '77', '78', '80', '81', '84', '85', '88', '109', '110', '111', '112', '113', '114', '232', '235', '236', '238', '239', '240', '241', '243', '248', '250', '251', '252', '253', '254', '255', '257', '258', '261', '262')],
    only_protein=True
)

In [55]:
v = view_pockets(
    clean_pdb,
    pockets={"pocket2": {"color": "green"}},
    site_residues=res_site.residues,
    path=path
)
v

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

### Loop

In [6]:
indir = f"{basein}/relax_nomd"

In [11]:
overlaps = {}

for i in range(8):
    pdbf = f"{indir}/frame_{i}.pdb"
    path = f"{indir}/predict_{i}"
    predsf = f"{path}/preds.pkl"
    
    clean_pdb = get_cif(file=pdbf, path=path)
    os.system(f"ln -s {clean_pdb.entry_id}_updated.cif {path}/{clean_pdb.entry_id}.cif")
    clean_pdb.filename = f"{path}/{clean_pdb.entry_id}.cif"

    if not os.path.isfile(predsf):
        pockets = get_pockets(
            clean_pdb,
            out=sys.stdout,
            path=path
        )
        pockets["pdb"] = clean_pdb.entry_id
    
        if i != 0:
            os.makedirs(f"{path}/features/{clean_pdb.entry_id}", exist_ok=True)
            os.system(f"ln -s ../../../predict_0/features/frame_0/HHBlitsF.pkl {path}/features/{clean_pdb.entry_id}/HHBlitsF.pkl")
    
        for feat in ['features', 'transferentropy', 'hhblits']:
            subprocess.run(f"python ../gradio/{feat}.py {clean_pdb.entry_id} {path}", shell=True, check=True)
    
        features = get_pdb_features(
            clean_pdb,
            sites = [pd.DataFrame(columns=clean_pdb.residues.columns),],
            features_path = path
        )
    
        pockets_features = get_pockets_features(
            clean_pdb,
            pockets,
            features,
            path=path
        )
    
        data = prepare_data(pockets_features)
    
        preds = model.predict_proba(data)[[1]].sort_values(1, ascending=False).rename(columns={1: "Allosteric score"})
        preds.index = preds.index.map(lambda x: x.split("_")[-1])
        
        preds.to_pickle(predsf)
    else:
        preds = pd.read_pickle(predsf)

    res_site = Site(
        pdb=clean_pdb,
        residues=site_residues,
        only_protein=True
    )

    topp = preds.iloc[0].name
    merge = (
        res_site.residues
        .merge(
            Pocket(f"{path}/{clean_pdb.entry_id}/{clean_pdb.entry_id}_out/pockets/{topp}_atm.cif")
            .residues
        )
    )
    overlaps[f"frame_{i}"] = {
        "pocket": topp,
        "overlap": len(merge) / len(res_site.residues),
        "merge": merge
    }

ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_0/frame_0.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_1/frame_1.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_2/frame_2.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_3/frame_3.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_4/frame_4.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_5/frame_5.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_6/frame_6.cif': File exists
ln: failed to create symbolic link 'bioemu_test_150_batch75/relax_nomd/predict_7/frame_7.cif': File exists

{'frame_0': {'pocket': 'pocket2',
  'overlap': 0.24242424242424243,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           MET             A                 ?            A
  4           CYS             A                 ?            A
  5           HIS             A                 ?            A
  6           TYR             A                 ?            A
  7           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          72               1           73
  1                  1          ALA          76               1           77
  2                  1          LEU          79               1           80
  3                  1          MET         113               1          114
  4                  1          CYS         231               1          232
  5                  1          HIS         234               1          235
  6                  1          TYR         257               1          258
  7                  1          PHE         261               1          262  },
 'frame_1': {'pocket': 'pocket1',
  'overlap': 0.3333333333333333,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            LEU             A                 ?            A
  2            ILE             A                 ?            A
  3            ALA             A                 ?            A
  4            MET             A                 ?            A
  5            CYS             A                 ?            A
  6            HIS             A                 ?            A
  7            ARG             A                 ?            A
  8            TYR             A                 ?            A
  9            LEU             A                 ?            A
  10           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          72               1           73
  1                   1          LEU          79               1           80
  2                   1          ILE          83               1           84
  3                   1          ALA         112               1          113
  4                   1          MET         113               1          114
  5                   1          CYS         231               1          232
  6                   1          HIS         234               1          235
  7                   1          ARG         237               1          238
  8                   1          TYR         257               1          258
  9                   1          LEU         260               1          261
  10                  1          PHE         261               1          262  },
 'frame_2': {'pocket': 'pocket4',
  'overlap': 0.12121212121212122,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           LEU             A                 ?            A
  1           MET             A                 ?            A
  2           CYS             A                 ?            A
  3           HIS             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          LEU          79               1           80
  1                  1          MET         113               1          114
  2                  1          CYS         231               1          232
  3                  1          HIS         234               1          235  },
 'frame_3': {'pocket': 'pocket1',
  'overlap': 0.2727272727272727,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           MET             A                 ?            A
  4           HIS             A                 ?            A
  5           ARG             A                 ?            A
  6           LEU             A                 ?            A
  7           PHE             A                 ?            A
  8           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          72               1           73
  1                  1          ALA          76               1           77
  2                  1          LEU          79               1           80
  3                  1          MET         113               1          114
  4                  1          HIS         234               1          235
  5                  1          ARG         237               1          238
  6                  1          LEU         238               1          239
  7                  1          PHE         253               1          254
  8                  1          TYR         257               1          258  },
 'frame_4': {'pocket': 'pocket1',
  'overlap': 0.7575757575757576,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            ALA             A                 ?            A
  2            LEU             A                 ?            A
  3            THR             A                 ?            A
  4            ILE             A                 ?            A
  5            GLN             A                 ?            A
  6            VAL             A                 ?            A
  7            LEU             A                 ?            A
  8            LYS             A                 ?            A
  9            ALA             A                 ?            A
  10           ALA             A                 ?            A
  11           MET             A                 ?            A
  12           CYS             A                 ?            A
  13           HIS             A                 ?            A
  14           VAL             A                 ?            A
  15           LEU             A                 ?            A
  16           GLN             A                 ?            A
  17           GLN             A                 ?            A
  18           VAL             A                 ?            A
  19           GLN             A                 ?            A
  20           PHE             A                 ?            A
  21           LEU             A                 ?            A
  22           TYR             A                 ?            A
  23           LEU             A                 ?            A
  24           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          72               1           73
  1                   1          ALA          76               1           77
  2                   1          LEU          79               1           80
  3                   1          THR          80               1           81
  4                   1          ILE          83               1           84
  5                   1          GLN          84               1           85
  6                   1          VAL          87               1           88
  7                   1          LEU         108               1          109
  8                   1          LYS         109               1          110
  9                   1          ALA         110               1          111
  10                  1          ALA         112               1          113
  11                  1          MET         113               1          114
  12                  1          CYS         231               1          232
  13                  1          HIS         234               1          235
  14                  1          VAL         235               1          236
  15                  1          LEU         238               1          239
  16                  1          GLN         239               1          240
  17                  1          GLN         242               1          243
  18                  1          VAL         249               1          250
  19                  1          GLN         250               1          251
  20                  1          PHE         253               1          254
  21                  1          LEU         256               1          257
  22                  1          TYR         257               1          258
  23                  1          LEU         260               1          261
  24                  1          PHE         261               1          262  },
 'frame_5': {'pocket': 'pocket1',
  'overlap': 0.0,
  'merge': Empty DataFrame
  Columns: [label_comp_id, label_asym_id, pdbx_PDB_ins_code, auth_asym_id, pdbx_PDB_model_num, auth_comp_id, auth_seq_id, label_entity_id, label_seq_id]
  Index: []},
 'frame_6': {'pocket': 'pocket1',
  'overlap': 0.06060606060606061,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           HIS             A                 ?            A
  1           LEU             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          HIS          77               1           78
  1                  1          LEU          79               1           80  },
 'frame_7': {'pocket': 'pocket1',
  'overlap': 0.2727272727272727,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           GLN             A                 ?            A
  4           MET             A                 ?            A
  5           CYS             A                 ?            A
  6           HIS             A                 ?            A
  7           PHE             A                 ?            A
  8           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          72               1           73
  1                  1          ALA          76               1           77
  2                  1          LEU          79               1           80
  3                  1          GLN          84               1           85
  4                  1          MET         113               1          114
  5                  1          CYS         231               1          232
  6                  1          HIS         234               1          235
  7                  1          PHE         253               1          254
  8                  1          TYR         257               1          258  }}

In [12]:
overlaps

{'frame_0': {'pocket': 'pocket2',
  'overlap': 0.24242424242424243,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           MET             A                 ?            A
  4           CYS             A                 ?            A
  5           HIS             A                 ?            A
  6           TYR             A                 ?            A
  7           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          72               1           73
  1                  1          ALA          76               1           77
  2                  1          LEU          79               1           80
  3                  1          MET         113               1          114
  4                  1          CYS         231               1          232
  5                  1          HIS         234               1          235
  6                  1          TYR         257               1          258
  7                  1          PHE         261               1          262  },
 'frame_1': {'pocket': 'pocket1',
  'overlap': 0.3333333333333333,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            LEU             A                 ?            A
  2            ILE             A                 ?            A
  3            ALA             A                 ?            A
  4            MET             A                 ?            A
  5            CYS             A                 ?            A
  6            HIS             A                 ?            A
  7            ARG             A                 ?            A
  8            TYR             A                 ?            A
  9            LEU             A                 ?            A
  10           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          72               1           73
  1                   1          LEU          79               1           80
  2                   1          ILE          83               1           84
  3                   1          ALA         112               1          113
  4                   1          MET         113               1          114
  5                   1          CYS         231               1          232
  6                   1          HIS         234               1          235
  7                   1          ARG         237               1          238
  8                   1          TYR         257               1          258
  9                   1          LEU         260               1          261
  10                  1          PHE         261               1          262  },
 'frame_2': {'pocket': 'pocket4',
  'overlap': 0.12121212121212122,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           LEU             A                 ?            A
  1           MET             A                 ?            A
  2           CYS             A                 ?            A
  3           HIS             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          LEU          79               1           80
  1                  1          MET         113               1          114
  2                  1          CYS         231               1          232
  3                  1          HIS         234               1          235  },
 'frame_3': {'pocket': 'pocket1',
  'overlap': 0.2727272727272727,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           MET             A                 ?            A
  4           HIS             A                 ?            A
  5           ARG             A                 ?            A
  6           LEU             A                 ?            A
  7           PHE             A                 ?            A
  8           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          72               1           73
  1                  1          ALA          76               1           77
  2                  1          LEU          79               1           80
  3                  1          MET         113               1          114
  4                  1          HIS         234               1          235
  5                  1          ARG         237               1          238
  6                  1          LEU         238               1          239
  7                  1          PHE         253               1          254
  8                  1          TYR         257               1          258  },
 'frame_4': {'pocket': 'pocket1',
  'overlap': 0.7575757575757576,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            ALA             A                 ?            A
  2            LEU             A                 ?            A
  3            THR             A                 ?            A
  4            ILE             A                 ?            A
  5            GLN             A                 ?            A
  6            VAL             A                 ?            A
  7            LEU             A                 ?            A
  8            LYS             A                 ?            A
  9            ALA             A                 ?            A
  10           ALA             A                 ?            A
  11           MET             A                 ?            A
  12           CYS             A                 ?            A
  13           HIS             A                 ?            A
  14           VAL             A                 ?            A
  15           LEU             A                 ?            A
  16           GLN             A                 ?            A
  17           GLN             A                 ?            A
  18           VAL             A                 ?            A
  19           GLN             A                 ?            A
  20           PHE             A                 ?            A
  21           LEU             A                 ?            A
  22           TYR             A                 ?            A
  23           LEU             A                 ?            A
  24           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          72               1           73
  1                   1          ALA          76               1           77
  2                   1          LEU          79               1           80
  3                   1          THR          80               1           81
  4                   1          ILE          83               1           84
  5                   1          GLN          84               1           85
  6                   1          VAL          87               1           88
  7                   1          LEU         108               1          109
  8                   1          LYS         109               1          110
  9                   1          ALA         110               1          111
  10                  1          ALA         112               1          113
  11                  1          MET         113               1          114
  12                  1          CYS         231               1          232
  13                  1          HIS         234               1          235
  14                  1          VAL         235               1          236
  15                  1          LEU         238               1          239
  16                  1          GLN         239               1          240
  17                  1          GLN         242               1          243
  18                  1          VAL         249               1          250
  19                  1          GLN         250               1          251
  20                  1          PHE         253               1          254
  21                  1          LEU         256               1          257
  22                  1          TYR         257               1          258
  23                  1          LEU         260               1          261
  24                  1          PHE         261               1          262  },
 'frame_5': {'pocket': 'pocket1',
  'overlap': 0.0,
  'merge': Empty DataFrame
  Columns: [label_comp_id, label_asym_id, pdbx_PDB_ins_code, auth_asym_id, pdbx_PDB_model_num, auth_comp_id, auth_seq_id, label_entity_id, label_seq_id]
  Index: []},
 'frame_6': {'pocket': 'pocket1',
  'overlap': 0.06060606060606061,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           HIS             A                 ?            A
  1           LEU             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          HIS          77               1           78
  1                  1          LEU          79               1           80  },
 'frame_7': {'pocket': 'pocket1',
  'overlap': 0.2727272727272727,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           GLN             A                 ?            A
  4           MET             A                 ?            A
  5           CYS             A                 ?            A
  6           HIS             A                 ?            A
  7           PHE             A                 ?            A
  8           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          72               1           73
  1                  1          ALA          76               1           77
  2                  1          LEU          79               1           80
  3                  1          GLN          84               1           85
  4                  1          MET         113               1          114
  5                  1          CYS         231               1          232
  6                  1          HIS         234               1          235
  7                  1          PHE         253               1          254
  8                  1          TYR         257               1          258  }}

In [20]:
i = 7
pocket = 1
v = view_pockets(
    Cif(f"frame_{i}", f"{indir}/predict_{i}/frame_{i}_updated.cif"),
    pockets={f"pocket{pocket}": {"color": "green"}},
    site_residues=pd.DataFrame(site_residues),#res_site.residues,
    path=f"{indir}/predict_{i}"
)
v

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

In [4]:
sorted(os.listdir(f"bioemu_big_ensemble/msmbuilder_clust/contacts_skbirch_umap/sidechain"))

['frame_0.pdb',
 'frame_1.pdb',
 'frame_10.pdb',
 'frame_11.pdb',
 'frame_12.pdb',
 'frame_13.pdb',
 'frame_14.pdb',
 'frame_15.pdb',
 'frame_16.pdb',
 'frame_17.pdb',
 'frame_18.pdb',
 'frame_2.pdb',
 'frame_3.pdb',
 'frame_4.pdb',
 'frame_5.pdb',
 'frame_6.pdb',
 'frame_7.pdb',
 'frame_8.pdb',
 'frame_9.pdb',
 'out_sidechain_rec.pdb',
 'out_sidechain_rec.xtc']

In [3]:
pd.read_pickle("bioemu_big_ensemble/msmbuilder_clust/contacts_skbirch_umap/predictions/frame_18/features/frame_18/HHBlitsF.pkl")

FileNotFoundError: [Errno 2] No such file or directory: 'bioemu_big_ensemble/msmbuilder_clust/contacts_skbirch_umap/predictions/frame_18/features/frame_18/HHBlitsF.pkl'

### Results

- Only 1 of the predicted pockets captures the allosteric site and is very big, but does not extend to the orthosteric site.
- Other sites with overlap of 27-33 are the adjacent orthosteric site.

## sc + minim

### Loop

In [21]:
indir = f"{basein}/relax_minim_parallel"

In [22]:
overlaps = {}

for i in range(8):
    pdbf = f"{indir}/frame_{i}.pdb"
    path = f"{indir}/predict_{i}"
    predsf = f"{path}/preds.pkl"
    
    clean_pdb = get_cif(file=pdbf, path=path)
    os.system(f"ln -s {clean_pdb.entry_id}_updated.cif {path}/{clean_pdb.entry_id}.cif")
    clean_pdb.filename = f"{path}/{clean_pdb.entry_id}.cif"

    if not os.path.isfile(predsf):
        pockets = get_pockets(
            clean_pdb,
            out=sys.stdout,
            path=path
        )
        pockets["pdb"] = clean_pdb.entry_id
    
        os.makedirs(f"{path}/features/{clean_pdb.entry_id}", exist_ok=True)
        os.system(f"ln -s ../../../../relax_nomd/predict_0/features/frame_0/HHBlitsF.pkl {path}/features/{clean_pdb.entry_id}/HHBlitsF.pkl")
    
        for feat in ['features', 'transferentropy', 'hhblits']:
            subprocess.run(f"python ../gradio/{feat}.py {clean_pdb.entry_id} {path}", shell=True, check=True)
    
        features = get_pdb_features(
            clean_pdb,
            sites = [pd.DataFrame(columns=clean_pdb.residues.columns),],
            features_path = path
        )
    
        pockets_features = get_pockets_features(
            clean_pdb,
            pockets,
            features,
            path=path
        )
    
        data = prepare_data(pockets_features)
    
        preds = model.predict_proba(data)[[1]].sort_values(1, ascending=False).rename(columns={1: "Allosteric score"})
        preds.index = preds.index.map(lambda x: x.split("_")[-1])
        
        preds.to_pickle(predsf)
    else:
        preds = pd.read_pickle(predsf)

    res_site = Site(
        pdb=clean_pdb,
        residues=site_residues,
        only_protein=True
    )

    topp = preds.iloc[0].name
    merge = (
        res_site.residues
        .merge(
            Pocket(f"{path}/{clean_pdb.entry_id}/{clean_pdb.entry_id}_out/pockets/{topp}_atm.cif")
            .residues
        )
    )
    overlaps[f"frame_{i}"] = {
        "pocket": topp,
        "overlap": len(merge) / len(res_site.residues),
        "merge": merge
    }

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

In [23]:
overlaps

{'frame_0': {'pocket': 'pocket6',
  'overlap': 0.15151515151515152,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           HIS             A                 ?            A
  4           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          73               1           73
  1                  1          ALA          77               1           77
  2                  1          LEU          80               1           80
  3                  1          HIS         235               1          235
  4                  1          TYR         258               1          258  },
 'frame_1': {'pocket': 'pocket2',
  'overlap': 0.3333333333333333,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            ALA             A                 ?            A
  2            LEU             A                 ?            A
  3            ALA             A                 ?            A
  4            MET             A                 ?            A
  5            CYS             A                 ?            A
  6            HIS             A                 ?            A
  7            ARG             A                 ?            A
  8            PHE             A                 ?            A
  9            TYR             A                 ?            A
  10           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          73               1           73
  1                   1          ALA          77               1           77
  2                   1          LEU          80               1           80
  3                   1          ALA         111               1          111
  4                   1          MET         114               1          114
  5                   1          CYS         232               1          232
  6                   1          HIS         235               1          235
  7                   1          ARG         238               1          238
  8                   1          PHE         254               1          254
  9                   1          TYR         258               1          258
  10                  1          PHE         262               1          262  },
 'frame_2': {'pocket': 'pocket1',
  'overlap': 0.3333333333333333,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            ALA             A                 ?            A
  2            LEU             A                 ?            A
  3            ILE             A                 ?            A
  4            MET             A                 ?            A
  5            CYS             A                 ?            A
  6            HIS             A                 ?            A
  7            ARG             A                 ?            A
  8            PHE             A                 ?            A
  9            TYR             A                 ?            A
  10           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          73               1           73
  1                   1          ALA          77               1           77
  2                   1          LEU          80               1           80
  3                   1          ILE          84               1           84
  4                   1          MET         114               1          114
  5                   1          CYS         232               1          232
  6                   1          HIS         235               1          235
  7                   1          ARG         238               1          238
  8                   1          PHE         254               1          254
  9                   1          TYR         258               1          258
  10                  1          PHE         262               1          262  },
 'frame_3': {'pocket': 'pocket1',
  'overlap': 0.2727272727272727,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           MET             A                 ?            A
  4           HIS             A                 ?            A
  5           LEU             A                 ?            A
  6           PHE             A                 ?            A
  7           TYR             A                 ?            A
  8           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          73               1           73
  1                  1          ALA          77               1           77
  2                  1          LEU          80               1           80
  3                  1          MET         114               1          114
  4                  1          HIS         235               1          235
  5                  1          LEU         239               1          239
  6                  1          PHE         254               1          254
  7                  1          TYR         258               1          258
  8                  1          PHE         262               1          262  },
 'frame_4': {'pocket': 'pocket3',
  'overlap': 0.15151515151515152,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           HIS             A                 ?            A
  1           LEU             A                 ?            A
  2           LEU             A                 ?            A
  3           ALA             A                 ?            A
  4           MET             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          HIS          78               1           78
  1                  1          LEU          80               1           80
  2                  1          LEU         109               1          109
  3                  1          ALA         113               1          113
  4                  1          MET         114               1          114  },
 'frame_5': {'pocket': 'pocket3',
  'overlap': 0.24242424242424243,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           HIS             A                 ?            A
  3           LEU             A                 ?            A
  4           GLN             A                 ?            A
  5           MET             A                 ?            A
  6           HIS             A                 ?            A
  7           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          73               1           73
  1                  1          ALA          77               1           77
  2                  1          HIS          78               1           78
  3                  1          LEU          80               1           80
  4                  1          GLN          85               1           85
  5                  1          MET         114               1          114
  6                  1          HIS         235               1          235
  7                  1          TYR         258               1          258  },
 'frame_6': {'pocket': 'pocket1',
  'overlap': 0.30303030303030304,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           MET             A                 ?            A
  4           HIS             A                 ?            A
  5           VAL             A                 ?            A
  6           ARG             A                 ?            A
  7           LEU             A                 ?            A
  8           TYR             A                 ?            A
  9           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          73               1           73
  1                  1          ALA          77               1           77
  2                  1          LEU          80               1           80
  3                  1          MET         114               1          114
  4                  1          HIS         235               1          235
  5                  1          VAL         236               1          236
  6                  1          ARG         238               1          238
  7                  1          LEU         239               1          239
  8                  1          TYR         258               1          258
  9                  1          PHE         262               1          262  },
 'frame_7': {'pocket': 'pocket1',
  'overlap': 0.42424242424242425,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            ALA             A                 ?            A
  2            LEU             A                 ?            A
  3            MET             A                 ?            A
  4            CYS             A                 ?            A
  5            HIS             A                 ?            A
  6            VAL             A                 ?            A
  7            ARG             A                 ?            A
  8            LEU             A                 ?            A
  9            ILE             A                 ?            A
  10           VAL             A                 ?            A
  11           PHE             A                 ?            A
  12           TYR             A                 ?            A
  13           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          73               1           73
  1                   1          ALA          77               1           77
  2                   1          LEU          80               1           80
  3                   1          MET         114               1          114
  4                   1          CYS         232               1          232
  5                   1          HIS         235               1          235
  6                   1          VAL         236               1          236
  7                   1          ARG         238               1          238
  8                   1          LEU         239               1          239
  9                   1          ILE         241               1          241
  10                  1          VAL         250               1          250
  11                  1          PHE         254               1          254
  12                  1          TYR         258               1          258
  13                  1          PHE         262               1          262  }}

In [29]:
i = 4
pocket = 3
v = view_pockets(
    Cif(f"frame_{i}", f"{indir}/predict_{i}/frame_{i}_updated.cif"),
    pockets={f"pocket{pocket}": {"color": "green"}},
    site_residues=pd.DataFrame(site_residues),#res_site.residues,
    path=f"{indir}/predict_{i}"
)
v

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

### Results

- Only 1 of the predicted pockets captures the allosteric site and is very big, and in this case extends to the orthosteric site.
- Interestingly, now it happens on frame_7 while in the previous it was frame_4, and now in frame_4 the pred. pocket is totally different.
- Other sites with overlap of 27-33 are the adjacent orthosteric site.

## sc + minim + equil

### Loop

In [31]:
indir = f"{basein}/relax_equil_parallel"

In [32]:
overlaps = {}

for i in tqdm(range(8)):
    pdbf = f"{indir}/frame_{i}.pdb"
    path = f"{indir}/predict_{i}"
    predsf = f"{path}/preds.pkl"
    
    clean_pdb = get_cif(file=pdbf, path=path)
    os.system(f"ln -s {clean_pdb.entry_id}_updated.cif {path}/{clean_pdb.entry_id}.cif")
    clean_pdb.filename = f"{path}/{clean_pdb.entry_id}.cif"

    if not os.path.isfile(predsf):
        pockets = get_pockets(
            clean_pdb,
            out=sys.stdout,
            path=path
        )
        pockets["pdb"] = clean_pdb.entry_id
    
        os.makedirs(f"{path}/features/{clean_pdb.entry_id}", exist_ok=True)
        os.system(f"ln -s ../../../../relax_nomd/predict_0/features/frame_0/HHBlitsF.pkl {path}/features/{clean_pdb.entry_id}/HHBlitsF.pkl")
    
        for feat in ['features', 'transferentropy', 'hhblits']:
            subprocess.run(f"python ../gradio/{feat}.py {clean_pdb.entry_id} {path}", shell=True, check=True)
    
        features = get_pdb_features(
            clean_pdb,
            sites = [pd.DataFrame(columns=clean_pdb.residues.columns),],
            features_path = path
        )
    
        pockets_features = get_pockets_features(
            clean_pdb,
            pockets,
            features,
            path=path
        )
    
        data = prepare_data(pockets_features)
    
        preds = model.predict_proba(data)[[1]].sort_values(1, ascending=False).rename(columns={1: "Allosteric score"})
        preds.index = preds.index.map(lambda x: x.split("_")[-1])
        
        preds.to_pickle(predsf)
    else:
        preds = pd.read_pickle(predsf)

    res_site = Site(
        pdb=clean_pdb,
        residues=site_residues,
        only_protein=True
    )

    topp = preds.iloc[0].name
    merge = (
        res_site.residues
        .merge(
            Pocket(f"{path}/{clean_pdb.entry_id}/{clean_pdb.entry_id}_out/pockets/{topp}_atm.cif")
            .residues
        )
    )
    overlaps[f"frame_{i}"] = {
        "pocket": topp,
        "overlap": len(merge) / len(res_site.residues),
        "merge": merge
    }

  0%|          | 0/8 [00:00<?, ?it/s]

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/prody/utilities/misctools.py:424: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2025 [Rosetta PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release 2025.24+release.8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 2025-06-06T09:20:57] retrieved from: http://www.pyrosetta.org
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Reading PDB file...         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing PDB dataframe... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Initializing graph...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Constructing edges...       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.ubuntu.cxx11thread.serialization.Ubuntu.python311.Release r403 2025.24+release.8e1e5e54f0 8e1e5e54f047b0833dcf760a5cd5d3ce94d63938 http://www.pyrosetta.org 2025-06-06T09:20:57
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -mute core.pack basic core.scoring -ignore_zero_occupancy false -database /home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/pyrosetta/database

In [33]:
overlaps

{'frame_0': {'pocket': 'pocket1',
  'overlap': 0.0,
  'merge': Empty DataFrame
  Columns: [label_comp_id, label_asym_id, pdbx_PDB_ins_code, auth_asym_id, pdbx_PDB_model_num, auth_comp_id, auth_seq_id, label_entity_id, label_seq_id]
  Index: []},
 'frame_1': {'pocket': 'pocket1',
  'overlap': 0.5454545454545454,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            TRP             A                 ?            A
  1            ALA             A                 ?            A
  2            LEU             A                 ?            A
  3            ILE             A                 ?            A
  4            ALA             A                 ?            A
  5            MET             A                 ?            A
  6            CYS             A                 ?            A
  7            HIS             A                 ?            A
  8            VAL             A                 ?            A
  9            LEU             A                 ?            A
  10           GLN             A                 ?            A
  11           GLN             A                 ?            A
  12           VAL             A                 ?            A
  13           GLN             A                 ?            A
  14           PHE             A                 ?            A
  15           TYR             A                 ?            A
  16           LEU             A                 ?            A
  17           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          TRP          73               1           73
  1                   1          ALA          77               1           77
  2                   1          LEU          80               1           80
  3                   1          ILE          84               1           84
  4                   1          ALA         113               1          113
  5                   1          MET         114               1          114
  6                   1          CYS         232               1          232
  7                   1          HIS         235               1          235
  8                   1          VAL         236               1          236
  9                   1          LEU         239               1          239
  10                  1          GLN         240               1          240
  11                  1          GLN         243               1          243
  12                  1          VAL         250               1          250
  13                  1          GLN         251               1          251
  14                  1          PHE         254               1          254
  15                  1          TYR         258               1          258
  16                  1          LEU         261               1          261
  17                  1          PHE         262               1          262  },
 'frame_2': {'pocket': 'pocket1',
  'overlap': 0.18181818181818182,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           LEU             A                 ?            A
  1           ILE             A                 ?            A
  2           MET             A                 ?            A
  3           HIS             A                 ?            A
  4           TYR             A                 ?            A
  5           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          LEU          80               1           80
  1                  1          ILE          84               1           84
  2                  1          MET         114               1          114
  3                  1          HIS         235               1          235
  4                  1          TYR         258               1          258
  5                  1          PHE         262               1          262  },
 'frame_3': {'pocket': 'pocket1',
  'overlap': 0.2727272727272727,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           LYS             A                 ?            A
  1           ALA             A                 ?            A
  2           GLY             A                 ?            A
  3           MET             A                 ?            A
  4           CYS             A                 ?            A
  5           HIS             A                 ?            A
  6           VAL             A                 ?            A
  7           LEU             A                 ?            A
  8           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          LYS         110               1          110
  1                  1          ALA         111               1          111
  2                  1          GLY         112               1          112
  3                  1          MET         114               1          114
  4                  1          CYS         232               1          232
  5                  1          HIS         235               1          235
  6                  1          VAL         236               1          236
  7                  1          LEU         261               1          261
  8                  1          PHE         262               1          262  },
 'frame_4': {'pocket': 'pocket5',
  'overlap': 0.0,
  'merge': Empty DataFrame
  Columns: [label_comp_id, label_asym_id, pdbx_PDB_ins_code, auth_asym_id, pdbx_PDB_model_num, auth_comp_id, auth_seq_id, label_entity_id, label_seq_id]
  Index: []},
 'frame_5': {'pocket': 'pocket10',
  'overlap': 0.24242424242424243,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           HIS             A                 ?            A
  2           LEU             A                 ?            A
  3           ILE             A                 ?            A
  4           MET             A                 ?            A
  5           HIS             A                 ?            A
  6           ARG             A                 ?            A
  7           PHE             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          73               1           73
  1                  1          HIS          78               1           78
  2                  1          LEU          80               1           80
  3                  1          ILE          84               1           84
  4                  1          MET         114               1          114
  5                  1          HIS         235               1          235
  6                  1          ARG         238               1          238
  7                  1          PHE         262               1          262  },
 'frame_6': {'pocket': 'pocket4',
  'overlap': 0.06060606060606061,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           LYS             A                 ?            A
  1           ALA             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          LYS         110               1          110
  1                  1          ALA         111               1          111  },
 'frame_7': {'pocket': 'pocket1',
  'overlap': 0.15151515151515152,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           TRP             A                 ?            A
  1           ALA             A                 ?            A
  2           LEU             A                 ?            A
  3           PHE             A                 ?            A
  4           TYR             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          TRP          73               1           73
  1                  1          ALA          77               1           77
  2                  1          LEU          80               1           80
  3                  1          PHE         254               1          254
  4                  1          TYR         258               1          258  }}

In [44]:
i = 7
pocket = 1
v = view_pockets(
    Cif(f"frame_{i}", f"{indir}/predict_{i}/frame_{i}_updated.cif"),
    pockets={f"pocket{pocket}": {"color": "green"}},
    site_residues=pd.DataFrame(site_residues),#res_site.residues,
    path=f"{indir}/predict_{i}"
)
v

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

### Results

- No real allosteric-overlapping predicted pockets.
- Maybe the more physics-based relaxation leads the structure more towards the same conformation.