# Imports

In [4]:
import os, re, tempfile
from pathlib import Path
import subprocess as sp
import pandas as pd
# import argparse
# import gzip
# import os
# import shutil

# import sys
# import tempfile

from typing import List, Tuple, Optional
# 

from schrodinger import structure as sstruct

SCHRO = "/opt/schrodinger2025-2"

In [5]:
outdir = Path("dldocking")
outdir.mkdir(exist_ok=True)

## Data

In [6]:
extra_holos_featuresd = pd.read_pickle("../training_data/7.Extra_set/features.pkl")
extra_holos_featuresd

{'7gqu':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       7gqu               1             A           12            A
 1       7gqu               1             A           13            A
 2       7gqu               1             A           14            A
 3       7gqu               1             A           15            A
 4       7gqu               1             A           16            A
 ..       ...             ...           ...          ...          ...
 414     7gqu               1             A          426            A
 415     7gqu               1             A          427            A
 416     7gqu               1             A          428            A
 417     7gqu               1             A          429            A
 418     7gqu               1             A          430            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0           527                 ?     0               0               0  ...
 1           528                 ?     0               0               0  ...
 2           529                 ?     0               0               0  ...
 3           530                 ?     0               0               0  ...
 4           531                 ?     0               1               0  ...
 ..          ...               ...   ...             ...             ...  ...
 414         941                 ?     0               0               0  ...
 415         942                 ?     0               0               0  ...
 416         943                 ?     0               0               0  ...
 417         944                 ?     0               0               0  ...
 418         945                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.992404  0.000000  0.007872  0.000000  0.000000  0.000000  0.000000
 1    0.970634  0.000000  0.029688  0.000000  0.000000  0.000000  1.000000
 2    0.984184  0.016020  0.000000  0.317098  0.683020  0.677362  0.322641
 3    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
 4    0.983502  0.008717  0.007775  0.564091  0.435879  0.515842  0.483974
 ..        ...       ...       ...       ...       ...       ...       ...
 414  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 415  0.995850  0.004349  0.000000  1.000000  0.000000  0.000000  0.000000
 416  0.995160  0.000000  0.004849  0.000000  0.000000  0.000000  0.000000
 417  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 418  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


        Neff Neff_I Neff_D
 0    11.507  0.000  0.000
 1    11.647  0.000  1.004
 2    11.184  1.054  1.083
 3    11.324  0.000  1.019
 4    11.412  1.024  1.019
 ..      ...    ...    ...
 414  11.186  0.000  1.038
 415  10.451  1.004  0.000
 416  10.892  0.000  0.000
 417  11.436  0.000  1.004
 418  10.967  0.000  0.000

 [419 rows x 174 columns],
 '7yg5':      Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0        7yg5               1             A           76            A
 1        7yg5               1             A           77            A
 2        7yg5               1             A           78            A
 3        7yg5               1             A           79            A
 4        7yg5               1             A           80            A
 ...       ...             ...           ...          ...          ...
 1314     7yg5               1             A         1867            A
 1315     7yg5               1             A         1868            A
 1316     7yg5               1             A         1869            A
 1317     7yg5               1             A         1870            A
 1318     7yg5               1             A         1871            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             76                 ?     0               0               0  ...
 1             77                 ?     0               0               0  ...
 2             78                 ?     0               0               0  ...
 3             79                 ?     0               0               0  ...
 4             80                 ?     0               0               0  ...
 ...          ...               ...   ...             ...             ...  ...
 1314        1867                 ?     0               0               0  ...
 1315        1868                 ?     0               0               0  ...
 1316        1869                 ?     0               0               0  ...
 1317        1870                 ?     0               1               0  ...
 1318        1871                 ?     0               1               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0     0.997923  0.001115  0.000782  1.000000  0.000000  0.071051  0.929161
 1     0.988971  0.007325  0.003434  0.274904  0.724973  0.310357  0.689680
 2     0.985549  0.008520  0.005723  0.248445  0.751581  0.323536  0.676424
 3     0.992404  0.001790  0.006012  0.064614  0.935623  0.087595  0.912565
 4     0.991030  0.006263  0.002367  0.261159  0.738669  0.184156  0.815637
 ...        ...       ...       ...       ...       ...       ...       ...
 1314  0.982140  0.017787  0.000000  1.000000  0.000000  0.117522  0.882703
 1315  0.996540  0.002181  0.001338  0.190782  0.809442  0.361985  0.638164
 1316  0.953960  0.046007  0.000000  0.933033  0.067265  0.057472  0.942785
 1317  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
 1318  0.997231  0.002726  0.000000  0.247757  0.752102  0.075992  0.924023


        Neff Neff_I Neff_D
 0     8.362  1.001  1.129
 1     8.411  1.018  1.123
 2     8.575  1.019  1.097
 3     8.609  1.006  1.076
 4     8.642  1.024  1.090
 ...     ...    ...    ...
 1314  6.021  1.025  1.115
 1315  6.050  1.002  1.102
 1316  6.077  1.052  1.066
 1317  6.077  0.000  1.062
 1318  6.078  1.003  1.062

 [1319 rows x 174 columns],
 '8aq6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8aq6               1             G           11            G
 1       8aq6               1             G           12            G
 2       8aq6               1             G           13            G
 3       8aq6               1             G           14            G
 4       8aq6               1             G           15            G
 ..       ...             ...           ...          ...          ...
 166     8aq6               1             G          177            G
 167     8aq6               1             G          178            G
 168     8aq6               1             G          179            G
 169     8aq6               1             G          180            G
 170     8aq6               1             G          181            G

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            -1                 ?     0               0               0  ...
 1             0                 ?     0               0               0  ...
 2             1                 ?     0               0               0  ...
 3             2                 ?     0               0               0  ...
 4             3                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 166         165                 ?     0               0               0  ...
 167         166                 ?     0               0               0  ...
 168         167                 ?     1               0               0  ...
 169         168                 ?     0               0               0  ...
 170         169                 ?     0               1               0  ...

       HHBlits                                                                  \
          M->M      M->I      M->D      I->M      I->I D->M D->D   Neff Neff_I
 0    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  6.039  0.000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.096  0.000
 2    0.998615  0.000000  0.001522  0.000000  0.000000  0.0  0.0  8.233  0.000
 3    0.988971  0.010866  0.000000  0.227037  0.773246  0.0  1.0  8.232  1.017
 4    0.980779  0.006551  0.012578  1.000000  0.000000  1.0  0.0  7.877  1.005
 ..        ...       ...       ...       ...       ...  ...  ...    ...    ...
 166  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 167  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 168  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 169  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 170  1.000000  0.000000  0.000000  1.000000  0.000000  0.0  0.0  1.000  0.000


     Neff_D
 0    0.000
 1    0.000
 2    0.000
 3    1.000
 4    1.011
 ..     ...
 166  0.000
 167  0.000
 168  0.000
 169  0.000
 170  0.000

 [171 rows x 174 columns],
 '8f4s':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8f4s               1             A            4            A
 1       8f4s               1             A            5            A
 2       8f4s               1             A            6            A
 3       8f4s               1             A            7            A
 4       8f4s               1             A            8            A
 ..       ...             ...           ...          ...          ...
 293     8f4s               1             A          297            A
 294     8f4s               1             A          298            A
 295     8f4s               1             A          299            A
 296     8f4s               1             A          300            A
 297     8f4s               1             A          301            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0          6799                 ?     0               0               0  ...
 1          6800                 ?     0               0               0  ...
 2          6801                 ?     0               0               0  ...
 3          6802                 ?     0               1               0  ...
 4          6803                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 293        7092                 ?     0               0               0  ...
 294        7093                 ?     0               0               0  ...
 295        7094                 ?     0               0               0  ...
 296        7095                 ?     0               0               0  ...
 297        7096                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.974004  0.000000  0.026278  0.000000  0.000000  0.000000  1.000000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.832776  0.167009
 2    0.967947  0.013304  0.019024  1.000000  0.000000  0.000000  1.000000
 3    0.979420  0.012595  0.008077  1.000000  0.000000  0.446583  0.553249
 4    0.977386  0.022640  0.000000  0.333325  0.666649  0.405564  0.594604
 ..        ...       ...       ...       ...       ...       ...       ...
 293  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 294  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 295  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 296  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 297  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


       Neff Neff_I Neff_D
 0    7.678  0.000  1.007
 1    8.325  0.000  1.081
 2    8.371  1.064  1.007
 3    8.851  1.103  1.080
 4    8.999  1.041  1.076
 ..     ...    ...    ...
 293  2.301  0.000  0.000
 294  2.301  0.000  0.000
 295  2.301  0.000  0.000
 296  2.131  0.000  0.000
 297  2.025  0.000  0.000

 [298 rows x 174 columns],
 '8jp0':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8jp0               1             A           51            A
 1       8jp0               1             A           52            A
 2       8jp0               1             A           53            A
 3       8jp0               1             A           54            A
 4       8jp0               1             A           55            A
 ..       ...             ...           ...          ...          ...
 714     8jp0               1             A          933            A
 715     8jp0               1             A          934            A
 716     8jp0               1             A          935            A
 717     8jp0               1             A          936            A
 718     8jp0               1             A          937            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            51                 ?     0               0               0  ...
 1            52                 ?     0               0               0  ...
 2            53                 ?     0               0               0  ...
 3            54                 ?     0               0               0  ...
 4            55                 ?     0               0               1  ...
 ..          ...               ...   ...             ...             ...  ...
 714         933                 ?     0               0               0  ...
 715         934                 ?     0               0               0  ...
 716         935                 ?     0               0               0  ...
 717         936                 ?     0               0               0  ...
 718         937                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.944092  0.023389  0.032577  0.520150  0.479632  0.208050  0.791686
 1    0.969962  0.007620  0.022718  0.396667  0.603322  0.224845  0.775393
 2    0.898755  0.088634  0.012595  0.181873  0.817902  0.261521  0.738669
 3    0.981459  0.013725  0.004629  0.559419  0.440740  0.255430  0.744323
 4    0.991717  0.003901  0.004537  0.302918  0.697372  0.243164  0.756808
 ..        ...       ...       ...       ...       ...       ...       ...
 714  0.995160  0.002707  0.001924  1.000000  0.000000  1.000000  0.000000
 715  0.997923  0.000000  0.002213  0.000000  0.000000  1.000000  0.000000
 716  0.981459  0.018453  0.000000  1.000000  0.000000  0.000000  1.000000
 717  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 718  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


       Neff Neff_I Neff_D
 0    6.153  1.060  1.203
 1    6.275  1.022  1.246
 2    6.314  1.319  1.265
 3    6.353  1.083  1.229
 4    6.468  1.009  1.186
 ..     ...    ...    ...
 714  8.194  1.002  1.096
 715  7.700  0.000  1.007
 716  6.919  1.017  1.001
 717  5.703  0.000  1.001
 718  5.823  0.000  0.000

 [719 rows x 174 columns],
 '8qni':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8qni               1             A            5            A
 1       8qni               1             A            6            A
 2       8qni               1             A            7            A
 3       8qni               1             A            8            A
 4       8qni               1             A            9            A
 ..       ...             ...           ...          ...          ...
 372     8qni               1             A          383            A
 373     8qni               1             A          384            A
 374     8qni               1             A          385            A
 375     8qni               1             A          386            A
 376     8qni               1             A          387            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            38                 ?     0               0               0  ...
 1            39                 ?     0               1               0  ...
 2            40                 ?     0               1               0  ...
 3            41                 ?     0               1               0  ...
 4            42                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 372         416                 ?     0               0               0  ...
 373         417                 ?     0               0               0  ...
 374         418                 ?     0               0               0  ...
 375         419                 ?     0               0               0  ...
 376         420                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.920188  0.011858  0.068157  0.500000  0.500000  0.000000  0.000000
 1    0.982821  0.003552  0.013850  0.250000  0.750019  0.882091  0.118093
 2    0.865137  0.053586  0.081447  0.267943  0.732043  0.770571  0.229410
 3    0.961261  0.038607  0.000000  0.547147  0.452817  0.872363  0.127627
 4    1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 ..        ...       ...       ...       ...       ...       ...       ...
 372  0.988971  0.007448  0.003895  0.430475  0.569592  0.405564  0.594604
 373  0.993092  0.004459  0.002436  1.000000  0.000000  0.434672  0.565265
 374  0.987601  0.009685  0.002568  0.411796  0.588453  0.245535  0.754190
 375  0.996540  0.003550  0.000000  0.163119  0.836826  0.466193  0.533663
 376  0.986917  0.009355  0.003379  0.631564  0.368312  0.147726  0.852044


        Neff Neff_I Neff_D
 0     3.752  1.002  0.000
 1     4.080  1.000  1.044
 2     4.267  1.074  1.020
 3     4.652  1.068  1.136
 4     4.565  0.000  1.013
 ..      ...    ...    ...
 372  11.384  1.022  1.087
 373  11.417  1.012  1.066
 374  11.485  1.023  1.044
 375  11.526  1.007  1.040
 376  11.540  1.014  1.019

 [377 rows x 174 columns],
 '8uk6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8uk6               1             A          233            A
 1       8uk6               1             A          234            A
 2       8uk6               1             A          235            A
 3       8uk6               1             A          236            A

In [7]:
extra_holos_sites = {k: v for k, v in pd.read_pickle("../training_data/7.Extra_set/news_sites.pkl").items() if k in extra_holos_featuresd}
extra_holos_sites

{'7gqu': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
   3420           X1L             D               4            .

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   3420                 ?        1002          X1L            A

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   3420                  1             1002                       ?

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   3420                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            VAL             A               1           55                 ?
   1            MET             A               1           56                 ?
   2            ALA             A               1           57                 ?
   3            THR             A               1          188                 ?
   4            ALA             A               1          189                 ?
   5            THR             A               1          190                 ?
   6            ALA             A               1          191                 ?
   7            SER             A               1          192                 ?
   8            ARG             A               1          196                 ?
   9            ILE             A               1          210                 ?
   10           THR             A               1          211                 ?
   11           CYS             A               1          212                 ?
   12           THR             A               1          213                 ?
   13           GLY             A               1          214                 ?
   14           ASP             A               1          329                 ?
   15           MET             A               1          330                 ?
   16           GLU             A               1          331                 ?
   17           SER             A               1          332                 ?
   18           TYR             A               1          334                 ?
   19           GLN             A               1          335                 ?
   20           TYR             A               1          376                 ?
   21           MET             A               1          380                 ?
   22           LYS             A               1          383                 ?
   23           ILE             A               1          398                 ?
   24           HIS             A               1          401                 ?
   25           PHE             A               1          402                 ?
   26           GLU             A               1          403                 ?
   27           ASP             A               1          404                 ?
   28           LYS             A               1          405                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0          570          VAL            A                  1               55
   1          571          MET            A                  1               56
   2          572          ALA            A                  1               57
   3          703          THR            A                  1              188
   4          704          ALA            A                  1              189
   5          705          THR            A                  1              190
   6          706          ALA            A                  1              191
   7          707          SER            A                  1              192
   8          711          ARG            A                  1              196
   9          725          ILE            A                  1              210
   10         726          THR            A                  1              211
   11         727          CYS            A                  1              212
   12         728          THR            A                  1              213
   13         729          GLY            A                  1              214
   14         844          ASP            A                  1              329
   15         845          MET            A                  1              330
   16         846          GLU            A                  1              331
   17         847          SER            A                  1              332
   18         849          TYR            A                  1              334
   19         850          GLN            A                  1              335
   20         891          TYR            A                  1              376
   21         895          MET            A                  1              380
   22         898          LYS            A                  1              383
   23         913          ILE            A                  1              398
   24         916          HIS            A                  1              401
   25         917          PHE            A                  1              402
   26         918          GLU            A                  1              403
   27         919          ASP            A                  1              404
   28         920          LYS            A                  1              405

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q14191                    570
   1                      UNP                 Q14191                    571
   2                      UNP                 Q14191                    572
   3                      UNP                 Q14191                    703
   4                      UNP                 Q14191                    704
   5                      UNP                 Q14191                    705
   6                      UNP                 Q14191                    706
   7                      UNP                 Q14191                    707
   8                      UNP                 Q14191                    711
   9                      UNP                 Q14191                    725
   10                     UNP                 Q14191                    726
   11                     UNP                 Q14191                    727
   12                     UNP                 Q14191                    728
   13                     UNP                 Q14191                    729
   14                     UNP                 Q14191                    844
   15                     UNP                 Q14191                    845
   16                     UNP                 Q14191                    846
   17                     UNP                 Q14191                    847
   18                     UNP                 Q14191                    849
   19                     UNP                 Q14191                    850
   20                     UNP                 Q14191                    891
   21                     UNP                 Q14191                    895
   22                     UNP                 Q14191                    898
   23                     UNP                 Q14191                    913
   24                     UNP                 Q14191                    916
   25                     UNP                 Q14191                    917
   26                     UNP                 Q14191                    918
   27                     UNP                 Q14191                    919
   28                     UNP                 Q14191                    920

      pdbx_sifts_xref_db_res
   0                       V
   1                       M
   2                       A
   3                       T
   4                       A
   5                       T
   6                       A
   7                       S
   8                       R
   9                       I
   10                      T
   11                      C
   12                      T
   13                      G
   14                      D
   15                      M
   16                      E
   17                      S
   18                      Y
   19                      Q
   20                      Y
   21                      M
   22                      K
   23                      I
   24                      H
   25                      F
   26                      E
   27                      D
   28                      K  }],
 '7yg5': [{'mod':       label_comp_id label_asym_id label_entity_id label_seq_id  \
   20113           TOR             V              10            .

         pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   20113                 ?        2416          TOR            A

         pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   20113                  1             2416                       ?

         pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   20113                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ILE             A               1          209                 ?
   1            VAL             A               1          210                 ?
   2            SER             A               1          213                 ?
   3            ILE             A               1          214                 ?
   4            ALA             A               1          217                 ?
   5            GLU             A               1          353                 ?
   6            PHE             A               1          354                 ?
   7            GLU             A               1          357                 ?
   8            ARG             A               1          358                 ?
   9            ARG             A               1          360                 ?
   10           ASN             A               1          363                 ?
   11           SER             A               1          595                 ?
   12           LEU             A               1          596                 ?
   13           SER             A               1          599                 ?
   14           MET             A               1          600                 ?
   15           LYS             A               1          601                 ?
   16           SER             A               1          602                 ?
   17           ILE             A               1          603                 ?
   18           ILE             A               1          604                 ?
   19           LEU             A               1          606                 ?
   20           ASN             A               1          696                 ?
   21           VAL             A               1          697                 ?
   22           LEU             A               1          699                 ?
   23           ALA             A               1          700                 ?
   24           ILE             A               1          701                 ?
   25           ALA             A               1          702                 ?
   26           VAL             A               1          703                 ?
   27           ASP             A               1          704                 ?
   28           ASN             A               1          705                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0          209          ILE            A                  1              209
   1          210          VAL            A                  1              210
   2          213          SER            A                  1              213
   3          214          ILE            A                  1              214
   4          217          ALA            A                  1              217
   5          353          GLU            A                  1              353
   6          354          PHE            A                  1              354
   7          357          GLU            A                  1              357
   8          358          ARG            A                  1              358
   9          360          ARG            A                  1              360
   10         363          ASN            A                  1              363
   11         595          SER            A                  1              595
   12         596          LEU            A                  1              596
   13         599          SER            A                  1              599
   14         600          MET            A                  1              600
   15         601          LYS            A                  1              601
   16         602          SER            A                  1              602
   17         603          ILE            A                  1              603
   18         604          ILE            A                  1              604
   19         606          LEU            A                  1              606
   20         696          ASN            A                  1              696
   21         697          VAL            A                  1              697
   22         699          LEU            A                  1              699
   23         700          ALA            A                  1              700
   24         701          ILE            A                  1              701
   25         702          ALA            A                  1              702
   26         703          VAL            A                  1              703
   27         704          ASP            A                  1              704
   28         705          ASN            A                  1              705

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q15878                    209
   1                      UNP                 Q15878                    210
   2                      UNP                 Q15878                    213
   3                      UNP                 Q15878                    214
   4                      UNP                 Q15878                    217
   5                      UNP                 Q15878                    353
   6                      UNP                 Q15878                    354
   7                      UNP                 Q15878                    357
   8                      UNP                 Q15878                    358
   9                      UNP                 Q15878                    360
   10                     UNP                 Q15878                    363
   11                     UNP                 Q15878                    595
   12                     UNP                 Q15878                    596
   13                     UNP                 Q15878                    599
   14                     UNP                 Q15878                    600
   15                     UNP                 Q15878                    601
   16                     UNP                 Q15878                    602
   17                     UNP                 Q15878                    603
   18                     UNP                 Q15878                    604
   19                     UNP                 Q15878                    606
   20                     UNP                 Q15878                    696
   21                     UNP                 Q15878                    697
   22                     UNP                 Q15878                    699
   23                     UNP                 Q15878                    700
   24                     UNP                 Q15878                    701
   25                     UNP                 Q15878                    702
   26                     UNP                 Q15878                    703
   27                     UNP                 Q15878                    704
   28                     UNP                 Q15878                    705

      pdbx_sifts_xref_db_res
   0                       I
   1                       V
   2                       S
   3                       I
   4                       A
   5                       E
   6                       F
   7                       E
   8                       R
   9                       R
   10                      N
   11                      S
   12                      L
   13                      S
   14                      M
   15                      K
   16                      S
   17                      I
   18                      I
   19                      L
   20                      N
   21                      V
   22                      L
   23                      A
   24                      I
   25                      A
   26                      V
   27                      D
   28                      N  }],
 '8aq6': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
   1349           NT0            IA               7            .

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   1349                 ?         301          NT0            G

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   1349                  1              301                       ?

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   1349                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ASP             G               1           21                 ?
   1            TRP             G               1           22                 ?
   2            ARG             G               1           23                 ?
   3            ILE             G               1           53                 ?
   4            ARG             G               1           55                 ?
   5            ASP             G               1           67                 ?
   6            HIS             G               1           69                 ?
   7            ILE             G               1           71                 ?
   8            TYR             G               1           93                 ?
   9            PRO             G               1           94                 ?
   10           VAL             G               1           95                 ?
   11           PHE             G               1          100                 ?
   12           LYS             G               1          101                 ?
   13           ILE             G               1          103                 ?
   14           TYR             G               1          106                 ?
   15           ILE             G               1          179                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0            9          ASP            G                  1               21
   1           10          TRP            G                  1               22
   2           11          ARG            G                  1               23
   3           41          ILE            G                  1               53
   4           43          ARG            G                  1               55
   5           55          ASP            G                  1               67
   6           57          HIS            G                  1               69
   7           59          ILE            G                  1               71
   8           81          TYR            G                  1               93

In [8]:
apos = pd.read_pickle(f"pdb_ensemble/apos.pkl")
overlaps = pd.read_pickle(f"pdb_ensemble/predictions.pkl")
origapos = pd.read_pickle("../models/other_tools_apos/models_lenient_labelling.pkl")["model5"]

origholos = pd.read_pickle("../models/other_tools/models.pkl")["model5"]

#### 8jp0 - 8sgi

In [9]:
overlaps["8jp0"].pop("8sgi")

{'pocket': 'pocket2',
 'site_in_pocket': 0.53125,
 'pocket_in_site': 0.3695652173913043,
 'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
 0            GLU             A               1          132                 ?
 1            THR             A               1          133                 ?
 2            VAL             A               1          134                 ?
 3            SER             A               1          135                 ?
 4            LEU             A               1          137                 ?
 5            THR             A               1          138                 ?
 6            ALA             A               1          141                 ?
 7            HIS             A               1          200                 ?
 8            VAL             A               1          203                 ?
 9            VAL             A               1          206                 ?
 10           THR             A               1          207                 ?
 11           ALA             A               1          208                 ?
 12           TRP             A               1          210                 ?
 13           SER             A               1          211                 ?
 14           PHE             A               1          241                 ?
 15           ILE             A               1          244                 ?
 16           CYS             A               1          245                 ?
 17           PHE             A               1          248                 ?
 18           ALA             A               1          249                 ?
 19           LEU             A               1          256                 ?
 20           GLU             A               1          279                 ?
 21           THR             A               1          803                 ?
 22           ILE             A               1          804                 ?
 23           GLY             A               1          805                 ?
 24           LEU             A               1          806                 ?
 25           LYS             A               1          807                 ?
 26           ASP             A               1          808                 ?
 27           VAL             A               1          810                 ?
 28           THR             A               1          811                 ?
 29           ALA             A               1          812                 ?
 30           VAL             A               1          814                 ?
 31           PHE             A               1          815                 ?

    auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
 0           97          GLU            A                  1              132
 1           98          THR            A                  1              133
 2           99          VAL            A                  1              134
 3          100          SER            A                  1              135
 4          102          LEU            A                  1              137
 5          103          THR            A                  1              138
 6          106          ALA            A                  1              141
 7          165          HIS            A                  1              200
 8          168          VAL            A                  1              203
 9          171          VAL            A                  1              206
 10         172          THR            A                  1              207
 11         173          ALA            A                  1              208
 12         175          TRP            A                  1              210
 13         176          SER            A                  1              211
 14         206          PHE            A                  1              241
 15         209          ILE            A                  1              244
 16         210          CYS            A                  1              245
 17         213          PHE            A                  1              248
 18         214          ALA            A                  1              249
 19         221          LEU            A                  1              256
 20         244          GLU            A                  1              279
 21         793          THR            A                  1              803
 22         794          ILE            A                  1              804
 23         795          GLY            A                  1              805
 24         796          LEU            A                  1              806
 25         797          LYS            A                  1              807
 26         798          ASP            A                  1              808
 27         800          VAL            A                  1              810
 28         801          THR            A                  1              811
 29         802          ALA            A                  1              812
 30         804          VAL            A                  1              814
 31         805          PHE            A                  1              815

    pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
 0                      UNP                 P32418                    132
 1                      UNP                 P32418                    133
 2                      UNP                 P32418                    134
 3                      UNP                 P32418                    135
 4                      UNP                 P32418                    137
 5                      UNP                 P32418                    138
 6                      UNP                 P32418                    141
 7                      UNP                 P32418                    200
 8                      UNP                 P32418                    203
 9                      UNP                 P32418                    206
 10                     UNP                 P32418                    207
 11                     UNP                 P32418                    208
 12                     UNP                 P32418                    210
 13                     UNP                 P32418                    211
 14                     UNP                 P32418                    241
 15                     UNP                 P32418                    244
 16                     UNP                 P32418                    245
 17                     UNP                 P32418                    248
 18                     UNP                 P32418                    249
 19                     UNP                 P32418                    256
 20                     UNP                 P32418                    279
 21                     UNP                 P32418                    828
 22                     UNP                 P32418                    829
 23                     UNP                 P32418                    830
 24                     UNP                 P32418                    831
 25                     UNP                 P32418                    832
 26                     UNP                 P32418                    833
 27                     UNP                 P32418                    835
 28                     UNP                 P32418                    836
 29                     UNP                 P32418                    837
 30                     UNP                 P32418                    839
 31                     UNP                 P32418                    840

    pdbx_sifts_xref_db_res
 0                       E
 1                       T
 2                       V
 3                       S
 4                       L
 5                       T
 6                       A
 7                       H
 8                       V
 9                       V
 10                      T
 11                      A
 12                      W
 13                      S
 14                      F
 15                      I
 16                      C
 17                      F
 18                      A
 19                      L
 20                      E
 21                      T
 22                      I
 23                      G
 24                      L
 25                      K
 26                      D
 27                      V
 28                      T
 29                      A
 30                      V
 31                      F  ,
 'merge':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
 0            GLU             A               1          132                 ?
 1            THR             A               1          133                 ?
 2            VAL             A               1          134                 ?
 3            LEU             A               1          137                 ?
 4            THR             A               1          138                 ?
 5            ALA             A               1          141                 ?
 6            HIS             A               1          200                 ?
 7            VAL             A               1          203                 ?
 8            VAL             A               1          206                 ?
 9            THR             A               1          207                 ?
 10           TRP             A               1          210                 ?
 11           SER             A               1          211                 ?
 12           ILE             A               1          244                 ?
 13           CYS             A               1          245                 ?
 14           PHE             A               1          248                 ?
 15           ALA             A               1          249                 ?
 16           GLU             A               1          279                 ?

    auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
 0           97          GLU            A                  1              132
 1           98          THR            A                  1              133
 2           99          VAL            A                  1              134
 3          102          LEU            A                  1              137
 4          103          THR            A                  1              138
 5          106          ALA            A                  1              141
 6          165          HIS            A                  1              200
 7          168          VAL            A                  1              203
 8          171          VAL            A                  1              206
 9          172          THR            A                  1              207
 10         175          TRP            A                  1              210
 11         176          SER            A                  1              211
 12         209          ILE            A                  1              244
 13         210          CYS            A                  1              245
 14         213          PHE            A                  1              248
 15         214          ALA            A                  1              249
 16         244          GLU            A                  1              279

    pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
 0                      UNP                 P32418                    132
 1                      UNP                 P32418                    133
 2                      UNP                 P32418                    134
 3                      UNP                 P32418                    137
 4                      UNP                 P32418                    138
 5                      UNP                 P32418                    141
 6                      UNP                 P32418                    200
 7                      UNP                 P32418                    203
 8                      UNP                 P32418                    206
 9                      UNP                 P32418                    207
 10                     UNP                 P32418                    210
 11                     UNP                 P32418                    211
 12                     UNP                 P32418                    244
 13                     UNP                 P32418                    245
 14                     UNP                 P32418                    248
 15                     UNP                 P32418                    249
 16                     UNP                 P32418                    279

    pdbx_sifts_xref_db_res
 0                       E
 1                       T
 2                       V
 3                       L
 4                       T
 5                       A
 6                       H
 7                       V
 8                       V
 9                       T
 10                      W
 11                      S
 12                      I
 13                      C
 14                      F
 15                      A
 16                      E  }

In [10]:
seqsf = f"cofolding/seqs.pkl"

seqs = pd.read_pickle(seqsf)

In [11]:
seqsdf = pd.DataFrame({k: {k1: v1 for k1, v1 in v.items() if k1 != "site"} for k, v in seqs.items()}).T
seqsdf

,seq,seqmin,seqmax,site_seqids,ccd,smiles
7gqu,FLWPAPNEEQVTCLKMYFGHSSFKPVQWKVIHSVLEERRDNVAVMA...,12,430,"(44, 45, 46, 177, 178, 179, 180, 181, 185, 199...",X1L,CC(c1ncc(c(n1)Oc2ccccc2)C(=O)NC(CCS(=O)(=O)C)C...
7yg5,NIVRKYAKKLIDWPPFEYMILATIIANCIVLALEQHLPEDDKTPMS...,76,1871,"(134, 135, 138, 139, 142, 278, 279, 282, 283, ...",TOR,CC1(OC2COC3(C(C2O1)OC(O3)(C)C)COS(=O)(=O)N)C
8aq6,MVFTLEDFVGDWRQTAGYNLDQVLEQGGVSSLFQNLGVSVTPIQRI...,11,181,"(11, 12, 13, 43, 45, 57, 59, 61, 83, 84, 85, 9...",NT0,c1ccc(cc1)Cc2c(ncc(n2)c3ccccc3)NC(=O)Cc4ccco4
8f4s,SSQAWQPGVAMPNLYKMQRMLLEKCDLQNYGDSATLPKGIMMNVAK...,4,301,"(68, 70, 71, 96, 98, 111, 113, 114, 115, 116, ...",XDU,c1cc(c(cc1Cl)Cl)C=Cc2cc(nc(n2)O)C(F)(F)F
8jp0,GSYYCKKGVILPIWEPQDPSFGDKIARATVYFVAMVYMFLGVSIIA...,51,937,"(82, 83, 84, 85, 87, 88, 91, 150, 153, 156, 15...",EKY,CCOc1ccc(c(c1)N)Oc2ccc(cc2)OCc3cc(ccc3F)F
8qni,QAAADRRTVEKTWKLMDKVVRLCQNPKLQLKNSPPYILDILPDTYQ...,5,387,"(104, 107, 108, 109, 111, 112, 115, 181, 182, ...",W7R,CC1CN(CCO1)Cc2ccccc2C(=O)NC3C(=O)Nc4cnccc4C(=N...
8uk6,PERSMFSEGFLGDLHKPGEEPQMYPELLEEHKKFICDKVYTRFPPE...,233,812,"(49, 50, 51, 52, 55, 280, 281, 282, 283, 284, ...",WVK,c1cc(sc1)C=CC(=O)Nc2ncccn2
8v81,RSPLEKASVVSKLFFSWTRPILRKGYRQRLELSDIYQIPSVDSADN...,1,1438,"(90, 93, 308, 309, 342, 343, 345, 346, 351, 91...",WG5,c1cc(cc(c1)N2C(=O)C(=Cc3ccc(cc3)C(=O)O)SC2=S)C...
9dnm,TRVFKKASPNGKLTVYLGKRDFVDHIDLVDPVDGVVLVDPEYLKER...,6,492,"(129, 344, 345, 346, 347, 348, 379, 380, 381, ...",ODN,CC1C2CCC3C45COC(C3(C2O)C1=O)(C(C4C(CCC5O)(C)C)O)O

In [12]:
bioemuensdir = Path("bioemu_8uk6/msmclust/dihedrals")

In [13]:
bioemuensresults = pd.read_pickle(bioemuensdir / "predictions.pkl")
bioemuensresults

{'frame_0': {'pocket': 'pocket1',
  'overlap': 0.9047619047619048,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            GLY             A                 ?            A
  6            THR             A                 ?            A
  7            ILE             A                 ?            A
  8            MET             A                 ?            A
  9            LYS             A                 ?            A
  10           ILE             A                 ?            A
  11           TRP             A                 ?            A
  12           ARG             A                 ?            A
  13           LEU             A                 ?            A
  14           TYR             A                 ?            A
  15           THR             A                 ?            A
  16           GLN             A                 ?            A
  17           LEU             A                 ?            A
  18           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          GLY         279               1          280
  6                   1          THR         280               1          281
  7                   1          ILE         281               1          282
  8                   1          MET         282               1          283
  9                   1          LYS         284               1          285
  10                  1          ILE         287               1          288
  11                  1          TRP         299               1          300
  12                  1          ARG         303               1          304
  13                  1          LEU         304               1          305
  14                  1          TYR         305               1          306
  15                  1          THR         306               1          307
  16                  1          GLN         485               1          486
  17                  1          LEU         486               1          487
  18                  1          PHE         487               1          488  },
 'frame_1': {'pocket': 'pocket1',
  'overlap': 0.6190476190476191,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            THR             A                 ?            A
  6            ILE             A                 ?            A
  7            MET             A                 ?            A
  8            LYS             A                 ?            A
  9            ILE             A                 ?            A
  10           TRP             A                 ?            A
  11           TYR             A                 ?            A
  12           THR             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          THR         280               1          281
  6                   1          ILE         281               1          282
  7                   1          MET         282               1          283
  8                   1          LYS         284               1          285
  9                   1          ILE         287               1          288
  10                  1          TRP         299               1          300
  11                  1          TYR         305               1          306
  12                  1          THR         306               1          307  },
 'frame_2': {'pocket': 'pocket1',
  'overlap': 0.5238095238095238,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            THR             A                 ?            A
  6            ILE             A                 ?            A
  7            MET             A                 ?            A
  8            SER             A                 ?            A
  9            LYS             A                 ?            A
  10           PRO             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          THR         280               1          281
  6                   1          ILE         281               1          282
  7                   1          MET         282               1          283
  8                   1          SER         283               1          284
  9                   1          LYS         284               1          285
  10                  1          PRO         492               1          493  },
 'frame_3': {'pocket': 'pocket1',
  'overlap': 0.3333333333333333,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           GLY             A                 ?            A
  1           PHE             A                 ?            A
  2           LEU             A                 ?            A
  3           HIS             A                 ?            A
  4           HIS             A                 ?            A
  5           MET             A                 ?            A
  6           LYS             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          GLY          48               1           49
  1                  1          PHE          49               1           50
  2                  1          LEU          50               1           51
  3                  1          HIS          51               1           52
  4                  1          HIS          54               1           55
  5                  1          MET         282               1          283
  6                  1          LYS         284               1          285  },
 'frame_4': {'pocket': 'pocket6',
  'overlap': 0.2857142857142857,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           HIS             A                 ?            A
  1           HIS             A                 ?            A
  2           GLY             A                 ?            A
  3           THR             A                 ?            A
  4           MET             A                 ?            A
  5           PRO             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          HIS          51               1           52
  1                  1          HIS          54               1           55
  2                  1          GLY         279               1          280
  3                  1          THR         280               1          281
  4                  1          MET         282               1          283
  5                  1          PRO         492               1          493  },
 'frame_5': {'pocket': 'pocket2',
  'overlap': 0.5714285714285714,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            HIS             A                 ?            A
  1            GLY             A                 ?            A
  2            THR             A                 ?            A
  3            ILE             A                 ?            A
  4            ILE             A                 ?            A
  5            ARG             A                 ?            A
  6            LEU             A                 ?            A
  7            TYR             A                 ?            A
  8            THR             A                 ?            A
  9            GLN             A                 ?            A
  10           LEU             A                 ?            A
  11           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          HIS          51               1           52
  1                   1          GLY         279               1          280
  2                   1          THR         280               1          281
  3                   1          ILE         281               1          282
  4                   1          ILE         287               1          288
  5                   1          ARG         303               1          304
  6                   1          LEU         304               1          305
  7                   1          TYR         305               1          306
  8                   1          THR         306               1          307
  9                   1          GLN         485               1          486
  10                  1          LEU         486               1          487
  11                  1          PHE         487               1          488  },
 'frame_6': {'pocket': 'pocket3',
  'overlap': 0.2857142857142857,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           GLY             A                 ?            A
  1           LEU             A                 ?            A
  2           HIS             A                 ?            A
  3           HIS             A                 ?            A
  4           MET             A                 ?            A
  5           LYS             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          GLY          48               1           49
  1                  1          LEU          50               1           51
  2                  1          HIS          51               1           52
  3                  1          HIS          54               1           55
  4                  1          MET         282               1          283
  5                  1          LYS         284               1          285  },
 'frame_7': {'pocket': 'pocket1',
  'overlap': 0.9047619047619048,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            GLY             A                 ?            A
  6            THR             A                 ?            A
  7            ILE             A                 ?            A
  8            MET             A                 ?            A
  9            SER             A                 ?            A
  10           LYS             A                 ?            A
  11           ILE             A                 ?            A
  12           ARG             A                 ?            A
  13           LEU             A                 ?            A
  14           TYR             A                 ?            A
  15           THR             A                 ?            A
  16           GLN             A                 ?            A
  17           LEU             A                 ?            A
  18           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          GLY         279               1          280
  6                   1          THR         280               1          281
  7                   1          ILE         281               1          282
  8                   1          MET         282               1          283
  9                   1          SER         283               1          284
  10                  1          LYS         284               1          285
  11                  1          ILE         287               1          288
  12                  1          ARG         303               1          304
  13                  1          LEU         304               1          305
  14                  1          TYR         305               1          306
  15                  1          THR         306               1          307
  16                  1          GLN         485               1          486
  17                  1          LEU         486               1          487
  18                  1          PHE         487               1          488  },
 'frame_8': {'pocket': 'pocket1',
  'overlap': 1.0,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            GLY             A                 ?            A
  6            THR             A                 ?            A
  7            ILE             A                 ?            A
  8            MET             A                 ?            A
  9            SER             A                 ?            A
  10           LYS             A                 ?            A
  11           ILE             A                 ?            A
  12           TRP             A                 ?            A
  13           ARG             A                 ?            A
  14           LEU             A                 ?            A
  15           TYR             A                 ?            A
  16           THR             A                 ?            A
  17           GLN             A                 ?            A
  18           LEU             A                 ?            A
  19           PHE             A                 ?            A
  20           PRO             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          GLY         279               1          280
  6                   1          THR         280               1          281
  7                   1          ILE         281               1          282
  8                   1          MET         282               1          283
  9                   1          SER         283               1          284
  10                  1          LYS         284               1          285
  11                  1          ILE         287               1          288
  12                  1          TRP         299               1          300
  13                  1          ARG         303               1          304
  14                  1          LEU         304               1          305
  15                  1          TYR         305               1          306
  16                  1          THR         306               1          307
  17                  1          GLN         485               1          486
  18                  1          LEU         486               1          487
  19                  1          PHE         487               1          488
  20                  1          PRO         492               1          493  },
 'frame_9': {'pocket': 'pocket2',
  'overlap': 0.6190476190476191,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            HIS             A                 ?            A
  1            GLY             A                 ?            A
  2            THR             A                 ?            A
  3            ILE             A                 ?            A
  4            MET             A                 ?            A
  5            ILE             A                 ?            A
  6            ARG             A                 ?            A
  7            LEU             A                 ?            A
  8            TYR             A                 ?            A
  9            THR             A                 ?            A
  10           GLN             A                 ?            A
  11           LEU             A                 ?            A
  12           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          HIS          51               1           52
  1                   1          GLY         279               1          280
  2                   1          THR         280               1          281
  3                   1          ILE         281               1          282
  4                   1          MET         282               1          283
  5                   1          ILE         287               1          288
  6                   1          ARG         303               1          304
  7                   1          LEU         304               1          305
  8                   1          TYR         305               1          306
  9                   1          THR         306               1          307

# Consensus residues

In [14]:
guide_resf = outdir / "guide_res.pkl"

if guide_resf.exists():
    guide_res = pd.read_pickle(guide_resf)
else:
    guide_res = {}

## Calculation

top=1
topcounts=3

for holo in tqdm(overlaps):
    if holo == "8uk6":
        continue
    print(holo)
    refapo = next(apo for apo in apos[holo] if apo in os.listdir("../training_data/8.Apos/Extra_set/features"))
    refaporesults = pd.DataFrame( origapos["results"][refapo] ).T.sort_values("prob", ascending=False)
    refapocif = Cif(refapo, f"../training_data/8.Apos/Extra_set/cifs/{refapo}.cif")

    apooverlaps = []
    aposres = []
    for i in range(top):
        apooverlaps.append(refaporesults.iloc[i]["pocket_in_site"])
        aposres.append(
            refapocif.residues.merge(
                Pocket(f"../training_data/8.Apos/Extra_set/pockets/{refapo}/{refapo}_out/pockets/{refaporesults.iloc[i].name}_atm.cif").residues
            )[
                ["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]
            ]
        )
        
    for apo, apod in overlaps[holo].items():
        preds = pd.read_pickle(f"pdb_ensemble/predictions/{apo}/preds.pkl")
        apores = Cif(apo, f"pdb_ensemble/predictions/{apo}/{apo}.cif").residues
        apooverlaps.append(apod["site_in_pocket"])#apod["overlap"]) # only top1
        for i in range(top):
            aposres.append(
                apores.merge(
                    Pocket(f"pdb_ensemble/predictions/{apo}/{apo}/{apo}_out/pockets/{preds.iloc[i].name}_atm.cif").residues
                )[
                    ["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]
                ]
            )
    
    counts = refapocif.residues.merge(
        pd.concat(aposres).value_counts().to_frame().reset_index(),
        how="right"
    )

    topres = pd.DataFrame()
    for _, g in counts.groupby("count", sort=False):
        topres = pd.concat((
            topres, 
            g.sample(n=min(3-len(topres), len(g)), random_state=0)
        ))
        if len(topres) == 3:
            break

    all_topres = counts.loc[lambda x: x["count"].isin(counts.iloc[:topcounts]["count"])]
    # topres = counts.loc[lambda x: x["count"].isin(counts.iloc[:topcounts]["count"])].sample(n=3, random_state=0)

    print("\t", "".join(
        topres
        .sort_values("pdbx_sifts_xref_db_num", key=lambda x: x.astype(int))
        ["pdbx_sifts_xref_db_res"]
    ))

    holo_topres = (
        Cif(holo, f"../training_data/7.Extra_set/cifs/{holo}.cif")
        .residues.replace({"pdbx_sifts_xref_db_acc": {"P32418-2": "P32418"}})
        .merge(topres[["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]])
        .sort_values("label_seq_id", key=lambda x: x.astype(int))
    )
    ids = sorted(holo_topres.label_seq_id.astype(int) - seqs[holo]["seqmin"])

    all_ids = list(
        Cif(holo, f"../training_data/7.Extra_set/cifs/{holo}.cif")
        .residues.replace({"pdbx_sifts_xref_db_acc": {"P32418-2": "P32418"}})
        .merge(all_topres[["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]])
        .sort_values("label_seq_id", key=lambda x: x.astype(int))
        .label_seq_id.astype(int)
        - seqs[holo]["seqmin"] + 1 # to make them 1-indexed as label_seq_id
    )
    
    print("\t", "".join(
        pd.DataFrame(list(seqs[holo]["seq"]))
        .iloc[ids]
        [0]
    ))

    top_overlap = (
        extra_holos_sites[holo][0]["site"]
        .replace({"pdbx_sifts_xref_db_acc": {"P32418-2": "P32418"}})
        .merge(holo_topres)
    )

    guide_res[holo] = {
        "seqids": tuple(pd.Series(ids) + 1), # to make them 1-indexed as label_seq_id
        "all_seqids": all_ids,
        "mean_overlap": pd.Series(apooverlaps).mean(),
        "top_3_overlap": len(top_overlap),
        "top_3_overlaps": top_overlap,
        "overlaps": apooverlaps,
        "topres": topres[["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]]
    }

guide_res

#### 8uk6

bioemuensdir = "bioemu_8uk6/msmclust/dihedrals"

bioemuensresults = pd.read_pickle(f"{bioemuensdir}/predictions.pkl")
bioemuensresults

holo = "8uk6"
refapo = 'frame_0'
# refaporesults = pd.DataFrame( origapos["results"][refapo] ).T.sort_values("prob", ascending=False)
refapocif = Cif(refapo, f"{bioemuensdir}/predictions/{refapo}/{refapo}.cif")

apooverlaps = []
aposres = []
    
for apo, apod in bioemuensresults.items():
    preds = pd.read_pickle(f"{bioemuensdir}/predictions/{apo}/preds.pkl")
    apores = Cif(apo, f"{bioemuensdir}/predictions/{apo}/{apo}.cif").residues
    apooverlaps.append(apod["overlap"]) # only top1
    for i in range(top):
        aposres.append(
            apores.merge(
                Pocket(f"{bioemuensdir}/predictions/{apo}/{apo}/{apo}_out/pockets/{preds.iloc[i].name}_atm.cif").residues
            )["label_seq_id"]
        )

counts = refapocif.residues.merge(
    pd.concat(aposres).value_counts().to_frame().reset_index(),
    how="right"
)

topres = pd.DataFrame()
for _, g in counts.groupby("count", sort=False):
    topres = pd.concat((
        topres, 
        g.sample(n=min(3-len(topres), len(g)), random_state=0)
    ))
    if len(topres) == 3:
        break
all_topres = counts.loc[lambda x: x["count"].isin(counts.iloc[:topcounts]["count"])]
# topres = counts.loc[lambda x: x["count"].isin(counts.iloc[:topcounts]["count"])].sample(n=3, random_state=0)

print("\t", " ".join(
    topres
    .sort_values("label_seq_id", key=lambda x: x.astype(int))
    ["label_comp_id"]
))

ids = topres["label_seq_id"].astype(int).sort_values()
holo_seqids = ( ids + seqs[holo]["seqmin"] - 1 ).astype(str)

holo_topres = (
    Cif(holo, f"../training_data/7.Extra_set/cifs/{holo}.cif").residues
    .merge(holo_seqids)
    .sort_values("label_seq_id", key=lambda x: x.astype(int))
)
# ids = sorted(holo_topres.label_seq_id.astype(int) - seqs[holo]["seqmin"])

print("\t", "".join(
    pd.DataFrame(list(seqs[holo]["seq"]))
    .iloc[ids - 1]
    [0]
))

top_overlap = (
    extra_holos_sites[holo][0]["site"]
    .merge(holo_topres)
)

guide_res[holo] = {
    "seqids": tuple(ids),# tuple(pd.Series(ids) + 1), # to make them 1-indexed as label_seq_id
    "all_seqids": all_topres["label_seq_id"].astype(int).sort_values().to_list(),
    "mean_overlap": pd.Series(apooverlaps).mean(),
    "top_3_overlap": len(top_overlap),
    "top_3_overlaps": top_overlap,
    "overlaps": apooverlaps,
    "topres": topres[["label_seq_id"]]
}

pd.to_pickle(guide_res, guide_resf)

## Results

In [15]:
guide_res_df = pd.DataFrame(guide_res).T
guide_res_df

,seqids,all_seqids,mean_overlap,top_3_overlap,top_3_overlaps,overlaps,topres
7gqu,"(47, 204, 323)","[47, 204, 323]",0.264212,1,label_comp_id label_asym_id label_entity_id ...,"[0.14864864864864866, 0.06896551724137931, 0.4...",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_nu...
7yg5,"(710, 1710, 1742)","[399, 401, 403, 404, 405, 407, 408, 409, 451, ...",0.0,0,"Empty DataFrame Columns: [label_comp_id, label...","[0.0, 0.0, 0.0]",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_...
8aq6,"(60, 79, 94)","[40, 42, 60, 79, 94]",0.114211,0,"Empty DataFrame Columns: [label_comp_id, label...","[0.07142857142857142, 0.0, 0.3333333333333333,...",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_nu...
8f4s,"(130, 132, 149)","[70, 71, 98, 130, 132, 133, 149]",0.246201,1,label_comp_id label_asym_id label_entity_id ...,"[0.5263157894736842, 0.4230769230769231, 0.0, ...",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_nu...
8qni,"(183, 199, 203)","[183, 199, 203]",0.427736,1,label_comp_id label_asym_id label_entity_id ...,"[0.5517241379310345, 0.6086956521739131, 0.043...",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_nu...
8v81,"(261, 264, 265)","[261, 264, 265]",0.116819,0,"Empty DataFrame Columns: [label_comp_id, label...","[0.13978494623655913, 0.0, 0.0, 0.0, 0.0, 0.0,...",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_nu...
9dnm,"(121, 122, 386)","[121, 122, 164, 386, 394]",0.247056,0,"Empty DataFrame Columns: [label_comp_id, label...","[0.01694915254237288, 0.0, 0.4, 0.6, 0.0, 0.88...",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_nu...
8jp0,"(54, 82, 826)","[50, 54, 82, 83, 84, 87, 88, 90, 91, 148, 150,...",0.422506,1,label_comp_id label_asym_id label_entity_id ...,"[0.18888888888888888, 0.5625, 0.5161290322580645]",pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_n...
8uk6,"(52, 58, 283)","[52, 55, 58, 246, 273, 283]",0.480159,2,label_comp_id label_asym_id label_entity_id ...,"[0.9047619047619048, 0.6190476190476191, 0.523...",label_seq_id 0 52 1 283 4...

['7gqu', '7yg5', '8aq6', '8f4s', '8qni', '8v81', '9dnm', '8jp0']

holo = "8uk6"

cif = Cif(holo, f"../training_data/7.Extra_set/origcifs/{holo}_updated.cif.gz")

builder = mvs.create_builder()
structure = (
    builder
    .download(url="cif")
    .parse(format="mmcif")
    .model_structure()
)
assets = {'cif': cif.cif.text.encode()}

proteins = (
    structure
    .component(selector=[
        mvs.ComponentExpression(**{"label_asym_id": c})
        for c in extra_holos_sites[holo][0]["site"]["label_asym_id"].unique()
    ])
    .focus()
    .representation(type="cartoon")
    .color(color='#FFFFFF')
)

annos = f'annos_pocketres.json'
assets[annos] = json.dumps(
    [
        {'label_asym_id': r["label_asym_id"], 'label_seq_id': int(r["label_seq_id"]), 'color': 'black'}
        for i, r in (
            cif.residues
            .query(f'label_seq_id in {list(map(str, pd.Series(guide_res_df.loc[holo]["seqids"]) + seqs[holo]["seqmin"] - 1))}')
            .iterrows()
        )
    ]
).encode()
proteins.color_from_uri(uri=annos, format='json', schema='all_atomic')


mod = extra_holos_sites[holo][0]["mod"].label_asym_id.unique()

(
    structure
    .component(selector=[
        mvs.ComponentExpression(**{"label_asym_id": c})
        for c in mod
    ])
    .representation()
    .color(
        custom={
            "molstar_color_theme_name": "element-symbol",
            "molstar_color_theme_params": {
                "carbonColor": { "name": "uniform", "params": {"value": int("#ffffff".replace('#', ''), 16)} }
            }
        }
    )
)

(
    structure
    .component(selector=[
        mvs.ComponentExpression(**{"label_asym_id": c})
        for c in mod
    ])
    .representation(type="surface")#, custom={"ignoreLight": True})
    .color(color="black")
    .opacity(opacity=0.25)
)

mvs.MVSX(
    data=builder.get_state(),
    assets=assets
)

# Functions

## General

In [16]:
def run(cmd: List[str], cwd: Optional[str] = None, **kwargs) -> None:
    print(f"[CMD] {cmd if 'shell' in kwargs else ' '.join(cmd)}")
    try:
        p = sp.run(cmd, check=True, cwd=cwd, text=True, capture_output=True, **kwargs)
        print(p.stdout, p.stderr)
    except sp.CalledProcessError as e:
        print("[CMD FAILED]", e.returncode, e.cmd)
        print("[STDOUT]\n", e.stdout)
        print("[STDERR]\n", e.stderr)
        raise
    return


def which(tool: str) -> str:
    """Return full path to a Schrödinger CLI tool."""
    p = Path(SCHRO) / tool
    if p.exists():
        return str(p)
    # Some tools live at the root (e.g., $SCHRODINGER/prepwizard), others under subdirs.
    for sub in ["", "utilities", "shape_screen", "glide", "sitemap", "ligprep", "epik", "vsw"]:
        pp = Path(SCHRO) / sub / tool
        if pp.exists():
            return str(pp)
    return tool  # fallback on PATH


def ensure_outdir(d: Path):
    d.mkdir(parents=True, exist_ok=True)
    print(f"[INFO] Output directory: {d}")

In [17]:
run(
    " ".join((
        SCHRO + "/run xglide.py",
        "-doc"
    )), 
    shell=True
)

[CMD] /opt/schrodinger2025-2/run xglide.py -doc

########################################################################
#                                                                      #
#                  XGlide input file documentation                     #
#                                                                      #
#    The input file is based on keyword/value pairs, though certain    #
#    keywords can accept multiple values).  The notes below            #
#    the keywords, with explanations of their purpose and accepted     #
#    values.                                                           #
#                                                                      #
########################################################################

####################
# Input structures #
####################

COMPLEX <file/dir>[,<ligand_asl>,<constraint-strings>]
#    Can be a Maestro or PDB file, or a directory.  If a directory, all of the
#    Maestro and PDB files there will be read in as complexes.  Multiple-CT
#    files will be treated as a combined complex.  If a file has only a
#    single molecule, it is ignored.  By default, the first ligand detected
#    by the AslLigandSearcher is assumed to be the ligand, unless a ligand ASL
#    expression <ligand_asl> is provided.
#    NOTE: In earlier versions, the option field was the ligand molecule
#    number.  The equivalent ASL expression is "mol.num <ligand_molnum>".
#    For backwards compatibility, if the <ligand_asl> is an integer, it will
#    be intpreted as a molecule number; if the value is 0, the ligand will be
#    the last molecule in the structure.

RECEPTOR <file/dir>
#    Can be a Maestro or PDB file, or a directory.  If a directory, all of the
#    Maestro and PDB files there will be read in as receptors.  Multiple-CT
#    files will be treated as a combined receptor.  Multiple molecules
#    are assumed to be part of the receptor structure.

LIGAND <file/dir>[,REFPOSE][,<file>]
#    Can be a Maestro, PDB, or SDF file, or a directory.  If a directory, all
#    of the Maestro and PDB files there will be read in as receptors.
#    Multiple-CT files will be treated as multiple ligands.  If REFPOSE is
#    present (no spaces allowed), the ligands so specified are assumed to be in
#    the proper pose and frame of reference for grid generation (if AUTO) and
#    RMSD calculations.  If an additional filename is provided for a file
#    LIGAND specification, and it matches a file RECEPTOR or GRID
#    specification, the LIGAND will be linked to that receptor or grid for the
#    purpose of native redocking; this option no longer implies REFPOSE, so
#    use that keyword explicitly to use these ligands for setting the grid
#    center (if SELF) and for RMSD calculations.

GRID <file>[,<int>]
#    Can be a .grd or .zip grid file.  The optional <int> specifies the number
#    of constraints to enforce, if there are any defined in the GRID.  A value
#    of -1 means require all eligible constraints.  Currently, only H-bond and
#    metal constraints can be applied.  If no <int> value is given, any
#    constraints defined in the GRID will be ignored.

ALIGN <TRUE/FALSE>
#    Default is FALSE.  Run 'structalign' on all non-GRID RECEPTORs and
#    COMPLEXes.  The reference for the alignment will be the REFERENCE
#    structure, if defined.  Otherwise, it will be the first COMPLEX
#    listed.  Otherwise, it will be the first RECEPTOR listed.  If the
#    COMPLEX/RECEPTOR is a directory, the first structure found in the
#    specified directory will be used.  Warning: If ALIGN is TRUE when there
#    are LIGANDs associated with RECEPTORs, the RECEPTORs may be moved out of
#    the proper frame of reference for RMSD calculations; the LIGANDs are not
#    ALIGNed.

REFERENCE <file>
#    Reference receptor/complex for alignment.  Not included in the
#    cross-docking unless also listed as a COMPLEX or RECEPTOR.

MAXLIGATOMS <int>
#    Default is 90.  When extracting a ligand from a COMPLEX, the maximum
#    number of atoms for molecules that can be considered ligands.  This is
#    not the same as the DOCK_MAXATOMS setting for Glide.

MINLIGATOMS <int>
#    Default is 12.  When extracting a ligand from a COMPLEX, the minimum
#    number of atoms for molecules that can be considered ligands.

EXCLUDE_IONS <TRUE/FALSE>
#    Default is TRUE.  When extracting a ligand from a COMPLEX, exclude
#    small charged molecules and ions.

EXCLUDE_AMINO_ACIDS <TRUE/FALSE>
#    Default is FALSE.  When extracting a ligand from a COMPLEX, exclude
#    peptides.

EXCLUDED_RESIDUES <list>
#    Default is to use the built-in excluded_residues list of the
#    AslLigandSearcher, consisting of a variety of small molecules that
#    occur in crystal structures but aren't considered ligands (e.g.,
#    SO4, ACY, GOL, NAG).  A list of PDB residue codes can be specified
#    instead.

###############
# Preparation #
###############

PPREP <TRUE/FALSE>
#    Default is FALSE.  Run the command-line Protein Preparation Wizard on
#    all RECEPTORs and COMPLEXes.  The following PPREP_* options apply only
#    if PPREP is TRUE.

PPREP_FIXBONDS <TRUE/FALSE>
#    Default is TRUE.  Assign bond orders to het groups.

PPREP_HTREAT <TRUE/FALSE>
#    Default is TRUE.  Add hydrogens.

PPREP_REHTREAT <TRUE/FALSE>
#    Default is FALSE.  Delete and re-add hydrogens (will reset PDB atom
#    names).

PPREP_TREATMETALS <TRUE/FALSE>
#    Default is TRUE.  Treat metals (e.g., break covalent bonds).

PPREP_CAPTERMINI <TRUE/FALSE>
#    Default is FALSE.  Cap chain termini.

PPREP_KEEPWATERS <TRUE/FALSE>
#    Default is FALSE.  Don't delete waters far from het groups.

PPREP_WATERDIST <float>
#    Default is 5.0 A.  Distance threshhold for 'far' waters.

PPREP_EPIK <TRUE/FALSE>
#    Default is TRUE.  Generate het group states with Epik.  Requires an Epik
#    license.

PPREP_PROTASSIGN <TRUE/FALSE>
#    Default is TRUE.  Run 'protassign' to optimize H-bond networks.

PPREP_PROTASSIGN_EXHAUSTIVE <TRUE/FALSE>
#    Default is FALSE.  Use exhaustive mode.

PPREP_PROTASSIGN_WATER <TRUE/FALSE>
#    Default is TRUE.  Sample waters.

PPREP_IMPREF <TRUE/FALSE>
#    Default is TRUE.  Run 'impref' constrained refinement.

PPREP_IMPREF_RMSD <float>
#    Default is 0.30 A.  RMSD cutoff for 'impref'

PPREP_IMPREF_FIXHEAVY <TRUE/FALSE>
#    Default is FALSE.  Fix heavy atoms during refinement.

LIGPREP <TRUE/FALSE>
#    Default is FALSE.  Run LigPrep on all ligands.  This can generate
#    multiple varaints (ionization and tautomerization states, stereoisomers)
#    for each input ligand.  In the XGlide analysis calculations, a ligand is
#    counted as docking successfully or docking correctly if any of its
#    variants dock successfully or correctly.  Requires a LigPrep license.

LIGPREP_EPIK <TRUE/FALSE>
#    Default is FALSE.  Use Epik instead of the Ionizer to generate ionization
#    states.  Requires an Epik license.

###########
# SiteMap #
###########

SITEMAP <TRUE/FALSE>
#    Default is FALSE.  If GRIDGEN_GRID_CENTER is SELF and there is no
#    ligand associated with a RECEPTOR, use SiteMap to identify the top
#    binding site(s) for defining the grid center(s).  NOTE: Currently,
#    SiteMap jobs will run on 'localhost' even if a remote host/queue
#    is specified for the XGlide job.
SITEMAP_MAXSITES <int>
#    Default is 1.  The maximum number of sites per receptor for which grids
#    will be generated.
SITEMAP_FORCE <TRUE/FALSE>
#   Default is FALSE.  If TRUE, use SiteMap to identify the binding site(s)
#   even if there is a ligand associated with the receptor.

#########
# Glide #
#########

GRIDGEN_<keyword> <value>
# Passes Grid Generation keyword/value pairs to Glide.  See the documentation
# for the $SCHRODINGER/glide simplified input file.  The defaults that XGlide
# sets are:
#     RECEP_VSCALE    1.0
#     RECEP_CCUT      0.25
#     INNERBOX        10
# When multiple values are specified for a keyword, they should be a commma-
# separated list
# NOTE: Since the ligand (if any) will be removed, the keywords containing ASL
# (FLEXASL, GLIDE_RECEP_ASLSCALE, ASL_RES_INTERACTION, ASLSTRINGS) may no
# longer match the same atoms.

GRIDGEN_GRID_CENTER <AUTO/SELF/x,y,z>
#    GRID_CENTER is a standard Glide keyword, the normal value of which is
#    the X, Y, and Z coordinates of the grid box center.  Alternatively, the
#    value can be AUTO (the default) or SELF.  With AUTO, the grid center for
#    all receptors is set at the centroid of the all pre-positioned LIGANDs;
#    this option should be used only when all the receptors are pre-aligned, or
#    if ALIGN is TRUE.  With SELF, the grid center for each receptor is
#    determined only by the associated ligand (i.e., the native ligand).

GRIDGEN_OUTERBOX <AUTO/SELF/size/x,y,z>
#    OUTERBOX is a standard Glide keyword, the normal real value of which is
#    the outer grid box dimension (single value for cubic box) or dimensions
#    (x,y,z).  Alternatively, the value can be AUTO (the default) or SELF.
#    With AUTO, the grid size for all receptors is set according to the
#    largest of all the pre-positioned LIGANDs associated with receptors.
#    With SELF, the grid size for each receptor is set according to the sizes
#    of the pre-positioned and associated (i.e., native) ligand or ligands.

GRIDGEN_OUTERBOX_BUFFER <float>
#    If GRIDGEN_OUTERBOX is AUTO or SELF, the grid size will be the sum of
#    the inner box size (default 10), the computed max ligand size, and
#    GRIDGEN_OUTERBOX_BUFFER (default 0.0).  This keyword can be used to make
#    the grid boxes a bit larger in cases where the pre-positioned, associated
#    ligands might be smaller than other ligands that will be docked to the
#    receptors.

DOCK_<keyword> <value>
# Passes Ligand Docking keyword/value pairs to Glide.  See the documentation
# for the $SCHRODINGER/glide simplified input file.  The defaults that XGlide
# sets are:
#     POSES_PER_LIG   1
#     WRITE_XP_DESC   FALSE
#     COMPRESS_POSES  TRUE
#     POSE_OUTTYPE    ligandlib
# When multiple values are specified for a keyword, they should be a commma-
# separated list

DOCK_LIG_VSCALE <float/min,max,increment>
#    LIG_VSCALE is a standard Glide keyword, the normal value of which is
#    the ligand vdW scaling factor (default is 0.8).  Alternatively, the value
#    can be three values -- the minimum scaling factor, the maximum scaling
#    factor, and the increment (e.g., "0.5,1.0,0.1").  XGlide then will run
#    docking jobs with this range of scaling factors, and the optimal scaling
#    per receptor will be determined from the number of ligands that dock to
#    2.0 A or less.  Note that the "AUTO" option greatly increases the length
#    of the docking stage (there are 10x the number of subjobs).

DOCK_NUSECONS <int>
#    Apply this many H-bond/metal constraints in the docking jobs.  This value
#    is overridden by number-of-constraint specifications for individual
#    GRIDs.

#################
# Miscellaneous #
#################

NATIVEONLY <TRUE/FALSE>
#    Default is FALSE.  Only dock ligands into the corresponding receptors
#    of COMPLEXes (or RECEPTORs/GRIDs associated with LIGANDs).

SKIP_DOCKING <TRUE/FALSE>
#    Default is FALSE.  Skip the docking and RMSD calculation stages.  Useful
#    for using XGlide just to generate grids.

GOOD_RMSD <float>
#    Default is 2.0 A.  Cutoff for the a "good" ligand RMSD for the summary
#    results and ligand vdW scaling analysis.

GENERATE_TOP_COMPLEXES <int>
#    Default is 0.  If non-zero, produce an output file of complexes
#    representing each input receptor and the ligand pose with the best
#    GlideScore.  This option probably should be used only when docking
#    a single ligand (and perhaps its variants) to a set of receptor
#    structures.  The complexes will be sorted by GlideScore.

MERGE_SUBSET_POSES <TRUE/FALSE>
#    Default is TRUE.  After RMSD calculations are finished, merge the
#    docking results for each receptor/scaling into a single pose file.
#    The subset pose files are archived.  Doesn't apply to NATIVEONLY
#    docking.

## ProtPrep

In [18]:
cmd = [
    which("prepwizard"),
    "--help"
]
run(cmd)

[CMD] /opt/schrodinger2025-2/utilities/prepwizard --help
usage: $SCHRODINGER/utilities/prepwizard [options] inputfile outputfile
    Input file should be in Maestro or PDB format.
    Output file should be in Maestro or PDB format.


Required:
  in_file               Input structure file (Maestro or PDB)
  out_file              Output structure file (Maestro or PDB)

Preprocess:
  -nopreprocess         Skip pre-processing (useful if only ProtAssign or
                        Impref is desired)
  -reference_st_file REFERENCE_ST_FILE
                        File containing reference structure to align to.
  -reference_pdbid REFERENCE_PDBID
                        PDB ID of the structure to align to.
  -nobondorders         Don't assign bond orders to het groups
  -noccd                Don't use the Chemical Component Dictionary when
                        assigning bond orders.
  -assign_all_residues  Assign bond orders to all residues (by default
                        residues are only processed if they only have single
                        order bonds). If CCD is used, existing bond orders and
                        formal charges will be overriden for residues that are
                        present in the CCD.
  -nohtreat             Don't add hydrogens
  -rehtreat             Delete and re-add hydrogens (will reset PDB atom
                        names)
  -nometaltreat         Don't treat metals (adding zero-order bonds, etc)
  -disulfides           Create bonds to proximal Sulfurs (delete hydrogens as
                        needed)
  -glycosylation        Create bonds to N-linked and O-linked sugars (delete
                        hydrogens as needed)
  -palmitoylation       Create palmitoylation bonds even if not included in
                        the CONNECT records (delete hydrogens as needed)
  -antibody_cdr_scheme {Chothia,Kabat,IMGT,EnhancedChothia,AHo,None}
                        CDR annotation scheme.
  -renumber_ab_residues
                        Renumber antibodies residues to match the scheme
                        specified with the -antibody_cdr_scheme option.
  -tcr_cdr_scheme {IMGT,AHo,None}
                        CDR annotation scheme.
  -renumber_tcr_residues
                        Renumber TCR residues to match the scheme specified
                        with the -tcr_cdr_scheme option.
  -mse                  Convert Selenomethionine residues to Methionines
  -preprocess_watdist PREPROCESS_WATDIST
                        If specified, during preprocessing delete waters that
                        are further than this distance from het groups. By
                        default, waters are deleted during cleanup.
  -fillloops            Fill missing loops with Prime
  -fasta_file CUSTOM_FASTA_FILE
                        If filling missing residues, the custom fasta file to
                        use. If not specified, the fasta file will be
                        generated from the sequence that was stored in the
                        input structure when it was converted from the PDB
                        format.
  -fillsidechains       Fill missing side chains with Prime
  -addOXT               Add terminal oxygens to polypeptides
  -c, -captermini       Cap termini
  -cap_termini_min_atoms CAP_TERMINI_MIN_ATOMS
                        By default, only proteins with more than 200 atoms are
                        capped when -captermini is specified. Use this option
                        to allow capping of smaller molecules.
  -noepik               Don't run Epik on het groups. By default Epik is ran
                        on all het groups, and metal binding states are
                        considered for hets that are within 5A of metal atoms.
  -epik_pH EPIK_PH      Epik target pH (default 7.0)
  -epik_pHt EPIK_PHT    Epik pH range for generated structures (default 2.0)
  -max_states MAX_STATES, -ms MAX_STATES
                        Maximum number of het states to generate for each
                        protein complex.
  -noidealizehtf        Don't idealize added hydrogen temperature factors.

Optimize H-bond Assignments:
  -noprotassign         Don't run ProtAssign
  -s, -samplewater      Sample water states
  -include_epik_states  Include Epik embedded states in optimization
  -xtal                 Use crystal symmetry
  -nopropka             Do not use PROPKA for protonation states
  -propka_pH PROPKA_PH  Run PROPKA at given pH value (default 7.0)
  -label_pkas           Label residues with PROPKA pKas
  -pH {very_low,low,neutral,high}
                        Sample at given pH when not using PROPKA (default
                        neutral)
  -force FORCE_LIST FORCE_LIST
                        Force a particular residue to adapt the specified
                        state. Multiple -f specifications are permitted. See
                        $SCHRODINGER/utilities/protassign help for more info.
  -minimize_adj_h       Energy minimize all adjustable hydrogens (titratable
                        hydrogens, water hydrogens, hydroxyls, thiols, and
                        ASN/GLN carboxamide hydrogens).

Minimize and Delete Waters:
  -noimpref             Don't run a restrained minimization job
  -r RMSD, -rmsd RMSD   Minimization: RMSD cutoff in angstrom (default 0.3)
  -fix                  Minimization: Fix heavy atoms (minimize hydrogens
                        only)
  -f {2005,2.1,3,S-OPLS,OPLS_2005}
                        Minimization: Version of the OPLS force field to use.
                        Options: 2005 or 3 (default OPLS_2005)
  -keepfarwat           Don't delete waters far from het groups
  -watdist WATDIST      Distance threshold for 'far' waters (default 5.0A)
  -delwater_hbond_cutoff DELWATER_HBOND_CUTOFF
                        If specified, delete waters that do not make at least
                        this number H-bonds to non-waters. By default, this
                        feature is disabled (default 0).

Other:
  -preserve_st_titles   Preserve titles of structures. By default they are
                        annotated to show which structures were prepared
  -use_PDB_pH           If input structure has property r_pdb_PDB_EXPDTA_PH,
                        use that for Epik and ProtAssign/PROPKA.
  -h, --help            show this help message and exit
  -j J                  Deprecated. Use -JOBNAME instead.

Job Control Options:
  -HOST <hostname>      Run job remotely on the indicated host entry.
  -WAIT                 Do not return a prompt until the job completes.
  -SAVE                 Return zip archive of job directory at job completion.
  -NOJOBID              Run the job directly, without Job Control layer.
  -JOBNAME JOBNAME      Provide an explicit name for the job.

In [19]:
def prepare_protein(infile: Path, out, cwd: Path) -> Path:
    """Protein Preparation Wizard (prepwizard) → MAE"""
    prep_out =  f"{out}_prep.mae" #outdir /
    if (cwd / prep_out).exists():
        return
    prepwizard = which("prepwizard")
    
    cmd = [
        prepwizard,
        "-WAIT -HOST localhost:8",
        "-assign_all_residues", #  Assign bond orders to all residues (by default residues are only processed if they only have single order bonds). If CCD is used, existing bond orders and formal charges will be overriden for residues that are present in the CCD.
        "-rehtreat", # Delete and re-add hydrogens (will reset PDB atom names)
        "-disulfides", # Create bonds to proximal Sulfurs (delete hydrogens as needed)
        "-mse", # Convert Selenomethionine residues to Methionines
        "-max_states 1", # Maximum number of het states to generate for each protein complex.
        "-captermini", # Add terminal oxygens to polypeptides, Cap termini
        # "-minimize_adj_h", # Energy minimize all adjustable hydrogens (titratable hydrogens, water hydrogens, hydroxyls, thiols, and ASN/GLN carboxamide hydrogens).
        "-f S-OPLS",
        "-epik_pH 7.4 -epik_pHt 2.0 -samplewater -include_epik_states -propka_pH 7.4  -rmsd 0.3 -watdist 5.0",
        
        # "-noprotassign",   # speed-up; set as needed
        # "-noimpref",       # we’ll still do a restrained minimization
        
        str(infile.absolute()),
        str(prep_out),
    ]
    run(" ".join(cmd), cwd=cwd, shell=True)
    return #prep_out

# Blind

In [17]:
glidedir = Path("glide")
glidedir.mkdir(exist_ok=True)

In [19]:
dockings = {}

for holo, holod in overlaps.items():
    # if holo in ("7yg5", "8v81"):
    #     continue
        
    path = glidedir / holo
    path.mkdir(exist_ok = True)

    smif = path / f"{holo}.smi"
    smif.write_text(seqs[holo]["smiles"])
    
    dockings[holo] = {
        "files": [],
        "smiles": smif
    }

    if not (path / f"{holo}_prep.mae").exists():
        (path / holo).mkdir(exist_ok=True)
        dockings[holo]["files"].append(f"../training_data/7.Extra_set/cifs/{holo}.cif")
    
    refapo = next(apo for apo in apos[holo] if apo in os.listdir("../training_data/8.Apos/Extra_set/features"))
    if not (path / f"{refapo}_prep.mae").exists():
        (path / refapo).mkdir(exist_ok=True)
        dockings[holo]["files"].append(f"../training_data/8.Apos/Extra_set/cifs/{refapo}.cif")
    
    for apo in holod.keys():
        (path / apo).mkdir(exist_ok=True)
        if not (path / f"{refapo}_prep.mae").exists():
            dockings[holo]["files"].append(f"pdb_ensemble/predictions/{apo}/{apo}.cif")



holo = "8uk6"
path = glidedir / holo
path.mkdir(exist_ok = True)

smif = path / f"{holo}.smi"
smif.write_text(seqs[holo]["smiles"])

dockings[holo] = {
        "files": [],
        "smiles": smif
    }

if not (path / f"{holo}_prep.mae").exists():
    (path / holo).mkdir(exist_ok=True)
    dockings[holo]["files"].append(f"../training_data/7.Extra_set/cifs/{holo}.cif")

for apo in bioemuensresults:
    if not (path / f"{apo}_prep.mae").exists():
        (path / apo).mkdir(exist_ok=True)
        dockings[holo]["files"].append(str(bioemuensdir / f"predictions/{apo}/{apo}.cif"))

 

dockings

{'7gqu': {'files': ['../training_data/7.Extra_set/cifs/7gqu.cif',
   '../training_data/8.Apos/Extra_set/cifs/6yhr.cif',
   'pdb_ensemble/predictions/7gqt/7gqt.cif',
   'pdb_ensemble/predictions/8yle/8yle.cif',
   'pdb_ensemble/predictions/8pfp/8pfp.cif',
   'pdb_ensemble/predictions/7gqs/7gqs.cif'],
  'smiles': PosixPath('glide/7gqu/7gqu.smi')},
 '7yg5': {'files': ['../training_data/7.Extra_set/cifs/7yg5.cif',
   '../training_data/8.Apos/Extra_set/cifs/7xlq.cif',
   'pdb_ensemble/predictions/8epm/8epm.cif',
   'pdb_ensemble/predictions/8epl/8epl.cif'],
  'smiles': PosixPath('glide/7yg5/7yg5.smi')},
 '8aq6': {'files': ['../training_data/7.Extra_set/cifs/8aq6.cif',
   '../training_data/8.Apos/Extra_set/cifs/5b0u.cif',
   'pdb_ensemble/predictions/7snr/7snr.cif',
   'pdb_ensemble/predictions/7sny/7sny.cif',
   'pdb_ensemble/predictions/7snw/7snw.cif',
   'pdb_ensemble/predictions/7sns/7sns.cif',
   'pdb_ensemble/predictions/7vsx/7vsx.cif',
   'pdb_ensemble/predictions/8aqh/8aqh.cif',
   'pdb_ensemble/predictions/7snt/7snt.cif'],
  'smiles': PosixPath('glide/8aq6/8aq6.smi')},
 '8f4s': {'files': ['../training_data/7.Extra_set/cifs/8f4s.cif',
   '../training_data/8.Apos/Extra_set/cifs/7l6r.cif',
   'pdb_ensemble/predictions/6wq3/6wq3.cif',
   'pdb_ensemble/predictions/7jz0/7jz0.cif',
   'pdb_ensemble/predictions/7lw4/7lw4.cif',
   'pdb_ensemble/predictions/8tyj/8tyj.cif',
   'pdb_ensemble/predictions/9gtf/9gtf.cif',
   'pdb_ensemble/predictions/6wvn/6wvn.cif',
   'pdb_ensemble/predictions/9eun/9eun.cif',
   'pdb_ensemble/predictions/7bq7/7bq7.cif',
   'pdb_ensemble/predictions/8ot0/8ot0.cif',
   'pdb_ensemble/predictions/9gs4/9gs4.cif',
   'pdb_ensemble/predictions/8rze/8rze.cif',
   'pdb_ensemble/predictions/7lw3/7lw3.cif',
   'pdb_ensemble/predictions/7jhe/7jhe.cif',
   'pdb_ensemble/predictions/9emv/9emv.cif',
   'pdb_ensemble/predictions/8rva/8rva.cif',
   'pdb_ensemble/predictions/7r1t/7r1t.cif',
   'pdb_ensemble/predictions/7koa/7koa.cif',
   'pdb_ensemble/predictions/6wrz/6wrz.cif',
   'pdb_ensemble/predictions/7r1u/7r1u.cif',
   'pdb_ensemble/predictions/6yz1/6yz1.cif',
   'pdb_ensemble/predictions/7ult/7ult.cif',
   'pdb_ensemble/predictions/8rv8/8rv8.cif',
   'pdb_ensemble/predictions/6wjt/6wjt.cif',
   'pdb_ensemble/predictions/8s8x/8s8x.cif',
   'pdb_ensemble/predictions/6xkm/6xkm.cif',
   'pdb_ensemble/predictions/6w61/6w61.cif',
   'pdb_ensemble/predictions/8rv9/8rv9.cif',
   'pdb_ensemble/predictions/6wkq/6wkq.cif',
   'pdb_ensemble/predictions/9p6p/9p6p.cif',
   'pdb_ensemble/predictions/8otr/8otr.cif',
   'pdb_ensemble/predictions/8rzc/8rzc.cif',
   'pdb_ensemble/predictions/7c2j/7c2j.cif',
   'pdb_ensemble/predictions/8s8w/8s8w.cif',
   'pdb_ensemble/predictions/8rv4/8rv4.cif',
   'pdb_ensemble/predictions/8c5m/8c5m.cif',
   'pdb_ensemble/predictions/9guf/9guf.cif',
   'pdb_ensemble/predictions/7c2i/7c2i.cif',
   'pdb_ensemble/predictions/8osx/8osx.cif',
   'pdb_ensemble/predictions/8rv7/8rv7.cif',
   'pdb_ensemble/predictions/7jpe/7jpe.cif',
   'pdb_ensemble/predictions/7jyy/7jyy.cif',
   'pdb_ensemble/predictions/6w4h/6w4h.cif',
   'pdb_ensemble/predictions/9grq/9grq.cif',
   'pdb_ensemble/predictions/9emj/9emj.cif',
   'pdb_ensemble/predictions/8vuo/8vuo.cif',
   'pdb_ensemble/predictions/7l6t/7l6t.cif',
   'pdb_ensemble/predictions/7jib/7jib.cif',
   'pdb_ensemble/predictions/8a23/8a23.cif',
   'pdb_ensemble/predictions/6w75/6w75.cif',
   'pdb_ensemble/predictions/8rzd/8rzd.cif',
   'pdb_ensemble/predictions/9gwo/9gwo.cif',
   'pdb_ensemble/predictions/8rvb/8rvb.cif',
   'pdb_ensemble/predictions/8rv5/8rv5.cif',
   'pdb_ensemble/predictions/9gud/9gud.cif',
   'pdb_ensemble/predictions/8rv6/8rv6.cif',
   'pdb_ensemble/predictions/8ov2/8ov2.cif',
   'pdb_ensemble/predictions/8oto/8oto.cif',
   'pdb_ensemble/predictions/9grp/9grp.cif',
   'pdb_ensemble/predictions/9q8h/9q8h.cif',
   'pdb_ensemble/predictions/8bsd/8bsd.cif',
   'pdb_ensemble/predictions/8ov1/8ov1.cif',
   'pdb_ensemble/predictions/9guy/9guy.cif',
   'pdb_ensemble/predictions/8ov4/8ov4.cif',
   'pdb_ensemble/predictions/9gny/9gny.cif',
   'pdb_ensemble/predictions/9gue/9gue.cif',
   'pdb_ensemble/predictions/9eml/9eml.cif',
   'pdb_ensemble/predictions/8bzv/8bzv.cif',
   'pdb_ensemble/predictions/8ov3/8ov3.cif'],
  'smiles': PosixPath('glide/8f4s/8f4s.smi')},
 '8qni': {'files': ['../training_data/7.Extra_set/cifs/8qni.cif',
   '../training_data/8.Apos/Extra_set/cifs/8vw5.cif',
   'pdb_ensemble/predictions/3pfv/3pfv.cif',
   'pdb_ensemble/predictions/3vgo/3vgo.cif',
   'pdb_ensemble/predictions/8vw4/8vw4.cif',
   'pdb_ensemble/predictions/3zni/3zni.cif'],
  'smiles': PosixPath('glide/8qni/8qni.smi')},
 '8v81': {'files': ['../training_data/7.Extra_set/cifs/8v81.cif',
   '../training_data/8.Apos/Extra_set/cifs/5uak.cif',
   'pdb_ensemble/predictions/6o1v/6o1v.cif',
   'pdb_ensemble/predictions/9dw8/9dw8.cif',
   'pdb_ensemble/predictions/7svr/7svr.cif',
   'pdb_ensemble/predictions/8gls/8gls.cif',
   'pdb_ensemble/predictions/8eio/8eio.cif',
   'pdb_ensemble/predictions/8v7z/8v7z.cif',
   'pdb_ensemble/predictions/8eiq/8eiq.cif',
   'pdb_ensemble/predictions/9dw7/9dw7.cif',
   'pdb_ensemble/predictions/9dw5/9dw5.cif',
   'pdb_ensemble/predictions/6msm/6msm.cif',
   'pdb_ensemble/predictions/9dw4/9dw4.cif',
   'pdb_ensemble/predictions/8eig/8eig.cif',
   'pdb_ensemble/predictions/7sv7/7sv7.cif',
   'pdb_ensemble/predictions/7svd/7svd.cif',
   'pdb_ensemble/predictions/8ej1/8ej1.cif',
   'pdb_ensemble/predictions/9dw9/9dw9.cif',
   'pdb_ensemble/predictions/6o2p/6o2p.cif'],
  'smiles': PosixPath('glide/8v81/8v81.smi')},
 '9dnm': {'files': ['../training_data/7.Extra_set/cifs/9dnm.cif',
   '../training_data/8.Apos/Extra_set/cifs/4jqi.cif',
   'pdb_ensemble/predictions/9cx9/9cx9.cif',
   'pdb_ensemble/predictions/9dng/9dng.cif',
   'pdb_ensemble/predictions/6u1n/6u1n.cif',
   'pdb_ensemble/predictions/8hst/8hst.cif',
   'pdb_ensemble/predictions/8ja3/8ja3.cif',
   'pdb_ensemble/predictions/6kl7/6kl7.cif',
   'pdb_ensemble/predictions/8j8z/8j8z.cif',
   'pdb_ensemble/predictions/9bt8/9bt8.cif',
   'pdb_ensemble/predictions/9cx3/9cx3.cif',
   'pdb_ensemble/predictions/8hsv/8hsv.cif',
   'pdb_ensemble/predictions/8gp3/8gp3.cif',
   'pdb_ensemble/predictions/8i0q/8i0q.cif',
   'pdb_ensemble/predictions/8i0n/8i0n.cif',
   'pdb_ensemble/predictions/8go8/8go8.cif'],
  'smiles': PosixPath('glide/9dnm/9dnm.smi')},
 '8jp0': {'files': ['../training_data/7.Extra_set/cifs/8jp0.cif',
   '../training_data/8.Apos/Extra_set/cifs/8sgj.cif',
   'pdb_ensemble/predictions/9iv8/9iv8.cif',
   'pdb_ensemble/predictions/8sgt/8sgt.cif'],
  'smiles': PosixPath('glide/8jp0/8jp0.smi')},
 '8uk6': {'files': ['../training_data/7.Extra_set/cifs/8uk6.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_0/frame_0.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_1/frame_1.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_2/frame_2.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_3/frame_3.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_4/frame_4.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_5/frame_5.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_6/frame_6.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_7/frame_7.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_8/frame_8.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_9/frame_9.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_10/frame_10.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_11/frame_11.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_12/frame_12.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_13/frame_13.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_14/frame_14.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_15/frame_15.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_16/frame_16.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_17/frame_17.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_18/frame_18.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_19/frame_19.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_20/frame_20.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_21/frame_21.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_22/frame_22.cif',
   'bioemu_8uk6/msmclust/dihedrals/predictions/frame_23/frame_23.cif'],
  'smiles': PosixPath('glide/8uk6/8uk6.smi')}}

In [35]:
for holo, holod in dockings.items():
    path = glidedir / holo

    if (path / f"xglide/{holo}_topcomplexes.maegz").exists():
        continue

    preps = path / "preps"
    preps.mkdir(exist_ok=True)
    xout = path / "xglide"
    xout.mkdir(exist_ok=True)
    
    for file in holod["files"]:
        f = Path(file).resolve() # this resolves the symlink of 8uk6 frames and makes their name *_updated
        prepare_protein(f, out=f.stem, cwd=preps)

    xglide_inp = xout / f"{holo}.inp"    
    xglide_inp.write_text(f"""
RECEPTOR	{preps.absolute()}
ALIGN	FALSE
LIGAND	{holod['smiles'].absolute()}
GRIDGEN_GRID_CENTER	SELF
PPREP FALSE
SITEMAP	TRUE
SITEMAP_MAXSITES    5
GRIDGEN_INNERBOX	10
GRIDGEN_OUTERBOX	26.0
LIGPREP	TRUE
LIGPREP_EPIK	TRUE
DOCK_PRECISION	SP
DOCK_WRITE_XP_DESC	FALSE
DOCK_POSE_OUTTYPE	poseviewer
NATIVEONLY	FALSE
DOCK_LIG_VSCALE	0.80
SKIP_DOCKING	FALSE
GOOD_RMSD	2.0
GENERATE_TOP_COMPLEXES	5
    """)

    run(
        " ".join((
            SCHRO + "/run xglide.py",
            xglide_inp.name,
            "-WAIT -HOST localhost:32 -TMPLAUNCHDIR"
        )),
        cwd=xout, 
        shell=True
    )

    counts = {}
    with sstruct.StructureReader(xout / f"{holo}_topcomplexes.maegz") as r:
        for i, st in enumerate(r, 1):
            grid = st.property.get("s_i_glide_gridfile", "") # 'xglide__[6yhr|frame_3]_prep_site1__grid'
            try:
                apo, site = re.search(rf"{holo}__([^_]+(?:_\d+)?)_prep_(site\d+)", grid).groups()
            except AttributeError:
                if holo == "8uk6": # frame_* of 8uk6 have _updated added to their basename
                    apo, site = re.search(rf"{holo}__([^_]+(?:_\d+)?)_updated_prep_(site\d+)", grid).groups()
                else:
                    apo = grid.split("_")[2]
                    grid = "grid"
            except:
                raise
            rank = counts.get(apo, 0) + 1
            if rank == 6: continue
            fname = path / apo / f"{apo}_rank{rank}_pose{i}_{site}.pdb"
            with sstruct.StructureWriter(str(fname)) as w: w.append(st)
            counts[apo] = rank

# Guided

## Grid

In [25]:
def build_grid(
    grid_inp: Path,
    grid_zip: Path,
    receptor_mae: Path,
    center: Tuple[float, float, float],
):
    inner = 10
    outer = 26
    x, y, z = center
    contents = f"""FORCEFIELD   OPLS_2005
GRID_CENTER   {x:.8f}, {y:.8f}, {z:.8f}
GRIDFILE   {grid_zip.absolute()}
INNERBOX   {inner}, {inner}, {inner}
OUTERBOX   {outer}, {outer}, {outer}
RECEP_FILE   {receptor_mae.absolute()}
"""
    grid_inp.write_text(contents)
    glide = which("glide")
    run([glide, "-WAIT", str(grid_inp.absolute())], cwd=grid_zip.parent)
    return

## LigPrep

cmd = [
    which("ligprep"),
    "-help"
]
run(cmd)

def prepare_ligands(smiles: Path, ligprep_inp: Path, out_mae: Path, cwd: Path):# -> Path: #  pH: float = 7.4, dpH: float = 1.0
    """
    LigPrep with Epik states; outputs a single MAEGZ of prepared ligands.
    Accepts SDF/MAE/SMILES (SMILES must be in a .smi or via -ismi).
    """
    ligprep_inp.write_text(f"""
INPUT_FILE_NAME   {smiles.absolute()}
MAX_ATOMS   500
FORCE_FIELD   16
EPIK   yes
EPIKX   no
EPIK_METAL_BINDING   no
INCLUDE_ORIGINAL_STATE   no
DETERMINE_CHIRALITIES   no
IGNORE_CHIRALITIES   yes
NUM_STEREOISOMERS   32
OUT_MAE   {out_mae.absolute()}
    """)

    # Detect SMILES input by extension
    # is_smiles = ligand_in.suffix.lower() in [".smi", ".smiles", ".can"] # has to be .smi
    ligprep = which("ligprep")
    cmd = [ligprep, "-WAIT", "-inp", str(ligprep_inp.absolute())]
    # Epik-like states around target pH
    # cmd += ["-ph", f"{pH}", "-pht", f"{dpH}", "-s", "1"]  # 1 conformer per state (adjust as needed)
    run(cmd, cwd=cwd)
    return #out_mae

## Dock

glide = which("glide")
run([glide, "-h"])

def dock(
    glide_inp: Path,
    grid_zip: Path,
    prep_lig: Path,
    cwd: Path
):# -> Path:
    glide_inp.write_text(f"""
GRIDFILE   {grid_zip.absolute()}
LIGANDFILE   {prep_lig.absolute()}
NREPORT   5
POSES_PER_LIG   5
POSTDOCK   False
PRECISION   SP
    """)
    glide = which("glide")
    run([glide, "-WAIT", "-HOST", "localhost:6", str(glide_inp.absolute())], cwd=cwd)
    return

In [18]:
dockings = pd.read_pickle(glidedir / "glide-guided_dockings.pkl")
dockings

{'7gqu': {'7gqu': {'ciff': '../training_data/7.Extra_set/cifs/7gqu.cif',
   'pfile': '../training_data/7.Extra_set/pockets/7gqu/7gqu_out/7gqu_out.cif',
   'pocket': '1',
   'pocket_cog': [6.964241027832031, 26.42584991455078, 16.23856544494629],
   'guide_cog': [11.84740161895752, 24.034400939941406, 21.308034896850586]},
  '6yhr': {'ciff': '../training_data/8.Apos/Extra_set/cifs/6yhr.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/6yhr/6yhr_out/6yhr_out.cif',
   'pocket': '1',
   'pocket_cog': [-17.198780059814453,
    -19.426149368286133,
    32.649749755859375],
   'guide_cog': [-9.501700401306152, -14.058333396911621, 39.8582649230957]},
  '7gqt': {'ciff': 'pdb_ensemble/predictions/7gqt/7gqt.cif',
   'pfile': 'pdb_ensemble/predictions/7gqt/7gqt/7gqt_out/7gqt_out.cif',
   'pocket': '5',
   'pocket_cog': [11.266744613647461, -2.0004360675811768, -5.426126956939697],
   'guide_cog': [6.413934230804443, -3.6677331924438477, -8.020732879638672]},
  '8yle': {'ciff': 'pdb_ensemble/predictions/8yle/8yle.cif',
   'pfile': 'pdb_ensemble/predictions/8yle/8yle/8yle_out/8yle_out.cif',
   'pocket': '6',
   'pocket_cog': [6.363697052001953, -7.641810417175293, 0.4531156122684479],
   'guide_cog': [-6.90873384475708, -5.753566265106201, 7.870967388153076]},
  '8pfp': {'ciff': 'pdb_ensemble/predictions/8pfp/8pfp.cif',
   'pfile': 'pdb_ensemble/predictions/8pfp/8pfp/8pfp_out/8pfp_out.cif',
   'pocket': '1',
   'pocket_cog': [-17.97509002685547, 7.158182144165039, 9.536262512207031],
   'guide_cog': [-7.704867839813232, 2.473766565322876, 11.024534225463867]},
  '7gqs': {'ciff': 'pdb_ensemble/predictions/7gqs/7gqs.cif',
   'pfile': 'pdb_ensemble/predictions/7gqs/7gqs/7gqs_out/7gqs_out.cif',
   'pocket': '4',
   'pocket_cog': [11.357709884643555, -1.7662665843963623, -5.515999794006348],
   'guide_cog': [6.683000564575195, -3.7686004638671875, -7.885000705718994]}},
 '8aq6': {'8aq6': {'ciff': '../training_data/7.Extra_set/cifs/8aq6.cif',
   'pfile': '../training_data/7.Extra_set/pockets/8aq6/8aq6_out/8aq6_out.cif',
   'pocket': '2',
   'pocket_cog': [40.16830062866211, -51.84346008300781, 65.40921020507812],
   'guide_cog': [38.92204284667969, -59.504695892333984, 60.898197174072266]},
  '5b0u': {'ciff': '../training_data/8.Apos/Extra_set/cifs/5b0u.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/5b0u/5b0u_out/5b0u_out.cif',
   'pocket': '1',
   'pocket_cog': [28.245317459106445, 27.96975326538086, 43.79201126098633],
   'guide_cog': [35.227420806884766, 28.676387786865234, 43.2849235534668]},
  '7snr': {'ciff': 'pdb_ensemble/predictions/7snr/7snr.cif',
   'pfile': 'pdb_ensemble/predictions/7snr/7snr/7snr_out/7snr_out.cif',
   'pocket': '2',
   'pocket_cog': [133.0259552001953, 33.79324722290039, 29.09103012084961],
   'guide_cog': [137.623046875, 40.31365203857422, 35.556697845458984]},
  '7sny': {'ciff': 'pdb_ensemble/predictions/7sny/7sny.cif',
   'pfile': 'pdb_ensemble/predictions/7sny/7sny/7sny_out/7sny_out.cif',
   'pocket': '2',
   'pocket_cog': [6.688579559326172, -3.6231143474578857, 63.346229553222656],
   'guide_cog': [9.121615409851074, 6.974422931671143, 65.76019287109375]},
  '7snw': {'ciff': 'pdb_ensemble/predictions/7snw/7snw.cif',
   'pfile': 'pdb_ensemble/predictions/7snw/7snw/7snw_out/7snw_out.cif',
   'pocket': '1',
   'pocket_cog': [65.45156860351562, 109.23767852783203, 14.865564346313477],
   'guide_cog': [69.28231048583984, 113.86084747314453, 20.59257698059082]},
  '7sns': {'ciff': 'pdb_ensemble/predictions/7sns/7sns.cif',
   'pfile': 'pdb_ensemble/predictions/7sns/7sns/7sns_out/7sns_out.cif',
   'pocket': '3',
   'pocket_cog': [57.599449157714844, 28.328693389892578, 79.11487579345703],
   'guide_cog': [57.134681701660156, 24.25084686279297, 83.18798828125]},
  '7vsx': {'ciff': 'pdb_ensemble/predictions/7vsx/7vsx.cif',
   'pfile': 'pdb_ensemble/predictions/7vsx/7vsx/7vsx_out/7vsx_out.cif',
   'pocket': '1',
   'pocket_cog': [-10.302811622619629,
    -15.112927436828613,
    -15.666013717651367],
   'guide_cog': [-13.111617088317871,
    -16.868921279907227,
    -12.159461975097656]},
  '8aqh': {'ciff': 'pdb_ensemble/predictions/8aqh/8aqh.cif',
   'pfile': 'pdb_ensemble/predictions/8aqh/8aqh/8aqh_out/8aqh_out.cif',
   'pocket': '4',
   'pocket_cog': [-54.2391471862793, 17.073421478271484, 43.14850616455078],
   'guide_cog': [-48.35504150390625, 15.993961334228516, 35.631690979003906]},
  '7snt': {'ciff': 'pdb_ensemble/predictions/7snt/7snt.cif',
   'pfile': 'pdb_ensemble/predictions/7snt/7snt/7snt_out/7snt_out.cif',
   'pocket': '1',
   'pocket_cog': [-12.02538013458252, -12.078550338745117, 3.4684391021728516],
   'guide_cog': [-14.39673137664795, -9.652194023132324, 10.55765438079834]}},
 '8f4s': {'8f4s': {'ciff': '../training_data/7.Extra_set/cifs/8f4s.cif',
   'pfile': '../training_data/7.Extra_set/pockets/8f4s/8f4s_out/8f4s_out.cif',
   'pocket': '1',
   'pocket_cog': [95.75851440429688, 10.924911499023438, 24.291059494018555],
   'guide_cog': [90.02748107910156, 18.477998733520508, 31.52903175354004]},
  '7l6r': {'ciff': '../training_data/8.Apos/Extra_set/cifs/7l6r.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/7l6r/7l6r_out/7l6r_out.cif',
   'pocket': '9',
   'pocket_cog': [88.20286560058594, 11.680387496948242, 28.9742488861084],
   'guide_cog': [88.517578125, 17.66758155822754, 30.786998748779297]},
  '6wq3': {'ciff': 'pdb_ensemble/predictions/6wq3/6wq3.cif',
   'pfile': 'pdb_ensemble/predictions/6wq3/6wq3/6wq3_out/6wq3_out.cif',
   'pocket': '5',
   'pocket_cog': [87.14366149902344, 12.833354949951172, 30.51795196533203],
   'guide_cog': [88.29472351074219, 17.868545532226562, 30.963226318359375]},
  '7jz0': {'ciff': 'pdb_ensemble/predictions/7jz0/7jz0.cif',
   'pfile': 'pdb_ensemble/predictions/7jz0/7jz0/7jz0_out/7jz0_out.cif',
   'pocket': '1',
   'pocket_cog': [79.79010772705078, 26.901254653930664, 12.156694412231445],
   'guide_cog': [84.87199401855469, 16.384065628051758, 5.997677326202393]},
  '7lw4': {'ciff': 'pdb_ensemble/predictions/7lw4/7lw4.cif',
   'pfile': 'pdb_ensemble/predictions/7lw4/7lw4/7lw4_out/7lw4_out.cif',
   'pocket': '1',
   'pocket_cog': [-72.68659973144531, 69.00186920166016, -14.217886924743652],
   'guide_cog': [-65.00434112548828, 74.0802993774414, -4.225584983825684]},
  '8tyj': {'ciff': 'pdb_ensemble/predictions/8tyj/8tyj.cif',
   'pfile': 'pdb_ensemble/predictions/8tyj/8tyj/8tyj_out/8tyj_out.cif',
   'pocket': '2',
   'pocket_cog': [-83.14083862304688, 27.060863494873047, 12.9276762008667],
   'guide_cog': [-80.42852783203125, 17.822418212890625, 4.5462260246276855]},
  '9gtf': {'ciff': 'pdb_ensemble/predictions/9gtf/9gtf.cif',
   'pfile': 'pdb_ensemble/predictions/9gtf/9gtf/9gtf_out/9gtf_out.cif',
   'pocket': '1',
   'pocket_cog': [63.4195671081543, -13.847278594970703, -13.4227294921875],
   'guide_cog': [80.68462371826172, -17.78647232055664, 5.35790491104126]},
  '6wvn': {'ciff': 'pdb_ensemble/predictions/6wvn/6wvn.cif',
   'pfile': 'pdb_ensemble/predictions/6wvn/6wvn/6wvn_out/6wvn_out.cif',
   'pocket': '11',
   'pocket_cog': [87.53656005859375, 11.979421615600586, 29.33329200744629],
   'guide_cog': [88.13690185546875, 17.790485382080078, 30.94257926940918]},
  '9eun': {'ciff': 'pdb_ensemble/predictions/9eun/9eun.cif',
   'pfile': 'pdb_ensemble/predictions/9eun/9eun/9eun_out/9eun_out.cif',
   'pocket': '8',
   'pocket_cog': [80.2883529663086, -11.566944122314453, 29.528648376464844],
   'guide_cog': [79.95275115966797, -17.31999397277832, 31.068527221679688]},
  '7bq7': {'ciff': 'pdb_ensemble/predictions/7bq7/7bq7.cif',
   'pfile': 'pdb_ensemble/predictions/7bq7/7bq7/7bq7_out/7bq7_out.cif',
   'pocket': '1',
   'pocket_cog': [-83.67912292480469, 12.818089485168457, 28.44301986694336],
   'guide_cog': [-80.94503784179688, 18.113256454467773, 30.810930252075195]},
  '8ot0': {'ciff': 'pdb_ensemble/predictions/8ot0/8ot0.cif',
   'pfile': 'pdb_ensemble/predictions/8ot0/8ot0/8ot0_out/8ot0_out.cif',
   'pocket': '4',
   'pocket_cog': [80.32618713378906, -11.497466087341309, 3.024831533432007],
   'guide_cog': [79.9298095703125, -17.448741912841797, 4.86154842376709]},
  '9gs4': {'ciff': 'pdb_ensemble/predictions/9gs4/9gs4.cif',
   'pfile': 'pdb_ensemble/predictions/9gs4/9gs4/9gs4_out/9gs4_out.cif',
   'pocket': '10',
   'pocket_cog': [81.87879943847656, -27.4150447845459, 16.45928192138672],
   'guide_cog': [80.443359375, -17.689804077148438, 5.1989665031433105]},
  '8rze': {'ciff': 'pdb_ensemble/predictions/8rze/8rze.cif',
   'pfile': 'pdb_ensemble/predictions/8rze/8rze/8rze_out/8rze_out.cif',
   'pocket': '6',
   'pocket_cog': [51.51806640625, -64.86425018310547, -29.192529678344727],
   'guide_cog': [55.397193908691406, -60.74415969848633, -31.116195678710938]},
  '7lw3': {'ciff': 'pdb_ensemble/predictions/7lw3/7lw3.cif',
   'pfile': 'pdb_ensemble/predictions/7lw3/7lw3/7lw3_out/7lw3_out.cif',
   'pocket': '1',
   'pocket_cog': [89.42193603515625, -31.018707275390625, 28.218900680541992],
   'guide_cog': [87.50460815429688, -19.07390594482422, 33.90980911254883]},
  '7jhe': {'ciff': 'pdb_ensemble/predictions/7jhe/7jhe.cif',
   'pfile': 'pdb_ensemble/predictions/7jhe/7jhe/7jhe_out/7jhe_out.cif',
   'pocket': '2',
   'pocket_cog': [81.06795501708984, -13.209855079650879, 31.3674373626709],
   'guide_cog': [81.68911743164062, -18.13532257080078, 30.701932907104492]},
  '9emv': {'ciff': 'pdb_ensemble/predictions/9emv/9emv.cif',
   'pfile': 'pdb_ensemble/predictions/9emv/9emv/9emv_out/9emv_out.cif',
   'pocket': '1',
   'pocket_cog': [-83.32295227050781, 20.549131393432617, 9.010366439819336],
   'guide_cog': [-80.78097534179688, 17.773815155029297, 5.231509208679199]},
  '8rva': {'ciff': 'pdb_ensemble/predictions/8rva/8rva.cif',
   'pfile': 'pdb_ensemble/predictions/8rva/8rva/8rva_out/8rva_out.cif',
   'pocket': '2',
   'pocket_cog': [50.44717788696289, -64.08948516845703, -28.897836685180664],
   'guide_cog': [55.329471588134766, -60.69806671142578, -30.9145450592041]},
  '7r1t': {'ciff': 'pdb_ensemble/predictions/7r1t/7r1t.cif',
   'pfile': 'pdb_ensemble/predictions/7r1t/7r1t/7r1t_out/7r1t_out.cif',
   'pocket': '2',
   'pocket_cog': [114.77811431884766, 61.96919631958008, 17.148908615112305],
   'guide_cog': [112.96310424804688, 61.024192810058594, 20.53154945373535]},
  '7koa': {'ciff': 'pdb_ensemble/predictions/7koa/7koa.cif',
   'pfile': 'pdb_ensemble/predictions/7koa/7koa/7koa_out/7koa_out.cif',
   'pocket': '3',
   'pocket_cog': [81.18576049804688, -11.838713645935059, 29.171796798706055],
   'guide_cog': [81.63928985595703, -18.100933074951172, 30.687807083129883]},
  '6wrz': {'ciff': 'pdb_ensemble/predictions/6wrz/6wrz.cif',
   'pfile': 'pdb_ensemble/predictions/6wrz/6wrz/6wrz_out/6wrz_out.cif',
   'pocket': '3',
   'pocket_cog': [87.46039581298828, 12.53999137878418, 30.719417572021484],
   'guide_cog': [88.0216064453125, 17.735774993896484, 30.850582122802734]},
  '7r1u': {'ciff': 'pdb_ensemble/predictions/7r1u/7r1u.cif',
   'pfile': 'pdb_ensemble/predictions/7r1u/7r1u/7r1u_out/7r1u_out.cif',
   'pocket': '2',
   'pocket_cog': [29.203275680541992, 74.99868774414062, 12.862027168273926],
   'guide_cog': [24.839675903320312, 78.22573852539062, 12.41045093536377]},
  '6yz1': {'ciff': 'pdb_ensemble/predictions/6yz1/6yz1.cif',
   'pfile': 'pdb_ensemble/predictions/6yz1/6yz1/6yz1_out/6yz1_out.cif',
   'pocket': '7',
   'pocket_cog': [86.85052490234375, 11.792060852050781, 28.922252655029297],
   'guide_cog': [88.0063247680664, 17.714418411254883, 30.72474479675293]},
  '7ult': {'ciff': 'pdb_ensemble/predictions/7ult/7ult.cif',
   'pfile': 'pdb_ensemble/predictions/7ult/7ult/7ult_out/7ult_out.cif',
   'pocket': '4',
   'pocket_cog': [86.0709228515625, 10.585299491882324, 4.447271347045898],
   'guide_cog': [86.19480895996094, 16.469158172607422, 6.089290142059326]},
  '8rv8': {'ciff': 'pdb_ensemble/predictions/8rv8/8rv8.cif',
   'pfile': 'pdb_ensemble/predictions/8rv8/8rv8/8rv8_out/8rv8_out.cif',
   'pocket': '3',
   'pocket_cog': [51.59640884399414, -64.75687408447266, -27.98881721496582],
   'guide_cog': [55.46038818359375, -60.71657943725586, -31.111125946044922]},
  '6wjt': {'ciff': 'pdb_ensemble/predictions/6wjt/6wjt.cif',
   'pfile': 'pdb_ensemble/predictions/6wjt/6wjt/6wjt_out/6wjt_out.cif',
   'pocket': '2',
   'pocket_cog': [86.26611328125, 16.83509063720703, 13.60916519165039],
   'guide_cog': [85.84490203857422, 16.502580642700195, 5.833871364593506]},
  '8s8x': {'ciff': 'pdb_ensemble/predictions/8s8x/8s8x.cif',
   'pfile': 'pdb_ensemble/predictions/8s8x/8s8x/8s8x_out/8s8x_out.cif',
   'pocket': '3',
   'pocket_cog': [80.79888153076172, -11.760050773620605, 29.455408096313477],
   'guide_cog': [80.14029693603516, -17.424394607543945, 31.42073631286621]},
  '6xkm': {'ciff': 'pdb_ensemble/predictions/6xkm/6xkm.cif',
   'pfile': 'pdb_ensemble/predictions/6xkm/6xkm/6xkm_out/6xkm_out.cif',
   'pocket': '6',
   'pocket_cog': [-52.34562301635742, 66.17670440673828, -2.231057643890381],
   'guide_cog': [-56.411190032958984, 61.64054870605469, -4.557677745819092]},
  '6w61': {'ciff': 'pdb_ensemble/predictions/6w61/6w61.cif',
   'pfile': 'pdb_ensemble/predictions/6w61/6w61/6w61_out/6w61_out.cif',
   'pocket': '1',
   'pocket_cog': [-62.87925338745117, 53.706687927246094, -17.5388240814209],
   'guide_cog': [-55.53666687011719, 60.938934326171875, -4.9072585105896]},
  '8rv9': {'ciff': 'pdb_ensemble/predictions/8rv9/8rv9.cif',
   'pfile': 'pdb_ensemble/predictions/8rv9/8rv9/8rv9_out/8rv9_out.cif',
   'pocket': '1',
   'pocket_cog': [-62.549964904785156, 54.134151458740234, -42.39063262939453],
   'guide_cog': [-55.39282989501953, 60.82432174682617, -31.02448272705078]},
  '6wkq': {'ciff': 'pdb_ensemble/predictions/6wkq/6wkq.cif',
   'pfile': 'pdb_ensemble/predictions/6wkq/6wkq/6wkq_out/6wkq_out.cif',
   'pocket': '3',
   'pocket_cog': [82.32595825195312, 22.02030372619629, 11.355411529541016],
   'guide_cog': [85.70800018310547, 16.389968872070312, 5.843580722808838]},
  '9p6p': {'ciff': 'pdb_ensemble/predictions/9p6p/9p6p.cif',
   'pfile': 'pdb_ensemble/predictions/9p6p/9p6p/9p6p_out/9p6p_out.cif',
   'pocket': '6',
   'pocket_cog': [87.14909362792969, 10.562287330627441, 3.710559844970703],
   'guide_cog': [87.37992858886719, 16.51671028137207, 5.697129249572754]},
  '8otr': {'ciff': 'pdb_ensemble/predictions/8otr/8otr.cif',
   'pfile': 'pdb_ensemble/predictions/8otr/8otr/8otr_out/8otr_out.cif',
   'pocket': '3',
   'pocket_cog': [82.63831329345703, -11.74229907989502, 3.232374429702759],
   'guide_cog': [80.18416595458984, -17.50335693359375, 4.908870697021484]},
  '8rzc': {'ciff': 'pdb_ensemble/predictions/8rzc/8rzc.cif',
   'pfile': 'pdb_ensemble/predictions/8rzc/8rzc/8rzc_out/8rzc_out.cif',
   'pocket': '8',
   'pocket_cog': [81.86692810058594, -28.260940551757812, 43.67376708984375],
   'guide_cog': [80.39515686035156, -17.59406280517578, 31.22226333618164]},
  '7c2j': {'ciff': 'pdb_ensemble/predictions/7c2j/7c2j.cif',
   'pfile': 'pdb_ensemble/predictions/7c2j/7c2j/7c2j_out/7c2j_out.cif',
   'pocket': '1',
   'pocket_cog': [-82.88915252685547, 12.095958709716797, 27.66318702697754],
   'guide_cog': [-79.98873138427734, 17.456708908081055, 30.593225479125977]},
  '8s8w': {'ciff': 'pdb_ensemble/predictions/8s8w/8s8w.cif',
   'pfile': 'pdb_ensemble/predictions/8s8w/8s8w/8s8w_out/8s8w_out.cif',
   'pocket': '1',
   'pocket_cog': [81.95956420898438, -11.558030128479004, 29.154741287231445],
   'guide_cog': [79.80680847167969, -17.204036712646484, 31.071683883666992]},
  '8rv4': {'ciff': 'pdb_ensemble/predictions/8rv4/8rv4.cif',
   'pfile': 'pdb_ensemble/predictions/8rv4/8rv4/8rv4_out/8rv4_out.cif',
   'pocket': '11',
   'pocket_cog': [85.30885314941406, -29.989208221435547, 41.210777282714844],
   'guide_cog': [80.34935760498047, -17.690643310546875, 31.21245002746582]},
  '8c5m': {'ciff': 'pdb_ensemble/predictions/8c5m/8c5m.cif',
   'pfile': 'pdb_ensemble/predictions/8c5m/8c5m/8c5m_out/8c5m_out.cif',
   'pocket': '6',
   'pocket_cog': [80.17535400390625, -11.588397026062012, 2.959218978881836],
   'guide_cog': [79.8766860961914, -17.472742080688477, 4.895322799682617]},
  '9guf': {'ciff': 'pdb_ensemble/predictions/9guf/9guf.cif',
   'pfile': 'pdb_ensemble/predictions/9guf/9guf/9guf_out/9guf_out.cif',
   'pocket': '3',
   'pocket_cog': [81.6391372680664, -26.9648494720459, 16.14048194885254],
   'guide_cog': [80.15824127197266, -17.49601936340332, 5.250434398651123]},
  '7c2i': {'ciff': 'pdb_ensemble/predictions/7c2i/7c2i.cif',
   'pfile': 'pdb_ensemble/predictions/7c2i/7c2i/7c2i_out/7c2i_out.cif',
   'pocket': '11',
   'pocket_cog': [65.9066162109375, -58.62894058227539, -14.1229829788208],
   'guide_cog': [55.327579498291016, -60.78042221069336, -4.768968105316162]},
  '8osx': {'ciff': 'pdb_ensemble/predictions/8osx/8osx.cif',
   'pfile': 'pdb_ensemble/predictions/8osx/8osx/8osx_out/8osx_out.cif',
   'pocket': '9',
   'pocket_cog': [81.3266372680664, -11.804312705993652, 2.7351043224334717],
   'guide_cog': [80.2200927734375, -17.645545959472656, 5.03867769241333]},
  '8rv7': {'ciff': 'pdb_ensemble/predictions/8rv7/8rv7.cif',
   'pfile': 'pdb_ensemble/predictions/8rv7/8rv7/8rv7_out/8rv7_out.cif',
   'pocket': '10',
   'pocket_cog': [84.31755828857422, -27.593265533447266, 39.33242416381836],
   'guide_cog': [80.27935028076172, -17.485700607299805, 31.078758239746094]},
  '7jpe': {'ciff': 'pdb_ensemble/predictions/7jpe/7jpe.cif',
   'pfile': 'pdb_ensemble/predictions/7jpe/7jpe/7jpe_out/7jpe_out.cif',
   'pocket': '5',
   'pocket_cog': [51.822715759277344, -64.02667999267578, -4.118810653686523],
   'guide_cog': [56.61431884765625, -61.702354431152344, -4.279064655303955]},
  '7jyy': {'ciff': 'pdb_ensemble/predictions/7jyy/7jyy.cif',
   'pfile': 'pdb_ensemble/predictions/7jyy/7jyy/7jyy_out/7jyy_out.cif',
   'pocket': '9',
   'pocket_cog': [85.66382598876953, 10.042218208312988, 4.256856441497803],
   'guide_cog': [85.65982818603516, 16.1839656829834, 5.960355281829834]},
  '6w4h': {'ciff': 'pdb_ensemble/predictions/6w4h/6w4h.cif',
   'pfile': 'pdb_ensemble/predictions/6w4h/6w4h/6w4h_out/6w4h_out.cif',
   'pocket': '3',
   'pocket_cog': [87.66934204101562, 28.474828720092773, 42.96949005126953],
   'guide_cog': [87.49745178222656, 17.649066925048828, 30.628870010375977]},
  '9grq': {'ciff': 'pdb_ensemble/predictions/9grq/9grq.cif',
   'pfile': 'pdb_ensemble/predictions/9grq/9grq/9grq_out/9grq_out.cif',
   'pocket': '5',
   'pocket_cog': [79.84784698486328, -11.276945114135742, 3.5515317916870117],
   'guide_cog': [79.59967803955078, -17.262836456298828, 5.079322814941406]},
  '9emj': {'ciff': 'pdb_ensemble/predictions/9emj/9emj.cif',
   'pfile': 'pdb_ensemble/predictions/9emj/9emj/9emj_out/9emj_out.cif',
   'pocket': '4',
   'pocket_cog': [-80.6800537109375, 12.986982345581055, 30.814800262451172],
   'guide_cog': [-80.30436706542969, 17.607093811035156, 31.323225021362305]},
  '8vuo': {'ciff': 'pdb_ensemble/predictions/8vuo/8vuo.cif',
   'pfile': 'pdb_ensemble/predictions/8vuo/8vuo/8vuo_out/8vuo_out.cif',
   'pocket': '3',
   'pocket_cog': [-14.589003562927246, 9.936572074890137, 34.285648345947266],
   'guide_cog': [-10.446064949035645, 8.567322731018066, 22.802804946899414]},
  '7l6t': {'ciff': 'pdb_ensemble/predictions/7l6t/7l6t.cif',
   'pfile': 'pdb_ensemble/predictions/7l6t/7l6t/7l6t_out/7l6t_out.cif',
   'pocket': '10',
   'pocket_cog': [88.41502380371094, 11.79647159576416, 28.718231201171875],
   'guide_cog': [88.74848175048828, 17.81854820251465, 30.701419830322266]},
  '7jib': {'ciff': 'pdb_ensemble/predictions/7jib/7jib.cif',
   'pfile': 'pdb_ensemble/predictions/7jib/7jib/7jib_out/7jib_out.cif',
   'pocket': '1',
   'pocket_cog': [-80.84369659423828, 14.198736190795898, 7.406043529510498],
   'guide_cog': [-81.81280517578125, 18.10780906677246, 4.341677188873291]},
  '8a23': {'ciff': 'pdb_ensemble/predictions/8a23/8a23.cif',
   'pfile': 'pdb_ensemble/predictions/8a23/8a23/8a23_out/8a23_out.cif',
   'pocket': '10',
   'pocket_cog': [38.73638153076172, -0.19208994507789612, -37.18867874145508],

In [26]:
for holo, holod in dockings.items():
    for guide in ("pocket", "guide"):
        path = glidedir / f"{holo}_{guide}"
        path.mkdir(exist_ok=True)
    
        if (path / f"xglide/{holo}_topcomplexes.maegz").exists():
            continue
        
        grids = path / "grids"
        grids.mkdir(exist_ok=True)
        xout = path / "xglide"
        xout.mkdir(exist_ok=True)

        gridsl = ""
        for apo, apod in holod.items():
            apopath = path / apo
            apopath.mkdir(exist_ok=True)

            grid_zip = grids / f"{apo}_grid.zip"
            if not grid_zip.exists():
                build_grid(
                    grid_inp = grids / f"{apo}_grid.inp",
                    grid_zip = grid_zip,
                    receptor_mae = glidedir / holo / "preps" / (f"{apo}_prep.mae" if (holo != "8uk6" or holo == apo) else f"{apo}_updated_prep.mae"),
                    center = apod[f"{guide}_cog"],
                )
            gridsl += f"GRID	{grid_zip.absolute()}\n"

        xglide_inp = xout / f"{holo}.inp"    
        xglide_inp.write_text(f"""
{gridsl}
ALIGN	FALSE
LIGAND	{(glidedir / holo / f"{holo}.smi").absolute()}
GRIDGEN_GRID_CENTER	AUTO
GRIDGEN_INNERBOX	10
GRIDGEN_OUTERBOX	26.0
PPREP FALSE
LIGPREP	TRUE
LIGPREP_EPIK	TRUE
DOCK_PRECISION	SP
DOCK_WRITE_XP_DESC	FALSE
DOCK_POSE_OUTTYPE	poseviewer
DOCK_POSES_PER_LIG   5
NATIVEONLY	FALSE
DOCK_LIG_VSCALE	0.80
SKIP_DOCKING	FALSE
GOOD_RMSD	2.0
GENERATE_TOP_COMPLEXES	5
        """)
    
        run(
            " ".join((
                SCHRO + "/run xglide.py",
                xglide_inp.name,
                "-WAIT -HOST localhost:16 -TMPLAUNCHDIR"
            )),
            cwd=xout, 
            shell=True
        )

        counts = {}
        with sstruct.StructureReader(xout / f"{holo}_topcomplexes.maegz") as r:
            for i, st in enumerate(r, 1):
                apo = (
                    st.property.get("s_i_glide_gridfile", "grid")
                    .rsplit("_", 1)[0]
                    .replace("_updated", "").replace("updated", "")
                )# '8pfp_grid' or frame_0_grid
                rank = counts.get(apo, 0) + 1
                if rank == 6: continue
                fname = path / apo / f"{apo}_rank{rank}.pdb"
                with sstruct.StructureWriter(str(fname)) as w: w.append(st)
                counts[apo] = rank

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_0_grid.inp
JobId: avogadro-0-68dcef28
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_1_grid.inp
JobId: avogadro-0-68dcef48
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_2_grid.inp
JobId: avogadro-0-68dcef67
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_3_grid.inp
JobId: avogadro-0-68dcef86
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_4_grid.inp
JobId: avogadro-0-68dcefa5
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_5_grid.inp
JobId: avogadro-0-68dcefc5
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_6_grid.inp
JobId: avogadro-0-68dcefe4
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_7_grid.inp
JobId: avogadro-0-68dcf003
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_8_grid.inp
JobId: avogadro-0-68dcf022
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_9_grid.inp
JobId: avogadro-0-68dcf041
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_10_grid.inp
JobId: avogadro-0-68dcf061
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_11_grid.inp
JobId: avogadro-0-68dcf080
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_12_grid.inp
JobId: avogadro-0-68dcf09f
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_13_grid.inp
JobId: avogadro-0-68dcf0be
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_14_grid.inp
JobId: avogadro-0-68dcf0de
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_15_grid.inp
JobId: avogadro-0-68dcf0fd
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_16_grid.inp
JobId: avogadro-0-68dcf11c
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_17_grid.inp
JobId: avogadro-0-68dcf13b
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_18_grid.inp
JobId: avogadro-0-68dcf15b
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_19_grid.inp
JobId: avogadro-0-68dcf17a
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_20_grid.inp
JobId: avogadro-0-68dcf199
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_21_grid.inp
JobId: avogadro-0-68dcf1b8
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_22_grid.inp
JobId: avogadro-0-68dcf1d7
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_23_grid.inp
JobId: avogadro-0-68dcf1f7
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/run xglide.py 8uk6.inp -WAIT -HOST localhost:16 -TMPLAUNCHDIR
JobId: avogadro-0-68dcf216

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/8uk6_grid.inp
JobId: avogadro-0-68dcf259
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_0_grid.inp
JobId: avogadro-0-68dcf278
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_1_grid.inp
JobId: avogadro-0-68dcf297
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_2_grid.inp
JobId: avogadro-0-68dcf2b6
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_3_grid.inp
JobId: avogadro-0-68dcf2d6
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_4_grid.inp
JobId: avogadro-0-68dcf2f5
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_5_grid.inp
JobId: avogadro-0-68dcf314
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_6_grid.inp
JobId: avogadro-0-68dcf333
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_7_grid.inp
JobId: avogadro-0-68dcf353
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_8_grid.inp
JobId: avogadro-0-68dcf372
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_9_grid.inp
JobId: avogadro-0-68dcf391
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_10_grid.inp
JobId: avogadro-0-68dcf3b0
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_11_grid.inp
JobId: avogadro-0-68dcf3d0
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_12_grid.inp
JobId: avogadro-0-68dcf3ef
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_13_grid.inp
JobId: avogadro-0-68dcf40e
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_14_grid.inp
JobId: avogadro-0-68dcf42d
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_15_grid.inp
JobId: avogadro-0-68dcf44c
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_16_grid.inp
JobId: avogadro-0-68dcf46c
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_17_grid.inp
JobId: avogadro-0-68dcf48b
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_18_grid.inp
JobId: avogadro-0-68dcf4aa
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_19_grid.inp
JobId: avogadro-0-68dcf4c9
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_20_grid.inp
JobId: avogadro-0-68dcf4e9
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_21_grid.inp
JobId: avogadro-0-68dcf508
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_22_grid.inp
JobId: avogadro-0-68dcf527
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_23_grid.inp
JobId: avogadro-0-68dcf546
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/run xglide.py 8uk6.inp -WAIT -HOST localhost:16 -TMPLAUNCHDIR
JobId: avogadro-0-68dcf566

for holo, holod in dockings.items():
    prep_lig = glidedir / holo / f"{holo}_ligprep.mae"
    if not prep_lig.exists():
        prepare_ligands(
            smiles = glidedir / holo / f"{holo}.smi",
            ligprep_inp = glidedir / holo / f"{holo}_ligprep.inp",
            out_mae = prep_lig,
            cwd = glidedir / holo
        )
    
    for guide in ("pocket", "guide"):
        path = glidedir / f"{holo}_{guide}"
        path.mkdir(exist_ok=True)
    
        if (path / f"xglide/{holo}_topcomplexes.maegz").exists():
            continue
        
        # grids = path / "grids"
        # grids.mkdir(exist_ok=True)
        # xout = path / "xglide"
        # xout.mkdir(exist_ok=True)

        for apo, apod in holod.items():
            apopath = path / apo
            apopath.mkdir(exist_ok=True)
                
            grid_zip = apopath / f"{apo}_grid.zip"
            if not grid_zip.exists():
                build_grid(
                    grid_inp = apopath / f"{apo}_grid.inp",
                    grid_zip = grid_zip,
                    receptor_mae = glidedir / holo / "preps" / f"{apo}_prep.mae",
                    center = apod[f"{guide}_cog"],
                )

            dock_out = apopath / f"{apo}_glide_pv.maegz"
            if not dock_out.exists():
                dock(
                    glide_inp = apopath / f"{apo}_glide.in",
                    grid_zip = grid_zip,
                    prep_lig = prep_lig,
                    cwd = apopath,
                )

            if not (apopath / "rank_1.pdb").exists():
                with sstruct.StructureReader(dock_out) as r:
                    r = list(r)
                    prot = r[0]
                    assert "r_i_docking_score" not in prot.property
                    for i, st in enumerate(r[1:], 1):
                        assert "r_i_docking_score" in st.property
                        # complex_st = prot.copy()
                        # complex_st.extend(st)
                        # with sstruct.StructureWriter(apopath / f"rank_{i}.pdb") as w: w.append(complex_st)
                        with sstruct.StructureWriter(apopath / f"rank_{i}.pdb") as w: w.append(st)

# Guided - bigger grid

In [ ]:
glidedir = Path("glide_bigger")

## Grid

In [25]:
def build_grid(
    grid_inp: Path,
    grid_zip: Path,
    receptor_mae: Path,
    center: Tuple[float, float, float],
):
    inner = 20
    outer = 30
    x, y, z = center
    contents = f"""FORCEFIELD   OPLS_2005
GRID_CENTER   {x:.8f}, {y:.8f}, {z:.8f}
GRIDFILE   {grid_zip.absolute()}
INNERBOX   {inner}, {inner}, {inner}
OUTERBOX   {outer}, {outer}, {outer}
RECEP_FILE   {receptor_mae.absolute()}
"""
    grid_inp.write_text(contents)
    glide = which("glide")
    run([glide, "-WAIT", str(grid_inp.absolute())], cwd=grid_zip.parent)
    return

## LigPrep

cmd = [
    which("ligprep"),
    "-help"
]
run(cmd)

def prepare_ligands(smiles: Path, ligprep_inp: Path, out_mae: Path, cwd: Path):# -> Path: #  pH: float = 7.4, dpH: float = 1.0
    """
    LigPrep with Epik states; outputs a single MAEGZ of prepared ligands.
    Accepts SDF/MAE/SMILES (SMILES must be in a .smi or via -ismi).
    """
    ligprep_inp.write_text(f"""
INPUT_FILE_NAME   {smiles.absolute()}
MAX_ATOMS   500
FORCE_FIELD   16
EPIK   yes
EPIKX   no
EPIK_METAL_BINDING   no
INCLUDE_ORIGINAL_STATE   no
DETERMINE_CHIRALITIES   no
IGNORE_CHIRALITIES   yes
NUM_STEREOISOMERS   32
OUT_MAE   {out_mae.absolute()}
    """)

    # Detect SMILES input by extension
    # is_smiles = ligand_in.suffix.lower() in [".smi", ".smiles", ".can"] # has to be .smi
    ligprep = which("ligprep")
    cmd = [ligprep, "-WAIT", "-inp", str(ligprep_inp.absolute())]
    # Epik-like states around target pH
    # cmd += ["-ph", f"{pH}", "-pht", f"{dpH}", "-s", "1"]  # 1 conformer per state (adjust as needed)
    run(cmd, cwd=cwd)
    return #out_mae

## Dock

glide = which("glide")
run([glide, "-h"])

def dock(
    glide_inp: Path,
    grid_zip: Path,
    prep_lig: Path,
    cwd: Path
):# -> Path:
    glide_inp.write_text(f"""
GRIDFILE   {grid_zip.absolute()}
LIGANDFILE   {prep_lig.absolute()}
NREPORT   5
POSES_PER_LIG   5
POSTDOCK   False
PRECISION   SP
    """)
    glide = which("glide")
    run([glide, "-WAIT", "-HOST", "localhost:6", str(glide_inp.absolute())], cwd=cwd)
    return

In [18]:
dockings = pd.read_pickle(glidedir / "glide-guided_dockings.pkl")
dockings

{'7gqu': {'7gqu': {'ciff': '../training_data/7.Extra_set/cifs/7gqu.cif',
   'pfile': '../training_data/7.Extra_set/pockets/7gqu/7gqu_out/7gqu_out.cif',
   'pocket': '1',
   'pocket_cog': [6.964241027832031, 26.42584991455078, 16.23856544494629],
   'guide_cog': [11.84740161895752, 24.034400939941406, 21.308034896850586]},
  '6yhr': {'ciff': '../training_data/8.Apos/Extra_set/cifs/6yhr.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/6yhr/6yhr_out/6yhr_out.cif',
   'pocket': '1',
   'pocket_cog': [-17.198780059814453,
    -19.426149368286133,
    32.649749755859375],
   'guide_cog': [-9.501700401306152, -14.058333396911621, 39.8582649230957]},
  '7gqt': {'ciff': 'pdb_ensemble/predictions/7gqt/7gqt.cif',
   'pfile': 'pdb_ensemble/predictions/7gqt/7gqt/7gqt_out/7gqt_out.cif',
   'pocket': '5',
   'pocket_cog': [11.266744613647461, -2.0004360675811768, -5.426126956939697],
   'guide_cog': [6.413934230804443, -3.6677331924438477, -8.020732879638672]},
  '8yle': {'ciff': 'pdb_ensemble/predictions/8yle/8yle.cif',
   'pfile': 'pdb_ensemble/predictions/8yle/8yle/8yle_out/8yle_out.cif',
   'pocket': '6',
   'pocket_cog': [6.363697052001953, -7.641810417175293, 0.4531156122684479],
   'guide_cog': [-6.90873384475708, -5.753566265106201, 7.870967388153076]},
  '8pfp': {'ciff': 'pdb_ensemble/predictions/8pfp/8pfp.cif',
   'pfile': 'pdb_ensemble/predictions/8pfp/8pfp/8pfp_out/8pfp_out.cif',
   'pocket': '1',
   'pocket_cog': [-17.97509002685547, 7.158182144165039, 9.536262512207031],
   'guide_cog': [-7.704867839813232, 2.473766565322876, 11.024534225463867]},
  '7gqs': {'ciff': 'pdb_ensemble/predictions/7gqs/7gqs.cif',
   'pfile': 'pdb_ensemble/predictions/7gqs/7gqs/7gqs_out/7gqs_out.cif',
   'pocket': '4',
   'pocket_cog': [11.357709884643555, -1.7662665843963623, -5.515999794006348],
   'guide_cog': [6.683000564575195, -3.7686004638671875, -7.885000705718994]}},
 '8aq6': {'8aq6': {'ciff': '../training_data/7.Extra_set/cifs/8aq6.cif',
   'pfile': '../training_data/7.Extra_set/pockets/8aq6/8aq6_out/8aq6_out.cif',
   'pocket': '2',
   'pocket_cog': [40.16830062866211, -51.84346008300781, 65.40921020507812],
   'guide_cog': [38.92204284667969, -59.504695892333984, 60.898197174072266]},
  '5b0u': {'ciff': '../training_data/8.Apos/Extra_set/cifs/5b0u.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/5b0u/5b0u_out/5b0u_out.cif',
   'pocket': '1',
   'pocket_cog': [28.245317459106445, 27.96975326538086, 43.79201126098633],
   'guide_cog': [35.227420806884766, 28.676387786865234, 43.2849235534668]},
  '7snr': {'ciff': 'pdb_ensemble/predictions/7snr/7snr.cif',
   'pfile': 'pdb_ensemble/predictions/7snr/7snr/7snr_out/7snr_out.cif',
   'pocket': '2',
   'pocket_cog': [133.0259552001953, 33.79324722290039, 29.09103012084961],
   'guide_cog': [137.623046875, 40.31365203857422, 35.556697845458984]},
  '7sny': {'ciff': 'pdb_ensemble/predictions/7sny/7sny.cif',
   'pfile': 'pdb_ensemble/predictions/7sny/7sny/7sny_out/7sny_out.cif',
   'pocket': '2',
   'pocket_cog': [6.688579559326172, -3.6231143474578857, 63.346229553222656],
   'guide_cog': [9.121615409851074, 6.974422931671143, 65.76019287109375]},
  '7snw': {'ciff': 'pdb_ensemble/predictions/7snw/7snw.cif',
   'pfile': 'pdb_ensemble/predictions/7snw/7snw/7snw_out/7snw_out.cif',
   'pocket': '1',
   'pocket_cog': [65.45156860351562, 109.23767852783203, 14.865564346313477],
   'guide_cog': [69.28231048583984, 113.86084747314453, 20.59257698059082]},
  '7sns': {'ciff': 'pdb_ensemble/predictions/7sns/7sns.cif',
   'pfile': 'pdb_ensemble/predictions/7sns/7sns/7sns_out/7sns_out.cif',
   'pocket': '3',
   'pocket_cog': [57.599449157714844, 28.328693389892578, 79.11487579345703],
   'guide_cog': [57.134681701660156, 24.25084686279297, 83.18798828125]},
  '7vsx': {'ciff': 'pdb_ensemble/predictions/7vsx/7vsx.cif',
   'pfile': 'pdb_ensemble/predictions/7vsx/7vsx/7vsx_out/7vsx_out.cif',
   'pocket': '1',
   'pocket_cog': [-10.302811622619629,
    -15.112927436828613,
    -15.666013717651367],
   'guide_cog': [-13.111617088317871,
    -16.868921279907227,
    -12.159461975097656]},
  '8aqh': {'ciff': 'pdb_ensemble/predictions/8aqh/8aqh.cif',
   'pfile': 'pdb_ensemble/predictions/8aqh/8aqh/8aqh_out/8aqh_out.cif',
   'pocket': '4',
   'pocket_cog': [-54.2391471862793, 17.073421478271484, 43.14850616455078],
   'guide_cog': [-48.35504150390625, 15.993961334228516, 35.631690979003906]},
  '7snt': {'ciff': 'pdb_ensemble/predictions/7snt/7snt.cif',
   'pfile': 'pdb_ensemble/predictions/7snt/7snt/7snt_out/7snt_out.cif',
   'pocket': '1',
   'pocket_cog': [-12.02538013458252, -12.078550338745117, 3.4684391021728516],
   'guide_cog': [-14.39673137664795, -9.652194023132324, 10.55765438079834]}},
 '8f4s': {'8f4s': {'ciff': '../training_data/7.Extra_set/cifs/8f4s.cif',
   'pfile': '../training_data/7.Extra_set/pockets/8f4s/8f4s_out/8f4s_out.cif',
   'pocket': '1',
   'pocket_cog': [95.75851440429688, 10.924911499023438, 24.291059494018555],
   'guide_cog': [90.02748107910156, 18.477998733520508, 31.52903175354004]},
  '7l6r': {'ciff': '../training_data/8.Apos/Extra_set/cifs/7l6r.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/7l6r/7l6r_out/7l6r_out.cif',
   'pocket': '9',
   'pocket_cog': [88.20286560058594, 11.680387496948242, 28.9742488861084],
   'guide_cog': [88.517578125, 17.66758155822754, 30.786998748779297]},
  '6wq3': {'ciff': 'pdb_ensemble/predictions/6wq3/6wq3.cif',
   'pfile': 'pdb_ensemble/predictions/6wq3/6wq3/6wq3_out/6wq3_out.cif',
   'pocket': '5',
   'pocket_cog': [87.14366149902344, 12.833354949951172, 30.51795196533203],
   'guide_cog': [88.29472351074219, 17.868545532226562, 30.963226318359375]},
  '7jz0': {'ciff': 'pdb_ensemble/predictions/7jz0/7jz0.cif',
   'pfile': 'pdb_ensemble/predictions/7jz0/7jz0/7jz0_out/7jz0_out.cif',
   'pocket': '1',
   'pocket_cog': [79.79010772705078, 26.901254653930664, 12.156694412231445],
   'guide_cog': [84.87199401855469, 16.384065628051758, 5.997677326202393]},
  '7lw4': {'ciff': 'pdb_ensemble/predictions/7lw4/7lw4.cif',
   'pfile': 'pdb_ensemble/predictions/7lw4/7lw4/7lw4_out/7lw4_out.cif',
   'pocket': '1',
   'pocket_cog': [-72.68659973144531, 69.00186920166016, -14.217886924743652],
   'guide_cog': [-65.00434112548828, 74.0802993774414, -4.225584983825684]},
  '8tyj': {'ciff': 'pdb_ensemble/predictions/8tyj/8tyj.cif',
   'pfile': 'pdb_ensemble/predictions/8tyj/8tyj/8tyj_out/8tyj_out.cif',
   'pocket': '2',
   'pocket_cog': [-83.14083862304688, 27.060863494873047, 12.9276762008667],
   'guide_cog': [-80.42852783203125, 17.822418212890625, 4.5462260246276855]},
  '9gtf': {'ciff': 'pdb_ensemble/predictions/9gtf/9gtf.cif',
   'pfile': 'pdb_ensemble/predictions/9gtf/9gtf/9gtf_out/9gtf_out.cif',
   'pocket': '1',
   'pocket_cog': [63.4195671081543, -13.847278594970703, -13.4227294921875],
   'guide_cog': [80.68462371826172, -17.78647232055664, 5.35790491104126]},
  '6wvn': {'ciff': 'pdb_ensemble/predictions/6wvn/6wvn.cif',
   'pfile': 'pdb_ensemble/predictions/6wvn/6wvn/6wvn_out/6wvn_out.cif',
   'pocket': '11',
   'pocket_cog': [87.53656005859375, 11.979421615600586, 29.33329200744629],
   'guide_cog': [88.13690185546875, 17.790485382080078, 30.94257926940918]},
  '9eun': {'ciff': 'pdb_ensemble/predictions/9eun/9eun.cif',
   'pfile': 'pdb_ensemble/predictions/9eun/9eun/9eun_out/9eun_out.cif',
   'pocket': '8',
   'pocket_cog': [80.2883529663086, -11.566944122314453, 29.528648376464844],
   'guide_cog': [79.95275115966797, -17.31999397277832, 31.068527221679688]},
  '7bq7': {'ciff': 'pdb_ensemble/predictions/7bq7/7bq7.cif',
   'pfile': 'pdb_ensemble/predictions/7bq7/7bq7/7bq7_out/7bq7_out.cif',
   'pocket': '1',
   'pocket_cog': [-83.67912292480469, 12.818089485168457, 28.44301986694336],
   'guide_cog': [-80.94503784179688, 18.113256454467773, 30.810930252075195]},
  '8ot0': {'ciff': 'pdb_ensemble/predictions/8ot0/8ot0.cif',
   'pfile': 'pdb_ensemble/predictions/8ot0/8ot0/8ot0_out/8ot0_out.cif',
   'pocket': '4',
   'pocket_cog': [80.32618713378906, -11.497466087341309, 3.024831533432007],
   'guide_cog': [79.9298095703125, -17.448741912841797, 4.86154842376709]},
  '9gs4': {'ciff': 'pdb_ensemble/predictions/9gs4/9gs4.cif',
   'pfile': 'pdb_ensemble/predictions/9gs4/9gs4/9gs4_out/9gs4_out.cif',
   'pocket': '10',
   'pocket_cog': [81.87879943847656, -27.4150447845459, 16.45928192138672],
   'guide_cog': [80.443359375, -17.689804077148438, 5.1989665031433105]},
  '8rze': {'ciff': 'pdb_ensemble/predictions/8rze/8rze.cif',
   'pfile': 'pdb_ensemble/predictions/8rze/8rze/8rze_out/8rze_out.cif',
   'pocket': '6',
   'pocket_cog': [51.51806640625, -64.86425018310547, -29.192529678344727],
   'guide_cog': [55.397193908691406, -60.74415969848633, -31.116195678710938]},
  '7lw3': {'ciff': 'pdb_ensemble/predictions/7lw3/7lw3.cif',
   'pfile': 'pdb_ensemble/predictions/7lw3/7lw3/7lw3_out/7lw3_out.cif',
   'pocket': '1',
   'pocket_cog': [89.42193603515625, -31.018707275390625, 28.218900680541992],
   'guide_cog': [87.50460815429688, -19.07390594482422, 33.90980911254883]},
  '7jhe': {'ciff': 'pdb_ensemble/predictions/7jhe/7jhe.cif',
   'pfile': 'pdb_ensemble/predictions/7jhe/7jhe/7jhe_out/7jhe_out.cif',
   'pocket': '2',
   'pocket_cog': [81.06795501708984, -13.209855079650879, 31.3674373626709],
   'guide_cog': [81.68911743164062, -18.13532257080078, 30.701932907104492]},
  '9emv': {'ciff': 'pdb_ensemble/predictions/9emv/9emv.cif',
   'pfile': 'pdb_ensemble/predictions/9emv/9emv/9emv_out/9emv_out.cif',
   'pocket': '1',
   'pocket_cog': [-83.32295227050781, 20.549131393432617, 9.010366439819336],
   'guide_cog': [-80.78097534179688, 17.773815155029297, 5.231509208679199]},
  '8rva': {'ciff': 'pdb_ensemble/predictions/8rva/8rva.cif',
   'pfile': 'pdb_ensemble/predictions/8rva/8rva/8rva_out/8rva_out.cif',
   'pocket': '2',
   'pocket_cog': [50.44717788696289, -64.08948516845703, -28.897836685180664],
   'guide_cog': [55.329471588134766, -60.69806671142578, -30.9145450592041]},
  '7r1t': {'ciff': 'pdb_ensemble/predictions/7r1t/7r1t.cif',
   'pfile': 'pdb_ensemble/predictions/7r1t/7r1t/7r1t_out/7r1t_out.cif',
   'pocket': '2',
   'pocket_cog': [114.77811431884766, 61.96919631958008, 17.148908615112305],
   'guide_cog': [112.96310424804688, 61.024192810058594, 20.53154945373535]},
  '7koa': {'ciff': 'pdb_ensemble/predictions/7koa/7koa.cif',
   'pfile': 'pdb_ensemble/predictions/7koa/7koa/7koa_out/7koa_out.cif',
   'pocket': '3',
   'pocket_cog': [81.18576049804688, -11.838713645935059, 29.171796798706055],
   'guide_cog': [81.63928985595703, -18.100933074951172, 30.687807083129883]},
  '6wrz': {'ciff': 'pdb_ensemble/predictions/6wrz/6wrz.cif',
   'pfile': 'pdb_ensemble/predictions/6wrz/6wrz/6wrz_out/6wrz_out.cif',
   'pocket': '3',
   'pocket_cog': [87.46039581298828, 12.53999137878418, 30.719417572021484],
   'guide_cog': [88.0216064453125, 17.735774993896484, 30.850582122802734]},
  '7r1u': {'ciff': 'pdb_ensemble/predictions/7r1u/7r1u.cif',
   'pfile': 'pdb_ensemble/predictions/7r1u/7r1u/7r1u_out/7r1u_out.cif',
   'pocket': '2',
   'pocket_cog': [29.203275680541992, 74.99868774414062, 12.862027168273926],
   'guide_cog': [24.839675903320312, 78.22573852539062, 12.41045093536377]},
  '6yz1': {'ciff': 'pdb_ensemble/predictions/6yz1/6yz1.cif',
   'pfile': 'pdb_ensemble/predictions/6yz1/6yz1/6yz1_out/6yz1_out.cif',
   'pocket': '7',
   'pocket_cog': [86.85052490234375, 11.792060852050781, 28.922252655029297],
   'guide_cog': [88.0063247680664, 17.714418411254883, 30.72474479675293]},
  '7ult': {'ciff': 'pdb_ensemble/predictions/7ult/7ult.cif',
   'pfile': 'pdb_ensemble/predictions/7ult/7ult/7ult_out/7ult_out.cif',
   'pocket': '4',
   'pocket_cog': [86.0709228515625, 10.585299491882324, 4.447271347045898],
   'guide_cog': [86.19480895996094, 16.469158172607422, 6.089290142059326]},
  '8rv8': {'ciff': 'pdb_ensemble/predictions/8rv8/8rv8.cif',
   'pfile': 'pdb_ensemble/predictions/8rv8/8rv8/8rv8_out/8rv8_out.cif',
   'pocket': '3',
   'pocket_cog': [51.59640884399414, -64.75687408447266, -27.98881721496582],
   'guide_cog': [55.46038818359375, -60.71657943725586, -31.111125946044922]},
  '6wjt': {'ciff': 'pdb_ensemble/predictions/6wjt/6wjt.cif',
   'pfile': 'pdb_ensemble/predictions/6wjt/6wjt/6wjt_out/6wjt_out.cif',
   'pocket': '2',
   'pocket_cog': [86.26611328125, 16.83509063720703, 13.60916519165039],
   'guide_cog': [85.84490203857422, 16.502580642700195, 5.833871364593506]},
  '8s8x': {'ciff': 'pdb_ensemble/predictions/8s8x/8s8x.cif',
   'pfile': 'pdb_ensemble/predictions/8s8x/8s8x/8s8x_out/8s8x_out.cif',
   'pocket': '3',
   'pocket_cog': [80.79888153076172, -11.760050773620605, 29.455408096313477],
   'guide_cog': [80.14029693603516, -17.424394607543945, 31.42073631286621]},
  '6xkm': {'ciff': 'pdb_ensemble/predictions/6xkm/6xkm.cif',
   'pfile': 'pdb_ensemble/predictions/6xkm/6xkm/6xkm_out/6xkm_out.cif',
   'pocket': '6',
   'pocket_cog': [-52.34562301635742, 66.17670440673828, -2.231057643890381],
   'guide_cog': [-56.411190032958984, 61.64054870605469, -4.557677745819092]},
  '6w61': {'ciff': 'pdb_ensemble/predictions/6w61/6w61.cif',
   'pfile': 'pdb_ensemble/predictions/6w61/6w61/6w61_out/6w61_out.cif',
   'pocket': '1',
   'pocket_cog': [-62.87925338745117, 53.706687927246094, -17.5388240814209],
   'guide_cog': [-55.53666687011719, 60.938934326171875, -4.9072585105896]},
  '8rv9': {'ciff': 'pdb_ensemble/predictions/8rv9/8rv9.cif',
   'pfile': 'pdb_ensemble/predictions/8rv9/8rv9/8rv9_out/8rv9_out.cif',
   'pocket': '1',
   'pocket_cog': [-62.549964904785156, 54.134151458740234, -42.39063262939453],
   'guide_cog': [-55.39282989501953, 60.82432174682617, -31.02448272705078]},
  '6wkq': {'ciff': 'pdb_ensemble/predictions/6wkq/6wkq.cif',
   'pfile': 'pdb_ensemble/predictions/6wkq/6wkq/6wkq_out/6wkq_out.cif',
   'pocket': '3',
   'pocket_cog': [82.32595825195312, 22.02030372619629, 11.355411529541016],
   'guide_cog': [85.70800018310547, 16.389968872070312, 5.843580722808838]},
  '9p6p': {'ciff': 'pdb_ensemble/predictions/9p6p/9p6p.cif',
   'pfile': 'pdb_ensemble/predictions/9p6p/9p6p/9p6p_out/9p6p_out.cif',
   'pocket': '6',
   'pocket_cog': [87.14909362792969, 10.562287330627441, 3.710559844970703],
   'guide_cog': [87.37992858886719, 16.51671028137207, 5.697129249572754]},
  '8otr': {'ciff': 'pdb_ensemble/predictions/8otr/8otr.cif',
   'pfile': 'pdb_ensemble/predictions/8otr/8otr/8otr_out/8otr_out.cif',
   'pocket': '3',
   'pocket_cog': [82.63831329345703, -11.74229907989502, 3.232374429702759],
   'guide_cog': [80.18416595458984, -17.50335693359375, 4.908870697021484]},
  '8rzc': {'ciff': 'pdb_ensemble/predictions/8rzc/8rzc.cif',
   'pfile': 'pdb_ensemble/predictions/8rzc/8rzc/8rzc_out/8rzc_out.cif',
   'pocket': '8',
   'pocket_cog': [81.86692810058594, -28.260940551757812, 43.67376708984375],
   'guide_cog': [80.39515686035156, -17.59406280517578, 31.22226333618164]},
  '7c2j': {'ciff': 'pdb_ensemble/predictions/7c2j/7c2j.cif',
   'pfile': 'pdb_ensemble/predictions/7c2j/7c2j/7c2j_out/7c2j_out.cif',
   'pocket': '1',
   'pocket_cog': [-82.88915252685547, 12.095958709716797, 27.66318702697754],
   'guide_cog': [-79.98873138427734, 17.456708908081055, 30.593225479125977]},
  '8s8w': {'ciff': 'pdb_ensemble/predictions/8s8w/8s8w.cif',
   'pfile': 'pdb_ensemble/predictions/8s8w/8s8w/8s8w_out/8s8w_out.cif',
   'pocket': '1',
   'pocket_cog': [81.95956420898438, -11.558030128479004, 29.154741287231445],
   'guide_cog': [79.80680847167969, -17.204036712646484, 31.071683883666992]},
  '8rv4': {'ciff': 'pdb_ensemble/predictions/8rv4/8rv4.cif',
   'pfile': 'pdb_ensemble/predictions/8rv4/8rv4/8rv4_out/8rv4_out.cif',
   'pocket': '11',
   'pocket_cog': [85.30885314941406, -29.989208221435547, 41.210777282714844],
   'guide_cog': [80.34935760498047, -17.690643310546875, 31.21245002746582]},
  '8c5m': {'ciff': 'pdb_ensemble/predictions/8c5m/8c5m.cif',
   'pfile': 'pdb_ensemble/predictions/8c5m/8c5m/8c5m_out/8c5m_out.cif',
   'pocket': '6',
   'pocket_cog': [80.17535400390625, -11.588397026062012, 2.959218978881836],
   'guide_cog': [79.8766860961914, -17.472742080688477, 4.895322799682617]},
  '9guf': {'ciff': 'pdb_ensemble/predictions/9guf/9guf.cif',
   'pfile': 'pdb_ensemble/predictions/9guf/9guf/9guf_out/9guf_out.cif',
   'pocket': '3',
   'pocket_cog': [81.6391372680664, -26.9648494720459, 16.14048194885254],
   'guide_cog': [80.15824127197266, -17.49601936340332, 5.250434398651123]},
  '7c2i': {'ciff': 'pdb_ensemble/predictions/7c2i/7c2i.cif',
   'pfile': 'pdb_ensemble/predictions/7c2i/7c2i/7c2i_out/7c2i_out.cif',
   'pocket': '11',
   'pocket_cog': [65.9066162109375, -58.62894058227539, -14.1229829788208],
   'guide_cog': [55.327579498291016, -60.78042221069336, -4.768968105316162]},
  '8osx': {'ciff': 'pdb_ensemble/predictions/8osx/8osx.cif',
   'pfile': 'pdb_ensemble/predictions/8osx/8osx/8osx_out/8osx_out.cif',
   'pocket': '9',
   'pocket_cog': [81.3266372680664, -11.804312705993652, 2.7351043224334717],
   'guide_cog': [80.2200927734375, -17.645545959472656, 5.03867769241333]},
  '8rv7': {'ciff': 'pdb_ensemble/predictions/8rv7/8rv7.cif',
   'pfile': 'pdb_ensemble/predictions/8rv7/8rv7/8rv7_out/8rv7_out.cif',
   'pocket': '10',
   'pocket_cog': [84.31755828857422, -27.593265533447266, 39.33242416381836],
   'guide_cog': [80.27935028076172, -17.485700607299805, 31.078758239746094]},
  '7jpe': {'ciff': 'pdb_ensemble/predictions/7jpe/7jpe.cif',
   'pfile': 'pdb_ensemble/predictions/7jpe/7jpe/7jpe_out/7jpe_out.cif',
   'pocket': '5',
   'pocket_cog': [51.822715759277344, -64.02667999267578, -4.118810653686523],
   'guide_cog': [56.61431884765625, -61.702354431152344, -4.279064655303955]},
  '7jyy': {'ciff': 'pdb_ensemble/predictions/7jyy/7jyy.cif',
   'pfile': 'pdb_ensemble/predictions/7jyy/7jyy/7jyy_out/7jyy_out.cif',
   'pocket': '9',
   'pocket_cog': [85.66382598876953, 10.042218208312988, 4.256856441497803],
   'guide_cog': [85.65982818603516, 16.1839656829834, 5.960355281829834]},
  '6w4h': {'ciff': 'pdb_ensemble/predictions/6w4h/6w4h.cif',
   'pfile': 'pdb_ensemble/predictions/6w4h/6w4h/6w4h_out/6w4h_out.cif',
   'pocket': '3',
   'pocket_cog': [87.66934204101562, 28.474828720092773, 42.96949005126953],
   'guide_cog': [87.49745178222656, 17.649066925048828, 30.628870010375977]},
  '9grq': {'ciff': 'pdb_ensemble/predictions/9grq/9grq.cif',
   'pfile': 'pdb_ensemble/predictions/9grq/9grq/9grq_out/9grq_out.cif',
   'pocket': '5',
   'pocket_cog': [79.84784698486328, -11.276945114135742, 3.5515317916870117],
   'guide_cog': [79.59967803955078, -17.262836456298828, 5.079322814941406]},
  '9emj': {'ciff': 'pdb_ensemble/predictions/9emj/9emj.cif',
   'pfile': 'pdb_ensemble/predictions/9emj/9emj/9emj_out/9emj_out.cif',
   'pocket': '4',
   'pocket_cog': [-80.6800537109375, 12.986982345581055, 30.814800262451172],
   'guide_cog': [-80.30436706542969, 17.607093811035156, 31.323225021362305]},
  '8vuo': {'ciff': 'pdb_ensemble/predictions/8vuo/8vuo.cif',
   'pfile': 'pdb_ensemble/predictions/8vuo/8vuo/8vuo_out/8vuo_out.cif',
   'pocket': '3',
   'pocket_cog': [-14.589003562927246, 9.936572074890137, 34.285648345947266],
   'guide_cog': [-10.446064949035645, 8.567322731018066, 22.802804946899414]},
  '7l6t': {'ciff': 'pdb_ensemble/predictions/7l6t/7l6t.cif',
   'pfile': 'pdb_ensemble/predictions/7l6t/7l6t/7l6t_out/7l6t_out.cif',
   'pocket': '10',
   'pocket_cog': [88.41502380371094, 11.79647159576416, 28.718231201171875],
   'guide_cog': [88.74848175048828, 17.81854820251465, 30.701419830322266]},
  '7jib': {'ciff': 'pdb_ensemble/predictions/7jib/7jib.cif',
   'pfile': 'pdb_ensemble/predictions/7jib/7jib/7jib_out/7jib_out.cif',
   'pocket': '1',
   'pocket_cog': [-80.84369659423828, 14.198736190795898, 7.406043529510498],
   'guide_cog': [-81.81280517578125, 18.10780906677246, 4.341677188873291]},
  '8a23': {'ciff': 'pdb_ensemble/predictions/8a23/8a23.cif',
   'pfile': 'pdb_ensemble/predictions/8a23/8a23/8a23_out/8a23_out.cif',
   'pocket': '10',
   'pocket_cog': [38.73638153076172, -0.19208994507789612, -37.18867874145508],

In [26]:
for holo, holod in dockings.items():
    for guide in ("pocket", "guide"):
        path = glidedir / f"{holo}_{guide}"
        path.mkdir(exist_ok=True)
    
        if (path / f"xglide/{holo}_topcomplexes.maegz").exists():
            continue
        
        grids = path / "grids"
        grids.mkdir(exist_ok=True)
        xout = path / "xglide"
        xout.mkdir(exist_ok=True)

        gridsl = ""
        for apo, apod in holod.items():
            apopath = path / apo
            apopath.mkdir(exist_ok=True)

            grid_zip = grids / f"{apo}_grid.zip"
            if not grid_zip.exists():
                build_grid(
                    grid_inp = grids / f"{apo}_grid.inp",
                    grid_zip = grid_zip,
                    receptor_mae = glidedir / holo / "preps" / (f"{apo}_prep.mae" if (holo != "8uk6" or holo == apo) else f"{apo}_updated_prep.mae"),
                    center = apod[f"{guide}_cog"],
                )
            gridsl += f"GRID	{grid_zip.absolute()}\n"

        xglide_inp = xout / f"{holo}.inp"    
        xglide_inp.write_text(f"""
{gridsl}
ALIGN	FALSE
LIGAND	{(glidedir / holo / f"{holo}.smi").absolute()}
GRIDGEN_GRID_CENTER	AUTO
GRIDGEN_INNERBOX	25
GRIDGEN_OUTERBOX	40
PPREP FALSE
LIGPREP	TRUE
LIGPREP_EPIK	TRUE
DOCK_PRECISION	SP
DOCK_WRITE_XP_DESC	FALSE
DOCK_POSE_OUTTYPE	poseviewer
DOCK_POSES_PER_LIG   5
NATIVEONLY	FALSE
DOCK_LIG_VSCALE	0.80
SKIP_DOCKING	FALSE
GOOD_RMSD	2.0
GENERATE_TOP_COMPLEXES	5
        """)
    
        run(
            " ".join((
                SCHRO + "/run xglide.py",
                xglide_inp.name,
                "-WAIT -HOST localhost:16 -TMPLAUNCHDIR"
            )),
            cwd=xout, 
            shell=True
        )

        counts = {}
        with sstruct.StructureReader(xout / f"{holo}_topcomplexes.maegz") as r:
            for i, st in enumerate(r, 1):
                apo = (
                    st.property.get("s_i_glide_gridfile", "grid")
                    .rsplit("_", 1)[0]
                    .replace("_updated", "").replace("updated", "")
                )# '8pfp_grid' or frame_0_grid
                rank = counts.get(apo, 0) + 1
                if rank == 6: continue
                fname = path / apo / f"{apo}_rank{rank}.pdb"
                with sstruct.StructureWriter(str(fname)) as w: w.append(st)
                counts[apo] = rank

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_0_grid.inp
JobId: avogadro-0-68dcef28
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_1_grid.inp
JobId: avogadro-0-68dcef48
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_2_grid.inp
JobId: avogadro-0-68dcef67
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_3_grid.inp
JobId: avogadro-0-68dcef86
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_4_grid.inp
JobId: avogadro-0-68dcefa5
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_5_grid.inp
JobId: avogadro-0-68dcefc5
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_6_grid.inp
JobId: avogadro-0-68dcefe4
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_7_grid.inp
JobId: avogadro-0-68dcf003
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_8_grid.inp
JobId: avogadro-0-68dcf022
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_9_grid.inp
JobId: avogadro-0-68dcf041
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_10_grid.inp
JobId: avogadro-0-68dcf061
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_11_grid.inp
JobId: avogadro-0-68dcf080
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_12_grid.inp
JobId: avogadro-0-68dcf09f
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_13_grid.inp
JobId: avogadro-0-68dcf0be
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_14_grid.inp
JobId: avogadro-0-68dcf0de
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_15_grid.inp
JobId: avogadro-0-68dcf0fd
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_16_grid.inp
JobId: avogadro-0-68dcf11c
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_17_grid.inp
JobId: avogadro-0-68dcf13b
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_18_grid.inp
JobId: avogadro-0-68dcf15b
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_19_grid.inp
JobId: avogadro-0-68dcf17a
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_20_grid.inp
JobId: avogadro-0-68dcf199
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_21_grid.inp
JobId: avogadro-0-68dcf1b8
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_22_grid.inp
JobId: avogadro-0-68dcf1d7
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_pocket/grids/frame_23_grid.inp
JobId: avogadro-0-68dcf1f7
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/run xglide.py 8uk6.inp -WAIT -HOST localhost:16 -TMPLAUNCHDIR
JobId: avogadro-0-68dcf216

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/8uk6_grid.inp
JobId: avogadro-0-68dcf259
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_0_grid.inp
JobId: avogadro-0-68dcf278
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_1_grid.inp
JobId: avogadro-0-68dcf297
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_2_grid.inp
JobId: avogadro-0-68dcf2b6
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_3_grid.inp
JobId: avogadro-0-68dcf2d6
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_4_grid.inp
JobId: avogadro-0-68dcf2f5
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_5_grid.inp
JobId: avogadro-0-68dcf314
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_6_grid.inp
JobId: avogadro-0-68dcf333
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_7_grid.inp
JobId: avogadro-0-68dcf353
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_8_grid.inp
JobId: avogadro-0-68dcf372
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_9_grid.inp
JobId: avogadro-0-68dcf391
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_10_grid.inp
JobId: avogadro-0-68dcf3b0
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_11_grid.inp
JobId: avogadro-0-68dcf3d0
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_12_grid.inp
JobId: avogadro-0-68dcf3ef
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_13_grid.inp
JobId: avogadro-0-68dcf40e
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_14_grid.inp
JobId: avogadro-0-68dcf42d
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_15_grid.inp
JobId: avogadro-0-68dcf44c
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_16_grid.inp
JobId: avogadro-0-68dcf46c
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_17_grid.inp
JobId: avogadro-0-68dcf48b
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_18_grid.inp
JobId: avogadro-0-68dcf4aa
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_19_grid.inp
JobId: avogadro-0-68dcf4c9
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_20_grid.inp
JobId: avogadro-0-68dcf4e9
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_21_grid.inp
JobId: avogadro-0-68dcf508
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_22_grid.inp
JobId: avogadro-0-68dcf527
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/glide -WAIT /home/fnerin/Desktop/AlloPockets/ensembles/glide/8uk6_guide/grids/frame_23_grid.inp
JobId: avogadro-0-68dcf546
ExitStatus: finished

[CMD] /opt/schrodinger2025-2/run xglide.py 8uk6.inp -WAIT -HOST localhost:16 -TMPLAUNCHDIR
JobId: avogadro-0-68dcf566

for holo, holod in dockings.items():
    prep_lig = glidedir / holo / f"{holo}_ligprep.mae"
    if not prep_lig.exists():
        prepare_ligands(
            smiles = glidedir / holo / f"{holo}.smi",
            ligprep_inp = glidedir / holo / f"{holo}_ligprep.inp",
            out_mae = prep_lig,
            cwd = glidedir / holo
        )
    
    for guide in ("pocket", "guide"):
        path = glidedir / f"{holo}_{guide}"
        path.mkdir(exist_ok=True)
    
        if (path / f"xglide/{holo}_topcomplexes.maegz").exists():
            continue
        
        # grids = path / "grids"
        # grids.mkdir(exist_ok=True)
        # xout = path / "xglide"
        # xout.mkdir(exist_ok=True)

        for apo, apod in holod.items():
            apopath = path / apo
            apopath.mkdir(exist_ok=True)
                
            grid_zip = apopath / f"{apo}_grid.zip"
            if not grid_zip.exists():
                build_grid(
                    grid_inp = apopath / f"{apo}_grid.inp",
                    grid_zip = grid_zip,
                    receptor_mae = glidedir / holo / "preps" / f"{apo}_prep.mae",
                    center = apod[f"{guide}_cog"],
                )

            dock_out = apopath / f"{apo}_glide_pv.maegz"
            if not dock_out.exists():
                dock(
                    glide_inp = apopath / f"{apo}_glide.in",
                    grid_zip = grid_zip,
                    prep_lig = prep_lig,
                    cwd = apopath,
                )

            if not (apopath / "rank_1.pdb").exists():
                with sstruct.StructureReader(dock_out) as r:
                    r = list(r)
                    prot = r[0]
                    assert "r_i_docking_score" not in prot.property
                    for i, st in enumerate(r[1:], 1):
                        assert "r_i_docking_score" in st.property
                        # complex_st = prot.copy()
                        # complex_st.extend(st)
                        # with sstruct.StructureWriter(apopath / f"rank_{i}.pdb") as w: w.append(complex_st)
                        with sstruct.StructureWriter(apopath / f"rank_{i}.pdb") as w: w.append(st)

# Guided - IFD

In [20]:
glidedir = Path("glide_ifd")
glidedir.mkdir(exist_ok=True)
(glidedir / "ligpreps").mkdir(exist_ok=True)

## LigPrep

In [21]:
cmd = [
    which("ligprep"),
    "-help"
]
run(cmd)

[CMD] /opt/schrodinger2025-2/ligprep -help
usage: ligprep [options] (-ismi|-icsv|-imae|-isd) infile (-osd|-omae|-osmi|-ocsv) outfile

General:
  -h, -help             Print brief help message.
  -long_help            Print exhaustive help message.
  -inp <filename>       Read arguments from the supplied input file.
  -sif_docs             List supported simplified input file format (SIF)
                        keywords.

Ionization:
  -epik                 Use Epik Classic for ionization and tautomerization
                        (Recommended, overrides -i).
  -epikx                Use Epik for ionization and tautomerization
                        (Recommended, overrides -i).
  -emb, -epik_metal_binding
                        Run Epik with the metal_binding option so that states
                        appropriate for interactions with metal ions in
                        protein binding pockets are also generated.
  -i {0,1,2}            Ionization treatment: 0 - do not neutralize or ionize,
                        1 - neutralize only, 2 - neutralize and ionize
                        (Default: 1). Note that -epik option overrides -i and
                        always implies ionization and tautomerization.
  -ph <number>          Effective/target pH. (default = 7.0 for Ionizer/Epik
                        Classic, 7.4 for Epik)
  -pht <number>         pH tolerance for generated structures.

Stereoisomers:
  -ac                   Do not respect existing chirality properties and do
                        not respect chiralities from the input geometry.
                        Generate stereoisomers for all chiral centers up to
                        the number permitted (specified using the -s option).
                        This is equivalent to "Generate all combinations" in
                        the Ligand Preparation user interface. Default
                        behavior is to respect only explicitly indicated
                        chiralities.
  -g                    Respect chiralities from input geometry when
                        generating stereoisomers.
  -s #                  Generate up to this many (#) stereoisomers per input
                        structure. (Default: 32).

Force-field based geometry optimization:
  -bff {14,16}          Force-field to be used for the final geometry
                        optimization. Default: 14 (OPLS_2005). For S-OPLS
                        specify 16.

Standard and job control options:
  -NJOBS NJOBS          Divide the overall job into NJOBS subjobs.
  -NSTRUCTS NSTRUCTS    Divide the overall job into subjobs with no more than
                        NSTRUCTS structures.
  -HOST <hostname>      Run job remotely on the indicated host entry.
  -WAIT                 Do not return a prompt until the job completes.
  -LOCAL                Do not use temporary directory for job files. Keep
                        files in the current directory.

Typical usage:
  Sample protonation states and stereoisomers, optimize geometry
  using OPLS force-field, and store results in Maestro format:

    ligprep <input> -omae outfile.maegz -epik

  where <input> is one of:
    -ismi infile.smi
    -icsv infile.csv
    -isd  infile.sd
    -imae infile.mae

In [44]:
def prepare_ligands(smiles: Path, holo: str, cwd: Path): # ligprep_inp: Path, out_mae: Path,
    # -> Path: #  pH: float = 7.4, dpH: float = 1.0
    """
    LigPrep with Epik states; outputs a single MAEGZ of prepared ligands.
    Accepts SDF/MAE/SMILES (SMILES must be in a .smi or via -ismi).
    """
    outmae = (cwd / f'{holo}.mae').absolute()
    ligprep_inp = cwd / f'{holo}.inp'
    ligprep_inp.write_text(f"""
INPUT_FILE_NAME   {smiles.absolute()}
MAX_ATOMS   500
FORCE_FIELD   16
EPIK   yes
EPIKX   no
EPIK_METAL_BINDING   no
INCLUDE_ORIGINAL_STATE   no
DETERMINE_CHIRALITIES   no
IGNORE_CHIRALITIES   yes
NUM_STEREOISOMERS   32
OUT_MAE   {outmae}
    """)

    # Detect SMILES input by extension
    # is_smiles = ligand_in.suffix.lower() in [".smi", ".smiles", ".can"] # has to be .smi
    ligprep = which("ligprep")
    cmd = [ligprep, "-WAIT", "-inp", str(ligprep_inp.absolute())]
    # Epik-like states around target pH
    # cmd += ["-ph", f"{pH}", "-pht", f"{dpH}", "-s", "1"]  # 1 conformer per state (adjust as needed)
    run(cmd, cwd=cwd)
    return outmae

## Dock

In [45]:
dockings = pd.read_pickle(glidedir.parent / "glide" / "glide-guided_dockings.pkl")
dockings

{'7gqu': {'7gqu': {'ciff': '../training_data/7.Extra_set/cifs/7gqu.cif',
   'pfile': '../training_data/7.Extra_set/pockets/7gqu/7gqu_out/7gqu_out.cif',
   'pocket': '1',
   'pocket_cog': [6.964241027832031, 26.42584991455078, 16.23856544494629],
   'guide_cog': [11.84740161895752, 24.034400939941406, 21.308034896850586]},
  '6yhr': {'ciff': '../training_data/8.Apos/Extra_set/cifs/6yhr.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/6yhr/6yhr_out/6yhr_out.cif',
   'pocket': '1',
   'pocket_cog': [-17.198780059814453,
    -19.426149368286133,
    32.649749755859375],
   'guide_cog': [-9.501700401306152, -14.058333396911621, 39.8582649230957]},
  '7gqt': {'ciff': 'pdb_ensemble/predictions/7gqt/7gqt.cif',
   'pfile': 'pdb_ensemble/predictions/7gqt/7gqt/7gqt_out/7gqt_out.cif',
   'pocket': '5',
   'pocket_cog': [11.266744613647461, -2.0004360675811768, -5.426126956939697],
   'guide_cog': [6.413934230804443, -3.6677331924438477, -8.020732879638672]},
  '8yle': {'ciff': 'pdb_ensemble/predictions/8yle/8yle.cif',
   'pfile': 'pdb_ensemble/predictions/8yle/8yle/8yle_out/8yle_out.cif',
   'pocket': '6',
   'pocket_cog': [6.363697052001953, -7.641810417175293, 0.4531156122684479],
   'guide_cog': [-6.90873384475708, -5.753566265106201, 7.870967388153076]},
  '8pfp': {'ciff': 'pdb_ensemble/predictions/8pfp/8pfp.cif',
   'pfile': 'pdb_ensemble/predictions/8pfp/8pfp/8pfp_out/8pfp_out.cif',
   'pocket': '1',
   'pocket_cog': [-17.97509002685547, 7.158182144165039, 9.536262512207031],
   'guide_cog': [-7.704867839813232, 2.473766565322876, 11.024534225463867]},
  '7gqs': {'ciff': 'pdb_ensemble/predictions/7gqs/7gqs.cif',
   'pfile': 'pdb_ensemble/predictions/7gqs/7gqs/7gqs_out/7gqs_out.cif',
   'pocket': '4',
   'pocket_cog': [11.357709884643555, -1.7662665843963623, -5.515999794006348],
   'guide_cog': [6.683000564575195, -3.7686004638671875, -7.885000705718994]}},
 '8aq6': {'8aq6': {'ciff': '../training_data/7.Extra_set/cifs/8aq6.cif',
   'pfile': '../training_data/7.Extra_set/pockets/8aq6/8aq6_out/8aq6_out.cif',
   'pocket': '2',
   'pocket_cog': [40.16830062866211, -51.84346008300781, 65.40921020507812],
   'guide_cog': [38.92204284667969, -59.504695892333984, 60.898197174072266]},
  '5b0u': {'ciff': '../training_data/8.Apos/Extra_set/cifs/5b0u.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/5b0u/5b0u_out/5b0u_out.cif',
   'pocket': '1',
   'pocket_cog': [28.245317459106445, 27.96975326538086, 43.79201126098633],
   'guide_cog': [35.227420806884766, 28.676387786865234, 43.2849235534668]},
  '7snr': {'ciff': 'pdb_ensemble/predictions/7snr/7snr.cif',
   'pfile': 'pdb_ensemble/predictions/7snr/7snr/7snr_out/7snr_out.cif',
   'pocket': '2',
   'pocket_cog': [133.0259552001953, 33.79324722290039, 29.09103012084961],
   'guide_cog': [137.623046875, 40.31365203857422, 35.556697845458984]},
  '7sny': {'ciff': 'pdb_ensemble/predictions/7sny/7sny.cif',
   'pfile': 'pdb_ensemble/predictions/7sny/7sny/7sny_out/7sny_out.cif',
   'pocket': '2',
   'pocket_cog': [6.688579559326172, -3.6231143474578857, 63.346229553222656],
   'guide_cog': [9.121615409851074, 6.974422931671143, 65.76019287109375]},
  '7snw': {'ciff': 'pdb_ensemble/predictions/7snw/7snw.cif',
   'pfile': 'pdb_ensemble/predictions/7snw/7snw/7snw_out/7snw_out.cif',
   'pocket': '1',
   'pocket_cog': [65.45156860351562, 109.23767852783203, 14.865564346313477],
   'guide_cog': [69.28231048583984, 113.86084747314453, 20.59257698059082]},
  '7sns': {'ciff': 'pdb_ensemble/predictions/7sns/7sns.cif',
   'pfile': 'pdb_ensemble/predictions/7sns/7sns/7sns_out/7sns_out.cif',
   'pocket': '3',
   'pocket_cog': [57.599449157714844, 28.328693389892578, 79.11487579345703],
   'guide_cog': [57.134681701660156, 24.25084686279297, 83.18798828125]},
  '7vsx': {'ciff': 'pdb_ensemble/predictions/7vsx/7vsx.cif',
   'pfile': 'pdb_ensemble/predictions/7vsx/7vsx/7vsx_out/7vsx_out.cif',
   'pocket': '1',
   'pocket_cog': [-10.302811622619629,
    -15.112927436828613,
    -15.666013717651367],
   'guide_cog': [-13.111617088317871,
    -16.868921279907227,
    -12.159461975097656]},
  '8aqh': {'ciff': 'pdb_ensemble/predictions/8aqh/8aqh.cif',
   'pfile': 'pdb_ensemble/predictions/8aqh/8aqh/8aqh_out/8aqh_out.cif',
   'pocket': '4',
   'pocket_cog': [-54.2391471862793, 17.073421478271484, 43.14850616455078],
   'guide_cog': [-48.35504150390625, 15.993961334228516, 35.631690979003906]},
  '7snt': {'ciff': 'pdb_ensemble/predictions/7snt/7snt.cif',
   'pfile': 'pdb_ensemble/predictions/7snt/7snt/7snt_out/7snt_out.cif',
   'pocket': '1',
   'pocket_cog': [-12.02538013458252, -12.078550338745117, 3.4684391021728516],
   'guide_cog': [-14.39673137664795, -9.652194023132324, 10.55765438079834]}},
 '8f4s': {'8f4s': {'ciff': '../training_data/7.Extra_set/cifs/8f4s.cif',
   'pfile': '../training_data/7.Extra_set/pockets/8f4s/8f4s_out/8f4s_out.cif',
   'pocket': '1',
   'pocket_cog': [95.75851440429688, 10.924911499023438, 24.291059494018555],
   'guide_cog': [90.02748107910156, 18.477998733520508, 31.52903175354004]},
  '7l6r': {'ciff': '../training_data/8.Apos/Extra_set/cifs/7l6r.cif',
   'pfile': '../training_data/8.Apos/Extra_set/pockets/7l6r/7l6r_out/7l6r_out.cif',
   'pocket': '9',
   'pocket_cog': [88.20286560058594, 11.680387496948242, 28.9742488861084],
   'guide_cog': [88.517578125, 17.66758155822754, 30.786998748779297]},
  '6wq3': {'ciff': 'pdb_ensemble/predictions/6wq3/6wq3.cif',
   'pfile': 'pdb_ensemble/predictions/6wq3/6wq3/6wq3_out/6wq3_out.cif',
   'pocket': '5',
   'pocket_cog': [87.14366149902344, 12.833354949951172, 30.51795196533203],
   'guide_cog': [88.29472351074219, 17.868545532226562, 30.963226318359375]},
  '7jz0': {'ciff': 'pdb_ensemble/predictions/7jz0/7jz0.cif',
   'pfile': 'pdb_ensemble/predictions/7jz0/7jz0/7jz0_out/7jz0_out.cif',
   'pocket': '1',
   'pocket_cog': [79.79010772705078, 26.901254653930664, 12.156694412231445],
   'guide_cog': [84.87199401855469, 16.384065628051758, 5.997677326202393]},
  '7lw4': {'ciff': 'pdb_ensemble/predictions/7lw4/7lw4.cif',
   'pfile': 'pdb_ensemble/predictions/7lw4/7lw4/7lw4_out/7lw4_out.cif',
   'pocket': '1',
   'pocket_cog': [-72.68659973144531, 69.00186920166016, -14.217886924743652],
   'guide_cog': [-65.00434112548828, 74.0802993774414, -4.225584983825684]},
  '8tyj': {'ciff': 'pdb_ensemble/predictions/8tyj/8tyj.cif',
   'pfile': 'pdb_ensemble/predictions/8tyj/8tyj/8tyj_out/8tyj_out.cif',
   'pocket': '2',
   'pocket_cog': [-83.14083862304688, 27.060863494873047, 12.9276762008667],
   'guide_cog': [-80.42852783203125, 17.822418212890625, 4.5462260246276855]},
  '9gtf': {'ciff': 'pdb_ensemble/predictions/9gtf/9gtf.cif',
   'pfile': 'pdb_ensemble/predictions/9gtf/9gtf/9gtf_out/9gtf_out.cif',
   'pocket': '1',
   'pocket_cog': [63.4195671081543, -13.847278594970703, -13.4227294921875],
   'guide_cog': [80.68462371826172, -17.78647232055664, 5.35790491104126]},
  '6wvn': {'ciff': 'pdb_ensemble/predictions/6wvn/6wvn.cif',
   'pfile': 'pdb_ensemble/predictions/6wvn/6wvn/6wvn_out/6wvn_out.cif',
   'pocket': '11',
   'pocket_cog': [87.53656005859375, 11.979421615600586, 29.33329200744629],
   'guide_cog': [88.13690185546875, 17.790485382080078, 30.94257926940918]},
  '9eun': {'ciff': 'pdb_ensemble/predictions/9eun/9eun.cif',
   'pfile': 'pdb_ensemble/predictions/9eun/9eun/9eun_out/9eun_out.cif',
   'pocket': '8',
   'pocket_cog': [80.2883529663086, -11.566944122314453, 29.528648376464844],
   'guide_cog': [79.95275115966797, -17.31999397277832, 31.068527221679688]},
  '7bq7': {'ciff': 'pdb_ensemble/predictions/7bq7/7bq7.cif',
   'pfile': 'pdb_ensemble/predictions/7bq7/7bq7/7bq7_out/7bq7_out.cif',
   'pocket': '1',
   'pocket_cog': [-83.67912292480469, 12.818089485168457, 28.44301986694336],
   'guide_cog': [-80.94503784179688, 18.113256454467773, 30.810930252075195]},
  '8ot0': {'ciff': 'pdb_ensemble/predictions/8ot0/8ot0.cif',
   'pfile': 'pdb_ensemble/predictions/8ot0/8ot0/8ot0_out/8ot0_out.cif',
   'pocket': '4',
   'pocket_cog': [80.32618713378906, -11.497466087341309, 3.024831533432007],
   'guide_cog': [79.9298095703125, -17.448741912841797, 4.86154842376709]},
  '9gs4': {'ciff': 'pdb_ensemble/predictions/9gs4/9gs4.cif',
   'pfile': 'pdb_ensemble/predictions/9gs4/9gs4/9gs4_out/9gs4_out.cif',
   'pocket': '10',
   'pocket_cog': [81.87879943847656, -27.4150447845459, 16.45928192138672],
   'guide_cog': [80.443359375, -17.689804077148438, 5.1989665031433105]},
  '8rze': {'ciff': 'pdb_ensemble/predictions/8rze/8rze.cif',
   'pfile': 'pdb_ensemble/predictions/8rze/8rze/8rze_out/8rze_out.cif',
   'pocket': '6',
   'pocket_cog': [51.51806640625, -64.86425018310547, -29.192529678344727],
   'guide_cog': [55.397193908691406, -60.74415969848633, -31.116195678710938]},
  '7lw3': {'ciff': 'pdb_ensemble/predictions/7lw3/7lw3.cif',
   'pfile': 'pdb_ensemble/predictions/7lw3/7lw3/7lw3_out/7lw3_out.cif',
   'pocket': '1',
   'pocket_cog': [89.42193603515625, -31.018707275390625, 28.218900680541992],
   'guide_cog': [87.50460815429688, -19.07390594482422, 33.90980911254883]},
  '7jhe': {'ciff': 'pdb_ensemble/predictions/7jhe/7jhe.cif',
   'pfile': 'pdb_ensemble/predictions/7jhe/7jhe/7jhe_out/7jhe_out.cif',
   'pocket': '2',
   'pocket_cog': [81.06795501708984, -13.209855079650879, 31.3674373626709],
   'guide_cog': [81.68911743164062, -18.13532257080078, 30.701932907104492]},
  '9emv': {'ciff': 'pdb_ensemble/predictions/9emv/9emv.cif',
   'pfile': 'pdb_ensemble/predictions/9emv/9emv/9emv_out/9emv_out.cif',
   'pocket': '1',
   'pocket_cog': [-83.32295227050781, 20.549131393432617, 9.010366439819336],
   'guide_cog': [-80.78097534179688, 17.773815155029297, 5.231509208679199]},
  '8rva': {'ciff': 'pdb_ensemble/predictions/8rva/8rva.cif',
   'pfile': 'pdb_ensemble/predictions/8rva/8rva/8rva_out/8rva_out.cif',
   'pocket': '2',
   'pocket_cog': [50.44717788696289, -64.08948516845703, -28.897836685180664],
   'guide_cog': [55.329471588134766, -60.69806671142578, -30.9145450592041]},
  '7r1t': {'ciff': 'pdb_ensemble/predictions/7r1t/7r1t.cif',
   'pfile': 'pdb_ensemble/predictions/7r1t/7r1t/7r1t_out/7r1t_out.cif',
   'pocket': '2',
   'pocket_cog': [114.77811431884766, 61.96919631958008, 17.148908615112305],
   'guide_cog': [112.96310424804688, 61.024192810058594, 20.53154945373535]},
  '7koa': {'ciff': 'pdb_ensemble/predictions/7koa/7koa.cif',
   'pfile': 'pdb_ensemble/predictions/7koa/7koa/7koa_out/7koa_out.cif',
   'pocket': '3',
   'pocket_cog': [81.18576049804688, -11.838713645935059, 29.171796798706055],
   'guide_cog': [81.63928985595703, -18.100933074951172, 30.687807083129883]},
  '6wrz': {'ciff': 'pdb_ensemble/predictions/6wrz/6wrz.cif',
   'pfile': 'pdb_ensemble/predictions/6wrz/6wrz/6wrz_out/6wrz_out.cif',
   'pocket': '3',
   'pocket_cog': [87.46039581298828, 12.53999137878418, 30.719417572021484],
   'guide_cog': [88.0216064453125, 17.735774993896484, 30.850582122802734]},
  '7r1u': {'ciff': 'pdb_ensemble/predictions/7r1u/7r1u.cif',
   'pfile': 'pdb_ensemble/predictions/7r1u/7r1u/7r1u_out/7r1u_out.cif',
   'pocket': '2',
   'pocket_cog': [29.203275680541992, 74.99868774414062, 12.862027168273926],
   'guide_cog': [24.839675903320312, 78.22573852539062, 12.41045093536377]},
  '6yz1': {'ciff': 'pdb_ensemble/predictions/6yz1/6yz1.cif',
   'pfile': 'pdb_ensemble/predictions/6yz1/6yz1/6yz1_out/6yz1_out.cif',
   'pocket': '7',
   'pocket_cog': [86.85052490234375, 11.792060852050781, 28.922252655029297],
   'guide_cog': [88.0063247680664, 17.714418411254883, 30.72474479675293]},
  '7ult': {'ciff': 'pdb_ensemble/predictions/7ult/7ult.cif',
   'pfile': 'pdb_ensemble/predictions/7ult/7ult/7ult_out/7ult_out.cif',
   'pocket': '4',
   'pocket_cog': [86.0709228515625, 10.585299491882324, 4.447271347045898],
   'guide_cog': [86.19480895996094, 16.469158172607422, 6.089290142059326]},
  '8rv8': {'ciff': 'pdb_ensemble/predictions/8rv8/8rv8.cif',
   'pfile': 'pdb_ensemble/predictions/8rv8/8rv8/8rv8_out/8rv8_out.cif',
   'pocket': '3',
   'pocket_cog': [51.59640884399414, -64.75687408447266, -27.98881721496582],
   'guide_cog': [55.46038818359375, -60.71657943725586, -31.111125946044922]},
  '6wjt': {'ciff': 'pdb_ensemble/predictions/6wjt/6wjt.cif',
   'pfile': 'pdb_ensemble/predictions/6wjt/6wjt/6wjt_out/6wjt_out.cif',
   'pocket': '2',
   'pocket_cog': [86.26611328125, 16.83509063720703, 13.60916519165039],
   'guide_cog': [85.84490203857422, 16.502580642700195, 5.833871364593506]},
  '8s8x': {'ciff': 'pdb_ensemble/predictions/8s8x/8s8x.cif',
   'pfile': 'pdb_ensemble/predictions/8s8x/8s8x/8s8x_out/8s8x_out.cif',
   'pocket': '3',
   'pocket_cog': [80.79888153076172, -11.760050773620605, 29.455408096313477],
   'guide_cog': [80.14029693603516, -17.424394607543945, 31.42073631286621]},
  '6xkm': {'ciff': 'pdb_ensemble/predictions/6xkm/6xkm.cif',
   'pfile': 'pdb_ensemble/predictions/6xkm/6xkm/6xkm_out/6xkm_out.cif',
   'pocket': '6',
   'pocket_cog': [-52.34562301635742, 66.17670440673828, -2.231057643890381],
   'guide_cog': [-56.411190032958984, 61.64054870605469, -4.557677745819092]},
  '6w61': {'ciff': 'pdb_ensemble/predictions/6w61/6w61.cif',
   'pfile': 'pdb_ensemble/predictions/6w61/6w61/6w61_out/6w61_out.cif',
   'pocket': '1',
   'pocket_cog': [-62.87925338745117, 53.706687927246094, -17.5388240814209],
   'guide_cog': [-55.53666687011719, 60.938934326171875, -4.9072585105896]},
  '8rv9': {'ciff': 'pdb_ensemble/predictions/8rv9/8rv9.cif',
   'pfile': 'pdb_ensemble/predictions/8rv9/8rv9/8rv9_out/8rv9_out.cif',
   'pocket': '1',
   'pocket_cog': [-62.549964904785156, 54.134151458740234, -42.39063262939453],
   'guide_cog': [-55.39282989501953, 60.82432174682617, -31.02448272705078]},
  '6wkq': {'ciff': 'pdb_ensemble/predictions/6wkq/6wkq.cif',
   'pfile': 'pdb_ensemble/predictions/6wkq/6wkq/6wkq_out/6wkq_out.cif',
   'pocket': '3',
   'pocket_cog': [82.32595825195312, 22.02030372619629, 11.355411529541016],
   'guide_cog': [85.70800018310547, 16.389968872070312, 5.843580722808838]},
  '9p6p': {'ciff': 'pdb_ensemble/predictions/9p6p/9p6p.cif',
   'pfile': 'pdb_ensemble/predictions/9p6p/9p6p/9p6p_out/9p6p_out.cif',
   'pocket': '6',
   'pocket_cog': [87.14909362792969, 10.562287330627441, 3.710559844970703],
   'guide_cog': [87.37992858886719, 16.51671028137207, 5.697129249572754]},
  '8otr': {'ciff': 'pdb_ensemble/predictions/8otr/8otr.cif',
   'pfile': 'pdb_ensemble/predictions/8otr/8otr/8otr_out/8otr_out.cif',
   'pocket': '3',
   'pocket_cog': [82.63831329345703, -11.74229907989502, 3.232374429702759],
   'guide_cog': [80.18416595458984, -17.50335693359375, 4.908870697021484]},
  '8rzc': {'ciff': 'pdb_ensemble/predictions/8rzc/8rzc.cif',
   'pfile': 'pdb_ensemble/predictions/8rzc/8rzc/8rzc_out/8rzc_out.cif',
   'pocket': '8',
   'pocket_cog': [81.86692810058594, -28.260940551757812, 43.67376708984375],
   'guide_cog': [80.39515686035156, -17.59406280517578, 31.22226333618164]},
  '7c2j': {'ciff': 'pdb_ensemble/predictions/7c2j/7c2j.cif',
   'pfile': 'pdb_ensemble/predictions/7c2j/7c2j/7c2j_out/7c2j_out.cif',
   'pocket': '1',
   'pocket_cog': [-82.88915252685547, 12.095958709716797, 27.66318702697754],
   'guide_cog': [-79.98873138427734, 17.456708908081055, 30.593225479125977]},
  '8s8w': {'ciff': 'pdb_ensemble/predictions/8s8w/8s8w.cif',
   'pfile': 'pdb_ensemble/predictions/8s8w/8s8w/8s8w_out/8s8w_out.cif',
   'pocket': '1',
   'pocket_cog': [81.95956420898438, -11.558030128479004, 29.154741287231445],
   'guide_cog': [79.80680847167969, -17.204036712646484, 31.071683883666992]},
  '8rv4': {'ciff': 'pdb_ensemble/predictions/8rv4/8rv4.cif',
   'pfile': 'pdb_ensemble/predictions/8rv4/8rv4/8rv4_out/8rv4_out.cif',
   'pocket': '11',
   'pocket_cog': [85.30885314941406, -29.989208221435547, 41.210777282714844],
   'guide_cog': [80.34935760498047, -17.690643310546875, 31.21245002746582]},
  '8c5m': {'ciff': 'pdb_ensemble/predictions/8c5m/8c5m.cif',
   'pfile': 'pdb_ensemble/predictions/8c5m/8c5m/8c5m_out/8c5m_out.cif',
   'pocket': '6',
   'pocket_cog': [80.17535400390625, -11.588397026062012, 2.959218978881836],
   'guide_cog': [79.8766860961914, -17.472742080688477, 4.895322799682617]},
  '9guf': {'ciff': 'pdb_ensemble/predictions/9guf/9guf.cif',
   'pfile': 'pdb_ensemble/predictions/9guf/9guf/9guf_out/9guf_out.cif',
   'pocket': '3',
   'pocket_cog': [81.6391372680664, -26.9648494720459, 16.14048194885254],
   'guide_cog': [80.15824127197266, -17.49601936340332, 5.250434398651123]},
  '7c2i': {'ciff': 'pdb_ensemble/predictions/7c2i/7c2i.cif',
   'pfile': 'pdb_ensemble/predictions/7c2i/7c2i/7c2i_out/7c2i_out.cif',
   'pocket': '11',
   'pocket_cog': [65.9066162109375, -58.62894058227539, -14.1229829788208],
   'guide_cog': [55.327579498291016, -60.78042221069336, -4.768968105316162]},
  '8osx': {'ciff': 'pdb_ensemble/predictions/8osx/8osx.cif',
   'pfile': 'pdb_ensemble/predictions/8osx/8osx/8osx_out/8osx_out.cif',
   'pocket': '9',
   'pocket_cog': [81.3266372680664, -11.804312705993652, 2.7351043224334717],
   'guide_cog': [80.2200927734375, -17.645545959472656, 5.03867769241333]},
  '8rv7': {'ciff': 'pdb_ensemble/predictions/8rv7/8rv7.cif',
   'pfile': 'pdb_ensemble/predictions/8rv7/8rv7/8rv7_out/8rv7_out.cif',
   'pocket': '10',
   'pocket_cog': [84.31755828857422, -27.593265533447266, 39.33242416381836],
   'guide_cog': [80.27935028076172, -17.485700607299805, 31.078758239746094]},
  '7jpe': {'ciff': 'pdb_ensemble/predictions/7jpe/7jpe.cif',
   'pfile': 'pdb_ensemble/predictions/7jpe/7jpe/7jpe_out/7jpe_out.cif',
   'pocket': '5',
   'pocket_cog': [51.822715759277344, -64.02667999267578, -4.118810653686523],
   'guide_cog': [56.61431884765625, -61.702354431152344, -4.279064655303955]},
  '7jyy': {'ciff': 'pdb_ensemble/predictions/7jyy/7jyy.cif',
   'pfile': 'pdb_ensemble/predictions/7jyy/7jyy/7jyy_out/7jyy_out.cif',
   'pocket': '9',
   'pocket_cog': [85.66382598876953, 10.042218208312988, 4.256856441497803],
   'guide_cog': [85.65982818603516, 16.1839656829834, 5.960355281829834]},
  '6w4h': {'ciff': 'pdb_ensemble/predictions/6w4h/6w4h.cif',
   'pfile': 'pdb_ensemble/predictions/6w4h/6w4h/6w4h_out/6w4h_out.cif',
   'pocket': '3',
   'pocket_cog': [87.66934204101562, 28.474828720092773, 42.96949005126953],
   'guide_cog': [87.49745178222656, 17.649066925048828, 30.628870010375977]},
  '9grq': {'ciff': 'pdb_ensemble/predictions/9grq/9grq.cif',
   'pfile': 'pdb_ensemble/predictions/9grq/9grq/9grq_out/9grq_out.cif',
   'pocket': '5',
   'pocket_cog': [79.84784698486328, -11.276945114135742, 3.5515317916870117],
   'guide_cog': [79.59967803955078, -17.262836456298828, 5.079322814941406]},
  '9emj': {'ciff': 'pdb_ensemble/predictions/9emj/9emj.cif',
   'pfile': 'pdb_ensemble/predictions/9emj/9emj/9emj_out/9emj_out.cif',
   'pocket': '4',
   'pocket_cog': [-80.6800537109375, 12.986982345581055, 30.814800262451172],
   'guide_cog': [-80.30436706542969, 17.607093811035156, 31.323225021362305]},
  '8vuo': {'ciff': 'pdb_ensemble/predictions/8vuo/8vuo.cif',
   'pfile': 'pdb_ensemble/predictions/8vuo/8vuo/8vuo_out/8vuo_out.cif',
   'pocket': '3',
   'pocket_cog': [-14.589003562927246, 9.936572074890137, 34.285648345947266],
   'guide_cog': [-10.446064949035645, 8.567322731018066, 22.802804946899414]},
  '7l6t': {'ciff': 'pdb_ensemble/predictions/7l6t/7l6t.cif',
   'pfile': 'pdb_ensemble/predictions/7l6t/7l6t/7l6t_out/7l6t_out.cif',
   'pocket': '10',
   'pocket_cog': [88.41502380371094, 11.79647159576416, 28.718231201171875],
   'guide_cog': [88.74848175048828, 17.81854820251465, 30.701419830322266]},
  '7jib': {'ciff': 'pdb_ensemble/predictions/7jib/7jib.cif',
   'pfile': 'pdb_ensemble/predictions/7jib/7jib/7jib_out/7jib_out.cif',
   'pocket': '1',
   'pocket_cog': [-80.84369659423828, 14.198736190795898, 7.406043529510498],
   'guide_cog': [-81.81280517578125, 18.10780906677246, 4.341677188873291]},
  '8a23': {'ciff': 'pdb_ensemble/predictions/8a23/8a23.cif',
   'pfile': 'pdb_ensemble/predictions/8a23/8a23/8a23_out/8a23_out.cif',
   'pocket': '10',
   'pocket_cog': [38.73638153076172, -0.19208994507789612, -37.18867874145508],

In [46]:
inp_str = lambda strucmae, ligprep: f"""
#  Multiple input structures can be specified by adding additional
#  INPUT_FILE lines or including multiple structures in a single
#  file.
#
#  If beginning with an existing Pose Viewer file, simply specify
#  it as the INPUT_FILE (making sure the name ends in "_pv.mae"
#  or "_pv.maegz") and ensure that the first GLIDE_DOCKING stage
#  is commented out.  The ligand used in producing the Pose Viewer
#  file must also be provided to the second GLIDE_DOCKING stage,
#  using the LIGAND_FILE keyword.

INPUT_FILE	{strucmae}

# Prime Loop Prediction
#  Perform a loop prediction on the specified loop, including
#  side chains within the given distance.  Only return
#  structures within the specified energy range from the
#  lowest energy prediction, up to the maximum number of
#  conformations given.
#
#  Note: This stage is disabled by default.  Uncomment the
#   lines below and edit the fields appropriately to enable it.
#STAGE PRIME_LOOP
#  START_RESIDUE A:11
#  END_RESIDUE A:16
#  RES_SPHERE 7.5
#  MAX_ENERGY_GAP 30.0
#  MAX_STRUCTURES 5
#  USE_MEMBRANE no

STAGE GLIDE_DOCKING2
  BINDING_SITE ligand Z:899
  INNERBOX 15.0
  OUTERBOX 30.0
  LIGAND_FILE  {ligprep}
  LIGANDS_TO_DOCK all
  GRIDGEN_RECEP_CCUT  0.25
  GRIDGEN_RECEP_VSCALE 0.50
  GRIDGEN_FORCEFIELD OPLS_2005
  DOCKING_PRECISION SP
  DOCKING_LIG_CCUT  0.15
  DOCKING_CV_CUTOFF  100.0
  DOCKING_LIG_VSCALE 0.50
  DOCKING_POSES_PER_LIG 20
  DOCKING_FORCEFIELD OPLS_2005
  DOCKING_RINGCONFCUT 2.5
  DOCKING_AMIDE_MODE penal

STAGE COMPILE_RESIDUE_LIST
  DISTANCE_CUTOFF	5.0

STAGE PRIME_REFINEMENT
  NUMBER_OF_PASSES	1
  USE_MEMBRANE no
  OPLS_VERSION OPLS_2005

STAGE SORT_AND_FILTER
  POSE_FILTER	r_psp_Prime_Energy
  POSE_KEEP	30.0

STAGE SORT_AND_FILTER
  POSE_FILTER	r_psp_Prime_Energy
  POSE_KEEP	20#

STAGE GLIDE_DOCKING2
  BINDING_SITE ligand Z:999
  INNERBOX 10.0
  OUTERBOX auto
  LIGAND_FILE  {ligprep}
  LIGANDS_TO_DOCK self
  GRIDGEN_RECEP_CCUT  0.25
  GRIDGEN_RECEP_VSCALE 1.00
  GRIDGEN_FORCEFIELD OPLS_2005
  DOCKING_PRECISION SP
  DOCKING_LIG_CCUT  0.15
  DOCKING_CV_CUTOFF  0.0
  DOCKING_LIG_VSCALE 0.80
  DOCKING_POSES_PER_LIG 1
  DOCKING_FORCEFIELD OPLS_2005
  DOCKING_RINGCONFCUT 2.5
  DOCKING_AMIDE_MODE penal

STAGE SCORING
  SCORE_NAME  r_psp_IFDScore
  TERM 1.0,r_i_glide_gscore,0
  TERM 0.05,r_psp_Prime_Energy,1
  REPORT_FILE report.csv
"""

In [47]:
from schrodinger.structure import StructureReader, StructureWriter

In [69]:
for holo, holod in dockings.items():        
    if not ( glidedir / "ligpreps" / f"{holo}.mae" ).exists():
        outmae = prepare_ligands((glidedir.parent / "glide" / holo / f"{holo}.smi").absolute(), holo, glidedir / "ligpreps")
    
    for guide in ("pocket", "guide"):
        path = glidedir / f"{holo}_{guide}"
        path.mkdir(exist_ok=True)

        for apo, apod in holod.items():
            apopath = path / apo
            apopath.mkdir(exist_ok=True)
            if (apopath / f"{apo}-out.maegz").exists():
                continue

            cog_coords = apod[f"{guide}_cog"]
            strucmae = apopath / f"{apo}_center.mae"
            if holo == "8uk6" and apo != "8uk6":
                st = next(StructureReader((glidedir.parent / "glide" / holo / "preps" / f"{apo}_updated_prep.mae")))
            else:
                st = next(StructureReader((glidedir.parent / "glide" / holo / "preps" / f"{apo}_prep.mae")))
            a = st.addAtom("Du", *cog_coords)
            a.pdbres = "DUM"
            a.resnum = 899
            a.chain = "Z"
            StructureWriter(strucmae).append(st)
            StructureWriter(str(strucmae).replace(".mae", ".pdb")).append(st)
    
            ifd_inp = apopath / f"{apo}.inp"
            ifd_inp.write_text(
                inp_str(strucmae.name, outmae.absolute())
            )
        
            run(
                " ".join((
                    SCHRO + "/ifd",
                    ifd_inp.name,
                    "-NGLIDECPU 16 -NPRIMECPU 16 -NOLOCAL -HOST localhost -SUBHOST localhost -TMPLAUNCHDIR -WAIT"
                )),
                cwd=apopath, 
                shell=True
            )
            
            for rank, st in enumerate(
                sorted(
                    StructureReader(apopath / f"{apo}-out.maegz"), 
                    key=lambda st: st.property.get("r_psp_IFDScore")
                )[:5],
                1
            ):
                fname = apopath / f"{apo}_rank{rank}.pdb"
                with sstruct.StructureWriter(str(fname)) as w: w.append(st)

# OLD

# Functions

In [1]:
#!/usr/bin/env python
# blind_glide.py
"""
Blind docking with Glide using SiteMap site centers.

Pipeline:
  1) Protein preparation (prepwizard)
  2) Site detection (sitemap) -> site centers
  3) Build a Glide grid per site center
  4) Ligand preparation (ligprep + epik states)
  5) Dock ligands into each grid (glide)
  6) Collect top poses per grid and overall

Usage example (run with Schrodinger's Python):
  $SCHRODINGER/run python blind_glide.py \
      --receptor 1mj5.pdb \
      --ligand lig.sdf \
      --outdir run1 \
      --precision HTVS \
      --num_sites 5 \
      --inner 14 --outer 30

Notes:
- Requires a working Schrödinger 2025-2 installation (prepwizard, sitemap, ligprep, glide).
- "Blind" here means we auto-detect pockets and dock to each without prior knowledge.
"""

'\nBlind docking with Glide using SiteMap site centers.\n\nPipeline:\n  1) Protein preparation (prepwizard)\n  2) Site detection (sitemap) -> site centers\n  3) Build a Glide grid per site center\n  4) Ligand preparation (ligprep + epik states)\n  5) Dock ligands into each grid (glide)\n  6) Collect top poses per grid and overall\n\nUsage example (run with Schrodinger\'s Python):\n  $SCHRODINGER/run python blind_glide.py       --receptor 1mj5.pdb       --ligand lig.sdf       --outdir run1       --precision HTVS       --num_sites 5       --inner 14 --outer 30\n\nNotes:\n- Requires a working Schrödinger 2025-2 installation (prepwizard, sitemap, ligprep, glide).\n- "Blind" here means we auto-detect pockets and dock to each without prior knowledge.\n'

In [11]:
import argparse
import gzip
import os
import shutil
import subprocess as sp
import sys
import tempfile
from pathlib import Path
from typing import List, Tuple, Optional
import pandas as pd

In [3]:
# We'll read MAE/MAEGZ only if we need to compute centers from site points
try:
    from schrodinger import structure as sstruct
except Exception:
    sstruct = None

SCHRO = os.environ.get("SCHRODINGER") or "/opt/schrodinger2025-2"

In [4]:
sstruct

## General

In [15]:
def run(cmd: List[str], cwd: Optional[str] = None, **kwargs) -> None:
    print(f"[CMD] {cmd if 'shell' in kwargs else ' '.join(cmd)}")
    p = sp.run(cmd, check=True, cwd=cwd, text=True, capture_output=True, **kwargs)
    print(p.stdout)
    return


def which(tool: str) -> str:
    """Return full path to a Schrödinger CLI tool."""
    p = Path(SCHRO) / tool
    if p.exists():
        return str(p)
    # Some tools live at the root (e.g., $SCHRODINGER/prepwizard), others under subdirs.
    for sub in ["", "utilities", "shape_screen", "glide", "sitemap", "ligprep", "epik", "vsw"]:
        pp = Path(SCHRO) / sub / tool
        if pp.exists():
            return str(pp)
    return tool  # fallback on PATH


def ensure_outdir(d: Path):
    d.mkdir(parents=True, exist_ok=True)
    print(f"[INFO] Output directory: {d}")

## ProtPrep

In [16]:
cmd = [
    which("prepwizard"),
    "--help"
]
run(cmd)

[CMD] /opt/schrodinger2025-2/utilities/prepwizard --help
usage: $SCHRODINGER/utilities/prepwizard [options] inputfile outputfile
    Input file should be in Maestro or PDB format.
    Output file should be in Maestro or PDB format.


Required:
  in_file               Input structure file (Maestro or PDB)
  out_file              Output structure file (Maestro or PDB)

Preprocess:
  -nopreprocess         Skip pre-processing (useful if only ProtAssign or
                        Impref is desired)
  -reference_st_file REFERENCE_ST_FILE
                        File containing reference structure to align to.
  -reference_pdbid REFERENCE_PDBID
                        PDB ID of the structure to align to.
  -nobondorders         Don't assign bond orders to het groups
  -noccd                Don't use the Chemical Component Dictionary when
                        assigning bond orders.
  -assign_all_residues  Assign bond orders to all residues (by default
                        residues are only processed if they only have single
                        order bonds). If CCD is used, existing bond orders and
                        formal charges will be overriden for residues that are
                        present in the CCD.
  -nohtreat             Don't add hydrogens
  -rehtreat             Delete and re-add hydrogens (will reset PDB atom
                        names)
  -nometaltreat         Don't treat metals (adding zero-order bonds, etc)
  -disulfides           Create bonds to proximal Sulfurs (delete hydrogens as
                        needed)
  -glycosylation        Create bonds to N-linked and O-linked sugars (delete
                        hydrogens as needed)
  -palmitoylation       Create palmitoylation bonds even if not included in
                        the CONNECT records (delete hydrogens as needed)
  -antibody_cdr_scheme {Chothia,Kabat,IMGT,EnhancedChothia,AHo,None}
                        CDR annotation scheme.
  -renumber_ab_residues
                        Renumber antibodies residues to match the scheme
                        specified with the -antibody_cdr_scheme option.
  -tcr_cdr_scheme {IMGT,AHo,None}
                        CDR annotation scheme.
  -renumber_tcr_residues
                        Renumber TCR residues to match the scheme specified
                        with the -tcr_cdr_scheme option.
  -mse                  Convert Selenomethionine residues to Methionines
  -preprocess_watdist PREPROCESS_WATDIST
                        If specified, during preprocessing delete waters that
                        are further than this distance from het groups. By
                        default, waters are deleted during cleanup.
  -fillloops            Fill missing loops with Prime
  -fasta_file CUSTOM_FASTA_FILE
                        If filling missing residues, the custom fasta file to
                        use. If not specified, the fasta file will be
                        generated from the sequence that was stored in the
                        input structure when it was converted from the PDB
                        format.
  -fillsidechains       Fill missing side chains with Prime
  -addOXT               Add terminal oxygens to polypeptides
  -c, -captermini       Cap termini
  -cap_termini_min_atoms CAP_TERMINI_MIN_ATOMS
                        By default, only proteins with more than 200 atoms are
                        capped when -captermini is specified. Use this option
                        to allow capping of smaller molecules.
  -noepik               Don't run Epik on het groups. By default Epik is ran
                        on all het groups, and metal binding states are
                        considered for hets that are within 5A of metal atoms.
  -epik_pH EPIK_PH      Epik target pH (default 7.0)
  -epik_pHt EPIK_PHT    Epik pH range for generated structures (default 2.0)
  -max_states MAX_STATES, -ms MAX_STATES
                        Maximum number of het states to generate for each
                        protein complex.
  -noidealizehtf        Don't idealize added hydrogen temperature factors.

Optimize H-bond Assignments:
  -noprotassign         Don't run ProtAssign
  -s, -samplewater      Sample water states
  -include_epik_states  Include Epik embedded states in optimization
  -xtal                 Use crystal symmetry
  -nopropka             Do not use PROPKA for protonation states
  -propka_pH PROPKA_PH  Run PROPKA at given pH value (default 7.0)
  -label_pkas           Label residues with PROPKA pKas
  -pH {very_low,low,neutral,high}
                        Sample at given pH when not using PROPKA (default
                        neutral)
  -force FORCE_LIST FORCE_LIST
                        Force a particular residue to adapt the specified
                        state. Multiple -f specifications are permitted. See
                        $SCHRODINGER/utilities/protassign help for more info.
  -minimize_adj_h       Energy minimize all adjustable hydrogens (titratable
                        hydrogens, water hydrogens, hydroxyls, thiols, and
                        ASN/GLN carboxamide hydrogens).

Minimize and Delete Waters:
  -noimpref             Don't run a restrained minimization job
  -r RMSD, -rmsd RMSD   Minimization: RMSD cutoff in angstrom (default 0.3)
  -fix                  Minimization: Fix heavy atoms (minimize hydrogens
                        only)
  -f {2005,2.1,3,S-OPLS,OPLS_2005}
                        Minimization: Version of the OPLS force field to use.
                        Options: 2005 or 3 (default OPLS_2005)
  -keepfarwat           Don't delete waters far from het groups
  -watdist WATDIST      Distance threshold for 'far' waters (default 5.0A)
  -delwater_hbond_cutoff DELWATER_HBOND_CUTOFF
                        If specified, delete waters that do not make at least
                        this number H-bonds to non-waters. By default, this
                        feature is disabled (default 0).

Other:
  -preserve_st_titles   Preserve titles of structures. By default they are
                        annotated to show which structures were prepared
  -use_PDB_pH           If input structure has property r_pdb_PDB_EXPDTA_PH,
                        use that for Epik and ProtAssign/PROPKA.
  -h, --help            show this help message and exit
  -j J                  Deprecated. Use -JOBNAME instead.

Job Control Options:
  -HOST <hostname>      Run job remotely on the indicated host entry.
  -WAIT                 Do not return a prompt until the job completes.
  -SAVE                 Return zip archive of job directory at job completion.
  -NOJOBID              Run the job directly, without Job Control layer.
  -JOBNAME JOBNAME      Provide an explicit name for the job.

In [27]:
def prepare_protein(infile: Path, out, cwd: Path) -> Path:
    """Protein Preparation Wizard (prepwizard) → MAE"""
    prep_out =  f"{out}_prep.mae" #outdir /
    if (cwd / prep_out).exists():
        return
    prepwizard = which("prepwizard")
    # Typical settings: assign bond orders, add H, optimize H-bond network, restrained minimization.
    cmd = [
        prepwizard,
        "-WAIT",
        "-assign_all_residues", #  Assign bond orders to all residues (by default residues are only processed if they only have single order bonds). If CCD is used, existing bond orders and formal charges will be overriden for residues that are present in the CCD.
        "-rehtreat", # Delete and re-add hydrogens (will reset PDB atom names)
        "-disulfides", # Create bonds to proximal Sulfurs (delete hydrogens as needed)
        "-mse", # Convert Selenomethionine residues to Methionines
        "-max_states 1", # Maximum number of het states to generate for each protein complex.
        "-captermini", # Add terminal oxygens to polypeptides, Cap termini
        # "-minimize_adj_h", # Energy minimize all adjustable hydrogens (titratable hydrogens, water hydrogens, hydroxyls, thiols, and ASN/GLN carboxamide hydrogens).
        "-f S-OPLS",
        "-epik_pH 7.4 -epik_pHt 2.0 -samplewater -include_epik_states -propka_pH 7.4  -rmsd 0.3 -watdist 5.0",
        
        # "-noprotassign",   # speed-up; set as needed
        # "-noimpref",       # we’ll still do a restrained minimization
        
        str(infile.absolute()),
        str(prep_out),
    ]
    run(" ".join(cmd), cwd=cwd, shell=True)
    return #prep_out

## SiteMap

In [19]:
cmd = [
    which("sitemap"),
    "--help"
]
run(cmd)

[CMD] /opt/schrodinger2025-2/sitemap --help
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
usage:
        $SCHRODINGER/sitemap [options] -j <jobname> -prot <file.mae>
    or
        $SCHRODINGER/sitemap [options] <input_file.in>

$SCHRODINGER/sitemap carries out a site-finding job, then calculates SiteMaps
for each qualifying site-point grouping, and finally evaluates the SiteMap
results and summarizes the characteristics of the sites in a series of Maestro
properties. SiteMap can be invoked from Maestro or can be run from the command
line.

positional arguments:
  input_file            A file with lines such as "KEYWORD value", which are
                        equivalent to "-keyword value" command-line arguments.
                        (Except for job control options such as -HOST)

options:
  -j <jobname>, -job <jobname>, -jobname <jobname>
                        A unique descriptor for this data set, used to make
                        some file names unique. Required when not using an
                        input file.
  -h, -help             Show this help message and exit.

Job Control Options:
  -HOST <hostname>      Run job remotely on the indicated host entry.

Common SiteMap Options:
  -prot <file.mae> [<file.mae>...], -protein <file.mae> [<file.mae>...]
                        A required protein file in Maestro format. Multiple
                        such options may be specified to run multiple jobs.
  -lig <file>, -ligmae <file>, -ligsdf <file>
                        include optional ligand file in Maestro or SD format
  -receptortype <auto, protein, rna>
                        Specify the type of receptor to be protein or RNA.
                        auto mode will determine the receptor type
                        automatically
  -siteasl <asl>        ASL expression used instead of a ligand to restrict
                        the site-finding step.
  -sitebox <dist>       If an optional ligand file or ASL expression is
                        specified, restrict the site-finding step to a box
                        placed around the ligand plus a margin of <dist>
                        (default 6.0)
  -addsp [yes|no]       Add additional "extend" site points to the site-point
                        set if they fall in regions that satisfy the threshold
                        criteria for phobicity or philicity (default, "yes")
  -xcent XCENT          X coordinate of grid center, to be used instead of
                        ligand-, receptor-, or ASL-based centroid
  -ycent <float>        Y coordinate of grid center
  -zcent <float>        Z coordinate of grid center
  -xrange <float>       X size of grid box, to be used instead of receptor-,
                        or ASL-based box size
  -yrange <float>       Y size of grid box
  -zrange <float>       Z size of grid box
  -reportsize <size>    Minimum number of site points needed to report a site
                        grouping (default, 15)
  -maxsites <max>       Find/report up to this number of sites (default, 5)
  -modphobic {0|1|2|3}  Set definition to be used in defining hydrophobic
                        regions (default, 3)
  -grid <gridsize>      Grid size to be used in the SiteMap calculations
                        (default, 0.7 A)
  -resolution <val>     Alternative means for specifying the grid size
                        (<val>="low" for 1.0 A, "standard" for 0.7 A or "high"
                        for 0.35 A)
  -mapdist <dist>       Restrict displayed SiteMaps to <dist> from the nearest
                        site point (default, 4 A). Can be overriden, up to the
                        "-margin <margin>" distance, by using the Surface
                        Limit facility
  -ffield <OPLS version>
                        Version of OPLS to use (default, OPLS_2005)
  -extend <intdist>     In evaluating exposure in site-evaluation stage, try
                        adding additional site points at grid points +/-
                        <intdist> from an original site point (default, 3 A)
  -compact_mode_threshold <float>
                        If SiteMap generates sites with volumes above this
                        threshold, a 2nd sitemap run will start with settings
                        for the compact mode. To disable the 2nd sitemap run,
                        set a negative number like -1. (default, 800 Å³)
  -cleanup [yes|no]     Retain intermediate files (*.grd, *_volpts.pdb)
  -compress [yes|no]    Compress the final _out.mae file using gzip. (default,
                        "yes")
  -keepvolpts [yes|no]  keeps pdb-format files that contain the points that
                        are summed to compute the volume property assigned for
                        the site (default, "no")
  -writepot [yes|no]    writes (x,y,z,potential) files that specify the
                        phobic, philic, donor, acceptor, vdW, electrostatic,
                        and surface potentials computed by SiteMap (default,
                        "no")
  -keepvdw [yes|no]     computes and keeps grid-format file of vdW potentials
                        computed by SiteMap (default, "no")
  -keepelec [yes|no]    computes and keeps grid-format file of electrostatic
                        potentials computed by SiteMap (default, "no")
  -writestructs [yes|no]
                        include a copy of the receptor structure (and ligand,
                        if any) in the output file (default, "yes")
  -writevis [yes|no]    write .vis and .smap files for surface visualization
                        (default, "yes")
  -writegrids [yes|no]  write all .grd files (default, "no")

Additional Options:
  -enclosure <fraction>
                        Fraction of ray directions from a grid point that must
                        intersect the protein within a specified distance for
                        that grid point to be considered as a potential site
                        point (default, 0.5)
  -maxdist <dist>       Distance within which a directional ray from a
                        candidate grid point must intersect the protein
                        surface (default, 8 A)
  -maxvdw <vdw-energy>  vdW interaction-energy threshold (kcal/mol) for a grid
                        point to qualify as a potential site point (default,
                        1.1). Note this quantity is the negative of the
                        computed interaction energy, so that the argument
                        supplied must be positive. A smaller positive value
                        keeps more candidate site points
  -verbosity {0|1|2|3}  Control level of detail in output log files (default,
                        0)
  -margin <margin>      Grid-box margin to be used in the SiteMap calculations
                        (default, 6 A)
  -addphob <thresh>     Set criterion for adding additional phobic points to
                        <thresh> (default, -0.50 kcal/mol if modphobic
                        argument is 2 or 3, otherwise -0.75 kcal/mol)
  -addphil <thresh>     Set criterion for adding additional philic points
                        (default, -8 kcal/mol)

Advanced Options:
  -dvscale <float>      When multiplied by the square of a protein-atom vdW
                        radius, the argument sets the squared distance from a
                        candidate site point to a protein atom for determining
                        whether the site point is "inside" or "outside" the
                        protein (default, 2.5)
  -nthresh <int>        Minimum number of candidate site-point neighbors
                        required to be within a distance of sqrt(d2thresh) for
                        a candidate site point to be eligible for inclusion in
                        a site-point grouping (default, 3)
  -d2thresh <float>     Squared distance used in nthresh test (default 3.1
                        A**2)
  -kmax <int>           Maximum sum of differences in grid indices to nearest
                        site point allowed to add a candidate site point to a
                        site-point group (default, 3)
  -kmax2 <int>          Maximum sum of squares of differences in grid indices
                        to nearest site point allowed for a candidate site
                        point to be added to a site-point group (default, 5)
  -mingroup <int>       Minimum number of points in a site-point grouping
                        required to constitute a site (default, 3)
  -dthresh <float>      Maximum acceptable value for the minimum distance
                        separating site points in two site-point groupings for
                        them to be considered for merger into a single group
                        (default, 6.5 A)
  -rthresh <float>      Minimum acceptable ratio of the distance between the
                        centroids of two site-point groups relative to the
                        effective sizes of the groups (default, 5.)
  -r2thresh <float>     Squared distance used in determining whether two site-
                        point groupings being considered for merger have
                        successfully been interconnected by solvent-exposed
                        bridging points (default, 4.1 A**2)
  -cutoff <cutdist>     The cutdist value restricts the calculation of vdW and
                        electrostatic potentials to protein atoms that lie
                        within this distance of a grid point (default, 20 A)
  -modcharges [yes|no]  The default value of "yes" scales down formal-charge
                        contributions to the protein partial atomic charges by
                        50%
  -nearres <float>      Maximum distance between sitepoints and residues to
                        list in the s_sitemap_residues property (default, 3.5
                        A).

In [ ]:
def run_sitemap(receptor_mae: Path, outdir: Path, num_sites: int) -> Path:
    """
    Run SiteMap and return the base name used by sitemap outputs.
    We’ll use --maxsites to limit.
    """
    sitemap = which("sitemap")
    base = outdir / "sitemap_job"
    cmd = [
        sitemap,
        "-WAIT",
        "-jobname", str(base.name),
        "-protein", str(receptor_mae),
        # "-sitebox 6", # default
        # "-compact_mode_threshold 800" # default
        # -maxsites 5 default
        "-verbosity 3",
        "-keepvolpts yes",
        # "-cleanup no -compress no -keepvolpts yes -writepot yes -keepvdw yes -keepelec yes -writestructs yes -writegrids yes",
        
        # "-site", "1",              # start site index; CLI will enumerate sites
        # "-maxsites", str(num_sites),
        # "-sitebox", "20.0",        # search box (~protein-centric); adjust if needed
        # "-writecsv",               # request CSV summary (contains per-site properties; often includes centers)
        # "-writePoints",            # write site points maegz (fallback to compute centers)
    ]
    run(" ".join(cmd), cwd=str(outdir), shell=True)

    # run(f"{SCHRO}/utilities/proplister {str(base.name)}_out.maegz -a -c -o {base.name}_site_properties.csv", shell=True)
    return base

### Centers

In [30]:
def centroid_of_points(points: List[Tuple[float,float,float]]) -> Tuple[float,float,float]:
    if not points:
        raise ValueError("No points to centroid.")
    n = len(points)
    sx = sum(p[0] for p in points)
    sy = sum(p[1] for p in points)
    sz = sum(p[2] for p in points)
    return (sx/n, sy/n, sz/n)


def parse_centers_from_volpts(job_dir: Path, jobname: str) -> List[Tuple[float, float, float]]:
    """
    Compute a centroid per site from the *_volpts.pdb files produced by -keepvolpts yes.
    Accepts common filename patterns:
      {jobname}_site{N}_volpts.pdb
      {jobname}_site{N}.volpts.pdb
      {jobname}_site{N}-volpts.pdb
      or any '*site*volpts.pdb' within the job directory.
    """
    import glob

    patterns = [
        f"{jobname}_site*_volpts.pdb",
        f"{jobname}_site*.volpts.pdb",
        f"{jobname}_site*-volpts.pdb",
        "*site*volpts.pdb",
    ]
    pdb_paths = []
    for pat in patterns:
        pdb_paths.extend([Path(p) for p in glob.glob(str(job_dir / pat))])

    centers: List[Tuple[float,float,float]] = []

    for pdb in sorted(set(pdb_paths)):
        pts: List[Tuple[float,float,float]] = []
        with pdb.open() as f:
            for line in f:
                if line.startswith(("ATOM","HETATM")):
                    # PDB columns: x(31–38), y(39–46), z(47–54) (1-based)
                    try:
                        x = float(line[30:38].strip())
                        y = float(line[38:46].strip())
                        z = float(line[46:54].strip())
                        pts.append((x,y,z))
                    except ValueError:
                        continue
        if pts:
            centers.append(centroid_of_points(pts))
    return centers


def collect_site_centers(sitemap_base: Path) -> List[Tuple[float,float,float]]: # (job_folder: Path, jobname: str)
    """
    Preferred order:
      1) proplister CSV from myjob_out.mae → parse_centers_from_props_csv
      2) fall back to centroids from *_volpts.pdb files
    """
    # csv_path = job_folder / f"{jobname}_props.csv"     # your own exported filename
    # # If you instead use the raw proplister output name:
    # if not csv_path.exists():
    #     alt = job_folder / f"{jobname}_props.tsv"
    #     if alt.exists():
    #         csv_path = alt
    #     else:
    #         # very common name when calling: proplister myjob_out.mae -a -c -o myjob_props.csv
    #         common = job_folder / f"{jobname}_props.csv"
    #         if common.exists():
    #             csv_path = common

    # centers = parse_centers_from_props_csv(csv_path)
    # if centers:
    #     return centers

    # Fallback: compute from volpts
    return parse_centers_from_volpts(sitemap_base, sitemap_base)

In [32]:
parse_centers_from_volpts(Path("Glide.prj/jobs/sitemap_test"), jobname="test")

[(93.78350855745711, 11.69895354523225, 26.4618875305624),
 (109.88894463667802, 16.39640830449828, 13.259522491349498),
 (83.3760526315787, 16.661157894736874, 29.032210526315755),
 (98.86999999999992, 9.624666666666652, 22.507583333333347),
 (86.04350746268638, 27.978895522388118, 40.05979104477609)]

def parse_centers_from_csv(csv_path: Path) -> List[Tuple[float, float, float]]:
    """
    Parse SiteMap CSV for site centers, if present.
    CSV format can vary, but often has columns 'X', 'Y', 'Z' or 'Center X', 'Center Y', 'Center Z'.
    """
    centers = []
    if not csv_path.exists():
        return centers
    import csv
    with csv_path.open() as f:
        rdr = csv.DictReader(f)
        for row in rdr:
            # Try a few common header variants
            keys = row.keys()
            def getf(*names):
                for n in names:
                    if n in keys and row[n].strip():
                        return float(row[n])
                return None
            x = getf("X", "Center X", "CenterX", "r_x")
            y = getf("Y", "Center Y", "CenterY", "r_y")
            z = getf("Z", "Center Z", "CenterZ", "r_z")
            if x is not None and y is not None and z is not None:
                centers.append((x, y, z))
    return centers


def centroid_of_points(xs: List[Tuple[float, float, float]]) -> Tuple[float, float, float]:
    import math
    if not xs:
        raise ValueError("No points to centroid.")
    sx = sum(p[0] for p in xs)
    sy = sum(p[1] for p in xs)
    sz = sum(p[2] for p in xs)
    n = len(xs)
    return (sx / n, sy / n, sz / n)


def parse_centers_from_points_maegz(points_maegz: Path) -> List[Tuple[float, float, float]]:
    """
    Fallback: compute one centroid per 'site' from site points MAEGZ.
    We assume each site is in a separate block or has a property we can split on.
    Many sitemap runs write a single 'site_points.maegz' with multiple structures named 'Site #'.
    """
    if sstruct is None:
        return []

    def open_reader(p: Path):
        if p.suffix == ".maegz":
            return sstruct.StructureReader(str(p))
        elif p.suffix == ".mae":
            return sstruct.StructureReader(str(p))
        elif p.suffixes[-2:] == [".mae", ".gz"]:
            return sstruct.StructureReader(gzip.open(p, "rt"))
        else:
            return sstruct.StructureReader(str(p))

    centers = []
    # Common filenames from sitemap with -writePoints:
    #   <jobname>_site_points.maegz
    candidates = [points_maegz]
    for cand in candidates:
        if not cand.exists():
            continue
        # Each Structure may represent one site's cloud of points.
        for st in open_reader(cand):
            pts = [(a.x, a.y, a.z) for a in st.atom]
            if pts:
                centers.append(centroid_of_points(pts))
    return centers


def collect_site_centers(sitemap_base: Path) -> List[Tuple[float, float, float]]:
    """
    Try CSV first; if not usable, compute from site points.
    """
    csv_path = sitemap_base.with_suffix("")  # strip .suffix if any
    # SiteMap tends to create <jobname>_site_properties.csv
    csv_file = sitemap_base.parent / f"{sitemap_base.name}_site_properties.csv"
    centers = parse_centers_from_csv(csv_file)
    if centers:
        print(f"[INFO] Found {len(centers)} site centers in CSV.")
        return centers

    # Fallback to points maegz
    points_file = sitemap_base.parent / f"{sitemap_base.name}_site_points.maegz"
    centers = parse_centers_from_points_maegz(points_file)
    print(f"[INFO] Computed {len(centers)} site centers from site points.")
    return centers

## Grid

In [ ]:
def write_glide_grid_in(
    grid_in: Path,
    receptor_mae: Path,
    center: Tuple[float, float, float],
    inner: 10,#float,
    outer: 30#float
) -> None:
    x, y, z = center
    contents = f"""FORCEFIELD   OPLS_2005
GRID_CENTER   {x:.8f}, {y:.8f}, {z:.8f}
GRIDFILE   {grid_in.with_suffix('.zip')}
INNERBOX   {inner:.2f}, {inner:.2f}, {inner:.2f}
OUTERBOX   {outer:.2f}, {outer:.2f}, {outer:.2f}
RECEP_FILE   {receptor_mae}
"""
    grid_in.write_text(contents)

def build_grid(grid_in: Path) -> Path:
    glide = which("glide")
    run([glide, "-WAIT", str(grid_in)])
    grid_zip = grid_in.with_suffix(".zip")
    if not grid_zip.exists():
        raise RuntimeError(f"Grid not created: {grid_zip}")
    return grid_zip

## LigPrep

In [34]:
cmd = [
    which("ligprep"),
    "-help"
]
run(cmd)

[CMD] /opt/schrodinger2025-2/ligprep -help
usage: ligprep [options] (-ismi|-icsv|-imae|-isd) infile (-osd|-omae|-osmi|-ocsv) outfile

General:
  -h, -help             Print brief help message.
  -long_help            Print exhaustive help message.
  -inp <filename>       Read arguments from the supplied input file.
  -sif_docs             List supported simplified input file format (SIF)
                        keywords.

Ionization:
  -epik                 Use Epik Classic for ionization and tautomerization
                        (Recommended, overrides -i).
  -epikx                Use Epik for ionization and tautomerization
                        (Recommended, overrides -i).
  -emb, -epik_metal_binding
                        Run Epik with the metal_binding option so that states
                        appropriate for interactions with metal ions in
                        protein binding pockets are also generated.
  -i {0,1,2}            Ionization treatment: 0 - do not neutralize or ionize,
                        1 - neutralize only, 2 - neutralize and ionize
                        (Default: 1). Note that -epik option overrides -i and
                        always implies ionization and tautomerization.
  -ph <number>          Effective/target pH. (default = 7.0 for Ionizer/Epik
                        Classic, 7.4 for Epik)
  -pht <number>         pH tolerance for generated structures.

Stereoisomers:
  -ac                   Do not respect existing chirality properties and do
                        not respect chiralities from the input geometry.
                        Generate stereoisomers for all chiral centers up to
                        the number permitted (specified using the -s option).
                        This is equivalent to "Generate all combinations" in
                        the Ligand Preparation user interface. Default
                        behavior is to respect only explicitly indicated
                        chiralities.
  -g                    Respect chiralities from input geometry when
                        generating stereoisomers.
  -s #                  Generate up to this many (#) stereoisomers per input
                        structure. (Default: 32).

Force-field based geometry optimization:
  -bff {14,16}          Force-field to be used for the final geometry
                        optimization. Default: 14 (OPLS_2005). For S-OPLS
                        specify 16.

Standard and job control options:
  -NJOBS NJOBS          Divide the overall job into NJOBS subjobs.
  -NSTRUCTS NSTRUCTS    Divide the overall job into subjobs with no more than
                        NSTRUCTS structures.
  -HOST <hostname>      Run job remotely on the indicated host entry.
  -WAIT                 Do not return a prompt until the job completes.
  -LOCAL                Do not use temporary directory for job files. Keep
                        files in the current directory.

Typical usage:
  Sample protonation states and stereoisomers, optimize geometry
  using OPLS force-field, and store results in Maestro format:

    ligprep <input> -omae outfile.maegz -epik

  where <input> is one of:
    -ismi infile.smi
    -icsv infile.csv
    -isd  infile.sd
    -imae infile.mae

In [ ]:
def prepare_ligands(ligand_in: Path, outdir: Path) -> Path: #  pH: float = 7.4, dpH: float = 1.0
    """
    LigPrep with Epik states; outputs a single MAEGZ of prepared ligands.
    Accepts SDF/MAE/SMILES (SMILES must be in a .smi or via -ismi).
    """
    ligprep = which("ligprep")
    out_mae = outdir / "ligprep_out.maegz"

    ligprep_inp = outdir / "ligprep.inp"

    ligprep_inp.write_text(f"""
INPUT_FILE_NAME   {str(ligand_in)}
MAX_ATOMS   500
FORCE_FIELD   16
EPIK   yes
EPIKX   no
EPIK_METAL_BINDING   no
INCLUDE_ORIGINAL_STATE   no
DETERMINE_CHIRALITIES   no
IGNORE_CHIRALITIES   yes
NUM_STEREOISOMERS   32
OUT_MAE   {out_mae}
    """)

    # Detect SMILES input by extension
    # is_smiles = ligand_in.suffix.lower() in [".smi", ".smiles", ".can"] # has to be .smi
    cmd = [ligprep, "-WAIT", "-inp", str(ligprep_inp)]
    # Epik-like states around target pH
    # cmd += ["-ph", f"{pH}", "-pht", f"{dpH}", "-s", "1"]  # 1 conformer per state (adjust as needed)
    run(cmd)
    return out_mae

## TEST

In [9]:
bioemuensdir = Path("bioemu_8uk6/msmclust/dihedrals")

In [12]:
bioemuensresults = pd.read_pickle(bioemuensdir / "predictions.pkl")
bioemuensresults

{'frame_0': {'pocket': 'pocket1',
  'overlap': 0.9047619047619048,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            GLY             A                 ?            A
  6            THR             A                 ?            A
  7            ILE             A                 ?            A
  8            MET             A                 ?            A
  9            LYS             A                 ?            A
  10           ILE             A                 ?            A
  11           TRP             A                 ?            A
  12           ARG             A                 ?            A
  13           LEU             A                 ?            A
  14           TYR             A                 ?            A
  15           THR             A                 ?            A
  16           GLN             A                 ?            A
  17           LEU             A                 ?            A
  18           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          GLY         279               1          280
  6                   1          THR         280               1          281
  7                   1          ILE         281               1          282
  8                   1          MET         282               1          283
  9                   1          LYS         284               1          285
  10                  1          ILE         287               1          288
  11                  1          TRP         299               1          300
  12                  1          ARG         303               1          304
  13                  1          LEU         304               1          305
  14                  1          TYR         305               1          306
  15                  1          THR         306               1          307
  16                  1          GLN         485               1          486
  17                  1          LEU         486               1          487
  18                  1          PHE         487               1          488  },
 'frame_1': {'pocket': 'pocket1',
  'overlap': 0.6190476190476191,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            THR             A                 ?            A
  6            ILE             A                 ?            A
  7            MET             A                 ?            A
  8            LYS             A                 ?            A
  9            ILE             A                 ?            A
  10           TRP             A                 ?            A
  11           TYR             A                 ?            A
  12           THR             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          THR         280               1          281
  6                   1          ILE         281               1          282
  7                   1          MET         282               1          283
  8                   1          LYS         284               1          285
  9                   1          ILE         287               1          288
  10                  1          TRP         299               1          300
  11                  1          TYR         305               1          306
  12                  1          THR         306               1          307  },
 'frame_2': {'pocket': 'pocket1',
  'overlap': 0.5238095238095238,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            THR             A                 ?            A
  6            ILE             A                 ?            A
  7            MET             A                 ?            A
  8            SER             A                 ?            A
  9            LYS             A                 ?            A
  10           PRO             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          THR         280               1          281
  6                   1          ILE         281               1          282
  7                   1          MET         282               1          283
  8                   1          SER         283               1          284
  9                   1          LYS         284               1          285
  10                  1          PRO         492               1          493  },
 'frame_3': {'pocket': 'pocket1',
  'overlap': 0.3333333333333333,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           GLY             A                 ?            A
  1           PHE             A                 ?            A
  2           LEU             A                 ?            A
  3           HIS             A                 ?            A
  4           HIS             A                 ?            A
  5           MET             A                 ?            A
  6           LYS             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          GLY          48               1           49
  1                  1          PHE          49               1           50
  2                  1          LEU          50               1           51
  3                  1          HIS          51               1           52
  4                  1          HIS          54               1           55
  5                  1          MET         282               1          283
  6                  1          LYS         284               1          285  },
 'frame_4': {'pocket': 'pocket6',
  'overlap': 0.2857142857142857,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           HIS             A                 ?            A
  1           HIS             A                 ?            A
  2           GLY             A                 ?            A
  3           THR             A                 ?            A
  4           MET             A                 ?            A
  5           PRO             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          HIS          51               1           52
  1                  1          HIS          54               1           55
  2                  1          GLY         279               1          280
  3                  1          THR         280               1          281
  4                  1          MET         282               1          283
  5                  1          PRO         492               1          493  },
 'frame_5': {'pocket': 'pocket2',
  'overlap': 0.5714285714285714,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            HIS             A                 ?            A
  1            GLY             A                 ?            A
  2            THR             A                 ?            A
  3            ILE             A                 ?            A
  4            ILE             A                 ?            A
  5            ARG             A                 ?            A
  6            LEU             A                 ?            A
  7            TYR             A                 ?            A
  8            THR             A                 ?            A
  9            GLN             A                 ?            A
  10           LEU             A                 ?            A
  11           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          HIS          51               1           52
  1                   1          GLY         279               1          280
  2                   1          THR         280               1          281
  3                   1          ILE         281               1          282
  4                   1          ILE         287               1          288
  5                   1          ARG         303               1          304
  6                   1          LEU         304               1          305
  7                   1          TYR         305               1          306
  8                   1          THR         306               1          307
  9                   1          GLN         485               1          486
  10                  1          LEU         486               1          487
  11                  1          PHE         487               1          488  },
 'frame_6': {'pocket': 'pocket3',
  'overlap': 0.2857142857142857,
  'merge':   label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0           GLY             A                 ?            A
  1           LEU             A                 ?            A
  2           HIS             A                 ?            A
  3           HIS             A                 ?            A
  4           MET             A                 ?            A
  5           LYS             A                 ?            A

    pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                  1          GLY          48               1           49
  1                  1          LEU          50               1           51
  2                  1          HIS          51               1           52
  3                  1          HIS          54               1           55
  4                  1          MET         282               1          283
  5                  1          LYS         284               1          285  },
 'frame_7': {'pocket': 'pocket1',
  'overlap': 0.9047619047619048,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            GLY             A                 ?            A
  6            THR             A                 ?            A
  7            ILE             A                 ?            A
  8            MET             A                 ?            A
  9            SER             A                 ?            A
  10           LYS             A                 ?            A
  11           ILE             A                 ?            A
  12           ARG             A                 ?            A
  13           LEU             A                 ?            A
  14           TYR             A                 ?            A
  15           THR             A                 ?            A
  16           GLN             A                 ?            A
  17           LEU             A                 ?            A
  18           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          GLY         279               1          280
  6                   1          THR         280               1          281
  7                   1          ILE         281               1          282
  8                   1          MET         282               1          283
  9                   1          SER         283               1          284
  10                  1          LYS         284               1          285
  11                  1          ILE         287               1          288
  12                  1          ARG         303               1          304
  13                  1          LEU         304               1          305
  14                  1          TYR         305               1          306
  15                  1          THR         306               1          307
  16                  1          GLN         485               1          486
  17                  1          LEU         486               1          487
  18                  1          PHE         487               1          488  },
 'frame_8': {'pocket': 'pocket1',
  'overlap': 1.0,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            GLY             A                 ?            A
  1            PHE             A                 ?            A
  2            LEU             A                 ?            A
  3            HIS             A                 ?            A
  4            HIS             A                 ?            A
  5            GLY             A                 ?            A
  6            THR             A                 ?            A
  7            ILE             A                 ?            A
  8            MET             A                 ?            A
  9            SER             A                 ?            A
  10           LYS             A                 ?            A
  11           ILE             A                 ?            A
  12           TRP             A                 ?            A
  13           ARG             A                 ?            A
  14           LEU             A                 ?            A
  15           TYR             A                 ?            A
  16           THR             A                 ?            A
  17           GLN             A                 ?            A
  18           LEU             A                 ?            A
  19           PHE             A                 ?            A
  20           PRO             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          GLY          48               1           49
  1                   1          PHE          49               1           50
  2                   1          LEU          50               1           51
  3                   1          HIS          51               1           52
  4                   1          HIS          54               1           55
  5                   1          GLY         279               1          280
  6                   1          THR         280               1          281
  7                   1          ILE         281               1          282
  8                   1          MET         282               1          283
  9                   1          SER         283               1          284
  10                  1          LYS         284               1          285
  11                  1          ILE         287               1          288
  12                  1          TRP         299               1          300
  13                  1          ARG         303               1          304
  14                  1          LEU         304               1          305
  15                  1          TYR         305               1          306
  16                  1          THR         306               1          307
  17                  1          GLN         485               1          486
  18                  1          LEU         486               1          487
  19                  1          PHE         487               1          488
  20                  1          PRO         492               1          493  },
 'frame_9': {'pocket': 'pocket2',
  'overlap': 0.6190476190476191,
  'merge':    label_comp_id label_asym_id pdbx_PDB_ins_code auth_asym_id  \
  0            HIS             A                 ?            A
  1            GLY             A                 ?            A
  2            THR             A                 ?            A
  3            ILE             A                 ?            A
  4            MET             A                 ?            A
  5            ILE             A                 ?            A
  6            ARG             A                 ?            A
  7            LEU             A                 ?            A
  8            TYR             A                 ?            A
  9            THR             A                 ?            A
  10           GLN             A                 ?            A
  11           LEU             A                 ?            A
  12           PHE             A                 ?            A

     pdbx_PDB_model_num auth_comp_id auth_seq_id label_entity_id label_seq_id
  0                   1          HIS          51               1           52
  1                   1          GLY         279               1          280
  2                   1          THR         280               1          281
  3                   1          ILE         281               1          282
  4                   1          MET         282               1          283
  5                   1          ILE         287               1          288
  6                   1          ARG         303               1          304
  7                   1          LEU         304               1          305
  8                   1          TYR         305               1          306
  9                   1          THR         306               1          307

In [29]:
outdir = Path("glide/8uk6_prep")
outdir.mkdir(exist_ok=True)

for fn, f in [("8uk6", "dldocking/diffdock-pocket/8uk6/8uk6.pdb")] + [(frame, f"dldocking/diffdock-pocket/8uk6/{frame}.pdb") for frame in bioemuensresults]:
    prepare_protein(Path(f), out=fn, cwd=outdir)

In [33]:
seqsf = f"cofolding/seqs.pkl"

seqs = pd.read_pickle(seqsf)

In [43]:
outdir = Path("glide")

smi = outdir / "xglide.smi"
smi.write_text(seqs["8uk6"]["smiles"])

xglide_inp = outdir / "xglide.inp"

xglide_inp.write_text(f"""
RECEPTOR	{'8uk6_prep'}
ALIGN	FALSE
LIGAND	{smi.name}
GRIDGEN_GRID_CENTER	SELF
SITEMAP	TRUE
SITEMAP_MAXSITES    5
GRIDGEN_INNERBOX	10
GRIDGEN_OUTERBOX	26.0
LIGPREP	TRUE
LIGPREP_EPIK	TRUE
DOCK_PRECISION	SP
DOCK_WRITE_XP_DESC	FALSE
DOCK_POSE_OUTTYPE	poseviewer
NATIVEONLY	FALSE
DOCK_LIG_VSCALE	0.80
SKIP_DOCKING	FALSE
GOOD_RMSD	2.0
GENERATE_TOP_COMPLEXES	5
    """)

355

In [45]:
run(
    " ".join((
        SCHRO + "/run xglide.py",
        xglide_inp.name,
        "-WAIT -HOST localhost:1 -NJOBS 16 -TMPLAUNCHDIR"
    )),
    cwd=Path("glide"), 
    shell=True
)

[CMD] /opt/schrodinger2025-2/run xglide.py xglide.inp -WAIT -HOST localhost:1 -NJOBS 16 -TMPLAUNCHDIR
JobId: avogadro-0-68d6cd73

In [50]:
import re

In [55]:
# change to your .maegz
outdir = Path("glide/pdbs"); outdir.mkdir(exist_ok=True)
with sstruct.StructureReader("glide/xglide_topcomplexes.maegz") as r:
    for i, st in enumerate(r, 1):
        title = re.sub(r"[^\w\-]+","_", st.title)[:30] if st.title else f"pose{i}"
        # score = st.property.get("r_i_docking_score") or st.property.get("r_glide_gscore")
        grid = st.property.get("s_i_glide_gridfile", "") # 'xglide__frame_3_prep_site1__grid'
        frame, site = re.search(r"xglide__([^_]+(?:_\d+)?)_prep_(site\d+)", grid).groups()
        fname = f"{'8uk6'}_{frame}_pose{i}_{site}"
        # if score is not None: fname += f"_score_{float(score):+.2f}"
        with sstruct.StructureWriter(str(outdir/f"{fname}.pdb")) as w: w.append(st)

'xglide__8uk6_prep_site5__grid'

In [46]:
test = sstruct.MaestroReader("glide/xglide_topcomplexes.maegz")
test

In [48]:
test = test.read()
test

Structure(2)

In [ ]:
test.

In [ ]:
test.

In [31]:
SCHRO / "a"

TypeError: unsupported operand type(s) for /: 'str' and 'str'

## Glide

In [ ]:
def write_glide_dock_in(
    dock_in: Path,
    grid_zip: Path,
    lig_mae: Path,
    precision: str = "HTVS",
    nposes: int = 5
) -> None:
    """
    precision: HTVS | SP | XP
    """
    precision = precision.upper()
    if precision not in {"HTVS", "SP", "XP"}:
        raise ValueError("precision must be one of: HTVS, SP, XP")

    contents = f"""DOCKING
GRIDFILE {grid_zip}
LIGANDFILE {lig_mae}
PRECISION {precision}
POSES_PER_LIG {nposes}
WRITE_XP_DESC 1
NREPORT 25
"""
    dock_in.write_text(contents)


def dock(grid_zip: Path, lig_mae: Path, outdir: Path, precision: str) -> Path:
    glide = which("glide")
    jobname = f"dock_{grid_zip.stem}"
    dock_in = outdir / f"{jobname}.in"
    write_glide_dock_in(dock_in, grid_zip, lig_mae, precision=precision, nposes=5)
    run([glide, "-WAIT", str(dock_in)])
    out_mae = outdir / f"{jobname}_pv.maegz"
    if not out_mae.exists():
        # Some versions write <jobname>_lib.maegz or _raw.maegz; collect any *_pv.maegz fallback
        candidates = list(outdir.glob(f"{jobname}*_pv.mae*"))
        if candidates:
            return candidates[0]
        raise RuntimeError(f"Docking output not found for {grid_zip}")
    return out_mae


def pick_top_pose_from_mae(mae_file: Path, out_pose: Path) -> bool:
    """
    Copy best-scoring pose (first structure) into out_pose (MAE).
    """
    if sstruct is None:
        print("[WARN] schrodinger.structure not available; skipping top-pose extraction.")
        return False
    sts = list(sstruct.StructureReader(str(mae_file)))
    if not sts:
        return False
    with sstruct.StructureWriter(str(out_pose)) as w:
        w.append(sts[0])
    return True


def merge_best_poses(pose_files: List[Path], merged_out: Path) -> None:
    if sstruct is None:
        # fallback: concatenate binary files is not safe; skip
        print("[WARN] schrodinger.structure not available; skipping merged poses.")
        return
    with sstruct.StructureWriter(str(merged_out)) as w:
        for pf in pose_files:
            try:
                sts = list(sstruct.StructureReader(str(pf)))
                if sts:
                    w.append(sts[0])
            except Exception:
                pass


def main():
    ap = argparse.ArgumentParser(description="Blind docking with Glide via SiteMap pockets.")
    ap.add_argument("--receptor", required=True, help="Protein structure (PDB/MAE).")
    ap.add_argument("--ligand", required=True, help="Ligand file (SDF/MAE/SMI).")
    ap.add_argument("--outdir", required=True, help="Output directory.")
    ap.add_argument("--num_sites", type=int, default=5, help="Number of SiteMap sites to use.")
    ap.add_argument("--inner", type=float, default=14.0, help="Glide inner box (Å).")
    ap.add_argument("--outer", type=float, default=30.0, help="Glide outer box (Å).")
    ap.add_argument("--precision", default="HTVS", choices=["HTVS", "SP", "XP"], help="Docking precision.")
    ap.add_argument("--ph", type=float, default=7.4, help="LigPrep target pH.")
    ap.add_argument("--dph", type=float, default=1.0, help="LigPrep pH tolerance (±).")
    args = ap.parse_args()

    outdir = Path(args.outdir).absolute()
    ensure_outdir(outdir)

    receptor_in = Path(args.receptor).absolute()
    ligand_in = Path(args.ligand).absolute()

    # 1) Prepare protein
    receptor_prep = prepare_protein(receptor_in, outdir)

    # 2) SiteMap
    sm_base = run_sitemap(receptor_prep, outdir, args.num_sites)
    centers = collect_site_centers(sm_base)
    if not centers:
        print("[ERROR] No site centers found by SiteMap. Consider increasing --num_sites or adjusting --sitebox.", file=sys.stderr)
        sys.exit(1)

    centers = centers[: args.num_sites]
    print(f"[INFO] Using {len(centers)} site centers for grid generation.")

    # 3) Build grids
    grid_zips: List[Path] = []
    grids_dir = outdir / "grids"
    grids_dir.mkdir(exist_ok=True)
    for i, c in enumerate(centers, 1):
        grid_in = grids_dir / f"grid_site{i}.in"
        write_glide_grid_in(grid_in, receptor_prep, c, args.inner, args.outer)
        gz = build_grid(grid_in)
        grid_zips.append(gz)

    # 4) Ligand prep
    lig_mae = prepare_ligands(ligand_in, outdir, pH=args.ph, dpH=args.dph)

    # 5) Dock per grid
    poses_dir = outdir / "poses"
    poses_dir.mkdir(exist_ok=True)
    best_pose_files: List[Path] = []
    for gz in grid_zips:
        dock_out = dock(gz, lig_mae, poses_dir, args.precision)
        top_pose = poses_dir / f"best_{gz.stem}.mae"
        ok = pick_top_pose_from_mae(dock_out, top_pose)
        if ok:
            best_pose_files.append(top_pose)
        else:
            # If picking failed, still keep the full pv file in the merged set
            best_pose_files.append(dock_out)

    # 6) Merge best poses
    merged = outdir / "best_poses_all_sites.mae"
    merge_best_poses(best_pose_files, merged)

    print("\n[DONE]")
    print(f"Prepared receptor: {receptor_prep}")
    print(f"Site centers used: {len(centers)}")
    print(f"Grids: {len(grid_zips)} → {grids_dir}")
    print(f"Ligands (LigPrep): {lig_mae}")
    print(f"Docking outputs: {poses_dir}")
    if merged.exists():
        print(f"Merged best poses: {merged}")
    else:
        print("Merged best poses skipped (missing schrodinger.structure).")


if __name__ == "__main__":
    main()