In [27]:
import os, sys, shutil
import pandas as pd
from tqdm.notebook import tqdm

In [2]:
sys.path.append("../training_data")

In [3]:
from utils.new_pdbs import Cif, Pdb

# ATLAS data

Assuming that the chain in MDAtlas is the `auth_asym_id`.

In [4]:
with open("2023_03_09_ATLAS_pdb.txt", "r") as f:
    mdatlas = f.read().split("\n")[:-1]

mdatlas, mdatlas[-1]

(['1r6w_A',
  '2y44_A',
  '1ux6_A',
  '1jnr_C',
  '3mx7_A',
  '1u55_A',
  '3k59_A',
  '3owt_A',
  '4zds_A',
  '3st1_A',
  '3mmh_B',
  '4obi_A',
  '4ojl_C',
  '2ie6_A',
  '3frr_A',
  '5dje_A',
  '3rt4_A',
  '3lui_B',
  '4ftf_A',
  '3nqi_A',
  '1qau_A',
  '8b3w_A',
  '1xsz_A',
  '4g94_B',
  '7n0j_A',
  '4exo_A',
  '1h16_A',
  '3e4w_B',
  '2fb5_B',
  '1ng6_A',
  '3kz7_A',
  '2p3p_A',
  '7w81_B',
  '1tuk_A',
  '5noh_B',
  '2qmj_A',
  '6exa_B',
  '3kef_B',
  '6l34_A',
  '1cvr_A',
  '5wfy_A',
  '4k2m_A',
  '3iis_M',
  '1fs1_C',
  '1c1k_A',
  '6xrx_A',
  '1wlg_A',
  '4qtq_A',
  '1l5o_A',
  '5j2l_B',
  '6in7_A',
  '3e2d_A',
  '3a3d_B',
  '1huf_A',
  '1wf3_A',
  '2hq4_B',
  '3dso_A',
  '1n7z_B',
  '1ugp_B',
  '4cjn_A',
  '2bmo_B',
  '2h2z_A',
  '1eb0_A',
  '7r79_B',
  '1r5l_A',
  '5njb_B',
  '5m45_K',
  '2o7o_A',
  '1v9m_A',
  '1l2w_J',
  '2vri_A',
  '2q9r_A',
  '2bf6_A',
  '7mi2_A',
  '2jhq_A',
  '1lr0_A',
  '2a6s_B',
  '1zw0_G',
  '4tsh_A',
  '7nru_A',
  '2qsk_A',
  '5wvo_C',
  '3a6d_F',
  '1r8m_E',
  '2cxi_B',
  '2zfz_D',
  '2db7_B',
  '2eo4_A',
  '3a1g_B',
  '3dnh_B',
  '2nuk_A',
  '4zds_B',
  '3jsz_A',
  '1j77_A',
  '4q7o_B',
  '4myy_A',
  '2ozl_A',
  '3f4m_A',
  '6dgk_B',
  '3pkz_A',
  '5ftw_A',
  '4b2f_A',
  '6tgk_C',
  '2pu3_A',
  '5b5i_B',
  '1n7z_A',
  '4ics_A',
  '1ojh_C',
  '2jc5_A',
  '2v05_A',
  '5imu_A',
  '3o0g_D',
  '3ohg_A',
  '5ggl_A',
  '2gib_A',
  '3fm2_A',
  '6sup_A',
  '2xeu_A',
  '3f7w_A',
  '7ned_A',
  '4e1p_B',
  '4zmk_A',
  '3wvz_B',
  '3pkz_B',
  '5kdw_B',
  '2qsa_A',
  '4m0q_B',
  '6pnv_A',
  '4y7s_B',
  '4koq_A',
  '5t2p_D',
  '1w2w_E',
  '2pef_A',
  '2xu8_B',
  '3k29_A',
  '1vbw_A',
  '1tzv_A',
  '4rgi_A',
  '2qq4_B',
  '2qqc_D',
  '4rr9_A',
  '1g38_D',
  '1sx3_A',
  '1jyo_F',
  '2z5e_B',
  '3gkj_A',
  '7s94_C',
  '2gs5_A',
  '7mfu_A',
  '4h9q_C',
  '2pv4_A',
  '2hqk_A',
  '1uz3_B',
  '2vmc_A',
  '1k5n_A',
  '3kd4_B',
  '1wpb_L',
  '4jgi_B',
  '2b0t_A',
  '1qdd_A',
  '4m37_A',
  '1chd_A',
  '2foz_A',
  '3x0g_A',
  '3e8t_A',
  '3do6_A',
  '2fzp_A',
  '4fhr_B',
  '3ol3_A',
  '3o6p_A',
  '5exe_C',
  '1xeo_A',
  '6y43_A',
  '4bgp_A',
  '1ocy_A',
  '7mf4_A',
  '1xta_A',
  '2ox7_B',
  '2icu_A',
  '3ipj_A',
  '2gkr_I',
  '5iff_B',
  '4psf_B',
  '1ssq_D',
  '1o0s_A',
  '4oa3_A',
  '1m7v_A',
  '2yp8_A',
  '1y6i_A',
  '3ka5_A',
  '3g5k_D',
  '2x8w_A',
  '3ofg_A',
  '3zl8_A',
  '1svb_A',
  '5ol4_A',
  '3ipf_B',
  '2vzc_A',
  '1md6_A',
  '1hc9_B',
  '6pce_A',
  '2py5_A',
  '1oh9_A',
  '5bs1_B',
  '5btz_A',
  '3emi_A',
  '3npd_A',
  '3m7a_A',
  '5erq_A',
  '1d4t_A',
  '2pbi_C',
  '2vac_A',
  '1q7e_A',
  '6p5h_A',
  '6h86_A',
  '3mqz_A',
  '1x6i_A',
  '3rzn_A',
  '6yud_B',
  '3hvv_A',
  '2r2d_A',
  '5o9e_A',
  '2xse_A',
  '1pp0_C',
  '2oxl_B',
  '5en2_C',
  '4jo7_C',
  '4ytw_C',
  '3eqx_A',
  '5ok6_A',
  '2gwm_A',
  '2cg7_A',
  '3vth_A',
  '1jmx_G',
  '5b3p_A',
  '5x1e_D',
  '1o1x_A',
  '4fch_B',
  '6jwh_A',
  '3k5j_A',
  '2vm5_A',
  '1f3u_G',
  '4rp5_A',
  '7jrq_A',
  '1vzy_B',
  '6uxe_B',
  '3d7a_B',
  '2arz_A',
  '2vh3_A',
  '6tly_A',
  '5h6x_A',
  '3lgb_B',
  '4u9b_A',
  '5y4z_A',
  '2x63_A',
  '3lpe_B',
  '7bhc_A',
  '7adr_C',
  '3e7h_A',
  '3ig9_B',
  '5muy_A',
  '3wx4_A',
  '1ptq_A',
  '1n2m_A',
  '4bt9_B',
  '2xf2_A',
  '4n67_A',
  '1fx4_A',
  '4erv_A',
  '3cjs_C',
  '1vaj_A',
  '7qsu_A',
  '2rdi_A',
  '2w9y_A',
  '2dt8_A',
  '3bpj_C',
  '3ii2_A',
  '7ubk_B',
  '3klr_A',
  '6mdw_A',
  '4p5a_B',
  '2xf5_B',
  '1yu5_X',
  '1m8s_A',
  '1sx3_B',
  '7qgs_A',
  '6qgr_B',
  '5i8j_A',
  '2wfp_A',
  '3dha_A',
  '4gip_B',
  '1rl6_A',
  '2qdx_A',
  '3luu_A',
  '1ze3_D',
  '3tdt_A',
  '1rpo_A',
  '4jja_A',
  '1t9i_B',
  '2v0u_A',
  '4gsj_A',
  '4geh_C',
  '3bec_A',
  '6bk4_A',
  '2b9d_A',
  '3zdm_A',
  '4qxo_A',
  '1wq8_A',
  '6c0h_A',
  '2gc4_B',
  '2f6e_A',
  '4bt9_A',
  '5w53_A',
  '1b2s_F',
  '3fgh_A',
  '1v2z_A',
  '1ab1_A',
  '2zwd_A',
  '4xo2_A',
  '2z4u_A',
  '4na5_A',
  '1hoe_A',
  '7rsa_A',
  '2xrh_A',
  '2x9o_A',
  '1pcf_C',
  '4z8t_B',
  '1fm4_A',
  '4xdu_A',
  '3ov5_A',
  '1s2o_A',
  '1cpq_A',
  '4z8q_B',
  '3imk_A',
  '3crv_A',
  '4qaz_A',
  '2ycl_A',
  '5ltj_A',
  '2pyq_B',
  '7w81_A',
  '2ed6_A',
  '1jo0_A',
  '7s58_D',
  '2vkp_B',
  '2wbf_X',
  '3zoq_B',
  '2e5y_B',
  '6wqd_B',
  '2cwy_A',
  '1nh2_B',
  '2ia1_B',
  '1lsl_A',
  '2au7_A',
  '4ndt_A',
  '4mmj_A',
  '5ef9_A',
  '3nke_B',
  '1uwk_B',
  '3las_B',
  '7nmq_A',
  '2oy9_B',
  '3im3_A',
  '2ia1_A',
  '1thm_A',
  '1lwb_A',
  '3mxz_A',
  '5dmu_A',
  '1zjc_A',
  '1o75_A',
  '4zqv_A',
  '6nl2_A',
  '6a02_A',
  '2waw_A',
  '2wzb_A',
  '2hxm_A',
  '3u9g_A',
  '3w1o_A',
  '1vk1_A',
  '6tj6_C',
  '1h99_A',
  '1v7z_F',
  '1yqw_B',
  '8bnt_B',
  '3dff_A',
  '3enu_A',
  '1llf_B',
  '3lbl_A',
  '5l0s_A',
  '1q0q_A',
  '5kts_A',
  '1ojh_D',
  '2au3_A',
  '2h7g_X',
  '1vyi_A',
  '2po4_A',
  '2v27_A',
  '2bw3_B',
  '6fc0_B',
  '2e7u_A',
  '3fbl_A',
  '3eh1_A',
  '3wp8_A',
  '4k05_B',
  '2fip_A',
  '4zce_B',
  '2vh3_B',
  '5x0b_A',
  '4o87_A',
  '5uc0_A',
  '1o98_A',
  '3a1u_A',
  '3tee_A',
  '4epi_A',
  '1l9l_A',
  '6qj0_A',
  '3lq9_A',
  '6l4p_B',
  '2fe5_A',
  '1f5n_A',
  '7jfl_D',
  '6cb7_A',
  '3zr8_X',
  '5b1n_A',
  '4ead_A',
  '2hnu_B',
  '3gmv_X',
  '2it2_B',
  '5xbc_B',
  '3vhj_A',
  '3a1g_D',
  '4geh_A',
  '1xmk_A',
  '5x1e_A',
  '4lur_A',
  '3zfn_A',
  '7la6_A',
  '3ti2_A',
  '1qlm_A',
  '4mb5_A',
  '4omf_B',
  '2o70_F',
  '6pxz_B',
  '1g81_A',
  '3bjd_B',
  '2zd2_B',
  '1ve0_A',
  '6rwt_A',
  '3sws_E',
  '3mm6_A',
  '3ilw_A',
  '6vr8_I',
  '2qcu_B',
  '1gqe_A',
  '1p5g_X',
  '4fbs_A',
  '2ccq_A',
  '3omd_B',
  '1xg0_A',
  '1q8f_A',
  '1utg_A',
  '3pf6_A',
  '2xc1_B',
  '1ifg_A',
  '5xct_B',
  '1fn9_B',
  '1mk0_A',
  '2fef_A',
  '2yjg_A',
  '7snb_A',
  '3ijw_A',
  '4ehx_A',
  '2jdd_A',
  '1zd7_B',
  '3qc7_A',
  '1ka1_A',
  '3ig9_C',
  '1h8e_G',
  '4wlr_B',
  '4lzh_A',
  '1tg7_A',
  '4n7w_B',
  '2y1y_A',
  '3iiu_M',
  '3zzo_A',
  '3l51_B',
  '1yoc_B',
  '3gnu_P',
  '4v4e_M',
  '3fpn_A',
  '3pt1_A',
  '6vg5_A',
  '3obl_B',
  '3fh2_A',
  '1ugp_A',
  '4h4n_A',
  '4j8c_B',
  '3zzr_A',
  '1xvg_E',
  '5opm_A',
  '2vg3_C',
  '6eu8_A',
  '6e5y_A',
  '4j8c_A',
  '4p3x_A',
  '1koe_A',
  '2ygs_A',
  '3hlz_A',
  '3bqp_B',
  '5eqz_A',
  '1yoz_A',
  '5jfc_L',
  '1xhk_B',
  '3b4q_A',
  '5fia_B',
  '3qfl_A',
  '5jbg_A',
  '3vc8_A',
  '3ld7_B',
  '2o74_F',
  '2c9i_D',
  '3jsy_A',
  '3qc5_X',
  '5ygh_A',
  '2ex2_A',
  '2oqz_A',
  '2hyv_A',
  '2ad6_A',
  '4kct_B',
  '3ouf_B',
  '4ued_B',
  '5bnh_A',
  '4ew5_B',
  '3m6z_A',
  '3qra_A',
  '3u5v_A',
  '2fi9_A',
  '3mfd_A',
  '3msw_A',
  '3h8t_A',
  '1ijx_C',
  '6wzw_A',
  '1qz4_A',
  '3ldu_A',
  '4qx8_C',
  '3q1c_A',
  '6spt_A',
  '2dlb_A',
  '16pk_A',
  '1bgf_A',
  '3whj_A',
  '1xkr_A',
  '1fxo_G',
  '7c45_A',
  '1bxy_B',
  '2wcu_A',
  '6ao8_A',
  '1yib_A',
  '1yu2_A',
  '2i6d_A',
  '6sms_A',
  '4n7w_A',
  '4z3x_A',
  '6iah_A',
  '2igp_A',
  '1g7t_A',
  '1z0b_A',
  '4qlp_A',
  '1z2u_A',
  '3ajf_A',
  '4lim_A',
  '6ne6_A',
  '1g2r_A',
  '3h1w_A',
  '1kp3_A',
  '7zou_A',
  '2fhz_A',
  '2bln_B',
  '4bcl_A',
  '1hbn_E',
  '6gfx_C',
  '3kde_C',
  '3tkk_A',
  '1skz_A',
  '3nrw_A',
  '1wui_S',
  '4o7j_B',
  '1dvo_A',
  '1pch_A',
  '3ono_A',
  '1mjf_B',
  '1h17_A',
  '3dza_A',
  '3pvh_A',
  '4xb6_H',
  '2uxy_A',
  '2oez_A',
  '1ef1_C',
  '3fpu_A',
  '2hu9_A',
  '4cv4_A',
  '7aqx_A',
  '3kd4_A',
  '3dau_A',
  '2vnl_A',
  '5wbx_B',
  '2ot9_A',
  '6gus_A',
  '2pst_X',
  '6q10_A',
  '1r0k_A',
  '5a0n_A',
  '2cx7_A',
  '5ngd_B',
  '1egw_B',
  '5klh_A',
  '7n0j_E',
  '2y3w_B',
  '5hqh_A',
  '1n8v_B',
  '2e6x_A',
  '4ubp_C',
  '5lc8_A',
  '3gs9_A',
  '6qfk_A',
  '3nis_B',
  '5e5y_C',
  '7mq3_A',
  '2rci_A',
  '4mzv_A',
  '1gpj_A',
  '5m1m_A',
  '6as3_B',
  '6p5h_B',
  '2pnw_A',
  '3hht_A',
  '3a1g_A',
  '3agn_A',
  '1g7s_A',
  '3eoj_A',
  '1j8e_A',
  '2wfr_A',
  '4p5a_A',
  '1v7r_A',
  '2jft_A',
  '7t9q_A',
  '6o2v_B',
  '1iuq_A',
  '4gv2_A',
  '3dpg_B',
  '4b6i_D',
  '1wq6_A',
  '3i94_A',
  '2q2g_A',
  '2ovj_A',
  '1tez_B',
  '2db7_A',
  '1u8v_C',
  '3kbb_A',
  '2at8_X',
  '3gwi_A',
  '5cfl_A',
  '3ju4_A',
  '2qud_A',
  '3c05_A',
  '3v3l_A',
  '6jim_B',
  '2y1q_A',
  '1wq6_B',
  '6fub_B',
  '3k6q_B',
  '2yvo_A',
  '2nwv_A',
  '2ysk_A',
  '7dmn_A',
  '5yrv_I',
  '1uoy_A',
  '1pby_C',
  '2xdg_A',
  '2ofz_A',
  '2qcu_A',
  '1qxo_B',
  '4q6v_A',
  '1c96_A',
  '3mil_A',
  '1rqj_A',
  '1fk5_A',
  '4cbe_A',
  '3fke_A',
  '2gke_A',
  '2xjq_A',
  '2z0j_E',
  '3rv1_B',
  '3i57_B',
  '4ywk_A',
  '6o2v_A',
  '5klh_B',
  '3cyi_A',
  '4f87_A',
  '3txs_C',
  '1qcs_A',
  '4iaj_B',
  '3a7l_A',
  '4ljo_A',
  '2w39_A',
  '2dtr_A',
  '7wab_A',
  '6mbg_A',
  '1hw1_B',
  '7z1k_A',
  '1m5q_Z',
  '2x96_A',
  '6fsw_A',
  '3let_B',
  '4ke2_B',
  '1ls1_A',
  '2w0g_A',
  '3vjz_A',
  '3mwz_A',
  '4kk7_A',
  '1fd3_A',
  '4zya_A',
  '3a0y_B',
  '6pce_B',
  '4oe9_A',
  '2j6c_A',
  '5w4a_B',
  '1s9r_A',
  '1h02_B',
  '1bq8_A',
  '1mix_A',
  '3dai_A',
  '1wqj_B',
  '4v23_A',
  '2gib_B',
  '4peg_C',
  '4jnu_B',
  '4dol_A',
  '2hy5_A',
  '5b6c_A',
  '2qt4_A',
  '3sfv_B',
  '7asg_A',
  '2bk9_A',
  '3c8w_C',
  '7p46_A',
  '1qb7_A',
  '5kko_D',
  '2imf_A',
  '2pu9_A',
  '2p12_B',
  '1j8r_A',
  '4oe9_B',
  '2zca_B',
  '2fj8_A',
  '4lty_A',
  '5b42_A',
  '5w82_B',
  '2g9e_A',
  '3da8_A',
  '2xpp_A',
  '5hkx_A',
  '2ixm_A',
  '3hlz_B',
  '4jmu_A',
  '5h7w_B',
  '3wol_A',
  '3lyy_A',
  '5naz_A',
  '3l51_A',
  '4zav_A',
  '4ok9_A',
  '5kko_C',
  '7s6q_C',
  '3nci_A',
  '5mux_B',
  '3ni2_A',
  '3e9v_A',
  '1i2t_A',
  '2wqi_D',
  '1doi_A',
  '1bkp_A',
  '1gte_D',
  '3hxw_A',
  '4hkd_B',
  '3d3y_A',
  '6w6x_A',
  '5h1n_A',
  '1wna_A',
  '2wzg_A',
  '4xb6_D',
  '3ktp_A',
  '1rss_A',
  '1jhs_A',
  '1ez3_B',
  '4pfx_A',
  '1u09_A',
  '3kz5_E',
  '6dgk_A',
  '1o4k_A',
  '4ezi_A',
  '3fn2_B',
  '6i0i_A',
  '1u6r_B',
  '2jek_A',
  '4hfv_A',
  '1upt_B',
  '1ikp_A',
  '7dif_A',
  '5lpa_B',
  '2dt4_A',
  '3g5t_A',
  '3pzw_A',
  '3zoq_C',
  '2hu9_B',
  '3zrg_B',
  '1yqe_A',
  '4dok_A',
  '2znr_A',
  '4jo7_A',
  '4goq_B',
  '7z4m_A',
  '3fkc_A',
  '4tkx_L',
  '2ogb_B',
  '2fos_A',
  '2jhf_B',
  '2xm5_A',
  '5mdu_A',
  '3kby_B',
  '1wx1_B',
  '2pcn_A',
  '6atg_C',
  '1zht_A',
  '3it4_B',
  '2dka_A',
  '2fyg_A',
  '5kvk_A',
  '2w56_A',
  '2gg6_A',
  '3c1q_B',
  '2qtd_A',
  '3bl9_B',
  '2cxi_A',
  '4fqn_B',
  '1io1_A',
  '1ail_A',
  '2bo1_A',
  '6okd_C',
  '2o4t_A',
  '1r9f_A',
  '1k7j_A',
  '2w8x_A',
  '3wwh_A',
  '5j3t_B',
  '2igi_A',
  '2y7b_A',
  '2x5r_A',
  '3hmr_A',
  '3n8u_A',
  '4m0q_A',
  '2ftx_A',
  '6xb3_H',
  '2fb6_A',
  '3eye_A',
  '4j32_B',
  '2dlb_B',
  '5txr_B',
  '1v4p_C',
  '1mv8_C',
  '2rkv_A',
  '2eq8_C',
  '4jgn_A',
  '3mol_B',
  '2e7z_A',
  '4v1g_B',
  '3bwu_D',
  '1u07_A',
  '4o6q_A',
  '3kvd_D',
  '3glx_A',
  '1wpb_A',
  '1g38_A',
  '3bl9_A',
  '6jfk_A',
  '3wvz_A',
  '2w6k_A',
  '1ctf_A',
  '7n51_A',
  '2xmx_A',
  '2wny_B',
  '1njh_A',
  '7fd1_A',
  '7zh9_A',
  '1jq5_A',
  '4wt3_A',
  '1dwk_A',
  '1k8k_E',
  '1f20_A',
  '2o6x_A',
  '6l8s_A',
  '2x5g_A',
  '1m15_A',
  '5n76_F',
  '5yrt_C',
  '3sol_A',
  '1msc_A',
  '2cfm_A',
  '4wwr_F',
  '4iu3_B',
  '7rm7_A',
  '2i9x_B',
  '3hol_A',
  '2bti_A',
  '4e5r_A',
  '5l87_A',
  '6q9c_B',
  '3im1_A',
  '3jub_A',
  '3po8_A',
  '2inc_A',
  '2vcc_A',
  '3vgp_A',
  '2vrs_C',
  '3djl_A',
  '6bm5_A',
  '7m8h_A',
  '2gec_A',
  '2prv_A',
  '2wya_A',
  '1b0n_A',
  '4s39_A',
  '2wn3_C',
  '1aol_A',
  '4hwx_A',
  '2hnu_A',
  '2qjz_A',
  '6h49_A',
  '7p46_B',
  '1n8u_A',
  '4q0y_B',
  '2pyq_C',
  '1oao_C',
  '7uw7_A',
  '7ubj_A',
  '5w5c_A',
  '4r7q_A',
  '5vz0_B',
  '1nl1_A',
  '4ct7_A',
  '5w82_E',
  '1qwz_A',
  '2wnp_F',
  '3lk7_A',
  '5oh5_A',
  '3l9a_X',
  '4jgi_A',
  '3b9q_A',
  '5gof_A',
  '3fp5_A',
  '6okd_D',
  '5cyz_C',
  '3q1n_A',
  '5bmt_B',
  '3mcb_A',
  '7z27_A',
  '3oxp_A',
  '3lyw_A',
  '5e3e_E',
  '5wqq_A',
  '6b6m_A',
  '6l3r_E',
  '1zpe_A',
  '1ewf_A',
  '3tbn_A',
  '3vu0_B',
  '5vz0_A',
  '1yoz_B',
  '4cfi_A',
  '8b2r_B',
  '3h1d_A',
  '4lty_D',
  '1lj5_A',
  '6f45_D',
  '1m9z_A',
  '2qev_A',
  '1ig3_A',
  '1j09_A',
  '3jtz_A',
  '2onf_B',
  '3vej_B',
  '1krn_A',
  '2hl7_A',
  '3lvu_D',
  '3g28_A',
  '2bbr_A',
  '1z1l_A',
  '4za9_A',
  '2rji_A',
  '5udz_A',
  '1nf8_A',
  ...],
 '5exh_C')

# Extra test set

In [5]:
features = pd.read_pickle("../training_data/7.Extra_set/features.pkl")
print(len(features))
features

9

{'7gqu':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       7gqu               1             A           12            A
 1       7gqu               1             A           13            A
 2       7gqu               1             A           14            A
 3       7gqu               1             A           15            A
 4       7gqu               1             A           16            A
 ..       ...             ...           ...          ...          ...
 414     7gqu               1             A          426            A
 415     7gqu               1             A          427            A
 416     7gqu               1             A          428            A
 417     7gqu               1             A          429            A
 418     7gqu               1             A          430            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0           527                 ?     0               0               0  ...
 1           528                 ?     0               0               0  ...
 2           529                 ?     0               0               0  ...
 3           530                 ?     0               0               0  ...
 4           531                 ?     0               1               0  ...
 ..          ...               ...   ...             ...             ...  ...
 414         941                 ?     0               0               0  ...
 415         942                 ?     0               0               0  ...
 416         943                 ?     0               0               0  ...
 417         944                 ?     0               0               0  ...
 418         945                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.992404  0.000000  0.007872  0.000000  0.000000  0.000000  0.000000
 1    0.970634  0.000000  0.029688  0.000000  0.000000  0.000000  1.000000
 2    0.984184  0.016020  0.000000  0.317098  0.683020  0.677362  0.322641
 3    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
 4    0.983502  0.008717  0.007775  0.564091  0.435879  0.515842  0.483974
 ..        ...       ...       ...       ...       ...       ...       ...
 414  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 415  0.995850  0.004349  0.000000  1.000000  0.000000  0.000000  0.000000
 416  0.995160  0.000000  0.004849  0.000000  0.000000  0.000000  0.000000
 417  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 418  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


        Neff Neff_I Neff_D
 0    11.507  0.000  0.000
 1    11.647  0.000  1.004
 2    11.184  1.054  1.083
 3    11.324  0.000  1.019
 4    11.412  1.024  1.019
 ..      ...    ...    ...
 414  11.186  0.000  1.038
 415  10.451  1.004  0.000
 416  10.892  0.000  0.000
 417  11.436  0.000  1.004
 418  10.967  0.000  0.000

 [419 rows x 174 columns],
 '7yg5':      Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0        7yg5               1             A           76            A
 1        7yg5               1             A           77            A
 2        7yg5               1             A           78            A
 3        7yg5               1             A           79            A
 4        7yg5               1             A           80            A
 ...       ...             ...           ...          ...          ...
 1314     7yg5               1             A         1867            A
 1315     7yg5               1             A         1868            A
 1316     7yg5               1             A         1869            A
 1317     7yg5               1             A         1870            A
 1318     7yg5               1             A         1871            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             76                 ?     0               0               0  ...
 1             77                 ?     0               0               0  ...
 2             78                 ?     0               0               0  ...
 3             79                 ?     0               0               0  ...
 4             80                 ?     0               0               0  ...
 ...          ...               ...   ...             ...             ...  ...
 1314        1867                 ?     0               0               0  ...
 1315        1868                 ?     0               0               0  ...
 1316        1869                 ?     0               0               0  ...
 1317        1870                 ?     0               1               0  ...
 1318        1871                 ?     0               1               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0     0.997923  0.001115  0.000782  1.000000  0.000000  0.071051  0.929161
 1     0.988971  0.007325  0.003434  0.274904  0.724973  0.310357  0.689680
 2     0.985549  0.008520  0.005723  0.248445  0.751581  0.323536  0.676424
 3     0.992404  0.001790  0.006012  0.064614  0.935623  0.087595  0.912565
 4     0.991030  0.006263  0.002367  0.261159  0.738669  0.184156  0.815637
 ...        ...       ...       ...       ...       ...       ...       ...
 1314  0.982140  0.017787  0.000000  1.000000  0.000000  0.117522  0.882703
 1315  0.996540  0.002181  0.001338  0.190782  0.809442  0.361985  0.638164
 1316  0.953960  0.046007  0.000000  0.933033  0.067265  0.057472  0.942785
 1317  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
 1318  0.997231  0.002726  0.000000  0.247757  0.752102  0.075992  0.924023


        Neff Neff_I Neff_D
 0     8.362  1.001  1.129
 1     8.411  1.018  1.123
 2     8.575  1.019  1.097
 3     8.609  1.006  1.076
 4     8.642  1.024  1.090
 ...     ...    ...    ...
 1314  6.021  1.025  1.115
 1315  6.050  1.002  1.102
 1316  6.077  1.052  1.066
 1317  6.077  0.000  1.062
 1318  6.078  1.003  1.062

 [1319 rows x 174 columns],
 '8aq6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8aq6               1             G           11            G
 1       8aq6               1             G           12            G
 2       8aq6               1             G           13            G
 3       8aq6               1             G           14            G
 4       8aq6               1             G           15            G
 ..       ...             ...           ...          ...          ...
 166     8aq6               1             G          177            G
 167     8aq6               1             G          178            G
 168     8aq6               1             G          179            G
 169     8aq6               1             G          180            G
 170     8aq6               1             G          181            G

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            -1                 ?     0               0               0  ...
 1             0                 ?     0               0               0  ...
 2             1                 ?     0               0               0  ...
 3             2                 ?     0               0               0  ...
 4             3                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 166         165                 ?     0               0               0  ...
 167         166                 ?     0               0               0  ...
 168         167                 ?     1               0               0  ...
 169         168                 ?     0               0               0  ...
 170         169                 ?     0               1               0  ...

       HHBlits                                                                  \
          M->M      M->I      M->D      I->M      I->I D->M D->D   Neff Neff_I
 0    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  6.039  0.000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.096  0.000
 2    0.998615  0.000000  0.001522  0.000000  0.000000  0.0  0.0  8.233  0.000
 3    0.988971  0.010866  0.000000  0.227037  0.773246  0.0  1.0  8.232  1.017
 4    0.980779  0.006551  0.012578  1.000000  0.000000  1.0  0.0  7.877  1.005
 ..        ...       ...       ...       ...       ...  ...  ...    ...    ...
 166  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 167  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 168  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 169  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 170  1.000000  0.000000  0.000000  1.000000  0.000000  0.0  0.0  1.000  0.000


     Neff_D
 0    0.000
 1    0.000
 2    0.000
 3    1.000
 4    1.011
 ..     ...
 166  0.000
 167  0.000
 168  0.000
 169  0.000
 170  0.000

 [171 rows x 174 columns],
 '8f4s':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8f4s               1             A            4            A
 1       8f4s               1             A            5            A
 2       8f4s               1             A            6            A
 3       8f4s               1             A            7            A
 4       8f4s               1             A            8            A
 ..       ...             ...           ...          ...          ...
 293     8f4s               1             A          297            A
 294     8f4s               1             A          298            A
 295     8f4s               1             A          299            A
 296     8f4s               1             A          300            A
 297     8f4s               1             A          301            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0          6799                 ?     0               0               0  ...
 1          6800                 ?     0               0               0  ...
 2          6801                 ?     0               0               0  ...
 3          6802                 ?     0               1               0  ...
 4          6803                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 293        7092                 ?     0               0               0  ...
 294        7093                 ?     0               0               0  ...
 295        7094                 ?     0               0               0  ...
 296        7095                 ?     0               0               0  ...
 297        7096                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.974004  0.000000  0.026278  0.000000  0.000000  0.000000  1.000000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.832776  0.167009
 2    0.967947  0.013304  0.019024  1.000000  0.000000  0.000000  1.000000
 3    0.979420  0.012595  0.008077  1.000000  0.000000  0.446583  0.553249
 4    0.977386  0.022640  0.000000  0.333325  0.666649  0.405564  0.594604
 ..        ...       ...       ...       ...       ...       ...       ...
 293  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 294  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 295  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 296  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 297  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


       Neff Neff_I Neff_D
 0    7.678  0.000  1.007
 1    8.325  0.000  1.081
 2    8.371  1.064  1.007
 3    8.851  1.103  1.080
 4    8.999  1.041  1.076
 ..     ...    ...    ...
 293  2.301  0.000  0.000
 294  2.301  0.000  0.000
 295  2.301  0.000  0.000
 296  2.131  0.000  0.000
 297  2.025  0.000  0.000

 [298 rows x 174 columns],
 '8jp0':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8jp0               1             A           51            A
 1       8jp0               1             A           52            A
 2       8jp0               1             A           53            A
 3       8jp0               1             A           54            A
 4       8jp0               1             A           55            A
 ..       ...             ...           ...          ...          ...
 714     8jp0               1             A          933            A
 715     8jp0               1             A          934            A
 716     8jp0               1             A          935            A
 717     8jp0               1             A          936            A
 718     8jp0               1             A          937            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            51                 ?     0               0               0  ...
 1            52                 ?     0               0               0  ...
 2            53                 ?     0               0               0  ...
 3            54                 ?     0               0               0  ...
 4            55                 ?     0               0               1  ...
 ..          ...               ...   ...             ...             ...  ...
 714         933                 ?     0               0               0  ...
 715         934                 ?     0               0               0  ...
 716         935                 ?     0               0               0  ...
 717         936                 ?     0               0               0  ...
 718         937                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.944092  0.023389  0.032577  0.520150  0.479632  0.208050  0.791686
 1    0.969962  0.007620  0.022718  0.396667  0.603322  0.224845  0.775393
 2    0.898755  0.088634  0.012595  0.181873  0.817902  0.261521  0.738669
 3    0.981459  0.013725  0.004629  0.559419  0.440740  0.255430  0.744323
 4    0.991717  0.003901  0.004537  0.302918  0.697372  0.243164  0.756808
 ..        ...       ...       ...       ...       ...       ...       ...
 714  0.995160  0.002707  0.001924  1.000000  0.000000  1.000000  0.000000
 715  0.997923  0.000000  0.002213  0.000000  0.000000  1.000000  0.000000
 716  0.981459  0.018453  0.000000  1.000000  0.000000  0.000000  1.000000
 717  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 718  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


       Neff Neff_I Neff_D
 0    6.153  1.060  1.203
 1    6.275  1.022  1.246
 2    6.314  1.319  1.265
 3    6.353  1.083  1.229
 4    6.468  1.009  1.186
 ..     ...    ...    ...
 714  8.194  1.002  1.096
 715  7.700  0.000  1.007
 716  6.919  1.017  1.001
 717  5.703  0.000  1.001
 718  5.823  0.000  0.000

 [719 rows x 174 columns],
 '8qni':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8qni               1             A            5            A
 1       8qni               1             A            6            A
 2       8qni               1             A            7            A
 3       8qni               1             A            8            A
 4       8qni               1             A            9            A
 ..       ...             ...           ...          ...          ...
 372     8qni               1             A          383            A
 373     8qni               1             A          384            A
 374     8qni               1             A          385            A
 375     8qni               1             A          386            A
 376     8qni               1             A          387            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            38                 ?     0               0               0  ...
 1            39                 ?     0               1               0  ...
 2            40                 ?     0               1               0  ...
 3            41                 ?     0               1               0  ...
 4            42                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 372         416                 ?     0               0               0  ...
 373         417                 ?     0               0               0  ...
 374         418                 ?     0               0               0  ...
 375         419                 ?     0               0               0  ...
 376         420                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.920188  0.011858  0.068157  0.500000  0.500000  0.000000  0.000000
 1    0.982821  0.003552  0.013850  0.250000  0.750019  0.882091  0.118093
 2    0.865137  0.053586  0.081447  0.267943  0.732043  0.770571  0.229410
 3    0.961261  0.038607  0.000000  0.547147  0.452817  0.872363  0.127627
 4    1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 ..        ...       ...       ...       ...       ...       ...       ...
 372  0.988971  0.007448  0.003895  0.430475  0.569592  0.405564  0.594604
 373  0.993092  0.004459  0.002436  1.000000  0.000000  0.434672  0.565265
 374  0.987601  0.009685  0.002568  0.411796  0.588453  0.245535  0.754190
 375  0.996540  0.003550  0.000000  0.163119  0.836826  0.466193  0.533663
 376  0.986917  0.009355  0.003379  0.631564  0.368312  0.147726  0.852044


        Neff Neff_I Neff_D
 0     3.752  1.002  0.000
 1     4.080  1.000  1.044
 2     4.267  1.074  1.020
 3     4.652  1.068  1.136
 4     4.565  0.000  1.013
 ..      ...    ...    ...
 372  11.384  1.022  1.087
 373  11.417  1.012  1.066
 374  11.485  1.023  1.044
 375  11.526  1.007  1.040
 376  11.540  1.014  1.019

 [377 rows x 174 columns],
 '8uk6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8uk6               1             A          233            A
 1       8uk6               1             A          234            A
 2       8uk6               1             A          235            A
 3       8uk6               1             A          236            A

## How many PDBs are in the extra test set?

May not be the relevant chain.

In [6]:
mdatlas_nochain = set(p.split("_")[0] for p in mdatlas)

In [7]:
[i for i in features if i in mdatlas_nochain]

[]

## Process

In [8]:
Cif.path = "../training_data/7.Extra_set/cifs"
Cif.original_cifs_path = "../training_data/7.Extra_set/origcifs"

In [9]:
ets = {
    (pdb, cif.residues.label_asym_id.unique().item()): {
        u: ures
        for u, ures in cif.residues.groupby("pdbx_sifts_xref_db_acc", sort=False)
        if u != "?"
    }
    for pdb in features
    for cif in (Cif(pdb),)
}

ets

{('7gqu',
  'A'): {'Q14191':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              PHE             A               1           12
  11             LEU             A               1           13
  19             TRP             A               1           14
  33             PRO             A               1           15
  40             ALA             A               1           16
  ...            ...           ...             ...          ...
  3299           SER             A               1          426
  3305           ARG             A               1          427
  3316           LEU             A               1          428
  3324           ASP             A               1          429
  3332           HIS             A               1          430

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?         527          PHE            A
  11                   ?         528          LEU            A
  19                   ?         529          TRP            A
  33                   ?         530          PRO            A
  40                   ?         531          ALA            A
  ...                ...         ...          ...          ...
  3299                 ?         941          SER            A
  3305                 ?         942          ARG            A
  3316                 ?         943          LEU            A
  3324                 ?         944          ASP            A
  3332                 ?         945          HIS            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1               12                     UNP
  11                    1               13                     UNP
  19                    1               14                     UNP
  33                    1               15                     UNP
  40                    1               16                     UNP
  ...                 ...              ...                     ...
  3299                  1              426                     UNP
  3305                  1              427                     UNP
  3316                  1              428                     UNP
  3324                  1              429                     UNP
  3332                  1              430                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                    Q14191                    527                      F
  11                   Q14191                    528                      L
  19                   Q14191                    529                      W
  33                   Q14191                    530                      P
  40                   Q14191                    531                      A
  ...                     ...                    ...                    ...
  3299                 Q14191                    941                      S
  3305                 Q14191                    942                      R
  3316                 Q14191                    943                      L
  3324                 Q14191                    944                      D
  3332                 Q14191                    945                      H

  [419 rows x 14 columns]},
 ('7yg5',
  'A'): {'Q15878':       label_comp_id label_asym_id label_entity_id label_seq_id  \
  0               ASN             A               1           76
  8               ILE             A               1           77
  16              VAL             A               1           78
  23              ARG             A               1           79
  34              LYS             A               1           80
  ...             ...           ...             ...          ...
  10639           LYS             A               1         1867
  10648           ILE             A               1         1868
  10656           TYR             A               1         1869
  10668           ALA             A               1         1870
  10673           ALA             A               1         1871

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                     ?          76          ASN            A
  8                     ?          77          ILE            A
  16                    ?          78          VAL            A
  23                    ?          79          ARG            A
  34                    ?          80          LYS            A
  ...                 ...         ...          ...          ...
  10639                 ?        1867          LYS            A
  10648                 ?        1868          ILE            A
  10656                 ?        1869          TYR            A
  10668                 ?        1870          ALA            A
  10673                 ?        1871          ALA            A

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                      1               76                     UNP
  8                      1               77                     UNP
  16                     1               78                     UNP
  23                     1               79                     UNP
  34                     1               80                     UNP
  ...                  ...              ...                     ...
  10639                  1             1867                     UNP
  10648                  1             1868                     UNP
  10656                  1             1869                     UNP
  10668                  1             1870                     UNP
  10673                  1             1871                     UNP

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                     Q15878                     76                      N
  8                     Q15878                     77                      I
  16                    Q15878                     78                      V
  23                    Q15878                     79                      R
  34                    Q15878                     80                      K
  ...                      ...                    ...                    ...
  10639                 Q15878                   1867                      K
  10648                 Q15878                   1868                      I
  10656                 Q15878                   1869                      Y
  10668                 Q15878                   1870                      A
  10673                 Q15878                   1871                      A

  [1319 rows x 14 columns]},
 ('8aq6',
  'G'): {'Q9GV45':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  15             PHE             G               1           13
  26             THR             G               1           14
  33             LEU             G               1           15
  41             GLU             G               1           16
  50             ASP             G               1           17
  ...            ...           ...             ...          ...
  1307           GLU             G               1          177
  1316           ARG             G               1          178
  1327           ILE             G               1          179
  1335           LEU             G               1          180
  1343           ALA             G               1          181

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  15                   ?           1          PHE            G
  26                   ?           2          THR            G
  33                   ?           3          LEU            G
  41                   ?           4          GLU            G
  50                   ?           5          ASP            G
  ...                ...         ...          ...          ...
  1307                 ?         165          GLU            G
  1316                 ?         166          ARG            G
  1327                 ?         167          ILE            G
  1335                 ?         168          LEU            G
  1343                 ?         169          ALA            G

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  15                    1               13                     UNP
  26                    1               14                     UNP
  33                    1               15                     UNP
  41                    1               16                     UNP
  50                    1               17                     UNP
  ...                 ...              ...                     ...
  1307                  1              177                     UNP
  1316                  1              178                     UNP
  1327                  1              179                     UNP
  1335                  1              180                     UNP
  1343                  1              181                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  15                   Q9GV45                     28                      F
  26                   Q9GV45                     29                      T
  33                   Q9GV45                     30                      L
  41                   Q9GV45                     31                      A
  50                   Q9GV45                     32                      D
  ...                     ...                    ...                    ...
  1307                 Q9GV45                    192                      E
  1316                 Q9GV45                    193                      N
  1327                 Q9GV45                    194                      I
  1335                 Q9GV45                    195                      L
  1343                 Q9GV45                    196                      A

  [169 rows x 14 columns]},
 ('8f4s',
  'A'): {'P0DTD1':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              SER             A               1            4
  6              SER             A               1            5
  12             GLN             A               1            6
  21             ALA             A               1            7
  26             TRP             A               1            8
  ...            ...           ...             ...          ...
  2301           VAL             A               1          297
  2308           LEU             A               1          298
  2316           VAL             A               1          299
  2323           ASN             A               1          300
  2331           ASN             A               1          301

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?        6799          SER            A
  6                    ?        6800          SER            A
  12                   ?        6801          GLN            A
  21                   ?        6802          ALA            A
  26                   ?        6803          TRP            A
  ...                ...         ...          ...          ...
  2301                 ?        7092          VAL            A
  2308                 ?        7093          LEU            A
  2316                 ?        7094          VAL            A
  2323                 ?        7095          ASN            A
  2331                 ?        7096          ASN            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1                4                     UNP
  6                     1                5                     UNP
  12                    1                6                     UNP
  21                    1                7                     UNP
  26                    1                8                     UNP
  ...                 ...              ...                     ...
  2301                  1              297                     UNP
  2308                  1              298                     UNP
  2316                  1              299                     UNP
  2323                  1              300                     UNP
  2331                  1              301                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                    P0DTD1                   6799                      S
  6                    P0DTD1                   6800                      S
  12                   P0DTD1                   6801                      Q
  21                   P0DTD1                   6802                      A
  26                   P0DTD1                   6803                      W
  ...                     ...                    ...                    ...
  2301                 P0DTD1                   7092                      V
  2308                 P0DTD1                   7093                      L
  2316                 P0DTD1                   7094                      V
  2323                 P0DTD1                   7095                      N
  2331                 P0DTD1                   7096                      N

  [298 rows x 14 columns]},
 ('8jp0',
  'A'): {'P32418-2':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              GLY             A               1           51
  4              SER             A               1           52
  10             TYR             A               1           53
  22             TYR             A               1           54
  34             CYS             A               1           55
  ...            ...           ...             ...          ...
  5613           HIS             A               1          933
  5623           ILE             A               1          934
  5631           LYS             A               1          935
  5640           GLY             A               1          936
  5644           PHE             A               1          937

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?          51          GLY            A
  4                    ?          52          SER            A
  10                   ?          53          TYR            A
  22                   ?          54          TYR            A
  34                   ?          55          CYS            A
  ...                ...         ...          ...          ...
  5613                 ?         933          HIS            A
  5623                 ?         934          ILE            A
  5631                 ?         935          LYS            A
  5640                 ?         936          GLY            A
  5644                 ?         937          PHE            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1               51                     UNP
  4                     1               52                     UNP
  10                    1               53                     UNP
  22                    1               54                     UNP
  34                    1               55                     UNP
  ...                 ...              ...                     ...
  5613                  1              933                     UNP
  5623                  1              934                     UNP
  5631                  1              935                     UNP
  5640                  1              936                     UNP
  5644                  1              937                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                  P32418-2                     51                      G
  4                  P32418-2                     52                      S
  10                 P32418-2                     53                      Y
  22                 P32418-2                     54                      Y
  34                 P32418-2                     55                      C
  ...                     ...                    ...                    ...
  5613               P32418-2                    933                      H
  5623               P32418-2                    934                      I
  5631               P32418-2                    935                      K
  5640               P32418-2                    936                      G
  5644               P32418-2                    937                      F

  [719 rows x 14 columns]},
 ('8qni',
  'A'): {'Q13191':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              GLN             A               1            5
  9              ALA             A               1            6
  14             ALA             A               1            7
  19             ALA             A               1            8
  24             ASP             A               1            9
  ...            ...           ...             ...          ...
  3040           LYS             A               1          383
  3049           GLY             A               1          384
  3053           THR             A               1          385
  3060           GLU             A               1          386
  3069           PRO             A               1          387

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?          38          GLN            A
  9                    ?          39          ALA            A
  14                   ?          40          ALA            A
  19                   ?          41          ALA            A
  24                   ?          42          ASP            A
  ...                ...         ...          ...          ...
  3040                 ?         416          LYS            A
  3049                 ?         417          GLY            A
  3053                 ?         418          THR            A
  3060                 ?         419          GLU            A
  3069                 ?         420          PRO            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1                5                     UNP
  9                     1                6                     UNP
  14                    1                7                     UNP
  19                    1                8                     UNP
  24                    1                9                     UNP
  ...                 ...              ...                     ...
  3040                  1              383                     UNP
  3049                  1              384                     UNP
  3053                  1              385                     UNP
  3060                  1              386                     UNP
  3069                  1              387                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                    Q13191                     38                      Q
  9                    Q13191                     39                      A
  14                   Q13191                     40                      A
  19                   Q13191                     41                      A
  24                   Q13191                     42                      D
  ...                     ...                    ...                    ...
  3040                 Q13191                    416                      K
  3049                 Q13191                    417                      G
  3053                 Q13191                    418                      T
  3060                 Q13191                    419                      E
  3069                 Q13191                    420                      P

  [377 rows x 14 columns]},
 ('8uk6',
  'A'): {'A0A1D8PQM9':      label_comp_id label_asym_id label_entity_id label_seq_id  \

In [10]:
{k: (len(v), tuple(len(r) for r in v.values())) for k, v in ets.items()}

{('7gqu', 'A'): (1, (419,)),
 ('7yg5', 'A'): (1, (1319,)),
 ('8aq6', 'G'): (1, (169,)),
 ('8f4s', 'A'): (1, (298,)),
 ('8jp0', 'A'): (1, (719,)),
 ('8qni', 'A'): (1, (377,)),
 ('8uk6', 'A'): (1, (573,)),
 ('8v81', 'A'): (1, (1132,)),
 ('9dnm', 'C'): (2, (329, 106))}

### 9dnm

**9dnm is a chimera with a cytochrome for crystallization**

In [11]:
ets[("9dnm", "C")].keys()

dict_keys(['P29066', 'P0ABE7'])

In [12]:
ets[("9dnm", "C")].pop('P0ABE7')
ets[("9dnm", "C")].keys()

dict_keys(['P29066'])

<br>

In [13]:
tuple((k, u) for k, v in ets.items() for u in v)

((('7gqu', 'A'), 'Q14191'),
 (('7yg5', 'A'), 'Q15878'),
 (('8aq6', 'G'), 'Q9GV45'),
 (('8f4s', 'A'), 'P0DTD1'),
 (('8jp0', 'A'), 'P32418-2'),
 (('8qni', 'A'), 'Q13191'),
 (('8uk6', 'A'), 'A0A1D8PQM9'),
 (('8v81', 'A'), 'P13569'),
 (('9dnm', 'C'), 'P29066'))

### 8jp0

**In the RCSB PDB 8jp0 is associated to P32418**, which was also force to successfully find apo structures.

In [14]:
ets[('8jp0', 'A')] = {'P32418': ets.pop(('8jp0', 'A'))['P32418-2']}

In [15]:
ets[('8jp0', 'A')]['P32418'].replace(to_replace={"pdbx_sifts_xref_db_acc": "P32418-2"}, value="P32418", inplace=True)
ets[('8jp0', 'A')]['P32418']

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,GLY,A,1,51,?,51,GLY,A,1,51,UNP,P32418,51,G
4,SER,A,1,52,?,52,SER,A,1,52,UNP,P32418,52,S
10,TYR,A,1,53,?,53,TYR,A,1,53,UNP,P32418,53,Y
22,TYR,A,1,54,?,54,TYR,A,1,54,UNP,P32418,54,Y
34,CYS,A,1,55,?,55,CYS,A,1,55,UNP,P32418,55,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5613,HIS,A,1,933,?,933,HIS,A,1,933,UNP,P32418,933,H
5623,ILE,A,1,934,?,934,ILE,A,1,934,UNP,P32418,934,I
5631,LYS,A,1,935,?,935,LYS,A,1,935,UNP,P32418,935,K
5640,GLY,A,1,936,?,936,GLY,A,1,936,UNP,P32418,936,G
5644,PHE,A,1,937,?,937,PHE,A,1,937,UNP,P32418,937,F

In [16]:
tuple((k, u) for k, v in ets.items() for u in v)

((('7gqu', 'A'), 'Q14191'),
 (('7yg5', 'A'), 'Q15878'),
 (('8aq6', 'G'), 'Q9GV45'),
 (('8f4s', 'A'), 'P0DTD1'),
 (('8qni', 'A'), 'Q13191'),
 (('8uk6', 'A'), 'A0A1D8PQM9'),
 (('8v81', 'A'), 'P13569'),
 (('9dnm', 'C'), 'P29066'),
 (('8jp0', 'A'), 'P32418'))

In [17]:
ets_ups = {
    u: {
        "pdb": pdb, 
        "label_asym_id": chain,
        "ures": ures
    }
    for (pdb, chain), ud in ets.items()
    for u, ures in ud.items()    
}

ets_ups

{'Q14191': {'pdb': '7gqu',
  'label_asym_id': 'A',
  'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              PHE             A               1           12
  11             LEU             A               1           13
  19             TRP             A               1           14
  33             PRO             A               1           15
  40             ALA             A               1           16
  ...            ...           ...             ...          ...
  3299           SER             A               1          426
  3305           ARG             A               1          427
  3316           LEU             A               1          428
  3324           ASP             A               1          429
  3332           HIS             A               1          430

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?         527          PHE            A
  11                   ?         528          LEU            A
  19                   ?         529          TRP            A
  33                   ?         530          PRO            A
  40                   ?         531          ALA            A
  ...                ...         ...          ...          ...
  3299                 ?         941          SER            A
  3305                 ?         942          ARG            A
  3316                 ?         943          LEU            A
  3324                 ?         944          ASP            A
  3332                 ?         945          HIS            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1               12                     UNP
  11                    1               13                     UNP
  19                    1               14                     UNP
  33                    1               15                     UNP
  40                    1               16                     UNP
  ...                 ...              ...                     ...
  3299                  1              426                     UNP
  3305                  1              427                     UNP
  3316                  1              428                     UNP
  3324                  1              429                     UNP
  3332                  1              430                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                    Q14191                    527                      F
  11                   Q14191                    528                      L
  19                   Q14191                    529                      W
  33                   Q14191                    530                      P
  40                   Q14191                    531                      A
  ...                     ...                    ...                    ...
  3299                 Q14191                    941                      S
  3305                 Q14191                    942                      R
  3316                 Q14191                    943                      L
  3324                 Q14191                    944                      D
  3332                 Q14191                    945                      H

  [419 rows x 14 columns]},
 'Q15878': {'pdb': '7yg5',
  'label_asym_id': 'A',
  'ures':       label_comp_id label_asym_id label_entity_id label_seq_id  \
  0               ASN             A               1           76
  8               ILE             A               1           77
  16              VAL             A               1           78
  23              ARG             A               1           79
  34              LYS             A               1           80
  ...             ...           ...             ...          ...
  10639           LYS             A               1         1867
  10648           ILE             A               1         1868
  10656           TYR             A               1         1869
  10668           ALA             A               1         1870
  10673           ALA             A               1         1871

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                     ?          76          ASN            A
  8                     ?          77          ILE            A
  16                    ?          78          VAL            A
  23                    ?          79          ARG            A
  34                    ?          80          LYS            A
  ...                 ...         ...          ...          ...
  10639                 ?        1867          LYS            A
  10648                 ?        1868          ILE            A
  10656                 ?        1869          TYR            A
  10668                 ?        1870          ALA            A
  10673                 ?        1871          ALA            A

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                      1               76                     UNP
  8                      1               77                     UNP
  16                     1               78                     UNP
  23                     1               79                     UNP
  34                     1               80                     UNP
  ...                  ...              ...                     ...
  10639                  1             1867                     UNP
  10648                  1             1868                     UNP
  10656                  1             1869                     UNP
  10668                  1             1870                     UNP
  10673                  1             1871                     UNP

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                     Q15878                     76                      N
  8                     Q15878                     77                      I
  16                    Q15878                     78                      V
  23                    Q15878                     79                      R
  34                    Q15878                     80                      K
  ...                      ...                    ...                    ...
  10639                 Q15878                   1867                      K
  10648                 Q15878                   1868                      I
  10656                 Q15878                   1869                      Y
  10668                 Q15878                   1870                      A
  10673                 Q15878                   1871                      A

  [1319 rows x 14 columns]},
 'Q9GV45': {'pdb': '8aq6',
  'label_asym_id': 'G',
  'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  15             PHE             G               1           13
  26             THR             G               1           14
  33             LEU             G               1           15
  41             GLU             G               1           16
  50             ASP             G               1           17
  ...            ...           ...             ...          ...
  1307           GLU             G               1          177
  1316           ARG             G               1          178
  1327           ILE             G               1          179
  1335           LEU             G               1          180
  1343           ALA             G               1          181

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  15                   ?           1          PHE            G
  26                   ?           2          THR            G
  33                   ?           3          LEU            G
  41                   ?           4          GLU            G
  50                   ?           5          ASP            G
  ...                ...         ...          ...          ...
  1307                 ?         165          GLU            G
  1316                 ?         166          ARG            G
  1327                 ?         167          ILE            G
  1335                 ?         168          LEU            G
  1343                 ?         169          ALA            G

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  15                    1               13                     UNP
  26                    1               14                     UNP
  33                    1               15                     UNP
  41                    1               16                     UNP
  50                    1               17                     UNP
  ...                 ...              ...                     ...
  1307                  1              177                     UNP
  1316                  1              178                     UNP
  1327                  1              179                     UNP
  1335                  1              180                     UNP
  1343                  1              181                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  15                   Q9GV45                     28                      F
  26                   Q9GV45                     29                      T
  33                   Q9GV45                     30                      L
  41                   Q9GV45                     31                      A
  50                   Q9GV45                     32                      D
  ...                     ...                    ...                    ...
  1307                 Q9GV45                    192                      E
  1316                 Q9GV45                    193                      N
  1327                 Q9GV45                    194                      I
  1335                 Q9GV45                    195                      L
  1343                 Q9GV45                    196                      A

  [169 rows x 14 columns]},
 'P0DTD1': {'pdb': '8f4s',
  'label_asym_id': 'A',
  'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              SER             A               1            4
  6              SER             A               1            5
  12             GLN             A               1            6
  21             ALA             A               1            7
  26             TRP             A               1            8
  ...            ...           ...             ...          ...
  2301           VAL             A               1          297
  2308           LEU             A               1          298
  2316           VAL             A               1          299
  2323           ASN             A               1          300
  2331           ASN             A               1          301

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?        6799          SER            A
  6                    ?        6800          SER            A
  12                   ?        6801          GLN            A
  21                   ?        6802          ALA            A
  26                   ?        6803          TRP            A
  ...                ...         ...          ...          ...
  2301                 ?        7092          VAL            A
  2308                 ?        7093          LEU            A
  2316                 ?        7094          VAL            A
  2323                 ?        7095          ASN            A
  2331                 ?        7096          ASN            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1                4                     UNP
  6                     1                5                     UNP
  12                    1                6                     UNP
  21                    1                7                     UNP
  26                    1                8                     UNP
  ...                 ...              ...                     ...
  2301                  1              297                     UNP
  2308                  1              298                     UNP
  2316                  1              299                     UNP
  2323                  1              300                     UNP
  2331                  1              301                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                    P0DTD1                   6799                      S
  6                    P0DTD1                   6800                      S
  12                   P0DTD1                   6801                      Q
  21                   P0DTD1                   6802                      A
  26                   P0DTD1                   6803                      W
  ...                     ...                    ...                    ...
  2301                 P0DTD1                   7092                      V
  2308                 P0DTD1                   7093                      L
  2316                 P0DTD1                   7094                      V
  2323                 P0DTD1                   7095                      N
  2331                 P0DTD1                   7096                      N

  [298 rows x 14 columns]},
 'Q13191': {'pdb': '8qni',
  'label_asym_id': 'A',
  'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              GLN             A               1            5
  9              ALA             A               1            6
  14             ALA             A               1            7
  19             ALA             A               1            8
  24             ASP             A               1            9
  ...            ...           ...             ...          ...
  3040           LYS             A               1          383
  3049           GLY             A               1          384
  3053           THR             A               1          385
  3060           GLU             A               1          386
  3069           PRO             A               1          387

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?          38          GLN            A
  9                    ?          39          ALA            A
  14                   ?          40          ALA            A
  19                   ?          41          ALA            A
  24                   ?          42          ASP            A
  ...                ...         ...          ...          ...
  3040                 ?         416          LYS            A
  3049                 ?         417          GLY            A
  3053                 ?         418          THR            A
  3060                 ?         419          GLU            A
  3069                 ?         420          PRO            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1                5                     UNP
  9                     1                6                     UNP
  14                    1                7                     UNP
  19                    1                8                     UNP
  24                    1                9                     UNP
  ...                 ...              ...                     ...
  3040                  1              383                     UNP
  3049                  1              384                     UNP
  3053                  1              385                     UNP
  3060                  1              386                     UNP
  3069                  1              387                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                    Q13191                     38                      Q
  9                    Q13191                     39                      A
  14                   Q13191                     40                      A
  19                   Q13191                     41                      A
  24                   Q13191                     42                      D
  ...                     ...                    ...                    ...
  3040                 Q13191                    416                      K
  3049                 Q13191                    417                      G
  3053                 Q13191                    418                      T
  3060                 Q13191                    419                      E
  3069                 Q13191                    420                      P

  [377 rows x 14 columns]},
 'A0A1D8PQM9': {'pdb': '8uk6',
  'label_asym_id': 'A',
  'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  0              PRO             A               1          233
  7              GLU             A               1          234
  16             ARG             A               1          235
  27             SER             A               1          236
  33             MET             A               1          237
  ...            ...           ...             ...          ...
  4639           ILE             A               1          808
  4647           VAL             A               1          809
  4654           SER             A               1          810
  4660           LEU             A               1          811
  4668           LYS             A               1          812

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  0                    ?         214          PRO            A
  7                    ?         215          GLU            A
  16                   ?         216          ARG            A
  27                   ?         217          SER            A
  33                   ?         218          MET            A
  ...                ...         ...          ...          ...
  4639                 ?         789          ILE            A
  4647                 ?         790          VAL            A
  4654                 ?         791          SER            A
  4660                 ?         792          LEU            A
  4668                 ?         793          LYS            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  0                     1              233                     UNP
  7                     1              234                     UNP
  16                    1              235                     UNP
  27                    1              236                     UNP
  33                    1              237                     UNP
  ...                 ...              ...                     ...
  4639                  1              808                     UNP
  4647                  1              809                     UNP
  4654                  1              810                     UNP
  4660                  1              811                     UNP
  4668                  1              812                     UNP

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  0                A0A1D8PQM9                    214                      P
  7                A0A1D8PQM9                    215                      E
  16               A0A1D8PQM9                    216                      R
  27               A0A1D8PQM9                    217                      S
  33               A0A1D8PQM9                    218                      M
  ...                     ...                    ...                    ...
  4639             A0A1D8PQM9                    789                      I
  4647             A0A1D8PQM9                    790                      V
  4654             A0A1D8PQM9                    791                      S
  4660             A0A1D8PQM9                    792                      L

# ATLAS

## Download cifs

In [22]:
# Recycling check
[f[:4] for f in os.listdir("mdatlascifs") if f.endswith(".cif.gz") and f[:4] not in mdatlas_nochain]

[]

In [23]:
for pdb in mdatlas_nochain:
    fn = f"mdatlascifs/{pdb}_updated.cif.gz"
    if not os.path.isfile(fn):
        if os.path.isfile(fn.replace("_updated", "")):
            shutil.move(fn.replace("_updated", ""), fn)
        else:
            with open(fn, "wb") as f:
                f.write(Pdb(pdb).cif._cif_content)

## Process

In [24]:
Cif.path = "mdatlascifs"
Cif.original_cifs_path = "mdatlascifs"

In [28]:
matches = []

for i in tqdm(mdatlas):
    pdb, chain = i.split("_")
    cif = Cif(pdb, filename=f"mdatlascifs/{pdb}_updated.cif.gz")
    chainres = cif.residues.query(f"auth_asym_id == '{chain}'")
    
    if "pdbx_sifts_xref_db_acc" not in chainres.columns or not any(u in ets_ups for u in chainres.pdbx_sifts_xref_db_acc.unique()):
        continue

    for u, ures in chainres.groupby("pdbx_sifts_xref_db_acc", sort=False):
        if u != "?":
            orig = ets_ups.get(u, {"pdb": "", "label_asym_id": "", "ures": pd.DataFrame(columns=["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"])})
            merge = len(
                ures
                .merge(
                    orig["ures"],
                    on = ["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"],
                    how = "outer", indicator = True
                ).query("_merge == 'both'")
            )
            matches.append({
                "orig_pdb": orig["pdb"],
                "orig_label_asym_id": orig["label_asym_id"],
                "orig_u": u,
                "orig_umin": orig["ures"]["pdbx_sifts_xref_db_num"].astype(int).min(),
                "orig_umax": orig["ures"]["pdbx_sifts_xref_db_num"].astype(int).max(),
                "pdb": pdb,
                "chain": chain,
                "label_asym_id": ures.label_asym_id.unique().item(),
                "umin": ures["pdbx_sifts_xref_db_num"].astype(int).min(),
                "umax": ures["pdbx_sifts_xref_db_num"].astype(int).max(),
                "overlap_ets": merge/( len(orig["ures"]) ),
                "overlap_atlas": merge/( len(ures) ),
            })

  0%|          | 0/1938 [00:00<?, ?it/s]

In [29]:
matchesdf = pd.DataFrame(matches)
matchesdf.to_pickle("atlas_matches.pkl")
matchesdf

,orig_pdb,orig_label_asym_id,orig_u,orig_umin,orig_umax,pdb,chain,label_asym_id,umin,umax,overlap_ets,overlap_atlas
0,8f4s,A,P0DTD1,6799,7096,6wqd,B,B,4020,4140,0.0,0.0
1,8f4s,A,P0DTD1,6799,7096,6zpe,A,A,4263,4383,0.0,0.0
2,8f4s,A,P0DTD1,6799,7096,7k7p,B,A,10,126,0.0,0.0
3,8f4s,A,P0DTD1,6799,7096,7buy,A,A,3264,3569,0.0,0.0
4,8f4s,A,P0DTD1,6799,7096,6zsl,B,A,5326,5917,0.0,0.0
5,8f4s,A,P0DTD1,6799,7096,6yhu,B,B,4018,4134,0.0,0.0
6,8f4s,A,P0DTD1,6799,7096,5rlk,B,B,5326,5917,0.0,0.0