In [1]:
import sys

sys.path.append("../training_data")

In [2]:
from utils.utils import *

# structures_path = "1.Minimal_structures/Minimal_structures"

# Cif.path = structures_path
# Cif.original_cifs_path = "/home/fnerin/Desktop/allodb_new/src/data" # <pdb>_updated.cif.gz

# Functions

## Get representative's sites annos

Dictionary with the site's residues, modulators, chains, and its uniprots. For each uniprot, the corresponding site residues, chains and its residues, and range.

In [3]:
def get_sites_ups(p, sites):
    sites_ups = {}
    for sid, site in sites.items():
        # The annotation is based on Uniprots, so equivalent sites of the site are assumed to have the same Uniprots
        site_res = site["site"]

        # Skip site if any of the chains of the site do not have more than 3 Uniprot-associated residues participating in it
        if any(
            len(ares.query("pdbx_sifts_xref_db_acc != '?'")) < 3 
            for aid, ares in site_res.groupby("label_asym_id")
        ):
            continue

        # For each Uniprot in the site, annotate the chain IDs, the residues of the site and of the chains (that have Uniprots) and the min-max of the Uniprot
        site_ups = {}
        for u, ures in site_res.query("pdbx_sifts_xref_db_acc != '?'").groupby("pdbx_sifts_xref_db_acc"):
            asym_ids = ures.label_asym_id.unique().tolist()
            chains_res = p.residues.query(f"label_asym_id in {asym_ids} and pdbx_sifts_xref_db_acc == '{u}'") # maybe simplify
            site_ups[u] = {
                "ulabel_asym_id": asym_ids, 
                "usiteres": ures,
                "ures": chains_res,
                "umin": chains_res.pdbx_sifts_xref_db_num.astype(int).min(),
                "umax": chains_res.pdbx_sifts_xref_db_num.astype(int).max()
            }
        if len(site_ups) == 0: continue

        sites_ups[sid] = {
            "siteres": site_res,
            "label_asym_id": site_res.query("pdbx_sifts_xref_db_acc != '?'").label_asym_id.unique().tolist(),
            "uniprots": site_ups,
            "modulator": site['mod'].label_asym_id.unique().tolist()
        }
        
    return sites_ups

## Detect ligands close to site

Any elements closer than 6A from the center of geometry of a passed site to detect true apos.

In [4]:
import pymol2

def get_apo_ligands(newpdb, newp, site, threshold=6):
     # Define the PyMOL-style selection of the modulator residues
    sele = " or ".join(
        f"{res['label_asym_id']}/{res['auth_asym_id']}/{res['auth_comp_id']}`{res['auth_seq_id']}{res['pdbx_PDB_ins_code'].replace('?', '')}/*"
        for i, res in site.iterrows()
    )

    with pymol2.PyMOL() as pymol, newp.cif.ciff() as f:
        pymol.cmd.feedback(
            "disable", "executive", "details"
        )  # to silence "ExecutiveLoad-Detail: Detected mmCIF"
        pymol.cmd.load(f.name)

        # Crete a pseudoatom in the center of mass of the site's residues
        pymol.cmd.pseudoatom("pa", selection=sele)

        # Retrieve all atoms within the threshold of the selection
        atoms = pymol.cmd.get_model(f"(br. all within {threshold} of pa) and not (pa or {sele})")
        
    # Process the atom selection to obtain residue identifiers
    residue_ids = set(
        tuple(
            (
                a.segi, a.chain, a.resn,
                a.resi_number, a.ins_code or '?' # pdbx_PDB_ins_code or "?" if none
            ) 
            for a in atoms.atom
        )
    )

    # Transform the PyMOL-derived residue identifiers into a standard table of residues that can be used to retrieve the rows/residues from the parent structure's .residues table    
    residues = (
        newp.residues.merge(
            pd.DataFrame(
                residue_ids,
                columns=[
                    "label_asym_id", "auth_asym_id", "auth_comp_id",
                    "auth_seq_id", "pdbx_PDB_ins_code"
                ],
                dtype=str
            )
        )
        .query("auth_comp_id != 'HOH'")
        .query(f"label_asym_id not in {site.label_asym_id.unique().tolist()}")
    )

    # If there are any residues
    if len(residues) > 0:
        # Get the cif field with entity data        
        edata = pd.DataFrame(newpdb.cif.data["_entity"], dtype=str)
        
        # Get dictionaries of the info of only non-polymer items
        ligands = [
            e
            for e in (
                edata
                .query(f"id in {residues.label_entity_id.unique().tolist()}")[
                    ["pdbx_description", "type"]
                ].to_dict("records")
            )
        ]
        
        ions = all(e["pdbx_description"].lower().endswith(" ion") for e in ligands)

        # Return the info
        if ions: # if found molecules is all ions: no lig
            return {
            ("apo", "has_lig"): False,
            ("apo", "lig_types"): ["ion",],
            ("apo", "lig"): residues
        }
        else: #
            return {
                ("apo", "has_lig"): True,
                ("apo", "lig_types"): list(set(e["type"] for e in ligands)),
                ("apo", "lig"): residues
            }
    else:
        return {("apo", "has_lig"): False}

## Check overlaps in a new putative apo pdb

In [5]:
from utils.new_pdbs import Pdb
import numpy as np
import gzip

In [6]:
def check_pdb(newpdb, pdb, sites_ups, ups):
    newpdb = Pdb(newpdb.lower())

    # If the new PDB doesn't have a column for Uniprotts or doesn't have all Uniprots of holo, skip
    if "pdbx_sifts_xref_db_acc" not in newpdb.residues.columns: return
    if not all(u in newpdb.residues.pdbx_sifts_xref_db_acc.unique() for u in ups): return

    # Use structure of the assembly if it's different from the model and it isn't repetition-based
    newp = newpdb
    try:
        if newpdb.assembly is not None and newpdb.assembly._repetitions is None:
            newp = newpdb.assembly
    except: # fix/patch for structures with multiple models to use only first
        with newpdb._extended_temp_ciff({
            "_atom_site": newpdb.atoms.query("pdbx_PDB_model_num == '1'").to_dict(orient="list")
        }) as f:
            newpdb.cif._cif_content = gzip.compress(f.read().encode())
        if newpdb.assembly is not None and newpdb.assembly._repetitions is None:
            newp = newpdb.assembly
    # we assume that all sites_uniprots are going to be found in the pdb, AND:
    # we don't care that the chains with the ups of interest have other ups (chimeras)

    # Check each Uniprot-based site for overlaps
    for sid, site in sites_ups.items():
        # Obtain the residues of the Uniprot-based site in the new structure, and skip if not found
        merged_site = (
            newp.residues
            .query(f"pdbx_PDB_model_num == '1'")
            .merge(
                site["siteres"],
                on=['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num'],
                suffixes = (None, '_del')
            )
            .loc[:, lambda x: [c for c in x if not c.endswith("_del")]]
        )
        if len(merged_site) == 0:
            continue

        # Get the ligands found in the correspnding Uniprot-based site, if any
        ligands = {
            asym_id: get_apo_ligands(newpdb, newp, merged_siteres)
            for asym_id, merged_siteres in merged_site.groupby("label_asym_id")
        }

        # Create the base Uniprot-site dictionary with the holo information
        sd = {
            ("allodb", "pdb"): pdb.entry_id,
            ("allodb", "site_id"): sid,
            ("allodb", "label_asym_id"): site["label_asym_id"],
            ("allodb", "mod"): site["modulator"],
            ("allodb", "siteres"): site["siteres"],
        }
        # Create the base Uniprot-site dictionary with the apo information at the whole-site level
        apo_sd = {
            ("apo", "site"): round(
                (
                    len( merged_site[['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']].drop_duplicates() ) 
                    / len( site["siteres"][['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']].drop_duplicates() )
                ),               
                2
            ),
            ("apo", "siteres"): merged_site,
            ("apo", "any_apo_chain"): any(not c[("apo", "has_lig")] for c in ligands.values()),
            ("apo", "ligands"): ligands,
        }
        # Yield a dictinary for each Uniprot on the original Uniprot-site, containing sd and apo_sd together with other Uniprot-specific information
        for u, ud in site["uniprots"].items():
            d = sd.copy()

            # Obtain the Uniprot residues of the structure and calculate chain and site overlaps
            ures = newp.residues.query(f"pdbx_sifts_xref_db_acc == '{u}' and pdbx_PDB_model_num == '1'")
            if len(ures) == 0:
                break
            umin, umax = ures.pdbx_sifts_xref_db_num.astype(int).min(), ures.pdbx_sifts_xref_db_num.astype(int).max()
            usite = ures.merge(
                ud["usiteres"], 
                on=['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num'],
                suffixes = (None, '_del')
            ).loc[:, lambda x: [c for c in x if not c.endswith("_del")]]
                            
            udrange = range(ud["umin"], ud["umax"]+1)
            urange = range(umin, umax+1)
            merge = ud["ures"].drop_duplicates().merge(ures[['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']].drop_duplicates())

            # Return the Uniprot-specific dictionary with all holo, apo, Uniprot and chain and site overlap info
            d.update({
                ("allodb", "uniprot"): u,
                **{("allodb", k): v for k, v in ud.items() if k != "ures"},
                ("apo", "pdb"): newpdb.entry_id, 
                ("apo", "label_asym_id"): ures.label_asym_id.unique().tolist(), 
                **apo_sd,
                ("apo", "umin"): umin,
                ("apo", "umax"): umax,
                ("apo", "usite"): round(
                    len(
                        usite[
                            ['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']
                        ].drop_duplicates()
                    )  / len( ud["usiteres"][['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']].drop_duplicates() ),
                    2
                ),
                ("overlap", "a_in_h_minmax"): len(np.intersect1d(udrange, urange)) / len(urange),
                ("overlap", "h_in_a_minmax"): len(np.intersect1d(udrange, urange)) / len(udrange),
                ("overlap", "a_in_h_merge"): len(merge) / len( ures[['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']].drop_duplicates() ),
                ("overlap", "h_in_a_merge"): len(merge) / len( ud["ures"][['pdbx_sifts_xref_db_acc', 'pdbx_sifts_xref_db_num']].drop_duplicates() ),
            })
            yield d

## Function

In [7]:
from rcsbsearchapi import rcsb_attributes
from functools import partial

def get_apos(pdb):
    pdb = Cif(pdb)
    if "pdbx_sifts_xref_db_acc" not in pdb.residues.columns:
        print(f"{pdb.entry_id}: No Uniprot column in original pdb")
        return []
        
    # protein or others. allo modulators. Ions?
    sites_ups = get_sites_ups(pdb, holos_sites[pdb.entry_id])
    if len(sites_ups) == 0:
        print(f"{pdb.entry_id}: No valid Uniprots in any site")
    
    ups = list(set(u for sd in sites_ups.values() for u in sd["uniprots"].keys()))

    
    pdbs = False
    for q in (
        rcsb_attributes.rcsb_polymer_entity_container_identifiers.reference_sequence_identifiers.database_accession == up
        for up in ups
    ):
        pdbs = q if not pdbs else pdbs & q
    
    if not pdbs:
        print(f"{pdb.entry_id}: No valid Uniprots in any site")
        return []
        
    pdbs = set(i.lower() for i in pdbs()) - dbpdbs
    if len(pdbs) == 0: 
        print(f"{pdb.entry_id}: No other PDBs of Uniprots")
        return []

    for newpdb in tqdm(pdbs, smoothing=0, desc=pdb.entry_id):
        for r in check_pdb(newpdb, pdb, sites_ups, ups):
            yield r

# Apos of extra set

## Data

In [8]:
from tqdm import tqdm

In [9]:
import os, sys, pickle
from tqdm.notebook import tqdm

In [10]:
extra_holos_featuresf = "../training_data/7.Extra_set/features.pkl"

with open(extra_holos_featuresf, "rb") as f:
    extra_holos_featuresd = pickle.load(f)

extra_holos_featuresd

{'7gqu':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       7gqu               1             A           12            A
 1       7gqu               1             A           13            A
 2       7gqu               1             A           14            A
 3       7gqu               1             A           15            A
 4       7gqu               1             A           16            A
 ..       ...             ...           ...          ...          ...
 414     7gqu               1             A          426            A
 415     7gqu               1             A          427            A
 416     7gqu               1             A          428            A
 417     7gqu               1             A          429            A
 418     7gqu               1             A          430            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0           527                 ?     0               0               0  ...
 1           528                 ?     0               0               0  ...
 2           529                 ?     0               0               0  ...
 3           530                 ?     0               0               0  ...
 4           531                 ?     0               1               0  ...
 ..          ...               ...   ...             ...             ...  ...
 414         941                 ?     0               0               0  ...
 415         942                 ?     0               0               0  ...
 416         943                 ?     0               0               0  ...
 417         944                 ?     0               0               0  ...
 418         945                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.992404  0.000000  0.007872  0.000000  0.000000  0.000000  0.000000
 1    0.970634  0.000000  0.029688  0.000000  0.000000  0.000000  1.000000
 2    0.984184  0.016020  0.000000  0.317098  0.683020  0.677362  0.322641
 3    1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
 4    0.983502  0.008717  0.007775  0.564091  0.435879  0.515842  0.483974
 ..        ...       ...       ...       ...       ...       ...       ...
 414  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 415  0.995850  0.004349  0.000000  1.000000  0.000000  0.000000  0.000000
 416  0.995160  0.000000  0.004849  0.000000  0.000000  0.000000  0.000000
 417  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 418  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000


        Neff Neff_I Neff_D
 0    11.507  0.000  0.000
 1    11.647  0.000  1.004
 2    11.184  1.054  1.083
 3    11.324  0.000  1.019
 4    11.412  1.024  1.019
 ..      ...    ...    ...
 414  11.186  0.000  1.038
 415  10.451  1.004  0.000
 416  10.892  0.000  0.000
 417  11.436  0.000  1.004
 418  10.967  0.000  0.000

 [419 rows x 174 columns],
 '7yg5':      Residues                                                          \
           pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0        7yg5               1             A           76            A
 1        7yg5               1             A           77            A
 2        7yg5               1             A           78            A
 3        7yg5               1             A           79            A
 4        7yg5               1             A           80            A
 ...       ...             ...           ...          ...          ...
 1314     7yg5               1             A         1867            A
 1315     7yg5               1             A         1868            A
 1316     7yg5               1             A         1869            A
 1317     7yg5               1             A         1870            A
 1318     7yg5               1             A         1871            A

                                    Label     Amino acids                  ...  \
      auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0             76                 ?     0               0               0  ...
 1             77                 ?     0               0               0  ...
 2             78                 ?     0               0               0  ...
 3             79                 ?     0               0               0  ...
 4             80                 ?     0               0               0  ...
 ...          ...               ...   ...             ...             ...  ...
 1314        1867                 ?     0               0               0  ...
 1315        1868                 ?     0               0               0  ...
 1316        1869                 ?     0               0               0  ...
 1317        1870                 ?     0               1               0  ...
 1318        1871                 ?     0               1               0  ...

        HHBlits                                                              \
           M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0     0.997923  0.001115  0.000782  1.000000  0.000000  0.071051  0.929161
 1     0.988971  0.007325  0.003434  0.274904  0.724973  0.310357  0.689680
 2     0.985549  0.008520  0.005723  0.248445  0.751581  0.323536  0.676424
 3     0.992404  0.001790  0.006012  0.064614  0.935623  0.087595  0.912565
 4     0.991030  0.006263  0.002367  0.261159  0.738669  0.184156  0.815637
 ...        ...       ...       ...       ...       ...       ...       ...
 1314  0.982140  0.017787  0.000000  1.000000  0.000000  0.117522  0.882703
 1315  0.996540  0.002181  0.001338  0.190782  0.809442  0.361985  0.638164
 1316  0.953960  0.046007  0.000000  0.933033  0.067265  0.057472  0.942785
 1317  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000
 1318  0.997231  0.002726  0.000000  0.247757  0.752102  0.075992  0.924023


        Neff Neff_I Neff_D
 0     8.362  1.001  1.129
 1     8.411  1.018  1.123
 2     8.575  1.019  1.097
 3     8.609  1.006  1.076
 4     8.642  1.024  1.090
 ...     ...    ...    ...
 1314  6.021  1.025  1.115
 1315  6.050  1.002  1.102
 1316  6.077  1.052  1.066
 1317  6.077  0.000  1.062
 1318  6.078  1.003  1.062

 [1319 rows x 174 columns],
 '8aq6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8aq6               1             G           11            G
 1       8aq6               1             G           12            G
 2       8aq6               1             G           13            G
 3       8aq6               1             G           14            G
 4       8aq6               1             G           15            G
 ..       ...             ...           ...          ...          ...
 166     8aq6               1             G          177            G
 167     8aq6               1             G          178            G
 168     8aq6               1             G          179            G
 169     8aq6               1             G          180            G
 170     8aq6               1             G          181            G

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            -1                 ?     0               0               0  ...
 1             0                 ?     0               0               0  ...
 2             1                 ?     0               0               0  ...
 3             2                 ?     0               0               0  ...
 4             3                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 166         165                 ?     0               0               0  ...
 167         166                 ?     0               0               0  ...
 168         167                 ?     1               0               0  ...
 169         168                 ?     0               0               0  ...
 170         169                 ?     0               1               0  ...

       HHBlits                                                                  \
          M->M      M->I      M->D      I->M      I->I D->M D->D   Neff Neff_I
 0    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  6.039  0.000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  7.096  0.000
 2    0.998615  0.000000  0.001522  0.000000  0.000000  0.0  0.0  8.233  0.000
 3    0.988971  0.010866  0.000000  0.227037  0.773246  0.0  1.0  8.232  1.017
 4    0.980779  0.006551  0.012578  1.000000  0.000000  1.0  0.0  7.877  1.005
 ..        ...       ...       ...       ...       ...  ...  ...    ...    ...
 166  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 167  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 168  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 169  1.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.0  1.000  0.000
 170  1.000000  0.000000  0.000000  1.000000  0.000000  0.0  0.0  1.000  0.000


     Neff_D
 0    0.000
 1    0.000
 2    0.000
 3    1.000
 4    1.011
 ..     ...
 166  0.000
 167  0.000
 168  0.000
 169  0.000
 170  0.000

 [171 rows x 174 columns],
 '8f4s':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8f4s               1             A            4            A
 1       8f4s               1             A            5            A
 2       8f4s               1             A            6            A
 3       8f4s               1             A            7            A
 4       8f4s               1             A            8            A
 ..       ...             ...           ...          ...          ...
 293     8f4s               1             A          297            A
 294     8f4s               1             A          298            A
 295     8f4s               1             A          299            A
 296     8f4s               1             A          300            A
 297     8f4s               1             A          301            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0          6799                 ?     0               0               0  ...
 1          6800                 ?     0               0               0  ...
 2          6801                 ?     0               0               0  ...
 3          6802                 ?     0               1               0  ...
 4          6803                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 293        7092                 ?     0               0               0  ...
 294        7093                 ?     0               0               0  ...
 295        7094                 ?     0               0               0  ...
 296        7095                 ?     0               0               0  ...
 297        7096                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.974004  0.000000  0.026278  0.000000  0.000000  0.000000  1.000000
 1    1.000000  0.000000  0.000000  0.000000  0.000000  0.832776  0.167009
 2    0.967947  0.013304  0.019024  1.000000  0.000000  0.000000  1.000000
 3    0.979420  0.012595  0.008077  1.000000  0.000000  0.446583  0.553249
 4    0.977386  0.022640  0.000000  0.333325  0.666649  0.405564  0.594604
 ..        ...       ...       ...       ...       ...       ...       ...
 293  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 294  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 295  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 296  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
 297  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


       Neff Neff_I Neff_D
 0    7.678  0.000  1.007
 1    8.325  0.000  1.081
 2    8.371  1.064  1.007
 3    8.851  1.103  1.080
 4    8.999  1.041  1.076
 ..     ...    ...    ...
 293  2.301  0.000  0.000
 294  2.301  0.000  0.000
 295  2.301  0.000  0.000
 296  2.131  0.000  0.000
 297  2.025  0.000  0.000

 [298 rows x 174 columns],
 '8jp0':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8jp0               1             A           51            A
 1       8jp0               1             A           52            A
 2       8jp0               1             A           53            A
 3       8jp0               1             A           54            A
 4       8jp0               1             A           55            A
 ..       ...             ...           ...          ...          ...
 714     8jp0               1             A          933            A
 715     8jp0               1             A          934            A
 716     8jp0               1             A          935            A
 717     8jp0               1             A          936            A
 718     8jp0               1             A          937            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            51                 ?     0               0               0  ...
 1            52                 ?     0               0               0  ...
 2            53                 ?     0               0               0  ...
 3            54                 ?     0               0               0  ...
 4            55                 ?     0               0               1  ...
 ..          ...               ...   ...             ...             ...  ...
 714         933                 ?     0               0               0  ...
 715         934                 ?     0               0               0  ...
 716         935                 ?     0               0               0  ...
 717         936                 ?     0               0               0  ...
 718         937                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.944092  0.023389  0.032577  0.520150  0.479632  0.208050  0.791686
 1    0.969962  0.007620  0.022718  0.396667  0.603322  0.224845  0.775393
 2    0.898755  0.088634  0.012595  0.181873  0.817902  0.261521  0.738669
 3    0.981459  0.013725  0.004629  0.559419  0.440740  0.255430  0.744323
 4    0.991717  0.003901  0.004537  0.302918  0.697372  0.243164  0.756808
 ..        ...       ...       ...       ...       ...       ...       ...
 714  0.995160  0.002707  0.001924  1.000000  0.000000  1.000000  0.000000
 715  0.997923  0.000000  0.002213  0.000000  0.000000  1.000000  0.000000
 716  0.981459  0.018453  0.000000  1.000000  0.000000  0.000000  1.000000
 717  1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 718  1.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000


       Neff Neff_I Neff_D
 0    6.153  1.060  1.203
 1    6.275  1.022  1.246
 2    6.314  1.319  1.265
 3    6.353  1.083  1.229
 4    6.468  1.009  1.186
 ..     ...    ...    ...
 714  8.194  1.002  1.096
 715  7.700  0.000  1.007
 716  6.919  1.017  1.001
 717  5.703  0.000  1.001
 718  5.823  0.000  0.000

 [719 rows x 174 columns],
 '8qni':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8qni               1             A            5            A
 1       8qni               1             A            6            A
 2       8qni               1             A            7            A
 3       8qni               1             A            8            A
 4       8qni               1             A            9            A
 ..       ...             ...           ...          ...          ...
 372     8qni               1             A          383            A
 373     8qni               1             A          384            A
 374     8qni               1             A          385            A
 375     8qni               1             A          386            A
 376     8qni               1             A          387            A

                                   Label     Amino acids                  ...  \
     auth_seq_id pdbx_PDB_ins_code label label_comp_id_A label_comp_id_C  ...
 0            38                 ?     0               0               0  ...
 1            39                 ?     0               1               0  ...
 2            40                 ?     0               1               0  ...
 3            41                 ?     0               1               0  ...
 4            42                 ?     0               0               0  ...
 ..          ...               ...   ...             ...             ...  ...
 372         416                 ?     0               0               0  ...
 373         417                 ?     0               0               0  ...
 374         418                 ?     0               0               0  ...
 375         419                 ?     0               0               0  ...
 376         420                 ?     0               0               0  ...

       HHBlits                                                              \
          M->M      M->I      M->D      I->M      I->I      D->M      D->D
 0    0.920188  0.011858  0.068157  0.500000  0.500000  0.000000  0.000000
 1    0.982821  0.003552  0.013850  0.250000  0.750019  0.882091  0.118093
 2    0.865137  0.053586  0.081447  0.267943  0.732043  0.770571  0.229410
 3    0.961261  0.038607  0.000000  0.547147  0.452817  0.872363  0.127627
 4    1.000000  0.000000  0.000000  0.000000  0.000000  1.000000  0.000000
 ..        ...       ...       ...       ...       ...       ...       ...
 372  0.988971  0.007448  0.003895  0.430475  0.569592  0.405564  0.594604
 373  0.993092  0.004459  0.002436  1.000000  0.000000  0.434672  0.565265
 374  0.987601  0.009685  0.002568  0.411796  0.588453  0.245535  0.754190
 375  0.996540  0.003550  0.000000  0.163119  0.836826  0.466193  0.533663
 376  0.986917  0.009355  0.003379  0.631564  0.368312  0.147726  0.852044


        Neff Neff_I Neff_D
 0     3.752  1.002  0.000
 1     4.080  1.000  1.044
 2     4.267  1.074  1.020
 3     4.652  1.068  1.136
 4     4.565  0.000  1.013
 ..      ...    ...    ...
 372  11.384  1.022  1.087
 373  11.417  1.012  1.066
 374  11.485  1.023  1.044
 375  11.526  1.007  1.040
 376  11.540  1.014  1.019

 [377 rows x 174 columns],
 '8uk6':     Residues                                                          \
          pdb label_entity_id label_asym_id label_seq_id auth_asym_id
 0       8uk6               1             A          233            A
 1       8uk6               1             A          234            A
 2       8uk6               1             A          235            A
 3       8uk6               1             A          236            A

In [11]:
extra_holos_sitesf = "../training_data/7.Extra_set/news_sites.pkl"

with open(extra_holos_sitesf, "rb") as f:
    extra_holos_sites = {k: v for k, v in pickle.load(f).items() if k in extra_holos_featuresd}

extra_holos_sites

{'7gqu': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
   3420           X1L             D               4            .

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   3420                 ?        1002          X1L            A

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   3420                  1             1002                       ?

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   3420                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            VAL             A               1           55                 ?
   1            MET             A               1           56                 ?
   2            ALA             A               1           57                 ?
   3            THR             A               1          188                 ?
   4            ALA             A               1          189                 ?
   5            THR             A               1          190                 ?
   6            ALA             A               1          191                 ?
   7            SER             A               1          192                 ?
   8            ARG             A               1          196                 ?
   9            ILE             A               1          210                 ?
   10           THR             A               1          211                 ?
   11           CYS             A               1          212                 ?
   12           THR             A               1          213                 ?
   13           GLY             A               1          214                 ?
   14           ASP             A               1          329                 ?
   15           MET             A               1          330                 ?
   16           GLU             A               1          331                 ?
   17           SER             A               1          332                 ?
   18           TYR             A               1          334                 ?
   19           GLN             A               1          335                 ?
   20           TYR             A               1          376                 ?
   21           MET             A               1          380                 ?
   22           LYS             A               1          383                 ?
   23           ILE             A               1          398                 ?
   24           HIS             A               1          401                 ?
   25           PHE             A               1          402                 ?
   26           GLU             A               1          403                 ?
   27           ASP             A               1          404                 ?
   28           LYS             A               1          405                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0          570          VAL            A                  1               55
   1          571          MET            A                  1               56
   2          572          ALA            A                  1               57
   3          703          THR            A                  1              188
   4          704          ALA            A                  1              189
   5          705          THR            A                  1              190
   6          706          ALA            A                  1              191
   7          707          SER            A                  1              192
   8          711          ARG            A                  1              196
   9          725          ILE            A                  1              210
   10         726          THR            A                  1              211
   11         727          CYS            A                  1              212
   12         728          THR            A                  1              213
   13         729          GLY            A                  1              214
   14         844          ASP            A                  1              329
   15         845          MET            A                  1              330
   16         846          GLU            A                  1              331
   17         847          SER            A                  1              332
   18         849          TYR            A                  1              334
   19         850          GLN            A                  1              335
   20         891          TYR            A                  1              376
   21         895          MET            A                  1              380
   22         898          LYS            A                  1              383
   23         913          ILE            A                  1              398
   24         916          HIS            A                  1              401
   25         917          PHE            A                  1              402
   26         918          GLU            A                  1              403
   27         919          ASP            A                  1              404
   28         920          LYS            A                  1              405

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q14191                    570
   1                      UNP                 Q14191                    571
   2                      UNP                 Q14191                    572
   3                      UNP                 Q14191                    703
   4                      UNP                 Q14191                    704
   5                      UNP                 Q14191                    705
   6                      UNP                 Q14191                    706
   7                      UNP                 Q14191                    707
   8                      UNP                 Q14191                    711
   9                      UNP                 Q14191                    725
   10                     UNP                 Q14191                    726
   11                     UNP                 Q14191                    727
   12                     UNP                 Q14191                    728
   13                     UNP                 Q14191                    729
   14                     UNP                 Q14191                    844
   15                     UNP                 Q14191                    845
   16                     UNP                 Q14191                    846
   17                     UNP                 Q14191                    847
   18                     UNP                 Q14191                    849
   19                     UNP                 Q14191                    850
   20                     UNP                 Q14191                    891
   21                     UNP                 Q14191                    895
   22                     UNP                 Q14191                    898
   23                     UNP                 Q14191                    913
   24                     UNP                 Q14191                    916
   25                     UNP                 Q14191                    917
   26                     UNP                 Q14191                    918
   27                     UNP                 Q14191                    919
   28                     UNP                 Q14191                    920

      pdbx_sifts_xref_db_res
   0                       V
   1                       M
   2                       A
   3                       T
   4                       A
   5                       T
   6                       A
   7                       S
   8                       R
   9                       I
   10                      T
   11                      C
   12                      T
   13                      G
   14                      D
   15                      M
   16                      E
   17                      S
   18                      Y
   19                      Q
   20                      Y
   21                      M
   22                      K
   23                      I
   24                      H
   25                      F
   26                      E
   27                      D
   28                      K  }],
 '7yg5': [{'mod':       label_comp_id label_asym_id label_entity_id label_seq_id  \
   20113           TOR             V              10            .

         pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   20113                 ?        2416          TOR            A

         pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   20113                  1             2416                       ?

         pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   20113                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ILE             A               1          209                 ?
   1            VAL             A               1          210                 ?
   2            SER             A               1          213                 ?
   3            ILE             A               1          214                 ?
   4            ALA             A               1          217                 ?
   5            GLU             A               1          353                 ?
   6            PHE             A               1          354                 ?
   7            GLU             A               1          357                 ?
   8            ARG             A               1          358                 ?
   9            ARG             A               1          360                 ?
   10           ASN             A               1          363                 ?
   11           SER             A               1          595                 ?
   12           LEU             A               1          596                 ?
   13           SER             A               1          599                 ?
   14           MET             A               1          600                 ?
   15           LYS             A               1          601                 ?
   16           SER             A               1          602                 ?
   17           ILE             A               1          603                 ?
   18           ILE             A               1          604                 ?
   19           LEU             A               1          606                 ?
   20           ASN             A               1          696                 ?
   21           VAL             A               1          697                 ?
   22           LEU             A               1          699                 ?
   23           ALA             A               1          700                 ?
   24           ILE             A               1          701                 ?
   25           ALA             A               1          702                 ?
   26           VAL             A               1          703                 ?
   27           ASP             A               1          704                 ?
   28           ASN             A               1          705                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0          209          ILE            A                  1              209
   1          210          VAL            A                  1              210
   2          213          SER            A                  1              213
   3          214          ILE            A                  1              214
   4          217          ALA            A                  1              217
   5          353          GLU            A                  1              353
   6          354          PHE            A                  1              354
   7          357          GLU            A                  1              357
   8          358          ARG            A                  1              358
   9          360          ARG            A                  1              360
   10         363          ASN            A                  1              363
   11         595          SER            A                  1              595
   12         596          LEU            A                  1              596
   13         599          SER            A                  1              599
   14         600          MET            A                  1              600
   15         601          LYS            A                  1              601
   16         602          SER            A                  1              602
   17         603          ILE            A                  1              603
   18         604          ILE            A                  1              604
   19         606          LEU            A                  1              606
   20         696          ASN            A                  1              696
   21         697          VAL            A                  1              697
   22         699          LEU            A                  1              699
   23         700          ALA            A                  1              700
   24         701          ILE            A                  1              701
   25         702          ALA            A                  1              702
   26         703          VAL            A                  1              703
   27         704          ASP            A                  1              704
   28         705          ASN            A                  1              705

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
   0                      UNP                 Q15878                    209
   1                      UNP                 Q15878                    210
   2                      UNP                 Q15878                    213
   3                      UNP                 Q15878                    214
   4                      UNP                 Q15878                    217
   5                      UNP                 Q15878                    353
   6                      UNP                 Q15878                    354
   7                      UNP                 Q15878                    357
   8                      UNP                 Q15878                    358
   9                      UNP                 Q15878                    360
   10                     UNP                 Q15878                    363
   11                     UNP                 Q15878                    595
   12                     UNP                 Q15878                    596
   13                     UNP                 Q15878                    599
   14                     UNP                 Q15878                    600
   15                     UNP                 Q15878                    601
   16                     UNP                 Q15878                    602
   17                     UNP                 Q15878                    603
   18                     UNP                 Q15878                    604
   19                     UNP                 Q15878                    606
   20                     UNP                 Q15878                    696
   21                     UNP                 Q15878                    697
   22                     UNP                 Q15878                    699
   23                     UNP                 Q15878                    700
   24                     UNP                 Q15878                    701
   25                     UNP                 Q15878                    702
   26                     UNP                 Q15878                    703
   27                     UNP                 Q15878                    704
   28                     UNP                 Q15878                    705

      pdbx_sifts_xref_db_res
   0                       I
   1                       V
   2                       S
   3                       I
   4                       A
   5                       E
   6                       F
   7                       E
   8                       R
   9                       R
   10                      N
   11                      S
   12                      L
   13                      S
   14                      M
   15                      K
   16                      S
   17                      I
   18                      I
   19                      L
   20                      N
   21                      V
   22                      L
   23                      A
   24                      I
   25                      A
   26                      V
   27                      D
   28                      N  }],
 '8aq6': [{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
   1349           NT0            IA               7            .

        pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
   1349                 ?         301          NT0            G

        pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
   1349                  1              301                       ?

        pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
   1349                      ?                      ?                      ?  ,
   'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
   0            ASP             G               1           21                 ?
   1            TRP             G               1           22                 ?
   2            ARG             G               1           23                 ?
   3            ILE             G               1           53                 ?
   4            ARG             G               1           55                 ?
   5            ASP             G               1           67                 ?
   6            HIS             G               1           69                 ?
   7            ILE             G               1           71                 ?
   8            TYR             G               1           93                 ?
   9            PRO             G               1           94                 ?
   10           VAL             G               1           95                 ?
   11           PHE             G               1          100                 ?
   12           LYS             G               1          101                 ?
   13           ILE             G               1          103                 ?
   14           TYR             G               1          106                 ?
   15           ILE             G               1          179                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
   0            9          ASP            G                  1               21
   1           10          TRP            G                  1               22
   2           11          ARG            G                  1               23
   3           41          ILE            G                  1               53
   4           43          ARG            G                  1               55
   5           55          ASP            G                  1               67
   6           57          HIS            G                  1               69
   7           59          ILE            G                  1               71
   8           81          TYR            G                  1               93

In [12]:
len(extra_holos_featuresd), len(extra_holos_sites)

(9, 9)

##### 8uk6

Already know the only other structure is the AlphaFold model.

In [13]:
extra_holos_featuresd.pop("8uk6")
extra_holos_sites.pop("8uk6")

[{'mod':      label_comp_id label_asym_id label_entity_id label_seq_id  \
  4678           WVK             C               3            .

       pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
  4678                 ?         802          WVK            A

       pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
  4678                  1              802                       ?

       pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
  4678                      ?                      ?                      ?  ,
  'site':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            GLY             A               1          281                 ?
  1            PHE             A               1          282                 ?
  2            LEU             A               1          283                 ?
  3            HIS             A               1          284                 ?
  4            HIS             A               1          287                 ?
  5            GLY             A               1          512                 ?
  6            THR             A               1          513                 ?
  7            ILE             A               1          514                 ?
  8            MET             A               1          515                 ?
  9            SER             A               1          516                 ?
  10           LYS             A               1          517                 ?
  11           ILE             A               1          520                 ?
  12           TRP             A               1          532                 ?
  13           ARG             A               1          536                 ?
  14           LEU             A               1          537                 ?
  15           TYR             A               1          538                 ?
  16           THR             A               1          539                 ?
  17           GLN             A               1          718                 ?
  18           LEU             A               1          719                 ?
  19           PHE             A               1          720                 ?
  20           PRO             A               1          725                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
  0          262          GLY            A                  1              281
  1          263          PHE            A                  1              282
  2          264          LEU            A                  1              283
  3          265          HIS            A                  1              284
  4          268          HIS            A                  1              287
  5          493          GLY            A                  1              512
  6          494          THR            A                  1              513
  7          495          ILE            A                  1              514
  8          496          MET            A                  1              515
  9          497          SER            A                  1              516
  10         498          LYS            A                  1              517
  11         501          ILE            A                  1              520
  12         513          TRP            A                  1              532
  13         517          ARG            A                  1              536
  14         518          LEU            A                  1              537
  15         519          TYR            A                  1              538
  16         520          THR            A                  1              539
  17         699          GLN            A                  1              718
  18         700          LEU            A                  1              719
  19         701          PHE            A                  1              720
  20         706          PRO            A                  1              725

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
  0                      UNP             A0A1D8PQM9                    262
  1                      UNP             A0A1D8PQM9                    263
  2                      UNP             A0A1D8PQM9                    264
  3                      UNP             A0A1D8PQM9                    265
  4                      UNP             A0A1D8PQM9                    268
  5                      UNP             A0A1D8PQM9                    493
  6                      UNP             A0A1D8PQM9                    494
  7                      UNP             A0A1D8PQM9                    495
  8                      UNP             A0A1D8PQM9                    496
  9                      UNP             A0A1D8PQM9                    497
  10                     UNP             A0A1D8PQM9                    498
  11                     UNP             A0A1D8PQM9                    501
  12                     UNP             A0A1D8PQM9                    513
  13                     UNP             A0A1D8PQM9                    517
  14                     UNP             A0A1D8PQM9                    518
  15                     UNP             A0A1D8PQM9                    519
  16                     UNP             A0A1D8PQM9                    520
  17                     UNP             A0A1D8PQM9                    699
  18                     UNP             A0A1D8PQM9                    700
  19                     UNP             A0A1D8PQM9                    701
  20                     UNP             A0A1D8PQM9                    706

     pdbx_sifts_xref_db_res
  0                       G
  1                       F
  2                       L
  3                       H
  4                       H
  5                       G
  6                       T
  7                       I
  8                       M
  9                       S
  10                      K
  11                      I
  12                      W
  13                      R
  14                      L
  15                      Y
  16                      T
  17                      Q
  18                      L
  19                      F
  20                      P  }]

## Apos

In [14]:
extra_apos_path = "pdb_ensemble"

os.makedirs(extra_apos_path, exist_ok=True)

In [15]:
extra_apos_original_cifs_path = f"{extra_apos_path}/origcifs"
os.makedirs(extra_apos_original_cifs_path, exist_ok=True)

extra_apos_structures_path = f"{extra_apos_path}/cifs"
os.makedirs(extra_apos_structures_path, exist_ok=True)

# extra_apos_pockets_path = f"{extra_apos_path}/pockets"
# os.makedirs(extra_apos_pockets_path, exist_ok=True)

# extra_apos_features_path = extra_apos_path
# os.makedirs(f"{extra_apos_features_path}/features", exist_ok=True)

### Run

In [16]:
Cif.path = "../training_data/7.Extra_set/cifs"
Cif.original_cifs_path = "../training_data/7.Extra_set/origcifs" # <pdb>_updated.cif.gz
Pdb.path = extra_apos_structures_path

In [58]:
def get_extra_apos(pdb):
    pdb = Cif(pdb)
    if "pdbx_sifts_xref_db_acc" not in pdb.residues.columns:
        print(f"{pdb.entry_id}: No Uniprot column in original pdb")
        return []
    
    # protein or others. allo modulators. Ions?
    sites_ups = get_sites_ups(pdb, {i: s for i, s in enumerate(extra_holos_sites[pdb.entry_id])})
    if len(sites_ups) == 0:
        print(f"{pdb.entry_id}: No valid Uniprots in any site")

    return sites_ups
    
    # # Including fix for 8jp0 "P32418-2"
    # ups = list(set(u.replace("-2", "") for sd in sites_ups.values() for u in sd["uniprots"].keys()))
    
    
    # pdbs = False
    # for q in (
    #     rcsb_attributes.rcsb_polymer_entity_container_identifiers.reference_sequence_identifiers.database_accession == up
    #     for up in ups
    # ):
    #     pdbs = q if not pdbs else pdbs & q
    
    # if not pdbs:
    #     print(f"{pdb.entry_id}: No valid Uniprots in any site")
    #     return []
        
    # pdbs = set(i.lower() for i in pdbs()) - set(extra_holos_featuresd.keys())
    # if len(pdbs) == 0: 
    #     print(f"{pdb.entry_id}: No other PDBs of Uniprots")
    #     return []

    # for newpdb in tqdm(pdbs, smoothing=0, desc=pdb.entry_id):
    #     for r in check_pdb(newpdb, pdb, sites_ups, ups):
    #         yield r

In [61]:
test = get_extra_apos("8jp0")

In [62]:
test

{0: {'siteres':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
  0            GLU             A               1          132                 ?
  1            THR             A               1          133                 ?
  2            VAL             A               1          134                 ?
  3            SER             A               1          135                 ?
  4            LEU             A               1          137                 ?
  5            THR             A               1          138                 ?
  6            ALA             A               1          141                 ?
  7            HIS             A               1          200                 ?
  8            VAL             A               1          203                 ?
  9            VAL             A               1          206                 ?
  10           THR             A               1          207                 ?
  11           ALA             A               1          208                 ?
  12           TRP             A               1          210                 ?
  13           SER             A               1          211                 ?
  14           PHE             A               1          241                 ?
  15           ILE             A               1          244                 ?
  16           CYS             A               1          245                 ?
  17           PHE             A               1          248                 ?
  18           ALA             A               1          249                 ?
  19           LEU             A               1          256                 ?
  20           GLU             A               1          279                 ?
  21           ASP             A               1          828                 ?
  22           ALA             A               1          829                 ?
  23           SER             A               1          830                 ?
  24           ILE             A               1          831                 ?
  25           GLY             A               1          832                 ?
  26           ASN             A               1          833                 ?
  27           THR             A               1          835                 ?
  28           GLY             A               1          836                 ?
  29           SER             A               1          837                 ?
  30           ALA             A               1          839                 ?
  31           VAL             A               1          840                 ?

     auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
  0          132          GLU            A                  1              132
  1          133          THR            A                  1              133
  2          134          VAL            A                  1              134
  3          135          SER            A                  1              135
  4          137          LEU            A                  1              137
  5          138          THR            A                  1              138
  6          141          ALA            A                  1              141
  7          200          HIS            A                  1              200
  8          203          VAL            A                  1              203
  9          206          VAL            A                  1              206
  10         207          THR            A                  1              207
  11         208          ALA            A                  1              208
  12         210          TRP            A                  1              210
  13         211          SER            A                  1              211
  14         241          PHE            A                  1              241
  15         244          ILE            A                  1              244
  16         245          CYS            A                  1              245
  17         248          PHE            A                  1              248
  18         249          ALA            A                  1              249
  19         256          LEU            A                  1              256
  20         279          GLU            A                  1              279
  21         828          ASP            A                  1              828
  22         829          ALA            A                  1              829
  23         830          SER            A                  1              830
  24         831          ILE            A                  1              831
  25         832          GLY            A                  1              832
  26         833          ASN            A                  1              833
  27         835          THR            A                  1              835
  28         836          GLY            A                  1              836
  29         837          SER            A                  1              837
  30         839          ALA            A                  1              839
  31         840          VAL            A                  1              840

     pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
  0                      UNP               P32418-2                    132
  1                      UNP               P32418-2                    133
  2                      UNP               P32418-2                    134
  3                      UNP               P32418-2                    135
  4                      UNP               P32418-2                    137
  5                      UNP               P32418-2                    138
  6                      UNP               P32418-2                    141
  7                      UNP               P32418-2                    200
  8                      UNP               P32418-2                    203
  9                      UNP               P32418-2                    206
  10                     UNP               P32418-2                    207
  11                     UNP               P32418-2                    208
  12                     UNP               P32418-2                    210
  13                     UNP               P32418-2                    211
  14                     UNP               P32418-2                    241
  15                     UNP               P32418-2                    244
  16                     UNP               P32418-2                    245
  17                     UNP               P32418-2                    248
  18                     UNP               P32418-2                    249
  19                     UNP               P32418-2                    256
  20                     UNP               P32418-2                    279
  21                     UNP               P32418-2                    828
  22                     UNP               P32418-2                    829
  23                     UNP               P32418-2                    830
  24                     UNP               P32418-2                    831
  25                     UNP               P32418-2                    832
  26                     UNP               P32418-2                    833
  27                     UNP               P32418-2                    835
  28                     UNP               P32418-2                    836
  29                     UNP               P32418-2                    837
  30                     UNP               P32418-2                    839
  31                     UNP               P32418-2                    840

     pdbx_sifts_xref_db_res
  0                       E
  1                       T
  2                       V
  3                       S
  4                       L
  5                       T
  6                       A
  7                       H
  8                       V
  9                       V
  10                      T
  11                      A
  12                      W
  13                      S
  14                      F
  15                      I
  16                      C
  17                      F
  18                      A
  19                      L
  20                      E
  21                      D
  22                      A
  23                      S
  24                      I
  25                      G
  26                      N
  27                      T
  28                      G
  29                      S
  30                      A
  31                      V  ,
  'label_asym_id': ['A'],
  'uniprots': {'P32418-2': {'ulabel_asym_id': ['A'],
    'usiteres':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0            GLU             A               1          132                 ?
    1            THR             A               1          133                 ?
    2            VAL             A               1          134                 ?
    3            SER             A               1          135                 ?
    4            LEU             A               1          137                 ?
    5            THR             A               1          138                 ?
    6            ALA             A               1          141                 ?
    7            HIS             A               1          200                 ?
    8            VAL             A               1          203                 ?
    9            VAL             A               1          206                 ?
    10           THR             A               1          207                 ?
    11           ALA             A               1          208                 ?
    12           TRP             A               1          210                 ?
    13           SER             A               1          211                 ?
    14           PHE             A               1          241                 ?
    15           ILE             A               1          244                 ?
    16           CYS             A               1          245                 ?
    17           PHE             A               1          248                 ?
    18           ALA             A               1          249                 ?
    19           LEU             A               1          256                 ?
    20           GLU             A               1          279                 ?
    21           ASP             A               1          828                 ?
    22           ALA             A               1          829                 ?
    23           SER             A               1          830                 ?
    24           ILE             A               1          831                 ?
    25           GLY             A               1          832                 ?
    26           ASN             A               1          833                 ?
    27           THR             A               1          835                 ?
    28           GLY             A               1          836                 ?
    29           SER             A               1          837                 ?
    30           ALA             A               1          839                 ?
    31           VAL             A               1          840                 ?

       auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0          132          GLU            A                  1              132
    1          133          THR            A                  1              133
    2          134          VAL            A                  1              134
    3          135          SER            A                  1              135
    4          137          LEU            A                  1              137
    5          138          THR            A                  1              138
    6          141          ALA            A                  1              141
    7          200          HIS            A                  1              200
    8          203          VAL            A                  1              203
    9          206          VAL            A                  1              206
    10         207          THR            A                  1              207
    11         208          ALA            A                  1              208
    12         210          TRP            A                  1              210
    13         211          SER            A                  1              211
    14         241          PHE            A                  1              241
    15         244          ILE            A                  1              244
    16         245          CYS            A                  1              245
    17         248          PHE            A                  1              248
    18         249          ALA            A                  1              249
    19         256          LEU            A                  1              256
    20         279          GLU            A                  1              279
    21         828          ASP            A                  1              828
    22         829          ALA            A                  1              829
    23         830          SER            A                  1              830
    24         831          ILE            A                  1              831
    25         832          GLY            A                  1              832
    26         833          ASN            A                  1              833
    27         835          THR            A                  1              835
    28         836          GLY            A                  1              836
    29         837          SER            A                  1              837
    30         839          ALA            A                  1              839
    31         840          VAL            A                  1              840

       pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                      UNP               P32418-2                    132
    1                      UNP               P32418-2                    133
    2                      UNP               P32418-2                    134
    3                      UNP               P32418-2                    135
    4                      UNP               P32418-2                    137
    5                      UNP               P32418-2                    138
    6                      UNP               P32418-2                    141
    7                      UNP               P32418-2                    200
    8                      UNP               P32418-2                    203
    9                      UNP               P32418-2                    206
    10                     UNP               P32418-2                    207
    11                     UNP               P32418-2                    208
    12                     UNP               P32418-2                    210
    13                     UNP               P32418-2                    211
    14                     UNP               P32418-2                    241
    15                     UNP               P32418-2                    244
    16                     UNP               P32418-2                    245
    17                     UNP               P32418-2                    248
    18                     UNP               P32418-2                    249
    19                     UNP               P32418-2                    256
    20                     UNP               P32418-2                    279
    21                     UNP               P32418-2                    828
    22                     UNP               P32418-2                    829
    23                     UNP               P32418-2                    830
    24                     UNP               P32418-2                    831
    25                     UNP               P32418-2                    832
    26                     UNP               P32418-2                    833
    27                     UNP               P32418-2                    835
    28                     UNP               P32418-2                    836
    29                     UNP               P32418-2                    837
    30                     UNP               P32418-2                    839
    31                     UNP               P32418-2                    840

       pdbx_sifts_xref_db_res
    0                       E
    1                       T
    2                       V
    3                       S
    4                       L
    5                       T
    6                       A
    7                       H
    8                       V
    9                       V
    10                      T
    11                      A
    12                      W
    13                      S
    14                      F
    15                      I
    16                      C
    17                      F
    18                      A
    19                      L
    20                      E
    21                      D
    22                      A
    23                      S
    24                      I
    25                      G
    26                      N
    27                      T
    28                      G
    29                      S
    30                      A
    31                      V  ,
    'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
    0              GLY             A               1           51
    4              SER             A               1           52
    10             TYR             A               1           53
    22             TYR             A               1           54
    34             CYS             A               1           55
    ...            ...           ...             ...          ...
    5613           HIS             A               1          933
    5623           ILE             A               1          934
    5631           LYS             A               1          935
    5640           GLY             A               1          936
    5644           PHE             A               1          937

         pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
    0                    ?          51          GLY            A
    4                    ?          52          SER            A
    10                   ?          53          TYR            A
    22                   ?          54          TYR            A
    34                   ?          55          CYS            A
    ...                ...         ...          ...          ...
    5613                 ?         933          HIS            A
    5623                 ?         934          ILE            A
    5631                 ?         935          LYS            A
    5640                 ?         936          GLY            A
    5644                 ?         937          PHE            A

         pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
    0                     1               51                     UNP
    4                     1               52                     UNP
    10                    1               53                     UNP
    22                    1               54                     UNP
    34                    1               55                     UNP
    ...                 ...              ...                     ...
    5613                  1              933                     UNP
    5623                  1              934                     UNP
    5631                  1              935                     UNP

In [64]:
test[0]["siteres"]

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,GLU,A,1,132,?,132,GLU,A,1,132,UNP,P32418-2,132,E
1,THR,A,1,133,?,133,THR,A,1,133,UNP,P32418-2,133,T
2,VAL,A,1,134,?,134,VAL,A,1,134,UNP,P32418-2,134,V
3,SER,A,1,135,?,135,SER,A,1,135,UNP,P32418-2,135,S
4,LEU,A,1,137,?,137,LEU,A,1,137,UNP,P32418-2,137,L
5,THR,A,1,138,?,138,THR,A,1,138,UNP,P32418-2,138,T
6,ALA,A,1,141,?,141,ALA,A,1,141,UNP,P32418-2,141,A
7,HIS,A,1,200,?,200,HIS,A,1,200,UNP,P32418-2,200,H
8,VAL,A,1,203,?,203,VAL,A,1,203,UNP,P32418-2,203,V
9,VAL,A,1,206,?,206,VAL,A,1,206,UNP,P32418-2,206,V
10,THR,A,1,207,?,207,THR,A,1,207,UNP,P32418-2,207,T
11,ALA,A,1,208,?,208,ALA,A,1,208,UNP,P32418-2,208,A
12,TRP,A,1,210,?,210,TRP,A,1,210,UNP,P32418-2,210,W
13,SER,A,1,211,?,211,SER,A,1,211,UNP,P32418-2,211,S
14,PHE,A,1,241,?,241,PHE,A,1,241,UNP,P32418-2,241,F
15,ILE,A,1,244,?,244,ILE,A,1,244,UNP,P32418-2,244,I
16,CYS,A,1,245,?,245,CYS,A,1,245,UNP,P32418-2,245,C
17,PHE,A,1,248,?,248,PHE,A,1,248,UNP,P32418-2,248,F
18,ALA,A,1,249,?,249,ALA,A,1,249,UNP,P32418-2,249,A
19,LEU,A,1,256,?,256,LEU,A,1,256,UNP,P32418-2,256,L
20,GLU,A,1,279,?,279,GLU,A,1,279,UNP,P32418-2,279,E
21,ASP,A,1,828,?,828,ASP,A,1,828,UNP,P32418-2,828,D
22,ALA,A,1,829,?,829,ALA,A,1,829,UNP,P32418-2,829,A
23,SER,A,1,830,?,830,SER,A,1,830,UNP,P32418-2,830,S
24,ILE,A,1,831,?,831,ILE,A,1,831,UNP,P32418-2,831,I
25,GLY,A,1,832,?,832,GLY,A,1,832,UNP,P32418-2,832,G
26,ASN,A,1,833,?,833,ASN,A,1,833,UNP,P32418-2,833,N
27,THR,A,1,835,?,835,THR,A,1,835,UNP,P32418-2,835,T
28,GLY,A,1,836,?,836,GLY,A,1,836,UNP,P32418-2,836,G
29,SER,A,1,837,?,837,SER,A,1,837,UNP,P32418-2,837,S
30,ALA,A,1,839,?,839,ALA,A,1,839,UNP,P32418-2,839,A
31,VAL,A,1,840,?,840,VAL,A,1,840,UNP,P32418-2,840,V

In [67]:
test[0]["uniprots"].keys()

dict_keys(['P32418-2'])

In [72]:
test[0]["uniprots"]["P32418-2"]["usiteres"].replace({"pdbx_sifts_xref_db_acc": {"P32418-2": "P32418"}})

,label_comp_id,label_asym_id,label_entity_id,label_seq_id,pdbx_PDB_ins_code,auth_seq_id,auth_comp_id,auth_asym_id,pdbx_PDB_model_num,pdbx_label_index,pdbx_sifts_xref_db_name,pdbx_sifts_xref_db_acc,pdbx_sifts_xref_db_num,pdbx_sifts_xref_db_res
0,GLU,A,1,132,?,132,GLU,A,1,132,UNP,P32418,132,E
1,THR,A,1,133,?,133,THR,A,1,133,UNP,P32418,133,T
2,VAL,A,1,134,?,134,VAL,A,1,134,UNP,P32418,134,V
3,SER,A,1,135,?,135,SER,A,1,135,UNP,P32418,135,S
4,LEU,A,1,137,?,137,LEU,A,1,137,UNP,P32418,137,L
5,THR,A,1,138,?,138,THR,A,1,138,UNP,P32418,138,T
6,ALA,A,1,141,?,141,ALA,A,1,141,UNP,P32418,141,A
7,HIS,A,1,200,?,200,HIS,A,1,200,UNP,P32418,200,H
8,VAL,A,1,203,?,203,VAL,A,1,203,UNP,P32418,203,V
9,VAL,A,1,206,?,206,VAL,A,1,206,UNP,P32418,206,V
10,THR,A,1,207,?,207,THR,A,1,207,UNP,P32418,207,T
11,ALA,A,1,208,?,208,ALA,A,1,208,UNP,P32418,208,A
12,TRP,A,1,210,?,210,TRP,A,1,210,UNP,P32418,210,W
13,SER,A,1,211,?,211,SER,A,1,211,UNP,P32418,211,S
14,PHE,A,1,241,?,241,PHE,A,1,241,UNP,P32418,241,F
15,ILE,A,1,244,?,244,ILE,A,1,244,UNP,P32418,244,I
16,CYS,A,1,245,?,245,CYS,A,1,245,UNP,P32418,245,C
17,PHE,A,1,248,?,248,PHE,A,1,248,UNP,P32418,248,F
18,ALA,A,1,249,?,249,ALA,A,1,249,UNP,P32418,249,A
19,LEU,A,1,256,?,256,LEU,A,1,256,UNP,P32418,256,L
20,GLU,A,1,279,?,279,GLU,A,1,279,UNP,P32418,279,E
21,ASP,A,1,828,?,828,ASP,A,1,828,UNP,P32418,828,D
22,ALA,A,1,829,?,829,ALA,A,1,829,UNP,P32418,829,A
23,SER,A,1,830,?,830,SER,A,1,830,UNP,P32418,830,S
24,ILE,A,1,831,?,831,ILE,A,1,831,UNP,P32418,831,I
25,GLY,A,1,832,?,832,GLY,A,1,832,UNP,P32418,832,G
26,ASN,A,1,833,?,833,ASN,A,1,833,UNP,P32418,833,N
27,THR,A,1,835,?,835,THR,A,1,835,UNP,P32418,835,T
28,GLY,A,1,836,?,836,GLY,A,1,836,UNP,P32418,836,G
29,SER,A,1,837,?,837,SER,A,1,837,UNP,P32418,837,S
30,ALA,A,1,839,?,839,ALA,A,1,839,UNP,P32418,839,A
31,VAL,A,1,840,?,840,VAL,A,1,840,UNP,P32418,840,V

In [43]:
extra_matchesf = f"{extra_apos_path}/matches.pkl"

In [44]:
extra_df = pd.DataFrame(columns=pd.MultiIndex.from_tuples(
    (('allodb', 'pdb'), ('allodb', 'site_id'), ('allodb', 'label_asym_id'), ('allodb', 'mod'), ('allodb', 'uniprot'), ('allodb', 'ulabel_asym_id'), ('allodb', 'usiteres'), ('allodb', 'umin'), ('allodb', 'umax'), ('apo', 'pdb'), ('apo', 'label_asym_id'), ('apo', 'site'), ('apo', 'siteres'), ('apo', 'ligands'), ('apo', 'any_apo_chain'), ('apo', 'umin'), ('apo', 'umax'), ('apo', 'usite'), ('overlap', 'a_in_h_minmax'), ('overlap', 'h_in_a_minmax'), ('overlap', 'a_in_h_merge'), ('overlap', 'h_in_a_merge'))
))

In [45]:
# Retrieve processed elements from the DataFrame
extra_processed = extra_df[("allodb", "pdb")].unique().tolist()

In [21]:
# Load the existing DataFrame if it exists
if os.path.exists(extra_matchesf):
    extra_df = pd.read_pickle(extra_matchesf)
    extra_processed.extend(extra_df[("allodb", "pdb")].unique().tolist())

In [46]:
# Process the reps keys in chunks
for p in ["8jp0",]:
    if p not in extra_processed:
        p_df = pd.DataFrame(get_extra_apos(p))
        if len(p_df):
            p_df.columns = pd.MultiIndex.from_tuples(p_df.columns)
            extra_df = pd.concat([extra_df, p_df])
            extra_df.to_pickle(extra_matchesf)
        extra_processed.append(p)

{0: {'siteres':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
0            GLU             A               1          132                 ?
1            THR             A               1          133                 ?
2            VAL             A               1          134                 ?
3            SER             A               1          135                 ?
4            LEU             A               1          137                 ?
5            THR             A               1          138                 ?
6            ALA             A               1          141                 ?
7            HIS             A               1          200                 ?
8            VAL             A               1          203                 ?
9            VAL             A               1          206                 ?
10           THR             A               1          207                 ?
11           ALA             A               1          208                 ?
12           TRP             A               1          210                 ?
13           SER             A               1          211                 ?
14           PHE             A               1          241                 ?
15           ILE             A               1          244                 ?
16           CYS             A               1          245                 ?
17           PHE             A               1          248                 ?
18           ALA             A               1          249                 ?
19           LEU             A               1          256                 ?
20           GLU             A               1          279                 ?
21           ASP             A               1          828                 ?
22           ALA             A               1          829                 ?
23           SER             A               1          830                 ?
24           ILE             A               1          831                 ?
25           GLY             A               1          832                 ?
26           ASN             A               1          833                 ?
27           THR             A               1          835                 ?
28           GLY             A               1          836                 ?
29           SER             A               1          837                 ?
30           ALA             A               1          839                 ?
31           VAL             A               1          840                 ?

   auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
0          132          GLU            A                  1              132
1          133          THR            A                  1              133
2          134          VAL            A                  1              134
3          135          SER            A                  1              135
4          137          LEU            A                  1              137
5          138          THR            A                  1              138
6          141          ALA            A                  1              141
7          200          HIS            A                  1              200
8          203          VAL            A                  1              203
9          206          VAL            A                  1              206
10         207          THR            A                  1              207
11         208          ALA            A                  1              208
12         210          TRP            A                  1              210
13         211          SER            A                  1              211
14         241          PHE            A                  1              241
15         244          ILE            A                  1              244
16         245          CYS            A                  1              245
17         248          PHE            A                  1              248
18         249          ALA            A                  1              249
19         256          LEU            A                  1              256
20         279          GLU            A                  1              279
21         828          ASP            A                  1              828
22         829          ALA            A                  1              829
23         830          SER            A                  1              830
24         831          ILE            A                  1              831
25         832          GLY            A                  1              832
26         833          ASN            A                  1              833
27         835          THR            A                  1              835
28         836          GLY            A                  1              836
29         837          SER            A                  1              837
30         839          ALA            A                  1              839
31         840          VAL            A                  1              840

   pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
0                      UNP               P32418-2                    132
1                      UNP               P32418-2                    133
2                      UNP               P32418-2                    134
3                      UNP               P32418-2                    135
4                      UNP               P32418-2                    137
5                      UNP               P32418-2                    138
6                      UNP               P32418-2                    141
7                      UNP               P32418-2                    200
8                      UNP               P32418-2                    203
9                      UNP               P32418-2                    206
10                     UNP               P32418-2                    207
11                     UNP               P32418-2                    208
12                     UNP               P32418-2                    210
13                     UNP               P32418-2                    211
14                     UNP               P32418-2                    241
15                     UNP               P32418-2                    244
16                     UNP               P32418-2                    245
17                     UNP               P32418-2                    248
18                     UNP               P32418-2                    249
19                     UNP               P32418-2                    256
20                     UNP               P32418-2                    279
21                     UNP               P32418-2                    828
22                     UNP               P32418-2                    829
23                     UNP               P32418-2                    830
24                     UNP               P32418-2                    831
25                     UNP               P32418-2                    832
26                     UNP               P32418-2                    833
27                     UNP               P32418-2                    835
28                     UNP               P32418-2                    836
29                     UNP               P32418-2                    837
30                     UNP               P32418-2                    839
31                     UNP               P32418-2                    840

   pdbx_sifts_xref_db_res
0                       E
1                       T
2                       V
3                       S
4                       L
5                       T
6                       A
7                       H
8                       V
9                       V
10                      T
11                      A
12                      W
13                      S
14                      F
15                      I
16                      C
17                      F
18                      A
19                      L
20                      E
21                      D
22                      A
23                      S
24                      I
25                      G
26                      N
27                      T
28                      G
29                      S
30                      A
31                      V  , 'label_asym_id': ['A'], 'uniprots': {'P32418-2': {'ulabel_asym_id': ['A'], 'usiteres':    label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
0            GLU             A               1          132                 ?
1            THR             A               1          133                 ?
2            VAL             A               1          134                 ?
3            SER             A               1          135                 ?
4            LEU             A               1          137                 ?
5            THR             A               1          138                 ?
6            ALA             A               1          141                 ?
7            HIS             A               1          200                 ?
8            VAL             A               1          203                 ?
9            VAL             A               1          206                 ?
10           THR             A               1          207                 ?
11           ALA             A               1          208                 ?
12           TRP             A               1          210                 ?
13           SER             A               1          211                 ?
14           PHE             A               1          241                 ?
15           ILE             A               1          244                 ?
16           CYS             A               1          245                 ?
17           PHE             A               1          248                 ?
18           ALA             A               1          249                 ?
19           LEU             A               1          256                 ?
20           GLU             A               1          279                 ?
21           ASP             A               1          828                 ?
22           ALA             A               1          829                 ?
23           SER             A               1          830                 ?
24           ILE             A               1          831                 ?
25           GLY             A               1          832                 ?
26           ASN             A               1          833                 ?
27           THR             A               1          835                 ?
28           GLY             A               1          836                 ?
29           SER             A               1          837                 ?
30           ALA             A               1          839                 ?
31           VAL             A               1          840                 ?

   auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
0          132          GLU            A                  1              132
1          133          THR            A                  1              133
2          134          VAL            A                  1              134
3          135          SER            A                  1              135
4          137          LEU            A                  1              137
5          138          THR            A                  1              138
6          141          ALA            A                  1              141
7          200          HIS            A                  1              200
8          203          VAL            A                  1              203
9          206          VAL            A                  1              206
10         207          THR            A                  1              207
11         208          ALA            A                  1              208
12         210          TRP            A                  1              210
13         211          SER            A                  1              211
14         241          PHE            A                  1              241
15         244          ILE            A                  1              244
16         245          CYS            A                  1              245
17         248          PHE            A                  1              248
18         249          ALA            A                  1              249
19         256          LEU            A                  1              256
20         279          GLU            A                  1              279
21         828          ASP            A                  1              828
22         829          ALA            A                  1              829
23         830          SER            A                  1              830
24         831          ILE            A                  1              831
25         832          GLY            A                  1              832
26         833          ASN            A                  1              833
27         835          THR            A                  1              835
28         836          GLY            A                  1              836
29         837          SER            A                  1              837
30         839          ALA            A                  1              839
31         840          VAL            A                  1              840

   pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
0                      UNP               P32418-2                    132
1                      UNP               P32418-2                    133
2                      UNP               P32418-2                    134
3                      UNP               P32418-2                    135
4                      UNP               P32418-2                    137
5                      UNP               P32418-2                    138
6                      UNP               P32418-2                    141
7                      UNP               P32418-2                    200
8                      UNP               P32418-2                    203
9                      UNP               P32418-2                    206
10                     UNP               P32418-2                    207
11                     UNP               P32418-2                    208
12                     UNP               P32418-2                    210
13                     UNP               P32418-2                    211
14                     UNP               P32418-2                    241
15                     UNP               P32418-2                    244
16                     UNP               P32418-2                    245
17                     UNP               P32418-2                    248
18                     UNP               P32418-2                    249
19                     UNP               P32418-2                    256
20                     UNP               P32418-2                    279
21                     UNP               P32418-2                    828
22                     UNP               P32418-2                    829
23                     UNP               P32418-2                    830
24                     UNP               P32418-2                    831
25                     UNP               P32418-2                    832
26                     UNP               P32418-2                    833
27                     UNP               P32418-2                    835
28                     UNP               P32418-2                    836
29                     UNP               P32418-2                    837
30                     UNP               P32418-2                    839
31                     UNP               P32418-2                    840

   pdbx_sifts_xref_db_res
0                       E
1                       T
2                       V
3                       S
4                       L
5                       T
6                       A
7                       H
8                       V
9                       V
10                      T
11                      A
12                      W
13                      S
14                      F
15                      I
16                      C
17                      F
18                      A
19                      L
20                      E
21                      D
22                      A
23                      S
24                      I
25                      G
26                      N
27                      T
28                      G
29                      S
30                      A
31                      V  , 'ures':      label_comp_id label_asym_id label_entity_id label_seq_id  \
0              GLY             A               1           51
4              SER             A               1           52
10             TYR             A               1           53
22             TYR             A               1           54
34             CYS             A               1           55
...            ...           ...             ...          ...
5613           HIS             A               1          933
5623           ILE             A               1          934
5631           LYS             A               1          935
5640           GLY             A               1          936
5644           PHE             A               1          937

     pdbx_PDB_ins_code auth_seq_id auth_comp_id auth_asym_id  \
0                    ?          51          GLY            A
4                    ?          52          SER            A
10                   ?          53          TYR            A
22                   ?          54          TYR            A
34                   ?          55          CYS            A
...                ...         ...          ...          ...
5613                 ?         933          HIS            A
5623                 ?         934          ILE            A
5631                 ?         935          LYS            A
5640                 ?         936          GLY            A
5644                 ?         937          PHE            A

     pdbx_PDB_model_num pdbx_label_index pdbx_sifts_xref_db_name  \
0                     1               51                     UNP
4                     1               52                     UNP
10                    1               53                     UNP
22                    1               54                     UNP
34                    1               55                     UNP
...                 ...              ...                     ...
5613                  1              933                     UNP
5623                  1              934                     UNP
5631                  1              935                     UNP
5640                  1              936                     UNP
5644                  1              937                     UNP

     pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num pdbx_sifts_xref_db_res
0                  P32418-2                     51                      G
4                  P32418-2                     52                      S
10                 P32418-2                     53                      Y
22                 P32418-2                     54                      Y
34                 P32418-2                     55                      C
...                     ...                    ...                    ...
5613               P32418-2                    933                      H
5623               P32418-2                    934                      I
5631               P32418-2                    935                      K
5640               P32418-2                    936                      G

8jp0:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
sites_ups[0]

In [29]:
extra_df

Empty DataFrame
Columns: [(allodb, pdb), (allodb, site_id), (allodb, label_asym_id), (allodb, mod), (allodb, uniprot), (allodb, ulabel_asym_id), (allodb, usiteres), (allodb, umin), (allodb, umax), (apo, pdb), (apo, label_asym_id), (apo, site), (apo, siteres), (apo, ligands), (apo, any_apo_chain), (apo, umin), (apo, umax), (apo, usite), (overlap, a_in_h_minmax), (overlap, h_in_a_minmax), (overlap, a_in_h_merge), (overlap, h_in_a_merge)]
Index: []

[0 rows x 22 columns]

In [30]:
# Process the reps keys in chunks
for p in tqdm(extra_holos_featuresd, smoothing=0):
    if p not in extra_processed:
        p_df = pd.DataFrame(get_extra_apos(p))
        if len(p_df):
            p_df.columns = pd.MultiIndex.from_tuples(p_df.columns)
            extra_df = pd.concat([extra_df, p_df])
            extra_df.to_pickle(extra_matchesf)
        extra_processed.append(p)

  0%|          | 0/8 [00:00<?, ?it/s]

7gqu:   0%|          | 0/21 [00:00<?, ?it/s]

/tmp/ipykernel_172997/2230244043.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  extra_df = pd.concat([extra_df, p_df])

7yg5:   0%|          | 0/4 [00:00<?, ?it/s]

8aq6:   0%|          | 0/20 [00:00<?, ?it/s]

8f4s:   0%|          | 0/3022 [00:00<?, ?it/s]

8jp0:   0%|          | 0/4 [00:00<?, ?it/s]

8qni:   0%|          | 0/23 [00:00<?, ?it/s]

8v81:   0%|          | 0/57 [00:00<?, ?it/s]

9dnm:   0%|          | 0/15 [00:00<?, ?it/s]

extra_apos = {}
extra_apos_sites = {}

## Analysis

In [21]:
extra_df = extra_df.reset_index(drop=True)
extra_df

    allodb                                                    \
       pdb site_id label_asym_id  mod uniprot ulabel_asym_id
0     7gqu       0           [A]  [D]  Q14191            [A]
1     7gqu       0           [A]  [D]  Q14191            [A]
2     7gqu       0           [A]  [D]  Q14191            [A]
3     7gqu       0           [A]  [D]  Q14191            [A]
4     7gqu       0           [A]  [D]  Q14191            [A]
..     ...     ...           ...  ...     ...            ...
141   9dnm       0           [C]  [D]  P29066            [C]
142   9dnm       0           [C]  [D]  P29066            [C]
143   9dnm       0           [C]  [D]  P29066            [C]
144   9dnm       0           [C]  [D]  P29066            [C]
145   9dnm       0           [C]  [D]  P29066            [C]

                                                                   apo  ...  \
                                              usiteres umin umax   pdb  ...
0       label_comp_id label_asym_id label_entity_id...  527  945  7gqt  ...
1       label_comp_id label_asym_id label_entity_id...  527  945  9og3  ...
2       label_comp_id label_asym_id label_entity_id...  527  945  8yle  ...
3       label_comp_id label_asym_id label_entity_id...  527  945  9og8  ...
4       label_comp_id label_asym_id label_entity_id...  527  945  6yhr  ...
..                                                 ...  ...  ...   ...  ...
141    label_comp_id label_asym_id label_entity_id ...    6  391  8i0n  ...
142    label_comp_id label_asym_id label_entity_id ...    6  391  9bt8  ...
143    label_comp_id label_asym_id label_entity_id ...    6  391  8go8  ...
144    label_comp_id label_asym_id label_entity_id ...    6  391  9cx3  ...
145    label_comp_id label_asym_id label_entity_id ...    6  391  8hsv  ...

                                                                           \
                                               ligands any_apo_chain umin
0                   {'A': {('apo', 'has_lig'): False}}          True  527
1    {'A': {('apo', 'has_lig'): True, ('apo', 'lig_...         False  526
2                   {'A': {('apo', 'has_lig'): False}}          True  526
3    {'A': {('apo', 'has_lig'): True, ('apo', 'lig_...         False  526
4                   {'A': {('apo', 'has_lig'): False}}          True  528
..                                                 ...           ...  ...
141  {'A': {('apo', 'has_lig'): True, ('apo', 'lig_...         False    7
142                 {'E': {('apo', 'has_lig'): False}}          True    6
143  {'A': {('apo', 'has_lig'): True, ('apo', 'lig_...         False    7
144                 {'E': {('apo', 'has_lig'): False}}          True    6
145  {'A': {('apo', 'has_lig'): False}, 'C': {('apo...          True    4

                      overlap                                          \
     umax usite a_in_h_minmax h_in_a_minmax a_in_h_merge h_in_a_merge
0     945   1.0      1.000000      1.000000     1.000000     0.988067
1     946   1.0      0.995249      1.000000     0.995157     0.980907
2     945   1.0      0.997619      1.000000     0.997596     0.990453
3     946   1.0      0.995249      1.000000     0.995227     0.995227
4    1072   1.0      0.766972      0.997613     0.772643     0.997613
..    ...   ...           ...           ...          ...          ...
141   368   1.0      1.000000      0.937824     0.886740     0.975684
142   356   1.0      1.000000      0.909326     0.944785     0.936170
143   368   1.0      1.000000      0.937824     0.886740     0.975684
144   356   1.0      1.000000      0.909326     0.953560     0.936170
145   394   1.0      0.987212      1.000000     0.906336     1.000000

                                                allodb
                                               siteres
0       label_comp_id label_asym_id label_entity_id...
1       label_comp_id label_asym_id label_entity_id...
2       label_comp_id label_asym_id label_entity_id...
3       label_comp_id label_asym_id label_entity_id...
4       label_comp_id label_asym_id label_entity_id...
..                                                 ...
141    label_comp_id label_asym_id label_entity_id ...
142    label_comp_id label_asym_id label_entity_id ...
143    label_comp_id label_asym_id label_entity_id ...
144    label_comp_id label_asym_id label_entity_id ...
145    label_comp_id label_asym_id label_entity_id ...

[146 rows x 23 columns]

In [22]:
len(extra_df[("allodb", "pdb")].unique())

7

##### No site overlap

In [23]:
set(
    extra_df[("allodb", "pdb")].unique()
) - set(
    extra_df[extra_df[("apo", "site")] >= 0.8][("allodb", "pdb")].unique()
)

set()

In [24]:
extra_df[("allodb", "pdb")].value_counts(), \
extra_df[extra_df[("apo", "site")] >= 0.8][("allodb", "pdb")].value_counts()

((allodb, pdb)
 8f4s    71
 8v81    21
 8qni    16
 9dnm    15
 8aq6    11
 7gqu     9
 7yg5     3
 Name: count, dtype: int64,
 (allodb, pdb)
 8f4s    71
 8v81    21
 9dnm    15
 8aq6    11
 8qni    11
 7gqu     9
 7yg5     3
 Name: count, dtype: int64)

##### 8qni

In [28]:
(
    extra_df[extra_df[("allodb", "pdb")] == "8qni"]
    .drop(columns=[("allodb", "usiteres"), ("allodb", "siteres"), ("apo", "siteres"), ("apo", "ligands"),])
    .sort_values(("apo", "site"))
)

    allodb                                                               apo  \
       pdb site_id label_asym_id  mod uniprot ulabel_asym_id umin umax   pdb
108   8qni       0           [A]  [B]  Q13191            [A]   38  420  2ldr
95    8qni       0           [A]  [B]  Q13191            [A]   38  420  8vw4
98    8qni       0           [A]  [B]  Q13191            [A]   38  420  3vgo
97    8qni       0           [A]  [B]  Q13191            [A]   38  420  3pfv
103   8qni       0           [A]  [B]  Q13191            [A]   38  420  8vw5
99    8qni       0           [A]  [B]  Q13191            [A]   38  420  8gcy
96    8qni       0           [A]  [B]  Q13191            [A]   38  420  8qtj
94    8qni       0           [A]  [B]  Q13191            [A]   38  420  9fqi
101   8qni       0           [A]  [B]  Q13191            [A]   38  420  9fqj
100   8qni       0           [A]  [B]  Q13191            [A]   38  420  3zni
104   8qni       0           [A]  [B]  Q13191            [A]   38  420  9fqh
102   8qni       0           [A]  [B]  Q13191            [A]   38  420  8qtg
105   8qni       0           [A]  [B]  Q13191            [A]   38  420  8qtk
106   8qni       0           [A]  [B]  Q13191            [A]   38  420  8qng
107   8qni       0           [A]  [B]  Q13191            [A]   38  420  8qth
109   8qni       0           [A]  [B]  Q13191            [A]   38  420  8qnh

                                                            overlap  \
    label_asym_id  site any_apo_chain umin umax usite a_in_h_minmax
108           [A]  0.23          True  351  426  0.23      0.921053
95            [A]  0.77         False   38  341  0.77      1.000000
98            [A]  0.77          True   43  339  0.77      1.000000
97            [A]  0.77          True   44  344  0.77      1.000000
103           [A]  0.77          True   38  341  0.77      1.000000
99            [A]  1.00         False   38  427  1.00      0.982051
96            [A]  1.00         False   37  427  1.00      0.979540
94            [A]  1.00         False   37  427  1.00      0.979540
101           [A]  1.00         False   37  427  1.00      0.979540
100           [A]  1.00         False   38  427  1.00      0.982051
104           [A]  1.00         False   37  427  1.00      0.979540
102           [A]  1.00         False   37  427  1.00      0.979540
105           [A]  1.00         False   37  427  1.00      0.979540
106           [A]  1.00         False   38  427  1.00      0.982051
107           [A]  1.00         False   37  427  1.00      0.979540
109           [A]  1.00         False   37  427  1.00      0.979540


    h_in_a_minmax a_in_h_merge h_in_a_merge
108      0.182768     0.881579     0.177719
95       0.793734     1.000000     0.806366
98       0.775457     1.000000     0.761273
97       0.785901     1.000000     0.798408
103      0.793734     1.000000     0.806366
99       1.000000     0.981333     0.976127
96       1.000000     0.979167     0.997347
94       1.000000     0.979167     0.997347
101      1.000000     0.979167     0.997347
100      1.000000     0.966667     1.000000
104      1.000000     0.979167     0.997347
102      1.000000     0.979167     0.997347
105      1.000000     0.979167     0.997347
106      1.000000     0.981771     1.000000
107      1.000000     0.976684     1.000000
109      1.000000     0.979167     0.997347

0.77 site presence in the apo is also acceptable. **Some of the PDBs have h_in_a overlap of less than 0.8, and will be taken into account in the next step**

<br>

In [29]:
extra_df[("allodb", "pdb")].value_counts(), \
extra_df[extra_df[("apo", "site")] >= 0.77][("allodb", "pdb")].value_counts()

((allodb, pdb)
 8f4s    71
 8v81    21
 8qni    16
 9dnm    15
 8aq6    11
 7gqu     9
 7yg5     3
 Name: count, dtype: int64,
 (allodb, pdb)
 8f4s    71
 8v81    21
 8qni    15
 9dnm    15
 8aq6    11
 7gqu     9
 7yg5     3
 Name: count, dtype: int64)

In [30]:
extra_filt_df = extra_df[extra_df[("apo", "site")] >= 0.77]

##### No chain overlap

In [33]:
# No chain overlap
## Checked with the % of the holo residues inside the apo because we can use bigger structures, and "cut" the extra part
set(
    extra_filt_df[("allodb", "pdb")].unique()
) - set(
    extra_filt_df[extra_filt_df[("overlap", "h_in_a_merge")] >= 0.76][("allodb", "pdb")].unique()
)

set()

In [34]:
extra_filt_df[("allodb", "pdb")].value_counts(), \
extra_filt_df[extra_filt_df[("overlap", "h_in_a_merge")] >= 0.76][("allodb", "pdb")].value_counts()

((allodb, pdb)
 8f4s    71
 8v81    21
 8qni    15
 9dnm    15
 8aq6    11
 7gqu     9
 7yg5     3
 Name: count, dtype: int64,
 (allodb, pdb)
 8f4s    71
 8v81    21
 8qni    15
 9dnm    15
 8aq6    11
 7gqu     9
 7yg5     2
 Name: count, dtype: int64)

##### 7yg5

In [35]:
(
    extra_filt_df[extra_filt_df[("allodb", "pdb")] == "7yg5"]
    .drop(columns=[("allodb", "usiteres"), ("allodb", "siteres"), ("apo", "siteres"), ("apo", "ligands"),])
)

   allodb                                                                apo  \
      pdb site_id label_asym_id  mod uniprot ulabel_asym_id umin  umax   pdb
9    7yg5       0           [A]  [V]  Q15878            [A]   76  1871  8epm
10   7yg5       0           [A]  [V]  Q15878            [A]   76  1871  7xlq
11   7yg5       0           [A]  [V]  Q15878            [A]   76  1871  8epl

                                                            overlap  \
   label_asym_id  site any_apo_chain umin  umax usite a_in_h_minmax
9            [A]  0.86          True   89  1730  0.86           1.0
10           [A]  1.00          True   76  1871  1.00           1.0
11           [A]  1.00          True   85  1851  1.00           1.0


   h_in_a_minmax a_in_h_merge h_in_a_merge
9       0.914254     0.996973     0.749052
10      1.000000     1.000000     1.000000
11      0.983853     0.986656     0.952995

The 8epm will also be a valid apo.

<br>

In [36]:
extra_filt_df = extra_filt_df[extra_filt_df[("overlap", "h_in_a_merge")] >= 0.74]

extra_filt_df = pd.concat((
    extra_filt_df[extra_filt_df[("overlap", "h_in_a_merge")] >= 0.8],
    extra_filt_df[(extra_filt_df[("allodb", "pdb")] == "7yg5") & (extra_filt_df[("apo", "pdb")] == "8epm")]
))

##### No apos

In [37]:
set(
    extra_filt_df[("allodb", "pdb")].unique()
) - set(
    extra_filt_df[extra_filt_df[("apo", "any_apo_chain")] == True][("allodb", "pdb")].unique()
)

set()

In [38]:
extra_filt_df[("allodb", "pdb")].value_counts(), \
extra_filt_df[extra_filt_df[("apo", "any_apo_chain")] == True][("allodb", "pdb")].value_counts()

((allodb, pdb)
 8f4s    71
 8v81    21
 8qni    15
 9dnm    15
 8aq6    11
 7gqu     9
 7yg5     3
 Name: count, dtype: int64,
 (allodb, pdb)
 8f4s    57
 8v81    19
 9dnm    11
 8aq6     9
 7gqu     5
 7yg5     3
 8qni     3
 Name: count, dtype: int64)

In [39]:
(
    extra_filt_df[ extra_filt_df[("apo", "any_apo_chain")] == False ]
    .drop(columns=[("allodb", "usiteres"), ("allodb", "siteres"), ("apo", "siteres"),])
    .sort_values([("allodb", "pdb")], ascending=False)
    [[("allodb", "pdb"), ("apo", "pdb"), ("apo", "ligands")]]
    .to_dict(orient="records")
)

[{('allodb', 'pdb'): '9dnm',
  ('apo', 'pdb'): '8go8',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    1           LEU             C               1          335                 ?
    2           ASP             C               1          337                 ?
    3           LEU             C               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    1         335          LEU            B                  1              335
    2         337          ASP            B                  1              337
    3         338          LEU            B                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    1                     UNP                 P29066                    335
    2                     UNP                 P29066                    337
    3                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    1                      L
    2                      D
    3                      L  }, 'C': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           LEU             A               1          335                 ?
    1           ASP             A               1          337                 ?
    2           LEU             A               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         335          LEU            A                  1              335
    1         337          ASP            A                  1              337
    2         338          LEU            A                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                     UNP                 P29066                    335
    1                     UNP                 P29066                    337
    2                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    0                      L
    1                      D
    2                      L  }}},
 {('allodb', 'pdb'): '9dnm',
  ('apo', 'pdb'): '8i0n',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    1           LEU             B               1          335                 ?
    2           ASP             B               1          337                 ?
    3           LEU             B               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    1         335          LEU            B                  1              335
    2         337          ASP            B                  1              337
    3         338          LEU            B                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    1                     UNP                 P29066                    335
    2                     UNP                 P29066                    337
    3                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    1                      L
    2                      D
    3                      L  }, 'B': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           LEU             A               1          335                 ?
    1           ASP             A               1          337                 ?
    2           LEU             A               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         335          LEU            A                  1              335
    1         337          ASP            A                  1              337
    2         338          LEU            A                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                     UNP                 P29066                    335
    1                     UNP                 P29066                    337
    2                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    0                      L
    1                      D
    2                      L  }}},
 {('allodb', 'pdb'): '9dnm',
  ('apo', 'pdb'): '8i0q',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    1           LEU             B               1          335                 ?
    2           ASP             B               1          337                 ?
    3           LEU             B               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    1         335          LEU            B                  1              335
    2         337          ASP            B                  1              337
    3         338          LEU            B                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    1                     UNP                 P29066                    335
    2                     UNP                 P29066                    337
    3                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    1                      L
    2                      D
    3                      L  }, 'B': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           LEU             A               1          335                 ?
    1           ASP             A               1          337                 ?
    2           LEU             A               1          338                 ?
    3           ALA             A               1          339                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         335          LEU            A                  1              335
    1         337          ASP            A                  1              337
    2         338          LEU            A                  1              338
    3         339          ALA            A                  1              339

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                     UNP                 P29066                    335
    1                     UNP                 P29066                    337
    2                     UNP                 P29066                    338
    3                     UNP                 P29066                    339

      pdbx_sifts_xref_db_res
    0                      L
    1                      D
    2                      L
    3                      A  }}},
 {('allodb', 'pdb'): '9dnm',
  ('apo', 'pdb'): '8gp3',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    1           LEU             C               1          335                 ?
    2           ASP             C               1          337                 ?
    3           LEU             C               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    1         335          LEU            B                  1              335
    2         337          ASP            B                  1              337
    3         338          LEU            B                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    1                     UNP                 P29066                    335
    2                     UNP                 P29066                    337
    3                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    1                      L
    2                      D
    3                      L  }, 'C': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           LEU             A               1          335                 ?
    1           ASP             A               1          337                 ?
    2           LEU             A               1          338                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         335          LEU            A                  1              335
    1         337          ASP            A                  1              337
    2         338          LEU            A                  1              338

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                     UNP                 P29066                    335
    1                     UNP                 P29066                    337
    2                     UNP                 P29066                    338

      pdbx_sifts_xref_db_res
    0                      L
    1                      D
    2                      L  }}},
 {('allodb', 'pdb'): '8v81',
  ('apo', 'pdb'): '8ubr',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           WG5             I               6            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0        1508          WG5            A                  1             1508

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8v81',
  ('apo', 'pdb'): '9mxl',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0         A1BUJ             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0        1501        A1BUJ            B                  1             1501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8qtg',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           WUQ             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501          WUQ            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8qtj',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           WUI             E               4            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         504          WUI            A                  1              504

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8gcy',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           Z3N             D               3            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         503          Z3N            A                  1              503

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '3zni',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    8           EDO             T               7            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    8        1431          EDO            A                  1             1431

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    8                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    8                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '9fqj',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0         A1IE5             C               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501        A1IE5            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8qng',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           W89             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501          W89            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '9fqh',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0         A1IEW             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501        A1IEW            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8qtk',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           WX9             E               4            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         504          WX9            A                  1              504

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '9fqi',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0         A1IEV             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501        A1IEV            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8qth',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           WX0             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501          WX0            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8qnh',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           Z3N             B               2            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \
    0         501          Z3N            A                  1              501

      pdbx_sifts_xref_db_name pdbx_sifts_xref_db_acc pdbx_sifts_xref_db_num  \
    0                       ?                      ?                      ?

      pdbx_sifts_xref_db_res
    0                      ?  }}},
 {('allodb', 'pdb'): '8qni',
  ('apo', 'pdb'): '8vw4',
  ('apo',
   'ligands'): {'A': {('apo', 'has_lig'): True,
    ('apo', 'lig_types'): ['non-polymer'],
    ('apo',
     'lig'):   label_comp_id label_asym_id label_entity_id label_seq_id pdbx_PDB_ins_code  \
    0           GOL             F               4            .                 ?
    1           GOL             G               4            .                 ?

      auth_seq_id auth_comp_id auth_asym_id pdbx_PDB_model_num pdbx_label_index  \

- The ones from 9dnm are all to be considered apo, they just have a crystal contact.
- From 8v81: not mod-free
- From 8qni, 3zni and 8vw4 only have co-crystallization molecules
- From 8f4s, 8ov3, 8bsd, 9eml, 9gue, 9gny, 8ov4, 9guy, 8ov1, 8bzv, 9q8h, 9grp, 8oto, 8ov2 have a co-crystallization molecule and has an adjacent ligand ¿orthosteric site? (not 8f4y)
- From 8aq6, 8aqi has mod, 5ibo has a fatty acid
- From 7gqu, all are mods

In [40]:
no_apo = extra_filt_df[ extra_filt_df[("apo", "any_apo_chain")] == False ]

In [45]:
extra_filt_df = pd.concat((
    extra_filt_df[extra_filt_df[("apo", "any_apo_chain")] == True],
    no_apo[(no_apo[("allodb", "pdb")] == "9dnm")],
    no_apo[(no_apo[("allodb", "pdb")] == "8qni") & (no_apo[("apo", "pdb")].isin(["3zni", "8vw4"]))],
    no_apo[(no_apo[("allodb", "pdb")] == "8f4s") & (no_apo[("apo", "pdb")] != "8f4y")]
))

##### Multiple sites

In [49]:
{
    p: {
        sid: sid in extra_df[("allodb", "site_id")].unique()
        for sid in sids
    }
    for p, g in extra_df.groupby(("allodb", "pdb"))
    for sids in [
        extra_df.loc[lambda x: x[("allodb", "pdb")] == p]
        .loc[:, ("allodb", "site_id")]
        .unique(),
    ]
    if len(sids) > 1
}

{}

None.

<br>

##### Heteromers

In [50]:
[
    p for p, g in extra_df.groupby(("allodb", "pdb"))
    if len(
        extra_df.loc[lambda x: x[("allodb", "pdb")] == p]
        .loc[:, ("allodb", "uniprot")]
        .unique()
    ) > 1
]

[]

None

<br>

## Cifs and chains

In [18]:
Cif.path = extra_apos_structures_path
Cif.original_cifs_path = extra_apos_original_cifs_path # <pdb>_updated.cif.gz
Pdb.path = extra_apos_structures_path

In [19]:
aposf = f"{extra_apos_path}/apos.pkl"

In [79]:
apos = {}

for holo, rows in  tqdm(extra_filt_df.groupby(("allodb", "pdb"), sort=False)):
    apos[holo] = {}
    print(holo)
    for apo, g in tqdm(rows.groupby(("apo", "pdb"), sort=False), total=len(rows)):
        assert len(g) == 1, "What"
        pdb = Pdb(apo)
        
        origciff = f"{extra_apos_original_cifs_path}/{apo}_updated.cif.gz"
        if not os.path.isfile(origciff):
            with open(origciff, "wb") as f:
                f.write(pdb.cif._cif_content)

        # ASSUMING ALL ARE MONOMERS
        apo_chains = tuple(sorted(
            [
                c
                for c, cd in g[("apo", "ligands")].item().items() 
                if not cd[("apo", "has_lig")]
            ] 
            or g[("apo", "label_asym_id")].item()
        ))
        apos[holo][apo] = apo_chains[0]


with open(aposf, "wb") as f:
    pickle.dump(apos, f)
apos

  0%|          | 0/7 [00:00<?, ?it/s]

7gqu

  0%|          | 0/5 [00:00<?, ?it/s]

7yg5

  0%|          | 0/3 [00:00<?, ?it/s]

8aq6

  0%|          | 0/9 [00:00<?, ?it/s]

8f4s

  0%|          | 0/70 [00:00<?, ?it/s]

8qni

  0%|          | 0/5 [00:00<?, ?it/s]

8v81

  0%|          | 0/19 [00:00<?, ?it/s]

9dnm

  0%|          | 0/15 [00:00<?, ?it/s]

{'7gqu': {'7gqt': 'A', '8yle': 'A', '6yhr': 'A', '8pfp': 'A', '7gqs': 'A'},
 '7yg5': {'8epm': 'A', '7xlq': 'A', '8epl': 'A'},
 '8aq6': {'7snx': 'A',
  '7snr': 'A',
  '7sny': 'A',
  '7snw': 'A',
  '7sns': 'A',
  '7vsx': 'A',
  '8aqh': 'A',
  '5b0u': 'A',
  '7snt': 'A'},
 '8f4s': {'6wq3': 'A',
  '7jz0': 'A',
  '7lw4': 'A',
  '8tyj': 'A',
  '9gtf': 'A',
  '6wvn': 'A',
  '9eun': 'A',
  '7bq7': 'A',
  '8ot0': 'A',
  '9gs4': 'A',
  '8rze': 'A',
  '7lw3': 'A',
  '7jhe': 'A',
  '9emv': 'A',
  '8rva': 'A',
  '7r1t': 'A',
  '7koa': 'A',
  '6wrz': 'A',
  '7r1u': 'A',
  '6yz1': 'A',
  '7ult': 'A',
  '8rv8': 'A',
  '6wjt': 'A',
  '8s8x': 'A',
  '6xkm': 'A',
  '6w61': 'A',
  '8rv9': 'A',
  '6wkq': 'A',
  '9p6p': 'A',
  '8otr': 'A',
  '8rzc': 'A',
  '7c2j': 'A',
  '8s8w': 'A',
  '8rv4': 'A',
  '8c5m': 'A',
  '9guf': 'A',
  '7c2i': 'A',
  '8osx': 'A',
  '8rv7': 'A',
  '7jpe': 'A',
  '7l6r': 'A',
  '7jyy': 'A',
  '6w4h': 'A',
  '9grq': 'A',
  '9emj': 'A',
  '8vuo': 'A',
  '7l6t': 'A',
  '7jib': 'A',
  '8a23': 'A',
  '6wks': 'A',
  '6w75': 'A',
  '8rzd': 'A',
  '9gwo': 'A',
  '8rvb': 'A',
  '8rv5': 'A',
  '9gud': 'A',
  '8rv6': 'A',
  '8ov2': 'A',
  '8oto': 'A',
  '9grp': 'A',
  '9q8h': 'A',
  '8bsd': 'A',
  '8ov1': 'A',
  '9guy': 'A',
  '8ov4': 'A',
  '9gny': 'A',
  '9gue': 'A',
  '9eml': 'A',
  '8bzv': 'A',
  '8ov3': 'A'},
 '8qni': {'3pfv': 'A', '3vgo': 'A', '8vw5': 'A', '8vw4': 'A', '3zni': 'A'},
 '8v81': {'6o1v': 'A',
  '9dw8': 'A',
  '7svr': 'A',
  '8gls': 'A',
  '8eio': 'A',
  '8v7z': 'A',
  '8eiq': 'A',
  '5uak': 'A',
  '8fzq': 'A',
  '9dw7': 'B',
  '9dw5': 'A',
  '6msm': 'A',
  '9dw4': 'B',
  '8eig': 'A',
  '7sv7': 'A',
  '7svd': 'A',
  '8ej1': 'A',
  '9dw9': 'A',
  '6o2p': 'A'},
 '9dnm': {'9cx9': 'D',
  '9dng': 'C',
  '6u1n': 'B',
  '8hst': 'A',
  '8ja3': 'A',
  '4jqi': 'A',
  '6kl7': 'A',
  '8j8z': 'A',
  '9bt8': 'E',
  '9cx3': 'E',
  '8hsv': 'A',
  '8gp3': 'A',
  '8i0q': 'A',
  '8i0n': 'A',
  '8go8': 'A'}}

In [80]:
apos

{'7gqu': {'7gqt': 'A', '8yle': 'A', '6yhr': 'A', '8pfp': 'A', '7gqs': 'A'},
 '7yg5': {'8epm': 'A', '7xlq': 'A', '8epl': 'A'},
 '8aq6': {'7snx': 'A',
  '7snr': 'A',
  '7sny': 'A',
  '7snw': 'A',
  '7sns': 'A',
  '7vsx': 'A',
  '8aqh': 'A',
  '5b0u': 'A',
  '7snt': 'A'},
 '8f4s': {'6wq3': 'A',
  '7jz0': 'A',
  '7lw4': 'A',
  '8tyj': 'A',
  '9gtf': 'A',
  '6wvn': 'A',
  '9eun': 'A',
  '7bq7': 'A',
  '8ot0': 'A',
  '9gs4': 'A',
  '8rze': 'A',
  '7lw3': 'A',
  '7jhe': 'A',
  '9emv': 'A',
  '8rva': 'A',
  '7r1t': 'A',
  '7koa': 'A',
  '6wrz': 'A',
  '7r1u': 'A',
  '6yz1': 'A',
  '7ult': 'A',
  '8rv8': 'A',
  '6wjt': 'A',
  '8s8x': 'A',
  '6xkm': 'A',
  '6w61': 'A',
  '8rv9': 'A',
  '6wkq': 'A',
  '9p6p': 'A',
  '8otr': 'A',
  '8rzc': 'A',
  '7c2j': 'A',
  '8s8w': 'A',
  '8rv4': 'A',
  '8c5m': 'A',
  '9guf': 'A',
  '7c2i': 'A',
  '8osx': 'A',
  '8rv7': 'A',
  '7jpe': 'A',
  '7l6r': 'A',
  '7jyy': 'A',
  '6w4h': 'A',
  '9grq': 'A',
  '9emj': 'A',
  '8vuo': 'A',
  '7l6t': 'A',
  '7jib': 'A',
  '8a23': 'A',
  '6wks': 'A',
  '6w75': 'A',
  '8rzd': 'A',
  '9gwo': 'A',
  '8rvb': 'A',
  '8rv5': 'A',
  '9gud': 'A',
  '8rv6': 'A',
  '8ov2': 'A',
  '8oto': 'A',
  '9grp': 'A',
  '9q8h': 'A',
  '8bsd': 'A',
  '8ov1': 'A',
  '9guy': 'A',
  '8ov4': 'A',
  '9gny': 'A',
  '9gue': 'A',
  '9eml': 'A',
  '8bzv': 'A',
  '8ov3': 'A'},
 '8qni': {'3pfv': 'A', '3vgo': 'A', '8vw5': 'A', '8vw4': 'A', '3zni': 'A'},
 '8v81': {'6o1v': 'A',
  '9dw8': 'A',
  '7svr': 'A',
  '8gls': 'A',
  '8eio': 'A',
  '8v7z': 'A',
  '8eiq': 'A',
  '5uak': 'A',
  '8fzq': 'A',
  '9dw7': 'B',
  '9dw5': 'A',
  '6msm': 'A',
  '9dw4': 'B',
  '8eig': 'A',
  '7sv7': 'A',
  '7svd': 'A',
  '8ej1': 'A',
  '9dw9': 'A',
  '6o2p': 'A'},
 '9dnm': {'9cx9': 'D',
  '9dng': 'C',
  '6u1n': 'B',
  '8hst': 'A',
  '8ja3': 'A',
  '4jqi': 'A',
  '6kl7': 'A',
  '8j8z': 'A',
  '9bt8': 'E',
  '9cx3': 'E',
  '8hsv': 'A',
  '8gp3': 'A',
  '8i0q': 'A',
  '8i0n': 'A',
  '8go8': 'A'}}

# Predictions

In [20]:
import os, sys, subprocess
import pandas as pd
from tqdm.notebook import tqdm

In [21]:
sys.path.append("..")

In [22]:
from predict import \
get_cif, get_clean_pdb, Cif, Site, get_pockets, Pocket, \
get_pdb_features, get_pockets_features, \
prepare_data, model, view_pockets
# get_features

/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/autogluon/common/utils/utils.py:78: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
INFO:.prody:ProDy is configured: verbosity='none'
/home/fnerin/miniconda3/envs/allopockets/lib/python3.11/site-packages/Bio/Application/__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(

In [23]:
os.makedirs(f"{extra_apos_path}/predictions", exist_ok=True)

In [24]:
holos_ups = {
    '7gqu': 'Q14191',
    '7yg5': 'Q15878',
    '8aq6': 'Q9GV45',
    '8f4s': 'P0DTD1',
    '8qni': 'Q13191',
    # '8uk6': 'A0A1D8PQM9',
    '8v81': 'P13569',
    '9dnm': 'P29066',
    '8jp0': 'P32418'
} # already with -2 correction

In [25]:
overlapsf = f"{extra_apos_path}/predictions.pkl"

In [28]:
if os.path.isfile(overlapsf):
    overlaps = pd.read_pickle(overlapsf)
else:
    overlaps = {}

# Ran with a .py script

for holo, aposd in tqdm(apos.items()):
    overlaps[holo] = {}
    
    holocif = Cif(holo, f"../training_data/7.Extra_set/cifs/{holo}.cif")
    u = holos_ups[holo]
    umin, umax = next(((min(us), max(us)) for us in (holocif.residues.query(f"pdbx_sifts_xref_db_acc == '{u}'")["pdbx_sifts_xref_db_num"].astype(int),)))
    realsite = extra_holos_sites[holo][0]["site"][["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]].query(f"pdbx_sifts_xref_db_acc == '{u}'")

    for apo, chain in tqdm(aposd.items()):
        if apo in os.listdir("../training_data/8.Apos/Extra_set/features"):
            continue
            
        origciff = f"{extra_apos_original_cifs_path}/{apo}_updated.cif.gz"
        
        path = f"{extra_apos_path}/predictions/{apo}"
        os.makedirs(path, exist_ok=True)
        os.system(f"ln -s ../../origcifs/{apo}_updated.cif.gz {path}/")

        apocif = Cif(apo, origciff)
        seqmin, seqmax = (
            apocif.atoms
            .loc[lambda d: (
                d["pdbx_sifts_xref_db_acc"].eq(u) 
                & pd.to_numeric(d["pdbx_sifts_xref_db_num"], errors="coerce").between(umin, umax)
            )]
            .iloc[[0,-1]]["label_seq_id"].astype(int).to_list()
        )
        apocif.atoms = apocif.atoms.loc[lambda d: (
            pd.to_numeric(d["label_seq_id"], errors="coerce").between(seqmin, seqmax)
        )]

        assert len(apocif.residues.pdbx_sifts_xref_db_acc.unique()) == 1, "What"
        clean_pdb = get_clean_pdb(apocif, chain, path)

        predsf = f"{path}/preds.pkl"
        if not os.path.isfile(predsf):
            pockets = get_pockets(
                clean_pdb,
                out=sys.stdout,
                path=path
            )
            pockets["pdb"] = clean_pdb.entry_id
        
            for feat in ['features', 'transferentropy', 'hhblits']:
                subprocess.run(f"python ../gradio/{feat}.py {clean_pdb.entry_id} {path}", shell=True, check=True)
        
            features = get_pdb_features(
                clean_pdb,
                sites = [pd.DataFrame(columns=clean_pdb.residues.columns),],
                features_path = path
            )
        
            pockets_features = get_pockets_features(
                clean_pdb,
                pockets,
                features,
                path=path
            )
        
            data = prepare_data(pockets_features)
        
            preds = model.predict_proba(data)[[1]].sort_values(1, ascending=False).rename(columns={1: "Allosteric score"})
            preds.index = preds.index.map(lambda x: x.split("_")[-1])
            
            preds.to_pickle(predsf)
        else:
            preds = pd.read_pickle(predsf)

        topp = preds.iloc[0].name
        
        site_in_apo = clean_pdb.residues.merge(realsite) # hopefully will preserve all columns of clean_pdb.residues

        merge = site_in_apo.merge(
            Pocket(f"{path}/{clean_pdb.entry_id}/{clean_pdb.entry_id}_out/pockets/{topp}_atm.cif").residues
        )
        
        overlaps[holo][apo] = {
            "pocket": topp,
            "overlap": len(merge) / len(site_in_apo),
            "site": site_in_apo,
            "merge": merge
        }

        pd.to_pickle(overlaps, overlapsf)

## Results

- For **7gqu** all 4 structures have an acceptable pocket. 8pfp's pocket includes the allo site but is very big, and 7gqt/7gqs are small pockets within the allo site. They all have a bound ligand in a different site and AlloPockets is successful at discriminating.
- For **7yg5** the results are still incorrect and moreover they are not consistent.
- For **8aq6**, the results are mostly negative as with the originally-chosen apo, predicting the orthosteric site. For 7vsx and 7sny the predicted pocket extends a bit through the surface.
- For 8f4s (so far), predictions are consistent with the originally-chosen apo; but the pocket is the one that contains the ortho ligand and extends a bit (~35% of residues) to the allosteric site.
- For **8v81**, pockets are wrongly predicted and the only two with high overlap are enormous pockets spanning the whole structure.
- For 9dnm, results aren't great either and the ones showing overlap are again big pockets and mostly do not cover the surface-shallow site, but come from behind or from the side. The pockets would also need to be compared with the non-annotated pocket.
- For **8qni** the results are good, with 3/4 apos (+ original apo) being correct predictions.

In [26]:
apos = pd.read_pickle(aposf)
dict(sorted({k: len(v) for k, v in apos.items()}.items(), key=lambda x: x[1], reverse=True))

{'8f4s': 70,
 '8v81': 19,
 '9dnm': 15,
 '8aq6': 9,
 '7gqu': 5,
 '8qni': 5,
 '7yg5': 3}

In [27]:
overlaps = pd.read_pickle(overlapsf)
dict(sorted({k: len(v) for k, v in overlaps.items()}.items(), key=lambda x: x[1], reverse=True))

{'8f4s': 68,
 '8v81': 17,
 '9dnm': 14,
 '8aq6': 7,
 '7gqu': 4,
 '8qni': 4,
 '7yg5': 2}

**8v81**
- 6o1v: top4 18%
- 7svd: -
- 7sv7: top3 8%
- 8eig: top3 27%
- 6msm: top5 24%
- 9dw9: top5 8%
- 9dw5: top6 27%
- 8v7z: top3 16%
- 8eio: top5 7%
- 8gls: top4 25%
- 7svr: top2 23%
- 9dw8: top2 54%
- 8eiq: top4 40%
- 6o2p: top5 19%
- 9dw7: top3 63%
- 9dw4, 8ej1

**7yg5**
- 8epm:
    - top1: could coincide with modulator in 8F0Q (chimera Na channel) when taking account symmetry
    - top2: -
    - top3: -
    - top4: pore
    - top5: -
- 8epl:
    - top1: -
    - top2: -, similar to top3 from 8epm
    - top3: -, similar to top2 from 8epm
    - top4: coincides with modulator in 8QUD

In [150]:
holo = "7gqu"
pd.DataFrame(overlaps[holo]).T.sort_values("overlap")

,pocket,overlap,site,merge
7gqt,pocket5,0.068966,label_comp_id label_asym_id label_entity_id...,label_comp_id label_asym_id label_entity_id ...
7gqs,pocket4,0.068966,label_comp_id label_asym_id label_entity_id...,label_comp_id label_asym_id label_entity_id ...
8yle,pocket6,0.448276,label_comp_id label_asym_id label_entity_id...,label_comp_id label_asym_id label_entity_id...
8pfp,pocket1,0.586207,label_comp_id label_asym_id label_entity_id...,label_comp_id label_asym_id label_entity_id...

In [155]:
pdb = "8pfp"
toppocket = 1

preds = pd.read_pickle(f"pdb_ensemble/predictions/{pdb}/preds.pkl").iloc[:5]; print(preds)
cif = Cif(pdb, f'pdb_ensemble/predictions/{pdb}/{pdb}.cif')
view_pockets(
    cif,
    pockets={preds.iloc[toppocket-1].name: {"color": "green"}},
    site_residues=cif.residues.merge(
        extra_holos_sites[holo][0]["site"][["pdbx_sifts_xref_db_acc", "pdbx_sifts_xref_db_num"]]
    ),
    path=f'pdb_ensemble/predictions/{pdb}',
)

          Allosteric score
pocket1           0.610110
pocket3           0.185555
pocket2           0.025168
pocket4           0.002601
pocket10          0.001652

PDBeMolstar(bg_color='#F7F7F7', color_data={'data': [{'struct_asym_id': 'A', 'representation': 'cartoon', 'rep…

In [66]:
apos = pd.read_pickle(f"{extra_apos_path}/apos.pkl")

In [73]:
dict(sorted({k: len(v) for k, v in apos.items()}.items(), key=lambda x: x[1], reverse=True))

{'8f4s': 70,
 '8v81': 19,
 '9dnm': 15,
 '8aq6': 9,
 '7gqu': 5,
 '8qni': 5,
 '7yg5': 3}

In [98]:
apos["8v81"]

{'6o1v': 'A',
 '9dw8': 'A',
 '7svr': 'A',
 '8gls': 'A',
 '8eio': 'A',
 '8v7z': 'A',
 '8eiq': 'A',
 '5uak': 'A',
 '8fzq': 'A',
 '9dw7': 'B',
 '9dw5': 'A',
 '6msm': 'A',
 '9dw4': 'B',
 '8eig': 'A',
 '7sv7': 'A',
 '7svd': 'A',
 '8ej1': 'A',
 '9dw9': 'A',
 '6o2p': 'A'}